### ISSUE TITLE
Custom Table of Content Icons Not Displaying on Uncategorized Articles

### ISSUE THREAD

**Issue by GeekzGamingz** [worldanvil/worldanvil-bug-tracker#10]
**World Anvil Username**:
GeekzAnonymous

**Related URLS (add URLs of the pages that do not work!)**:
https://www.worldanvil.com/w/GeekzAnonymous-Oryth

**Describe the bug**
Whenever I add a custom icon using the new feature, it only shows in categorized articles. When I have an uncategorized article it defaults to the original.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/42735252/109426527-22d30780-79bc-11eb-84e0-f64d27c50b6f.JPG)
![Capture2](https://user-images.githubusercontent.com/42735252/109426529-249ccb00-79bc-11eb-9f27-cb146df26707.JPG)

**Comment by iamromeo** [comment]
Fixed

**Comment by GeekzGamingz** [comment]
Excellent work! Thanks, Dimi!!
