### ISSUE TITLE
Top part of 'new article' widget pop-up obscured/off screen

### ISSUE THREAD

**Issue by JEDI-Rialla** [worldanvil/worldanvil-bug-tracker#100]
**World Anvil Username**: JEDI_Rialla-Sheng

**World / Campaign / RPG Character / Manuscript Title**:  Seo Vere Werlyd 

**Feature**: Quick Content Creation / Quick content Menu

**Related URLS** (To public & visible pages add screenshots otherwise): 
![Screenshot 2021-03-25 18 57 01](https://user-images.githubusercontent.com/81393516/112555206-1c0e9900-8d9e-11eb-83db-301d52b24819.png)

**Describe the Issue**
The last day or two, when I have tried to use the Quick Actions Menu, the top of the menu has been off screen/I can't access or see it.  I've tried refreshing and logging out and then back in, but the issue has remained.  I took a screen cap of it and added teh screen cap to my WorldAnvil images, and also uploaded it onto my deviantArt in case you couldn't access it (I can upload it to my gDrive as well, should you prefer that)

**To Reproduce**
1. Go to my World Anvil page, articles, images, etc
2. Click on the + sign/Quick Access Menu, and then any of the tools in the menu
3. the widget/pop-up comes up, but the top bar is off screen

**Expected behavior**
I've been using the Quick Actions Menu for a while, and loved that I could make quick one sentence place-holder articles and the like as I worked, but with how the menu is... glitching I guess is the term...  I can't type in a title for the article or choose a category

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Screenshot 2021-03-25 18 57 01](https://user-images.githubusercontent.com/81393516/112555273-419ba280-8d9e-11eb-886f-d8b717215576.png)

**Comment by iamromeo** [comment]
There was nothing changed on World Anvil regarding the height of this. 
Having said that, I took the opportunity to slim this down to make it more accessible to small resolution screens. 
It will be deployed later on today

**Comment by JEDI-Rialla** [comment]
Huh, I wonder if it was just my computer glitching out then.
I'm sorry to have caused you needless work, but thank you for your
fantastic site.  I love working on it and the community

-Jackie

**Comment by Kordishal** [comment]
It is just that on some specific screen sizes the widget is too big, but doesn't change to mobile format yet. So it was always an issue on really small resolutions.(or zoomed in as you have)

**Comment by Kordishal** [comment]
@iamromeo 

Not sure where this comes from but you broke it on my end now:

![image](https://user-images.githubusercontent.com/14262536/112625116-c46c3e00-8e2e-11eb-8dc3-c0d9a875a289.png)

![image](https://user-images.githubusercontent.com/14262536/112625204-e2d23980-8e2e-11eb-9b05-4f99f3da34c2.png)

**Comment by JEDI-Rialla** [comment]
...I had forgotten I had it zoomed in ^^;;  I have severe vision problems
and need large text, but I'd zoomed in so long ago that I forgot I did so
^^;;
Still, thank you again!!

**Comment by iamromeo** [comment]
@Kordishal .page-undefined is not a WA class, this is injected in there for somewhere else.
