### ISSUE TITLE
Can't load my Timeline

### ISSUE THREAD

**Issue by pettersoderberg** [worldanvil/worldanvil-bug-tracker#1000]
**World Anvil Username**: AhlbergSoderberg

**World / Campaign / RPG Character / Manuscript Title**: Dick World

**Feature**:  Timeline

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/world/timeline/48934f82-022c-4297-ba96-ce643faefa97/edit

**Describe the Issue**
A clear and concise description of what the issue is.

The issue is that I can't open my timeline "4 Wizards from the Beginning of Time" for editing. The site crashes before the timeline opens.

**To Reproduce**
1. Go to 'Timeline'
2. Click on 'The Tool icon next to the timeline 4 Wizards from the Beginning of Time'
3. See error

**Expected behavior**

I expected the timeline to open for editing.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/91053794/164969174-66b7f95f-8043-4307-913b-ca8d0ba52677.png)
![image](https://user-images.githubusercontent.com/91053794/164969201-66c278b0-281d-4f86-aa3a-5a766473dad9.png)

**Comment by Kordishal** [comment]
The timelines is private or a draft, so I cannot confirm if this happens to anyone else. Does the issue persist?

What are the last things you have added to the timeline? Is it a particularly large timeline? Are there many images?

**Comment by iamromeo** [comment]
Closed due to inactivity
