### ISSUE TITLE
Bug Report: Uninteractive articles

### ISSUE THREAD

**Issue by Banner223** [worldanvil/worldanvil-bug-tracker#1001]
**World Anvil Username**: Ryuujin223

**World / Campaign / RPG Character / Manuscript Title**: Atronach

**Feature**: Article

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/atronach-ryuujin223/a/kordanin-species

**Describe the Issue**
In world viewing mode, the article can't be interacted with - the text can't be highlighted, the hyperlinks can be clicked and so on. This applies the the article itself, not the page - it is still possible to click the UI buttons. This started happening at some point while the article was getting bigger and bigger. This issue doesn't apply to small articles.

**To Reproduce**
1. Go to world view mode.
2. Click on the "Kordanin" article (or any significantly long article).
3. Scroll down to the text in the article and try to highlight and interact with it.

**Expected behavior**
It's supposed to be possible to highlight the text and interact with the article's hyperlinks.

**Screenshots**
Not applicable, screenshots can't showcase this error.

**Comment by Kordishal** [comment]
You have some kind of unclosed or unopened BBCode tag in your article. 

Common culprits are [center], [justify] and [in] BBCodes.
