### ISSUE TITLE
Whiteboard block change glitch

### ISSUE THREAD

**Issue by Deleyna** [worldanvil/worldanvil-bug-tracker#1002]
**World Anvil Username**: Deleyna

**World / Campaign / RPG Character / Manuscript Title**: Whiteboard "the children" - note, I have moved on with the project, so error is no longer there

**Feature**:  article link, multiple blocks, change from default view to avatar view while multiple selected

**Related URLS** (To public & visible pages add screenshots otherwise):
![image](https://user-images.githubusercontent.com/4100767/164988358-63b74bf3-63d6-4503-8b7e-6c4695d876d5.png)

**Describe the Issue**
I'm working on a rough geneology of a series of characters (not quite right for family tree...yet, still drafting). I had added links to articles using the lovely big green button, but was running out of space. Discovered that I could change the block to an avatar view. Changed Drenil - the only one with an image. Then selected the whole set of them and changed them to avatar view at the same time.

All of them changed to Drenil.

**To Reproduce**
1. Add two character articles to the whiteboard in the default type view.
2. select both
3. right click and choose "type->avatar"
4. both will now be avatars... of the same article.

**Expected behavior**
I expected to have two avatars linked to two different articles.

**Screenshots**
1:
![image](https://user-images.githubusercontent.com/4100767/164988563-b53c6043-7295-4b94-af9e-45083c5a09a3.png)
2-3:
![image](https://user-images.githubusercontent.com/4100767/164988658-dcf5a833-8cee-4d9c-b1cf-7d07fdfbc6f6.png)
4:
![image](https://user-images.githubusercontent.com/4100767/164988669-857f7d36-eafe-4735-a72b-de37c8e3cf3c.png)

Expected:
![image](https://user-images.githubusercontent.com/4100767/164988692-966a3d6b-c853-4f0e-a311-b4ad4d8d74c1.png)

Thanks! Loving the feature! Any plans to integrate with manuscripts?

**Comment by Duranzno** [comment]
Thank you for noticing this bug! I just updated a fix for this and is already in production!

**Comment by Deleyna** [comment]
Thanks!
