### ISSUE TITLE
Typo on pricing page for whiteboards.

### ISSUE THREAD

**Issue by the-composer** [worldanvil/worldanvil-bug-tracker#1003]
**World Anvil Username**: TheComposer

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/pricing

**Describe the Issue**
For the whiteboards feature description, there's a typing error, "Creat" which should be "Create".

**To Reproduce**
1. Go to (https://www.worldanvil.com/pricing)
2. Read what Whiteboard involves
3. Creat facepalm
4. Add an 'e' at the end of the word.
5. Achieve glorious victory

**Screenshots**
![image](https://user-images.githubusercontent.com/33100501/164991722-e7c521df-2071-4c39-96e5-7ce8e7170383.png)

**Comment by iamromeo** [comment]
Thank you for the heads - it is fixed and it will be deployed with the next update :)
