### ISSUE TITLE
Campaign Plot Page Will Not Open

### ISSUE THREAD

**Issue by Alfisol** [worldanvil/worldanvil-bug-tracker#1005]
**World Anvil Username**:  Grandmaster Solidago

**World / Campaign / RPG Character / Manuscript Title**: War of Entrophy
**Feature**: 

**Related URL:   https://www.worldanvil.com/heroes/campaign/plot/list

**Describe the Issue**
I was working on my Plot articles and then suddenly I could not access the page.  I received "This Page is not Working" error.   see link above. 

**To Reproduce**
Click on the Plot link on the left hand toolbar under the campaign section

**Expected behavior**
link should take you to my Plots page

**Screenshots**

**Comment by Kordishal** [comment]
The plot page fails when there is a loop in the in the plots structure. It can also cause issue when your master plot has a parent plot. You can fix this by removing the loop or problematic connection.

Duplicte of #810
