### ISSUE TITLE
Unable to delete a world

### ISSUE THREAD

**Issue by Kalacia** [worldanvil/worldanvil-bug-tracker#1006]
**Username**: Kalacia

**World name:** Duo
**World name:** Twoopoly

**Feature**:  World deletion

**Describe the Issue**
I am unable to delete a world, I get a 404 when I attempt to.

**To Reproduce**
1. Go to 'Home>World>Settings>Delete world (confirm)'
2. Receive 404 page
3. World is not deleted

**Expected behaviour**
I would expect the world to be deleted

** Browser version **
Chrome Version 100.0.4896.88 (Official Build) (64-bit)

**Comment by Kordishal** [comment]
This is usually related to one of the following resources still present in the world to be deleted:

- Delete campaigns in the world
- Expel RPG Characters from the campaign
- Delete manuscripts associated with the world
- Remove subscribers & authors from the world
- Delete subscriber groups from the world

After this the world should delete.

**Comment by iamromeo** [comment]
Closed due to inactivity
