### ISSUE TITLE
Typo in Meta Character Agency

### ISSUE THREAD

**Issue by motzy** [worldanvil/worldanvil-bug-tracker#1007]
**World Anvil Username**: Motzy

**World**: Neverafter

**Feature**: World Meta

**Describe the Issue**
The helper text under **WHAT IS THE CHARACTER AGENCY LEVEL LIKE?** it reads:
_These motifs are a great way to help reinforce the feeling of your world, despite the different pacing and mood of locations or scenes within your story or campaign. They do not need to feature in every single session or scene._

I believe this is a left over from another prompt and probably should be somewhere else.

**To Reproduce**
1. Go to your world.
2. Click on Edit Meta.
3. Click on Theme
4. Scroll down to the third input.

**Expected behavior**
A text referring to Character Agency, not motifs.

**Comment by iamromeo** [comment]
Thank you for the heads up
