### ISSUE TITLE
Map content does not load after adding markers.

### ISSUE THREAD

**Issue by SipofRiviera** [worldanvil/worldanvil-bug-tracker#1009]
**Sip of Riviera**:

**Aerthera / none / none / Terras conhecidas de Aerthera**:

**Feature**: 

**[Related URLS](https://www.worldanvil.com/world/map/90e6d38e-99ee-471a-9d7b-b34cb5462d2b/edit)** 
Screenshots below

**The map became dark and all my work toward city creation seems to be gone. Just after posting another city description, the map turned black and cannot be seen in the edit tool, despite there being a loaded image to function as the map. Accessing it into the public view tool looks like all the work that was in progress is now lost**

**To Reproduce**
Steps made to reach the bug:
1. Gone to https://www.worldanvil.com/world/map/list
2. Clicked on "Edit" on the tool
3. Created a city with similar description to "Nova Meridian"
4. Map bugged and points cannot be accessed

**Expected behavior**
The expectation was to return to the edit screen normally

**Screenshots**
![image](https://user-images.githubusercontent.com/104560404/165718445-bfcd03c5-e4c3-4cdd-a85d-ecf736c587bf.png)

![image](https://user-images.githubusercontent.com/104560404/165718322-81ff6f1a-872d-487e-b2c4-c8238a1a5d33.png)

**Comment by Kordishal** [comment]
Hi! This is most likely related to a marker causing the map generation to crash but in this case the data is still there.
When you check the tab called MARKERS are there still markers there?

If it is, try to delete the latest marker you've created and see if that resolves the issue.

**Comment by SipofRiviera** [comment]
It worked! And the job is indeed preserved!

Thank you very much! 😃


Em qui., 28 de abr. de 2022 às 11:33, Jonas Waeber ***@***.***>
escreveu:
