### ISSUE TITLE
404 when creating Historical Entries

### ISSUE THREAD

**Issue by IsaacAThom** [worldanvil/worldanvil-bug-tracker#101]
**World Anvil Username**: Isaac Thompson

**World / Campaign / RPG Character / Manuscript Title**: Tiyu Amara

**Feature**: Timelines

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/world/timeline/history/new

**Describe the Issue**
When attempting to create a new historical entry, it takes me to a 404 page. No entry is created, regardless of world or timeline setups.

**To Reproduce**
1. Go to Timelines
2. Open any Timeline (Master or Parallel)
3. Click on 'Create New Historical Entry'

**Expected behavior**
That clicking on this button would create a new historical entry

**Comment by iamromeo** [comment]
No idea how this happened but it's now fixed.
