### ISSUE TITLE
Campaign Session Report Data Corruption

### ISSUE THREAD

**Issue by aetherith** [worldanvil/worldanvil-bug-tracker#1010]
**World Anvil Username**:
aetherith

**World / Campaign / RPG Character / Manuscript Title**:
Baerdan / Tales of Vediki / Session 10: Report

I'm happy to provide the internal UUID for the article if that would help as well but all my articles are set private.

**Describe the Issue**
After taking notes in an unordered list including a reference to a Secret I returned to the page several days later to find all of the additional text replaced with references to the Secret and all the other data lost.

**To Reproduce**
1. Create a Campaign Session Report
2. Take notes in the "Content" section using an unordered list.
3. Include a reference to a Secret associated with the Report in the list.
4. Leave article for several days.
5. Return to find all list elements after the Secret replaced with the Secret reference.

**Expected behavior**
Note data retained.

I know there's no way to recover the data but I'd like to help debug so that this doesn't happen again.

**Comment by Kordishal** [comment]
Hi aetherith!
That does not just happen after some time. My guess is you accidentally selected all the text and then add the secret reference overwriting your list. Unfortunately you are right that the data cannot be restored. To be sure that everything stored as you intended make sure to check the article after finishing it. If you have any further questions or different ideas of what could have happened feel free to answer here!

**Comment by aetherith** [comment]
Hey Kordishal,
So I can only report what I experienced. I wrote the article a week ago during the session, and inserted the secret reference midway through the list, continuing on with more list elements afterwards. I saved the article at the end of the session after reviewing the data and it looked correct. The sequence of events you describe makes sense if I had added in the secret at the end but that isn't the case, leaving me still confused. I reopened the article yesterday and found it corrupted in the manner described above. The only other thing that might be relevant is that I originally wrote the article using the basic WYSIWYG editor and the same day as I discovered the corruption changed my preferences to using the Euclid editor.

Thanks,
Thomas

**Comment by Kordishal** [comment]
The WYSIWYG editor could indeed be the culprit in this case. How exactly did you create the list in the editor? Which syntax did you use or did you add it via the buttons?

That editor will be reworked sometime in the future (hopefully soon) from scratch. Which is why bugs are not being addressed since the new version will no longer share the same code at all.

**Comment by Kordishal** [comment]
Yes Euclid is fully maintained and any bugs would be fixed immediately. But due to how it was built there really haven't been many at all since it was added.
