### ISSUE TITLE
Articletoc BBCode does not exclude inline statblocks from table of contents

### ISSUE THREAD

**Issue by shadowfalcon** [worldanvil/worldanvil-bug-tracker#1011]
Scholarmage

I have a test page visible at https://www.worldanvil.com/w/sundered-lands-scholarmage/a/toc-test-plot

When I attempted to use the [articletoc] BBCode to create a table of contents for a page which has inline D&D statblocks (eg [block:839121]), the table of contents included the stat names & values, "STR", "20+5" etc, plus "Actions", "Reactions", and "Suggested Environments". It did not exclude the contents of the statblock container.

To reproduce:
1. Create a D&D monster 5e statblock.
2. Create an article with standard header formatting in the text, [h3] etc.
3. Insert the statblock inline via the [block:] command
4. Insert the [articletoc] BBCode
5. View the page.

I would expect it to exclude the contents of the statblock container, even if the container uses header formatting for styling.
![articletoc result](https://user-images.githubusercontent.com/16592320/165946643-92a684b7-1e95-4b25-8f57-8741e2199259.JPG)

**Comment by iamromeo** [comment]
Sadly we have no control over that since it is has to do with the way the statblock was created.

**Comment by iamromeo** [comment]
I will see if we can add an exclusion but it is tricky
