### ISSUE TITLE
Cannot select subscriber groups after whiteboard is created.

### ISSUE THREAD

**Issue by erica447788** [worldanvil/worldanvil-bug-tracker#1012]
**World Anvil Username**: Girlhead

**World / Campaign / RPG Character / Manuscript Title**: For Alloria

**Feature**: Whiteboards

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I cannot change subscriber groups when I create a new whiteboard.  And a LOT of other issues that I can't mention here.

**To Reproduce**
1. I go to whiteboards
2. I click on new whiteboard
3. I enter a title
4. I choose one of my two subscriber groups
5. I click create whiteboard
6. I click on the name of the whiteboard in the upper left had corner of the screen next to the hamburger menu
7. I get the "edit whiteboard" menu
8. There is no option to change the subscriber group.

**Expected behavior**
I am supposed to have an option to change the subscriber group. It does not appear.  Please help!  This is a major issue and is affecting my campaign. 
![wb2](https://user-images.githubusercontent.com/83630349/166069070-8a721366-181c-4c67-8547-2853f886e444.PNG)

![wb1](https://user-images.githubusercontent.com/83630349/166069057-e48f6d2b-b63d-4a57-94a8-46880f2d8562.PNG)

**Screenshots**
![wb3](https://user-images.githubusercontent.com/83630349/166069078-6057d2a9-0065-4ddc-b5dd-87335c5de4e3.PNG)

If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Hi, a few questions to track down the issue:

What browser do you use?
Which operating system are you on? (Windows / Mac)
Can you check if this issue persists in a private / incognito window of your browser?

**Comment by Kordishal** [comment]
As for your other issues. Can you check if any of them are described in the other open issues about the Whiteboard:

https://github.com/worldanvil/worldanvil-bug-tracker/issues?q=is%3Aissue+is%3Aopen+label%3A%22Feature%3A+Whiteboards%22

This link will lead you to the list of all open issues with the whiteboards. Otherwise please make a bug report on them as well.

**Comment by erica447788** [comment]
I am using chrome browser.  I am on Windows 10.  I just checked and I get the same result using a incognito browser.

**Comment by erica447788** [comment]
Thank you- none of my issues are among those listed. I will make separate tickets.

**Comment by Duranzno** [comment]
I'm sorry for the delay. 
I thought I had answered and attended this issue 😅.
A bug fix has been released to fix this.

**Comment by Duranzno** [comment]
Should be fixed now
