### ISSUE TITLE
Translation bug in article creation

### ISSUE THREAD

**Issue by Assairessa** [worldanvil/worldanvil-bug-tracker#1013]
**World Anvil Username**:Mynameissofie

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: Article bug

**Related URLS** : (https://www.worldanvil.com/w/barovia-mynameissofie/a/blood-on-the-vine-landmark )

**Describe the Issue**
When creating or editing an article in all my worlds a translation bug appears after saving and is added to my flavour texts and is visable after viewing the article. When trying to remove the text it retuns after I have saved the article again.

**To Reproduce**
1. Go to create article
2. Write text in any of the main blocks
3. Save the article and make is visable
4. View article
5. The translation bug is now visable in my article
6. When going in to edit the article the bug is there
7. I remove it, save and view the article
8. Bug is back.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/104677122/166102069-2eab865d-dd28-4521-bbd0-eb13521a4491.png)
![image](https://user-images.githubusercontent.com/104677122/166102287-bbcf0ef1-ca51-4cca-8ddd-4372a07cbec9.png)

**Comment by Kordishal** [comment]
This is an issue with the plato editor. To resolve this switch to the Euclid editor. Check the guide below on how to do that.

https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors

As the Plato editor will be rebuilt from scratch issues will not be addressed until then.
