### ISSUE TITLE
Deleting Variables

### ISSUE THREAD

**Issue by SolarCat02** [worldanvil/worldanvil-bug-tracker#1015]
**World Anvil Username**: SolarCat02

**World / Campaign / RPG Character / Manuscript Title**: Vazdimet & Fillimet

**Feature**: Variables

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When deleting a single variable there is no confirmation, meaning a variable could be easily deleted by accident with a single click.

**To Reproduce**
1. Go to a variable category with at least one variable beneath it.
2. Click on the delete icon. 
3. The variable will be deleted

**Expected behavior**
For everything else a second click is required.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
This is not a bug :) THis is a lack of a feature
