### ISSUE TITLE
Dice roller on character pages not working

### ISSUE THREAD

**Issue by APence-XGEN** [worldanvil/worldanvil-bug-tracker#1016]
**World Anvil Username**: A14113

**World / Campaign / RPG Character / Manuscript Title**: Characters

**Feature**: Dice Roller

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/hero/0be4c39a-78f9-4bdf-a439-94041113b9eb

**Describe the Issue**
Dice rollers on hero/character page in the ajax-sheet-container below the health tracker aren't working. Tried on multiple accounts, multiple characters, and multiple browsers. 
The roller pops up as normal when directly viewing a sheet but on the hero page it acts as text.

**To Reproduce**
1. Go to the sheets tab of the character
2. Click on any of the dice roll buttons on any of the pages of the ajax-sheet-container

**Expected behavior**
I expect the dice roller to pop up in the corner with a result when a dice roll button is clicked

**Comment by iamromeo** [comment]
Thank you for the heads up - I will investigate ASAP

**Comment by iamromeo** [comment]
The cause of the issue has been identified - will be fixed within the next 72 hours

**Comment by APence-XGEN** [comment]
Looks like this is still an issue.

**Comment by iamromeo** [comment]
That is indeed still the case - we had a bit of a scheduling issue - it will be addressed asap

**Comment by iamromeo** [comment]
This is now tested and fixed

**Comment by APence-XGEN** [comment]
Awesome! Thank you!
