### ISSUE TITLE
Subscribers cannot click on articles through whiteboard

### ISSUE THREAD

**Issue by erica447788** [worldanvil/worldanvil-bug-tracker#1017]
World Anvil Username: Girlhead

World / Campaign / RPG Character / Manuscript Title: For Alloria

Feature: Whiteboards

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I have created a whiteboard.  When my subscribers view the whiteboard, they cannot click on and open the articles I have posted to the whiteboard.

**To Reproduce**
1. Go to whiteboard
2. Click on article

**Expected behavior**
When a subscriber tries to click on an article I've added to a whiteboard, it will not open.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Duranzno** [comment]
Cannot replicate
