### ISSUE TITLE
Issue with sizing of icons in whiteboards

### ISSUE THREAD

**Issue by erica447788** [worldanvil/worldanvil-bug-tracker#1018]
World Anvil Username: Girlhead

World / Campaign / RPG Character / Manuscript Title: For Alloria

Feature: Whiteboards

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I have added articles to my whiteboard and have used the "Icon" type.  When I view the article as a creator, I can see the full name of the article.  When I view the article as a subscriber, the name of the article is cut off.  I do not want to increase the size of the icon because I want all of the other icons to be the same size.  

**To Reproduce**
1. Edit whiteboard
2. Add Article
3. Change article type to "Icon"
4. View whiteboard as creator- can see full name of article
5. View article type as "subscriber" - sees part of article name

**Expected behavior**
Article name and size should be consistent no
![I see](https://user-images.githubusercontent.com/83630349/166166474-0c1efcb8-38f2-4d98-8874-bd6953e5ce36.PNG)
 matter who is viewing it.  
![subcriber sees](https://user-images.githubusercontent.com/83630349/166166481-adb938af-12bc-43c9-a3f5-ed91f797315b.PNG)

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Duranzno** [comment]
Released an update that fixes this issue

**Comment by erica447788** [comment]
Ok- same question as my other ticket- does this mean that the bug will be fixing this soon and I'm just supposed to wait, right?
