### ISSUE TITLE
When viewing a world, Writers can view the entire table of contents

### ISSUE THREAD

**Issue by N7Huntsman** [worldanvil/worldanvil-bug-tracker#1019]
**World Anvil Username**: N7Huntsman

**World**: Age of the Wolf

**Feature**: View World / World Codex / Access Management 

**Related URLS** (To public & visible pages add screenshots otherwise): **See screenshots.**

**Describe the Issue**
When viewing a world, the table of contents allows writers to view the category names and article titles of everything on the world, even items they did not create or were otherwise given access to through a subscriber group. They will get an 'Access Denied!' page if they attempt to go to the article or category page itself, but even titles can contain spoilers. Disabling the table of contents (naturally) prevents writers from viewing it.

(This is a revised and more accurate report stemming from feedback on #991)

**To Reproduce**
1. Join a world as a Writer.
2. From the Contributor's Dashboard, click 'View World'.
3. Under the table of contents, expand categories and view article titles.

**Expected behavior**
When viewing a world, I would expect that Writers cannot see the titles of articles and categories they did not create, provided they do not otherwise have permission to access to the articles themselves (such as public articles/categories or through a subscriber group). It's not desirable for the Writer to be able to view these article titles, as they can contain spoilers.

**Screenshots**
1. Add user to world as writer.
![1](https://user-images.githubusercontent.com/38633594/166415321-2e014508-aa07-4aa1-83be-c06964181081.PNG)

2. The user has created no articles, and cannot see any of the world from the Contributor Dashboard.
![7](https://user-images.githubusercontent.com/38633594/166415380-b8284e0f-49cf-4fbc-b1cc-3cf3b645c7b4.PNG)

3. When Viewing the World, they can view the full table of contents via the landing page.
![5](https://user-images.githubusercontent.com/38633594/166415432-01c33057-4995-4edc-b19f-d3c98f1c5275.PNG)

**Comment by iamromeo** [comment]
I am sorry but this works exactly as intended. Writers are by definition .... writers of the world and therefore can see everything in the world. The definition of a writer is someone that who is part of the writing team but has no access to PUBLISH on the world unless their work is approved by an Editor or Owner / Co-owner

**Comment by Kordishal** [comment]
If that is the case, then why do they not actually see everything... This seems a very arbitrary. They can only see the articles & categories names of private articles, but cannot actually access them at all.

They can only view public articles and articles that they are the author of. They cannot view articles which are private.

The same applies to Advanced Writers.

**Comment by N7Huntsman** [comment]
> I am sorry but this works exactly as intended. Writers are by definition .... writers of the world and therefore can see everything in the world.

I'm speaking strictly to the Writer role here, not Authors in general. From the [World Anvil main codex ](https://www.worldanvil.com/w/WorldAnvilCodex/a/coauthors#:~:text=Join%20World%20Anvil%20Codex%20Discord,cast%20of%20contributors%20and%20editors.)(emphasis mine):
>Writer can create articles as drafts, but they can't publish them nor edit existing articles. **They can't view private content unless they are also a subscriber**.

Additionally, note in the second screen shot that, as a Writer on the world, I cannot see any of these articles or categories (nor should I be able to, since they're private content). As a Writer, can't actually go to the articles or categories I can see the titles of in the table of contents, because I get an 'Access Denied' page (because I don't have access to them).

**Comment by iamromeo** [comment]
That is very odd - I will investigate ASAP. I will lean towards hiding the categories from the TOS but .... hmmmm - Will come back to you on that.

**Comment by Kordishal** [comment]
The WRITER & ADVANCED WRITER on the EDITOR side has just a list of all their articles. Only articles that they created or were assigned to as authors. Nothing else is visible.

On the VIEW side of the world they can see all articles & categories in the table of contents. Including the ones that are private and they do not have access to as subscribers. However, when they click on any of the private article links they go to the multipass page.

I believe it would be more consistent if they did not see the private articles & categories in the table of contents when they are not a subscriber.

**Comment by N7Huntsman** [comment]
> are you talking about the Dashboard or the View World side?

I'm talking about the View World side, as I can't see listings for any of those articles or categories from the Contributor Dashboard (as you can see in screenshot #2).

Those are private articles/categories that the Writer account didn't create and doesn't have access to via a subscriber group. The only the only place the Writer can see a listing for them is on the Table of Contents,  but get Access Denied if the Writer tries to click any of them. 

> I believe it would be more consistent if they did not see the private articles & categories in the table of contents when they are not a subscriber.

This was my thinking as well. It would make sense for the Writer to only be able to see articles and categories on the Table of Contents that they have access to, whether it's because they're public, the Writer has access through a subscriber group, or because they're things the Writer themselves created.
