### ISSUE TITLE
Article textarea fields have errant row of buttons below them

### ISSUE THREAD

**Issue by cyberianfrontier** [worldanvil/worldanvil-bug-tracker#102]
**World Anvil Username**: Buzzard

**World / Campaign / RPG Character / Manuscript Title**: Eastern Urik

**Feature**: Edit Article - Textarea

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
In the last couple of days, the article interface has changed a little for me.  On long text (textarea) fields I've got the normal formatting buttons at the top of those fields.  But there is also a row of buttons under those fields that looks to be the buttons that normally appear at the top of the single line text fields.  I haven't made any CSS changes to the admin side, and I haven't made any CSS changes in over a week.  This only started in the last few days.  These extra buttons aren't functional.

I also asked about this on the help discord channel and two other users were able to confirm that they are seeing this behavior as well.

**To Reproduce**
Steps to reproduce the behavior: Edit any article.

**Expected behavior**
Textarea fields and their buttons (above textarea) render and operate properly.  Below textarea field there is an extra row of buttons that aren't functional.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Screenshot 2021-03-26 072241](https://user-images.githubusercontent.com/81428411/112648666-f8336d80-8e06-11eb-87bc-6446d9f8ad4e.png)

**Comment by iamromeo** [comment]
All fixed. deployoment under way
