### ISSUE TITLE
Not Saving Text in Manuscripts

### ISSUE THREAD

**Issue by twistedfateslulu** [worldanvil/worldanvil-bug-tracker#1020]
**World Anvil Username**: UtterRando_Lulu

**World / Campaign / RPG Character / Manuscript Title**: Ingenoisus

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
In manuscripts for a new chapter, everything seems to go well while writing chapters and even the save icon comes up. However, when leaving the current chapter that is being worked on and entering another chapter, when coming back, all work disappeared and wasn't saved.

**To Reproduce**
1. Go to 'manuscripts'
2. Click on 'new text/chapter'
3. Write down something
4. Exit current text and then re-enter chapter
5. See error

**Expected behavior**
Text to be saved regardless of exiting/entering text to enter other chapters/text within same manuscript.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Hi, this doesn't happen just like that in every case. It might be possible that the save indicator appears even if the save failed.

The question then is what causes the fail. To figure that out we would need the content that causes this.

If this happens regardless of the content you add then it might be something wrong with just that manuscript. Or does it happen in a new manuscript as well?

**Comment by twistedfateslulu** [comment]
Thank you! 

I'll see if I'm causing this issue because regardless of the content, the text wasn't saving and giving a false save icon. I'll open a new manuscript to see if that fixes the issue.
