### ISSUE TITLE
Trying to delete a world.

### ISSUE THREAD

**Issue by WildFire3838** [worldanvil/worldanvil-bug-tracker#1021]
**World Anvil Username**: 

   [WildFire3838]

**World / Campaign / RPG Character / Manuscript Title**: 

   [Nordlands Campaign]

**Feature**: 

   [Delete World]

**Related URLS**): 

   https://www.worldanvil.com/world/55852673-1929-4d86-9689-7c6aaa1f14a0/edit

   https://www.worldanvil.com/world/55852673-1929-4d86-9689-7c6aaa1f14a0/delete

**Describe the Issue**

   [Upon confirming delete, the page goes to an error message: “ Thus you have reached the end of this world.” 404]

**To Reproduce**

   World Anvil Dashboard Page:

      [Nordlands] 
      [Settings] 
      [Delete World] 
      [Delete This World] (Window Popup: Are you sure you want to do this? This is a non-reversible action.)
      [Ok] 
      [Error 404]

**Expected behavior**
   [The World: Nordlands to be deleted from my World Anvil Page]

**Screenshots**
![Nordlands Dashboard](https://user-images.githubusercontent.com/104879071/166616847-f9aff445-3d58-4385-89d5-f5f940579860.JPG)
![Nordlands Settings Page](https://user-images.githubusercontent.com/104879071/166616862-1ef4aff6-a66d-43db-9fbf-b0387ee29e0b.JPG)
![Nordlands Delete World Clicked](https://user-images.githubusercontent.com/104879071/166616849-1a5d11d5-4396-4b8f-9e49-3b7e40ea6a91.JPG)
![Nordlands Popup Window (Delete World)](https://user-images.githubusercontent.com/104879071/166616854-8840d658-967d-497a-8ef3-c261b69b505a.JPG)
![Error 404](https://user-images.githubusercontent.com/104879071/166616586-12d0f211-a1f9-4da0-85d8-912d3320f40a.JPG)
![Thank you](https://user-images.githubusercontent.com/104879071/166616977-7d52e4ae-fdf1-4cf2-a2a3-d69f8f0c3e8d.JPG)

**Comment by iamromeo** [comment]
Hahahahaah - nice report! 

The chances are that you have some assigned subscriber groups and or authors
- Go here https://www.worldanvil.com/world/access/groups/list delete all
- Go here https://www.worldanvil.com/world/access/author/author/list delete all 
- Try deleting again

Then try again - if it doesn't work let me know :)

**Comment by WildFire3838** [comment]
Thanks!
I did what you suggested, still getting that error message. It's also
showing it to me when I try to delete the groups. I went and individually
deleted everyone out of the groups. Still not working.

**Comment by Kordishal** [comment]
Other things you can try:

- Delete associated manuscripts
- Delete associated campaigns
- Expel RPG Characters which are in that world

**Comment by WildFire3838** [comment]
Finally had time to sit down and try this, it worked. Thank you for your
help.
-Christopher Burns
