### ISSUE TITLE
Map Marker broken: [pin:flat_white_church1]

### ISSUE THREAD

**Issue by Tillerz** [worldanvil/worldanvil-bug-tracker#1022]
**World Anvil Username**: Tillerz

**World / Campaign / RPG Character / Manuscript Title**: Alana

**Feature**: Map Editing: Marker Icons

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

**To Reproduce**
1. Edit Map
2. Edit Marker
3. Hit Alt-Enter to get the marker icon list up.
4. Entry does show a "broken image" icons and also no name for the icon.

**Screenshot**

![image](https://user-images.githubusercontent.com/63370525/166670245-b5834b62-f620-4aa5-8511-b00304bd4be4.png)

**Comment by iamromeo** [comment]
I cannot repro this one and there shouldn't be an icon with an 1 at the end.
