### ISSUE TITLE
Dark Mode Makes Buttons Unreadable

### ISSUE THREAD

**Issue by Russlejimjam** [worldanvil/worldanvil-bug-tracker#1023]
**World Anvil Username**: RussleJimJams

**World / Campaign / RPG Character / Manuscript Title**: Any new D&D 5e Statblock Edit Page

**Feature**: Dark Mode

**Related URLS** (To public & visible pages add screenshots otherwise): See attached screenshot provided below or link to same picture via Google Photos: https://photos.app.goo.gl/4tBP5r9AxY15h7P8A

**Describe the Issue**
Toggling on dark mode changes the background of the buttons to a darker color, but the text doesn't change color, making it impossible to read the button icons.

**To Reproduce**
1. Go to any D&D 5e statblock page (race, monster, etc.) and edit the article
2. Click on the dark mode toggle at the top of the page if dark mode was not already enabled.
3. Ctrl+F5 to refresh the page clearing cached data.
4. Observe that the buttons icons/text and background are both dark colors, making them unreadable.

**Expected behavior**
If the buttons should change color with dark mode, then the icons/text should invert to contrast the background color of the buttons.

**Screenshots**
![2022-05-04 15_10_22-Photos](https://user-images.githubusercontent.com/104938941/166820032-9ea021b7-ce5d-4f3c-afea-9e1cddbe1540.png)

**Comment by iamromeo** [comment]
HEy @RussleJimJams this looks like an issue with the sheet you are using. Can you please let me know which sheet this is so I can tlak to the creator and fix this for you?

**Comment by Russlejimjam** [comment]
Hello,
This issue as described in my earlier submission occurs with the DnD5e
Monster statblock, Dnd5e NPC statblock, DnD5e Item statblock, DnD5e Spell
statblock, and DnD5e Race statblock.

Hopefully this clarifies where this issue is occurring. If you have any
other questions, please let me know.

Regards,
Jonathan

**Comment by Tillerz** [comment]
Should be fixed now.
