### ISSUE TITLE
Add the Storybook System to WA

### ISSUE THREAD

**Issue by RiverFang13** [worldanvil/worldanvil-bug-tracker#1024]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name (RPG SYSTEM)**: Storybook System
**List Name** (Name under which it should be listed on World Anvil): Storybook System
**World Anvil Username**: RiverFang

**Website**: https://www.worldanvil.com/w/isekai/c/storybook-system-category
*Note: Viewing the Storybook System rules requires joining a self-assigned subscriber group. Dimi should have access to view this and there will soon be a box to join on Isekai’s homepage. 

**Logo Image Link**:

**Logo Usage Terms (URL)**:

**Comment by iamromeo** [comment]
Done :)
