### ISSUE TITLE
Specific World name not working

### ISSUE THREAD

**Issue by ObscureDawn** [worldanvil/worldanvil-bug-tracker#1025]
**World Anvil Username**: RemixDawn

**World / Campaign / RPG Character / Manuscript Title**: Aceron

**Feature**: World Creation

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.
When trying to create a world named "Aceron" I get redirected to a 404 error page, I can make a world with any other name, and other people have been able to make a world with that name, but specifically that name gives me an error page, i talked to the support and the discord and was told just to send one of these
**To Reproduce**
1. Go to 'your worlds'
2. Click on 'create a new world'
3. Type Aceron into the world name 
4. Submit
5. See error

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
This means that name was used by you before and you deleted the world with that name. This creates a copyright lock on the username-world combination.

Dimitris has to manually unlock this, which he usually only does for paid accounts.

**Comment by ObscureDawn** [comment]
I had made an account prior to this one, but never actually used any of the
features, I forgot the login to it and eventually just gave up and made a
new account, from the moment I finished making the new account the error
was happening, it never once made it through to the actual world page.

**Comment by Kordishal** [comment]
You said the opposite in your last message though? What is it now?
