### ISSUE TITLE
Vote Amounts do not wrap on small screens

### ISSUE THREAD

**Issue by graylion-wa** [worldanvil/worldanvil-bug-tracker#1026]
**World Anvil Username**:

Graylion

**Feature**: 

Suggestion Voting Board

Thank you

![20220510_094121.jpg](https://user-images.githubusercontent.com/79761754/167642671-78b81c76-6ec5-4135-990c-306c94436932.jpg)

**Comment by iamromeo** [comment]
Thank you for letting me know. I have made the change and some additional fixes / changes on the UI
