### ISSUE TITLE
Nested containers fail if the first inner container is not visible.

### ISSUE THREAD

**Issue by DinosaurBob** [worldanvil/worldanvil-bug-tracker#1029]
**World Anvil Username**:

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):
https://worldanvil.com/w/world-of-cartyrion

**Describe the Issue**
Nesting subcontainers isn't working consistently.
Code in the World Introduction includes a set of nested subscriber-group subcontainers.  The outer container is for subscribers with the "Gamemasters" assignment.  There are two inner subcontainers - one for "ShowGamemasterContent" and one for "DontShowGMContent".  These two are self-assignable by anyone within the Gamemasters group.
If the first of the these is "true", the page appears as expected.  But if the first is false/second is true, then NEITHER group's code appears!

**To Reproduce**
1. Create three subscriber groups.  Assign person to groups 1 & 2
2. Code something like:
      [subcontainer1]
           [subcontainer2] Stuff here [/subcontainer]
           [subcontainer3] More stuff here [/subcontainer]
     [/subcontainer]
4. If assigned to 1 and 2; everything should work. But if assigned to 1 and 3, neither of the nested subcontainers should appear.

**Expected behavior**
Only the correct nested sub should appear.

**Screenshots**
Soullink said I don't need them.

**Comment by iamromeo** [comment]
@Kordishal this is a different potential issue - but the above works as expected.

**Comment by Kordishal** [comment]
So it is not intended for subcontainers to be nested?

**Comment by iamromeo** [comment]
Subcontontainers nesting was not never part of the purview of the feature. They are a simple way to gate a part of an article.

**Comment by Kordishal** [comment]
Ok then the second issue I mentioned isn't technically an issue either since it can only happen with nested subcontainers.
