### ISSUE TITLE
Euclid editor - appears blank.

### ISSUE THREAD

**Issue by Bladeswillfall** [worldanvil/worldanvil-bug-tracker#103]
**World Anvil Username**: 
Bladeswillfall

**World / Campaign / RPG Character / Manuscript Title**: 
The Lands of Errack

**Feature**: 
Euclid editor

**Related URLS** (To public & visible pages add screenshots otherwise): 
Screenshot 1: https://prnt.sc/10wa094,
Screenshot 2: https://prnt.sc/10wa1ru,

**Describe the Issue**
When loading the Configuration page under the "World Settings" menu (for example), my World Introduction / Description content disapears as does the editor, I've disabled my adblocks and VPN and the issue persists. 
The content and editor are visible when loading the page, however as soon as the page finishes loading, it disapears. If I switch to the Plato editor though, the issue disapears and it works fine.

**To Reproduce**
1. Have the Euclid editor enabled,
2. Click on any article to edit it,
3. Watch as the page loads the editor and then it disapears,

**Expected behavior**
I expected the editor to stay visible and for me to be able to edit my articles/content with the Euclid editor.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
Screenshot 1:
![image](https://user-images.githubusercontent.com/81432164/112661160-1ff9f400-8e4e-11eb-9916-056bab477899.png)

Screenshot 2:
![image](https://user-images.githubusercontent.com/81432164/112660759-b4b02200-8e4d-11eb-9658-218ea00ad6e8.png)

**Comment by iamromeo** [comment]
@Kordishal can you reproduce this? 
@Bladeswillfall is this persisting if you are in incognito mode?

**Comment by Bladeswillfall** [comment]
@iamromeo It doesn't persist in incognito mode no. Weird...

**Comment by Kordishal** [comment]
This means that most likely one of your extensions prevents the editor from loading properly. Adblock is a likely candidate. The editor loads for me no problem.

**Comment by Bladeswillfall** [comment]
I didn't have a problem earlier in the week with everything enabled? And
when I disabled them the issue persisted.
Did firefox update this week? I have a feeling it did... Will try again
with the adblockers etc and report back

**Comment by Kordishal** [comment]
There was a change to the editor this week. So maybe the bad interaction just came up because of it.

**Comment by iamromeo** [comment]
@Kordishal no change on the editor that would affect this. 
Chrome extensions auto update.

**Comment by Bladeswillfall** [comment]
I'm on version 87.0 of Firefox, have disabled all of my extensions and it's still not working?
![image](https://user-images.githubusercontent.com/81432164/112722381-25fcdd00-8f01-11eb-8043-116fa63ba1dc.png)
![image](https://user-images.githubusercontent.com/81432164/112722386-2dbc8180-8f01-11eb-8d2d-7abb3dcc4cdc.png)

Yet if I open it in incognito mode, it works fine?
![image](https://user-images.githubusercontent.com/81432164/112722409-5e042000-8f01-11eb-9abe-b429a3f62606.png)

This is a new issue and was not a problem earlier in the week... I've not changed anything about my system in this past week either. Do you have any clues as to what it could be?

**Comment by Bladeswillfall** [comment]
To close this off, I cleared my cache and the issue was resolved.
Whatever the update to the editor was caused the issue by the looks of it...
