### ISSUE TITLE
E-Mail Change

### ISSUE THREAD

**Issue by Marshixel** [worldanvil/worldanvil-bug-tracker#1030]
**World Anvil Username**: Marshixel

**World / Campaign / RPG Character / Manuscript Title**: -

**Feature**: -

**Related URLS** (To public & visible pages add screenshots otherwise): -

**Describe the Issue**
I can't change my E-Mail. When i go to account, change my E-Mail, write my Password down and then click on Update a screen shows  up with a Dragon and a text saying 404 “ Thus you have reached the end of this world.”

**To Reproduce**
1. Go to Account
2. Change E-Mail
3. Write down Password
4. Click on Update
5. See error

**Expected behavior**
I expect that i can change my E-Mail.

**Screenshots**
![image](https://user-images.githubusercontent.com/105457775/168155466-7ac75925-237a-43f9-ae63-610c2dfab6dd.png)

**Comment by iamromeo** [comment]
Hello there :) That means that there is already an account with the email you are trying to change your email to. This is not a bug.

**Comment by iamromeo** [comment]
Also please keep in mind that is it against ToS to have more than one account if you do not have an active subscription

**Comment by Marshixel** [comment]
Hello,

yeah i had made an account with my e-mail but deleted it because i forgott i already had an account. So that E-Mail can't be in use anymore since i deleted that account and i accidentily wrote my E-Mail, on my now Account which i want to keep using wrong. Is there a way to change that?



Sent from my Galaxy



-------- Original message --------
From: Dimitris Romeo Havlidis ***@***.***>
Date: 13/05/2022 07:04 (GMT+01:00)
To: worldanvil/worldanvil-bug-tracker ***@***.***>
Cc: Marshixel ***@***.***>, State change ***@***.***>
Subject: Re: [worldanvil/worldanvil-bug-tracker] E-Mail Change (Issue #1030)


Hello there :) That means that there is already an account with the email you are trying to change your email to. This is not a bug.
