### ISSUE TITLE
Whiteboard forces article view on it

### ISSUE THREAD

**Issue by MGatta** [worldanvil/worldanvil-bug-tracker#1031]
**World Anvil Username**: MGatta

**Feature**: Embedded whiteboard

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/13-mgatta/a/candle-river-location

**Describe the Issue**
After putting the whiteboard in my article, every time I view my article, it loads on the whiteboard, rather than the beginning of the page. The article seems to skip down towards where the whiteboard is for some reason.

**To Reproduce**
1. Go to an article
2. Embedd a whiteboard
3. Click "View"

**Expected behavior**
For the article to load at the beginning of the page, regardless of whether there is a whiteboard or not.

**Comment by iamromeo** [comment]
This will not be addressed since the system actually does try to scroll back to top -

**Comment by MGatta** [comment]
> This will not be addressed since the system actually does try to scroll back to top -
I do not understand this. I've tried with all my browsers (chrome included) and my article simply stays at the whiteboard (unless I manually scroll). What do you mean by "the system tries to scroll back to the top"?
![image](https://user-images.githubusercontent.com/80196715/168861221-1fff85cd-d28d-4124-8c62-942ba96f8cc1.png)
