### ISSUE TITLE
Timeline Eras bugged

### ISSUE THREAD

**Issue by RedLordTMM** [worldanvil/worldanvil-bug-tracker#1032]
**Redlord**:

**World / Campaign / RPG Character / Manuscript Title**: Ioral/History of the World

**Feature**: Timeline Eras

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/ioral-redlord/t/history-of-the-world-timeline

**Describe the Issue**
I have been converting a written timeline from elsewhere into one for World Anvil and, after adding in most of the written timeline events, one of my eras, the Neolithic, was removed at random. After re-adding this era, dates after 5387 and 5400 are duplicated and placed within the incorrect era. 5387 is the beginning of a new era, events after the 5387 end of an era should not be duplicated and the previous era.

**To Reproduce**
Add a ton of events to a single time line with at least 3 eras, after the first era each era starts at 0. Currently the bugged timeline has 100 events, though when the bug occurred it was less than that, though at least at 90 events

**Expected behavior**
Events with a given date within an era should display within that era

**Screenshots**
![Beginning](https://user-images.githubusercontent.com/68730201/168238252-d6d49426-1f56-401e-b117-2fa87d324327.PNG)
![Duplic](https://user-images.githubusercontent.com/68730201/168238998-b8d2be21-04f9-4f5b-98f9-12e31dab0666.PNG)
![LongSummer](https://user-images.githubusercontent.com/68730201/168238265-3e9e733c-9ec4-4764-8b99-9ecf10a6f403.PNG)
![LongSummerpic](https://user-images.githubusercontent.com/68730201/168238267-c2aaafe6-692a-4eb9-8687-2f1a7ada4068.PNG)
![Unrest](https://user-images.githubusercontent.com/68730201/168238270-4e5be0fb-f657-4117-b74f-f1a45a7abd80.PNG)

**Comment by iamromeo** [comment]
I am really sorry but this is not a bug. An event cannot extend across the boundaries of a timeline (please check the documentation). Aside of that I cannot see any other issues. If you want to discuss further please feel free to bring this to discord, but this is not a bug with timelines with a large number of events or eras since there are hundeds of timelins with literally 500+ events across tens of eras.
