### ISSUE TITLE
Map not Showing (for View or Edit)

### ISSUE THREAD

**Issue by StudioBlueGames** [worldanvil/worldanvil-bug-tracker#1033]
**World Anvil Username**: StudioBlue

**World / Campaign / RPG Character / Manuscript Title**: Grand World

**Feature**: Maps

**Related URLS** (To public & visible pages add screenshots otherwise): screenshot provided

**Describe the Issue**
When we go to the map pages, or attempting to edit pins on the map, the map image won't show, even though the map image is listed as the primary image in the editor.

**To Reproduce**
1. Go to 'Maps'
2. Click on 'Countries of the Holy Empire'
3. Try to view the map.

**Expected behavior**
We expect to see the map and its pins.

**Screenshots**
![image](https://user-images.githubusercontent.com/89875498/168428495-8fb03929-7762-4f47-bb56-3243d9ec13fa.png)

**Comment by Kordishal** [comment]
This is usually caused by one of two things:

1. The image isn't a supported format. Like if you have a gif or animated WEBP image. Or it might be a supported image but with metadata that is not supported. Make sure the image is either PNG, JPG or WEBP. No transparency. Recommended is WEBP image properly exported from GIMP or other image processing software.

2. The image is not loaded because one of the pins is corrupted. This can have a few reasons, but the image and the pins reappear if you delete the offending pin.

**Comment by iamromeo** [comment]
In both cases we will need an actual URL (and access if private) so we can help you out :)

**Comment by iamromeo** [comment]
@StudioBlueGames any update on this?

**Comment by iamromeo** [comment]
No response for 7 days

**Comment by StudioBlueGames** [comment]
We did reply as requested. Sent from my Galaxy
-------- Original message --------From: Dimitris Romeo Havlidis ***@***.***> Date: 5/24/22  1:46 AM  (GMT-06:00) To: worldanvil/worldanvil-bug-tracker ***@***.***> Cc: Studio Blue ***@***.***>, Mention ***@***.***> Subject: Re: [worldanvil/worldanvil-bug-tracker] Map not Showing (for View or Edit) (Issue #1033) 
Closed #1033 as completed.

**Comment by StudioBlueGames** [comment]
Odd. The message seemed to have been stuck in our drafts folder? No idea.
Here is what we sent. It would have resulted in a closed ticket anyway, but
maybe this can be for your records?

~Steel and Teal
   Studio Blue
   https://www.youtube.com/c/StudioBlueGames
   https://www.twitch.tv/studiobluegames


Hey there. The situation seemed to resolve itself when we logged out, clear
cache/cookies, and then logged back in. Not sure what happened, but it's
working now.

Thanks!

~Steel and Teal
   Studio Blue
   https://www.youtube.com/c/StudioBlueGames
   https://www.twitch.tv/studiobluegames

**Comment by StudioBlueGames** [comment]
Apologies. Had to take care of IRL. I'll update tomorrow. Thanks as always for your attention. 🙂Sent from my Galaxy
-------- Original message --------From: Dimitris Romeo Havlidis ***@***.***> Date: 5/16/22  2:34 PM  (GMT-06:00) To: worldanvil/worldanvil-bug-tracker ***@***.***> Cc: Studio Blue ***@***.***>, Mention ***@***.***> Subject: Re: [worldanvil/worldanvil-bug-tracker] Map not Showing (for View or Edit) (Issue #1033) 
@StudioBlueGames any update on this?
