### ISSUE TITLE
Cannot find Orphaned Timeline to delete

### ISSUE THREAD

**Issue by Reuwriting** [worldanvil/worldanvil-bug-tracker#1034]
**World Anvil Username**: Sgt Reuster

**World / Campaign / RPG Character / Manuscript Title**: The World of Thear

**Feature**: Timeline

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/the-world-of-thear-reuster/t/the-world-of-thear-timeline-master?preview=1

**Describe the Issue**
It states I have an orphaned timeline but i cannot find anything orphaned

**To Reproduce**
Steps to reproduce the behavior: go to above link

**Expected behavior**
There should be no orphaned timeline info

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Do you mean the banner on the timeline that indicates that historical events below it are orphaned? That one appears regardless if you have any or not. And its meant to separate historical events that according to their date do not fit into any era on that timeline.

**Comment by Reuwriting** [comment]
Yes, Sir. That’s what I was talking about. So, I spent hours trying to find a non-existent orphaned timeline item? Lol please kill me

**Comment by Kordishal** [comment]
Unfortunately yes. 

@iamromeo: Maybe it would make sense to hide the banner if there are no orphaned historical events? This is not the first time I've seen people confused by it.

**Comment by iamromeo** [comment]
I will see what we can do about that :) - checking now
