### ISSUE TITLE
Whiteboard text size does not scale with container size.

### ISSUE THREAD

**Issue by BoSRaptoR** [worldanvil/worldanvil-bug-tracker#1035]
**World Anvil Username**: BoSRaptoR

**World**: Delmera : Innocence

**Feature**: Whiteboards

**Related URLS** (To public & visible pages add screenshots otherwise): https://media.discordapp.net/attachments/380013392653451264/975112928816685086/unknown.png
https://media.discordapp.net/attachments/380013392653451264/975117234110337044/unknown.png

**Describe the Issue**
I reopen my whiteboard and all the texts have changed in size and I can no longer scale them properly to fit into the shapes I created. any ideas ?

**To Reproduce**
1. I just reopen my whiteboard today, so i don't know who to reproduce the bug.

**Expected behavior**
I expect that my text fit in the created shapes, like before.

**Screenshots**
Before : https://media.discordapp.net/attachments/380013392653451264/975116804177416253/unknown.png
Today : https://media.discordapp.net/attachments/380013392653451264/975116902458351667/unknown.png

**Comment by Kordishal** [comment]
https://www.worldanvil.com/w/WBtV/a/hunters-guild

My whiteboard now has smaller sized text as well, though I did not change anything.

**Comment by Duranzno** [comment]
Working on this right now

**Comment by Duranzno** [comment]
@BoSRaptoR @Kordishal I apologize for the inconveniences from this bug, this should be fixed now 😅 😅 😅 .

**Comment by Kordishal** [comment]
Can confirm that the issues was gone after a hard refresh CTRL+F5! Thanks :)

**Comment by BoSRaptoR** [comment]
@Duranzno Thanks :)
