### ISSUE TITLE
Cant delete world

### ISSUE THREAD

**Issue by sohns** [worldanvil/worldanvil-bug-tracker#1036]
**World Anvil Username**:Lydriana

**World / Campaign / RPG Character / Manuscript Title**:Seradel

**Feature**: DELETE WORLD

**Describe the Issue**
I get a 404 error when I try to delete this world

**To Reproduce**
1. Go to Settings page
2. Click on Delete world
3. Confirm Delete world
4. Be redirected to 404 page; 
     NOTE: World is not deleted

**Expected behavior**
I would expect the world to be deleted and returned to dashboard

**Comment by Kordishal** [comment]
You can attempt the following to delete the world:

- Delete associated campaign
- Expel RPG characters from the world
- Delete associated manuscripts
- Remove subscriber groups, subscribers and co-authors from the world.


If it still doesn't work, Dimitris will have to investigate further.

**Comment by iamromeo** [comment]
@sohns let us know if  you are still having an issue since 99,99% of the times the above fix the issue.
