### ISSUE TITLE
ads showing on profile page for non-logged in users

### ISSUE THREAD

**Issue by Deleyna** [worldanvil/worldanvil-bug-tracker#1037]
**World Anvil Username**: deleyna

**World / Campaign / RPG Character / Manuscript Title**:
author profile page

**Feature**: 
profile page shows ads to non-logged in users

**Related URLS** (To public & visible pages add screenshots otherwise):
deleyna.rocks

**Describe the Issue**
profile page shows ads to non-logged in users

**To Reproduce**
1. Open private browser
2. go to deleyna.rocks 
3. See ad at top of ugly profile page

**Expected behavior**
In the sage seminar, we talked about prettying up our author pages. I thought it would be fun to consider eventually making my WA profile function like a website, and then tie it into my worlds. I know I can attach a domain name to my worlds individually - and may do that eventually - but wanted to see if I could build an author website this way.

Just let me know if this would make sense as a feature request instead, but it was suggested that I report it as a bug.

I love the idea of building this page out as a home base for authors... but ads are probably not helpful... makes it look like Wordpress.com. LOL

**Comment by iamromeo** [comment]
We can definitely make User profiles from a guild rank up not to show adverts (this is not a bug, probably a feature but no reason to suggest it, since it is not a matter of implementation but policy) 

I will talk with Janet and we will come up with a solution.

**Comment by Deleyna** [comment]
Thanks! I did wonder... in the Sage Hall we talked about it briefly and
they suggested we start with bug, but if you wanted to do feature, we'd go
that way, too. (grin)

Policy is a 3rd option we hadn't considered! Yay!

**Comment by iamromeo** [comment]
This has been addressed and a deployment will happen within the next 48 hours

**Comment by Deleyna** [comment]
Excellent! Thanks!
