### ISSUE TITLE
E-Mail change

### ISSUE THREAD

**Issue by Marshixel** [worldanvil/worldanvil-bug-tracker#1038]
**World Anvil Username**: Marshixel

**Describe the Issue**
I Already reported this once. I cannot change my E-Mail. I got a message that it's not a bug but because the E-Mail is already in use. Which can not be since the account i had that E-Mail with has been deleted and i cannot long in anymore. So i have no explanation why i can not change my E-Mail to another one which i used once on an account which has been deleted. It seems more like a bug to me than anything else.

**Expected behavior**
I expect to be able to use my E-Mail because the other account has been deleted.

![Screenshot 2022-05-15 14 12 45](https://user-images.githubusercontent.com/105457775/168472205-44d422bf-a1f0-415f-95d2-53f315bb8ddf.png)

**Comment by Kordishal** [comment]
Hi, I think it would be best if you write an email with your existing email and the email you want to change it to and your account details to `contact@worldanvil.com` so they can check what is causing the issue.

Duplicate: #1030

**Comment by iamromeo** [comment]
In case that was not clear before, creating more than 2 accounts and non of them being a guild account is a breach of the terms of service and a reason for termination of your account now and in the future. 
If you have an account already with another email, you should recover that account and use that. If the account is deleted then the email change would have been possible.
