### ISSUE TITLE
Five torches deep RPG system request  

### ISSUE THREAD

**Issue by Evilcookiz** [worldanvil/worldanvil-bug-tracker#1039]
Great system, has active players, would love to have it :)

**Full Name (RPG SYSTEM)**: Five torches deep
**List Name** (Name under which it should be listed on World Anvil): 5TD
**World Anvil Username**: Evilcookiz

**Website**:  https://www.fivetorchesdeep.com/

**Comment by iamromeo** [comment]
Added to the list :)
