### ISSUE TITLE
View Source in Article Edit converts BBCode to HTML

### ISSUE THREAD

**Issue by cyberianfrontier** [worldanvil/worldanvil-bug-tracker#104]
**World Anvil Username**: Buzzard

**World / Campaign / RPG Character / Manuscript Title**: Eastern Urik

**Feature**: Article Edit - Textarea Editor

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When editing the Content for one of my species articles, clicking the View Source button converts the article content from BBCode to HTML.  I haven't tried this on any other articles because I don't want to lose my content and formatting via the auto-save.  The article in question I happened to be editing the source in Notepad++ so I thankfully had a backup of my source.  This seems to permanently change the content of the field to HTML.  The HTML code shows on the View side as well.

**To Reproduce**
1. Edit existing species article
2. Click the View Source button in the editor.
3. Source should show as HTML instead of BBCode

**Expected behavior**
Expect to see BBEdit tags, not HTML

**Screenshots**

![Screenshot 2021-03-26 101733](https://user-images.githubusercontent.com/81428411/112671464-700d9200-8e1f-11eb-9157-450ae7d010c8.png)

**Comment by cyberianfrontier** [comment]
I think this bug might be more serious than I originally realized.  At least for me, even if I don't use the View Source button on the editor, any changes that I make to an article are being recorded in HTML and not in BBCode.

**Comment by Kordishal** [comment]
containers are not supported in the Plato editor.

You have to switch to the [Euclid](https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors) editor to use them.
