### ISSUE TITLE
Adding Coyote & Crow RPG System

### ISSUE THREAD

**Issue by qwertynerd97** [worldanvil/worldanvil-bug-tracker#1044]
Remember, to request an RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first four points at least, otherwise the request will not be considered.

**Full Name (RPG SYSTEM)**: Coyote & Crow
**List Name** (Name under which it should be listed on World Anvil): Coyote & Crow
**World Anvil Username**: qwertynerd97

**Website**: https://coyoteandcrow.net/

**Logo Image Link**: https://coyoteandcrow.net/wp-content/uploads/2021/05/CoyoteHeader-grad-pur.jpg

**Logo Usage Terms (URL)**: Unknown

**Comment by iamromeo** [comment]
All done :)
