### ISSUE TITLE
Navigation menu issues

### ISSUE THREAD

**Issue by QuintusAgrippa** [worldanvil/worldanvil-bug-tracker#1045]
**World Anvil Username**:
Agrippa

**World / Campaign / RPG Character / Manuscript Title**:
Anbomira

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
On any article, in the navigation tab, only about 1/3 of categories are in the drop down menu of the parent category in basic navigation.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Have you searched for the categories? It is possible that the list doesn't load fully. How many categories do you have? On my world they are all there.

**Comment by QuintusAgrippa** [comment]
It seems to be working now as long as I rename the category, save it, and
then change it back.
