### ISSUE TITLE
Dark Blue Interface Title Box Visual Bug

### ISSUE THREAD

**Issue by NecroAura** [worldanvil/worldanvil-bug-tracker#1046]
NecroAura

Runeterra

Article Creation

![image](https://user-images.githubusercontent.com/90993347/169671213-506bd7a3-5659-4650-8b46-8783db0684e4.png)
![image](https://user-images.githubusercontent.com/90993347/169671234-e297dcfe-40d6-4b62-be17-dc3caa630ab9.png)
![image](https://user-images.githubusercontent.com/90993347/169671238-b43d32d0-efd0-4a91-b01a-898a5e0cb423.png)

**Describe the Issue**
When using the Dark Blue interface//dark mode, Article Boxes no longer highlight as you can see in the second image. On Dark Gray they do as you can see in the first image, but only when you interact with them by clicking on them on Dark Blue do they highlight. This makes the whole article page very irritating to the eye, and makes it unclear what can actually be clicked on. This was not the case as of 21/05/2022.

**To Reproduce**
1. Go to Manage Your Account in the top right corner
2. Click [Interface].
3. Click below [Interface Theme].
4. Scroll down to and select [Terror from the Deep (Dark Blue].
5. Create an Article
6. See error

**Expected behavior**
Like you can see in the first image, every box you can interact with on other interface options can be identified easily because it is highlighted. In the current Dark Blue mode this does not happen, but it is obvious it is meant ot because the Tags are still following this rule without needing to be interacted with, as you can see below:
![image](https://user-images.githubusercontent.com/90993347/169671354-5d3424f1-1692-4a6d-bc6a-067c34ad2479.png)

**Comment by iamromeo** [comment]
This is not a bug! :) 

It is a design change. Form inputs still highlight when you click on them and work with them
