### ISSUE TITLE
Whiteboards and UI issues

### ISSUE THREAD

**Issue by rttuo** [worldanvil/worldanvil-bug-tracker#1047]
**World Anvil Username**: rttuo

**World / Campaign / RPG Character / Manuscript Title**: Numidius

**Feature**:  Whiteboards and UI

**Related URLS**: https://www.worldanvil.com/w/numidius/a/phylogenetic-trees-of-sapient-species-law

**Describe the Issue**
1) On every page it should appear, the "continue working" section does not display at all. I am a co-author in this world.
2) When attempting to display multiple whiteboards in the same article, only the first appears. I have tested this and found that the order in which they are embedded is the sole cause (or otherwise couldn't find another). Any whiteboard after the first just loads indefinitely.
3) Thank you <3

**Expected behavior**
1) For the section to display the most recently changed article.
2) For all whiteboards to load properly.

**Comment by Kordishal** [comment]
1. The continue working is disabled for co-authors. Not sure if it will come back.
2. Whiteboards are limited to one per article, they are not intended to be stacked. This is the case with most interactive embeds.

**Comment by rttuo** [comment]
That's a shame.
Thank you very much!
