### ISSUE TITLE
Cyberpunk theme prevents world background setting from styling menu.

### ISSUE THREAD

**Issue by mate888** [worldanvil/worldanvil-bug-tracker#1048]
**World Anvil Username**:
Icewall Staff
**World / Campaign / RPG Character / Manuscript Title**:
Kessler
**Feature**: 
Styling
**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/kessler-icewall-staff
**Describe the Issue**
A clear and concise description of what the issue is.
When styling the page, I added an image to the background to see how it looked. Not liking how it looked, I chose another image for the background, but after saving changes and clicking View World, the default background image was there instead. I tried putting the previous image back in as the background, but the default background remained.
**To Reproduce**
1. Go to 'Styling'
2. Click on 'Global Cover'
3. Pick any image
4. Click on view world
5. The error may or may not be present

**Expected behavior**
I expected the default background to be replaced with the chosen image.
**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Hi, currently the image seen on the page you linked is not the default image on the theme you are using. Did you change that with  custom CSS? 

So you are reporting, that the background doesn't change on the Cyberpunk theme with the UI selection right?

**Comment by mate888** [comment]
yes, i managed to change it using a custom css, the problem seemed to be
that the cyberpunk 2020 theme attaches its background image to
.user-css-presentation div#full-layout, rather than just
.user-css-presentation, which is why the change can only be made on the
custom css screen

**Comment by iamromeo** [comment]
Will be fixed with next deployment

**Comment by PeachesOnPaper** [comment]
While this issue seems to be fixed, now the background image is unable to be displayed at all. It's just a slightly purple colour.
