### ISSUE TITLE
Can't remove relationship

### ISSUE THREAD

**Issue by JohanFalt** [worldanvil/worldanvil-bug-tracker#105]
**World Anvil Username**: 
johanfk

**World / Campaign / RPG Character / Manuscript Title**:
Rage across Colorado

**Feature**: 
Remove existing relationship

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/rage-across-colorado-johanfk/a/aaron-spencer-person?preview=true?

**Describe the Issue**
I had a character called Shad, I added relationships from him to other characters. Then I transformed him into a PC, but as I did secrets I didn't wanted the player to see became visible so I removed the PC and recreated a new Shad character adding that to the player. Now all the old relationship from the first Shad is still there but since the character doesn't exist I can't remove them.

**To Reproduce**
Go to character https://www.worldanvil.com/w/rage-across-colorado-johanfk/a/aaron-spencer-person?preview=true?
Try remove the relationship Shad <-> Aaron Spencer
If you try to edit it you get a Page is missing

**Comment by iamromeo** [comment]
@JohanFalt you have generally done some really interesting mambo jambo with that character :P 
I will see what I can do

**Comment by JohanFalt** [comment]
LOL yes but I can still describe it in detail:

- Created it as NPC
- Created relationship with a number of NPCs
- Gave the character to player
- Deleted character
- Created new character as PC to player with same name

But yeah :)
If anything, if you just delete the old relationship the character had I am
fine with that. Do you need to know which NPCs that has these relationships
or can you see that on your end?

Den lör 27 mars 2021 kl 13:24 skrev Dimitris Romeo Havlidis <
***@***.***>:

**Comment by JohanFalt** [comment]
No there relationships are still visible and I can still not remove them.

lör 27 mars 2021 kl. 13:58 skrev Dimitris Romeo Havlidis <
***@***.***>:

**Comment by iamromeo** [comment]
![Screenshot 2021-03-29 at 07 18 39](https://user-images.githubusercontent.com/660175/112786473-fe238b80-905e-11eb-9f41-199b91075a1b.png)

I can see no relationship here - where are you able to see the relationship?

**Comment by JohanFalt** [comment]
You can see it when you edit the article under Relationship, in this case
Shad <-> Aaron Spencer, there are the same type of ghost links on
characters this ghost Shad is connected too.

Den mån 29 mars 2021 kl 06:19 skrev Dimitris Romeo Havlidis <
***@***.***>:

**Comment by JohanFalt** [comment]
Just to add it to the description of the task itself. Problem exists with the character (the article under relationship)

Aaron Spencer - https://www.worldanvil.com/world/person/6b6ca77d-a258-49d1-8b86-d47149d91919/edit
Delit - https://www.worldanvil.com/world/person/ac5f215e-37ec-4696-a2af-6888678ef64b/edit
Jonny Cox - https://www.worldanvil.com/world/person/15258131-7706-4f4a-b823-112f98dfeb6d/edit
Makkapitew -  https://www.worldanvil.com/world/person/b778eed1-9554-4c63-ae0a-3f809fc25fca/edit

**Comment by iamromeo** [comment]
In the example you have given to me both Aaron Spencer 6b6ca77d-a258-49d1-8b86-d47149d91919 and Shad 4ff10645-86a1-49d5-867d-dd890740e3af are both non deleted characters. 
The only difference is that Shad is no longer a member of your world but it is still a character of **saas98**

**Comment by JohanFalt** [comment]
But as you go e.g Aaron’s article, goes to relationship the relationship
with the former character Shad is still there and you can’t remove it.

It is the same on the characters I mentioned. My guess is there are left
over data in the table that handles relationship and as you try to delete
the relationship as you look up the primary key of the deleted Shad that
fails and thus why it can’t be removed.

lör 10 apr. 2021 kl. 12:46 skrev Dimitris Romeo Havlidis <
***@***.***>:

**Comment by JohanFalt** [comment]
You can close this now I have fixed it myself.

Den lör 10 apr. 2021 kl 17:32 skrev Johan Fält ***@***.***>:
