### ISSUE TITLE
Plots page not working

### ISSUE THREAD

**Issue by TorcDuridak** [worldanvil/worldanvil-bug-tracker#1050]
**DungeonMasterTorc**:

**Terros / Planar Conjunction / Torc / N/A**:

**[Plots]**: 

**(https://www.worldanvil.com/heroes/campaign/plot/list)** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When I click on the plots page it gives me an HTTP ERROR 500 message saying the site is not able to handle the request. I can't view my plots in a list like normal.

**To Reproduce**
1. Go to **Campaign**
2. Click on 'Plots'
3. See error

**Expected behavior**
Normally I click on the PLOTS tab and it allows me to view all of my campaign's plots broken down in an ordered list by Acts & Chapters

**Comment by Kordishal** [comment]
This means that there is a loop in your plots or the master plot has parent plots. You need to go into your plots and remove any parent plot links that could be causing this issue.
