### ISSUE TITLE
Green loading bar repeats itself

### ISSUE THREAD

**Issue by AmeliaNite** [worldanvil/worldanvil-bug-tracker#1051]
**World Anvil Username**: amelianite

**World / Campaign / RPG Character / Manuscript Title**: Darkness Moon Chronicles (World)

**Feature**: editing side causes the green loading bar to repeat itself as random points

**Related URLS** (To public & visible pages add screenshots otherwise): [Screenshot of the green bar](https://lh3.googleusercontent.com/4VjcGRtNaAAU3SuSqi7S4NMoCXQDeFabQo1CEaM5OAy_8h8z9Qg21AvvW20J1PivPktkHz9ao0TbL2To-q0yPtG9Y6JZZhqGf47AEpJXBrO390VcVl_5bhGWvwTe3FB1sHcKKDJCjNDudEIXnklNHt3tXINDIxWbY1PvjS7gsqMuNdGCilr51kMVqBxau60IgvkAodbezUGdzVoEz_XdF8fto8HWZ4rjla1Z31QIzR6ZJQGqHoKZ8Alg22WLUZbeRJVmu7sOPU37ZjzurjjIYafgaU1eB9rzDfqq0YXDzgigALj41kZIwHY4jtsavoQ5FwCcEn2HOJHO1Lc67Rno3UFj4RmH1-3GM6NwKAc3jw041o22Q8QDR68pcEjuc5qNVSmGmc54bbx6xlfkAIVBRkfa6TrfgQbWmE73EQ-LKG5Q5Y7t9DHCn8VantFziR7t2x9NyrADy26sfLWtoXxg6kDEWL-LpipvRRYjvwuy20afZjo39B0jCSXn2VaJkgsGK-asmGFcNBDVHUE73pqYhHY0BZw-aBVE6WmQsJ9SrVB1mLV-mBAWcbLDauuzh_Gbl40OQ0fZLVIqydi989yxG8kcui2DT9MQP9SbQsuIv2NbHVupMq5nYKXl_PJRdnr8m5CRqzpcmlf9JRGlXrqE0y4XqlqRHv4eKxqmXXsS-6AVRuNmi0fcApq4RZQKffjwsduT0oboUf5fUb44RgaM7oD2QAmRvpsgV2haFnNquDo3pqgZU_KeU6Rw4_Z_=w1666-h937-no?authuser=0)

**Describe the Issue**
On Chrome (on my laptop), I got to any section (dashboard, statblocks, an article, etc.) and it does the first green loading bar across the top. Then it repeats the green loading bar after the page is completely loaded and does not go away unless I click on another website's tab when the second green bar is 97% complete and then return to the WA tab I was originally on.

**To Reproduce**
1. Go to 'dashboard/statblocks/etc'
2. Watch as the green load bar goes through once.
3. Watch as it tries to load a second green load bar and go very, very slow to the end
4. See green load bar does not disappear

**Expected behavior**
An annoying second green loading bar repeats itself and does not go away.

**Screenshots**
This may not be a screenshot, but a video that helps to better show what happens.
[Video of the bar repeating itself upon loading to the dashboard](https://photos.app.goo.gl/Pv5tAZYTK8ttYFo4Al)

**Comment by iamromeo** [comment]
Hey there @AmeliaNite!
1. I cannot reproduce this 
2. The video link at the bottom does not work

**Comment by AmeliaNite** [comment]
I haven't added any new plug-ins for over a year and this only started around 4 days ago, after the big updates and the main sidebar on the left changing its design.

The only extensions I have are the typical ad-blockers (though I just turned them off to test), the main google apps (like translate and docs offline), Grammarly, an app called Forest (a timer that allows you to stay focused; haven't touched that in months and I know another anvilite who uses the same app but doesn't have issues), and Webroot (internet web protection, but I've had that for years, long before I joined WA).

And I don't know why you can't get the video, but I'm going to try this [video](https://photos.app.goo.gl/Pv5tAZYTK8ttYFo4A). If this doesn't link, then it's something on Github's end because when I paste the link in the search bar, it takes me straight to the video.

**Comment by Kordishal** [comment]
Hi!

I did see a second loading bar once or twice, but it finished loading on my end. After that the second loading bar doesn't appear anymore. In general your bars are very slow, so there is likely some issue with something breaking / not finishing loading on your end.

This happens in a private window too?

**Comment by AmeliaNite** [comment]
Yup. I just tested it.

**Comment by iamromeo** [comment]
- Which browser is used?
- Is this happening on INCOGNITO (not private) mode
- Is this this happening on other browsers?

**Comment by AmeliaNite** [comment]
I know this is happening on Chrome and in Incognito mode and it's happening in Firefox when I haven't even logged in.

**Comment by iamromeo** [comment]
Thank you for the information. I have kept a note for it - but I cannot fix something I cannot reproduce for the time being. 
<3
