### ISSUE TITLE
Default presentation theme makes text bold when marked as italic inside of quotes

### ISSUE THREAD

**Issue by airbreather** [worldanvil/worldanvil-bug-tracker#1052]
**World Anvil Username**: skidznet

**World Title**: Aeternia

**Feature**: Article

**Related URLs**: https://www.worldanvil.com/w/aeternia-skidznet/a/session-108-report#BlockQuoteWithItalics

(edit: to work around this issue, I've inlined the imported CSS for the missing bits, so you won't see it on our world as-is.  sorry about that.  please see the updated repro steps)

**Describe the Issue**
The default article template (i.e., the one that's used when "Theme" is left blank on https://www.worldanvil.com/world/styling) has it so that all italicized text in a block quote is also automatically bolded.  This is not what I expect to see.

We've been living with this for a while, and I've finally gotten annoyed enough that I've decided to look into it.  Playing around with the style editor, I noticed this part of `styles-2018.css`:
```css
@import 'https://fonts.googleapis.com/css?family=Alegreya:400,700,700i&subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext';
@import 'https://fonts.googleapis.com/css?family=Alegreya+SC:400,700,700i&subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext';
```
When I change it to this (i.e., adding "`400i`"), I see the block quotes rendering as I expected them:
```css
@import 'https://fonts.googleapis.com/css?family=Alegreya:400,400i,700,700i&subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext';
@import 'https://fonts.googleapis.com/css?family=Alegreya+SC:400,400i,700,700i&subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext';
```

**To Reproduce**
1. Click the link I put into "Related URLs".  It's an anchor to a block quote that contains some italicized text that is not marked bold.
2. In your web debugging tools, disable the inline stylesheet that adds all the `font-family: Alegreya; font-style: italic; font-weight: 400;` stuff.  In my Firefox, this is "<inline style sheet #​9>".
3. Observe the italicized text in that block quote.

**Expected behavior**
Italicized text should not be weighted significantly more heavily than the text around it, unless we explicitly also ask for it to be bold.

**Screenshots**
How it displays by default:
![image](https://user-images.githubusercontent.com/3792815/170485993-34efbbe6-c573-41da-8eca-6c348d4e233e.png)

How it displays after I make the CSS change listed in the description:
![image](https://user-images.githubusercontent.com/3792815/170486240-508d3096-84a0-4b22-b2c1-09526f8ab615.png)

**Comment by iamromeo** [comment]
Thank you :) WIll be deployed later on today
