### ISSUE TITLE
Changes to world look without altering CSS

### ISSUE THREAD

**Issue by MGatta** [worldanvil/worldanvil-bug-tracker#1053]
**World Anvil Username**: MGatta

**Feature**: Header articles

**Describe the Issue**
All headers are now much slimmer. I have not touched the CSS of the world (at all, not just related to the fonts). I first noticed this issue on the 25th. Over discord, I was told that TJ also noticed some slight changes on his world too.

**To Reproduce**
See the screenshots taken on different dates.
![image](https://user-images.githubusercontent.com/80196715/170504746-a73c2cba-ec81-4ae3-aca7-fdc571a87fe9.png)
![image](https://user-images.githubusercontent.com/80196715/170504817-d2a625e5-2f36-4ddf-8ea3-2306925e43e2.png)

**Expected behavior**
For the CSS to remain the same unless I change it (or to get a notification if website changes will affect the CSS).

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Aren't the differences on this page caused by the Whiteboard embed? At least it used to look like in the second image and was then fixed to look like in the first one.

**Comment by iamromeo** [comment]
That was a biproduct of another bug reported. it will be returned to its original state

**Comment by MGatta** [comment]
I am not sure why it was closed, the issue is still not solved. All of my headers are substantially slimmer.
