### ISSUE TITLE
404 whenever I open my only map

### ISSUE THREAD

**Issue by Azerdoze** [worldanvil/worldanvil-bug-tracker#1054]
**World Anvil Username**: DMrico

**World / Campaign / RPG Character / Manuscript Title**: Arthan Uthyl

**Feature**: Map

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I just wanted to give a link to a marker. Now I get "404: Thus you have reached the end of this world.” anytime I try to access the only map I have. 

**To Reproduce**
1. Go to 'Maps'
2. Click on 'either EDIT or VIEW of Map of the Human Lands'

**Expected behavior**
For the map to open normally. 

**Screenshots**
-

**Comment by iamromeo** [comment]
You have added a faulty link to an article or another entify - this means that you manually edited something on your pin or maps's description and changed the id. 

1. Open the edit mode of your map
2. Find the mention of a link that begins with the value in bold below
3. Delete or fix it. 

````
An exception has been thrown during the rendering of a template ("Could not convert database value "**91bdcc35-8c71-49f6-8**..." 
````

**Comment by Azerdoze** [comment]
Good Afternoon, Dimitris.

Thanks for checking my issue, but as stated on the template, I can't open the edit mode, it sends me to the 404.
Anyway to manually override it?

Thanks in advance.

**Comment by iamromeo** [comment]
@Azerdoze there is now a delete button on the list that should allow you to delete the map from there :)
