### ISSUE TITLE
Wrongly scaled ko-fi button and unable to remove ko-fi/patreon links from Manuscripts

### ISSUE THREAD

**Issue by artyrambles** [worldanvil/worldanvil-bug-tracker#1055]
**World Anvil Username**: arty

**World / Campaign / RPG Character / Manuscript Title**: [example](https://www.worldanvil.com/community/manuscripts/read/0147780669-arty-renegade/12da5946-f365-4aff-928a-71fb6e2780a8) (scroll to bottom of the page)

**Feature**: Manuscripts

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

**To Reproduce**
1. Create Manuscript
2. Fill in the patreon and/or ko-fi username fields
3. If you try to remove them, the change won't save
4. On the manuscript's chapter pages, the buttons will still be there and they will be wrongly sized even when the fields are filled

**Expected behavior**
If I delete the content of the field, the buttons should disappear. If the field is filled correctly, the buttons should be the same size.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/29456646/170878369-58ce4436-7f89-4a46-9da3-8530b32b3bbd.png)
The buttons are scaled wrong.
![grafik](https://user-images.githubusercontent.com/29456646/170878390-6fc1c3b0-a1c5-459c-9410-6af2592585e9.png)
The patreon button still is shown on the page even if the field's content was deleted.

**Comment by iamromeo** [comment]
Fixed will be deployed within the next 48 hours
