### ISSUE TITLE
Timeline Date Issue

### ISSUE THREAD

**Issue by Satstoy** [worldanvil/worldanvil-bug-tracker#1056]
**World Anvil Username**:
Satstoy
**World / Campaign / RPG Character / Manuscript Title**:
Evil Campaign/ Exandria Campaign
**Feature**: 
Timeline
**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/evil-campaign-satstoy/t/history-of-exandria-timeline?preview=1
**Describe the Issue**
A clear and concise description of what the issue is.
I have entered a date for two of my events as 869 but they show up in the timeline as 870. 
**To Reproduce**
1. Go to '..https://www.worldanvil.com/w/evil-campaign-satstoy/t/history-of-exandria-timeline?preview=1.'
2. Click on '..THE DESTRUCTION OF URUKAYXL Historical Event..'
3. Scroll down to '..Starting and Ending Date..'
4. See that I have selected 869 but it shows as 870

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
870 PD is the year of the era. 869 is the UTD date that you set. The era starts at year 0 I presume? Have you set the era to start at year 1? As an offset?

And your events are all private so I can't check what they display.

**Comment by Satstoy** [comment]
That was exactly what the issue was, thanks for your help!


Cheers,


Samwise Skelhorn

he/him


________________________________
