### ISSUE TITLE
Articles Displaying Twice When Searched For

### ISSUE THREAD

**Issue by SableAradia** [worldanvil/worldanvil-bug-tracker#1058]
**World Anvil Username**: SableAradia

**World / Campaign / RPG Character / Manuscript Title**: Game of Tomes, Toy Soldier Saga

**Feature**: Article Search (Athena)

**Related URLS** (To public & visible pages add screenshots otherwise): (See screenshots)

**Describe the Issue**
When a Character article is searched in the Article Search in Athena, it seems to be displaying twice. They are not two different articles; they are otherwise identical, and any changes made to one is made to the "other" as well, which I tested by editing one of the "doubled" articles, by publishing when it had been a draft. The URLs and all other information are identical, which suggests it's a "phantom" that's appearing somehow. Testing it in another world (Toy Soldier Saga,) the issue only seems to be affecting Character articles that were personally created, not Character articles that are automatically generated by the RPG functions (see Screenshot 2022-05-30(4), "Selene Wintermist Sunfall" - which was created by me for SummerCamp last year - as opposed to "Selene Wintermist" - which was automatically created from my RPG character.)

**To Reproduce**
1. Go to Athena
2. Click on the Search bar above the article list
3. Search any Character article that was created from the Dashboard
4. See error (doubled article listing)

**Expected behavior**
I expected that each Character article would only appear in the listing once.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![2022-05-30](https://user-images.githubusercontent.com/92393446/171079869-0738293f-23f8-408e-b11a-c9edbeebb410.png)
![2022-05-30 (1)](https://user-images.githubusercontent.com/92393446/171080016-1d6cb965-8c8a-4095-9ac4-2dfaa35dcdd9.png)
![2022-05-30 (2)](https://user-images.githubusercontent.com/92393446/171080025-dd68bbe7-5f74-4ba6-860b-fd363df63cb2.png)
![2022-05-30 (3)](https://user-images.githubusercontent.com/92393446/171080032-7984462c-ce24-49aa-b27f-ecb03c55423d.png)
![2022-05-30 (4)](https://user-images.githubusercontent.com/92393446/171080044-e98291f0-f52c-4577-ab9c-7345367ce815.png)

**Comment by iamromeo** [comment]
Reading through the code this is only possible if the advanced search was activated. There is literally no other way for this to happen UNLESS there are actually two articles with the same name on that world,

**Comment by Kordishal** [comment]
It happens consistently with the advanced search disabled though. The trigger is when an article has the same title & tag. It then finds them both and returns them both. 

With advanced search activated this does not happen. I've made an article with the same word in the title, tag and content. It only displayed once.

**Comment by iamromeo** [comment]
Doh - found the reason - fixed will deploy today @Kordishal @SableAradia 
Thank you for reporting
