### ISSUE TITLE
unexpected Tagging behavior

### ISSUE THREAD

**Issue by Sebastianos-Ionnides** [worldanvil/worldanvil-bug-tracker#1059]
**World Anvil Username**:
Aelstyn

**World / Campaign / RPG Character / Manuscript Title**:
Cimmerian Shade
**Feature**: 
unexpected Tagging behavior

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I have a tag called #corax I also have a tag #corax-insights. if I use [tagged:corax|list|Corax] it pulls EVERYTHING with corax in the name. its not EXACTLY matching the text field, its just finding corax and adding it in. so I get cross tags into anything that has a foundational base. 

So if I have a species and Im tagging sub information in a heierachy. it doesn work

#Corax (the species)
#Corax-insights (their view of X, Y or Z)
#corax-cities (tags for their settlements)

etc.. it'll just lunp everything into the top tier tag. which I personally find unexpected behavior. 

**To Reproduce**
see above, easy to reproduce.

**Expected behavior**
[tagged:corax|list|Corax] should only return articles with specific tag #corax
[tagged:corax-insights|list|Corax] shoudl only return articles with speciic tag #corax-insights

**Screenshots**
![image](https://user-images.githubusercontent.com/94059525/171203194-a992d970-95d6-438b-854b-4c5cecb2104e.png)
![image](https://user-images.githubusercontent.com/94059525/171203498-cc500d07-5ab5-499d-b28c-fcc1769ef3dd.png)

**Comment by Kordishal** [comment]
Although it might be unexpected, this behavior is intended as it is. Exactly to be able to create compound tags and match them all with a single tag.

**Comment by Sebastianos-Ionnides** [comment]
oh thats unfortunate because you cant make relationships easily and call specific ones to create a proper tagging hierarchy.

never seen tags work like this in azure, aws, etc. filters are always specific.   it sucks, but oh well.
