### ISSUE TITLE
Account upgrade does not reflect on website

### ISSUE THREAD

**Issue by jimmyjansen93** [worldanvil/worldanvil-bug-tracker#1060]
**World Anvil Username**: tinyjim93

**Describe the Issue**
A clear and concise description of what the issue is.

**To Reproduce**
1. Get yearly 'Guildmaster' subscription
2. Pay for it
3. See in [account settings](https://www.worldanvil.com/dashboard/user/account) that you are still 'freeman'
4. See [Active Subscriptions](https://worldanvil.onfastspring.com/account/mmgVhv8PQ-W2njo9a6HJxw/I8hFFI0pSFc) that you should be 'Guildmaster'

**Expected behavior**
To be upgraded to 'Guildmaster'

**Screenshots**

<details>
<summary>Subscription</summary>

![Screenshot 2022-05-31 at 20 12 42](https://user-images.githubusercontent.com/12512737/171256160-83060079-0e33-444f-ae96-d3fc8924b2fe.png)

</details>

<details>
<summary>Guild status</summary>

![Screenshot 2022-05-31 at 20 13 19](https://user-images.githubusercontent.com/12512737/171256262-f12a52e9-dc51-44f5-9f6c-f4a396d0563a.png)

</details>

**Comment by Kordishal** [comment]
For account and billing issues please email `contact@worldanvil.com`. This isn't a bug, but a billing / account issue.

**Comment by jimmyjansen93** [comment]
Then the problem, which is a developer problem, is that the email address is not properly linked on the website. I have been looking extensively for a contact address and was unable to find it.
