### ISSUE TITLE
Clicked save, got error screen, work lost

### ISSUE THREAD

**Issue by CEPOsbourne** [worldanvil/worldanvil-bug-tracker#1061]
**World Anvil Username**: C.E.P. Osbourne

**World / Campaign / RPG Character / Manuscript Title**:The Ring

**Feature**: Meta

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Spent some time working on my world meta (two hours or so), clicked save, redirected to an error screen, all work lost.

**To Reproduce**
Steps to reproduce the behavior:I don't know?  Is there a timer on how long I can stay logged in without clicking a button or loading a new screen?  I was just typing in the first three windows of the world meta.  I'm slow, so it took me a couple of hours to put in those paragraphs.

**Expected behavior**
The expected behavior would have been for the few paragraphs I'd typed out to be saved.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Hi!
That is very frustrating, but there isn't really something we can do. A few people reported some server issues earlier so you might have run into that.

You should always safe your work regularly and not let it sit in just a browser window for several hours. In the future, hopefully the meta will get auto-save as well, but until then you need to make sure to save regularly or write somewhere else and then copy over to World Anvil.
