### ISSUE TITLE
Plato editor on RPG character fields has color input disabled even for Grandmasters

### ISSUE THREAD

**Issue by LadyxLily** [worldanvil/worldanvil-bug-tracker#1062]
**CaptainRose**:

**account**:

**grandmaster acess**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I paid for my grandmaster membership in April, and still can't access any of the features.  I have no access to family trees, diplomacy maps,  colored text,  ect. 
![Screenshot_20220527-211819](https://user-images.githubusercontent.com/106656540/171357699-14b8136d-9fcb-4ab4-8582-c48c7a038943.png)

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
That is just the editor that has a bug apparently and only on characters. Family trees and diplomacy webs are definitely available to Grandmasters and working as intended. Please come by the Discord or check on the Codex if you can't find how to use them!

https://www.worldanvil.com/w/WorldAnvilCodex/a/family-trees

https://www.worldanvil.com/w/WorldAnvilCodex/a/diplomacy-webs

**Comment by LadyxLily** [comment]
> That is just the editor that has a bug apparently and only on characters. You can just manually add colors BBCode or switch to the recommended editor where this bug doesn't happen. As the Plato editor will be reworked at some time this will not be addressed at this time.
> 
> https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors
> 
> Family trees and diplomacy webs are definitely available to Grandmasters and working as intended. Please come by the Discord or check on the Codex if you can't find how to use them!
> 
> https://www.worldanvil.com/w/WorldAnvilCodex/a/family-trees
> 
> https://www.worldanvil.com/w/WorldAnvilCodex/a/diplomacy-webs

I've already read through these pages.  In the case of family trees,  I don't have a relationships tab to click on.  Tried on both mobile and desk top.
