### ISSUE TITLE
Presentation search only returns content results in some cases

### ISSUE THREAD

**Issue by AmeliaNite** [worldanvil/worldanvil-bug-tracker#1063]
**World Anvil Username**: amelianite

**World / Campaign / RPG Character / Manuscript Title**: Darkness Moon Chronicles

**Feature**: The search system update

**Related URLS** (To public & visible pages add screenshots otherwise): [Darkness Moon Chronicels presentation view](https://www.worldanvil.com/w/darkness-moon-chronicles-amelianite)

**Describe the Issue**
Some of my articles have special characters in the titles and even with using Unicode, I can't **type** the letters needed to get the proper articles to appear (I've tested this and it doesn't work). So, when the search system update was implemented, I was overjoyed as I could _finally_ search for my articles if I put certain tags in them.

I went to add the tag "keith" to my article "Kěith Cheonsa" since the title obviously has a special character in it. It added fine until I went to test to see if the tag would pull up. It did not. Instead, it pulled up a few articles that _did_ have the word "keith" in the title and I was okay with that via the "The global search now searches for TITLE and TAG only." But then I noticed the other articles popping up was _not_ tagged nor did they have the word in the title.

**To Reproduce**
1. Add tag to article
2. Go to presentation view
3. Type tag in search bar

**Expected behavior**
Tags are not pulling up via the presentation view search bar.

**Screenshots**
![Screenshot (37)](https://user-images.githubusercontent.com/88216660/171362111-65575a8a-cc04-43e1-90ee-342c789906e6.png)
![Screenshot (38)](https://user-images.githubusercontent.com/88216660/171362113-dbe86057-cf97-4852-a7ac-9ba9671fad15.png)

**Comment by AmeliaNite** [comment]
They contain the term "Kěith," which is the word with the special character, but none of the articles use the word "Keith," which is _without_ the special character.

**Comment by Kordishal** [comment]
As far as I can tell all searches on World Anvil can now match special characters with their base characters all the time. So I am pretty sure the issue is related to the presentation search currently not displaying title / tag matches in some cases.

**Comment by Kordishal** [comment]
Because its not entirely correct. The presentation search does return the correct results if there are no articles with the word in the content. The presentation search still returns content searches and these currently replace the title / tag returns. It is a bug and not working as intended.

**Comment by AmeliaNite** [comment]
Then what can be done? Is there a plan to fix it in the near future?

**Comment by Kordishal** [comment]
Dimitris will have to say. I just help clarify issues (I am SoulLink on the Discord ;))

**Comment by iamromeo** [comment]
This should now be resolved. The Presentation search should now 
- List By Title and Tag
followed by 
- List by Contents
