### ISSUE TITLE
Google Drive PDF returns Forbidden even if its set to be public sharing

### ISSUE THREAD

**Issue by rjoshuaw** [worldanvil/worldanvil-bug-tracker#1065]
**World Anvil Username**:
The 3D Printed Game Master

**World / Campaign / RPG Character / Manuscript Title**:
Empires Fall

**Feature**: 
PDF Linking in Articles

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I found this post for linking PDFs in articles by World Anvil: https://blog.worldanvil.com/2022/03/02/pdf-viewer-embed-pdfs-on-world-anvil/

In attempting to do so I created an article to a google drive hosted pdf with a public link
[pdf:https://drive.google.com/file/d/1g340q2I1zhyqAJ-8GWCEb6-K2P570kit/view?usp=drivesdk]

On World View however, I get a '403 Forbidden Message' when clicking on my article.

**To Reproduce**
See above and screenshots
I reported this on Discord and was told to post it as a bug report.

**Expected behavior**
![wapdflinkerror2](https://user-images.githubusercontent.com/106838451/171935230-28b1a010-2f10-4deb-b67d-46a75877a02c.PNG)

Link to externally hosted PDF for article
**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![wapdflinkerror](https://user-images.githubusercontent.com/106838451/171935007-869079dc-51f6-4c91-be97-de87cdea3a2b.PNG)

**Comment by iamromeo** [comment]
Sadly this is not on our end but on Google's end. We cannot control what they give access to.
