### ISSUE TITLE
Sticky notes editing makes text very small and hidden behind other text.

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#1066]
**World Anvil Username**: SoulLink

**Describe the Issue**
When editing some text in a sticky note after there is already some text in it, the text becomes very small and is hard to see. It is also hidden behind the old text which makes it even harder to see what you are doing. You are basically editing blind!

**To Reproduce**
1. Create sticky note
2. Add some text to sticky note
3. Deselect sticky note.
4. Double click sticky note.
5. See small text behind big text.

**Expected behavior**
It really shouldn't be so difficult to edit sticky notes ;)
And I am sorry should this already be on your ToDo list. I know I reported it on the channel back when it was in Alchemists, but it has been a while and I saw its not reported here.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/14262536/171936002-8bbe9ad2-c3a2-40de-bd13-0701846eb61c.png)

**Comment by Duranzno** [comment]
Cannot replicate the issue, can you check again? when you have time of course, no hurry

**Comment by Kordishal** [comment]
Still happening yeah. Created a new one too:
![image](https://user-images.githubusercontent.com/14262536/175652300-119a165b-a194-44e9-a6e5-36ddaf111b84.png)

Happens in a private window too. And CTRL+F5 for refresh. So its definitely happening.

**Comment by iamromeo** [comment]
This still cannot be replicated - we are going through all browsers / OS and we cannot see this happening the way it is described.
