### ISSUE TITLE
Spellcheck mode changes are not saved while in spellcheck mode in world settings.

### ISSUE THREAD

**Issue by txspro** [worldanvil/worldanvil-bug-tracker#1067]
**txsproninga**:

**Arcadian imperium**:

**Describe the Issue**
 you go to dashboard and into introduction setting, I'm editing my introduction and in go into spell Check mode, every time I save changes after editing two things and staying in that mode, it reverts back to what it was before, I don't know when this happen, but I believe i lost 5 revisions before I realize  it and they weren't small and that is stupidly frustrating to deal with

**Expected behavior**
i figure it would just save the changes I made, not revert my editing to what it was.

**Screenshots**

![Screenshot (13)](https://user-images.githubusercontent.com/106858799/171987059-96cfdc79-43b5-40c4-83b6-cecb5bf8a333.png)
![Screenshot (14)](https://user-images.githubusercontent.com/106858799/171987064-9617edbd-ae33-42c5-b534-d9c046e77b1d.png)

the highlighted parts

**Comment by Kordishal** [comment]
Don't save while you are in spellcheck mode. Spellcheck mode works by adding all the content to a separate field. Once you close the spellcheck mode the changes are applied to the actual input field. Before that they are only stored in that separate field. 

In that sense this is working as intended.
