### ISSUE TITLE
Multiple tables are not loading on pages, but they will in my dashboard.

### ISSUE THREAD

**Issue by GambetTV** [worldanvil/worldanvil-bug-tracker#107]
**World Anvil Username**: Gambet

**World / Campaign / RPG Character / Manuscript Title**: https://www.worldanvil.com/w/the-chords-of-chaos-gambet

**Feature**: Tables

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/the-chords-of-chaos-gambet/a/armor-article
https://www.worldanvil.com/w/the-chords-of-chaos-gambet/a/adventuring-gear-article
https://www.worldanvil.com/w/the-chords-of-chaos-gambet/a/weapons-article

**Describe the Issue**
Most of my tables are not loading when posted into a normal article. They just say they're loading forever. I can go into the table directly in my dashboard under Tools > Tables and they work just fine.

**Comment by Kordishal** [comment]
![image](https://user-images.githubusercontent.com/14262536/112715014-d78a1700-8edd-11eb-8bb4-a86e7fbc4a27.png)
The table fails to load if there is no description set, but it is configured to display.

**Comment by Kordishal** [comment]
In addition to that, the description field now tries to autosave every time you enter something.
