### ISSUE TITLE
Lost Whiteboard data

### ISSUE THREAD

**Issue by MyschaC** [worldanvil/worldanvil-bug-tracker#1071]
**World Anvil Username**: Myscha

**World / Campaign / RPG Character / Manuscript Title**: World is Dreamscape

**Feature**: Whiteboard

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is. 
I lost the data entered on two whiteboards. They have gone back to one of the earliest versions I was working on. Also, depending on the computer I use, the whiteboard actually shows a different version. So an earlier version on my laptop vs a little bit later version on my desktop. But I was many many version in already. My story line whiteboard even went back and added the original writing form WorldAnvil when you first create a whiteboard, so it deleted my work and replaced it with the info about sticky notes and arrows. Is there a way for me to retrieve my lost data?

**To Reproduce**
Steps to reproduce the behavior: NA

**Expected behavior**
I expected all data entered and saved on the whiteboard to remain.
**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Screen Shot 2022-06-07 at 09 48 13](https://user-images.githubusercontent.com/107057005/172410671-f0c88f7a-6988-4d78-a0fe-4fa2530ec468.png)

**Comment by iamromeo** [comment]
We have made updates that lowered the possibility of this happening again 
1. I will suggest that you try to work on a single window when possible and try not to keep your whiteboard open on other devices because that might override changes made elsewhere.
