### ISSUE TITLE
Help chat cannot be dismissed / moved

### ISSUE THREAD

**Issue by Homunculus023** [worldanvil/worldanvil-bug-tracker#1075]
**World Anvil Username**
Poe the Homunculus:

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 
Help Bubble

**Related URLS** (To public & visible pages add screenshots otherwise):
![image](https://user-images.githubusercontent.com/107209476/172907694-71db39b9-79c7-4988-8760-f2ae91823c95.png)

**Describe the Issue**
A clear and concise description of what the issue is.
The help bubble and banner does not go away nor can I move it.  It blocks the left banner

**To Reproduce**
1. Go to '...' Anwhere
2. Click on '....' nothing
3. Scroll down to '....' left side scroll bar

**Expected behavior**
Remove the help bubble

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/107209476/172907928-cb8dfc6c-916e-4372-be17-fadf6b841e87.png)

**Comment by iamromeo** [comment]
This might be a lack of feature but not a bug. There is a plan to allow the removal of it - but will not be handled as a bug.
