### ISSUE TITLE
CORS policy conflict

### ISSUE THREAD

**Issue by DusterFox** [worldanvil/worldanvil-bug-tracker#1077]
**World Anvil Username**: DusterFox

**World / Campaign / RPG Character / Manuscript Title**: Gaialon

**Feature**: Dashboard Interface

**Related URLS** (To public & visible pages add screenshots otherwise):
https://cdn.discordapp.com/attachments/548671712280051732/984457926301331536/unknown.png
https://cdn.discordapp.com/attachments/548671712280051732/984458105637175307/unknown.png

**Describe the Issue**
Unable to load Category sidebar while on certain networks. Receive the following errors: 

"Access to XMLHttpRequest at 'https://www.worldanvil.com/world/athena/category/index?_sm_byp=iVVN66ttt1RKLLfG' (redirected from 'https://www.worldanvil.com/world/athena/category/index%27) from origin 'https://www.worldanvil.com/' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."

"Access to XMLHttpRequest at 'https://www.worldanvil.com/world/explore/load/categories?_sm_byp=iVVN66ttt1RKLLfG' (redirected from 'https://www.worldanvil.com/world/explore/load/categories%27) from origin 'https://www.worldanvil.com/' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."

Access to XMLHttpRequest at 'https://www.worldanvil.com/notification/count?_sm_byp=iVVtWFHs6nV72f4S' (redirected from 'https://www.worldanvil.com/notification/count') from origin 'https://www.worldanvil.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

www.worldanvil.com/:1 Access to XMLHttpRequest at 'https://www.worldanvil.com/notebook/base?id=&_sm_byp=iVVtWFHs6nV72f4S' (redirected from 'https://www.worldanvil.com/notebook/base?id=') from origin 'https://www.worldanvil.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

www.worldanvil.com/:1 Access to XMLHttpRequest at 'https://www.worldanvil.com/dashboard/user/user/coin/check?_sm_byp=iVVtWFHs6nV72f4S' (redirected from 'https://www.worldanvil.com/dashboard/user/user/coin/check') from origin 'https://www.worldanvil.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
global.js?v=016535:1          GET https://www.worldanvil.com/dashboard/user/user/coin/check?_sm_byp=iVVtWFHs6nV72f4S net::ERR_FAILED

**To Reproduce**
Unknown

**Expected behavior**
All other features appear to be accessible

**Screenshots**
[If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!](https://cdn.discordapp.com/attachments/548671712280051732/984457926301331536/unknown.png
https://cdn.discordapp.com/attachments/548671712280051732/984458105637175307/unknown.png)

**Comment by iamromeo** [comment]
I am sorry but this is on the network not world anvil - There is not much we can do about that - 
This might be due ot interference by an external plugin since this is an internal call for us normally.
