### ISSUE TITLE
Cannot delete world

### ISSUE THREAD

**Issue by Zwergenmauer** [worldanvil/worldanvil-bug-tracker#1078]
**World Anvil Username**: Zwergenmauer

**World / Campaign / RPG Character / Manuscript Title**: Huek

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
In attempting to delete the world, the webpage goes to a 404 page, but then when logging back into WA, the old world and articles are still there. Perhaps I'm not doing something correctly or I have misunderstood the process needed to delete the world. 

**To Reproduce**
1) Go to Huek world
2) Open the Settings tab to configure the world
3) Click on the Delete World button to the right side

**Expected behavior**
I expected WA to refresh and the old world and its contents to no longer be part of the dropdown menu for my worlds. As it is, the worlds are still there. The process I showed above is recreated in the image order here; I did not include a pic of the 404 page, but rather followed the link on the 404 page back to the WA homepage. As you can see, the last image still shows the original world named under the WA list. I expected it to be deleted or not to show. 

**Screenshots**
![image](https://user-images.githubusercontent.com/107272120/173120197-59d5c9d0-a6e5-4f7a-831c-0a8b743a2e79.png)
![image](https://user-images.githubusercontent.com/107272120/173120295-7caff9da-8636-4f77-b96c-c862b8ee84ce.png)
![image](https://user-images.githubusercontent.com/107272120/173120476-22235ebd-9270-45e5-b752-5fea6f0f688c.png)

**Comment by Kordishal** [comment]
Hi! In order to delete the world you need to first delete some other resources:

- Delete the campaign
- Expel player characters
- Delete any manuscripts associated with the world
- Remove subscribers & co-authors.

After that it should work.
