### ISSUE TITLE
Maps don't work well on mobile devices

### ISSUE THREAD

**Issue by jakub-zwolakowski** [worldanvil/worldanvil-bug-tracker#108]
Hi! I've added my third map recently and I've noticed again, that although on my desktops everything works well, on my mobile (Chrome 89.0.4389.105) there are serious problems. The only way to make it work correctly is to switch to the "Desktop site" mode. Which is a workaround, but not a solution.

If this is not a common problem and you need the exact phone specs, let me know :)

### Hint
It seems that you are it using the Leaflet library. I've got a friend who has used it a few times. He diagnosed the problem as, most probably, badly defined viewports.

# Example

## Without the "Desktop site" option
Here are two screenshots (of [THIS MAP](https://www.worldanvil.com/w/straC5BCnica-na-rubieC5BCy-kubulozaurusrex/map/faa3cd56-65f3-45bf-a40a-5711264399ec)) where you can see that 1) by default it's not the "base" layer that is loaded, 2) the sidebar is taking half of the screen permanently, and 3) all the map markers are misaligned with the map:
![Screenshot_20210327-114012](https://user-images.githubusercontent.com/1905935/112718423-2db58500-8ef3-11eb-930a-cbb098649671.jpg)
![Screenshot_20210327-114105](https://user-images.githubusercontent.com/1905935/112718424-3443fc80-8ef3-11eb-88c1-573788f3e9ab.jpg)

## With the "Desktop site" option
And with the "Desktop site" option activated everything looks much better:
![Screenshot_20210327-114131](https://user-images.githubusercontent.com/1905935/112718453-6190aa80-8ef3-11eb-9adb-6c2e50fa79f3.jpg)

**Comment by iamromeo** [comment]
This is a known issue but it will not be addressed until the Atals update

**Comment by iamromeo** [comment]
@Kordishal that can be moved to Atlas
