### ISSUE TITLE
New chronicle is redirecting to old chronicle of the same name

### ISSUE THREAD

**Issue by Hanhula** [worldanvil/worldanvil-bug-tracker#1080]
**World Anvil Username**:
Hanhula

**World / Campaign / RPG Character / Manuscript Title**:
World: Istralar

**Feature**: 
Chronicles

**Related URLS** (To public & visible pages add screenshots otherwise):
Well, this is sort of the issue...
https://www.worldanvil.com/w/istralar-hanhula/chronicle/era-of-the-arcane-chronicle
![if2VKi9](https://user-images.githubusercontent.com/22137517/173201998-12c0c7fe-c311-4926-a780-bba57f459cf9.png)

**Describe the Issue**
During the Chronos beta, I created the main timeline of my world - the Era of the Arcane. Now that Chronos is out of beta, that old beta version has had its times shift around and it's a bit buggy, so I wanted to rename and recreate it. I renamed it to indicate that it was old, and created a new chronicle with the same name as the old one.

Unfortunately, the old one did not update its link when its name was changed, and still directs me to the old chronicle. I cannot seem to access the new one, and I'm worried that deleting it will delete the old chronicle as well. 

**To Reproduce**
1. Go to Timelines
2. Create a chronicle named 'Era of the Arcane'
3. Rename this chronicle after creation
4. Create a new chronicle named 'Era of the Arcane'
5. Try to edit this new chronicle - you will be redirected to the old one

**Expected behavior**
I expected the URL for my chronicle to update according to its name.

**Comment by iamromeo** [comment]
That is a known issue - I was not expecting it to pop out on day 0 for anyone - I will be handling it with the new week.

**Comment by iamromeo** [comment]
@Hanhula you should be able to delete your old chronicle without affecting the new. Just go ahead and delete the one you do not want.

**Comment by Hanhula** [comment]
@iamromeo Am I supposed to be able to access the new one? They're still both directing to the same URL.
