### ISSUE TITLE
Chronicles White Screens When Search for Articles Yields Long List

### ISSUE THREAD

**Issue by SolarCat02** [worldanvil/worldanvil-bug-tracker#1081]
**World Anvil Username**: SolarCat

**World / Campaign / RPG Character / Manuscript Title**: Vazdimet

**Feature**: Chronicles

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/vazdimet/chronicle/chronicles-of-vazdimet-chronicle

**Describe the Issue**
When adding an article to an event on Chronicles, if there are too many possibilities returned by the first three letters typed it white screens, requiring a refresh to reload Chronicles (and forgetting any unsaved information).
Copy-Pasting the full article name will bypass this as it reduces the number of articles returned.
I don't know the minimum required to cause this. I was trying to add a link to the first chapter of my novel, which has 44 chapters. so I'm not surprised it is having trouble. (The rest of WorldAnvil does not have this issue though, so I thought I'd mention that Chronicles does).

**To Reproduce**
1. Go to 'Chronicles' and create or edit an event
2. Pick the 'Links' tab
3. Click on '+ Link Article' and begin typing the name of an article with lots of similarly-titled articles
4. See error - Chronicles white screens

**Expected behavior**
I expected it to show a list of possible articles to link, but I think the fact it is also loading the headers for the articles is making it crash.

**Screenshots**
I don't think a screenshot will help in this case, it's literally just a white screen when the error kicks in.

**Comment by iamromeo** [comment]
@SolarCat02 can you give us some more infromation on this so we can test. How may articles were there :) and which world / example string.

**Comment by SolarCat02** [comment]
This was for my world Vazdimet.
I began typing my full article name, and it starts searching as soon as you get three letters in which in my case was "In " since I was searching for "In Spite of the Inevitable, Chapter 1".

As I mentioned in the original report, there are 44 chapters so it was trying to pull all 44 and their headers, plus my plot article. Which is a lot.

This is a very fringe case. I don't know the minimum number of articles you need to trigger it.

**Comment by iamromeo** [comment]
Cool thank you - we will check :)
