### ISSUE TITLE
Chronos Does Not Recognize Variables

### ISSUE THREAD

**Issue by SolarCat02** [worldanvil/worldanvil-bug-tracker#1082]
**World Anvil Username**: SolarCat

**Chronicle Title**: Chronicles of Vazdimet

**Chronos System**
https://www.worldanvil.com/w/vazdimet/chronicle/chronicles-of-vazdimet-chronicle

**Describe the Issue**
Variables do not render in Chronicles.

**To Reproduce**
1. Create or edit a Chronicle event to include a variable.
2. View the event to see the variable doesn't render.

**Expected behavior**
I expected the Variable to render the way it does elsewhere.

**Screenshots**
![image](https://user-images.githubusercontent.com/65487082/173209802-1737424b-29d5-4c11-9f97-3f75c177a311.png)
Hopefully that actually uploaded.

**Comment by iamromeo** [comment]
Not a feature
