### ISSUE TITLE
Chronos Does Not List Months as65 

### ISSUE THREAD

**Issue by SolarCat02** [worldanvil/worldanvil-bug-tracker#1083]
**World Anvil Username**:

**Chronicle Title**:

**Chronos System**

**Describe the Issue**
A clear and concise description of what the issue is.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
I am not sure what this means. There is no description.
