### ISSUE TITLE
Chronos Does Not List Months as Default Unit of Time

### ISSUE THREAD

**Issue by SolarCat02** [worldanvil/worldanvil-bug-tracker#1084]
**World Anvil Username**: SolarCat

**Chronicle Title**: Chronicles of Vazdimet

**Chronos System**

**Describe the Issue**
The drop down shows Minutes, Hours, Days, Years, Decades, etc but does not list Months as a duration option. This means if you have a lot of events in the same year you either have them all lumped together or spread out across days.

**To Reproduce**
1. Go to 'Chronicle Settings'
2. Click on the 'Time & Date' tab
3. Scroll through the 'Default Unit of Time'
4. See the list jump from Days to Years

**Expected behavior**
Is there a reason Months was excluded?

**Screenshots**
![image](https://user-images.githubusercontent.com/65487082/173210108-93950d34-56be-40ad-90e8-68e49a91bcb9.png)

**Comment by iamromeo** [comment]
Not a feature, it will not be.
