### ISSUE TITLE
Chronicles doesnt scale correctly

### ISSUE THREAD

**Issue by Aethelred-The-Ready** [worldanvil/worldanvil-bug-tracker#1085]
**World Anvil Username**: AethelredTheReady

**World / Campaign / RPG Character / Manuscript Title**: Any of them?

**Feature**:  Chronicles

**Related URLS** (To public & visible pages add screenshots otherwise): 

**Describe the Issue**
When using alternate webpage scales (like I have to) the chronicles timeline manager and side buttons overlay each other or get hidden off screen, making them impossible to see in the timelines case. The posted image doesnt scroll any further down

**To Reproduce**
1. Make a chronicle
2. Set scale to be something greater than 120%
3. Make another timeline
4. Try to see the lowest line of the new timeline

**Expected behavior**
Should be able to scroll to the bottom timeline line and the buttons should move out of each others way

**Screenshots**
![image](https://user-images.githubusercontent.com/26744043/173212269-ec6e1def-5375-43b2-be07-03a492a99209.png)

**Comment by iamromeo** [comment]
User forced scaling is not supported and it will not be supported.
