### ISSUE TITLE
Chronicles - Memory Error

### ISSUE THREAD

**Issue by graylion-wa** [worldanvil/worldanvil-bug-tracker#1087]
**World Anvil Username**:

Graylion

**World / Campaign / RPG Character / Manuscript Title**:

Creation

**Feature**: 

Chronicles

**Related URLS** (To public & visible pages add screenshots otherwise):

https://www.worldanvil.com/w/creation/chronicle/ptolus-chronicle-chronicle#

**Describe the Issue**
A clear and concise description of what the issue is.
After switching across time units for examples years, days, minutes the Tab & Chronicle froze and became unresponsive. See attached memory error

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

![image](https://user-images.githubusercontent.com/79761754/173219011-ed404d5e-175d-4af0-98fe-75c64bfb407a.png)

**Hardware**

ASUS ROG 
13.4 Touchscreen
AMD Ryzen 9 6900
16GB Ram
NVidia GeForce RTX3050 TI
VRam 4GB
Dedicated Graphics Card

**Comment by graylion-wa** [comment]
I am seeing the memory error mainly when switching from any time unit to Days. I am able to switch to all other units without the error.

**Comment by graylion-wa** [comment]
![image](https://user-images.githubusercontent.com/79761754/173221531-60ce1d71-02f7-4bfd-99ac-6d4eb126fa5a.png)

**Comment by graylion-wa** [comment]
Replicated the switch to Days Units on multiple devices and multiple browsers.

Desktop Chrome
Desktop Firefox
Android Chrome
Android Firefox

**Comment by Xuroth** [comment]
Is this in Days granularity?

**Comment by Xuroth** [comment]
Hmm... I'm curious if this is a css issue (because the size is calculated and required for calculations like the UTD bar). Can you send me the css you use to alter the layout for mobile? (DM on Discord, preferably)

**Comment by graylion-wa** [comment]
CSS file sent on Discord.
