### ISSUE TITLE
Image Manager Sidebar Documentation Improvements

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#109]
**World Anvil Username**: SoulLink
**Feature**: Apollo

**Describe the Issue**
The current description is very focused on newness and upcoming documentation. As this documentation actually exists I believe it would be helpful to change this to something more descriptive :) (Although I always enjoy the enthusiasm in your messages Dimitris!)

**New Version**

### Images & Files Manager (Codename: Apollo)
This is where you upload & organize your images for World Anvil. By default, the 25 most recently uploaded or edited images are shown. You can always return to this view by selecting the Recent list on the left side.

The **Favorite** list can be populated by pressing the star icon when an image is selected. 

The search bar searches through all the titles of your images to find a specific image. So make sure to always give good titles to your images!

To organize your images select a world on the left side and create gallery folders. Assign images to one or more galleries. Galleries can be attached to articles and form the basis for the image carousel.

Remember to fill in the image metadata for your images if you use works of others!

Images used in **maps** need to be uploaded via the map interface and will then show up here. 

**Screenshots**
![image](https://user-images.githubusercontent.com/14262536/112729846-9a9a4080-8f2e-11eb-9055-7efec0275c62.png)

**Comment by Kordishal** [comment]
Also purely out of curiosity... Why is it called Images **& Files** manager?

**Comment by iamromeo** [comment]
> Also purely out of curiosity... Why is it called Images **& Files** manager?

Because this is other things will be hosted as well (fonts/pdfs)
