### ISSUE TITLE
BBCode generated by the embed button for a chronicle is malformed

### ISSUE THREAD

**Issue by oldmicah** [worldanvil/worldanvil-bug-tracker#1090]
World Anvil Username:
oldmicah

World / Campaign / RPG Character / Manuscript Title:
World Altonne SSS. (https://www.worldanvil.com/w/altonne-sss-oldmicah)

Bug 
Chronicle

Describe the Issue
Link generated for a chronicle is malformed.

To Reproduce

	•Go to timelines
	•click on the chronicle name
	•you get this link: [chronicle:168ed499-42af-402f-a766-0137bc80eac7]History of Altonne Chronicle[/timeline]
	•(link fails bc terminated by timeline instead of chronicle tag) 

Expected behavior
link should be [chronicle:168ed499-42af-402f-a766-0137bc80eac7]History of Altonne Chronicle[/chronicle]

**Comment by iamromeo** [comment]
Fixed and deploying
