### ISSUE TITLE
Chronicle Events not saving dates

### ISSUE THREAD

**Issue by PrincessHoneytea** [worldanvil/worldanvil-bug-tracker#1092]
**World Anvil Username**: PrincessHoneytea

**World / Campaign / RPG Character / Manuscript Title**: The Drumlin (Private World)

**Feature**: Chronicles

**Related URLS** (To public & visible pages add screenshots otherwise): N/A, everything is private

**Describe the Issue**
I created a Chronicle and have tried to set the first event of the timeline, but whenever I save the event it resets the date of the event to the 1st day of the 1st month on a different year than I set it to. I.E. I set the Event to "Day 13, Month 2, Year 1", but it gets reset to "Day 1, Month 1, Year 6" or "Day 1, Month 1, Year 0".

**To Reproduce**
1. Go to Private Chronicle I created yesterday after the twitch livestream in my Private World
2. Click on 'Create an Event' -> Either right clicking the timeline or in event manager
3. Set name, description, date, event type, event importance, timeline lane -> no tags or map marker
4. Click save -> the event is reset to a different date than I set it to

**Expected behavior**
I expected the event to save at the exact date I set it to.

Thank you so much for your help!!

**Comment by Kordishal** [comment]
When setting the date there is an extra Save Date button. However, due to the layout that button can be hidden away and you might have to scroll down after changing the date.
