### ISSUE TITLE
Can you add Achtung! Cthulhu?  Thanks.

### ISSUE THREAD

**Issue by DrThunderGod** [worldanvil/worldanvil-bug-tracker#1093]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Achtung! Cthulhu**:
**Achtung! Cthulhu** (Name under which it should be listed on World Anvil):
**DrThunderGod**:

**Website**:

**Logo Image Link**:

**Logo Usage Terms (URL)**:

**Comment by iamromeo** [comment]
Added
