### ISSUE TITLE
Chronicles - Unable to Authenticate

### ISSUE THREAD

**Issue by graylion-wa** [worldanvil/worldanvil-bug-tracker#1095]
**World Anvil Username**:

Graylion

**World**:

Creation

**Feature**: 

Chronicles 

**Related URLS** 

https://www.worldanvil.com/w/creation/chronicle/ptolus-chronicle-chronicle

**Describe the Issue**

Player in my game and world sent me this. He gets it every time he visits my chronicle. Yes he logged in.

**Screenshots**

![7fb7fdf429ce070d54b530f2c58a8ca28e8e1921-14.jpg](https://user-images.githubusercontent.com/79761754/173303404-a0c32ea9-e69f-49e5-981b-113675450340.jpg)

**Comment by Xuroth** [comment]
Heya! I just wanted to ask a couple questions to hopefully narrow down the cause. Is the player set to a subscriber group or a writer/co-author? (or both?) Also, is the player in multiple subscriber groups?

Looks like the chronicle is actually loading, so it makes me think the bug here is just an erroneous message (but one that may cause confusion).

**Comment by graylion-wa** [comment]
The player has about a dozen subscriber groups. 

Upon his first visiting the chronicle, the chronicle is public and there were no private timelines. I have added a specific private timeline for one of his subscriber groups, however this was after the fact.

The player is a Writer | Advanced Writer.

Let me know of you need anything else.

**Comment by Xuroth** [comment]
I'm not able to reproduce currently. Do any of your other players experience this issue? Has the affected player(s) tried with a different browser (or device, like a desktop or non-mobile one)?

**Comment by sydcatkitcat** [comment]
This happens whenever I try to create a chronicle, let alone link to it

**Comment by Xuroth** [comment]
This appears to be a different issue, since the chronicle is not loading at all. Can you please create a separate issue here? (So I may track and troubleshoot without missing it)

**Comment by sydcatkitcat** [comment]
Sorry, I can't. I have tried several times, but the Submit button is always inactive. Is there a support email I can contact?

**Comment by Xuroth** [comment]
Sadly not (I am Chronicles support and dev) but I'll make a note. Are you on Discord? If so, I'd like to ask a couple questions.

**Comment by Xuroth** [comment]
@graylion-wa I believe this is an issue with the mobile browser (per our DMs). Can you have the player try testing with another mobile browser, like Firefox or Chrome.

**Comment by graylion-wa** [comment]
Since the yellow banner will go away I have left this player to his own choice. He will not install other browsers ... well because ... they are watching. So moving along. 🤣

**Comment by Xuroth** [comment]
Gotcha. I will mark this closed for now. Feel free to reopen or ping if you find any more info relating to this issue!
