### ISSUE TITLE
Talk Widget 

### ISSUE THREAD

**Issue by graylion-wa** [worldanvil/worldanvil-bug-tracker#1096]
**World Anvil Username**:

Graylion 

**World**:

Creation

**Feature**: 

Talk Widget 

**Describe the Issue**

I would like to be able to dismiss or toggle the help talk widget off. This is a great feature for a new user or someone who is not involved in the World Anvil Discord. However after three years on Discord I am in the best of hands with the amazing community you have gathered.

Thank you

**Screenshots**

![Screenshot_20220614-033135_Chrome.jpg](https://user-images.githubusercontent.com/79761754/173588123-48463e23-19b2-4521-b52b-f988a1aa694c.jpg)

**Comment by iamromeo** [comment]
This is not a bug, it is a feature request.

**Comment by graylion-wa** [comment]
So the new feature which I find amazing for those who need it, lands on my very small screen. And now you recommend a feature request for me to get rid of it. 

I apologize for wasting the bug report but I will not be creating a feature request so it can sit and gain very little support. 

Thank you.

**Comment by graylion-wa** [comment]
It is very frustrating after 3 years to have to switch browsers and my process to get rid of this Talk-Widget which is a fantastic feature for new users and those that are not on Discord.

The frustrating thing is it being in the way on small screens. I have been using Android Chrome for 3 years and now must switch to Android Firefox to run a Script blocking extention to remove this from my work-flow.

Here are steps for others should they need this ...

![Screenshot_20220615-023849_Firefox.jpg](https://user-images.githubusercontent.com/79761754/173760631-19fa7547-b00a-444d-b937-48b8f47dd4ae.jpg)

![Screenshot_20220615-023814_Firefox.jpg](https://user-images.githubusercontent.com/79761754/173760676-23811395-09e7-4645-a5f1-8c38c1914bbb.jpg)

![Screenshot_20220615-023820_Firefox.jpg](https://user-images.githubusercontent.com/79761754/173760706-0478c821-e1fa-4c41-b03c-2e9db514d606.jpg)

![Screenshot_20220615-023927_Firefox.jpg](https://user-images.githubusercontent.com/79761754/173760791-f5afa4e6-f8cf-418c-b449-a79051b9d256.jpg)

![Screenshot_20220615-023927_Firefox.jpg](https://user-images.githubusercontent.com/79761754/173760928-9fe7e65a-732a-4a47-a9e1-01322fdad359.jpg)

**Comment by graylion-wa** [comment]
Added jsdelivr.net to trusted which controls the light and dark theme toggle

**Comment by Kordishal** [comment]
As it can now be disabled this is no longer necessary.

**Comment by graylion-wa** [comment]
Agreed it is awesome to have a toggle to turn off the chat widget and reclaim the very small mobile space.
