### ISSUE TITLE
Sub levels do not work correctly in lists

### ISSUE THREAD

**Issue by jerry2478** [worldanvil/worldanvil-bug-tracker#1097]
**World Anvil Username**: jerry247

**World / Campaign / RPG Character / Manuscript Title**: Syntravo

**Feature**: HTML Lists

**Related URLS** https://www.worldanvil.com/w/syntravo-jerry247/a/log-in-to-worldanvil-inside-foundry-article

**Describe the Issue**
Sub levels do not work correctly in lists
**To Reproduce**
Make a quick ordered list.
Make a sub-level using two dashes
View.

**Expected behavior**
making a sub item with quick ordered list only indents the item, it does not switch the number to a letter. Same happens in quick unordered lists; the bullet stays the same (black solid)

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/61919595/173915219-3c496495-3162-4408-98b2-964f29715e28.png)
![image](https://user-images.githubusercontent.com/61919595/173915233-416b9684-5b48-4d8b-a632-a0831ef4dda7.png)

**Comment by iamromeo** [comment]
I am sorry but this is not a feature of the quick lists as it stands
