### ISSUE TITLE
Subscriber groups for events in chronicles

### ISSUE THREAD

**Issue by dinomite2000** [worldanvil/worldanvil-bug-tracker#1098]
**World Anvil Username**: Dinomite

**World / Campaign / RPG Character / Manuscript Title**: Veltendanus

**Feature**: Chronicles

**Describe the Issue**
A clear and concise description of what the issue is.
When having one of my players check my chronicle, the events do not show up despite being set to the correct subscriber group. Everything else shows up, only the events on the timeline and in the map markers do not show up. They did show up when I set it to public, however, but they should have been showing up for my players with the subscriber group it was set to. 

**To Reproduce**
1. go to chronicles and create an event
2. make the event private, set to a certain subscriber group. 
3. member of a subscriber group would not be able to see the event unless it was set to public

**Expected behavior**
For the event to show up for the players.

**Comment by Xuroth** [comment]
Hello! This should be resolved now! Can you please confirm if it works as expected now?

**Comment by dinomite2000** [comment]
I will this evening when I'm home from work!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dinomite2000** [comment]
Actually, we managed to check. It seems to be working now. Thanks!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Xuroth** [comment]
No problem!
