### ISSUE TITLE
[Chronicles] Possible issue with setting Starting Loading Date

### ISSUE THREAD

**Issue by AC-Snow** [worldanvil/worldanvil-bug-tracker#1099]
**World Anvil Username**: A.C. Snow

**World / Campaign / RPG Character / Manuscript Title**: Revenge Princess

**Feature**: Chronicles

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/revenge-princess-ac-snow/chronicle/book-timeline-chronicle

**Describe the Issue**
A clear and concise description of what the issue is.
When I try to set the starting date to 1550, it tells me it is updated, but it still says 0 C.E. on the calendar, and if I go back into settings, it resets. I also set it to this date on start up. I also placed an event in 1624, but I can't see it on the calendar though it is in the event tab.

**To Reproduce**
Go to the side bar and click on chronicle settings then go to the time and date tab and down to chronicle start date. This is when I change 0 to 1550 by typing it manually into the year bar.

**Expected behavior**
The calendar will update, and the first date I see will be 0 January 1550.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
@AC-Snow have you clicked the SET DATE after altering the date?
