### ISSUE TITLE
Unbearable lag in the editor

### ISSUE THREAD

**Issue by IronicJuice** [worldanvil/worldanvil-bug-tracker#110]
**World Anvil Username**: marcuslau

**World / Campaign / RPG Character / Manuscript Title**: The Lands Under The Heavens

**Feature**: Article Editing

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
The editor is unbearably laggy. Editing articles takes ages, and mistakes often occurs when the editor ignores an "enter" input for example. Selecting text is very slow as well. I can highlight a chunk of text I want to delete or edit, and wait several seconds before the actual highlight shows up so I can see what I selected.
Most of the frustration comes from writing a sentence, and having to wait for the text to actually show up before I can review what I just wrote and edit it. Freewriting becomes quite tedious. 

I use the Brave browser, but I have the same issue when testing on Google Chrome

**To Reproduce**
1. Go to an article I want to edit
2. Write

**Expected behavior**
I would expect a text editor to not be this laggy

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Hello there @IronicJuice 
Sadly this is something I cannot reproduce on my end, it might have to do with your browser/the extensions on it or even the system you are on. 
But, I am assuming that you are talking about the WYSIWYG (correct me if I am wrong) 
If you are having issues with it for any reason you might to give a try on the other 2 editors 
- Legacy, the old and super "lean" version 
- Euclid the advanced editor focused on a clearer editing experience
You can switch between them via the interface settings here: 
thttps://www.worldanvil.com/dashboard/user/interface
