### ISSUE TITLE
Unable to delete character

### ISSUE THREAD

**Issue by Beadanza** [worldanvil/worldanvil-bug-tracker#1100]
**World Anvil Username**: Beadan

**World / Campaign / RPG Character / Manuscript Title**: Character called "Test Test" in my world The Ancient Nexus of Worlds

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/heroes/character/edit/basic

**Describe the Issue**
I'm new to World Anvil. I created a test character and a test campaign. I assigned the character called "Test Test" to the campaign and tested a session. After that, I deleted the campaign but saw that the character didn't delete. Now I can't delete the character as there is no red option under the section "Delete Character".
I started a test with Roc and it was suggested to log a bug report.

**To Reproduce**
1. Go to My Characters https://www.worldanvil.com/characters
2. Click on view for "test"
3. Click activate character to display the option "edit" on the left column
4. Click edit
5. Scroll to the bottom and look on the right column for "delete character"
6. Click the arrow and this should open up to be able to delete the character, but nothing is showing

**Expected behavior**
I want to completely remove/delete the "Test" character as I won't need it anymore.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![delete-char](https://user-images.githubusercontent.com/49292700/174056860-4e6bfb60-391f-4138-a4fd-dccf67148415.jpg)

**Comment by Beadanza** [comment]
I think I managed to solve it. I went under advanced options -> player characters.
In there I could click "expel" under the character test and it's now gone.
I don't know if that was the correct step, but it gave me the expected result at least.

If there is a different or better way, please let me know.

**Comment by Kordishal** [comment]
I do not believe there is a faster way when the character is in a world / campaign no.
