### ISSUE TITLE
All History/Timeline Articles have been deleted

### ISSUE THREAD

**Issue by eldianangel** [worldanvil/worldanvil-bug-tracker#1102]
**World Anvil Username**: Eldianangel 

**World / Campaign / RPG Character / Manuscript Title**: World: Elbrin, Campaign: Under The Dreamer's Flame 

**Feature**: Articles, History, Timeline

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When attempting to review historical events in the timeline I've created, no articles can be found. Furthermore, when trying to search articles, they've all been replaced with "Untitled" blanks 

**To Reproduce**
1. Go to '...' Articles
2. Click on '....' uncategorized articles

**Expected behavior**
To open articles and see the timelines I have made

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

![Screenshot_20220616-100059_Chrome](https://user-images.githubusercontent.com/107637021/174114970-94fe11fa-cb2e-4bc9-850d-9c8ca57e4072.jpg)

**Comment by Kordishal** [comment]
Hi! I am not sure what the problem is. How did you create these articles? From your steps it is not clear what you did to get where you are. 

Untitled articles are expected when they are created via the dashboard and then no title is set.

**Comment by iamromeo** [comment]
There is no such a thing as a history **article** Histories (or Historical Events) always were and still are under the **TIMELINES** menu.

**Comment by eldianangel** [comment]
Ah! That's exactly what I needed to find! That cleared everything up thank
you!
