### ISSUE TITLE
Pop-up pins missing

### ISSUE THREAD

**Issue by DandanAlpha** [worldanvil/worldanvil-bug-tracker#1103]
**World Anvil Username**: dandan alpha

**World / Campaign / RPG Character / Manuscript Title**: [Chronicle Planet](https://www.worldanvil.com/w/chronicle-planet-dandan-alpha)

**Feature**: Pins

**Related URLS** (To public & visible pages add screenshots otherwise): 
![image](https://user-images.githubusercontent.com/107647968/174151697-451c9303-b2b0-449f-acb4-6f641542abe4.png)
![image](https://user-images.githubusercontent.com/107647968/174151825-a71cc9fc-1989-49e7-add7-06948e0a0f72.png)
![image](https://user-images.githubusercontent.com/107647968/174151926-1f78df6a-3acf-4673-bab0-91891c673d1c.png)

**Describe the Issue**
When direct linking is activated the pop-up message doesn't appear when you hover over the pin. This makes it harder to use when you want to travel to other maps without already knowing where the pin leads to beforehand.  Especially when you have a road going of the map that you want to go to different maps (A pin leading to the region, a pin leading to the country, a pin leading to the continent etc) and there's no way to distinguish between the pins.

**To Reproduce**
1. Go to 'Edit marker'
2. Click on 'Click to enable direct linking'
3. Go to map

**Expected behavior**
To see the white pop-up while hovering and clicking the pin will go to the next map without opening the sidebar and having to click on "open map".

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
This is not a bug, this is a feature that was never developed. It is planned for Atlas :)
