### ISSUE TITLE
Updating a map always requires to select a map

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#1105]
**World Anvil Username**: SoulLink
**Feature**: Chronicle

**Describe the Issue**
When updating the settings of a map the new settings can only be stored if the map image is re-selected. 

**Expected behavior**
The currently active image should be preselected when editing a map so we don't have to do that every time.

**Comment by Xuroth** [comment]
@Kordishal I just released a patch for this. Can you test to verify that you no longer need to select the map image to change title/description/etc on maps?

**Comment by Kordishal** [comment]
Yep that works!
