### ISSUE TITLE
Deleting Sage Notifications

### ISSUE THREAD

**Issue by SolarCat02** [worldanvil/worldanvil-bug-tracker#1110]
**World Anvil Username**: SolarCat02

**World / Campaign / RPG Character / Manuscript Title**: Vazdimet/Fillimet

**Feature**: Sage Seminar Notification

**Related URLS** (To public & visible pages add screenshots otherwise): Just the notification list. 

**Describe the Issue**
When I deleted the Sage Seminar notification it deleted all the notifications under it, too. It was a mix of notifications - several articles, two status updates, a new follower on my world - but when I deleted the Sage Seminar the page refreshed and everything that had been underneath it was gone. 

This has never happened with the past Sage Seminar notifications, or any other notification. Just today's, but I checked in thr Discord and it wasn't just me so making a report.

**To Reproduce**
1. Go to 'Notifications'
2. Click on the 'delete' icon for the Sage Seminar notification 
3. See error - the page blinks and then all notifications below it disappeared

**Expected behavior**
I expected it to just delete the one I told it to delete, like what usually happens. 

**Screenshots**
Doesn't really apply in this case.

I love the Sage Seminar notification reminders and would still love to get them! It's just that today's had very strange behavior and I thought someone should know.

**Comment by graylion-wa** [comment]
When I deleted the Sage notification it was replaced with a single bugle icon and nothing else with it. I next deleted this bugle icon.

**Comment by iamromeo** [comment]
I cannot replicate this and there is no way to do a live test without sending another notification. There is nothing special about those notifications and the two bug reports above are not the same bug if the bug is there. 
Next time we have a Mass notification we will have to test on live. No results on development env.

**Comment by SolarCat02** [comment]
So... The notification I deleted, and the notifications underneath it that disappeared, returned this afternoon. They were still gone this morning but tonight they are back. O.o
