### ISSUE TITLE
Blank white map when viewed

### ISSUE THREAD

**Issue by N9Gaming** [worldanvil/worldanvil-bug-tracker#1111]
**World Anvil Username**: N9

**World / Campaign / RPG Character / Manuscript Title**: The Astral Foundation

**Feature**: Map

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/the-astral-foundation-n9/map/6745e233-dc7b-4051-a163-44ff8b8ee641

**Describe the Issue**
Despite appearing normal in the edit screen, my maps appear entirely white and non-visible when viewed. Image appears fine in thumbnails and the editor, and I am not certain what could be causing this. Discussed with SoulLink on the Discord about it who pointed me in the direction of reporting a bug.

**To Reproduce**
Simply open the map linked above, it should be white. In order to actually cause this to happen? I'm not certain. As I said any map I attempt to create ends with this result.

**Expected behavior**
Well, I would expect the map to be visible of course!

**Screenshots**
![editor](https://user-images.githubusercontent.com/54754536/174458935-e05e7abc-fca7-4fed-b9ec-446ded886283.PNG)

![viewed](https://user-images.githubusercontent.com/54754536/174458952-d1ad5468-3be9-4eeb-b0a6-97eaf7b592de.PNG)

**Comment by iamromeo** [comment]
```
[center][h1][small][url:https://www.worldanvil.com/w/the-astral-foundation-n9|tab]Events (WIP)[/url] • @[Missions](article:60aa6f4f-2d42-4120-82b3-00da016deea2) • [url:https://www.worldanvil.com/w/the-astral-foundation-n9/map/6745e233-dc7b-4051-a163-44ff8b8ee641|tab]Map[/url] • @[Locations](article:14378ac9-324a-4343-9a10-0291fa8b3d08) • [url:https://www.worldanvil.com/w/the-astral-foundation-n9|tab]Vehicles (WIP)[/url][/small][/h1]
 [/center]
 [hr]
 [justify][small][i]1951, the Cold War begins. Tensions rise between the two world super powers of the time; the United States and the Soviet Union. Each develops technological advances in aerodynamics and rocketry that both terrify and drive the opposing Nation to push their edge further; a deadly game of leap frog while Kerbal citizens of the world fear total Nuclear destruction should one side ever launch their newly developed weapons against the other. It is here when these terrifying tools of war spark an idea that would lead to the greatest race of all time: [b]the exploration of space.[/b][/i][/small][/justify]
 [hr]
 [center][b][url:https://www.youtube.com/playlist?list=PLKsgkXe7Cn8usHFu3DNKkIelaOolmt6nq|tab][b][color:#cccccc]For All Kerbalkind:[/color][/b] [color:#cccccc]A Cold War Era Alternate History KSP Multiplayer[/color] [b][color:#C10300]YouTube Series[/color][/b][/url][/center]
 [br]
 [br]
 [sub][i][center]Notice: some articles may not work properly on mobile browsers[/center][/i][/sub]
```

You world Description had an unclosed [b] which broke the HTML of the whole page (world description is loading on the initial sidebar of your map) 

I have removed the rogue [b] without a [/b] and it now works.
