### ISSUE TITLE
Some Heroes not showing up in articles

### ISSUE THREAD

**Issue by Sham404** [worldanvil/worldanvil-bug-tracker#1112]
**World Anvil Username**: Sham101

**World / Campaign / RPG Character / Manuscript Title**: After the Collapse

**Feature**: Heroes

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/after-the-collapse-sham101/c/miria-s-band-category
https://www.worldanvil.com/w/after-the-collapse-sham101

**Describe the Issue**
I have 5 players using the Heroes feature. Three of them are showing up with articles on the worldanvil which they can edit themselves. Two of them are not showing up, but their characters are showing up under the character list

**To Reproduce**

**Expected behavior**
The two characters to have articles they can edit like the other three

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Can you attempt to remove and then re-invite the affected player characters to your campaign?

**Comment by Sham404** [comment]
I have tried this with the Tora Armadul character, it looked like it successfully expelled her, she rejoined but still doesnt have a character page

**Comment by iamromeo** [comment]
I will need the links to these character hero profiles to investigate please :)

**Comment by Sham404** [comment]
The character i expelled and rejoined is https://www.worldanvil.com/hero/6c02a435-0563-4c99-a6ba-d4d162c78ca5
I am also having issues with this one not showing up https://www.worldanvil.com/hero/e5f377d3-41ba-4eb2-b33e-84b0bab9401b
This one is showing up as intended https://www.worldanvil.com/hero/d9732b6f-3e5c-4ef7-866f-91f6e8062e94

**Comment by iamromeo** [comment]
@Sham404 both these articles were deleted by you from your world, this is the reason they do not show up. I can bring them back but this is not a bug :)

**Comment by Sham404** [comment]
I dont remember doing that! Please can you restore them and i will check that the players are able to edit them etc

**Comment by iamromeo** [comment]
Both fixed :) You are all set!
