### ISSUE TITLE
On a world with just a chronicle the homepage does not render the timeline header.

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#1114]
**World Anvil Username**: SoulLink
**Feature**: World Homepage / Chronicle

**Describe the Issue**
This only happens if there are no timelines created in the world. As soon as there is a timeline the header is generated.

**To Reproduce**
1. Create new world
2. Create chronicle
3. Check homepage.

**Expected behavior**
There should be a heading for the chronicle.

**Screenshots**
![image](https://user-images.githubusercontent.com/14262536/174485038-0613633c-3512-4190-a985-169de44bdd75.png)
![image](https://user-images.githubusercontent.com/14262536/174485066-fed2867c-1d76-486d-a3c8-b70210bd751b.png)

**Comment by iamromeo** [comment]
Hmmmm INTERESTING! :D Lemme check the magixs

**Comment by iamromeo** [comment]
Fixed - will deploy later on :)
