### ISSUE TITLE
Weird bug that causes language code to appear in textbox

### ISSUE THREAD

**Issue by GGFaith** [worldanvil/worldanvil-bug-tracker#1116]
**World Anvil Username**: 
ilikeice

**Describe the Issue**
I'm having an issue with the textboxes in Worldanvil. When I write an entry in the textbox and save it, it saves what I wrote, plus an addition extra text that looks to be a code for translating. I've tried removing the code, but it just reappears when I view the wiki page and when I go bac editing.

This happened using Plato, Euclid works fine.

**To Reproduce**
Use plato to get the textbox entry, then go to anything that has textboxes. I'll use the timeline page for an example, but it does this to everything.

1. Go to timelines
2. Click on Create a new timeline
3. Scroll down to the textbox
4. write whatever
5. Click on save changes
6. Click on view event
7. You'll see the weird coded text
8. On top of that, if you back to edit, you'll see it in your textbox.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
This image is after I clicked view timeline.
![image](https://user-images.githubusercontent.com/107851327/174583769-13a4a09d-a5d7-42f0-b857-b78f01e1a3ec.png)
This is after I returned to the textbox.
![image](https://user-images.githubusercontent.com/107851327/174583996-38fb2ab8-b269-41ab-915d-b4c49a995547.png)

**Comment by iamromeo** [comment]
This is not an issue with World Anvil but with a plugin loaded by the browser interfering

**Comment by Kordishal** [comment]
You can remedy this by either disabling the problematic extension or by switching to the Euclid editor, which is not affected by this:

https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors
