### ISSUE TITLE
"-" in world name kills things.

### ISSUE THREAD

**Issue by Galygious** [worldanvil/worldanvil-bug-tracker#1117]
**World Anvil Username**:
Galygious
**World / Campaign / RPG Character / Manuscript Title**:
"Faerun - Steampunk"
**Feature**: 
delete and creating 5e character sheet article.
**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/faerun---steampunk-galygious
**Describe the Issue**
A clear and concise description of what the issue is.
while attempting to create a character sheet i kept recieving a un able to handle request error. all features on the account are enabled. attempted to delete the world and got an error 404. made a new world with a different name and these features worked so eventually noticed the only difference between the titles was the presence of a "-" in the world name. this breaks atleast these two prior mentioned features.
**To Reproduce**
create a new world with a "-" in the name.
go to statblocks section under advanced tools.
on the right clear the drop down for type of article and hit create a new sheet. 
select dungeons and dragons 5e character sheet.
click create sheet.
see the error that says unable to make.
proceed back to dashboard.
go to world settings and attempt to delete world
see 404 error.

**Expected behavior**
make a sheet using the dungeons and dragons character sheet template and delete the world.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by GorkamWorka** [comment]
@Galygious  i cannot reproduce either, can you please retry ?
