### ISSUE TITLE
Autolinker not opening

### ISSUE THREAD

**Issue by DBuswell158** [worldanvil/worldanvil-bug-tracker#1118]
**World Anvil Username**: DPRBuswell

**World / Campaign / RPG Character / Manuscript Title**: Arkanum

**Feature**: Autolinker

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/arkanum-dprbuswell/a/athanian-article
https://www.worldanvil.com/w/arkanum-dprbuswell/a/the-athanian-empire-ethnicity

**Describe the Issue**
The Autolinker will not open. I have included the two URLs above to show that there are simularities enough for the autolinker's feature, but when I click autolinker in either while editing, the loading bar goes across the top, but nothing pops up. 
With a help agent, I have tried: 

- Using a different browser (I am using Chrome)
- Disabling browser extensions
- Disabling pop-up blocker
- Adding world anvil as a trusted site

**To Reproduce**
1. Go to 'edit article'
2. Click on 'autolinker'
3. See the loading bar
4. Nothing happens

**Expected behavior**
I expect the autolinker window to open

**Comment by Kordishal** [comment]
I can't reproduce this. The only other instance where this happens so far is with Safari + MacOS #998, but since you are using Chrome and some other browser that does not seem to be the case.

Can you try on a different device?

**Comment by DBuswell158** [comment]
Hi. I've tried on two other devices, another PC and a mobile. Same thing.

**Comment by GorkamWorka** [comment]
@DBuswell158 is your world containing a large number of articles by any chance ?

**Comment by DBuswell158** [comment]
No. When first ran into the problem I only had two. 
Now I have about a dozen. In both cases it's the same.

**Comment by GorkamWorka** [comment]
@DBuswell158  can you do the following please : 
- connect to your world 
- navigate to https://www.worldanvil.com/world/get-links-array

this should display a json array looking like that
```json
[{"id":"020220e4-010a-453e-a40b-711ae6332ce5","title":"Jovian Council","template":"organization","link":"@[Jovian Council](organization:020220e4-010a-453e-a40b-711ae6332ce5)"},{"id":"033252e9-03b4-44c9-8957-e8da7965db16","title":"azesdq","template":"article","link":"@[azesdq](article:033252e9-03b4-44c9-8957-e8da7965db16)"}]
```
(This is the array the system use as a basis for the autolinking process)

If it doesn't givve you such an array, please give me the result. If it does then it's probably something blocking the JS execution. in which case we could look into it together but that would mean arranging a time.

**Comment by DBuswell158** [comment]
Hi GorkamWorka, I went to that link and I do recieve a json array:

`[{"id":"03dc6c79-c1cc-477e-97da-08d5ad036bdb","title":"Talimeer","template":"location","link":"@[Talimeer](location:03dc6c79-c1cc-477e-97da-08d5ad036bdb)"},{"id":"3201412e-1724-4b02-9c94-8febe39c37c1","title":"The Athanian Empire","template":"ethnicity","link":"@[The Athanian Empire](ethnicity:3201412e-1724-4b02-9c94-8febe39c37c1)"},{"id":"407189ae-b0a4-4fb5-b01f-2bd6e95949dc","title":"Arkanum Timekeeping","template":"article","link":"@[Arkanum Timekeeping](article:407189ae-b0a4-4fb5-b01f-2bd6e95949dc)"},{"id":"4478c899-da04-435d-a16f-b38b54eabff3","title":"Athanian","template":"article","link":"@[Athanian](article:4478c899-da04-435d-a16f-b38b54eabff3)"},{"id":"4c64741d-4fe5-4ed7-afb2-7140cb7946ab","title":"Tilsen","template":"species","link":"@[Tilsen](species:4c64741d-4fe5-4ed7-afb2-7140cb7946ab)"},{"id":"522abf85-7707-43b9-bcf2-95abf23118fc","title":"Somnigh","template":"article","link":"@[Somnigh](article:522abf85-7707-43b9-bcf2-95abf23118fc)"},{"id":"59177855-f4c9-4c3f-81c5-909811e46b19","title":"Mundus","template":"location","link":"@[Mundus](location:59177855-f4c9-4c3f-81c5-909811e46b19)"},{"id":"5bbfb917-0f8f-4b7c-9524-652bd661d266","title":"Creation Mythos","template":"myth","link":"@[Creation Mythos](myth:5bbfb917-0f8f-4b7c-9524-652bd661d266)"},{"id":"5ce68fc0-60df-43c9-b0b9-d97f5fc9fe74","title":"The El'dari, (Forgotten Ones)","template":"ethnicity","link":"@[The El'dari, (Forgotten Ones)](ethnicity:5ce68fc0-60df-43c9-b0b9-d97f5fc9fe74)"},{"id":"6011bf70-f398-4ba6-9966-74ea4c178a09","title":"The A'fim, (Snow Elves)","template":"ethnicity","link":"@[The A'fim, (Snow Elves)](ethnicity:6011bf70-f398-4ba6-9966-74ea4c178a09)"},{"id":"617ab492-5c49-4b92-ae8e-c8712fa24f07","title":"The Great Elvish Schism","template":"myth","link":"@[The Great Elvish Schism](myth:617ab492-5c49-4b92-ae8e-c8712fa24f07)"},{"id":"62069787-f56a-4930-abd8-f45440cdd6ee","title":"Weiland","template":"location","link":"@[Weiland](location:62069787-f56a-4930-abd8-f45440cdd6ee)"},{"id":"6880a585-4850-4710-a565-1ae31d0fa578","title":"Elves","template":"species","link":"@[Elves](species:6880a585-4850-4710-a565-1ae31d0fa578)"},{"id":"6b78ff52-2687-4fcf-af27-dd980b82111d","title":"The Kan'an, (Wood Elves)","template":"ethnicity","link":"@[The Kan'an, (Wood Elves)](ethnicity:6b78ff52-2687-4fcf-af27-dd980b82111d)"},{"id":"6d3da143-ffcd-480b-903c-644c111f8fd2","title":"The Un'Char (High elves)","template":"ethnicity","link":"@[The Un'Char (High elves)](ethnicity:6d3da143-ffcd-480b-903c-644c111f8fd2)"},{"id":"7e9e58f8-4c7b-4767-9324-f43a48715cd2","title":"Animen","template":"article","link":"@[Animen](article:7e9e58f8-4c7b-4767-9324-f43a48715cd2)"},{"id":"901fc81b-3a1d-420f-91ae-e120fb03aa01","title":"The Suun'mar, (Sea Elves","template":"ethnicity","link":"@[The Suun'mar, (Sea Elves](ethnicity:901fc81b-3a1d-420f-91ae-e120fb03aa01)"},{"id":"922259e5-d90b-4f0d-8937-e4f963d1937c","title":"The Tilsen Rebellion","template":"myth","link":"@[The Tilsen Rebellion](myth:922259e5-d90b-4f0d-8937-e4f963d1937c)"},{"id":"9c2a3745-b178-47fb-acfd-b4d855891196","title":"Levata","template":"article","link":"@[Levata](article:9c2a3745-b178-47fb-acfd-b4d855891196)"},{"id":"a4aa13d8-5aa2-42c8-8b0c-e35399e9ac8e","title":"Primordial Arkanum","template":"article","link":"@[Primordial Arkanum](article:a4aa13d8-5aa2-42c8-8b0c-e35399e9ac8e)"},{"id":"aecafb01-3f71-4449-9ccb-a36440e636b3","title":"Partum","template":"article","link":"@[Partum](article:aecafb01-3f71-4449-9ccb-a36440e636b3)"},{"id":"bedca9cf-72f6-4f98-94d8-289e09006759","title":"The Underway","template":"location","link":"@[The Underway](location:bedca9cf-72f6-4f98-94d8-289e09006759)"},{"id":"bedceff8-1f79-49df-8c69-f6e58c105a5b","title":"The Ad'shuun, (Dark Elves)","template":"ethnicity","link":"@[The Ad'shuun, (Dark Elves)](ethnicity:bedceff8-1f79-49df-8c69-f6e58c105a5b)"},{"id":"c04f31d7-3195-44b9-bc80-7dd1fa1d0c29","title":"Ipsus","template":"article","link":"@[Ipsus](article:c04f31d7-3195-44b9-bc80-7dd1fa1d0c29)"},{"id":"df992084-4738-43de-840f-69112be100f0","title":"Undermar","template":"article","link":"@[Undermar](article:df992084-4738-43de-840f-69112be100f0)"},{"id":"e1bdcf32-ce3c-461b-9449-c0713b612b67","title":"The Suun'mar, (Sea Elves","template":"ethnicity","link":"@[The Suun'mar, (Sea Elves](ethnicity:e1bdcf32-ce3c-461b-9449-c0713b612b67)"},{"id":"ea70da99-0585-4562-bc4d-2198275c7778","title":"The Age of Myth","template":"article","link":"@[The Age of Myth](article:ea70da99-0585-4562-bc4d-2198275c7778)"},{"id":"f3000448-123b-43a1-a576-bcfd416bfcde","title":"Lorium","template":"article","link":"@[Lorium](article:f3000448-123b-43a1-a576-bcfd416bfcde)"}]`

**Comment by DBuswell158** [comment]
@GorkamWorka This is the output I get in the console when I click the autolinker button. Is it having an issue with the use of an apostraphe in the article titles?

autolinker-forEuclid.js:19 Uncaught (in promise) SyntaxError: Invalid regular expression: /(?<![²&"'(_)=^$*%µ£¨~#\{\[\|`\^@\}\p{Letter}\p{Number}-])The Suun'mar, (Sea Elves(?![²&"(_)=^$*%µ£¨~#\{\|`\^@\]\}\p{Letter}\p{Number}-])/: Unterminated group (at autolinker-forEuclid.js:19:80)
    at new RegExp (<anonymous>)
    at autolinker-forEuclid.js:19:80
    at Array.forEach (<anonymous>)
    at searchPossibleLinksFromArticles (autolinker-forEuclid.js:18:217)
    at Object.success (autolinker-forEuclid.js:10:62)
    at c (global.js?v=016535:1:27824)
    at Object.fireWith [as resolveWith] (global.js?v=016535:1:28569)
    at l (global.js?v=016535:1:78871)
    at XMLHttpRequest.<anonymous> (global.js?v=016535:1:81199)

**Comment by iamromeo** [comment]
@GorkamWorka this article's title has so many irregular characters (like parenthesis commas and quotes) any of them could have caused an issue

**Comment by DBuswell158** [comment]
It's the same error, no matter which article I try it from, just FYI.

**Comment by DBuswell158** [comment]
@GorkamWorka I deleted the "suun'mar (sea elves)" article, and it still did not work. But then I created another article with an apostraphe i it, and it worked. And now works on all articles. I have no idea why.

**Comment by iamromeo** [comment]
It was probably the parenthesis not the apostrophe
