### ISSUE TITLE
Images show incorrect world in right column details

### ISSUE THREAD

**Issue by JulesBV** [worldanvil/worldanvil-bug-tracker#1123]
**World Anvil Username**: SapphireSong

**World / Campaign / RPG Character / Manuscript Title**:  Correct World: Explorers of StarSea, Incorrect World: Something Akin to Fairytale

**Feature**: Images

**Related URLS** (To public & visible pages add screenshots otherwise):
n/a

**Describe the Issue**
The World listed in the right panel for a selected image is incorrect. 
The image was uploaded in the correct world
The image shows when the correct world is selected from the world list (ui in the column to the left of the displayed images), and doesn't show when the wrong world is selected from the world list.
But in the details column, the wrong world is listed. The drop down doesn't offer the correct world as an option.

Extra info: The world the image was uploaded to (Explorers of StarSea) is one I was invited to and have Editor permissions for. The world the details column displays (Something Akin to Fairytale) is a world I created and manage.

**To Reproduce**
1. Use an account with access to 2 worlds (may need editor permissions for world A, and ownership of World B)
2. Go to 'Images'
3. While in World A, drag an image file into the dashed box to upload
4. Click on the thumbnail of the image

Note: The World option in the right column shows World B. World A isn't even in the drop down.

5. Click on 'Worlds list' in the left column and switch to World B.

Note: The image doesn't show in the thumbnails for this worlds images.

**Expected behavior**
The image details show show the world the image is uploaded to. In this case, Explorers of StarSea.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by GorkamWorka** [comment]
i cannot reproduce it sadly, can you test it again ?
