### ISSUE TITLE
Invisible Chronicle Events

### ISSUE THREAD

**Issue by PleasantPheasant77** [worldanvil/worldanvil-bug-tracker#1124]
**PleasantPheasant77**:

**Dime-A-Dozen Dimensions**:

**Chronicles**: 

**Describe the Issue**
When I make an event, it appears invisible.

**To Reproduce**
1. Make an event as normal
2. Scroll to the date you set it as.
3. See error

**Expected behavior**
I expected to be able to see the event I made.

**Screenshots**
![image](https://user-images.githubusercontent.com/106975794/175750996-a35dd39d-995d-4c8a-b473-781fe17e1f3a.png)

**Comment by iamromeo** [comment]
Hey @PleasantPheasant77 we will be checking this out - but are you sure you created an event? Can you check on the right hand side under Event Management and see if you can see the event in the list there?

**Comment by PleasantPheasant77** [comment]
![image](https://user-images.githubusercontent.com/106975794/175766358-bdba0bf3-2335-4c54-a8a1-297fd40dce74.png)
Here's the event in the manager, and the name of the event is in the first screenshot but it's stuck behind the current date.

**Comment by PleasantPheasant77** [comment]
@iamromeo I created a new chronicle, and the problem fixed itself somehow. The only thing i did different was add a default cover image to the chronicle and gave it a different name. An updated version of the original map was also used.
![image](https://user-images.githubusercontent.com/106975794/175785713-b5951400-0080-4a86-ac5f-de0d1fa84cbc.png)

**Comment by Xuroth** [comment]
Closing this as the issue has gone (and I believe the original cause was recently fixed).
