### ISSUE TITLE
Imagine Role Playing

### ISSUE THREAD

**Issue by MichaelTenery** [worldanvil/worldanvil-bug-tracker#1125]
**Imagine Role Playing**:
**System Name**:Imagine Role Playing
**MichaelTenery**:

**[Website]**:https://role-playing.com/

**[Logo Image Link]**:https://www.role-playing.com/oc/image/catalog/colorlogo.jpg

**[Logo Usage Terms (URL)]**:https://role-playing.com/faq.html

**Comment by MichaelTenery** [comment]
Thank you for your consideration.

**Comment by iamromeo** [comment]
All done
