### ISSUE TITLE
Deleting a world leaves resources in it linked to the profile but uneditable / undeletable

### ISSUE THREAD

**Issue by CloudyChris** [worldanvil/worldanvil-bug-tracker#1128]
Arthank:

Durkaran:

Deleting a world: 

https://www.worldanvil.com/author/Arthank <- my profile on which said resources still reside, leading to a 404 

I deleted a world, cause I wanted to start from scratch. The resources linked to it ( a people, a language and a diety ) remained on my profile page.

Seems like a database cascade-behavior issue. If the resources to world respective columns are many to one it should be pretty straight forward... I suspect they're maybe related in a different way to allow reusability and such?

Anyway, it's not blocking, per say, but rather annoying.

Note: issue persists after clearing cookies... so it can't be cached data either. I suspect you GET on page load anyway.

**Comment by iamromeo** [comment]
This is a temporary caching issue. Aware of it :)
