### ISSUE TITLE
Cannot Delete Article

### ISSUE THREAD

**Issue by Azbolg** [worldanvil/worldanvil-bug-tracker#1130]
**World Anvil Username**: Azbolg

**World / Campaign / RPG Character / Manuscript Title**: https://www.worldanvil.com/w/zin-azbolg

**Feature**: Cannot delete articles.

**Related URLS** (To public & visible pages add screenshots otherwise): 
https://www.worldanvil.com/w/zin-azbolg/a/rahadin-s-prayers-7C-curse-of-strahd-episode-27-7C-c2e16-7C-adventures-in-zin-7C-dungeon-26-dragons-dnd5e-article?preview=true?

https://www.worldanvil.com/w/zin-azbolg/a/the-sunsword-7C-curse-of-strahd-episode-26-7C-c2e15-7C-adventures-in-zin-7C-dungeon-26-dragons-dnd5e-article?preview=true?

https://www.worldanvil.com/w/zin-azbolg/a/dreams-and-curses-7C-curse-of-strahd-episode-25-7C-c2e14-7C-adventures-in-zin-7C-dungeon-26-dragons-dnd5e-article?preview=true?

https://www.worldanvil.com/w/zin-azbolg/a/tsolenka-pass-7C-curse-of-strahd-episode-24-7C-c2e13-7C-adventures-in-zin-7C-dungeon-26-dragons-dnd5e-article?preview=true?

**Describe the Issue**
When trying to delete the article, either under the articles tab, or in the article under preferences, the article cannot be deleted, or gives a 404 error.

**To Reproduce**
1. Go to Articles -> 'https://www.worldanvil.com/world/athena/'
2. Go to List
3. Go to Uncategorized articles
4. Scroll to -> The Sunsword | Curse of Strahd Episode 26 | C2E15 | Adventures in Zin | Dungeon & Dragons DND5e
5. Click the trashcan (delete button)
6. Click the checkmark to confirm deletion

**Expected behavior**
Article being deleted

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
This is due to the extremely long article title. To resolved
- Edit the article title and set it to something that is not the size of the circumferance of Jupiter :P 
- Click to delete the article in order to delete


@GorkamWorka - check the archiving renaming function

**Comment by GorkamWorka** [comment]
Fixed will be deployed soon
