### ISSUE TITLE
Chronicles: Updating long-form description on existing event

### ISSUE THREAD

**Issue by Zarroph** [worldanvil/worldanvil-bug-tracker#1131]
Have a repeat issue in which, when I attempt to update the long form description of an existing event on my chronicle, if it takes me awhile to type, when I click update event, it does not update, and undoes all my editing. (On average, I'll lose about 3-4 minutes of work.) This issue only happens sometimes, often repeatedly on the same event, and seems to depend upon how long it takes me to type up the changes. If I copy paste the content in, or only edit a few words quickly, this bug never happens.

**Comment by Xuroth** [comment]
Hello! I recently pushed a fix for this, can you let me know if the issue persists?

**Comment by Xuroth** [comment]
Closing issue, feel free to reopen if needed!
