### ISSUE TITLE
Typo in Material Template

### ISSUE THREAD

**Issue by PleasantPheasant77** [worldanvil/worldanvil-bug-tracker#1132]
**World Anvil Username**: PleasantPheasant77

**World / Campaign / RPG Character / Manuscript Title**:Dime-a-Dozen Dimensions

**Feature**: Article Templates

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
The flavor test at the bottom of the "History" section under Usage contains multiple typos.

**To Reproduce**
1. Go to 'Material Template'
2. Click on 'Usage'
3. Scroll down to 'History'

**Expected behavior**
The correct sentence would be something like: How was this **historically** perceived **throughout** the history of your world? How did its usefulness **change** through the years?

**Screenshots**
![image](https://user-images.githubusercontent.com/106975794/176567838-36255ffc-e849-4b3f-bb8e-c6393b5668ca.png)

**Comment by iamromeo** [comment]
@PleasantPheasant77 thank you for the heads up and I am sorry for this. 

@GorkamWorka please ask Ondo to rewrite this and update it. I was obviously in some sort of trance when writing this.

**Comment by GorkamWorka** [comment]
fixed will be deployed soon
