### ISSUE TITLE
LodlanD

### ISSUE THREAD

**Issue by MrLighz** [worldanvil/worldanvil-bug-tracker#1134]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

Note: Please contact me, if any questions arise or you need more background. Thanks

**Full Name (RPG SYSTEM)**: LodlanD
**List Name** (Name under which it should be listed on World Anvil): LodlanD
**World Anvil Username**: mrlighz

**Website**: https://shop.hockeyzentrale.de/impressum.html
Note: the original LodlanD Webpage is no longer existing, the Image Verlag (publisher) is also no longer existent, merged in the  Image Sport & Event GmbH
However, I am still in contact with C. Fischer - I am allowed to use Material in WorldAnvil and also make a Char gen as long as it is non-commercial and the link to above Website is present - also the copyright note. I also got the proposal for possible commercial use (requires extra paperwork), but have currently no intention for that.

**Logo Image Link**:
Note: sorry dont know if there is still a free source for that. Maybe I can give a .jpg for use on WA.

**Logo Usage Terms (URL)**:

**Comment by iamromeo** [comment]
All done ;)
