### ISSUE TITLE
The extended edit interface always leads to 404 page

### ISSUE THREAD

**Issue by BroadsideZa** [worldanvil/worldanvil-bug-tracker#1136]
Username: aigenfuhr

**World**: Deilenaar

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/deilenaar-aigenfuhr40gmailcom/a/captain-cordelia-archer-person-1

**Describe the Issue**
I'm trying to edit this character in the extended view but when I hit save instead of saving it takes me to the world anvil 404 page

**To Reproduce**
1. Go to https://www.worldanvil.com/heroes/campaign/npc/20d55c7c-c415-4c41-9d1b-ee18ca359c0f/extended
2. Click on 'edit anything and then save the article'
3. then you get redirected to the 404 instead of saving the page

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
@ Dimitris 
I can actually access the extended profile edit link and save content and can confirm that the save button leads to a 404 page. However, from what I saw the changes are actually saved.

But I should not be able to access this link at all!

**Comment by iamromeo** [comment]
@BroadsideZa the chances are that your characters short description is very short - we are aware of this issue and we will be fixing it. Go to your basic edit and remove any @ mentions you might have on the short description this should fix it please let me know if there a problem still

**Comment by Kordishal** [comment]
I believe you are confusing this issue with an issue on RPG Characters. This issue only appears on the extended profile edit of pure NPC characters that are not full RPG characters.

The 404 page appears no matter what on all the NPCs I have, even if there is no content. It prevents saving of the content.

**Comment by GorkamWorka** [comment]
This should be fixed
@BroadsideZa  can you test it ?

**Comment by Kordishal** [comment]
It is working for me
