### ISSUE TITLE
RPG Character in campaign party, but not listed under PC Cast tab.

### ISSUE THREAD

**Issue by Balshon** [worldanvil/worldanvil-bug-tracker#1137]
**Balshon**:

**Ravenloft / Ravenloft / Eludora / Parties**:

**Parties and Protagonists**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
In the Campaign section of my DM editor I'm showing one of my characters in the party however that character does not show up under protagonists tab, because of this I cannot work with her character at all or even expel her from the party long enough to fix the issue. I resend the link to her and she just gets a 404 error when trying to choose that character.

**Comment by Balshon** [comment]
To fix I had to delete the party entirely and reinvite characters, this is a big headache as far as user friendliness when it comes to the party interface. Why can't the DM just move characters in and out of parties and other locations easily?

**Comment by iamromeo** [comment]
The chances are that you never removed the character from your world's characters and that the player never gave you editing access to their character. 

Sadly I cannot be sure what happened but I would suggest you have a read through the codex - we will be happy to help but I cannot fix what I cannot see. \

What is the current state?

**Comment by Kordishal** [comment]
We had this issue before:

#726 
#452 
#175 

Deleting the party and then re inviting the characters seems to always do the trick. You've said in the past that the plan is to resolve this with Hercules.

**Comment by iamromeo** [comment]
@Kordishal that is correct, this system will completely be redesigned
