### ISSUE TITLE
Cannot access Sage level campaign to delete it or change it to public.

### ISSUE THREAD

**Issue by B-Bye** [worldanvil/worldanvil-bug-tracker#1138]
**World Anvil Username**: Brandael

**World / Campaign / RPG Character / Manuscript Title**: The Circle Sea

**Feature**: Accessing campaign to delete it after going from Sage to Master guild level

**Related URLS** (To public & visible pages add screenshots otherwise): 

**Describe the Issue**
A clear and concise description of what the issue is.

**To Reproduce**
1. Go to Dashboard
2. Click on The Circle Sea
3. Get error
4. Follow instructions to return to Dashboard
5. "Go to 1"

**Expected behavior**
Obviously the expectation here is that the prompts would lead me to an area where I could alter the campaign and clear it out so that I'm not above the limits set by my guild level.

**Screenshots**
![step 1](https://user-images.githubusercontent.com/108592683/177015388-ba4885ed-2535-4146-a1ba-c1042e8d6713.png)
Step 1

![step 2](https://user-images.githubusercontent.com/108592683/177015395-6d2d9bce-7b92-4c09-b75e-25758965ded2.png)
Step 2

![step 3](https://user-images.githubusercontent.com/108592683/177015394-d4afa577-5438-43d7-a28e-0be494d892d0.png)
Step 3

**Comment by iamromeo** [comment]
There is not such a thing as a Sage-level campaing or world. The chances are that your world has currently a large amount of Subscribers which were not removed before deactivating your membership. 

This is not a bug, it is a security feature. 
If you wish for all the subscribers and their groups to be removed from your world, you will need to contact customer support so they can open a case and the development team will be able to take it from there. 

Keep in mind there is no mid solution - we will have to remove all your groups and subscribers.
