### ISSUE TITLE
Euclid Editor Usability Issues on Mobile

### ISSUE THREAD

**Issue by james227uk** [worldanvil/worldanvil-bug-tracker#114]
**World Anvil Username**: TheIllusiveMan227

**World / Campaign / RPG Character / Manuscript Title**: All Worlds

**Feature**: Euclid Editor

**Related URLS** -

**Describe the Issue**
On mobile browsers, there are severe usability issues with the new Euclid editor, particularly regarding text input and selection. I have my qualms about submitting this list since I'm sure some issues are down to the browser developers, but I still feel it important because I have never faced these issues in any other context than in the Euclid editor, nor am I able to find a single mobile browser that works without any issues at all. As the Legacy editor is soon to be deprecated, this is concerning.

A list I have identified is as follows, as well as a non-definitive list of the browsers I have encountered these issues in:

1. Cannot select regions of text. Any method of doing so will highlight a single word within the editor, but with no options to copy/paste/define, nor handles to expand or shrink the selection (Safari iOS, Edge iOS).
2. Trying to select a word whilst the cursor is inside it results in the word being selected for a moment, and then the selection cancelling itself. (Chrome Android).
3. Line/paragraph breaks cannot be removed, as hitting backspace does nothing. In the worst case, pressing backspace actually closes the keyboard without doing anything. (Firefox Android, Chrome Android).
4. Native iOS functions such as auto-correct and text predictions do not work within the Euclid editor space. (Safari iOS).

**To Reproduce**
Steps to reproduce the issues above by number:
1. Edit any article in the affected browsers, and try and double tap/long press to select text. Only a single word is selected, without the ability to modify the selection size, nor to copy/paste. 
2. Edit any article, place the cursor inside a word, then long-press to select that word. The selection will cancel itself immediately after.
3. Edit any article in the affected browsers, press enter several times to add a line break between paragraphs, and then try and backspace to delete the lines. On Firefox Android, nothing happens upon pressing backspace. On Chrome Android, pressing backspace will actually close the keyboard without doing anything. 
4. Edit any article, and input any text. Neither autocorrect or text suggestions are available within the Euclid editor text space.

All of these issues are present only within the actual Euclid editor. Other text inputs, such as the Scrapbook or Storyteller Seeds work fine in any mobile browser.

**Expected behavior**
1. Text should be freely selectable, OS functions such as copy/paste/define should be available, and the handles should be available to expand/shrink the selection.
2. Text should be freely selectable without the selection cancelling itself.
3. Line breaks should be freely removable.
4. Autocorrect and text suggestions should be available like in any other text input field.

**Screenshots**
I have attached short videos of each bug in action. Where applicable, I have demonstrated what happens when you try to do the same action in the Euclid editor input box, versus doing it in the Scrapbook/Storyteller Seeds input box.

Issue 1: https://user-images.githubusercontent.com/9790581/112762540-0dbbb980-8ff8-11eb-9811-1324170b6ff1.mp4

Issue 2: https://user-images.githubusercontent.com/9790581/112762542-101e1380-8ff8-11eb-8b1e-bbcbed9cb558.mp4

Issue 3: https://user-images.githubusercontent.com/9790581/112762544-114f4080-8ff8-11eb-8515-e99348eb3866.mp4

Issue 4: https://user-images.githubusercontent.com/9790581/112762547-13b19a80-8ff8-11eb-8964-32a5c529936a.mp4

**Comment by Kordishal** [comment]
I am sure captain fry will look into it, but there can be no promises. Mobile support has always been second class.

However, the legacy editor is likely to continue working for a long time since there isn't really anything that can break. At the same time, there are a total of 638 active legacy users (as of a few days ago anyway). So there is no reason to keep it around.

**Comment by Kordishal** [comment]
Ok to clarify. Legacy will not be removed. It will still be updated if there are major changes that require an update. So you can just keep using legacy.
