### ISSUE TITLE
Map select does not actually switch map

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#1141]
**World Anvil Username**: SoulLink
**Feature**: Chronicle

**Describe the Issue**
When multiple maps are present in a chronicle the green select button is used to switch between the maps from the maps manager. When clicking it nothing happens though. I have at least one other user that has reported this issue.

This issue appeared after #1108 was fixed and closed.

This doesn't appear to happen for everyone though, but I could not make it work, there is no error message and hard refresh and creating a new chronicle does not resolve the issue. It does not work in a private window either.

I use Firefox + Linux. The other user with this issue uses Vivaldi (Chromium).

**Comment by Xuroth** [comment]
Hey, there was indeed a typo included in that issue. You should be able to change the current map again!

**Comment by Kordishal** [comment]
Can confirm that it works for me. Thanks!
