### ISSUE TITLE
Transfer World function white-screening page

### ISSUE THREAD

**Issue by egghuffer23** [worldanvil/worldanvil-bug-tracker#1142]
**World Anvil Username**: kaekile

**World**: K/E-4R-05/TH-1 (there are no subscribers, co-authors, campaigns, or RPG characters linked to it)  

**Feature**: Transfer World

**Related URLS** (To public & visible pages add screenshots otherwise): https://imgur.com/a/mkTTYSi (gif) 

**Describe the Issue**
Would go to transfer a world to a different account that is Master Worldsmith tier, but when I went to initiate the transfer, the page would go blank and say that WA isn't capable of this action.   

**To Reproduce**
1. Go to <World> Configure
2. Click on Open Tools & Advanced Actions 
3. Scroll down to Transfer World
4. Input username of account that is Master tier or above. 
5. Click confirm action
6. See error. It remains the same when refreshing. 

I'm not sure how long this function has been out for, but I haven't been able to do it for a couple weeks. I'm hoping it gets fixed soon. I don't know what else might be doing it since it apparently has been successfully reproduced by someone in that little customer service bubble function window whatever.

**Comment by iamromeo** [comment]
Does the other account have the space to accept the world? Which is the account you are trying to transfer the world to?
