### ISSUE TITLE
Cannot delete months from chronicle calendars manager

### ISSUE THREAD

**Issue by amtep** [worldanvil/worldanvil-bug-tracker#1145]
**World Anvil Username**: Amtep

**World / Campaign / RPG Character / Manuscript Title**: Kanitra

**Feature**: Chronicles

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/kanitra-amtep/chronicle/tales-of-kanitra-chronicle

**Describe the Issue**
When I select "Calendars Manager" from the icons on the right, I can't delete excess months. (I started with the default Gregorian calendar, but decided I just want four 90-day seasons.)  Clicking on the red garbage-can icon for the months I want to delete does nothing.

**To Reproduce**
1. Go to Timelines
2. Click on my Chronicle
3. Click on Calendars Manager on the right
4. Click on the red icon next to one of the empty months
5. Nothing happens

**Expected behavior**
I expect that at step 5, I have one fewer month in my calendar's list of months.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Xuroth** [comment]
This should now be resolved!
