### ISSUE TITLE
Spell list and Class/Race Features don't import from D&D Beyond

### ISSUE THREAD

**Issue by shyredfox** [worldanvil/worldanvil-bug-tracker#1146]
**World Anvil Username**: shyredfox

**World / Campaign / RPG Character / Manuscript Title**: Stormy Smoking Mountain (character)

**Feature**: D&D Beyond Import

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.dndbeyond.com/sheet-pdfs/Shyredfox_68859394.pdf

**Describe the Issue**
Spell list and Class/Race Features don't import from D&D Beyond

**To Reproduce**
- Click the Import D&D Beyond Character button and fill in the number
- Click Summon my Character

**Expected behavior**
If I have spells and features on my sheet in D&D beyond, ideally it should import those, right? Right now, I have to add the statblocks every time I sync the sheet. Not fun. 

What it does import works wonderfully.

For now, I'll add the statblocks and update the sheet manually when I level up.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Screenshot_19](https://user-images.githubusercontent.com/59369948/177869464-644ed106-5220-471e-8b32-154fcf15ed54.jpg)
![Screenshot_20](https://user-images.githubusercontent.com/59369948/177869471-cb807621-80ce-4222-9fd6-398604b73d20.jpg)
No race or class features (even just the text) or spells

**Comment by Kordishal** [comment]
This is not a bug, its just not implemented. Not sure what the plans on that are, but the team is fairly busy with other stuff.
