### ISSUE TITLE
Printed D&D 5e character sheet hard to read - text too light in areas

### ISSUE THREAD

**Issue by shyredfox** [worldanvil/worldanvil-bug-tracker#1147]
**World Anvil Username**: Shyredfox

**World / Campaign / RPG Character / Manuscript Title**: Sample character sheet: Vasanti Sihir

**Feature**: Printing D&D 5e character sheet

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/block/613473

**Describe the Issue**
When printing a D&D 5e character sheet from a statblock, several of the numbers and words on the sheet are hard to read because they are too light. We need more contrast for those areas.

**To Reproduce**
1. Go to the character sheet statblock
2. Click print sheet.

**Expected behavior**
To have enough contrast to make the sheet readable. Most of the light colored text are important numbers. I need to be able to easily skim them in a game.

Beyond that, the sheet is nicely organized. Wish I had time to tweak the CSS for it.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Screenshot_21](https://user-images.githubusercontent.com/59369948/177871481-0b85669a-5c26-41dc-8ebd-339a8a3c804b.jpg)
Even on the screen shot it's light

![2022-07-07 16 05 26](https://user-images.githubusercontent.com/59369948/177871517-a7166325-960e-4241-bcc4-4063f333b80e.jpg)
Laser printed (NOT on toner saver mode)

**Comment by Tillerz** [comment]
Ok, I can fix that. :)

**Comment by Tillerz** [comment]
Fixed.
