### ISSUE TITLE
Secrete API issue.

### ISSUE THREAD

**Issue by Alithert** [worldanvil/worldanvil-bug-tracker#1149]
World Anvil Username: Jandis

Hi, 
Im currently having an export error for my worlds. the error is:
Job failed: pywaclient.exceptions.InternalServerException: world/eb4faf52-9bdb-4739-96b4-deb992931884/secrets

given that it says secrets, i checked the secrets tab and it gives me a 404 error.

any help appreciated :)

**Comment by Kordishal** [comment]
Hi, the issue should be resolved now! Can you please confirm that the export works for you once again and the the secrets page can be viewed?

**Comment by Alithert** [comment]
it's all working now, thank you
