### ISSUE TITLE
Implement proper conflict resolution, content versioning and roll-back

### ISSUE THREAD

**Issue by AliveDevil** [worldanvil/worldanvil-bug-tracker#115]
**World Anvil Username**: AliveDevil

**World / Campaign / RPG Character / Manuscript Title**: Does not apply, is universal to every world, campaign, character and manuscript as long as one person can have that article open in more than one editor.

**Feature**: Article editing/saving.
Applies to everything. Campaign Story Reports, Character sheets, descriptions, regular articles.

**Related URLS**: Private. Video attached.

**Describe the Issue**
Working with multiple people (or forgetting a browser window, used to create that article, and left in an empty edit-state) on the same article can result in loss of work and data.

**To Reproduce**
1. Create Article (hereafter referred to browser A)
2. Open that article in another browser window (hereafter referred to as browser B) (simulate two people working at the same article)
3. Change something in browser A, save.
4. Change title, or different tab in browser B. Save.
5. Changes from browser A have been lost.
6. There is no way of recovering this failure.

**Expected behavior**
I expect WorldAnvil to honor collaborative editing with multiple people on the same articles by applying some kind of versioning and conflict resolution strategies to prevent users from wasting time just because some auto-save feature goes rogue and overwrites everything - unconditionally.

This can be recreated by intent as shown in the attached video, but can be caused by having the edit article window open (unintentionally), opening the edit article window again on another machine, investing huge amounts of time into writing - believing that it has been saved correctly. Just to get back to the original window, which triggers an auto-save and wipes everything that has been added before.
I want control over those kind of changes to roll-back several versions
* These versions should be created on user-intent (hitting save)
* There can be a "actively worked on"-version which may be subject to data loss, but is not irreversibly wiped in the event of sudden conflicts
* I can roll-back a version or view a previous-version to merge content that has been overwritten.

A fast mitigation would be to "lock" an article to be edited by one-person in one browser window in one session only. Saving requires a one-time token, saved in the underlying database which grants the currently open edit exclusive write acces. Every other user must not be able to edit that article or open it in read-only mode. This lock may be lifted and another user might regain control of this lock but the now stale and out-of-date browser window of the original session is unable to ever save again. 
The user (of the stale browser window) should be warned immediately (without site navigation and with the option to dismiss the popup, to ensure that already written content is not lost (i.e. content can be copied into another browser window (with refreshed content of the article) or a text editor). Inspiration may be taken from the WebDAV [RFC 4918 HTTP Extensions for Web Distributed Authoring and Versioning (WebDAV)](https://tools.ietf.org/html/rfc4918#section-7) in Section 7 - Write Locks.

Content should not be considered transient data which can be irreversibly lost at any point in time.

This will result in larger databases and increased storage space usage, though what's the real cost here.

**Screenshots**

https://user-images.githubusercontent.com/734738/112866189-cd247480-90b9-11eb-97a5-a24849ff7f73.mp4

**Comment by iamromeo** [comment]
This is not a bug, at best it's a feature request.

**Comment by AliveDevil** [comment]
So autosave wiping hours of work and content is not considered a bug, got it.
I'll consider creating a feature request after remembering what I've written days ago.
