### ISSUE TITLE
Create new event button for historical events leads to blank page.

### ISSUE THREAD

**Issue by CathVdw** [worldanvil/worldanvil-bug-tracker#1151]
**World Anvil Username**: LaCath

**World / Campaign / RPG Character / Manuscript Title**: Tezcatlipoca

**Feature**: chronology / create a new event

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/world/timeline/history/new

**Describe the Issue**
When I click on the "create a new event" button, I get redirected to a blank page

**To Reproduce**
1. Go to https://www.worldanvil.com/w/tezcatlipoca-lacath
2. Click create a new event
3. get a blank page

**Expected behavior**
I don't know what to expect, as it is the first time I use the feature, but I would expect something

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Hi

Thank you for your report! Unfortunately I cannot reproduce this issue with the information given. 

- You are talking about the create new event button on this page: https://www.worldanvil.com/world/timeline/history/list ?
- What browser / device are you using?
- Does the same thing happen in a different browser? On a different device? In a private window?

**Comment by CathVdw** [comment]
Hello,
Right now, I'm on my pc and it seems to work just fine.
When the problem happen, I was on my MacAir. I'll try again to see if it's
fixed or if it still happens.
I use Firefox on both devices.
Regards,
LaCath

Le lun. 11 juil. 2022 à 06:06, Jonas Waeber ***@***.***> a
écrit :
