### ISSUE TITLE
Campaign Owner cannot edit sheets of campaign members

### ISSUE THREAD

**Issue by awildenhain** [worldanvil/worldanvil-bug-tracker#1152]
**World Anvil Username**: Nonopherian

**World / Campaign / RPG Character / Manuscript Title**: Soul of the Sea campaign (30297818-e587-404b-a3d0-ed7452f93dc6)

**Feature**: Campaigns and Campaign membership

**Related URLS** (To public & visible pages add screenshots otherwise): Private world, please see screenshots below 

**Describe the Issue**
When a member of my campaign creates a character sheet on their own World Anvil account and then joins my campaign, I see the Edit Sheet button for their sheet.  However, when I click on the button, I get a 404.  If I create the character sheet and then transfer it to the campaign member, when I click the button, I am able to view and edit their sheet.

**To Reproduce**
1. Player World Anvil user creates a character and a character sheet.  Player user links character to character sheet.
2. GM World Anvil user invites Player to join their campaign (private world).  Player accepts the invite with the created character.
3. GM navigates to Campaign/Protagonists and clicks on the Edit Sheet button for the character.
RESULT: GM receives a 404: string(20) "unauthorised access."

**Expected behavior**
GM is able to edit the character sheet even when the player originally created it.

**Screenshots**
![image](https://user-images.githubusercontent.com/55631431/178159590-b2709f8f-a9db-4b42-b754-4a52d185d87e.png)
![image](https://user-images.githubusercontent.com/55631431/178159608-552d48d9-1cfa-4af3-8125-3e4ee6b642e0.png)

**Comment by graylion-wa** [comment]
Using the url edit without the button also produced this string(20) "unauthorized access" 404

[Edit Character](https://www.worldanvil.com/heroes/sheet/1060779/edit)

**Comment by Kordishal** [comment]
This is unfortunately the case and working as intended. You need to follow the correct stops for the GM to be able to edit the character statblock of the players.

Graylion made a handy guide to follow:
https://www.worldanvil.com/w/creation/a/invite-characters-article 

This will be changed in the future to not require any extra steps, but until then this is how it is.
