### ISSUE TITLE
Problem with plot page

### ISSUE THREAD

**Issue by razafiki** [worldanvil/worldanvil-bug-tracker#1153]
**World Anvil Username**:  razaidi9295@gmail.com

**World / Campaign / RPG Character / Manuscript Title**: Raethia Campaign

**Feature**: Plot page

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue** For the past few months the "plot" tab in the campaign isn't working, when I do click the plot page I get "HTTP error 500" and the page will not load. I did enjoy using the plot section so please let me know what I can do to fix this. thank you. 
A clear and concise description of what the issue is.

**To Reproduce**
1. Go to 'Campaigns section '
2. Click on 'plots"
3. Scroll down to N/A
4. See error HTTP error 500

**Expected behavior**
I'm just hoping to be able to use the plots tab again

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

![error](https://user-images.githubusercontent.com/109044684/178162837-8e0bbcb8-6a1d-462f-819b-732994b39df8.PNG)

**Comment by Kordishal** [comment]
Hi

This means there is a loop or similar issue with the plots linked on the page. You need to go into your plots and resolve the issue for the plots page to appear again. Remove parent plots from the involved plots until it is working again and make sure to not create any loops when putting them back in place.
