### ISSUE TITLE
Unable to retrieve Chronicle/Unable to authenticate

### ISSUE THREAD

**Issue by ErikjeMS** [worldanvil/worldanvil-bug-tracker#1154]
**World Anvil Username**: erikfrog2

**World / Campaign / RPG Character / Manuscript Title**: History of the Weird West chronicle

**Feature**: Chronicle

**Related URLS** (To public & visible pages add screenshots otherwise): 

![wa-chronicle-errors](https://user-images.githubusercontent.com/15129944/178390573-7ac486fb-7df5-4630-a333-b17a1122f441.png)

**Describe the Issue**
Two different subscribers try to access a Private chronicle but get Unable to retrieve chronicle and Unable to authenticate error messages and see the image above.

**To Reproduce**
1. Go to https://www.worldanvil.com/w/deadlands-world-erikfrog/chronicle/history-of-deadlands-chronicle
2. See errors above.

**Expected behavior**
People in the subscriber group should be able to see the private chronicle.
The users can see Private articles in the subscriber group.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Related to #1106

**Comment by teloric** [comment]
I am getting a similar result. In my case it is co-authors who can edit it. They can see the chronicle and move along the timeline to see events and the maps associated with the events. They do not see the controls on the right (see attachment
![chronicle-control-panel](https://user-images.githubusercontent.com/3333909/178612204-f49db7e9-b8c4-4745-a6af-674dee636d62.png)). They are able to right click on the timeline and add events which are attached to existing pins on the map, however they can not right click on the map and add new pins. Unlike the Original poster they are not getting the red "unable to retrieve chronicle" error. They are getting the yellow "Unable to authenticate. Try making sure you are logged in" error, even if they log out and back in just to be sure.

**Comment by Rat-Face** [comment]
Is there a "me, too"? 'cos me, too. OP's problem is exactly my experience, screencap matches and all.

**Comment by teloric** [comment]
@Xuroth Do I need to follow a different Issue for updates of the edit mode problem?

**Comment by graylion-wa** [comment]
@Xuroth 

Question....

Was #1095 also possibly related to this?

https://github.com/worldanvil/worldanvil-bug-tracker/issues/1095

Thanks
