### ISSUE TITLE
Whiteboards get reset to default tutorial when clicking on notification bell and clicking back on browser

### ISSUE THREAD

**Issue by unexel** [worldanvil/worldanvil-bug-tracker#1156]
**World Anvil Username**: ulysse.nexel

**World / Campaign / RPG Character / Manuscript Title**: Sictaroth {RPG} 

**Feature**: Whiteboards

**Related URLS** (To public & visible pages add screenshots otherwise): N/A

**Describe the Issue**
When working on a whiteboard, clicking on the notification bell, and then the go back button on browser (mozilla), whiteboard gets reset to default tutorial, causing all the work to be lost. 

**To Reproduce**
1. Make whiteboard
2. Click on notification bell
3. Click on "go back one page" arrow on browser (mozilla) 
4. See error. 

**Expected behavior**
I expected to go back on my last saved progress and not have the whiteboard entirely reset.

**Comment by Duranzno** [comment]
Currently a major refactor in the way that that the autosave works is under way. Still working on it

**Comment by Duranzno** [comment]
A fix has been made to solve this issue. 
But in general the rule of thumb is that the data on the system is saved once the saved status icon is set on saved (the cloud on the upper left UI element has a checkmark)
