### ISSUE TITLE
Marked Chronicles as Private, but it's still showing as Public.

### ISSUE THREAD

**Issue by fewalton** [worldanvil/worldanvil-bug-tracker#1158]
**World Anvil Username**: fwalton

**World / Campaign / RPG Character / Manuscript Title**: World of Eloria, Chronicle: Kingdom Under Siege

**Feature**: The Privacy or Public button

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/eloria-fwalton/chronicle/kingdom-under-siege-chronicle

**Describe the Issue**
I chose Private for my Chronicle of 'Kingdom Under Siege' and it's displayed that way when I edit the Chronicle. But it is still displaying as Public under the Timelines and Chronicles page. I was told by Liana in the chat to copy the URL of the Chronicle, then log out and paste in the URL and if it doesn't come up then it's private. However, it did come up. I was able to see everything. However, when I click on the open article button on one of the articles of the timeline in the chronicle it says that article is private. I would like my Chronicle to be Private, and it says it is when I edit it, but it is still Public, please fix this.

**To Reproduce**
1. Go to Kingdom Under Siege Chronicle settings
2. Click on Privacy tab
3. Private is already chosen so you save. Or you click on make public, save that, then make it private again and save it again so you know Private has been pressed. The green line at the top of the page says it was successful. You go back to your Timelines/Chronicles page and sees it's still Public. Outrage ensues.
4. Continue process.

**Expected behavior**
I would like my Chronicles setting to be Private and not Public. 

**Screenshots**
![Chronicleissue](https://user-images.githubusercontent.com/109293460/179004225-80ee4ad7-14ff-4336-8143-ff853076a18f.PNG)

![Chronicleissue2](https://user-images.githubusercontent.com/109293460/179004170-dfc1b372-6cd7-4b08-878f-7c82a9449333.PNG)

**Comment by Kordishal** [comment]
Hi, I cannot reproduce this on my end. What browser / device combination are you using? Can you try changing the privacy state in another browser / device?

And both your screenshots show it as public, but I assume you mean it shows as private in the chronicle settings when you open it up even if it says public on the list?

**Comment by fewalton** [comment]
I'm using Chrome. In the Chronicles setting picture, the only thing that shows is the word Public, that is correct. Private is already chosen, if I clicked on Public, that would make it Public. So it confirms with me that I chose Private but still says it's Public.
