### ISSUE TITLE
Deleting World/Campaing/Character Problem

### ISSUE THREAD

**Issue by rafaellinares** [worldanvil/worldanvil-bug-tracker#1159]
World Anvil Username: Rafael Linares

World: A Pirâmide Negra /  Campaign: A Pirâmide Negra / Character: Ernest Watanabe

Feature: Deleting World / Campaign

Related URLS : https://www.worldanvil.com/w/a-piramide-negra-rafael-linares

Describe the Issue
If I try to delete the world or campaign it simply gives me a 404 error and it remains.

To Reproduce
I have not the slightest clue

Expected behavior
The world / campaign gets deleted
![imagem_2022-07-14_141335530](https://user-images.githubusercontent.com/52839368/179043247-227853fb-b25a-4ea2-adc9-4c98cd97869e.png)

![unknown](https://user-images.githubusercontent.com/52839368/179043170-0e2ebce9-97f3-4a84-a779-eb03fbd88beb.png)
.

**Comment by Kordishal** [comment]
This is a known issue with worlds. Please try the following steps:

- Delete associated campaigns
- Expel RPG characters (like Ernest Watanabe)
- Remove co-authors & subscribers
- Delete subscriber groups
- Delete associated manuscripts

**Comment by rafaellinares** [comment]
I deleted the campaing, deleted Ernest (i forgot about expel), but where i can go for "co-authors & subscribers"

**Comment by rafaellinares** [comment]
Thank you my brother, i lost 3 hours trying do resolve this

**Comment by Kordishal** [comment]
The link above no longer works, did it work now or did the link change?
