### ISSUE TITLE
Issue with making world public after not having a paid membership anymore. Can't access or edit my world whatsoever.

### ISSUE THREAD

**Issue by NightowlTBH** [worldanvil/worldanvil-bug-tracker#1160]
username: NightowlTBH

World : Arelis

**Feature**: Making a world that used to be private, a public world.

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I haven't used worldanvil in about a good year up until about the last month or so to reference my old world lore. I'm starting up a session again tomorrow and will be using my old world I've created as a base, but upon attempting to make the world active, It sends me to an error page (linked in screenshots) that says world anvil server's are down when attempting to change the visible state of my public world. I cant access it whether it be to view or edit it. my other world work's just fine, but the one I need to work doesn't at all. 

**To Reproduce**
1. Go to 'Your worlds'
2. Click on 'Arelis - Make public'
3. See error

**Expected behavior**
I'd expect it to just make the world public and allow me to access it?

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image_2022-07-14_151709566](https://user-images.githubusercontent.com/109310772/179065424-c2a93107-cc8b-40f3-bae5-b03bbaf03e02.png) 
![image](https://user-images.githubusercontent.com/109310772/179065729-f00eaf1f-e033-47bb-8016-83e3924dd0dc.png)
![image](https://user-images.githubusercontent.com/109310772/179065830-78807ec1-68b0-4f01-b681-4361a1945980.png)

**Comment by iamromeo** [comment]
@NightowlTBH to my knowledge there is no issue with that script in general but there might be an issue with the account specifically. 

Can you please send an email to hello@wordlanvi.com with your username and password (after you create a new one) so we can investigate the account.

**Comment by NightowlTBH** [comment]
@iamromeo Good Morning, I sent the email a few day's back but I have not received any emails back on the matter and the bug still is still prevalent. Any idea on when this might be resolved? I'd really love to use the world again I just started a new campaign and would like to add more articles. 

![image](https://user-images.githubusercontent.com/109310772/179690436-3ac2912a-e23e-4e43-a2a6-93790ba2832d.png)

**Comment by NightowlTBH** [comment]
> @iamromeo Good Morning, I sent the email a few day's back but I have not received any emails back on the matter and the bug still is still prevalent. Any idea on when this might be resolved? I'd really love to use the world again I just started a new campaign and would like to add more articles.
> 
> ![image](https://user-images.githubusercontent.com/109310772/179690436-3ac2912a-e23e-4e43-a2a6-93790ba2832d.png)

*The account details to verify the account is in the email

**Comment by iamromeo** [comment]
Thank you for letting me know - your email was sent by gmail to spam :) Will check and come back to you tomorrow

**Comment by NightowlTBH** [comment]
Thank you! Will be waiting for an update.

**Comment by iamromeo** [comment]
The issues was not fixed but your world and its assets are now public and accessible by you. Of course you will not be able to create any articles but it will work

**Comment by NightowlTBH** [comment]
Thank you for the help! I hope you have a good day!
