### ISSUE TITLE
MilitaryConflict Sidebar col-md-6

### ISSUE THREAD

**Issue by graylion-wa** [worldanvil/worldanvil-bug-tracker#1162]
**World Anvil Username**:

Graylion

**World / Campaign / RPG Character / Manuscript Title**:

Creation

**Feature**: 

Military Conflict Article

**Related URLS**

Recreated this linked article specifically for this Github Ticket

I have added CSS to my world to fix ...

I have added CSS to this linked article to remove the fix.

[Military Conflict](https://www.worldanvil.com/w/creation/a/military-conflict-for-bug-report-militaryConflict)

**Describe the Issue**
One or more of the sidebar prompts/connections for the Military Conflict article type has col-md-6 which is causing odd placment behavior.

**To Reproduce**

- Create a military conflict article
- Give it a name
- Assign a type like urban
- View

**Screenshots**

![image](https://user-images.githubusercontent.com/79761754/179115932-25ab7ca1-8816-480e-8853-2edc54377ef1.png)

**Comment by Kordishal** [comment]
This is on purpose in the military conflict template. It makes space for the belligerents! As you see the main part is col-md-6 too.
