### ISSUE TITLE
Word Count CSS

### ISSUE THREAD

**Issue by graylion-wa** [worldanvil/worldanvil-bug-tracker#1164]
**World Anvil Username**:

Graylion

**World / Campaign / RPG Character / Manuscript Title**:

Creation

**Feature**: 

Article Word Count

**Describe the Issue**

The article word count includes the CSS, should it?

And if there is a reason it would be great to have it do a breakdown under word count for example ...

Content Words
628

CSS Words
100

**Expected behavior**

Word Count not include CSS

**Screenshots**

![image](https://user-images.githubusercontent.com/79761754/179176493-e563aa2d-3eca-4334-9477-50be5abe47b5.png)

![image](https://user-images.githubusercontent.com/79761754/179176592-12a2df55-bf1f-4cc9-8387-89f4a4f7631c.png)

![image](https://user-images.githubusercontent.com/79761754/179176699-d50ad92c-ef8a-479c-8fe8-06e037efd71e.png)

**Comment by graylion-wa** [comment]
[Feature request resurrected ...](https://www.worldanvil.com/community/voting/suggestion/d6fa61a5-e050-4788-bfd2-18fa38f7b8d7/view)

**Comment by iamromeo** [comment]
Article CSS should not be counted in the word count - to my understanding we have made no changes to that system but it worths a look. 

In regards to BBcode being. removed from word count this is a non starter. It was not planned to  happen and will not be planned to. The reason is simply the fact that that script runs literally hundreds of times during the editing process of an article and adding an extremely heavy parser to it will lower the speed of loading for every single page across the domain.

**Comment by iamromeo** [comment]
@GorkamWorka can you please have a quick look to the word count script ? I am pretty sure it doesn't include the article CSS but it worths a look

**Comment by graylion-wa** [comment]
> Article CSS should not be counted in the word count - to my understanding we have made no changes to that system but it worths a look. 
> 
> In regards to BBcode being. removed from word count this is a non starter. It was not planned to  happen and will not be planned to. The reason is simply the fact that that script runs literally hundreds of times during the editing process of an article and adding an extremely heavy parser to it will lower the speed of loading for every single page across the domain. 

Thank you

**Comment by graylion-wa** [comment]
I was not aware until it was mentioned to me that the scrapbook also adds to the word count.

![image](https://user-images.githubusercontent.com/79761754/179334815-d16c5597-f6e9-44f7-982e-e0f1234e87cb.png)

**Comment by iamromeo** [comment]
The Scrapbook does at to the Wordcount or at least it was never excluded - this we can exclude

**Comment by graylion-wa** [comment]
Thank you

**Comment by iamromeo** [comment]
Implemented much stricter word count that excludes

                    $col <> "scrapbook" &&
                    $col <> "displayCss" &&
                    $col <> "cssClasses" &&
                    $col <> "metaTitle" &&
                    $col <> "metaDescription" &&
                    $col <> "folderId" &&
                    $col <> "slug" &&
                    $col <> "state" &&
                    $col <> "seeded" &&
                    $col <> "templateType"

**Comment by graylion-wa** [comment]
@iamromeo 

Thank you so much for this updating of the word count!
