### ISSUE TITLE
Character portrait not saved.

### ISSUE THREAD

**Issue by OldManSteve40** [worldanvil/worldanvil-bug-tracker#1165]
**World Anvil Username**: Oldmansteve

**World / Campaign / RPG Character / Manuscript Title**: Gaston Stanza

**Feature**: Images

**Related URLS** (To public & visible pages add screenshots otherwise): 

**Describe the Issue**
Pictures not loading when I click "view" even though I added the image code from the library. 

**To Reproduce**

1. Click "New Earth Articles"
2. Click the edit button on either Gaston Stanza or Horus
3. Open Images in a new tab
4.  Copy the image code. [img:3309609] 
5. in the Edit article section, click on Character Portrait and paste the image code there. Also click on Design and paste the image code there.
6. Click Save then click View. 

**Expected behavior**
The image of the character should appear on the right hand side of the article. But it's not there.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/109465123/179397130-6b57284a-e26c-4d19-a284-f7fdcdb33980.png)

**Comment by Kordishal** [comment]
The character portrait has a search bar that you can use to type in the title or id of the image and it will come up. Then select the image you want to add. It will replace the search bar and enlarge the displayed image.

**Comment by OldManSteve40** [comment]
That did the trick!
