### ISSUE TITLE
World Export not working.

### ISSUE THREAD

**Issue by Jellvisk** [worldanvil/worldanvil-bug-tracker#1167]
**World Anvil Username**:
Jellvisk

**World / Campaign / RPG Character / Manuscript Title**:
All worlds.

**Feature**: 
World Export

**Related URLS**:
https://toolbox.soullink.docker.worldanvil.com/backup/form

**Describe the Issue**
World exporting does not seem to work at all. It produces an error as soon as you click Start, regardless if you choose to export just one, multiple, or all worlds.

**To Reproduce**
1. Go to https://toolbox.soullink.docker.worldanvil.com/backup/form
2. Fill out the forms as told.
3. Click "Start"

**Expected behavior**
The world(s) begin exporting properly.

**Screenshots**
![6JiJ2hF3fg](https://user-images.githubusercontent.com/91459458/179438811-d9a767e4-10b1-40af-9439-8c9aff7fad4c.png)

**Comment by Kordishal** [comment]
It is now working again. Thanks for the report!
