### ISSUE TITLE
URLs with parentheses break!

### ISSUE THREAD

**Issue by LadyAethera** [worldanvil/worldanvil-bug-tracker#1170]
**World Anvil Username**: aethera

**World**: Fantasy Novel Setting WIP

**Feature**: URL BBCode rendering

**Related URLS**: [link to wheelhouse wiki on this setting page](https://www.worldanvil.com/w/fantasy-novel-setting-wip-aethera/a/ria-s-childhood-home-landmark), [link to wikipedia on this workspace page](https://www.worldanvil.com/w/fantasy-novel-setting-wip-aethera/a/22-07-16-iron-age-buildings-with-magic-report#start)

**Describe the Issue**
Any link that contains parentheses such as [this Wikipedia page](https://en.wikipedia.org/wiki/Roundhouse_%28dwelling%29#United_Kingdom) must be typed in using ascii codes (% with 28 and 29 respectively) in order to render properly. If not, the parentheses are stripped out by the processing of the url tags and the link is broken. I imagine it just requires a line of code to process parentheses within the url tag versus the url that is presented in parentheses.

**To Reproduce**
1. Find any link with parentheses—wikipedia uses them a bunch, so those links may be the easiest.
2. Insert link into any page, save, and view the page. (Preview ought to show it also.)
3. The URL will be stripped of parentheses.

**Comment by iamromeo** [comment]
Hey there @LadyAethera 

World Anvil does not allow parenthesis on its titles, it is in fact removing them where possible :) 

This is actually documented under the Codex. 

Please do not use parenthesis of any kind on the titles of articles, that can and it will cause you issues with the @ mention system and the auto completer

**Comment by Kordishal** [comment]
Hey @iamromeo

You misunderstood the issue. They are talking about the URL BBCode not article titles & URLs. The [url] BBCode does filter out parenthesis. Which I have also noticed again recently. I do not remember if this came up before, but you might have said it was related to the security filters.

**Comment by iamromeo** [comment]
Yes it is - the solution / fix for this is to use bit.ly

**Comment by LadyAethera** [comment]
> use bit.ly or another shortner
Aww, is that really the only option? It seems like this ought to be fixable.

**Comment by iamromeo** [comment]
Sadly yes @LadyAethera this is a security feature to make sure that you are protected from creators that might us in-url Javascript execution
