### ISSUE TITLE
Spoiler & Tables not playing nice

### ISSUE THREAD

**Issue by kestrelca** [worldanvil/worldanvil-bug-tracker#1171]
**World Anvil Username**:Kestrelca

**World / Campaign / RPG Character / Manuscript Title**: Riesa

**Feature**: Article editor (both source & wysiwyg)

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/riesa-kestrelca/a/character-traits-in-riesa-article

**Describe the Issue**
I have enveloped tables within spoiler tags. (Tried to use Interactive Tables with Collapse feature but can't format the text the way I would like.) I can set up the page and article so that it looks correct and works correctly. But when I open up the page for editing again, it changes the coding. 

Some of the issues I've noticed:
- cell width code disappears [th:15] becomes simply [th]
- extra carriage returns are entered for every [tr] which increase whitespace in the revealed spoiler text (currently above the title)
- sometimes entire rows are stripped of [tr], [td], or [th] tags, requiring reformatting and editing again. Typically this only affects the first three rows for some reason.

**To Reproduce**

1. Write article
2. View (button)
3. Edit Article (link)
4. View Source

**Expected behavior**
The source should be unchanged by viewing or re-opening for editing.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
Before error...
![Screenshot 2022-07-19 123859](https://user-images.githubusercontent.com/109622600/179825181-0af3bcfd-f754-433b-abba-a0056afeb50f.png)

After reopening...
![Screenshot 2022-07-19 124119](https://user-images.githubusercontent.com/109622600/179825329-2f7dc853-e25f-4fbc-ac3c-7c6705acf980.png)

**Comment by iamromeo** [comment]
Hey @kestrelca  Spoilers within tables is not currently supported. I am really sorry but this is not a bug, it is simply advanced functionality not currently present. 

This MIGHT work using the advanced editor (Euclid) but it will certainly not work on the WYSIWYG (which you are currently using,) 

**Suggestion**
- Go to your interface options
- Switch to Euclid
- Try again.

Have a wonderful day!
