### ISSUE TITLE
Images on Whiteboards are resized by save while not visible on viewport

### ISSUE THREAD

**Issue by SBlack202** [worldanvil/worldanvil-bug-tracker#1172]
SBlack202

Lux

Whiteboard: 

Added Images that have been previously resized get smaller when not within the window bounds. Panning off of an image or saving the whiteboard while the image is not visible causes it to change size, even when locked.

1. Go to Whiteboard
2. Add a new image
3. Resize it to something smaller
4. Pan away from image
5. Pan back toward image
6. Image is now smaller

**Expected behavior**
The image shrinks in size, even when locked.

**Comment by Kordishal** [comment]
I was able to reproduce this for images when I made sure that the image was not on the view port during a save operation. While the image is visible this does not happen.

**Comment by iamromeo** [comment]
We have checked and cannot replicate this at this stage following both suggested replication tests
