### ISSUE TITLE
World does not delete when delete button is pressed

### ISSUE THREAD

**Issue by robowar20** [worldanvil/worldanvil-bug-tracker#1173]
**World Anvil Username**:
Robowar20
**World / Campaign / RPG Character / Manuscript Title**:
World name Xion
**Feature**: 
Deleting world
**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/world/57dc994f-2bc7-4a31-8ae5-59a2b428d20a/edit
**Describe the Issue**
A clear and concise description of what the issue is.
Every time I try to delete the world it does not go away
**To Reproduce**
G
**Expected behavior**
I expect when I hit the delete button the world will be delete from my profile.
**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Hi, this is a known issue! The workaround is to do the following steps (which apply to you) before deleting:

- Delete any campaigns on the world.
- Expel RPG characters from the world.
- Delete manuscripts that are associated with the world.
- Remove any co-authors and subscribers from your world
- Delete all the subscriber groups from your world.
