### ISSUE TITLE
Typo on sidebar style popover: "theeme" should be "theme"

### ISSUE THREAD

**Issue by DomenicF** [worldanvil/worldanvil-bug-tracker#1174]
**World Anvil Username**: rockstarrem

**World / Campaign / RPG Character / Manuscript Title**: N/A

**Feature**: Left sidebar of dashboard

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/dashboard/

**Describe the Issue**
When using the cursor to hover over the Styling icon on the left sidebar, the word theme is misspelled. 

**To Reproduce**
1. Go to the World Anvil dashboard (https://www.worldanvil.com/dashboard/)
2. Hover over the Styling icon on the left sidebar
4. See misspelling

**Expected behavior**
The text "theeme" should read "theme". The whole sentence should most likely read: `Styling: Customize the way your world looks; choose a theme, background, and default header image.`

**Screenshots**
![worldanvil-theeme](https://user-images.githubusercontent.com/241384/180042092-b1c0a227-dac7-4f22-9807-e05ce44de1fb.png)

I know this isn't a bug but I did not know where to report it. Just a very tiny spelling error that caught my eye.

**Comment by iamromeo** [comment]
Thank you @DomenicF  :) Fixed, will deploy within the next hours
