### ISSUE TITLE
Typo in settlement template owning rank

### ISSUE THREAD

**Issue by Hurttaj** [worldanvil/worldanvil-bug-tracker#1175]
**World Anvil Username**: frogdrake

**World / Campaign / RPG Character / Manuscript Title**: Spirit of the Age

**Feature**: Settlement Template

**Describe the Issue**
The template says "Nothing here? You will need to create a character first!."

**Expected behavior**
It should probably say "Nothing here? You will need to create a rank first!."

**Screenshots**
![image](https://user-images.githubusercontent.com/16683268/180210827-1909eca5-e2db-4f91-8df7-c9eceabfaf42.png)

**Comment by iamromeo** [comment]
Thank you for the heads up @Hurttaj
