### ISSUE TITLE
Character article displaying 404

### ISSUE THREAD

**Issue by hopedefiant** [worldanvil/worldanvil-bug-tracker#1178]
**World Anvil Username**: hopedefiant

**World**: Redere

**RPG Character**: [hero:robin-pewtersmith]

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/redere-hopedefiant/a/robin-pewtersmith-person?preview=true

**Describe the Issue**
The published character page in the world always leads to a 404. This started sometime last week. 

**To Reproduce**
Different ways to reproduce the behavior:
1. From "edit article" page in the world (https://www.worldanvil.com/world/person/8605c2e6-b677-45a1-a53c-66cd6a405bc0/edit), hit "view"
2. From the search bar in the upper left of any page in the Redere world, search for "robin pewtersmith" and select either of the two pages that appear
3. From the hero page (https://www.worldanvil.com/hero/robin-pewtersmith), hit "view in world"

**Expected behavior**
Display Robin Pewtersmith's article

**Screenshots**
<img width="529" alt="Screen Shot 2022-07-22 at 00 48 16" src="https://user-images.githubusercontent.com/109783233/180371667-fd98e91e-252d-4ebd-b6b2-209a6599e026.png">
<img width="718" alt="Screen Shot 2022-07-22 at 00 48 45" src="https://user-images.githubusercontent.com/109783233/180371736-26686d5c-2dff-4434-b097-6e823a894d3b.png">
<img width="357" alt="Screen Shot 2022-07-22 at 00 49 39" src="https://user-images.githubusercontent.com/109783233/180371866-83b0b689-c71e-4a6d-afff-58b55a8db933.png">

**Comment by iamromeo** [comment]
Hey @hopedefiant 

That most probably means that
- You had a person article with the name of your player
- The player with exactly the same name joined your campaign (and subsequently your world) 
- Now you have 2 articles with exactly the same name. 

**Solution**
- Delete the original article, keep only the article linked to the player character :) 


If you need any help do let me know.
