### ISSUE TITLE
This brown popup creature 

### ISSUE THREAD

**Issue by Azcend** [worldanvil/worldanvil-bug-tracker#118]
This is becoming annoying. What is this brown popup creature saying things like "cheerup by adding bananas they are always smiling. What is this?!?!?
![Screen Shot 2021-04-01 at 1 07 42 AM](https://user-images.githubusercontent.com/12548057/113246297-c4cd6480-9286-11eb-8d86-84cd53d09f68.png)

**Comment by Kordishal** [comment]
April Fool's day.
