### ISSUE TITLE
Word Count Goal

### ISSUE THREAD

**Issue by TamOBedlam** [worldanvil/worldanvil-bug-tracker#1180]
TamOBedlam

TorKaligo

Word Count Goal

<img width="714" alt="Screen Shot 2022-07-22 at 10 47 22 AM" src="https://user-images.githubusercontent.com/109814460/180476102-1e88ef6b-71f6-405b-aea1-cd543c58f244.png">
<img width="624" alt="Screen Shot 2022-07-22 at 10 28 05 AM" src="https://user-images.githubusercontent.com/109814460/180476125-06889c69-410b-4df3-9907-7489a8fff21a.png">

**Describe the Issue**
I have the word count goal set to 1 to disable the feature, but instead it shows that I am 848,700% complete (wouldn't that be nice!). 

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
@TamOBedlam can you please make sure that you have given me the correct WA username ? 
There is no user under: **TamOBedlam**

**Comment by TamOBedlam** [comment]
Maybe it needs the apostrophe? Tam O’Bedlam…I am a Master Worldbuilder if that helps…

**Comment by iamromeo** [comment]
Fixed, will deploy later today
