### ISSUE TITLE
Whiteboard Blackscreen Bug

### ISSUE THREAD

**Issue by DrRandomnesss** [worldanvil/worldanvil-bug-tracker#1182]
**DrRandomnesss**:

**Whiteboard**: 

**https://www.worldanvil.com/world/whiteboard/list** 

Whenever I try to open a new whiteboard or edit an existing one, I get a blackscreen

Open the whiteboards section and create a new one or try to edit an existing one

**Comment by iamromeo** [comment]
Please hard refresh your browser and clear your cache there is a new version of Whiteboards and your browser probably did not update.
