### ISSUE TITLE
Whiteboard is blank

### ISSUE THREAD

**Issue by MAEKrawczyk** [worldanvil/worldanvil-bug-tracker#1183]
M.A.E.Krawczyk

Whiteboard

https://www.worldanvil.com/world/whiteboard/104732c1-57ca-43a4-b873-315da72a5346

![Capture](https://user-images.githubusercontent.com/109869908/180615949-e1045986-e16c-4314-b950-49b6d15b5241.PNG)

The screen goes blank and all buttons are absent whenever I try to edit or create a whiteboard.

**Comment by iamromeo** [comment]
Please hard refresh your browser and clear your cache there is a new version of Whiteboards and your browser probably did not update.
