### ISSUE TITLE
Unable to Make World Public

### ISSUE THREAD

**Issue by clcrawford** [worldanvil/worldanvil-bug-tracker#1186]
**World Anvil Username**: crawford2021

**World / Campaign / RPG Character / Manuscript Title**: The Realm

**Feature**: Make Public

**Related URLS** (To public & visible pages add screenshots otherwise): ![Screenshot 2022-07-25 074022](https://user-images.githubusercontent.com/19202517/180779537-3dbac9ec-2b60-4bf8-b07c-d8c2e3a8f57a.png)

**Describe the Issue**
I am unable to make a world public in order to delete articles and/or delete the world. I receive a 504 gateway error. I used to have a guild membership and have more articles than allowed on the Freeman account, which I think is contributing to this issue. I have already exported the pages when I still had the guild membership, and just want the world deleted. I have tried several times over the past week, and am able to make other worlds public and delete, but not this one, which had more articles than the account level allowance. Also worth noting, when I try to delete the only other world left on my account (Mysteries of Golarion), I receive a 404 error. 

**To Reproduce**
1. Sign in
2. Go to Dashboard
3. Go to Your Worlds
4. Click Make Public
5. See error as per screenshot

**Expected behavior**
I need the world to be made public so that I can access it on Freeman account again, allowing me to delete the world altogether to make room on my account for a new world. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
This should now be fixed for you :) @clcrawford 
Keep in mind that you are over the article limit for free accounts
