### ISSUE TITLE
Request for Ascendant  SuperHero RPG Character sheet

### ISSUE THREAD

**Issue by MolocBabyDaddy** [worldanvil/worldanvil-bug-tracker#1187]
It would be useful to me to have a method to import/create character sheets/stat blocks for this game

Ascendant SuperHero RPG
Ascendant

worldAnvil Eternal grandmaster username: judeo

[**Website**:] (https://www3.autarch.co/?page_id=301)

https://www3.autarch.co/wp-content/uploads/2020/06/asc-cover.jpg

**Logo Usage Terms (URL)**:

Thank you

**Comment by iamromeo** [comment]
I have added Ascendant SuperHero RPG to the list of RPG games.
