### ISSUE TITLE
Error accessing Plots for my campaign

### ISSUE THREAD

**Issue by Haydenschmitt** [worldanvil/worldanvil-bug-tracker#1188]
**World Anvil Username**: Pileofschmitt13

**World / Campaign / RPG Character / Manuscript Title**:  Exandria

**Feature**: Plot Tab

**Related URLS** (To public & visible pages add screenshots otherwise):  https://www.worldanvil.com/heroes/campaign/plot/list

**Describe the Issue**
When I open my story tell screen and Open my Plot tab. The "manage campaign" link takes me to a page with the Error code "HTTP ERROR 500"

**To Reproduce**
1. Go to 'Plot tab under Storyteller's screen'
2. Click on 'Manage Campaign Plot'
3. See error

**Expected behavior**
I expect this to open the page in which I can create new Campaign Plots and edit existing ones.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/110042713/181031909-ecff2918-9aac-4fc8-90ab-7455cdcef8ab.png)
![image](https://user-images.githubusercontent.com/110042713/181032278-c08a6f4a-92d2-448e-a9fd-8da49efe42cc.png)

**Comment by iamromeo** [comment]
Hello there @Haydenschmitt 

The chances are that you have somehow created a circular parent-child reference. That means that one your plots or one of their children is also a parent of one on top of it down the chain. 

The solution for this is: 
Go thought your plots and find the one that does that and fix the connection. The moment you do that it will start working again :)

**Comment by Haydenschmitt** [comment]
Hi thanks for answering. I sent a second report in because im a fool and didnt check my email. Sorry about that you guys are awesome!
