### ISSUE TITLE
@ mentions are not saving

### ISSUE THREAD

**Issue by Ijustwanttoreportabugcurseyou** [worldanvil/worldanvil-bug-tracker#1189]
**World Anvil Username**: St George Dragonslayer

**World / Campaign / RPG Character / Manuscript Title**: Manat

**Feature**: @ content mentioning

**Related URLS** (To public & visible pages add screenshots otherwise):  First appeared on https://www.worldanvil.com/world/settlement/6740468d-128b-41ca-af8d-cd4a31406e4d/edit

**Describe the Issue**
@ content mentions are not saving to edited articles.  When I add new @ mentions and save the article, the @ mentions do not save.  the @aaa appears as plain text.  If I open a page with existing @ mentions and save the page the old @ mentions remain, but new @ mentions will appear as plain text.  This does not happen on new articles made through the Quick Content function.

**To Reproduce**
1. Open any article to edit
2. type an @ mention into any of the text fields.  I've been typing @isa and clicking on Isabeth to complete the @ mention
3. Save the article
4. Refresh the article or view the article
5. Witness that only the @isa remains, or @isa appears as plain text if you view the article

**Expected behavior**
I expected @ mention to create a reference link to another article.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Mention 1](https://user-images.githubusercontent.com/63316181/181133988-ad1fd81c-852c-4ebc-9cac-c1f33ad2eee9.PNG)
![Mention 2](https://user-images.githubusercontent.com/63316181/181133997-6734e1af-2be9-49a6-80d0-cfdf0bd23ea5.PNG)
![Mention 3](https://user-images.githubusercontent.com/63316181/181134006-4c137e3d-92ca-40df-b85f-e7d8a0cfaca2.PNG)

**Comment by iamromeo** [comment]
That looks more like you refreshed the page before the changes had the time to be saved. We tried it across 5 different systems and this cannot be reproduced. Can. you give us more details in regards to the sequence of actions you have taken,

**Comment by Ijustwanttoreportabugcurseyou** [comment]
After much trial and error trying to figure out the best way to show you what was happening (screenshots, screen captures, etc), I made a breakthrough.  The @ mention will not work unless I add a SPACE or and LINE BREAK or TEXT after the @ mention.  If I just add the @ mention with nothing after it, then it will not work.  I do not know if this is as intended, but at least I know what to do now.  Thank you for your prompt response.  Please close this report.

**Comment by Kordishal** [comment]
The issue here is that the save does not pick up text or code added with mouse clicks only. So pressing any keyboard key fixes this.
