### ISSUE TITLE
Moving map pins in Edit screen doesn't update/save their positions

### ISSUE THREAD

**Issue by artyrambles** [worldanvil/worldanvil-bug-tracker#119]
**World Anvil Username**: arty

**World / Campaign / RPG Character / Manuscript Title**: The Hummelverse

**Feature**: Map pins

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/the-hummelverse-arty/map/cc7aab21-322c-4197-8a2d-c73dd473f6b8

**Describe the Issue**
I am trying to edit the position of map markers in the map editing screen. But their new positions when I drag them around doesn't get saved and it's not reflected in the Markers tab.

**To Reproduce**
1. Edit map
2. Drag an existing pin to the new position
3. Open the presentation screen
4. The pins are still in their old position

**Expected behavior**
If I move a pin around, I expect it to save its new position when I leave the page.

**Screenshots**
This is what I see in the editing screen: 
![editing screen](https://media.discordapp.net/attachments/514586810324615168/827240895694372975/unknown.png)

This is what I see in the presentation screen:
![presentation](https://media.discordapp.net/attachments/514586810324615168/827240999771832430/unknown.png)

**Comment by Kordishal** [comment]
The pins are saved after moving. The marker page needs a refresh to be up to date.

**Comment by artyrambles** [comment]
> The pins are saved after moving. The marker page needs a refresh to be up to date. I move the pin and then reload the presentation mode and the pin moves.

It still doesn't work. The pins don't save their new position for me, regardless of the marker page.

**Comment by Kordishal** [comment]
Does not happen on all maps. Only on this particular map. The edit function returns a 500 internal server error when moving.

**Comment by iamromeo** [comment]
Potentially an issue with an extension adblocker or firewall this looks like a client based issue.

**Comment by iamromeo** [comment]
@artyrambles try on incognito mode and other browser and let me know if it perists
