### ISSUE TITLE
Co-author can't access Project

### ISSUE THREAD

**Issue by MrSaltyAuthor** [worldanvil/worldanvil-bug-tracker#1190]
**World Anvil Username**: MrSaltyAuthor

**World / Campaign / RPG Character / Manuscript Title**: The Proteus Chronicles

**Feature**: Co-author

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

I went to add a friend's account to my World Anvil Project and they can't access the Project after being added.

**To Reproduce**
Steps to reproduce the behaviour: 

**Expected behavior**
I expected my Project to come up in his accounts worlds section with the ability to edit
**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Hey there @MrSaltyAuthor 
- How did your friend tried to access your world? (Specifically which steps they followed after logging in) 
- What is their username (so I can check they have the role)

**Comment by MrSaltyAuthor** [comment]
After signing in they:
- went to their profile page and it wasn't
- then they went directly to the public project page and their name was there but they had no edit links
Their account name is NineWizard

**Comment by iamromeo** [comment]
hello @MrSaltyAuthor 
This is not how a co-author gets access to a World. 
They need to go to their Dashboard (first page they see when they login or click the top left logo) and then go to their WORLDS option and SWITC TO THIS WORLD or ACTIVATE the world. 
<img width="1728" alt="Screenshot 2022-07-30 at 6 28 16 AM" src="https://user-images.githubusercontent.com/660175/181870783-fb050a5d-2ce5-48d2-9293-3b535dfa7d72.png">
