### ISSUE TITLE
Placing Maps on whiteboards is broken.

### ISSUE THREAD

**Issue by Sleeclow** [worldanvil/worldanvil-bug-tracker#1191]
**World Anvil Username**: Sleeclow

**World / Campaign / RPG Character / Manuscript Title**: Whiteboards and Maps

**Feature**: Whiteboards

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.
Maps can not be placed on a whiteboard.
**To Reproduce**
Steps to reproduce the behavior: Create a map, create a whiteboard, try to put the map on the whiteboard using the green plus, and nothing will happen.

**Expected behavior**
The map to appear on the Whiteboard
**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
i am sorry but this request has no information - can you please elaborate @Sleeclow

**Comment by Duranzno** [comment]
Thank you for bringing this to our attention. This issue has now been solved. Please test it.

**Comment by Sleeclow** [comment]
> Thank you for bringing this to our attention. This issue has now been solved. Please test it.

just tested, it works! thank you.

**Comment by Sleeclow** [comment]
So it works partially. Double clicking on the map does not open it like it does an article.
