### ISSUE TITLE
Maps are now placeable on whiteboards, but can not be opened from the Whiteboards

### ISSUE THREAD

**Issue by Sleeclow** [worldanvil/worldanvil-bug-tracker#1192]
So it works partially. Double clicking on the map does not open it like it does an article.

_Originally posted by @Sleeclow in https://github.com/worldanvil/worldanvil-bug-tracker/issues/1191#issuecomment-1198292807_

Very easy to duplicate, place a map on a whiteboard, and try to double-click the map on the whiteboard, it should open up in a new tab like articles do. (At least I would assume that would be intended.)

**Comment by Duranzno** [comment]
We are checking the current issue

**Comment by Duranzno** [comment]
Sorry for the delay, this issue has now been fixed.

**Comment by Sleeclow** [comment]
> Sorry for the delay, this issue has now been fixed.

Still doesn't work for me.

**Comment by Kordishal** [comment]
Try a hard refresh with CTRL + F5

**Comment by Sleeclow** [comment]
> Try a hard refresh with CTRL + F5

Still doesn't work

**Comment by Duranzno** [comment]
Have you tried adding new elements?

alejandro duran linkedin personal website m. 407-491-3205

**Comment by Sleeclow** [comment]
Added a different map to the same white board worked, then deleting the old map from the whiteboard and re adding has now caused it to work. Thank you!

**Comment by Duranzno** [comment]
Thank you and sorry for the problems!
