### ISSUE TITLE
List and heading formatting

### ISSUE THREAD

**Issue by Groonfish** [worldanvil/worldanvil-bug-tracker#1193]
**World Anvil Username**: Groonfish

**World / Campaign / RPG Character / Manuscript Title**: Tourmaline Valley, Humdrum Star

**Feature**: article body

![3006D2AD-DB20-404D-A55D-6269D9E2F40F](https://user-images.githubusercontent.com/110190393/181594603-03077385-d2a5-4661-ac24-b0c679ef22a8.png)

**Related URLS** (To public & visible pages add screenshots otherwise):

![A15E3BFD-9BF8-4F9D-9068-27464793D6F3](https://user-images.githubusercontent.com/110190393/181594582-f7d9fa6b-2f0c-42ef-b8b9-821215277dec.png)

**Describe the Issue**

After writing an article and utilizing the list or header functions, when I return to edit the article, whole sections will no longer “read” the code and will just present plain code, as you can see in the picture. This can sometimes be next to working bullet lists and headers, as you can see in the other picture. No rhyme or reason to it, but it happens all the time, and is prevalent enough that I don’t often use this platform as a result. 

**To Reproduce**
1. Write an article with bullet points and/or headers
2. Save the page
3. Leave the website and return to article edit

**Expected behavior**
Standard formatting of lists and headers.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window! 

Attached above.

**Comment by iamromeo** [comment]
Hey there  @Groonfish  :) 
 First of all - from what you can see there are a lot of unclosed or double closed [li]'s on this text. But regardless of that if. you are using higher level components (like headers) into lists you might run into problems with Euclid which is able to handle only the simplest of formatting. 

1. Make sure you close all your list elements correctly 
2. Maybe give a try to the advanced editor (Euclid)

**Comment by Groonfish** [comment]
Ok, that’s good to know. I don’t actually write the list in the code side, so if the formatting is breaking that’s happening in the back end — it sounds like that might be what you’re referencing about Euclid. I know nothing about code, but it seems a bit finicky in general. I’ll try the advanced editor and see if I can clean things up. Anyways, thanks for the follow up. That explains why the lists aren’t generating.

>
