### ISSUE TITLE
Autolinker not working in Euclid on iPad Pro?

### ISSUE THREAD

**Issue by Wheelmanforhire** [worldanvil/worldanvil-bug-tracker#1194]
**World Anvil Username**: wheelmanforhire

**World / Campaign / RPG Character / Manuscript Title**: 100 Worlds

**Feature**: Autolinker

**Related URLS** (To public & visible pages add screenshots otherwise): any

**Describe the Issue**
Using iPad Pro, I press autolinker and nothing pops up.

**To Reproduce**
1. Edit article
2. Type some constant with know article titles
3. Press Autolinker
4. Nothing happens (I’m a GrandMaster and should have autolinker access)

**Expected behavior**
Autolinker should pop up just like the videos show

**Screenshots**
N/a

**Comment by iamromeo** [comment]
Are you by any chance using Safari ?

**Comment by JohnHFriez** [comment]
I am not.

**Comment by Wheelmanforhire** [comment]
I’ve tried both Safari and Chrome on my iPad… neither pulls up the linker 


Sent from Yahoo Mail for iPhone


On Friday, July 29, 2022, 11:30 PM, Dimitris Romeo Havlidis ***@***.***> wrote:




Are you by any chance using Safari ?

**Comment by iamromeo** [comment]
Hey @Wheelmanforhire I can confirm that this actually occurs. We had similar issues with Javascript in the past. 
Sadly I am not sure I have a solution for this (right now) We are working on a long term solution that will most certainly fix this.
