### ISSUE TITLE
Subscribers not seeing my manuscript.

### ISSUE THREAD

**Issue by JohnHFriez** [worldanvil/worldanvil-bug-tracker#1195]
**World Anvil Username**: JohnHFriez

**World / Campaign / RPG Character / Manuscript Title**: World, Adamah; MS; Truth Will Out

**Feature**: Msnuscripts and notifications

**Related URLS** (To public & visible pages add screenshots otherwise):
Private Manuscript 

**Describe the Issue**
subscribers cannot locate the Private Manuscript for the world and are not receiving notifications when the new chapters are published.

**To Reproduce**
1. Go to Manuscripts
2. Verify editors subscription group has been granted access.
3. Click on Publish

**Expected behavior**
The "editors" subscription group members should receive a notification and should be able to find and read the manuscript.

The subscribers do not receive any notifications and cannot locate where in their user interface they can go to in order to read the Manuscript.

**Comment by iamromeo** [comment]
Hey @JohnHFriez !

If your manuscript is private, subscribers will only be able to find your manuscript if you give them a link or add a link to your world. 

In order for them to get updates for your manuscript they will need to be FOLLOWING you.
