### ISSUE TITLE
Sessions: The "send invitation email" button does not reliably send email

### ISSUE THREAD

**Issue by jimu** [worldanvil/worldanvil-bug-tracker#1196]
**World Anvil Username**: jimu

**Feature**: Sessions

**Describe the Issue**

The "send invitation email" button does not reliably send an email.

**To Reproduce**

1. Create a party P with members A and B.
2. Create a session for party P
3. Add member C to the party
4. Send invites.
5. Check C's email and observe that member C has not received an invitation
7. manually add member C to the player list
8. Send invites.
9. Check C's email and observe that member C has not received an invitation
10. Observe that C has disappeared from the player list.
12. manually add member C to the player list again
13. Press save
14. Send invites
15. Check C's email and observe that world anvil has FINALLY invited C.

So, pressing "Send invites" without saving first destroys form input. This is a nasty side effect.   Either auto-save the form contents when pressing SEND INVITES or disable the "Send invites" button because it is destructive.

**Expected behavior**
SEND INVITE should send invitations to all members of all parties involved in the session.

**Actual behavior**
SEND INVITE does not send invitations to Party members. It only invites characters in the hero list that were present when the form was rendered. Players added to the hero list are SILENTLY ignored unless the form is saved and re-rendered.

Further complicating the issue is that the help text specifically instructs the user NOT to include both a hero list and party list; they should define only heroes or only parties. So, if I follow this help, I will empty the heroes list and then send invitations, assuming that everybody in the party(s) will receive invitations.   Nobody gets invited.

Moreover, there is no "sent email" folder for me to inspect, so there is no way to verify who did or did not get emailed.

This "feature" is less than worthless because sending invitations results in a false sense of security. The system sends no invitations, and nobody shows up to the session. Or worse, some people are invited and show up, while other players do not, and we assume they weren't interested while world anvil simply didn't invite them.

**Comment by jimu** [comment]
![flash_message](https://user-images.githubusercontent.com/1031130/182332837-85c83000-7879-44bc-9482-e75b0df70345.jpg)

A bootstrap flash message like this would help

**Comment by GorkamWorka** [comment]
added the flash message. 

The autosave however is not gonna be implemented on this version as this system is due to rework anyway
