### ISSUE TITLE
Sessions: invitation email message includes incorrect time

### ISSUE THREAD

**Issue by jimu** [worldanvil/worldanvil-bug-tracker#1197]
**World Anvil Username**: jimu

**Feature**:  Sessions

**Describe the Issue**
Sessions scheduled in the afternoon or evening invite players to play in the morning

**To Reproduce**

1. create a session
2. enter a time of 18:00
3. send invitation
4. players receive notification that session will be at 06:00
5. Note that both form and message do not include am/pm. They are both expressed with a leading "0" indicating a 24-hour clock.

**Expected behavior**
Players are either invited to play at 18:00 or 6PM

**Actual behavior**
Players are invited to play at 06:00, which is 6AM

**Comment by GorkamWorka** [comment]
Done, Will deploy with the other fix
