### ISSUE TITLE
Sessions: Invitation email message includes blank (player?) list

### ISSUE THREAD

**Issue by jimu** [worldanvil/worldanvil-bug-tracker#1198]
**World Anvil Username**: jimu

**Feature**: Sessions

**Describe the Issue**
Invitation email messages sent to players include this content:

>   You will be hanging with .

OR

> You will be hanging at my location http://vttur.com with .

OR

> You will be hanging at my location with .

**To Reproduce**

1. create a session
2. include players in the session
3. send invites
4. observe meaningless "with ." text in the content of the invitation message.

**Expected behavior**
Text should reads:

> You will be haning with Player/Character1, Player/Character2, Player/Character3.

**Comment by GorkamWorka** [comment]
Added a list of session member (both player and storyteller)
