### ISSUE TITLE
Sessions: Session Experpt not included in invitation message

### ISSUE THREAD

**Issue by jimu** [worldanvil/worldanvil-bug-tracker#1199]
**World Anvil Username**: jimu

**Feature**: Sessions

**Describe the Issue**

The interface includes an "Excerpt" field with the prompt "Something to tantalize your players"

I took the time to created a session with an interesting exerpt. My expectation was that it would be shared with the players when inviting them to the session. the exerpt is not included in the message, nor is it linked to in the message.  There's no easy way for anyone to ever see it.

What's the point of authoring session content to "tantalizing your players" into attending the session if there is no easy way for them to ever see it?

**To Reproduce**

1. create a session
2. type tantalizing text int he excerpt filed
3. send invitations
4. observe that the tantalizing text does not appear in the email messsage
5. click the link included in the email
6. observe that the link takes you to the player's world anvil dashboard, not to a page related to the invitation

**Expected behavior**
The tantalizing experpt in included in the invitation message.

**Comment by GorkamWorka** [comment]
added the excerpt at the start of the mail
