### ISSUE TITLE
Item Statblock Visual Theme Bug

### ISSUE THREAD

**Issue by SomebodyPNG** [worldanvil/worldanvil-bug-tracker#12]
**World Anvil Username**:
qupsy.doodle

**World / Campaign / RPG Character / Manuscript Title**:
The Seavocra Empire / (NA) / Thamior / (NA)

**Feature**: 
Creating New Statblocks

**Related URLs**:
Monster, Item, Class, and Spell Statblocks (Editing/Creating)
https://www.worldanvil.com/heroes/sheet/choose?templateId=2991
https://www.worldanvil.com/heroes/sheet/choose?templateId=2999
https://www.worldanvil.com/heroes/sheet/choose?templateId=25
https://www.worldanvil.com/heroes/sheet/choose?templateId=3000

**Describe the bug**
The colours are jumbled up, looking like a mix of the 'Villain (Dark Gray)' Theme and the 'Heroes (Light Mode)' Theme. This makes it so it's difficult to read titles and tips. So far, this has only happened when creating new Monster, Item, Class, and Spell stat blocks. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Dashboard
2. Click on your account icon in the top right corner > Go to 'Interface Settings'
3. Change Theme to 'Villains (Dark Gray)'
4. Head back to Dashboard
2. Go to 'Create a New' Section
3. Click on 'Statblock'
4. Click on 'Items' (Monster, Class, and Spell works too)
5. See error 

**Expected behaviour**
I expected the template to have clearly visible and readable titles matching the theme when creating a new stat block. 

**Screenshots**
Typical Statblock Theme Colours --
![Screenshot 2021-02-28 at 12 50 41 PM](https://user-images.githubusercontent.com/79803451/109428129-9af0fb80-79c3-11eb-9728-75ddd208c4ab.png)
. . . 
Bugged Item Statblock Theme Colours --
![Screenshot 2021-02-28 at 12 19 15 PM](https://user-images.githubusercontent.com/79803451/109427199-421f6400-79bf-11eb-9e45-c840bd6a741b.png)
. . . 
Bugged Spell Statblock Theme Colours
![Screenshot 2021-02-28 at 12 45 08 PM](https://user-images.githubusercontent.com/79803451/109428155-b3f9ac80-79c3-11eb-930e-1cc87d7b80ab.png)

**Comment by GorkamWorka** [comment]
Hi, 
Can you specify  which RPG system is it for ?

**Comment by Kordishal** [comment]
Hi. The stat blocks are created and maintained by community members and not by the World Anvil team. So if you really want to have it changed you will need to contact the creator of the template.

The issue here is that the villain theme overwrites some values which the other two themes do not. It takes a lot of time and effort to create these sheets, so ensuring that they are optimal on all three interface themes and presentation guild themes is almost impossible.

Therefore my suggestion would be to either accept this or simply switch to one of the other themes while editing sheets.

**Comment by Tillerz** [comment]
For the Class Feature block there is a new (2020) version available: https://www.worldanvil.com/community/rpg/system/dnd5e?template=5460. The other three definitely could get looked at, I'll see what I can do.

**Comment by Tillerz** [comment]
Monster, Item and Spell are fixed, for Class Feature please switch to the 2020 version.

**Comment by Tillerz** [comment]
Change see https://github.com/iamromeo/worldanvil-templates/pull/146
