### ISSUE TITLE
Sessions: Invitations to a session include link to the session

### ISSUE THREAD

**Issue by jimu** [worldanvil/worldanvil-bug-tracker#1200]
**World Anvil Username**: jimu

**Feature**: Sessions

**Describe the Issue**

Invitation emails include a link to the world anvil dashboard, not the session they have been invited to.

A session is configured with information and links that are not included in the invitation email message. It would be helpful if the message would at least make it easy to discover the missing information.

It would also be nice if the invitation linked to SOMETHING with context to the world, campaign, party, character or session related to the inviter.

Instead the link just dumps the player on world anvil.  The player then has to figure out who invited them to what world and what campaign and what party and what session.

**To Reproduce**

1. create a session
2. send invitations
3. open an invitation email message
4. click the invitation link
5. observe you've been dumped onto the world anvil dashboard, a page unrelated to the invitation. You now have to discover and navigate to the session page somehow

**Expected behavior**

clicking the link takes me to the session endpoint

**Comment by GorkamWorka** [comment]
The Session link is not intended to be on this mail, the link you are talking about is a link to WA main page that is present by default.
Therefore this is not a bug. 
If you want a feature added to this mail, you can use the feature suggestion board on the website.
