### ISSUE TITLE
Sessions: Session owner cannot moderate session stream content

### ISSUE THREAD

**Issue by jimu** [worldanvil/worldanvil-bug-tracker#1203]
**World Anvil Username**: jimu

**Feature**: Sessions

**Describe the Issue**

Issue 1: Session owner cannot moderate inappropriate content added by a player.

Issue 2: Campaigns that do not use streaming still use sessions to manage player invites and to use the Article's Session field to relate an article to a game session.  In this case, giant SESSION STARTED and PLAYER JOINED events banners are attached to a session even though they mean nothing and cannot be deleted by the session owner

** Steps to Reproduce **

1. create a session
2. start the session
3. Using a player account, enter "Hitler did nothing wrong" to the stream.
4. Using a player account, add pornographic content to the stream
5. Observe that the owner (who has responsiblity for the stream and should have moderator control) cannot remove the undesired content without deleteing the entire stream

** Steps to reproduce issue 2 **

1. create a session
2. start a session
3. end a session
4. try to delete the garbage steam events:
- Test session 2 has come to an end.
- Test session 2 has come to an end (player 1)
- Test session 2 has come to an end (player 2)
- Test session 2 has come to an end (player 3)
- Test session 2 has come to an end (player 4)
- Test session 2 has come to an end (player 5)
- Test session 2 has come to an end (player 6)
- Test session 2 started.
- Test session 2 started (player 1)
- Test session 2 started (player 2)
- Test session 2 started (player 3)
- Test session 2 started (player 4)
- Test session 2 started (player 5)
- Test session 2 started (player 6)
5. observe that the drop down menu is empty.

** expected behavor

DELETE should appear when the session owner clicks on a session stream event's menu

A session owner should also be able to change the status of a session from PENDING to ENDED/COMPLETE without having to START and END it because starting and ending a stream populates it with undesirable garbage (start and end) events.

**Comment by iamromeo** [comment]
This is not a feature
