### ISSUE TITLE
Adding Images to a world you were added to as a co-creator don't get added to the world.

### ISSUE THREAD

**Issue by Kitsuyumia** [worldanvil/worldanvil-bug-tracker#1204]
**World Anvil Username**: Kitsuyumia

**World / Campaign / RPG Character / Manuscript Title**: World

**Feature**: Images

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I am a Co-creator on a world that a friend made for me since at the time I did not have guild membership. I had the world active and I added 2 large images (one being over 1000 x 4000 pixels the other being over 2000 x 3000 pixels), but they did not appear in the world images section. I check my account unsorted images and they were there but the world they were listed as being under was blank. When I tried to add them to a world it would only list worlds I directly created. They only were added once I moved them to a new gallery I created for that world.

**To Reproduce**
1. Make the desired world active
2. Select images tab
3. Click on the box on the left that says click pr drag images to add them.
4. When window pops up select all images by using ctrl click and then upload them.
5. if the bug happened they would not be visible in that worlds files and you will have to go to your personal unsorted images to find them.

**Expected behavior**
I expected them to be added directly to the world

**Screenshots**
No screenshot available. I found a work around before I reported this issue.

**Comment by iamromeo** [comment]
Thank you for reporting this - it is already in teh pipeline :)
