### ISSUE TITLE
Image Tags not saving

### ISSUE THREAD

**Issue by Kitsuyumia** [worldanvil/worldanvil-bug-tracker#1205]
**World Anvil Username**: Kitsuyumia

**World / Campaign / RPG Character / Manuscript Title**: World

**Feature**:  Image Tags

**Related URLS** (To public & visible pages add screenshots otherwise): 

**Describe the Issue**
when adding tags to images among other details, tags seem not to be saved while everything else saves.

**To Reproduce**

quick edit
1. Go to 'an image and select it
2. fill tag section with some tags
3. change name or another detail to force an autosave
4. tags will have cleared out.

advanced edit
1. Go to image and select the advanced edit option
2. scroll down to the tag field and insert tags
3. scroll up and select save changes.
4. scroll down and see that tags cleared out.

**Expected behavior**
I expect tags to be saved and listed under the image.

**Screenshots**
quick edit screenshots:

original
<img width="877" alt="Original" src="https://user-images.githubusercontent.com/64933901/182039734-641253b9-78a7-4cea-8d75-8606613a3400.png">

before save
<img width="880" alt="before save" src="https://user-images.githubusercontent.com/64933901/182039750-5a1e8890-37a3-4e15-b5b4-ef3053cc8578.png">

after save
<img width="878" alt="after save" src="https://user-images.githubusercontent.com/64933901/182039761-81d5983d-4349-448e-a930-660a6bfacb63.png">

----
advanced edit screenshots:

original
<img width="878" alt="advanced edit original" src="https://user-images.githubusercontent.com/64933901/182039779-7b54cb09-8a65-4f5a-ba3a-8e236daaa16a.png">

before save
<img width="879" alt="advanced edit before save" src="https://user-images.githubusercontent.com/64933901/182039789-fca94f04-59d7-4797-8078-a7f7eb25217d.png">

after save
<img width="875" alt="advanced edit after save" src="https://user-images.githubusercontent.com/64933901/182039797-a9ad1690-3e77-4d4d-b624-e3d984308740.png">

**Comment by iamromeo** [comment]
Are you copy pasting the tags or actually writing them?

**Comment by Kitsuyumia** [comment]
> them

I am writing them out every time. I didnt know if you could copy and paste since you cant on alot of websites.

**Comment by iamromeo** [comment]
You cannot and you shoudln't I was just making sure this was not the issue.

**Comment by iamromeo** [comment]
I am really sorry but I cannot reproduce this. 
We have tried it across Mac/PC and chrome/firefox in both with no issues. Is there a chance your tags were over 128 characters in total?

**Comment by Kitsuyumia** [comment]
> I am really sorry but I cannot reproduce this. We have tried it across Mac/PC and chrome/firefox in both with no issues. Is there a chance your tags were over 256 characters in total?

I dont believe so.
