### ISSUE TITLE
Summer Camp Article Un-Submitting

### ISSUE THREAD

**Issue by usurperkings** [worldanvil/worldanvil-bug-tracker#1206]
**World Anvil Username**: usurperkings

**World / Campaign / RPG Character / Manuscript Title**: Lieben Cycle

**Feature**: Summer Camp Articles

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/community/challenge/summercamp-2022/homepage/usurperkings

**Describe the Issue**
A clear and concise description of what the issue is. 
I submitted all 31 articles for Summer Camp 2022. They were all present, but one, the article about 'A food that marks a rite of passage...' kept un-submitting my Break-Fast article. I kept re-uploading, and it was fine. Until I checked after Summer Camp's deadline, and saw it yet again, isn't there. 

I had all 31 articles done and submitted, why is it removing one!? Help! 

You can see on my summer camp challenge there's one article missing. But I've submitted it multiple times, and it seemed to work, before it would just.... not. What happened?

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
I cannot replicate this - but please message the Community team after the badges are given to fix this issue for you.

**Comment by usurperkings** [comment]
https://www.worldanvil.com/w/lieben-cycle-usurperkings/a/break-fast-ritual?preview=true

This is the article, as per Ondo's ask.
