### ISSUE TITLE
Privacy State text broken

### ISSUE THREAD

**Issue by pressF13** [worldanvil/worldanvil-bug-tracker#1207]
**Describe the Issue**
When going to the Private/Public World setting, the text describing the Privacy state is broken, looks like the HTML code underneath is incorrect/incomplete tag, issue affects the hover text as well.

**To Reproduce**
1. View World
2. Click Settings
3. See error on the right hand

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![bug](https://user-images.githubusercontent.com/110419327/182213699-a1580090-f2a0-4808-ad35-c9f25f32723e.png)

**Comment by iamromeo** [comment]
Thank you for reporting!

**Comment by pressF13** [comment]
@iamromeo Hi, you’re welcome, but the issue persists.

**Comment by pressF13** [comment]
@iamromeo It's been relegated to the hover text
![image](https://user-images.githubusercontent.com/110419327/182539555-66b7bae4-8f2f-41bc-8bf0-aacf0d796e86.png)
