### ISSUE TITLE
Elven Forest CSS Theme Border error

### ISSUE THREAD

**Issue by RowanSilveroak** [worldanvil/worldanvil-bug-tracker#1208]
**World Anvil Username**: Rowan Silveroak

**World / Campaign / RPG Character / Manuscript Title**: Nifaalar

**Feature**: Elven Forest CSS Theme

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/nifaalar-rowan-silveroak

**Describe the Issue**
Hi! It seems that the border on the Elven Forest CSS Theme has turned grey, and the border around the comments/metadata box has turned brown?

**To Reproduce**
1. Go to '...' Any World Anvil world page, or article page
2. Click on '....' N/A
3. Scroll down to '....' N/A

**Expected behavior**
Usually the border is green with a gold-ish embellishment?...

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

![border](https://user-images.githubusercontent.com/109169482/182278328-09920337-04df-4a3b-861a-3024d09166e1.png)

![comments and meta](https://user-images.githubusercontent.com/109169482/182278355-6356e755-fb35-4156-aa36-c76e7872358b.png)

**Comment by GorkamWorka** [comment]
@RowanSilveroak can you confirm it's indeed fixed ?

**Comment by RowanSilveroak** [comment]
Yep! Everything seems to be fixed! ^.^
