### ISSUE TITLE
UX Menu Collision on iPad

### ISSUE THREAD

**Issue by MatthewThornton** [worldanvil/worldanvil-bug-tracker#1209]
**World Anvil Username**:
DragonFever 
**Related URLS** (To public & visible pages add screenshots otherwise):

[https://www.worldanvil.com/w/forgotten-realms-dragonfever/map/6e912664-0f47-4137-afe8-4bbf6909bca0](https://www.worldanvil.com/w/forgotten-realms-dragonfever/map/6e912664-0f47-4137-afe8-4bbf6909bca0)

**Describe the Issue**
A clear and concise description of what the issue is.
- There is a UX collision between the view map button and the general map button. 
- text in the button does not fit button space. 

**To Reproduce**
I was using an iPad 7 with mobile safari in landscape mode.  I assume this issue is universal on that device or similar device. 

**Expected behavior**

- Button text should fit in the space. IE: padding smaller text etc. 
- Make a UX change so the buttons don’t overlap. 

**Screenshots**
 Notice the center red button and the grey map button. 

![65ECB792-76E9-430F-89F6-8C43F3013DA3](https://user-images.githubusercontent.com/973184/182520204-b908be63-a80c-4c14-a037-6b7d826e1707.jpeg)

**Comment by iamromeo** [comment]
Fixed will deploy later today.
