### ISSUE TITLE
Historical Event shows up in two different Eras/Ages on same timeline despite having date range fitting inside one of the ages

### ISSUE THREAD

**Issue by jlinde1** [worldanvil/worldanvil-bug-tracker#1210]
**World Anvil Username**: CrazyZonie

**World / Campaign / RPG Character / Manuscript Title**: Dragon Chess

**Feature** Timeline/Historical Event: https://www.worldanvil.com/w/dragon-chess-crazyzonie/t/the-timeline-of-ihraidon-timeline

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/dragon-chess-crazyzonie/t/the-timeline-of-ihraidon-timeline

**Describe the Issue**
When adding the Historical Event article for "WAR BETWEEN MEDICI AND TREVERNO (FIRST TREVERNO-MEDICHI WAR)", it appears on the timeline twice, once for the Age of the Empire and once for The Age After the Fall. It should only appear in the Age after the Fall. Deleting one entry deletes both entries from the timeline. Recreated the entry from the timeline sidebar adds the entry back to both Eras. Removing the Timeline from the Historical Event removes both entries, but putting the timeline back puts the entry back in both eras. Removing/adding back in the linked article on the war does nothing.

I used the chat with a moderator feature. They were not able to figure this out and suggested I submit this issue.

**To Reproduce**
1. Go to the Ihraidon Timeline
2. Click on Create a New Historical Entry
3. Add a title on the new entry screen.
4. Add a start and end date to the new entry screen.
5. Link the Timelinein the new entry screen.
6. Click the  Show Advanced Options entry at the bottom of the screen.
7. Link the article on the event to the Historical Event screen.
8. Save the Event.
9. Return to the timeline.
10. See the event listed twice, once each under two different eras

**Expected behavior**
the Event should only show up once on the timeline within the Age After the Fall era.
![First Half of the timeline screen shot](https://user-images.githubusercontent.com/62734881/182689594-6f164bf2-6e14-4dce-b428-cecb4131a1dd.png)
![Historical Event screen](https://user-images.githubusercontent.com/62734881/182689609-86819a5e-55f4-4c91-ab08-acee98a952d7.png)
![Second Half of the timeline screen shot](https://user-images.githubusercontent.com/62734881/182689626-8b3f39d1-bbe5-4dbc-bf9b-d160845cd3f6.png)

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by jlinde1** [comment]
Okay, you can close this out, but I don't know what caused it. I noticed another event was being captured the same way as the first, showing up in two different ages, except the offending age was the same one. I deleted that age and readded it, and poof, the issue disappeared. 

Going to let the Dev decide if this needs further investigation, in case someone else gets it. But I can understand if they want to close it.

**Comment by iamromeo** [comment]
The War of Succession
11500  11750

and 

The Age After the Fall

Used to overlap  :) I saw it yesterday before heading to bed - it seems like you fixed it now

**Comment by AlfredAgear** [comment]
Whenever i make an event it is displayed on the correct era, but also appears as a duplicate in a prehistoric era.
There is only one timeline. The events duplicate inside the same timeline. If i try to delete the extra event in the prehistory then it deletes the original as well. This happens pretty much every time.

![timelineglitch1](https://user-images.githubusercontent.com/111672335/185775291-10634f71-eb07-4237-9c0b-a69ce8d38602.PNG)
![timelineglitch2](https://user-images.githubusercontent.com/111672335/185775296-803a8b1e-577e-46ec-994d-8a768fd003dc.PNG)

The on under "Man's Lift" is the correct version.

**Comment by Kordishal** [comment]
What are the UTD dates of the Prehistory?

Event duplication happens when the range of the event reaches into more than one Era. So they are displayed in both of them.

**Comment by AlfredAgear** [comment]
I followed the tutorial video. These are the settings for the prehistoric era:
 
![timelineglitch3](https://user-images.githubusercontent.com/111672335/185802265-587a864b-146f-418d-9468-00fac9366515.PNG)
![timelineglitch4](https://user-images.githubusercontent.com/111672335/185802335-3764f374-03d3-4a6a-aff7-e53b017b91f4.PNG)

**Comment by AlfredAgear** [comment]
And here are the settings for the current era

![timelineglitch5](https://user-images.githubusercontent.com/111672335/185802442-112e3305-b840-4b86-b600-99dbb80a5a09.PNG)
![timelineglitch6](https://user-images.githubusercontent.com/111672335/185802449-a0f6a99f-3a97-43b8-a490-84a8dc91a48f.PNG)

**Comment by Kordishal** [comment]
The prehistory era goes from negative infinite to positive 6 billion. The current Era goes 10500 to positive infinite. So the prehistory overlaps for about six billion years. If you set the end date of prehistory to 10499 then it will no longer overlap and not duplicate

**Comment by AlfredAgear** [comment]
nope. i even removed the inverted date and its still there. i should mention that i have two other eras in-between these two but the glitch only happens on the prehistory one

**Comment by Kordishal** [comment]
You changed the end date of the Prehistory from 6'000'000'000 to 10'499 and that didn't help? What are the UTD dates of the event?

**Comment by AlfredAgear** [comment]
![timelineglitch9](https://user-images.githubusercontent.com/111672335/186475643-e1f6d31a-eb44-4ffe-95b3-debaaa10b525.PNG)
![timelineglitch8](https://user-images.githubusercontent.com/111672335/186475647-b7e5184c-ba5f-4bf4-a31a-60c4e95f4096.PNG)
![timelineglitch7](https://user-images.githubusercontent.com/111672335/186475649-dd3df1ff-6b74-4bb4-843f-613b7eebef40.PNG)

**Comment by AlfredAgear** [comment]
nope. i tried that before, but did it again to see if maybe i was mistaken. still nothing.

**Comment by AlfredAgear** [comment]
![timelineglitch10](https://user-images.githubusercontent.com/111672335/186476168-3f4dbc7b-ccda-4e8d-bd9c-751327807ddd.PNG)

**Comment by Kordishal** [comment]
From the information you haven given me so far is all I can see that the prehistory spans the entire history (6 billion years into the future) and this is why the events are duplicating. The last few screenshots don't show anything amiss.

**Comment by AlfredAgear** [comment]
the problem is that the nesting is the only thing that should be under the prehistory. the others are the duplicates. their dates are different because i did the thing you asked:

**Comment by AlfredAgear** [comment]
![timelineglitch11](https://user-images.githubusercontent.com/111672335/186569859-a6260767-5de2-4899-b609-a3d76dc17d32.PNG)

**Comment by Kordishal** [comment]
Can you link your world? Or if everything is private can you make me an editor so I can have a look? I really don't see what is wrong, but I can't make them duplicate on my end with what I see.

My username on WorldAnvil is `SoulLink`.
