### ISSUE TITLE
Unable to delete world

### ISSUE THREAD

**Issue by CuriousGoose1** [worldanvil/worldanvil-bug-tracker#1211]
**World Anvil Username**: thesmuck

**World**: A lasting dream, coming into focus

**Feature**: world deletion

**Describe the Issue**
When attempting to delete a world, after clicking "Ok" on the confirmation pop-up, browser navigates to a 404 page (https://www.worldanvil.com/world/0831c7c0-588e-4e9b-9471-3e9345aa5727/delete). Was able to delete another world I created but not this one. Tried using Chrome and Firefox with same result

**To Reproduce**
1. Navigate to world.
2. Click on Settings
3. Click on Open Tools & Advanced Actions
4. Click on Delete World
5. Click on Delete this World
6. Click OK on confirmation pop-up

**Expected behavior**
Deletion confirmation message.

**Screenshots**

![Screenshot 2022-08-03 142930](https://user-images.githubusercontent.com/110570151/182715867-0343fbbb-b633-4e04-9331-4b66b1796a6c.png)

**Comment by iamromeo** [comment]
Hey @CuriousGoose1 - before you try to delete your world make sure you go under security and you remove 
- Subscribers
- Subscriber groups
- Editors 

Once you do that - you should be able to delete your world :) Please let me know if you are still having trouble having done that.

**Comment by CuriousGoose1** [comment]
Thank you, Dimitris. Unfortunately, I have no subscribers or authors on this world. I went to the security settings to confirm. I still get the same error when trying to delete.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by CuriousGoose1** [comment]
Follow-up. I found some auto added subscriber groups and was able to delete 3/4 but one goes to the 404 page when I try to delete. Still unable to delete the world.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by iamromeo** [comment]
@CuriousGoose1 I will need to investigate your account for this can you please 
email me at dimitris@worldanvil.com 
with 
- your username 
- your password (please change it to a temporary one before sending it) 
- the world you are trying to delete

**Comment by Kordishal** [comment]
You also need to expel any RPG characters, delete campaigns and should delete any manuscripts associated with the world.

**Comment by iamromeo** [comment]
CLosing due to no response.
