### ISSUE TITLE
please include the F.A.S.E.R.IP

### ISSUE THREAD

**Issue by tornado-thomas** [worldanvil/worldanvil-bug-tracker#1213]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**faserip (RPG SYSTEM)**:
**faserip** (Name under which it should be listed on World Anvil):
**World Anvil Username**:

**Website**:

**Logo Image Link**:

**Logo Usage Terms (URL)**:
![download](https://user-images.githubusercontent.com/93082542/182976831-ea4e34f2-a195-4c6b-86a8-56f738f0ff91.jpg)

**Comment by iamromeo** [comment]
Can you please give me your WA username ?

**Comment by iamromeo** [comment]
The game was added to the list

**Comment by tornado-thomas** [comment]
It's t-birdy.

**Comment by iamromeo** [comment]
I have added the game to the list and I will not remove it - but you need to be a Grandmaster to make a request.
