### ISSUE TITLE
Unable to Create Plot

### ISSUE THREAD

**Issue by Haydenschmitt** [worldanvil/worldanvil-bug-tracker#1214]
**World Anvil Username**: Pileofschmitt13

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**:  Plot tab

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Unable to access plot tab in story teller screen. "HTTP ERROR 500"

**To Reproduce**
1. Go to 'Story teller screen'
2. Click on 'Plot'
3. See error HTTP ERROR 500

**Expected behavior**
Open plot page in order to create new plot

**Screenshots**
![image](https://user-images.githubusercontent.com/110042713/182994025-ac5834fb-484b-4b58-91b1-303ebfe64382.png)
![image](https://user-images.githubusercontent.com/110042713/182994177-492f1019-939d-44af-9767-bbb900c10c9c.png)
![image](https://user-images.githubusercontent.com/110042713/182994080-840d708f-6a16-4d62-ab5f-736962318748.png)

**Comment by iamromeo** [comment]
Hey there @Haydenschmitt  that means that you have created a logical loop in your plots. 
In other words one or more of your plots have children that are also their parents. 
Going through your plots via the Articles menu and fixing that parent/child relationship will fix that for you :)
