### ISSUE TITLE
Browser spell check not working in manuscript writer

### ISSUE THREAD

**Issue by istaerlus** [worldanvil/worldanvil-bug-tracker#1215]
**World Anvil Username**: Armundy

**World / Campaign / RPG Character / Manuscript Title**: World: Magic Space, Manuscript: Arrival in a New World

**Feature**: Interaction with browser spell check

**Related URLS** (To public & visible pages add screenshots otherwise): https://photos.app.goo.gl/Ak8D2STTYLENqoyaA

**Describe the Issue**
Misspelled words are not being underlined in red in the manuscript editor. In other parts of world anvil the browser spell check does work as expected, such as in the article editor and comment sections, so the problem is just localized to the manuscripts. 

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Hello there @istaerlus that is indeed true but it is not a bug, some browsers do not recognise advanced editors. 
You can always use ProWritingAid or Grammarly (both free) if you wish that do so.

**Comment by iamromeo** [comment]
After further investigation I have found out there is a way to activate the browser spell checker - I will be investigating the viability of this and we will be implementing if stable.

**Comment by istaerlus** [comment]
Thank you so much. Whatever you did fixed it and the spell checker is
working in manuscripts now. Thanks again :D
