### ISSUE TITLE
text formatting not working

### ISSUE THREAD

**Issue by super-jumbo** [worldanvil/worldanvil-bug-tracker#1217]
**superjumbo**:

**valouria**:

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
when i try to apply formatting to text, such as bold or italics, it straight-up doesn't work. i apply the effect, hit save, then preview the page, and it just isn't there. it was working at first, but then it just stopped. additionally, when i go back to the edit page, all the changes i had made disappear.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Hi, this is an issue with the save function. The content of the article is only saved if you hit any keyboard key. Then there is also no need to hit the save button.
