### ISSUE TITLE
Creating inaccessible articles

### ISSUE THREAD

**Issue by M4Gn3t1Z3R** [worldanvil/worldanvil-bug-tracker#1218]
**World Anvil Username**: M4Gn3t1Z3R

**World / Campaign / RPG Character / Manuscript Title**: Athena / Ariana die Göttliche / Related Prosa

**Feature**: Create and link

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/world/person/824afd8d-0f74-4a67-98b6-d54e2e7151ab/edit#

**Describe the Issue**
When you click on the "create new article and link it" button above some fields with the middle mouse button (to open a new tab), you create an article with an empty title, that cannot be found in the article explorer and cannot be navigated to.

**To Reproduce**
1. Go to any article template that allows you to use the button as seen in the first screenshot
2. Click on the button with you middle mouse button (or while holding down CTRL)
3. Scroll back to where you were with the new tab or refresh the old tab
4. Now you can see a linked article with an empty title that cannot be clicked on. (as in the second screenshot) 
- You can still remove the linkage of the empty article, but there is no way to get to the article

**Expected behavior**
I would either expect a new tab, with the desired article template, to open up and allow immediate editing of it, or that I somehow have the ability to edit the newly created article when created as described above.

I have multiple of these articles and I don't know how to delete them, as they are not shown in the article explorer. I would like either a button that automatically deletes all titleless articles or a way to access them and manually delete them.

**Screenshots**

![image](https://user-images.githubusercontent.com/89660290/183607242-86ce08d6-9068-460b-b4d6-1d774bbcc69c.png)

![image](https://user-images.githubusercontent.com/89660290/183606321-9766c86d-8570-4e0f-9e1d-9de79ade7370.png)

**Comment by M4Gn3t1Z3R** [comment]
I just found, that I can also sort by article template, so I don't really need a button to remove untitled articles.
Behaviour is still unpleasant, so it should probably still be fixed.

**Comment by Kordishal** [comment]
You can also filter articles by uncategorized in the Articles menu where you will find these.

It is not intended for you to open this link in a new tab. If you click it with the left mouse button you can set a title and then go and edit it. It is possible that something like this is planned with a future update.
