### ISSUE TITLE
Chronicles are missing the edit button on the homepage

### ISSUE THREAD

**Issue by MJHeijster** [worldanvil/worldanvil-bug-tracker#1219]
**World Anvil Username**:
MoonRaven, hi, it's me again
**World / Campaign / RPG Character / Manuscript Title**:
https://www.worldanvil.com/w/paldurog
**Feature**: 
Homepage
**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/paldurog
**Describe the Issue**
When logged in, I have a pencil icon next to every item in articles, timelines, etc., except the chronicles in the timelines.

**To Reproduce**
Create a chronicle
Go to the homepage when logged in
???
No pencil next to the chronicle

**Expected behavior**
A nice pencil next to the chronicle. I know it will probably redirect to the same page, but it's a visual consistency.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/246678/183772506-c8612f4e-54ba-452a-8795-dac3a23de2f6.png)

**Comment by iamromeo** [comment]
Considering that the view and the edit of a chronicle is one and the same this is not a bug.
