### ISSUE TITLE
Changes not saving

### ISSUE THREAD

**Issue by GamezGm** [worldanvil/worldanvil-bug-tracker#122]
When using Grammarly as an editor and making changes to an article, the changes, although stated as saved, are not saved. This issue also arises when not using Grammarly in limited cases.

I have screen recorded the error and uploaded the video privately so those with this only can see it (this link has only be shared within this ticket) https://youtu.be/A9pjeXPXMaw

**Comment by Kordishal** [comment]
Changes created with just mouse clicks are not registered by the auto-save. And the save button just triggers the auto-save

So after inserting all the Grammarly changes simply add and remove a space somewhere in the article.

**Comment by GamezGm** [comment]
Thank you, @iamromeo, for your assistance. I am conscious others may have the same question; it might be worth a video.
