### ISSUE TITLE
Full Screen Map Hover Description

### ISSUE THREAD

**Issue by Sebastianos-Ionnides** [worldanvil/worldanvil-bug-tracker#1220]
**World Anvil Username**:
Aelstyn
**World / Campaign / RPG Character / Manuscript Title**:
Cimmerian Shade
**Feature**: 
Maps
**Related URLS** (To public & visible pages add screenshots otherwise):
Works (scroll to bottom): https://www.worldanvil.com/w/cimmerian-shade/c/empires2C-kingdoms-and-people-category
Doesnt work: https://www.worldanvil.com/w/cimmerian-shade/map/4c1043ff-7b3d-4585-a872-1e384b3272d1
**Describe the Issue**
When I hover over a custom icon in my map interface I see the description tag, when the map is imbedded in a category or article, when I hover over a custom icon it works. 

however when the map is full screen it doesnt show the hover over. This is problematic because its the ONLY way a tag exists for a custom icon/pin

it would be nice if you could put some text that is always there as well but I realize thats more a feature request. 

**To Reproduce**
setup a custom pin/icon and ensure it has a description. goto a full map and the hover over doesnt pop. it does pop when its an imbedded link 

**Expected behavior**
I expect the description for a custom icon/pin to be seen when you have a mouse hover over. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
this one works: from map interface. shows hover properly
![image](https://user-images.githubusercontent.com/94059525/183793078-28b464cf-ee8a-4375-88e9-d2ee5c1dd008.png)
This also works: this is on the front side of the house and shows properly
![image](https://user-images.githubusercontent.com/94059525/183793311-ff294876-4b2d-4380-a910-fc615bf4ce38.png)
Doesnt work: You cant see my mouse over on this, gonna have to trust me, but the URL is there so you can play with it
![image](https://user-images.githubusercontent.com/94059525/183793411-387bdb31-d2cd-4c60-be9c-5bcd04246914.png)

thank you

**Comment by Sebastianos-Ionnides** [comment]
also looking at it a bit more, seems specifically linked to "map links", I interconnect lots of maps together so I leverage the "pin direct link to map" often. The links to articles seems to show a description on a hover over.,

**Comment by Kordishal** [comment]
That is working as intended I believe. The direct link is instead of a popup.

**Comment by Sebastianos-Ionnides** [comment]
it doesnt work, is it works as intended? Ok I'll put in a feature request then? because not having the tooltip on hover over and having no label for a custom pin makes the pin almost worthless in full screen. 

its a bad user experience.
