### ISSUE TITLE
Unable to Edit Sheet Assigned to Campaign

### ISSUE THREAD

**Issue by tlees** [worldanvil/worldanvil-bug-tracker#1222]
**World Anvil Username**: stormtroll

**World / Campaign / RPG Character / Manuscript Title**: Terranon / Elementals and Engines / Dieter Jaeger
**Feature**: Edit Character Sheet

**Related URLS** (To public & visible pages add screenshots otherwise):

https://www.worldanvil.com/heroes/campaign/a0a624de-120c-4c3c-b757-17e915605a1a/dashboard Campaign
https://www.worldanvil.com/hero/c8f149b7-eec2-41be-8d52-8ff61620a9ec Hero URL
https://www.worldanvil.com/heroes/sheet/1082161/edit Sheet in question

**Describe the Issue**
Clicking Edit Sheet on a character that's been assigned to the campaign returns a 404.

**To Reproduce**
1. Create a character
2. Create a character sheet as a stat block
3. Assign the sheet to the character
4. Assign the character to a campaign
5. From the DM account, click edit sheet on the character that's assigned to the campaign
6. Get 404.

**Expected behavior**
As DM, I should be able to edit my player's character sheet. I see the edit sheet button, but the sheet returns a 404 error.

**Screenshots**
![image](https://user-images.githubusercontent.com/338971/183916504-970624bd-4e83-4597-88db-087e13a86b50.png)

I am also unable to edit it under the character manager using this link:
![image](https://user-images.githubusercontent.com/338971/183921027-7da4958e-8532-4f81-b7fe-e608710f3966.png)

**Comment by Kordishal** [comment]
In order to be able to edit the sheets of players as a GM you need to follow these steps:

https://www.worldanvil.com/w/creation/a/invite-characters-article

They cannot be edited by default. Though I suppose the button should be removed if that is the case.

**Comment by tlees** [comment]
It looks like the issue is that the statblock for the sheet is not assigned to my world.  Perhaps it was because the character was attached before the sheet was attached?  Creating a duplicate of the sheet in my world and then assigning it to the player seems to fix the issue.
