### ISSUE TITLE
Dashboard Youtube Video Won't Go Away

### ISSUE THREAD

**Issue by talross** [worldanvil/worldanvil-bug-tracker#1223]
**World Anvil Username**: Talross

**World / Campaign / RPG Character / Manuscript Title**: Danse du Vide

**Feature**: Youtube Video Guide

**Related URLS** (To public & visible pages add screenshots otherwise): Dashboard (see screenshots)

**Describe the Issue**
The "World Anvil in Five Minutes" Youtube video will not go away. Below the video, it says "This video will disappear once you create your first article but you can always find it under the [HELP] section ;)" I have made 3 articles and published 2 of them. I tried logging out and back in, and refreshing with Shift+F5. I spoke with the Livechat help, and they directed me here. 
I am on Windows 10, using the latest Google Chrome.

**To Reproduce**
1. Go to Dashboard
2. See error

**Expected behavior**
I expect the Youtube video to go away after making an article. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

![temp1](https://user-images.githubusercontent.com/10953411/183960730-80fe4314-3031-49a2-aba7-9c5db34ebd99.png)
![temp2](https://user-images.githubusercontent.com/10953411/183959538-d52ecc65-927b-4263-876e-6f2ab8135005.png)

**Comment by iamromeo** [comment]
Hey there @talross! 
This is not a bug. The text is indeed that it will disappear after you create your first aritcle but it takes into consideration also the 3 automatically created articles (grand total of 4) which have been deleted or never created on this world. 

Going over 4 articles will remove the video. The text has been altered to reflect this and will be deployed later today :)
