### ISSUE TITLE
Articles sometimes get created into the wrong world

### ISSUE THREAD

**Issue by mwmontfort** [worldanvil/worldanvil-bug-tracker#1224]
**World Anvil Username**: mwmontfort

**World / Campaign / RPG Character / Manuscript Title**: Anthalam

**Feature**: Article Creation

**Related URLS** (To public & visible pages add screenshots otherwise): n/a

**Describe the Issue**
I have multiple worlds, but most of them are more archived and less used. I only work in one world right now, which is Anthalam. Sometimes, when I create a new article, it randomly creates it in a different world (Tenah) rather than in Anthalam. This has happened several times now and it makes linking the articles very difficult. Sometimes I can re-create an article and it will be put in the correct world and sometimes it will not. 

**To Reproduce**
1. Go to Anthalam>The World> Creatures> Divine Creatures> God
2. Edit the article. You will see it is in Tenah rather than Anthalam.
3. Delete the article and recreate it.
4. See that it is still in Tenah rather than Anthalam.

**Expected behavior**
A recreated article will still sometimes appear within Tenah and sometimes not.

**Comment by Kordishal** [comment]
Hi, the most likely cause for this is that you do switch activation between worlds and then still have the other one active when you create an article. The create article endpoint adds the article to the world that is currently active.

Otherwise if you are sure that you have the correct world active then I am unable to reproduce your issue.

**Comment by iamromeo** [comment]
Just to clarify you should not have more than one tab open at any given time - you can do it at your own risk - but if you do you most certainly cannot have multiple worlds active at the same time
