### ISSUE TITLE
Privacy Map Bug

### ISSUE THREAD

**Issue by playwars536** [worldanvil/worldanvil-bug-tracker#1225]
**World Anvil Username**: Playwars

**World / Campaign / RPG Character / Manuscript Title**: The Eternal Seeker Saga

**Feature**: Map Privacy

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/the-empire-of-mara-the-forbidden/map/09ef3732-2bf7-42a5-b9ba-fe5d090dc213

**Describe the Issue**
Essentially, when a map is set to public, if any groups are listed in the 'subscriber group' section, the map is secretely forced into private, and people not part of those groups cannot see it.

**To Reproduce**
1. Create a map.
2. Add a subscriber group authorized to see it while it is private.
3. Switch to public.
4. People outside of authors/that subscriber group cannot access the map despite it being set to public.

**Expected behavior**
I expected the option of putting the map on public to put it on public, regardless of if there are authorized subscriber groups or not, like it does for markers, marker groups ,ect.

**Screenshots**
N/A

**Comment by Kordishal** [comment]
Hi, I cannot make this happen with the steps you describe. Is your world private or public? If the world is private then the map is not public. Adding a subscriber group to the private map and then making it public does not prevent people from seeing it on my end.

**Comment by iamromeo** [comment]
Closed due to no response
