### ISSUE TITLE
Visibility Toggle not working on linked articles

### ISSUE THREAD

**Issue by gluengenKmart** [worldanvil/worldanvil-bug-tracker#1227]
**World Anvil Username**: glenluengen

**World / Campaign / RPG Character / Manuscript Title**:  Elemental Archipelago Campaign

**Feature**: Visibility Toggle

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/elemental-archipelago-glenluengen/map/721256b5-1680-497c-86b2-eb99930887f8
https://www.worldanvil.com/w/elemental-archipelago-glenluengen/a/frozen-gateway-settlement

**Describe the Issue**
I have a section of text hidden using the visibility toggle on the article that is hidden when you access the article but when you click on the linked article from the map marker the hidden text is shown. 

**To Reproduce**
1. Go to https://www.worldanvil.com/w/elemental-archipelago-glenluengen/map/721256b5-1680-497c-86b2-eb99930887f8
2. Click on map marker 
3. See Text Section Called The Betrayal
4. Click on Read full Article
5. See that the Section called The Betrayal is hidden

**Expected behavior**
Sections that have visibilty toggle set should be hidden in the linked article

**Screenshots**
<img width="1503" alt="Screen Shot 2022-08-14 at 1 06 16 PM" src="https://user-images.githubusercontent.com/87049474/184553360-0e8467e2-c1e7-4510-9c72-bce3baae14ad.png">
<img width="1259" alt="Screen Shot 2022-08-14 at 1 05 55 PM" src="https://user-images.githubusercontent.com/87049474/184553356-e7d176b0-4f1e-46d5-a60f-a3cdbc37ab78.png">

**Comment by Kordishal** [comment]
This is a known limitation and not a bug. You can move the section into another part of the article to avoid this issue.
