### ISSUE TITLE
Mythras default statblock style issues

### ISSUE THREAD

**Issue by Frawak** [worldanvil/worldanvil-bug-tracker#1228]
**World Anvil Username**: Frawak

**World / Campaign / RPG Character / Manuscript Title**: -

**Feature**: Default statblock layout for Mythras system

**Related URLS** (To public & visible pages add screenshots otherwise): [Mythras Example Statblock](https://www.worldanvil.com/sheet/1088129/view)

**Describe the Issue**
There are two issues with the styling of the default statblock provided by World Anvil:
1. The characteristics and attributes are both styled rigidly horizontally (in viewing as well as editing mode). Firstly, this is not optimal for smaller windows where this leads to an overflow (see screenshot), secondly, this overflow is not scrollable (you cannot scroll to the right to see the respective values). There are mulitple possible solutions for this but I would prefer aligning them vertically like the skills, even more preferably with a second input  field like the skills. But in general, such horizontal overflows should be scrollable when they occur, or better, styled to wrap. 
2. The text fields for multiple lines like "Description" do not fit the content when viewing the statblock (see link and screenshot). It even flows under the next category (see link).

**To Reproduce**
1. Create a character or world with "Mythras" as the RPG system.
2. Go to Statblocks and create a new sheet with the "Mythras Character Sheet (Mythras)" template
3. Enter a long text in "Description"
4. Make the window smaller in width (e.g. just on a half of a screen; now you already see the first issue)
5. Click on "View Sheet"

**Expected behavior**

**Screenshots**
![WorldAnvil_Frawak_BugReport_01_MythrasStatSheet](https://user-images.githubusercontent.com/31745945/184554070-bef1af03-2efe-401b-9a80-be7a3b04173d.PNG)

Best regards
Frawak

**Comment by Kordishal** [comment]
Hi, statblock templates are created by community members and not the World Anvil team. This means that either track down the creator and ask them to fix it, or fix it yourself which needs a Grandmaster subscription.

Though it appears that the creator of this template is no longer a subscriber on World Anvil so they would not be able to fix it at the moment.

**Comment by Frawak** [comment]
Thanks for the quick reply.
If I recall correctly, in one of the tutorial videos it was mentioned that if one does not find a RPG system, one could make a feature request to get a base statblock for it but if you want to style it to your liking you need the Grandmaster subscription. 
But if I understand you correctly, one needs the Grandmaster subscription to begin with, do I not?

**Comment by Kordishal** [comment]
Yes. Requesting a system now requires a GM subscription as well, as there are already a lot of systems present. And there are no base statblocks created by the team anymore.
