### ISSUE TITLE
CSS Before/After elements are impossible due to quote elements being escaped when delivered to the browser

### ISSUE THREAD

**Issue by Veil** [worldanvil/worldanvil-bug-tracker#123]
**World Anvil Username**: Stakashadow

**World / Campaign / RPG Character / Manuscript Title**: Varsachia

**Feature**:  CSS Styling

**Related URLS** (To public & visible pages add screenshots otherwise): N/A

**Describe the Issue**
The CSS pseudo element stylers ::after and ::before currently can't be used correctly due to the fact that both ' and " are escaped using html escape tags when delivered to the page (&quot; and &#039; respectively). This doesn't just affect these elements of CSS, but it's the most infuriating instance of this limitation.

**To Reproduce**
1. Go to World Settings > Configuration > Styling
2. Modify your CSS to include any ::before or ::after pseudo element with a "content" attribute
3. Hit save
4. View any page which would display this before element
5. Observe the before element isn't shown
6. Inspect the CSS delivered to the page
7. Observe that the content attribute has escaped quote characters

**Expected behavior**
Quote characters are not escaped when delivering CSS, enabling ::before and ::after elements to be used correctly within CSS.

**Screenshots**
![image](https://user-images.githubusercontent.com/1429745/113486848-a5178580-94ac-11eb-8453-7b4a3fd69dc2.png)

**Comment by Veil** [comment]
I will say, after reporting this, a workaround for this issue at the moment is to set the value to "no-open-quote" and "no-close-quote" for ::before and ::after respectively. I'll still say that reall this would support the usual standard of empty (' ') content or at least make this work around more widely known.

**Comment by Kordishal** [comment]
Quotes are removed by the security filter. It is simply not possible to use any CSS that absolutely requires quotes.

Empty content can also be simulated by using `url();` in the content field.

**Comment by Veil** [comment]
That's a shame, is there no way the security filter can't be updated to allow quotes in CSS? I understand the need to escape them in most cases, but surely if the site offers CSS then it should try to offer all of the directives available?
