### ISSUE TITLE
System Request: Guild Chronicles

### ISSUE THREAD

**Issue by MGHAspireAndrew** [worldanvil/worldanvil-bug-tracker#1230]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name (RPG SYSTEM)**: Guild Chronicles Storytelling System
**List Name** (Name under which it should be listed on World Anvil): Guild Chronicles
**World Anvil Username**: GuildChronicler

**Website**: https://guildchronicles.com/guild-chronicles-storytelling-system/

**Logo Image Link**:
![Cropped Guild Chronicles Hero](https://user-images.githubusercontent.com/78936810/184641276-931eaa24-eb26-4542-a994-ce8f5adf20ac.png)

**Logo Usage Terms (URL)**: Do not alter (apart from scaling as needed) or use outside of World Anvil without explicit written permission by Andrew Harris Schramme (guildchronicles@gmail.com).  For questions and concerns please contact Andrew Harris Schramme (guildchronicles@gmail.com).

**Comment by iamromeo** [comment]
I am sorry but this is not a logo and there are specific sizes required for it. (check other systems) 
Also the Logo and any other design is implemented only with systems with a full array of public sheets. 

The game system has been added to the list

**Comment by MGHAspireAndrew** [comment]
No worries whatsoever! Am artist is working on a true logo now but I
figured I’d send along something in the meantime, lol. Many thanks!
