### ISSUE TITLE
Plot Articles can not be added to white boards

### ISSUE THREAD

**Issue by Sleeclow** [worldanvil/worldanvil-bug-tracker#1231]
**World Anvil Username**: Sleeclow

**World / Campaign / RPG Character / Manuscript Title**: 

**Feature**: White Board

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue** An article that is a "Plot" category article, can not be added to white boards, they simply don't show up when you search for them in the green + menu on the whiteboards.
A clear and concise description of what the issue is.

**To Reproduce**

Make a plot article, try to find it on the whiteboard to add it to the whiteboard.
**Expected behavior**
to be able to add my plot articles to my whiteboard.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Duranzno** [comment]
We have implemented a fix for this. Through our tests it seems to be working please check
