### ISSUE TITLE
Cannot reposition markers from main map in Edit mode

### ISSUE THREAD

**Issue by wlievens** [worldanvil/worldanvil-bug-tracker#1233]
**World Anvil Username**: wlievens

**World / Campaign / RPG Character / Manuscript Title**: Avendel

**Feature**: Maps

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/world/map/a38ab9ee-62c1-4394-9ba2-5a0b32e73342/edit

**Describe the Issue**
On the map in Edit mode, I cannot drag & drop marker pins to reposition them. My only recourse is selecting a marker, going to advanced mode, reposition the single marker there, and saving it. This flow is inefficient when repositioning a few dozen markers, and I'm still expanding my map image canvas sometimes.

**To Reproduce**
1. Go to the maps list and click to edit a map
2. Try to drag a map marker
3. Instead, the whole map pans as if I dragged on the background

**Expected behavior**
Dragging a marker pin, as described in the help text below the map: _Drag your markers and labels around to reposition them_

**Comment by wlievens** [comment]
Note that I can do the following
- Drag the position of the red pin which indicates where a new Marker would come
- Move individual markers on their Advanced Edit page
- When in Presentation mode, I can right-click to quickly create a new pin.

I'm a free user currently.

**Comment by iamromeo** [comment]
Hey @wlievens , 
This is not a bug this is how the feature currently works and a limitation on any tier under GM

**Comment by wlievens** [comment]
Ah, on the help chat I was told to make a ticket because this was supposed to work for free users regardless.

I'm considering subscribing anyway for other features. Thanks for the info.
