### ISSUE TITLE
Create Content Tree comes up blank with no clickable options

### ISSUE THREAD

**Issue by sethkay117** [worldanvil/worldanvil-bug-tracker#1235]
**World Anvil Username**:
seth.kay
**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 
Create content tree
**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/world/orgchart/new
**Describe the Issue**
A clear and concise description of what the issue is.

When I try to create a content tree, I am shown a broken page where it says "create content tree" but there are no actual options or fields to fill out. It's just blank.

**To Reproduce**

**Expected behavior**

I wanted to be able to make various things such as family trees.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

<img width="960" alt="Picture of problem WorldAnvil" src="https://user-images.githubusercontent.com/111540790/185505008-a6f8bfb8-5fbd-4bc5-9f4e-026f84c16b83.png">

**Comment by iamromeo** [comment]
Hey Seth! I am not sure how you managed to access the creation page but this feature is available to Grandmasters and above and you have a Master account from what I can see - this feature is simply not available to your tier.
