### ISSUE TITLE
Can't delete/expel character from world after deleting campaign

### ISSUE THREAD

**Issue by rin506** [worldanvil/worldanvil-bug-tracker#1236]
**World Anvil Username**: Those2Nerds

**World / Campaign / RPG Character / Manuscript Title**: World is Roleplay Radio: Strixhaven; Character I can't delete is Mistake

**Feature**: RPG Characters

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I created a campaign and added two of my characters to it. I later deleted the campaign, but the characters remained in the world. I removed one by editing the character's article, going to Preferences, and using the Delete Article & Character Profile button. The same button on the other character gives a 404 error and doesn't delete anything. The article's delete button is inoperable unless I expel the character and I don't have Player Characters under Advanced Tools.

**To Reproduce**
1. Open the character article's advanced edit page.
2. Go to Preferences and click the Delete Article & Character Profile button.
3. Confirm deletion when prompted.
4. I get WA's 404 page and returning to the article list shows the character article is still there.

**Expected behavior**
Instead of the 404 page, it should bring me back to the articles list with a notice saying the article was successfully deleted. This worked for the other character I deleted using this method, but won't for this one.

**Screenshots**
The delete button I'm trying to use. It worked for one character but won't for this one.
![Delete button](https://user-images.githubusercontent.com/100546092/185714233-b036f05c-a803-44c7-b280-4df59df37ed9.PNG)

When I click and confirm, I get the below 404 page and neither the article nor character are deleted.
![404 page](https://user-images.githubusercontent.com/100546092/185714364-97dea810-9b91-49b2-9a1a-7feb7d575d70.PNG)

**Comment by Kordishal** [comment]
Hi you should now be able to delete this character! Can you try again?

**Comment by rin506** [comment]
Hello,

I still get a 404 error if I try to delete through the Preferences page. I can't delete from the articles list (greyed out) and there is no delete button when editing the character directly.

**Comment by Kordishal** [comment]
have you tried removing the character from the world via the Character Access Rights panel above the delete panel?

**Comment by rin506** [comment]
Character Access Rights only shows me the character is part of the Strixhaven world I'm trying to remove it from, and gives me no option to remove from that world:
![image](https://user-images.githubusercontent.com/100546092/189916232-31d2c5cd-f709-486c-9270-352adba8e941.png)

I'm co-author of this world, not owner, if that makes any difference. From the World dashboard, I've been told I should have an additional option under Advanced Tools to affect characters, and I don't see that either:
![image](https://user-images.githubusercontent.com/100546092/189917276-c2432116-ecf0-4b22-bb90-f239ccbc131f.png)

But I do have the RPG tools enabled:
![image](https://user-images.githubusercontent.com/100546092/189917870-f0f39cc2-7c9a-45d8-903e-e7528107e772.png)

**Comment by Kordishal** [comment]
You being co-owner, might be part of the issue, though I don't understand why you can't unconnect the character from the world. Does the world owner have the Player Character menu item in the sidebar?

**Comment by Kordishal** [comment]
it might not show if there is no campaign, but not sure. RPG Character features would be the only thing I could think of, but those are active so not sure.

I'll close this issue. Should the missing Player Character thing become an issue feel free to make a new issue.
