### ISSUE TITLE
Typo on Author access management screen

### ISSUE THREAD

**Issue by SilkenScarlet** [worldanvil/worldanvil-bug-tracker#1238]
**World Anvil Username**:  SilkenScarlet

**World / Campaign / RPG Character / Manuscript Title**:  All

**Feature**: https://www.worldanvil.com/world/access/author/author/list (Author Management)

**Related URLS** (To public & visible pages add screenshots otherwise): 

**Describe the Issue**
Under the Author access list, the following text appears:
![image](https://user-images.githubusercontent.com/111769980/185960163-e30fc7d8-4100-40f2-bfd1-0c43af1edc92.png)

I believe 'write' should be changed to 'writer'.

**To Reproduce**
See above

**Expected behavior**
See above

**Screenshots**
See above

**Comment by iamromeo** [comment]
Thank you for the heads up
