### ISSUE TITLE
Multiple comma separated article tags are not properly saved when pasted into field

### ISSUE THREAD

**Issue by StefanDamberg** [worldanvil/worldanvil-bug-tracker#124]
**World Anvil Username**: Stiefel

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: TAGS

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When pasting multiple comma separated TAGs into the article field for TAGs the UI is updated indicating that the tags are added - yet then the article is opened again after being saved the just added tags disappeared.

**To Reproduce**
1. Copy any valid TAGs into the clipboard (e.g.: TagA, TagB, TagC)
2. Go to Any article in any editing mode.
3. Click on TAGs and paste tags in. Observe how UI indicated that the tags have been added.
4. Save article.
5. Reopen article.
6. Observe how tags disappeared.

**Expected behavior**
Valid TAGs should always be saved when the article is saved.

**Screenshots**

**Comment by iamromeo** [comment]
This is an issue with the library used, the developer stated it's extremely hard to fix
