### ISSUE TITLE
404 error when I try to create a world

### ISSUE THREAD

**Issue by Glyphie924** [worldanvil/worldanvil-bug-tracker#1241]
**World Anvil Username**
RinT

**World / Campaign / RPG Character / Manuscript Title**:
N/A
**Feature**: 
World Creation
**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I started a new account and tried to create a world, having disabled all RPG related features but enabling worldbuilding. Every time I have tried to create a world I was presented with a 404 error. I have removed all of my plugins, restarted my device, logged in and logged out and tried to delete my account and start a new one (this also presented a 404 error so I could not properly try it).

**To Reproduce**
1. Created a new account
2. Enabled worldbuilding and disabled the newsletter, nsfw content, rpg character and campaign management.
3. Clicked 'create world' and entered 'Seformos' as the title.
4. 404 error

**Expected behavior**
I expected some form of menu but am unfamiliar with what that would look like.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Did you create and delete a world with the same name on the same account name in the past? Then it is prevented from creating a world because of the Copyright lock. Try making a world with a different name.

**Comment by Glyphie924** [comment]
Ah- I didn't realise it would affect deleted worlds. That's worked now. Thanks for your help!
