### ISSUE TITLE
After changing the subscription no access to the world and no possibility to set the world to public as described on the website and support.

### ISSUE THREAD

**Issue by McLegi** [worldanvil/worldanvil-bug-tracker#1242]
**World Anvil Username**: McLegi

**World / Campaign / RPG Character / Manuscript Title**: [Lorenya](https://www.worldanvil.com/w/lorenya-mclegi)

**Feature**: Set World from Private to Public

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/dashboard/

**Describe the Issue**
Some time ago I downgraded my membership plan. Since then, I can no longer access my world because I apparently no longer have the necessary rights with the reduced plan. I think it's because I have too many co-authors. However, I can't change that until I get into the edit mode of the world.

When I try to go into edit mode I get the following error message: 

"Naughty naughty little hobbitses....
...If you wish to edit this world,
**you can renew your membership or make your world public. Head to the Dashboard to make the world public".**

However, when I go to my dashboard I see my world but no option to change the world to public. I only see the buttons "View World" and "Switch to this World". See screenshot

I have already written to the support and they said that it is a bug because there should be a button to set the world to public. 

**To Reproduce**
1. Go to your subscription settings. Downgrade the subscription from a monthly Grandmaster subscription to a Master subscription with a three-month payment term.
2. Go to your Dashboard, to see all your worlds (one world in my case)
3. Try to switch wordl von Privat to Public
4. There is no button/option to set the world to public

**Expected behavior**
An extra button "Switch to Public" or a dialogue window that opens when you click on the lock symbol. But for me it is also ok if my world is manually set to public. As long as I get access to the world again

**Screenshots**
![Screenshot 2022-08-26 121153](https://user-images.githubusercontent.com/48140319/186881972-89e2b3c1-a593-4ca8-b1a5-8f59a775f491.png)

**Comment by iamromeo** [comment]
Hey there @McLegi it's not actually a bug because you do nto want to world to go public - as far as I understand you want access to it. 

I can remove all co-authors and subscribers from the world if you wish me to but I will need your approval to do that. 
Am I ok to proceed?

**Comment by McLegi** [comment]
Yes thats fine for me. Please remove all co-authors. Thanks for your help

**Comment by iamromeo** [comment]
Hey @McLegi you should be all set my good sir, let me know if this you are sitll having trouble
