### ISSUE TITLE
"Display this map on the World's homepage" keeps turning on

### ISSUE THREAD

**Issue by Zerahar** [worldanvil/worldanvil-bug-tracker#1244]
**World Anvil Username**: Zerahar

**World / Campaign / RPG Character / Manuscript Title**: Onigma V

**Feature**: Maps

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I try to set my maps to not display on homepage. The page says that everything is saved, yet the option is back turned on when I check it.

**To Reproduce**
1. Uncheck "Display this map on the World's homepage"
2. Save
3. Setting is still enabled

**Expected behavior**
The setting should stay unchecked and maps hidden from frontpage.

**Comment by Kordishal** [comment]
Hi, I cannot reproduce this with the steps you provided. Can you save any other map settings on that map? Does the issue appear on other maps too? And on a new map?

**Comment by iamromeo** [comment]
Hey @Kordishal , @Zerahar is a Freeman and does not have access to privacy or any kind, hiding maps included. The issue here is that the option is visible to them - will take care of it.
