### ISSUE TITLE
Add Cyberpunk 2020 to RPG System in new Campaigns selector

### ISSUE THREAD

**Issue by cybersmily** [worldanvil/worldanvil-bug-tracker#1246]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name (RPG SYSTEM)**:
**List Name** (Name under which it should be listed on World Anvil):
**World Anvil Username**:

**Website**:

**Logo Image Link**:

**Logo Usage Terms (URL)**:

**Comment by Kordishal** [comment]
![image](https://user-images.githubusercontent.com/14262536/187093294-b34255ec-d75b-4331-94c1-3693588e77b5.png)

Its in the campaign selection too. If you want it in the player section then there needs to be a community player character statblock template. I see that you made two characters with a template, if you talk to Dimitris you can get the template shared with the community. After that player RPG Characters can then select cyberpunk 2020 as a system.

**Comment by cybersmily** [comment]
Hi, 

 

I actually found where Cyberpunk 2020 isn’t showing up. When I create an NPC in campaigns:



 

Is this because there isn’t a template for Cyberpunk 2020?

 

Will

 

 

 

From: ***@***.*** ***@***.***> 
Sent: Thursday, September 1, 2022 7:09 PM
To: 'worldanvil/worldanvil-bug-tracker' ***@***.***>; 'worldanvil/worldanvil-bug-tracker' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [worldanvil/worldanvil-bug-tracker] Add Cyberpunk 2020 to RPG System in new Campaigns selector (Issue #1246)

 

Hi, 

 

I didn’t know that it was a combobox. I assume it was a select and scroll down the dropdown. I see that there are 2 lists, one in the top which I assume is popular games(?) and then the mega list at the bottom.

 

Thanks for emailing me about this. Appreciate the help.

 

Will

**Comment by Kordishal** [comment]
Yes, just like with Player Characters, for the NPCs it needs a character sheet available for the system for this to be available.

**Comment by cybersmily** [comment]
Ok, I create a 2020 sheet, still needs some tweaks. But to submit it do I need to create all the types? Display, edit, badge, and tracking?

 

Will

**Comment by Kordishal** [comment]
They are not required, the places where these things are used it will just be empty!
