### ISSUE TITLE
Player's Handbook items not opening

### ISSUE THREAD

**Issue by BillSawyer-Oracle** [worldanvil/worldanvil-bug-tracker#1247]
**World Anvil Username**: BillSawyer

**World / Campaign / RPG Character / Manuscript Title**: Torrul

**Feature**: Player's Handbook

**Related URLS** (To public & visible pages add screenshots otherwise): see screenshot below

**Describe the Issue**
From my dashboard, click on View World. When it opens, click on Player's Handbook. It opens. It presents a "World Codex" at the bottom with the categories I created (See screenshot). When I click on the first category, it accordion opens just fine. None of the other categories will accordion open. If I click the open category page icon, they will open properly.

**To Reproduce**
No error. See the description

**Expected behavior**
Each category should accordion open at does the first open.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/78377981/187097524-cd29c889-8ee0-4345-aeee-229c9c863492.png)

**Comment by Kordishal** [comment]
The articles in those categories are most likely drafts. If that is the case then this is working as intended. Draft articles do not appear here. Or in the category page when you open that.

**Comment by BillSawyer-Oracle** [comment]
Not this problem. All my articles, at least within these categories, were published. I gave up expecting a quick fix, and simply deleted the Player Handbook category. I assigned all of the content into the Campaign. It worked there. There is definitely an issue.

**Comment by Kordishal** [comment]
I see. However, without a way to reproduce the issue the team won't be able to fix it. Feel free to post a comment here should you encounter this issue again.
