### ISSUE TITLE
Map editor cannot be accessed due to error state

### ISSUE THREAD

**Issue by Azerdoze** [worldanvil/worldanvil-bug-tracker#1248]
**World Anvil Username**: _DMrico_

**World / Campaign / RPG Character / Manuscript Title**: _Arthan Uthyl_

**Feature**: _Maps_

**Related URLS**: https://www.worldanvil.com/world/map/8c8e269c-9702-4ae2-b905-c4b1b5c493ef/edit

**Describe the Issue**: _Can't access map editor_
It has been several months since I reported this issue and I have yet to receive a solution. Perhaps I didn't explain it properly the first time, so apologies in advance. It seems I have screwed up my map definitions and now my map editor just takes to an error screen.

I would like to point out that I just want to be able to DELETE the map without going to the map editor (since It automatically takes me to an error page), if possible. If this can be done from your backend, so be it.

**To Reproduce**
1. Go to 'Maps'
2. Click on 'Map of the Human Lands - edit button' 
3. See error

**Expected behavior**
If I screw up a map link, I would expect in the backoffice to be able to remove it without having to opening it.  Just a button with a delete option for each map on the Maps general backoffice would help alot. I'm sure I'm not the first person to have made this rookie mistake.
If there is a workaround this issue, please, would it be possible to give me step-by-step instructions? 

**Screenshots**
![image](https://user-images.githubusercontent.com/19597249/187300905-2c9d6a91-fea2-4438-8541-76efc9ddc054.png)
![image](https://user-images.githubusercontent.com/19597249/187301027-6aa36834-fcdb-4e89-b8b3-9067a943293b.png)

**Comment by Kordishal** [comment]
New report for #1054
