### ISSUE TITLE
editor can not edit my work

### ISSUE THREAD

**Issue by pholland1** [worldanvil/worldanvil-bug-tracker#1249]
**World Anvil Username**:

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):
https://cdn.discordapp.com/attachments/1000642269117943869/1014458497817133118/unknown.png

**Describe the Issue**
I have added a member as a Editor to my project but he canon edit my pages. when he attempts to change the page, he is met with an error message. there error message reads; "This page isn't working, www.worldanvil.com is currently unable to handle this request. HTTP ERROR 500"
https://cdn.discordapp.com/attachments/1000642269117943869/1014458497817133118/unknown.png

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
https://cdn.discordapp.com/attachments/1000642269117943869/1014458497817133118/unknown.png
![unknown4](https://user-images.githubusercontent.com/112729423/188231062-c53e0dc8-26e9-48fe-acc3-ec080311c0a1.png)

**Comment by Kordishal** [comment]
Hi, which links is he attempting to open that lead to this page? And does he have the world activated?
