### ISSUE TITLE
Changing email address

### ISSUE THREAD

**Issue by Loirisoch** [worldanvil/worldanvil-bug-tracker#125]
**World Anvil Username**: Marine Hermitant

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/profile/edit

**Describe the Issue**
When I try to update my email adress linked to my worldanvil account, an error 404 appears.

**To Reproduce**
1. Go to the parameters of the account
2. Change the email adress (+add the password)
3. Click on update
4. error 404

**Comment by iamromeo** [comment]
@Kordishal have you reproduced this bug?

**Comment by Kordishal** [comment]
Ah yeah. It goes 404 when the email address is already in use.
