### ISSUE TITLE
Request New System:  MAGS RPG

### ISSUE THREAD

**Issue by Messer23** [worldanvil/worldanvil-bug-tracker#1251]
[MAGS v3.pdf](https://github.com/worldanvil/worldanvil-bug-tracker/files/9485740/MAGS.v3.pdf)

**Full Name (RPG SYSTEM)**: Mechanics Amalgamated Game System
**List Name** (Name under which it should be listed on World Anvil): MAGS RPG
**World Anvil Username**: Messer23

**Website**: https://www.blogger.com/blog/posts/2894050173011058208?pli=1

**Logo Image Link**:
![MAGSRpgBlueSteelCoverHex](https://user-images.githubusercontent.com/112833328/188339090-9d572ef3-9952-46a8-b756-1f2751185bb0.png)

**Logo Usage Terms (URL)**:

[MAGS Character Sheet TealnSteel.pdf](https://github.com/worldanvil/worldanvil-bug-tracker/files/9485759/MAGS.Character.Sheet.TealnSteel.pdf)

**Comment by iamromeo** [comment]
@Messer23 I am sorry bu there is no WA user under the username **Messer23**
Please let me know what is your correct username so I can check that you are able to submit the system within the next 48 hours
