### ISSUE TITLE
Issue with Whiteboard (seems to be repeat of a 'fixed' issue) with Images/backgrounds not displaying

### ISSUE THREAD

**Issue by badgersoft** [worldanvil/worldanvil-bug-tracker#1253]
**Mark Durban**:

**terra-novus-mark-durban**:

**Whiteboards**: 

**Describe the Issue**
When creating a new Whiteboard and either changing the background or an item background to an Image it does not show.
Have seen previous issues which suggested clearing Cache and Hard F5 refresh but this hasn't resolved.
My account is only 2 weeks old, I am presuming that the old issue would not have been picked up in my browser cache, but tried the above just to make sure.

**To Reproduce**
1. Go to 'whiteboards.'
2. Click on '...Edit/Change Background'
3. Scroll down to 'Set an Image as a background and then select any image (PNG, JPG, GIF etc).'
4. Image doesn't show up, screen goes black.

**Expected behavior**
I would expect the background to be set to the image.

**Screenshots**
![image](https://user-images.githubusercontent.com/24875744/188625370-4b61393c-8ca8-4ae5-ad53-33aff47a2cd5.png)

I am running Windows 10 and seeing same issues on Firefox/Chrome and IE Edge.

Happy to provide any more information, this isn't a critical issue as I presume its local and can live without Whiteboards for now (Am using them for tracking other things without images required and they work very well, just the image issues that I have a problem with currently).

**Comment by Kordishal** [comment]
Potentially related to #1079.

Expands the issue to also not display images in Blocks.

**Comment by iamromeo** [comment]
We are aware of the issue and already working on a fix

**Comment by Duranzno** [comment]
This issue is now fixed and deployed to production
