### ISSUE TITLE
System Request: Pathfinder for Savage Worlds

### ISSUE THREAD

**Issue by Wombees** [worldanvil/worldanvil-bug-tracker#1255]
**Full Name (RPG SYSTEM)**: Pathfinder for Savage Worlds
**List Name**: Pathfinder for Savage Worlds
**World Anvil Username**: Wombie

**Website**: https://peginc.com/savage-settings/savage-pathfinder/

**Comment by Kordishal** [comment]
Does this have a lot of mechanical differences to PF1 / 2? Or is it just PF with different lore? Would it need different statblocks?

**Comment by Wombees** [comment]
Hi, yes - it is an adaptation of PF1 using Savage Worlds as a base. Mechnically it's more similar to Savage Worlds but with some differences to fit the Pathfinder setting.

Character sheet can be found here: [https://peginc.com/store/pathfinder-for-savage-worlds-character-sheet-free-pdf/](url)

**Comment by iamromeo** [comment]
Added -
