### ISSUE TITLE
Hidden session reports can be seen by all players

### ISSUE THREAD

**Issue by 737oli** [worldanvil/worldanvil-bug-tracker#1257]
**World Anvil Username**: 737oli

**World / Campaign / RPG Character / Manuscript Title**:
Waterdeep (campaign/world)

**Feature**: 
Session reports

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/epic/Waterdeep-campaign/report/203e2eec-3491-49aa-945e-3c68ee41a9c7
https://www.worldanvil.com/w/waterdeep-737oli/a/session-33a3A-guess-who-s-back2C-back-again21-report-report?preview=true

**Describe the Issue**
The session reports can be clicked upon and seen by all players in the "/epic/Waterdeep-campaign" url. 
The session reports can only be clicked upon and seen by the correct subscriber group on the "view world" page.

When setting only 1 player as the subscriber group for a session report, only that player can see the session report on the "view world" page. Yet all other players can see the same session report when they navigate to the "/epic/Waterdeep-campaign" url. Therefore 1 of my players read a session report which was  not meant to be read by them.

**To Reproduce**
1. Make a session
2. Make a session report
3. Create a subscriber group with 1 player
4. Set the session report to private
5. Give that subscriber group access to the article
6. Log in with a different player
7. Go to "https://www.worldanvil.com/epic/Waterdeep-campaign"
8. Click on the session and notice that you are able to read the session report
9. Go to the View world page
10. Type in the session report name and notice you can't find it

**Expected behavior**
The subscriber groups given access to the session reports should also be the only ones that are able to read the session report in the "/epic/Waterdeep-campaign". 

**Screenshots**
Given subscriber groups to the session report
![image](https://user-images.githubusercontent.com/66430857/189479014-137c7bd5-7b4e-4065-8fe6-b5832673fae5.png)

Only the correct subscriber group can see the report on the "view world" site
![image](https://user-images.githubusercontent.com/66430857/189479078-f3fe6bb7-9774-4253-80d3-30b0cebb387d.png)

When logging in with a different player that is not in the subscriber group, you can click on read session report
![image](https://user-images.githubusercontent.com/66430857/189479137-e4a475f9-9a35-490c-b154-132b9ae9a671.png)

Reading the article without having permission
![image](https://user-images.githubusercontent.com/66430857/189479247-d095e567-6130-4e6e-ac6f-95f9ed7fb3e1.png)

**Comment by katerinach** [comment]
@737oli We have fixed the issue. Can you confirm that it's fixed for you as well?

**Comment by 737oli** [comment]
Hey, I confirm that the session reports cannot be read anymore by players not in the correct subscriber group yet I find that other reports cannot be read as well anymore on the "epic" page. I checked this with multiple session reports. In the world view everything is still okay!

The Epic page (currently logged in as the female character with white hair, Girlfriend's account)
![image](https://user-images.githubusercontent.com/66430857/191231134-8b92f858-ce5d-42a1-b3e1-d7a264aa1e40.png)

The session report of Session 33A which should be hidden for her (works correctly)
![image](https://user-images.githubusercontent.com/66430857/191231491-64e5dd14-1881-430f-a1d1-890271270882.png)

The session report of Session 34 which should be visible for her (works incorrectly)
![image](https://user-images.githubusercontent.com/66430857/191231608-0b128f0d-dfe0-4135-852f-4c24bcc15100.png)

**Comment by katerinach** [comment]
Will look into it, thanks for the response.

**Comment by katerinach** [comment]
@737oli Is Session Report 34 set to "private" or "public" state? And if it is "private", is the user you are testing from in the subscriber group for this report?

**Comment by 737oli** [comment]
Private and the user is a subscriber in the group. This has been from the start (2 years ago).

**Comment by katerinach** [comment]
@737oli For a private report, a user can access it if they are a player of the campaign and if they're also in the subscribergroup of the specific session report (not just the campaign). Can you confirm if this is the case? We have tighened up the access rights for session reports with this bug fix so it might not work exactly as it did.

**Comment by 737oli** [comment]
To my understanding my players are both. See Screenshots below. Hope this helps. 

[Gamemaster]  Subscriber group "The Party" given to the session report:
![image](https://user-images.githubusercontent.com/66430857/192818990-c064ddf9-0086-467b-97d0-b0b9b1c8615f.png)

[Gamemaster]  All players are in the "The Party" subscriber group:
![image](https://user-images.githubusercontent.com/66430857/192819288-89db939a-b1c7-4e9f-8b61-75fc7709ff71.png)

[PLAYER]  The access button to the specific report:
![image](https://user-images.githubusercontent.com/66430857/192819725-e23c9175-4ea1-41fe-a653-15708c85d1d9.png)

[PLAYER] Unable to gain access to the report:
![image](https://user-images.githubusercontent.com/66430857/192819849-76b02be5-b448-4e97-bc1a-7b72cf4169df.png)

[PLAYER]  Able to gain access to the report in world view: 
![image](https://user-images.githubusercontent.com/66430857/192820168-61983516-9f8b-41d0-8086-b8f00a9c1123.png)

**Comment by katerinach** [comment]
@737oli  Thanks for the feedback. This bug should now be resolved, can you confirm if the issue has been fixed for you as well?

**Comment by 737oli** [comment]
I do confirm! Thank you for the help!
