### ISSUE TITLE
Can't start creating new chronicle

### ISSUE THREAD

**Issue by larsvansche** [worldanvil/worldanvil-bug-tracker#1258]
**World Anvil Username**:

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I recently became a grand master. Chronicles are new to me. I created one, which worked, but when I open it, I can't get past the second step in the wizard (Choose Calendar Template). The dropdown works, and everything seems fine, except that the 'Back' and 'Next' buttons don't do anything. Hovering over them does change the cursor to a pointer, but clicking them doesn't do anything. 

Additionally, on the first page of the wizard, there is a loading animation that keeps going. I'm not sure if this has anything to do with the aforementioned problem, 

**To Reproduce**
1. Go to 'Timelines & Chronicles'
2. Click on 'Create new chronicle'
3. Give it a title and description and click on 'create chronicle'
4. Enter the chronicles-setup-wizard5. 
5. Click 'next'
6. Optional: select any calendar
7. Click 'next'
8. Nothing happens

**Expected behavior**
I expect to go to the next step in the chronicle-setup-wizard, so I can create my chronicle. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Hello @larsvansche 

Sadly I cannot replicate this 
1. Which browser are you using? 
2. Have you tried using this browser in incognito mode to check if any of your browser plugins interferes?

**Comment by Kordishal** [comment]
Could be related to  #1148. If you use Safari try using a different browser. Firefox or any chromium based browsers like Chrome, Opera or Edge should work!

**Comment by iamromeo** [comment]
No response in 48 hours - Please reply if you have an update
