### ISSUE TITLE
Private chapters in public manuscript can be accessed by any user

### ISSUE THREAD

**Issue by Deleyna** [worldanvil/worldanvil-bug-tracker#1259]
**World Anvil Username**: Deleyna

**World / Campaign / RPG Character / Manuscript Title**: Dominion of Darkness

**Feature**: public/private access to different chapters

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I have the manuscript set to public, but chapters after the first couple are set to private. Anyone can read them, even though there is a lock.

**To Reproduce**
1. Go to Manuscript
2. see the lock
3. click on one of those chapters
4. read chapter (I show 500 views on the entire book...)
5. Leave me a comment telling me how brilliant it is... ok, maybe not that one...

**Expected behavior**
1. Go to Manuscript
2. read the first couple of chapters
3. come to one with a lock
4. get sent to Ko-fi to buy the book
5. Deleyna gets rich... (HA!) Okay, not that one, either...

**Screenshots**
![Screenshot 2022-09-11 011936](https://user-images.githubusercontent.com/4100767/189518286-6c3c286c-25af-4648-b84b-78279aa28391.jpg)
Here in private window is a locked chapter... readable...
![Screenshot 2022-09-11 012042](https://user-images.githubusercontent.com/4100767/189518309-9455f507-b760-489d-af06-991f7b8f7f4a.jpg)

I'm new enough that I figured I just had something set wrong, but RiverFang said they were able to duplicate it...

Thanks for all you do!!!

**Comment by Kordishal** [comment]
I can confirm that I can no longer access the private chapters of Deleyna's manuscript!

**Comment by katerinach** [comment]
Amazing, thanks @Kordishal!

**Comment by Deleyna** [comment]
I can confirm! It is fixed. Thank you so much!
