### ISSUE TITLE
Ampersand end comment on feature suggestion prematurely

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#126]
**World Anvil Username**: SoulLink

**Feature**: Feature Voting

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
The ampersand seems to cut off the comment.

**To Reproduce**
1. Open a suggestion.
2. Write a comment with an ampersand (&).
3. Submit vote.

**Expected behavior**
Post the full comment.

**Screenshots**
![image](https://user-images.githubusercontent.com/14262536/113502827-ec465a80-952e-11eb-8262-0494e98bf427.png)

**Comment by iamromeo** [comment]
That is all me. I do not know what was I thinking and made this request a get. which means that the & makes the rest another variable. Will fix
