### ISSUE TITLE
World Privacy settings

### ISSUE THREAD

**Issue by CrystalGalax** [worldanvil/worldanvil-bug-tracker#1260]
When I created a new world titled Earth I went to settings so I could make it private but it wouldnt let me change the option.

**Comment by Kordishal** [comment]
It works fine on my end. Do you have a subscription to World Anvil?

**Comment by iamromeo** [comment]
@CrystalGalax what is your WA username and do you have a guild membership?

**Comment by iamromeo** [comment]
No response for 2 days
