### ISSUE TITLE
Touch UI issue on article categories

### ISSUE THREAD

**Issue by The-Nusbaum** [worldanvil/worldanvil-bug-tracker#1262]
**World Anvil Username**: CashmereCthulu

**World / Campaign / RPG Character / Manuscript Title**: irrelevant 

**Feature**: article categoried

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When using touch interface (android, chrome) the categories cannot be expanded. The touch event triggers drag, there does not appear to be a long press event.

**To Reproduce**
1. Go to articles > categories on mobile/touch ui
2. Touch category (name,icon,+/-)
4. Note that you cannot expand/close category

**Expected behavior**
Should be able to more, sort, and expand categories

**Screenshots**
![Screenshot_20220911-151515_Chrome](https://user-images.githubusercontent.com/38957691/189545115-8186561b-e0da-4caf-9c93-16e2585f54a1.jpg)

**Proposed Solution**
I suspect that the touch event is attached too high in the DOM, and the touch event is overriding any listeners on the expand/collapse element. Moving the listener to be a sibling of the expand/collapse element would allow for both to function.

**Comment by graylion-wa** [comment]
This would be wonder to have fixed and be able to select the categories on mobile.

**Comment by iamromeo** [comment]
We are aware of the issue on **some Android**  (works correctly on some and all iOS and Windows systems) but we will not be addressing it at this point.
