### ISSUE TITLE
Can't edit player's sheets in my campaign

### ISSUE THREAD

**Issue by Larperlass** [worldanvil/worldanvil-bug-tracker#1264]
**World Anvil Username**: LarperLass

**World / Campaign / RPG Character / Manuscript Title**: Kelidonia/It Started In Heathdale

**Feature**: Editing player's sheets

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When I try to edit my player's sheet, I get a 404 error 

**To Reproduce**
1) Go to Campaign Homepage (It started in Heathdale)
2) Click on Protagonists (PCS)
3) Click on 'Edit Sheet' for Ser Aelred Fireshield

**Expected behavior**
Hoped to be able to go in and edit the character sheet

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Screenshot 2022-09-13 142227](https://user-images.githubusercontent.com/113445667/189912353-71108e07-ce61-4c1e-be7d-dd981feeab21.jpg)

**Comment by Kordishal** [comment]
Hi, this means that the sheet does not have the correct permissions. To get them you have to follow specific steps outlined in the guide below:

https://www.worldanvil.com/w/creation/a/invite-characters-article 

The edit sheet button appears even if you do not have the correct permissions, which is a known issue.
