### ISSUE TITLE
Can't delete world

### ISSUE THREAD

**Issue by huntsfromshadow** [worldanvil/worldanvil-bug-tracker#1267]
**World Anvil Username**: huntsfromshadow

**World / Campaign / RPG Character / Manuscript Title**: Golarion - The Open Road

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/world/bef641b2-816a-41b5-afc9-cc4d9f915515/summary

**Describe the Issue**
Can't delete the world.

**To Reproduce**
Trying to delete the world throws me to a 404.

**Expected behavior**
World should be deleted.

**Comment by Kordishal** [comment]
Hi,

Can you try to first

- expel any RPG characters associated with the world
- delete any campaigns associated with the world
- delete any manuscripts associated with the world
- remove all subscribers, authors and subscriber groups from the world.

After this it should work.

**Comment by huntsfromshadow** [comment]
That fixed it. Once I deleted everything out of the world.
