### ISSUE TITLE
'Campaign' 'Plots'

### ISSUE THREAD

**Issue by afterphil** [worldanvil/worldanvil-bug-tracker#1268]
afterphil

Geladras/ Evil Abounds

Campaign: 'Plots'

Screenshot below

**Describe the Issue**
The 'Campaign' 'Plots' page never loads. The page appears to load while observing the status bar, upon completion I am presented with a blank white page. I have attempted logging out and clearing history/cache/cookies. I have tried on a Windows 10 PC and laptop as well as an iPhone and an iPad. 

**To Reproduce**
1. Go to 'Campaigns'
2. Click on 'Plots'
3. See error

**Expected behavior**
I expect the 'Plots' page to load.

**Screenshots**
![bugreport](https://user-images.githubusercontent.com/105827725/190472751-ad5656e8-0c16-4f95-bfb8-3cf87529b132.png)

**Comment by iamromeo** [comment]
Good day @afterphil that means that you have a plot that is at the same time a child and a parent to one of your plots. You have created a circular reference :) 

Go through your plots and find out which of them creates the infinite loop :) 
Best way to do it is via the **Articles** interface
