### ISSUE TITLE
Cannot delete phantom discussion boards

### ISSUE THREAD

**Issue by lulunacy** [worldanvil/worldanvil-bug-tracker#1270]
**World Anvil Username**: lulunacy

**World / Campaign / RPG Character / Manuscript Title**: of Starfell and Nightfall

**Feature**: Discussion Boards

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I created a discussion board titled Player Characters (category type). I afterward create another category board beneath Player Characters titled Mordecai Meremoth. Within that board, I created a threads type board called Session Reports. ONLY the player characters board appeared and I could not see any of the boards within it anywhere on my side or on the world's side. I deleted Player Characters to see if that would delete the boards within, but it did not and now I have two boards that do not appear and cannot be deleted or accessed. 

**Expected behavior**
Please let me delete all current boards in my world.

**Screenshots**
![image](https://user-images.githubusercontent.com/113865523/190933308-6e439fac-71a3-4628-a4a4-61bf825e9f54.png)

**Comment by iamromeo** [comment]
The chances are that this was a board 3 levels deep that remained once the top-top level board was deleted. 

@katerinach we will need to rewrite the delete function so once someone is deleting a board will **recursively** delete all boards and thread under them - Please add a task for this.

**Comment by iamromeo** [comment]
Closed due to lack of response.
