### ISSUE TITLE
Can’t get past the calendar selection menu in Chronicles

### ISSUE THREAD

**Issue by GalaxyWolf32** [worldanvil/worldanvil-bug-tracker#1271]
World Anvil Username: TheDoctor292

World / Campaign / RPG Character / Manuscript Title: Eceon 

Feature: Chronicles 

Related URLS (To public & visible pages add screenshots otherwise):

Describe the Issue
Whenever I create a chronicle I can’t get past the calendar selection page and the next and back buttons don’t do anything once I get there

To Reproduce
1. Create a new chronicle 
2. Look through the Chronicle creation guide
3. See issue 

Expected behavior
I expect to go through the entire Chronicle creation guide

Screenshots
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
@GalaxyWolf32 which browser / OS are you using

**Comment by GalaxyWolf32** [comment]
I’m using chrome

**Comment by iamromeo** [comment]
@GalaxyWolf32 this might mean there is an issue with your Chrome plugins or that something is forgotten unfilled. 
- can you try to use Incognito mode?

**Comment by GalaxyWolf32** [comment]
I don’t have any plugins and just tried to do it in incognito mode. No luck

**Comment by GalaxyWolf32** [comment]
I just checked and apparently another person is also having this issue

**Comment by iamromeo** [comment]
@GalaxyWolf32 we will do a quick investigation but we cannot reproduce this with the information given above. 
- Can you show us a loom video of this happening? 
- Which browser are you using? 
- Which OS are you using?

**Comment by iamromeo** [comment]
> I just checked and apparently another person is also having this issue

I am sorry but this comment without the person submitting it or knowing their username is not really adding anything to this report.

**Comment by GalaxyWolf32** [comment]
1. https://user-images.githubusercontent.com/89235919/191166581-a4909221-dcb1-4330-a199-e9d41acbe1b8.MOV
2. Mobile (IOS)

**Comment by iamromeo** [comment]
Mobile?! I am sorry but Chronicles were never made for Mobile and they are not supporting it - there is no plan to do so.

**Comment by GalaxyWolf32** [comment]
Ah. Thanks for trying to help anyways.
