### ISSUE TITLE
Category and subcategory order not saving properly/consistently

### ISSUE THREAD

**Issue by schizoidnightmares** [worldanvil/worldanvil-bug-tracker#1274]
**World Anvil Username**: schizoidnightmares

**World / Campaign / RPG Character / Manuscript Title**: The Absurd Realms

**Feature**: Articles -> Categories

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/world/athena/

**Describe the Issue**
The order of categories and subcategories does not save consistently.

**To Reproduce**
For example, say I order the following categories (this effects subcategories too):
- General
- Specific
- Time
If I refresh, it may appear as (or any combination thereof):
- Specific
- General
- Time

**Expected behavior**
Categories and subcategories should save properly in the order they were placed.

**Comment by iamromeo** [comment]
Hello @schizoidnightmares  that probably means that at some point one of your categories lost their weight on the system. If you go through your categories and make sure that those on the level you are trying to order all have a weight and that the weight is not the same for 2 of them you will resolve the issue.
