### ISSUE TITLE
Intercalary Days

### ISSUE THREAD

**Issue by Ddienw** [worldanvil/worldanvil-bug-tracker#1276]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Rheolwr

**World / Campaign / RPG Character / Manuscript Title**: Kaleris

**Feature**: Calendar

**Operating System**: Windows

**Browser**: Chrome

**Device / Device Model**: Laptop, Dell G5

**Describe the Issue**
When trying to establish the last day of a 44-day month as an intercalary day, it does so normally. When trying to establish the last day of a 45-day month as an intercalary day, with all other settings the same, it adds a 46th day afterwards. It appears that an additional day is added for months of more than 45 days as well, though I have not experimented extensively. If the "Offset the beginning of this event one day forward" option is selected, the intercalary event simply vanishes from display.

**To Reproduce**
Exhibited in the screenshots below.

**Expected behavior**
I expect the calendar to not add more days to my months when I choose an existing day to be intercalary. I would _like_ it if I didn't have to specifically change how many days were in my months to account for an intercalary day, and have one created when I create an intercalary event. 

**Screenshots**
![Screenshot (21)](https://user-images.githubusercontent.com/113993474/191257946-461d03ba-1e64-4bc0-833f-d52a41cfc4e0.png)
![Screenshot (23)](https://user-images.githubusercontent.com/113993474/191258036-305b3a2c-8c93-4013-a070-679a11b2ede5.png)
![Screenshot (24)](https://user-images.githubusercontent.com/113993474/191258058-8896f7d0-e824-46d7-9960-aecaca0ed632.png)
![Screenshot (22)](https://user-images.githubusercontent.com/113993474/191258094-afa7e860-1c84-41df-b667-f02a434d50f6.png)
![Screenshot (25)](https://user-images.githubusercontent.com/113993474/191258327-9cebd3ca-4686-4704-a65b-b572e9ed2ec9.png)
![Screenshot (19)](https://user-images.githubusercontent.com/113993474/191258345-354da610-2ec1-4c7c-98db-b4c6cdd51ca5.png)
![Screenshot (20)](https://user-images.githubusercontent.com/113993474/191258360-de1eb064-3b03-4b2f-a338-79cf8eddbc71.png)

**Comment by Kordishal** [comment]
Hi unfortunately the calendar as it is now is currently not in development and the intercalary events were not fully implemented. This will not be addressed as the calendar will be replaced sometime in the future.
