### ISSUE TITLE
Subscribers can no longer view Discussion Boards

### ISSUE THREAD

**Issue by SolarCat02** [worldanvil/worldanvil-bug-tracker#1277]
**World Anvil Username**: SolarCat02

**World / Campaign / RPG Character / Manuscript Title**: Vazdimet and Fillimet

**Feature**: Subscriber Groups

**Operating System**: Android, Windows

**Browser**: Chrome

**Device / Device Model**: Samsung s10e, others

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
My subscribers cannot access things thry should have access to, and I cannot access things I was given subscriber access to. Everyone is logged in, and the permissions are still correct. I have attempted this with discussion boards, articles, and Manuscripts. I don't know what else is impacted. 

**To Reproduce**
1. Go to 'an article with subscriber content, or a manuscript, article, or discussion board locked behind subscriber access'
2. See error - no access to the subscriber content

**Expected behavior**
I should have access to things that I have subscriber access to see, and my subscribers should have access to the things they are allowed to see. But they don't. It acts as if they are not subscribers. 

**Screenshots**
![unknown-226](https://user-images.githubusercontent.com/65487082/191296787-fb7f11ab-7920-4886-9161-b9470d96d056.png)
![Screenshot_20220920-111028_Chrome](https://user-images.githubusercontent.com/65487082/191296829-06637199-c73f-4cbc-bd3d-bdb700b05c71.jpg)
![Screenshot_20220920_103800](https://user-images.githubusercontent.com/65487082/191296851-bb3b0f9e-3da2-4724-b3a9-f43563bc6b4d.jpg)

**Comment by SolarCat02** [comment]
I should add...
Subscribers worked at 3:30am EST 20 Sept 2022 (~8 hours ago) but stopped working my 8:50am EST 20 Sept 2022 (~2.5 hours ago).

**Comment by iamromeo** [comment]
Thank you for reporting @SolarCat02  we are investigating the issue

**Comment by JulianRRJ** [comment]
I can't access content that I was subscribed but I'm logged in.

**Comment by iamromeo** [comment]
@SolarCat02 I will need more specific information to proceed with this 
- This is **NOT AN ISSUE** with Articles or it cannot be reproduced.

**Comment by Naeliner** [comment]
I am also unable to see Solar's article and I can confirm I was able to see the content on that article before.

However, I tested asking someone else to check one of my articles that has both a secret and some text inside a subscriber's subcontainer, and they are able to see my content
Article: https://www.worldanvil.com/w/symbols-of-power-naelin/a/good-one-rank
The container is a box with a red border under the section "A private name" and Dimitris should be able to see it. The secret is at the bottom of the article

**Comment by SolarCat02** [comment]
I have given you access to this Discussion Board.

https://www.worldanvil.com/w/vazdimet/board/private-communiques

![Screenshot_20220920_114218](https://user-images.githubusercontent.com/65487082/191303521-8014b93b-3d3b-45d8-8669-43bafbd47d93.jpg)

**Comment by iamromeo** [comment]
> You now also have access to this Manuscript.
> 
> https://www.worldanvil.com/community/manuscripts/read/8543493613-solarcat02-facets-of-fillimet2C-vol-23A-vazdimet/35e859d5-be47-4680-b5b8-bbd1faa9790a

Yes I have access to the manuscript - which Implies there is no problem with this?

**Comment by SolarCat02** [comment]
The person whose manuscript I tested on must have hidden theirs from me then. My apologies.

The Discussion Boards is still not working though.

**Comment by iamromeo** [comment]
> The person whose manuscript I tested on must have hidden theirs from me then. My apologies.
> 
> The Discussion Boards is still not working though.

I can confirm there is a possible issue with Discussion boards - we are investigating

**Comment by SolarCat02** [comment]
Thank you!

**Comment by SolarCat02** [comment]
How many chapters can you see at this link? 
You have permission to see all of them. Only the first three are public, and it seems only those are visibly listed for subscribers.

https://www.worldanvil.com/w/vazdimet/c/book-13A-in-spite-of-the-inevitable-category

**Comment by iamromeo** [comment]
@SolarCat02 I will need to you be more detailed please - I am trying to help but being bombarded does not help me resolve this. Are you talking about somewhere on the page ? Is it a ToC / A tagged list?

**Comment by iamromeo** [comment]
**Update**
In regards to the issue of access to **DISCUSSION BOARDS** the issue as described above cannot be replicated. 

I can confirm that some changes took place today during release but the system appears to work as should.

**Comment by iamromeo** [comment]
> I am also unable to see Solar's article and I can confirm I was able to see the content on that article before.
> 
> However, I tested asking someone else to check one of my articles that has both a secret and some text inside a subscriber's subcontainer, and they are able to see my content Article: https://www.worldanvil.com/w/symbols-of-power-naelin/a/good-one-rank The container is a box with a red border under the section "A private name" and Dimitris should be able to see it. The secret is at the bottom of the article

I can confirm that I can see the contents of the red box. 
**@Naeliner this might be related to a different deployment related to a change on the access checks of BBcode. 
Can you please create a separate bug for this.**

**Comment by SolarCat02** [comment]
I apologize for the repeated messages. I will condense.

My subscribers cannot access this private discussion board, even though they have access to see it:
https://www.worldanvil.com/w/vazdimet/board/private-communiques

We had been writing in this thread yesterday, and now they cannot see it:
https://www.worldanvil.com/w/vazdimet/thread/b9270292-780e-4d68-b9c2-ec58cbea692e/view

Also there seems to be an issue displaying subscriber TOC articles to subscribers. There are 44 chapters listed on this page. Only my coauthor can see more than 3. It uses the category specific TOC callout. 
[toc:adb77ca5-bce9-449f-be92-64358ea812d0]

https://www.worldanvil.com/w/vazdimet/c/book-13A-in-spite-of-the-inevitable-category

**Comment by Kordishal** [comment]
You should make a screenshot of what Dimi is supposed to see on that page

**Comment by SolarCat02** [comment]
Screenshots of how it should look.

**Discussion Boards**
![Screenshot_20220920-122603_Chrome](https://user-images.githubusercontent.com/65487082/191313201-2363b23e-ebd7-41fc-ad0e-972beff7ec4c.jpg)
![Screenshot_20220920-122623_Chrome](https://user-images.githubusercontent.com/65487082/191313231-1aa87097-c5cf-41dc-886d-5e5b523163fa.jpg)

**Screenshots of Chapter List**
On page
![Screenshot_20220920-122658_Chrome](https://user-images.githubusercontent.com/65487082/191313307-c72e582d-0dc1-4cb6-9fb4-f3a243393bc0.jpg)

In [TOC]
![Screenshot_20220920-121943_Chrome](https://user-images.githubusercontent.com/65487082/191313361-d8d31807-a461-499b-b393-c43047ccc318.jpg)

**Comment by iamromeo** [comment]
> I am also unable to see Solar's article and I can confirm I was able to see the content on that article before.
> 
> However, I tested asking someone else to check one of my articles that has both a secret and some text inside a subscriber's subcontainer, and they are able to see my content Article: https://www.worldanvil.com/w/symbols-of-power-naelin/a/good-one-rank The container is a box with a red border under the section "A private name" and Dimitris should be able to see it. The secret is at the bottom of the article

Naelinar - this is what I see - what shouldn't I be able to see? 

![image](https://user-images.githubusercontent.com/660175/191314383-e25b2979-1160-4642-850f-dcbfea556d1e.png)

**Comment by Kros78** [comment]
If it's of help we could replicate the discussion board problem in my account too.
A discussion board has been set as private and accessible only to a subscriber group.
The members to that subscriber group can't access it as they should.
The members of the group can still access other content like subscribers specific containers.

**Comment by Kros78** [comment]
![image](https://user-images.githubusercontent.com/114015095/191321224-25191ce9-50e2-4e54-b6a8-68c15ad65e5e.png)

**Comment by GorkamWorka** [comment]
@SolarCat02 just deployed a fix that i think can fix it can you check ?

**Comment by SolarCat02** [comment]
It worked! Thank you so much!

Back to our regularly scheduled live fiction. Thank you! That was faster than I dared hope.
