### ISSUE TITLE
Negative Anvil Coins

### ISSUE THREAD

**Issue by GIB-H** [worldanvil/worldanvil-bug-tracker#128]
**World Anvil Username**: ibhulbert

**World / Campaign / RPG Character / Manuscript Title**: Not world/campaign related

**Feature**: Anvil Coins

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/dashboard/user/user/coin/transaction/list
![image](https://user-images.githubusercontent.com/72026233/113600429-ebe5b680-9637-11eb-82b8-e8d602a61a48.png)

**Describe the Issue**
I was able to give a -300 to a feature when I only had 50 Anvil Coins to begin with.

**To Reproduce**
1. Go to https://www.worldanvil.com/community/voting/
2. Click on a suggested feature, I clicked on "Themes"
3. When prompted on how many coins to give/subtract, select a minus greater than your balance
4. The transaction will go through and you will end up with a negative amount of coins
5: See error

**Expected behavior**
A prompt or message to say that not enough coins were available to vote with, similar to what happens when someone tries to give too many coins and they don't have enough.

**Screenshots**
![image](https://user-images.githubusercontent.com/72026233/113600855-8514cd00-9638-11eb-9c1a-965500ebabc4.png)
![image](https://user-images.githubusercontent.com/72026233/113600897-9067f880-9638-11eb-8692-7483f131875f.png)

**Comment by Kordishal** [comment]
Only negative numbers of coins are not checked properly.

**Comment by Kordishal** [comment]
![image](https://user-images.githubusercontent.com/14262536/113603514-56045880-9644-11eb-82fa-8df291bc5ffc.png)

Both those -300 were added by accident on the Theme suggestion https://www.worldanvil.com/community/voting/suggestion/15686f4c-6092-40f6-a68c-f549055a1570/view

**Comment by iamromeo** [comment]
Fixed (missed abs() on the check so -300 was considered that the used had more points than it was needed)

**Comment by iamromeo** [comment]
Thank you for reporting @GIB-H thank you for checking @Kordishal
