### ISSUE TITLE
Historical Entry Secret Info Text Formatting Break 

### ISSUE THREAD

**Issue by Jadelaw413** [worldanvil/worldanvil-bug-tracker#1280]
**World Anvil Username**: Jadelaw413

**World / Campaign / RPG Character / Manuscript Title**: Panngraeca of the Sallesian Realms

**Feature**: Timelines/Historical Entries

**Operating System**: Windows 10 Home, version 21H2, build 19044.2006

**Browser**: Firefox but tested on Chrome as well with same results

**Device / Device Model**: MSi GL73

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
The formatting on a timeline is broken by historical entries that contain certain text sequences in the 'Secret Information' section under advanced options when editing Historical entries. Using dashes at the start of new lines in the Secret Information section of a Historical Entry (see Step 8 below) is the only way I've been able recreate this bug but I used the phrasing 'certain text sequences' in case other characters can cause the same issue.
     Such corrupted formatting includes the sidebar options when editing a timeline being all the way down at the bottom of the page and jammed so far to the left they're covered by the main navigation menu, the Orphaned Histories section becomes not visible at all, and any historical entry that comes chronologically after the corrupted entry instead appears at the end where Orphaned Histories would normally be (both when editing the relevant timeline and when viewing it). In addition, the edit and delete buttons on entries past the corrupted entry can not be clicked as they disappear before the cursor can mouse over them. Said articles can still be edited however by visiting the edit link directly. This issue was caused by the presence of dashes in the Secret Information section of the Historical Entry (see below) creating a List through unintended code formatting (if I knew the difference I'd specify html or css or whatever it is that World Anvil uses for article text formatting)

**To Reproduce**
1. Go to 'Timelines' 
2. Scroll down to 'Simple Timelines'
3. Click on 'Edit … Timeline' 
4. Click on 'Create a new Historical Entry'
5. Name the new Historical Entry and attach it to your timeline
6. Scroll down to and click 'Show advanced options'
7. Scroll down to and click the 'Secret Information' text box
8. At the start of any new line, type a 'dash' followed by a 'space' and then any text [eg. '- w']
9. Scroll to and click 'Save Changes'
10. Click '… Timeline'
11. See error

**Expected behavior**
I expected the dashes to just be dashes to be honest. That's on me however for not realizing that text formatting worked in the 'Secret Information' box. Past that, I would expect a list created in that way to be contained within the usual historical entry box on a timeline and to not break the formatting of everything that comes after it.

**Screenshots**
A side by side comparison of the raw text in the Secret Information text box and how it breaks the formatting in the timeline editor:
https://cdn.discordapp.com/attachments/923807457761959977/1022247500742135909/unknown.png

The sidebar options shoved to the bottom left of the screen in the Timeline editor:
https://cdn.discordapp.com/attachments/923807457761959977/1022219521097994351/unknown.png

How the broken formatting looks when viewing the timeline:
https://cdn.discordapp.com/attachments/923807457761959977/1022252771476508763/unknown.png

**Comment by iamromeo** [comment]
Hey there! 

The timelines themselves are actually a list element therefore you cannot use a list element of either kind [li] or "-" in them. 
This is not an issue of the specific section but of the timelines in general, simply put you cannot use lists in them.
