### ISSUE TITLE
Pink background added to striketrough text on journals (Light and grey themes)

### ISSUE THREAD

**Issue by Naeliner** [worldanvil/worldanvil-bug-tracker#1284]
**World Anvil Username**: Naelin

**World / Campaign / RPG Character / Manuscript Title**: Journal entries on profile

**Feature**: Site UI BBCode

**Operating System/browser **: Several (Screenshots are from different people on several devices)

**Browser**: Chrome

**Device / Device Model**: Both PC and mobile

**Related URLs**: https://www.worldanvil.com/dashboard/user/post/94105716-830b-41e2-a6e8-a3fd7b31f198

**Describe the Issue**
When using either the Light or the Dark Grey theme on WorldAnvil, strikethrough text written in the site's UI such as the journal entries (NOT in the world) have a pink background. This doesn't happen in the deep blue theme.

**To Reproduce**
Write a journal entry (and presumably also profile introductions) with text between [s][/s] commands and see the result

**Expected behaviour**
The text should have a transparent background and be crossed out. The crossed-out effect is showing correctly but the background is pink.

**Screenshots**
![image](https://user-images.githubusercontent.com/86533873/192147090-f0e1ae19-f9b5-4ca7-b172-e5d207daeecb.png)
![image](https://user-images.githubusercontent.com/86533873/192147128-c4792cdd-c916-44c9-b65a-7490bba55245.png)
![image](https://user-images.githubusercontent.com/86533873/192148191-11abecf6-11d7-4807-aa13-6771adbec2f4.png)
![image](https://user-images.githubusercontent.com/86533873/192148266-55b9b9e5-47a5-4110-9c58-64a898c68ae6.png)
![image](https://user-images.githubusercontent.com/86533873/192148274-5e4d7f1b-93a7-46bc-8b2a-cb175fd4f793.png)

**Comment by iamromeo** [comment]
The not-really fix for the not-really a bug will be deployed later in the week.
