### ISSUE TITLE
Chronicle Timelines Visuals

### ISSUE THREAD

**Issue by daedelous00** [worldanvil/worldanvil-bug-tracker#1285]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Daedelous

**World / Campaign / RPG Character / Manuscript Title**: Worldtest1

**Feature**: Chronicle

**Operating System**: Windows 11

**Browser**: Chrome

**Device / Device Model**: n/a

**Related URLS** (To public & visible pages, add screenshots otherwise): n/a

**Describe the Issue**
Multiple bugs here:

1) WorldAnvil's Chronicle timelines can't properly retrieve icons from FontAwesome. When I try to add an icon to my Chronicle timeline, none of the FontAwesome icon names I enter seem to be accepted. I did figure a couple icon names that work, but it seems like WorldAnvil is using an old version with different names than FontAwesome's website(?).

2) Even when I find an icon that WorldAnvil accepts, it never displays on the timeline like it's supposed to.

Overall, I'm frustrated at the lack of ability to see my (to soon be) complicated, far-reaching timelines at a glance. I can't put any text on them directly (this would be a very nice feature), none of the the icons seem to work, and I can't scale the timeline in/out (my timeline covers many millennia). All of this almost makes this feature useless for me, as I can't see a lot of information at a glance, and is the only reason I subscribed to worldanvil.

**Comment by Kordishal** [comment]
Chronicles currently use v5.x icons and not v6 icons.

https://fontawesome.com/v5/search

Make sure to add the full code: `fas fa-yin-yang`

Icons definitely work in general.
