### ISSUE TITLE
Chronicle Icons

### ISSUE THREAD

**Issue by daedelous00** [worldanvil/worldanvil-bug-tracker#1286]
**World Anvil Username**: Daedelous

**World / Campaign / RPG Character / Manuscript Title**: WorldTest1

**Feature**: Chronicle Timeline

**Operating System**: WIndows 11

**Browser**: Chrome

**Describe the Issue**
In Chronicle, I chose an icon for my timeline event but it is not appearing. See Screenshots of this.
![Screenshot 2022-09-30 165038](https://user-images.githubusercontent.com/114772983/193361889-3e210a70-3761-4e1e-91eb-db1e555bf4eb.png)
![Screenshot 2022-09-30 175843](https://user-images.githubusercontent.com/114772983/193361890-88be061f-b0b9-42d5-96b5-44083f10e11e.png)

**Comment by iamromeo** [comment]
Hello there @daedelous00 - this is not a bug - Currently, icons  only appear when an event does not have length
