### ISSUE TITLE
add RPX system

### ISSUE THREAD

**Issue by GreyWulfe** [worldanvil/worldanvil-bug-tracker#1288]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name (RPG SYSTEM)**:RPXpress
**List Name** (Name under which it should be listed on World Anvil):RPXpress
**World Anvil Username**:Grey Wulfe

**Website**:https://www.drivethrurpg.com/product/398176/Extraordinary-Adventures-Players-Handbook?src=hottest_filtered

**Logo Image Link**:

**Logo Usage Terms (URL)**:

**Comment by iamromeo** [comment]
All done
