### ISSUE TITLE
Various editing issues with characters

### ISSUE THREAD

**Issue by Telmach** [worldanvil/worldanvil-bug-tracker#1289]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Telmach

**World / Campaign / RPG Character / Manuscript Title**: YonZora / The War for Soteropolis / Dagon Innsmouth

**Feature**: Profile Picture / Journal Entries

**Operating System**: Windows

**Browser**: Brave Browser

**Device / Device Model**:

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
Attempting to change my profile picture or using italics in a journal entry cause changes not to be saved.

**To Reproduce**
1. Click edit character
2. Upload a picture for the character
3. Click save
4.  The screen refreshes, and a green banner displays that says "All done, your changes to to Dagon have been saved!"
5. The image however remains the default image.
![Italics](https://user-images.githubusercontent.com/75909257/193425459-848a548f-876b-4a0b-8be5-31fb1e14405d.png)
![Text](https://user-images.githubusercontent.com/75909257/193425463-fd3108e6-c0bb-4fc6-abaa-4506e4da498b.png)
![Pre](https://user-images.githubusercontent.com/75909257/193425464-e989b605-9240-464e-a57e-a49a8b2cc3a1.png)
![Post](https://user-images.githubusercontent.com/75909257/193425465-97996787-ff07-4a7e-9a3f-e07724287ca7.png)

1. Click Write a new journal
2. Fill out the Title, Body, and date.
3. Add any italicized text such as "𝘓𝘢 𝘭𝘢 𝘭𝘢. 𝘓𝘰𝘰𝘬 𝘢𝘵 𝘮𝘦. 𝘐'𝘮 𝘴𝘰 𝘴𝘮𝘢𝘭𝘭 𝘢𝘯𝘥 𝘐 𝘭𝘰𝘷𝘦 𝘣𝘦𝘪𝘯𝘨 𝘱𝘪𝘤𝘬𝘦𝘥 𝘶𝘱. 𝘓𝘢 𝘭𝘢 𝘭𝘢. 𝘊𝘈𝘛𝘊𝘏 𝘔𝘌 𝘐𝘍 𝘠𝘖𝘜 𝘊𝘈𝘕"! 
4. Click sign and submit.
5. The page refreshes with a 404 error.

**Expected behavior**
I expect I can change my profile picture and use italics in journal entries.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Hi!

A character portrait not being saved means that World Anvil does not accept it. It is true that there is no error message for it and instead says that it is accepted anyway.

Common reasons for images not being accepted are image size and image format.

RPG Character portrait images have a 1 MB size limit and have to be PNG, JPG or WEBP. In rarer cases the image may simply have some metadata that World Anvil cannot process. In that case make sure to re-export the image from a standard image processing software like GIMP or Photopea. It is recommended to upload all images as WEBP as this is the best format for the web.

As for italics not working: World Anvil uses BBCode to format text the way you want. To create italics surround the the text with `[i] [/i]`. Formatting from Rich Text Editors like Word or Google Docs are not accepted by World Anvil.
