### ISSUE TITLE
Unable to use my Grandmaster Guild membership for features in maps

### ISSUE THREAD

**Issue by only1maimi** [worldanvil/worldanvil-bug-tracker#1291]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Maimi

**World / Campaign / RPG Character / Manuscript Title**: Locfaion

**Feature**:  Maps, create new marker, Circle 

**Operating System**: Windows 10

**Browser**: Chrome

**Device / Device Model**: Surface Pro 7

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue** When selecting the circle marker, I get this message: This is a Grandmaster+ level exclusive feature. Join the [Worldbuilders Guild](https://www.worldanvil.com/worldbuilders-guild-membership) to get access to this feature and help the development of World Anvil.

A clear and concise description of what the issue is. Have Grandmaster Membership, unable to create circle markers on maps

**To Reproduce**
1. Go to any map
2. Click on edit
3. Select Circle(as marker)

**Expected behavior**
A clear and concise description of what you expected to happen.  I'd like to be able to use the features I'm paying extra for.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Hello @only1maimi from what I can see you have no worlds of your own - your Grandmaster feature can be used on your own worlds not worlds of people that do not have that level. 
The features activated in any world are bound to the owner not the author.
