### ISSUE TITLE
Marker drop shadow is not loading and shows [?] on map. 

### ISSUE THREAD

**Issue by wcatron** [worldanvil/worldanvil-bug-tracker#1292]
**World Anvil Username**: wesman16

**World / Campaign / RPG Character / Manuscript Title**: "Disparate Valley"

**Feature**:  Map

**Operating System**: Mac

**Browser**: Safari (I couldn't reproduce in Chrome)

**Device / Device Model**: MacBook Pro

**Describe the Issue**
Marker shows [?] behind it as shown below.

**To Reproduce**
1. Go to [The World Map](https://www.worldanvil.com/w/disparate-valley-wesman16/map/5366422a-3a5d-456c-830f-cff1574adc4f) in **Safari**
2. Find the Library and Manufacturing District in the town

**Expected behavior**
Either a drop shadow appears or nothing appears.

**Screenshots**

<img width="175" alt="Screen Shot 2022-10-02 at 10 53 49 AM" src="https://user-images.githubusercontent.com/5385284/193460579-755b9952-071f-49cd-a52b-f2d61f823208.png">

**Comment by iamromeo** [comment]
Confirmed and fixed - will be deploying later on today or tomorrow.
