### ISSUE TITLE
Dashboard Categories Has Non-functional Buttons

### ISSUE THREAD

**Issue by Maxcalibur** [worldanvil/worldanvil-bug-tracker#1293]
I am trying to create some new articles for my RPG setting, but when click on a category of article on the dashboard, it takes me to the articles I am already working on.

Matmatmat

Sinefine

Dashboard: 

Windows 10

Google Chrome

Lenovo
Device name	DESKTOP-KJK0RJA
Processor	Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz   2.21 GHz
Installed RAM	8.00 GB
Device ID	74BED48A-ABCE-4106-9AF5-89EF91CF9CAD
Product ID	00325-96482-06387-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

**Attempts to create new articles results in me being redirected to the articles page instead of a new article**
1. Go to 'Dashboard'
2. Click on 'Any article category button'

**Expected behavior**
I expected to be taken to the editing page for a new article

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Do you mean these buttons?

![image](https://user-images.githubusercontent.com/14262536/193482312-41d0890e-81f8-4c52-94a9-00c73c9b07c2.png)

They work fine for me. Not sure what could be the issue on your end.
