### ISSUE TITLE
Webhook link doesn't send you to correct place

### ISSUE THREAD

**Issue by Catoblepon** [worldanvil/worldanvil-bug-tracker#1295]
**World Anvil Username**: Catoblepon

**World**: Iphars (although it doesn't mind which world I'm in)

**Feature**: Webhook link to guide

**Operating System**: Windows

**Browser**: Chrome

**Device / Device Model**: Laptop

**Related URLS** (To public & visible pages, add screenshots otherwise): 
![image](https://user-images.githubusercontent.com/55326820/193578491-43182232-5664-4176-a6fe-0b578885dfa6.png)

**Describe the Issue**
In the world's setting, specifically in socials, where the webhook spot is, the link given to direct you to a codex article about webhook isn't correct and sends you to the Homepage of the Codex.

**To Reproduce**
1. Go to World's Settings - > Socials
2. Scroll down to "Discord global updates webhook"
3. Click on "Check out this guide"
4. Be sent to the codex homepage rather than the webhook article

**Expected behavior**
The link should send you to the webhook article in the codex rather than the homepage

**Comment by iamromeo** [comment]
Fixed will deploy later on in the week the link should be set to go here: https://www.worldanvil.com/w/WorldAnvilCodex/a/guide-to-setting-up-a-discord-webhook-article
