### ISSUE TITLE
Unable to access Secrets list

### ISSUE THREAD

**Issue by Gamingbrew** [worldanvil/worldanvil-bug-tracker#1296]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Gamingbrew

**World / Campaign / RPG Character / Manuscript Title**: Erenel

**Feature**: Secrets

**Operating System**:

**Browser**: Chrome and Firefox

**Device / Device Model**:

**Related URLS** (To public & visible pages, add screenshots otherwise): https://www.worldanvil.com/world/secret/list

**Describe the Issue**
Receiving a 500 error when trying to access my worlds secret list.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Hotfix being deployed
