### ISSUE TITLE
can not sub

### ISSUE THREAD

**Issue by Teslakoyal** [worldanvil/worldanvil-bug-tracker#1299]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Teslakoyal

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: Subscribing

**Operating System**: Windows

**Browser**: Google Chrome and MS Edge

**Device / Device Model**: PC

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is. Can't sub, just keeps taking me to the top of the screen

**To Reproduce**
1. Go to '...' go to sub page
2. Click on '....' click on sub button

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
For issues with subscription please write an email to the support email of World Anvil. 

https://www.worldanvil.com/help/ 

The email under Send Us A Message!
