### ISSUE TITLE
Very long loading times on Heroes pages

### ISSUE THREAD

**Issue by artyrambles** [worldanvil/worldanvil-bug-tracker#130]
**World Anvil Username**: arty

**World / Campaign / RPG Character / Manuscript Title**: n/a

**Feature**: Heroes

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/community/stream and any character's page

**Describe the Issue**
The loading times on Heroes pages (stream and character profiles) take up to minutes. Confirmed by several people I talked to who are experiencing the same.

**To Reproduce**
1. Open any Heroes page
2. For example, Followed Characters Stream
3. Watch the little loading icon spin for a looong time

**Expected behavior**
The loading times should be within an acceptable range, similar to other WA pages. When they are this long, most people will just get tired of waiting and close the tab.

**Screenshots**
n/a

**Comment by iamromeo** [comment]
Abstract definition - Yes stream take some time.
