### ISSUE TITLE
Discord Embeds do not use the cover image for Chronicles

### ISSUE THREAD

**Issue by bitterolft** [worldanvil/worldanvil-bug-tracker#1300]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Soul Valand

**World / Campaign / RPG Character / Manuscript Title**: Astralaria

**Feature**: Chronicle

**Operating System**: Windows 11

**Browser**: Opera GX

**Device / Device Model**: NA

**Related URLS** (To public & visible pages, add screenshots otherwise): 
https://www.worldanvil.com/w/astralaria-soul-valand/chronicle/the-calamity-chronicle

**Describe the Issue**
 It looks like it doesn't consider the cover image for chronicles to be an actual cover image the same way it does for articles. It always uses the default WA cover image for chronicle embeds.

**To Reproduce**
1. Go to 'https://www.worldanvil.com/w/astralaria-soul-valand/chronicle/the-calamity-chronicle'
2. Click on 'Chronicle Settings'
3. Click on 'Display'
4. Upload or Select the image if already uploaded.
5. Paste link in Discord. 

**Expected behavior**

**Screenshots**
![unknown](https://user-images.githubusercontent.com/9982372/194778811-f6574891-35df-4a01-9f2f-e85aca06d2c9.png)
![unknown](https://user-images.githubusercontent.com/9982372/194778828-078c27a1-e568-4699-b298-f91276f7da19.png)

**Comment by iamromeo** [comment]
I am sorry but this is not a bug, it was never designed or intended to work as such. You can request a feature for this.
