### ISSUE TITLE
New RPG System for World Anvil

### ISSUE THREAD

**Issue by kengc2** [worldanvil/worldanvil-bug-tracker#1301]
**Full Name:**:Warlock!
**List Name** (Name under which it should be listed on World Anvil):Warlock!
**World Anvil Username**:U_Killed_Kenny!

**Website**: https://www.facebook.com/firerubydesigns/

**Logo Image Link**: https://www.facebook.com/photo/?fbid=624038742513116&set=a.624038705846453

**Logo Usage Terms (URL)**:<unknown>

**Comment by iamromeo** [comment]
All done!
