### ISSUE TITLE
Created Chronicle is now only loading a blank white screen

### ISSUE THREAD

**Issue by Alrena** [worldanvil/worldanvil-bug-tracker#1302]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Asharen

**World / Campaign / RPG Character / Manuscript Title**: Runeterra

**Feature**: Timeline

**Operating System**: Windows 10

**Browser**: Chrome

**Device / Device Model**: Asus Predator / 

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
After creating parts of the timeline a few months ago I was editing settings (I honestly can't remember now which ones) and ran into an issue where the timeline screen would only load pure white. At the time I figured it was a temporary bug and would be worked out while I focused on other projects.
Coming back now though I'm still having the issue where it will show the loading screen when I go to edit the timeline but then, when it seems to have finished loading after a couple seconds, becomes a completely white screen. This issue exists on both my laptop and desktop on chrome.
I tried turning hardware acceleration on to see if that might have a difference and cleared cookies and cache to no avail.

**To Reproduce**
1. Go to Timelines
2. Click the edit button for
3. Page begins loading
4. Page is blank white

**Expected behavior**
Having the timeline load up properly

**Screenshots**
![chrome_OA1XhKVx5i](https://user-images.githubusercontent.com/19279451/194966249-a8c748a3-b54b-41bf-b2b6-3be332f2a021.png)

![chrome_HltPuwgqei](https://user-images.githubusercontent.com/19279451/194966261-c0e41b59-7d48-4071-8efe-73ab30be2f73.png)

**Comment by Kordishal** [comment]
Does this happen if you create a new chronicle?

**Comment by Kordishal** [comment]
Considering that you made this chronicle a few months ago there might be a migration issue, as there were quite a few changes to chronicles since then.

Have you tried hard refreshing the cache to ensure that all the new scripts and files are loaded? You can do that by pressing CTRL+F5 after opening the chronicle.

Should this not resolve the issue it might require direct intervention by the dev which could get tricky. Would you lose a lot of work?

**Comment by iamromeo** [comment]
Closed due to inactivity. 
@Alrena please feel free to update us if there are any new information
