### ISSUE TITLE
Campaign homepage still shows ads for visitors even with Grandmaster subscription

### ISSUE THREAD

**Issue by randy1976** [worldanvil/worldanvil-bug-tracker#1303]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Randy1976

**World / Campaign / RPG Character / Manuscript Title**: The Dawn Realms

**Feature**: Upgrading to grandmaster doesn't stop ads from popping up in browser.

**Operating System**: Windows 10

**Browser**: Chrome

**Device / Device Model**: Surface Pro

**Related URLS** (To public & visible pages, add screenshots otherwise): https://www.worldanvil.com/epic/the-dawn-realms

**Describe the Issue**
Updating to grandmaster did not effect the ability of my players to not experience advertisements on the homepage.

**To Reproduce**
1. Go to ['...'](https://www.worldanvil.com/epic/the-dawn-realms)
2. See ad located beneath title banner.

**Expected behavior**
I expect not to see advertisements when I am not logged in as myself.

**Screenshots**
![image](https://user-images.githubusercontent.com/115557227/195095407-39340a87-38c3-4575-9792-569a3562b1e7.png)

**Comment by iamromeo** [comment]
Fixed will be deployed later this week.
