### ISSUE TITLE
Not saving my work

### ISSUE THREAD

**Issue by btransu1** [worldanvil/worldanvil-bug-tracker#1305]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: CadetPenguin

**World / Campaign / RPG Character / Manuscript Title**: Ellhenora

**Feature**: Description

**Operating System**: Windows 10

**Browser**: Chrome

**Device / Device Model**: Custom

**Related URLS** (To public & visible pages, add screenshots otherwise): https://www.worldanvil.com/w/ellhenora-cadetpenguin

**Describe the Issue**
A clear and concise description of what the issue is. I just lost a two hours of work after trying to fill out the description of my world, I hit the SAVE button and instead of SAVING what I had spent so much time working on, it instead deleted everything and reverted back to what it said the last time I saved it, which wasn't even a full paragraph

**To Reproduce**
1. Go to 'description'
2. Click on 'save after spending two hours working on your lore'
3. watch as everything disappears

**Expected behavior**
To save my work instead of deleting it

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
I am really sorry for the loss of your work @btransu1
Under the above description and details there is not much I can investigate. 

Possible causes of this: 
- You had an account in the past with the same username and created a world with the same name, 
- You have used a not allowed character like an emoji or something within the UTF16 range
