### ISSUE TITLE
Changed the theme on my players handbook and now no links are working

### ISSUE THREAD

**Issue by Catspur** [worldanvil/worldanvil-bug-tracker#1306]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: catspur

**World / Campaign / RPG Character / Manuscript Title**: Northlands

**Feature**: View world/players handbook

**Operating System**: windows 11

**Browser**: chrome

**Device / Device Model**: PC

**Related URLS** (To public & visible pages, add screenshots otherwise): https://www.worldanvil.com/w/the-northlands-catspur

**Describe the Issue**
A clear and concise description of what the issue is.
I changed the theme to my world view/players book, using Bright Fantasy, and suddenly non of the options are selectable. I tried changing it back and still the same. i tried other themes and they worked, but that one doesn't. But thats the one that best suits the look I want. I tried leaving it overnight in case things needed to magically refresh but its the same.

**To Reproduce**

**Expected behavior**
Nothing happens

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Catspur** [comment]
Tried again and no matter what theme I choose for Northlands World the links are not working.

**Comment by Kordishal** [comment]
Then that has most likely nothing to do with the themes. Instead you have most likely an unclosed BBCode tag on the pages you can't click links. If its all of them then it must be in a global field.

**Comment by Catspur** [comment]
Would you care to elaborate, with some examples, and explain what I do next?

**Comment by iamromeo** [comment]
@Catspur we do not have access to your private data - nobody does unless you give them access to them. (you can check the Privacy policy for that) 

[br] should not be an issue the [in] if it is not followed by an [/in] can be :) but as @Kordishal we cannot know if we cannot see what is going on.

**Comment by Kordishal** [comment]
Yes most likely you did not close a [in] somewhere. Make sure for every [in] there is a [/in] at the end of the paragraph.

**Comment by iamromeo** [comment]
@Catspur can we have an update on this ? Is this resolved? Have you find the unclosed [/in] - if not can we have co-author access so we can investigate?

**Comment by iamromeo** [comment]
Closed due to inactivity.
