### ISSUE TITLE
SPQR

### ISSUE THREAD

**Issue by Serpicko** [worldanvil/worldanvil-bug-tracker#1308]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name (RPG SYSTEM)**: SPQR
**List Name** (Name under which it should be listed on World Anvil): SPQR
**World Anvil Username**: Serpicko

**Website**: https://store.warlordgames.com/collections/spqr/products/spqr-death-or-glory-rulebook

**Logo Image Link**: 
![Screenshot 2022-10-14 190247](https://user-images.githubusercontent.com/115740336/195912211-04f1fca5-775a-4881-a04a-cae9304a6ada.png)

**Logo Usage Terms (URL)**:

**Comment by iamromeo** [comment]
All done!
