### ISSUE TITLE
Character sheet values barely visible in Terror from the Deep theme

### ISSUE THREAD

**Issue by Deixx** [worldanvil/worldanvil-bug-tracker#1309]
**World Anvil Username**: Deixx

**Feature**:  Character Sheet

**Operating System**: Windows 11

**Browser**: Opera GX

**Device / Device Model**: PC

**Describe the Issue**
There are actually 2 issues concerning this.
1. Character sheet values are barely visible in Terror from the Deep theme. (Very light numbers on white background, see screenshots.)
2. If I have Villains theme selected and click twice on 'switch between light & dark mode' button, the theme goes from Villains to Heroes to Terror from the Deep.

**To Reproduce**
1. Change theme to Villains.
2. Go to 'Character sheet' (values should be visible).
3. Click the button to switch to light mode.
4. Click the button to switch to dark mode.
5. See that the theme has changed to Terror from the Deep and that the values are barely visible.

**Expected behavior**
Switching back to dark mode should restore previously set dark mode, and values should be clearly visible.

**Screenshots**
Villain theme:
![villain](https://user-images.githubusercontent.com/45125679/195975784-97d081e2-6f0e-4922-afa9-cb5adbfbc7e7.png)
Terror from the Deep theme:
![terror](https://user-images.githubusercontent.com/45125679/195975769-a581b196-09a7-4fcc-b06b-7d2279c606c7.png)

**Comment by Kordishal** [comment]
This is an issue of the character sheet which is made and maintained by a community member. Furthermore it is not clear which character statblock you are talking about as there are quite a few and sometimes even multiple per system.

**Comment by Deixx** [comment]
@Kordishal, are you telling me that it's not an issue with site themes but rather with the character sheet? As I understand it's the theme that decides which colors are applied on what types of fields. It is a reasonable assumption considering that it works well for Heroes and Villains themes.
Furthermore you've completely ignored the 2nd described issue, with switching light/dark mode.

**Comment by Kordishal** [comment]
The statblock templates, including their CSS, are created by community members. The team cannot make an adjustment to make this work, the creator of this statblock template has to. The team does not have access to these templates. Which is why I closed this issue. You'll have to contact the creator of the Call of Cthulhu statblock template in order for this to get resolved. Most likely they just adjusted the CSS to work for the light theme and it happens to work for villains. So yes, this is an issue with the template and not with the theme.

The second issue is not a bug. It is working as intended. The villains theme is only maintained and not an official theme anymore.

**Comment by Deixx** [comment]
Thanks for clarification. I'll try to contact the statblock template creator.

**Comment by Deixx** [comment]
Hi @Kordishal, I've inspected the character sheet template site and compared it with https://github.com/Tillerz/worldanvil-templates/blob/master/block-system-2.0/call_of_cthulhu/character-sheet/call_of_cthulhu_sheet.css - I'm no expert but it looks like `.form-control` style used for the input box is just inherited from darkest.css (Terror from the Deep).
I've added the line highlighted in the below screenshot and it looks like it has fixed the problem. Using `background` instead of `background-color` also works and I've checked that dark.css (Villains) has `background` set. Could you check if darkest.css has any of the mentioned values set for `.form-control`? 
![image](https://user-images.githubusercontent.com/45125679/196899236-5bd058c3-e6e4-4ebb-a060-4beee8d53e9c.png)

**Comment by Deixx** [comment]
No longer needed, I've found what needs to be fixed in the template. Thanks!
