### ISSUE TITLE
Suggested features say "You have already voted on this feature." after being accepted even if you didn't.

### ISSUE THREAD

**Issue by Dark-Hobbit** [worldanvil/worldanvil-bug-tracker#131]
**World Anvil Username**: Dark Hobbit

**World / Campaign / RPG Character / Manuscript Title**: Not world/campaign related

**Feature**: Anvil Coins

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/community/voting/suggestion/f97b9421-8eda-4252-b040-16f51bcc4454/view

**Describe the Issue**
When a suggested feature is accepted, you can no longer vote on it. However, the description says "You have already voted on this feature." even if you didn't actually vote on it.

**To Reproduce**
1. Open an accepted feature suggestion you haven't voted on.
2. Get told by the website that you have voted on it.

**Expected behavior**
While this doesn't really break any mechanics, might be a good idea to switch the default description to something more like "You can no longer vote on this feature" and keep the initial message for only when a user actually did vote on that feature.

**Screenshots**
![You have already voted on this feature](https://user-images.githubusercontent.com/77054637/113680250-d7162b00-96ea-11eb-9b93-7830863db0c1.png)

**Comment by iamromeo** [comment]
Fixed
