### ISSUE TITLE
i can't upload my maps

### ISSUE THREAD

**Issue by gtraxx01** [worldanvil/worldanvil-bug-tracker#1310]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Gtraxx

**World / Campaign / RPG Character / Manuscript Title**: Selkari

**Feature**: 

**Operating System**: win10

**Browser**: google chrome

**Device / Device Model**: PC

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
i can't upload my maps

**To Reproduce**
1. Go to the maps menu
2. Click on "create map"
3. select the png on my pc (1,8mo)
4. put name and description
5. Click on "create map"
6. nothing is happening

**Expected behavior**
return to the map menu with my map upload

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/115902461/196009474-04fc0e36-e6bc-4528-8d51-f0b3178ea698.png)
![image](https://user-images.githubusercontent.com/115902461/196009511-f881d0d8-9c6d-4e56-baa1-9a2f7674c2e0.png)
![Sans titre2](https://user-images.githubusercontent.com/115902461/196009611-5657a18c-c1f2-4d2a-b713-ef98a31c6b09.png)

**Comment by Kordishal** [comment]
Hi! The file size is obviously not the problem here. Can you try to transform the image to a WEBP format? It is optimized for the web and will likely remove from the PNG what is causing WA troubles to accept the image,

**Comment by gtraxx01** [comment]
Thanks for your answer, but it didn't solve the problem.
![image](https://user-images.githubusercontent.com/115902461/196031015-06660bc8-57a4-4a8b-aab9-7db474266ca6.png)

**Comment by gtraxx01** [comment]
I think google chrome is the problem, I did the same manipulation on Mozilla Firefox and it worked
![image](https://user-images.githubusercontent.com/115902461/196033018-9d72d2a0-63f1-4c24-874d-773b0bf9c02a.png)

**Comment by Kordishal** [comment]
Do you have any extensions on Chrome? If yes could you try uploading the image in a incognito window to see if the issue persists?

**Comment by gtraxx01** [comment]
okey it work in incognito 
![image](https://user-images.githubusercontent.com/115902461/196034114-d653b26d-ec62-41f0-afa5-80b9100b03fa.png)
so i tried to remove my extensions but it didn't work

**Comment by Kordishal** [comment]
Then try pressing CTRL+F5 (hard refreshing cache). Maybe there is some script that is not loaded properly.

**Comment by iamromeo** [comment]
Hello @gtraxx01 as @Kordishal said that looks like a chrome extension issue - can you please confirm within the next 24 hours if that works when you are using Chrome in Incognito mode?
