### ISSUE TITLE
Issue with categories and articles

### ISSUE THREAD

**Issue by Lady-Ginnie** [worldanvil/worldanvil-bug-tracker#1311]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: LotusVee

**World / Campaign / RPG Character / Manuscript Title**: Clockwork heart

**Feature**: Category

**Operating System**: Windows 10

**Browser**: Google Chrome

**Device / Device Model**: iBuyPower PC

**Related URLS** (To public & visible pages, add screenshots otherwise): https://www.worldanvil.com/w/clockwork-heart-lotus-vee

**Describe the Issue**
I'm unable to make articles appear under categories. I've gone directly to the article pages to try to put it under my intended category, tried to drag the article under the category, logged out and back in, restarted my browser, and restarted my computer. Miss Medeline McBride from support reached out to me when I emailed her and told me to send in a bug report since it's not working.

**To Reproduce**
Try to put an article under a category.

**Expected behavior**
For the article to appear in the category on my world page. This does not happen.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/115916367/196021867-572f92e3-800a-4a6d-8419-54b79bf450d6.png)
![image](https://user-images.githubusercontent.com/115916367/196021887-18318db9-c019-437c-991b-60cb79973d4b.png)
![image](https://user-images.githubusercontent.com/115916367/196021903-505bba7b-e0ea-496d-a58a-9f50dba9593d.png)
![image](https://user-images.githubusercontent.com/115916367/196021972-02de5bb5-34e0-4762-a7bb-636f919b4b6e.png)

**Comment by Kordishal** [comment]
All of your articles are drafts. Publish them and they will show up.
