### ISSUE TITLE
Unable to delete world

### ISSUE THREAD

**Issue by Kattenkvvaad** [worldanvil/worldanvil-bug-tracker#1312]
**World Anvil Username**: Kattenkwaad

**World**: Planes & Primordials

**Feature**: Deleting the World

**Operating System**: Windows 11

**Browser**: Google Chrome

**Device / Device Model**: Laptop (Acer Aspire A317-51G)

**Related URLS** N/A?

**Describe the Issue**
I want to delete this world but after clicking the "Delete this World" button on the world configuration page and confirming I want to delete the world, it still remains in my list of worlds. I have tried this several times but it didn't make a difference.

**To Reproduce**
1. Go to the Configuration page for the world
2. Click on Delete World
3. Click on the "Delete this World" button
4. Confirm the deletion of the world
5. Get the screen that says "this is the end of this world"
6. Redirect back to the World Anvil homepage
7. See the world still fully intact and very much not deleted

**Expected behavior**
I would have expected the world to be deleted when I clicked the buttons to do so.

**Screenshots**
![image](https://user-images.githubusercontent.com/115976372/196113147-db7447ed-99f0-4ad7-8472-b9a5e36521f5.png)
![image](https://user-images.githubusercontent.com/115976372/196113177-b601f12d-cda4-4355-96ce-893debd7e8e3.png)
![image](https://user-images.githubusercontent.com/115976372/196113621-c9d76e55-2ccb-4831-9259-8b61e689c3bf.png)

**Comment by Kordishal** [comment]
Hi!

Before you can delete the world you should first do the following:

- Delete the campaign
- Expel any RPG Characters from your world
- Delete any manuscripts
- Remove subscribers & coauthors
- Delete subscriber groups.

After this the world should delete no problem
