### ISSUE TITLE
Whiteboard Avatar only shows characters chests

### ISSUE THREAD

**Issue by Lirissa** [worldanvil/worldanvil-bug-tracker#1313]
**World Anvil Username**: Lirissa

**World / Campaign / RPG Character / Manuscript Title**: Elandris

**Feature**: Whiteboard Avatar type

**Operating System**: Windows 10

**Browser**: Firefox

**Device / Device Model**:

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.
Instead of starting from the top of the image like in the family tree, using the avatar frame in whiteboards starts from the bottom, causing it to only show characters chests.
**To Reproduce**
Click on whiteboard, add a portrait-shape image/article, right click and change to avatar

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/100167372/196161162-1a35db83-5e8c-4dba-ba8c-a3d61e841005.png)

**Comment by iamromeo** [comment]
I am really sorry but this is not a bug and will not be addressed . 
This probably has to do with the fact that the **portrait** images for the characters at too tall and you are using a system that it meant to be using portraits not full body pictures.

**Comment by Kordishal** [comment]
But it could be improved by making the images start from the top instead of the bottom without making it worse with just portraits. Because these same images work fine in the family tree where a similar size circle is present.

**Comment by Lirissa** [comment]
Should i add it as a suggestion then? Though I wouldn't know how

**Comment by iamromeo** [comment]
Hey @Lirissa if you want to add it as a suggestion you can use the Feature Suggestions board here: https://www.worldanvil.com/community/voting/ :) and please - yes do go ahead - I would love to see what the rest of the community has to say about it.
