### ISSUE TITLE
Can't upload profile image

### ISSUE THREAD

**Issue by SunLo** [worldanvil/worldanvil-bug-tracker#1314]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: SunLo

**World / Campaign / RPG Character / Manuscript Title**: https://www.worldanvil.com/hero/cc44bfe2-11a9-43a0-8012-f6734803922a

**Feature**: Change Profile Image

**Operating System**: Windows 10, and android

**Browser**: Firefox and firefox mobile

**Device / Device Model**: Desktop and samsung s21 ultra

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
Anytime I've tried to upload a new profile image, it says it updates - but it nevers actually does. I've tried to use both desktop, phone and ipad.

**To Reproduce**
1. Go to Character profile
2. Click on Edit
3. Upload new profile image, see the tick appear
4. See error when saving the profile. Get success notification, but the image doesn't actually upload.

**Expected behavior**
I would exåepect uploaded image to actually be set as a profile image.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

![image](https://user-images.githubusercontent.com/37328034/196258764-43c441ca-c903-4df3-bcb3-2dfac59888fa.png)
![image](https://user-images.githubusercontent.com/37328034/196258820-720333f9-626f-404c-9e93-5d52ffbad1d5.png)

**Comment by iamromeo** [comment]
Hey there! Do you have enough space on your image store? 
What is the size of the image?

**Comment by SunLo** [comment]
Hi!
I don't have the image right now, but I think it's below 8Mb because I was
able to send it in a discord chat.

Right now I've only uploaded one profile image before, which was a
placeholder. I managed to delete this, but weren't able to upload a new one
even after this..

tir. 18. okt. 2022, 08:52 skrev Dimitris Romeo Havlidis <
***@***.***>:
