### ISSUE TITLE
Plots on the campaign screen leads to 500 ERROR screen

### ISSUE THREAD

**Issue by queenkitters** [worldanvil/worldanvil-bug-tracker#1316]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: queenkitters

**World / Campaign / RPG Character / Manuscript Title**: Out of the Abyss

**Feature**: Plots

**Operating System**: Windows 11
 
**Browser**: Google Chrome

**Device / Device Model**: acer Swift 3

**Related URLS** (To public & visible pages, add screenshots otherwise): 

**Describe the Issue**
From the Campaign screen, whenever I click the "Plots" button along the top menu, I am directed to an ERROR 500 page.

**To Reproduce**
1. Go to 'Campaign'
2. Click on 'Plots'
3. See error

**Expected behavior**
To be taken to the Plots page.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/116340694/197139464-bf3f15cd-5854-446d-b719-c8f91bec4897.png)
![image](https://user-images.githubusercontent.com/116340694/197139494-bd98caef-f1a9-4474-a781-0db002e991d2.png)

**Comment by Kordishal** [comment]
This means that you have an invalid connection in your plots. Please unlink your plots via the Subplot prompt field until the page displays again.

**Comment by Kordishal** [comment]
The campaign plot page displays the master plots and their children. You define children by selecting the parent in a plot article under the templates additional prompts. So you have to open the plot articles that are linked on the campaign plot page and undo this connection until the page loads again. 

Open the below:
![image](https://user-images.githubusercontent.com/14262536/197149994-54344bc3-182b-4b5a-8898-3f7fbea1f715.png)

Then remove the parent plot connections:
![image](https://user-images.githubusercontent.com/14262536/197150151-c2c38934-39b4-4841-bafb-228fc3c8a46c.png)
