### ISSUE TITLE
Campaign Cover Image “tileing” even at suggested ratios

### ISSUE THREAD

**Issue by GlennCauthon** [worldanvil/worldanvil-bug-tracker#1317]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: GlennCauthon

**World / Campaign / RPG Character / Manuscript Title**: Tyranny of Dragons 

**Feature**: campaign cover image

**Operating System**: Windows 10

**Browser**: Chrome, Firefox, Brave, and Edge

**Device / Device Model**: Desktop PC

**Related URLS** (To public & visible pages, add screenshots otherwise):
https://www.worldanvil.com/epic/6APOuuTfD6tZcLSvOO8PD99hCGyj0R

**Describe the Issue**
Uploading an image for a campaign results in the image being tiled even when uploaded at the recommended 1600x400 pixel size and 4:1 aspect ratio. The recommend ratio splits the image approximately in half.

**To Reproduce**
1. Go to Your Campaigns
2. Click on Create a new Campaign
3. Upload a Cover Image
4. Save
5. Click View Campaign Homepage if you're not there already.
Alternatively, for step 2 you could instead click on an existing campaign, Click Settings, Upload a Campaign Cover Image, Save Changes, and finally View Campaign Homepage 

**Expected behavior**
When uploaded at the recommended aspect ratio the cover image fits in the default area without tiling. (What I mean is, though I realize it will tile some when you scroll down, but the initial default I wouldn't expect to display tiling, splitting the image in half.)

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

![2022-10-24](https://user-images.githubusercontent.com/63131231/197669049-2d8d2125-457c-4763-bb5f-7e23434ddbab.png)

Edit: 
Apologies for missing the requested format. I first filled this out from my phone which didn't show the above template for some reason, which is why I didn't fill it out in that manner. I only saw it now when reviewing the other issues on my PC and clicking "New issue" to see if something different popped up. Narrative below left for reference.
Hey all. I have a small issue/bug that’s been driving me crazy so I’m posting here in the hope of helping to squash a small bug. I’ve created a new campaign in WA and added a campaign cover image and can’t seem to get it to come out without chopping off the top and putting it on the bottom. I don’t just mean “tileing,” though it’s that too. For example, with one resolution I tried (1920x720) it seemed like it would have fit, but for some reason the top of the image was chopped off and the corresponding section was tiled on the bottom, even though it looked as if the section would have fit on top without any tileing if it was left as is (or perhaps just very close to it. It’s hard to be 100% sure, but it looked like it.) I’ve tried editing the photo to use a bunch of different sized and have gotten closer, but haven’t got it to just fit. This includes using the recommended 4:1 ratio whether or not I used 1920x480 or the recommended 1600x400. At that ratio it seemed to cut it more-or-less in the middle and tiled it. 
Sorry if that’s a bit long, but when I have to troubleshoot or debug something I always find it helpful to have the most detailed notes possible. 🙂 And I hope it all makes sense and is clear. Thanks for an awesome product!
Also, I looked through the guide linked below for help, and mentioned the issue in a comment there. Sage Ondo said he has the same issue when trying and requested I make a big report here and gave the link to this GitHub in his comment. https://www.worldanvil.com/w/WorldAnvilCodex/a/images
I’ve also tried it in Safari and Firefox, but that didn’t seem to change it.

**Comment by GlennCauthon** [comment]
Since this is my first time submitting something like this, it’s entirely possible, perhaps likely, that I left out useful information. If so, please let me know and I’ll try to respond as soon as practical. Thanks!
World Anvil Username is the same as this one if it’s needed. GlennCauthon

**Comment by GlennCauthon** [comment]
Initial request now edited to fit the format. Original was filled out on my mobile which didn't display the template for some reason. Please let me know if there's anything I can do to improve the request or more information needed.

**Comment by iamromeo** [comment]
Fixed - will be deployed within the next 72 hours
