### ISSUE TITLE
Custom content in right column not deleting

### ISSUE THREAD

**Issue by Deleyna** [worldanvil/worldanvil-bug-tracker#1319]
Found this while troubleshooting #1318 - I'm 90% sure this wasn't here before and I'm baffled...

**World Anvil Username**: Deleyna

**World / Campaign / RPG Character / Manuscript Title**: 
https://www.worldanvil.com/w/spaceport-deleyna  <- homepage

**Feature**: 
Can't remove custom content from right hand sidebar

**Operating System**:
Windows 10

**Browser**:
Tested in Firefox and Chrome (Also tried logging out and back in again, and private browser window...just in case it was an extension...)

**Device / Device Model**:
desktop PC

**Related URLS** (To public & visible pages, add screenshots otherwise):
https://www.worldanvil.com/w/spaceport-deleyna

**Describe the Issue**
While testing the Map issue, I added the map in as custom content on the right hand column of the home page. Worked fine. Now I want to remove it. THAT doesn't seem to work.

**To Reproduce**
1. Go to world -> settings -> Homepage -> custom content -- I added [map:86aadad2-2e1b-453f-be51-06d169ca8040] in the right column, saved. This works fine.
2. Go back in and delete that code. Click save.
3. Go to front end... map is still there. ???? Stare at screen in confusion.
4. Go to world -> settings -> Homepage -> custom content -- delete code from right hand column. Push save. Note that changes have been saved via page refresh.
5. Go back to Homepage -> custom content -- note the code is still there...

**Expected behavior**
I expected it to go away.

**Screenshots**

![Map-bug-2](https://user-images.githubusercontent.com/4100767/197423864-7a799fb5-303e-4ef2-9e26-1041dbba860a.jpg)

(Yes, I'm sad because the one I want to work doesn't, and the one I want to go away won't. LOL. I'm going to build a new map, so this isn't urgent, but wanted to document it...)

Mental note to self: do not do something stupid like deleting map image...

**Comment by iamromeo** [comment]
The not going away is probably an issue with the WYSIWYG @Deleyna  - change, even temporarily to Euclid and try again (let me know if that resolved it) 
The issue with the map cover is another thing - I am not sure how to fix but will investigate.

**Comment by Deleyna** [comment]
YES! That was it. Perfect!

So... is this still a bug? Mine is resolved!

**Comment by iamromeo** [comment]
I am keeping this open until I add this as a future fix (for the map without preview image)
