### ISSUE TITLE
anonymous vote on features despite leaving the option unchecked

### ISSUE THREAD

**Issue by kjanowski** [worldanvil/worldanvil-bug-tracker#132]
**World Anvil Username**: Kaleidechse

**Feature**: Feature Suggestion Board

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/community/voting/suggestion/a98abfae-e53d-419e-aa52-93da5c7d3dfb/view
https://www.worldanvil.com/community/voting/suggestion/2b7646ad-3e6e-4ca9-99a2-df00e60f8da8/view

**Describe the Issue**
I just voted on two feature suggestions, but left the checkbox empty which said "Check this so your username will not be displayed on your vote." Nevertheless, my name is made anonymous in the list of votes below. One of my votes has a comment attached, the other does not, but both are affected.

**To Reproduce**
1. Go to a feature suggestion at https://www.worldanvil.com/community/voting/
2. Leave the checkbox for anonymous voting unchecked (default state)
3. Add a comment to identify your vote later 
4. Vote on the feature
5. Look for your comment and compare the name

**Expected behavior**
I expected the vote to be attached to my user name, because the checkbox looked unchecked in its default state and the anonymous vote is described as optional.

**Comment by kjanowski** [comment]
Update: Even when I explicitly check and uncheck the checkbox before voting, the list shows the "a (adjective) (species)" pseudonym instead of my user name.

**Comment by iamromeo** [comment]
Fixed
