### ISSUE TITLE
Timeline events do not properly respect Era Start/Stop

### ISSUE THREAD

**Issue by SlendyMcTendies** [worldanvil/worldanvil-bug-tracker#1320]
**World Anvil Username**: SlendyMcTendies

**World / Campaign / RPG Character / Manuscript Title**: (Not Relevant)

**Feature**: Timelines

**Operating System**: Windows 10

**Browser**: Brave

**Device / Device Model**: (Irrelevant)

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
If a Historical event starts in one Era and ends in a following Era, the end date will not be properly annotated with the Era's abbreviation. 

For example, "Era A" (with abbreviation "EA") is from year 0 to 100, and "Era B" (with abbreviation "EB") is from year 101 to 200.

"Event" starts in 99, but ends in 101. The timeline will read "Event started in 99 EA and ended in 101 EA". But this is wrong. It should say "Event started in 99 EA and ended in 1 EB".

**To Reproduce**
1. Create a timeline with two or more Eras
2. Create an event that has a start date in one Era and ends in any following Eras

**Expected behavior**
The ending date should be noted with the proper year and abbreviation respective to the Era

**Screenshots**
![Era A](https://user-images.githubusercontent.com/19656239/197598789-ea179d96-b478-4e2b-80d1-721ab5220fbb.PNG)

![Era B](https://user-images.githubusercontent.com/19656239/197598791-507469b7-efea-4b30-9f4d-91eac184a294.PNG)

![Wrong Years](https://user-images.githubusercontent.com/19656239/197598793-bcc24d54-5f13-4f56-9a44-11f0723435af.PNG)

![Year Settings](https://user-images.githubusercontent.com/19656239/197598795-f1464135-7c0b-4bf4-af6e-7fd9f1cf8b25.PNG)

**Comment by iamromeo** [comment]
I am sorry but if I am reading this right your event begins and ends before the first of the 2 eras even starts - can you please elaborate

**Comment by Kordishal** [comment]
The first era AWD goes from 2'001 - 3'000. 
The second era AoT goes from 3'001 - 4'000.

The event starts in 2'999 and ends in 3'011. So it should theoretically display the first date as 999 AWD (which is correct) and the second date as 10 AoT. The second date shows as 1011 AWD instead. So essentially the second date doesn't check if its in a different era.

**Comment by iamromeo** [comment]
Events cannot currently extended between the boundaries of an era. This was never a feature which is the reason that this occurs.

**Comment by SlendyMcTendies** [comment]
Ok... will this be a future "feature"? Things don't just "stop happening" at the end of an era, so it makes no sense that events can't extend into another era.

**Comment by SlendyMcTendies** [comment]
Cool, thanks for looking into it.
