### ISSUE TITLE
Calendar ID shows up red in edit and calendar is invisible in view, Chat support suggested bug report

### ISSUE THREAD

**Issue by OldZean** [worldanvil/worldanvil-bug-tracker#1321]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: OldZean

**World / Campaign / RPG Character / Manuscript Title**: Terraria / Article "Kalender"

**Feature**: Calendar

**Operating System**: Win 11 Pro 21H2

**Browser**: 106.0.1 (64-Bit) firefox

**Device / Device Model**:

**Related URLS** (To public & visible pages, add screenshots otherwise): https://www.worldanvil.com/w/terraria-oldzean/a/kalender-article

**Describe the Issue**
I want to display the calendar I made, manual said post ID anywhere, posted in article, ID shows up red, no calendar in preview or view

**To Reproduce**

**Expected behavior**
Calendar visible in article 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![2022-10-25 11_34_34-OneNote for Windows 10](https://user-images.githubusercontent.com/116636856/197741586-27f9ce79-3f71-4c3d-9801-8dd46fe1bae4.png)
![2022-10-25 11_36_27-OneNote for Windows 10](https://user-images.githubusercontent.com/116636856/197741589-469c13b3-be55-412b-9c62-546792a63912.png)

**Comment by OldZean** [comment]
thanks you. it now looks like this:
"edit calendar showed up but no calendar
![2022-10-26 21_05_40-Editing Kalender _ World Anvil – Mozilla Firefox](https://user-images.githubusercontent.com/116636856/198114523-8a128d20-e54d-461f-8509-7d0544716fde.png)
![2022-10-26 21_03_51-Kalender in Terraria _ World Anvil – Mozilla Firefox](https://user-images.githubusercontent.com/116636856/198114531-e594ec73-0d01-4fdb-badf-c52e7046d82a.png)

**Comment by Kordishal** [comment]
when you open the calendar editor, does it display the preview calendar at the bottom?

**Comment by OldZean** [comment]
no. output is empty

![2022-10-26 21_38_27-Edit Unification Calendar _ World Anvil – Mozilla Firefox](https://user-images.githubusercontent.com/116636856/198120615-8035c3d4-ae9e-41ff-9edd-ada50185a944.png)

**Comment by Kordishal** [comment]
then there is an issue with the calendar you've created. Most likely an event contains some kind of character or issue that the system cannot render.

Did you put a lot of work into it? The easiest would be to just start over. Otherwise you'd have to use the JSON code to find the issue and fix it and then reimport that same JSON output.

The calendar is no longer developed and will be replaced eventually, so this issue won't be resolved.

If you have any questions you can continue to ask them here. If you post the full text content of the JSON field I might be able to help you track down the issue in the calendar.

**Comment by OldZean** [comment]
`{"notes":[],"calendarVersion":"0.8.3","eventsdata":{"importantDates":[],"countOfUniqueEvents":0,"countOfDaysWithEvents":0,"countOfTotalEvents":0},"name":"test","description":"","monthOffset":"","startAtZero":false,"defaultYear":1,"showDays":false,"days":["ipsum","lorem"],"daysPerWeek":2,"months":[],"monthsPerYear":0,"celestials":[],"celestialBodyCount":0}`

i made a second test calendar same result

**Comment by Kordishal** [comment]
You didn't add any week days or months to it. So its not displaying anything!

![image](https://user-images.githubusercontent.com/14262536/198126436-0fabdb71-ee4f-453d-adf5-eacecc288f54.png)

Click on the Weekday and Month bars to see that add button!

**Comment by OldZean** [comment]
oh....i had days. no months.
thanks you. now I understand how this works ^^

sorry for the bother
