### ISSUE TITLE
Cyberpunk Red Dark Theme

### ISSUE THREAD

**Issue by RiPCorD5A1** [worldanvil/worldanvil-bug-tracker#1322]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**Ripcord5a1**:

**Cyberpunk / Adventurers of NIght City 2020 Maybe / Angel / Manuscript Title**:

**Character Sheet Theme**: 

**Windows 11**:

**Opera GX**:

**Computer Desktop**:

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
Cannot See due to white text on yellow background.

**To Reproduce**
1. Go to Character sheet
2. Click on Dark theme
3. Scroll down to Skills

**Expected behavior**
To be able to see

**Screenshots**
![Blind](https://user-images.githubusercontent.com/59139849/197928046-3a0b9966-8964-4859-814a-c50261239511.png)

If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
This is one for the creator of the sheet @Tillerz can you have a look?

**Comment by Tillerz** [comment]
Fixed.
