### ISSUE TITLE
Adding Historical Entry in Timeline Causes Visual Glitch

### ISSUE THREAD

**Issue by RikThunder** [worldanvil/worldanvil-bug-tracker#1323]
**World Anvil Username**: Rik Thunder

**World / Campaign / RPG Character / Manuscript Title**: Mystik / Timeline 3

**Feature**: Timelines

**Operating System**: Windows 10

**Browser**: Brave

**Device / Device Model**: A83AEBE9-ACE3-4E69-B3D7-F2B731E5C074

**Related URLS** (To public & visible pages, add screenshots otherwise): https://www.worldanvil.com/world/timeline/73f1b93a-ea4b-4fe0-9fae-ae7fdd45e94b/edit

**Describe the Issue**
After adding a historical Entry in Timeline 3, it seems like the menu with the buttons "View Timeline" and "Create a new Historical Entry" on the right got transported to the end on the page if you scroll down, and it only partially displayed. Furthermore, the text which is was supposed to be inside the entry in on the timeline, but without any formatting. Looking into the HTML code, I get a lot of errors which I include as screenshots here. Not sure if related. The issue is, I have no idea how to reproduce it, since at any other instance, adding historical entries worked fine!

**To Reproduce**
1. Go to the Timelines tab
2. Click on "Edit" Timeline 3 - Mystik
3. Scroll all the way down

**Expected behavior**
Normally the Menu on the far down should be topside the page on the right and fully visible. Also, the Historical entry text should be in the timeline inside a little box like the rest of them with an icon and everything, and not just naked text. 

**Screenshots**
![image](https://user-images.githubusercontent.com/27198576/198134476-a7cce377-60c1-445b-b6b1-55bacbfed34f.png)
![image](https://user-images.githubusercontent.com/27198576/198134585-8fd84e68-1d24-43de-bbc6-0bf491c5b9cc.png)
![image](https://user-images.githubusercontent.com/27198576/198134656-faebf052-cc67-43a4-bd60-b2221fb4ea52.png)
![image](https://user-images.githubusercontent.com/27198576/198134736-f2e45568-b2be-444f-bd9f-4e8bc32d725e.png)
![image](https://user-images.githubusercontent.com/27198576/198135082-a2d0acf4-842f-4326-8022-7053cd62d894.png)
![image](https://user-images.githubusercontent.com/27198576/198135129-44c28268-2db3-42d9-9d7b-41fc93f73274.png)
![image](https://user-images.githubusercontent.com/27198576/198135164-393f55c1-5310-4b25-8eae-729c008b7b0b.png)
![image](https://user-images.githubusercontent.com/27198576/198135236-6c8ae294-caa3-42ad-99b8-10755e43fd12.png)
![image](https://user-images.githubusercontent.com/27198576/198135297-b51bc586-2397-4951-a173-7b97af60d9ae.png)

**Comment by Kordishal** [comment]
Hi

This is most likely an issue with an unclosed BBCode tag. Tags that are unclosed like [in], [center], [row] and a few more will cause the layout to break due to how they are translated.

Please check if there are any of this in the descriptions of your events. Reply here if that is or is not the case!
