### ISSUE TITLE
Historical Entry in a Timelines Glitches

### ISSUE THREAD

**Issue by RikThunder** [worldanvil/worldanvil-bug-tracker#1324]
**World Anvil Username**: Rik Thunder

**World / Campaign / RPG Character / Manuscript Title**: Mystik / Timeline 3

**Feature**: Timelines

**Operating System**: Windows 10

**Browser**: Brave

**Device / Device Model**: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz   3.30 GHz

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
The entire Menu drops from the top right of the page to the lowest part of the page and the part after the "-" will be displayed on the timeline in pure text. I don't think this is intended. However, delete the line break and the "-" and the problem is solved. Just an annoying bug if one wants to make bullet points with "-" for any reason. 

**To Reproduce**
1. Go to any historical Entry on a timeline.
2. Within the SHORT DESCRIPTION / EXCERPT create a line break and type a "-"
3. Save changes. 
4. Go to the timeline, scroll down and see error

**Expected behavior**
The entire Menu drops from the top right of the page to the lowest part of the page and the part after the "-" will be displayed on the timeline in pure text. I don't think this is intended. 

**Screenshots**
![image](https://user-images.githubusercontent.com/27198576/198221957-aae34ae2-be82-485d-a6ec-d0ea53210da8.png)
![image](https://user-images.githubusercontent.com/27198576/198222054-7454a919-a22b-42b9-a557-2b407a8b6a9e.png)
![image](https://user-images.githubusercontent.com/27198576/198222180-c49b254a-9f38-4cef-b2d9-a205a8d153d0.png)

**Comment by Kordishal** [comment]
That is the beginning of a list for the content renderer. Lists break timelines because they are lists themselves. Do not use a `-` sign at the beginning of a line. Probably just adding a space before the `-` will fix it.
