### ISSUE TITLE
Slower Site Loadpages when using whitelabel domains

### ISSUE THREAD

**Issue by SigmaXD** [worldanvil/worldanvil-bug-tracker#1325]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: WriterGreg

**World / Campaign / RPG Character / Manuscript Title**: https://www.worldanvil.com/w/worldcraft-and-wordmancy-writergreg

**Feature**: Site Load Times

**Operating System**: Windows 10

**Browser**: Version 106.0.5249.121 (Official Build) (64-bit)

**Device / Device Model**: Laptop

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
I was doing some comparative tests using https://www.webpagetest.org/ comparing the difference between the custom domain and the direct WA site. Has there been any discussion on this difference?

There's an extra 8 seconds before the page BEGINS to render. Also, the custom domain takes 7x longer (2.298s to 15.263s).

Here's the detailed test links: 
Custom Domain: https://www.webpagetest.org/result/221027_BiDcE5_X08/
Native Domain: https://www.webpagetest.org/result/221027_AiDcV6_WZQ/

**To Reproduce**
1: go to https://www.webpagetest.org/
2: run reports on the two domains that point to the same worldanvil world
- https://school.writergreg.com/
- https://www.worldanvil.com/w/worldcraft-and-wordmancy-writergreg
3: compare

**Expected behavior**

The site loading time would have comparable times. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![WA_CustomDomain_WebPageTest Result](https://user-images.githubusercontent.com/9139852/198644444-304dfd62-5260-47f6-b396-c550c8aa3fe3.png)
![WA_NativeDomain_WebPageTest Result](https://user-images.githubusercontent.com/9139852/198644493-b53879dd-2d71-45e1-987b-994ad4d0b238.png)

**Comment by iamromeo** [comment]
This is a known issue and already in the pipeline
