### ISSUE TITLE
Fabula Ultima

### ISSUE THREAD

**Issue by thekmank** [worldanvil/worldanvil-bug-tracker#1327]
**Full Name (RPG SYSTEM)**: Fabula Ultima TTJRPG
**List Name** (Name under which it should be listed on World Anvil): Fabula Ultima
**World Anvil Username**: TheKmank

**Website**: https://www.needgames.it/fabula-ultima-en/#core

**Logo Image Link**: https://www.needgames.it/wp-content/uploads/2021/06/fu-logo-trasp.png

**Logo Usage Terms (URL)**: Unable to locate

Note: Similar to the Ryuutama rpg but distinct enough that it would require it's own entry.

**Comment by iamromeo** [comment]
Added :)
