### ISSUE TITLE
Cyberpunk Red Character Sheet, Armor section undercooked

### ISSUE THREAD

**Issue by RiPCorD5A1** [worldanvil/worldanvil-bug-tracker#1328]
Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!

World Anvil Username: Ripcord5a1

World / Campaign / RPG Character / Manuscript Title: Cyberpunk Red

Feature: World Anvil Character sheet, armor section. 

Operating System: Win 11

Browser: Chrome/Opera GX

Device / Device Model: Laptop/Personal Computer

Describe the Issue: The Armor Section of the cyberpunk red character sheet is far to simple. The games mechanics allow for; Armor upgrading, armor invention, armor reinforcement, armor repairing, armor destruction, and armor ablation. There is no way to, add a custom armor, increase/decrease SP value, add a note to armor, add a custom armor name.

**To Reproduce**
1. Go to character sheet
2. Click on armor dropdown
3. Read Cyberpunk Red player handbook. PG. 96-97, 147-149, 184-186

**Expected behavior**
For the armor section to be like the weapon section

**Comment by Kordishal** [comment]
Hi,

The statblock templates are created by the community for the community. Furthermore this isn't really a bug in the statblock its just not as detailed as you'd like. Please contact the creator of the statblock template to voice your concerns or make your own adjustments by copying the template to your own studio.
