### ISSUE TITLE
Deleting World - Error 404

### ISSUE THREAD

**Issue by melgxs** [worldanvil/worldanvil-bug-tracker#1329]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Melgxs

**World / Campaign / RPG Character / Manuscript Title**: Earth

**Browser**: Opera

**Device / Device Model**: PC

**Related URLS** (To public & visible pages, add screenshots otherwise): [world/7258878b-c96a-4aeb-a86f-2e6b43d1bc27/summary](https://www.worldanvil.com/world/7258878b-c96a-4aeb-a86f-2e6b43d1bc27/summary) https://www.worldanvil.com/world/7258878b-c96a-4aeb-a86f-2e6b43d1bc27/delete

**Describe the Issue**
I'm trying to delete this World a few times now and is just not working. I deleted the campaign, characters and even all articles manually, but still goes to error 404. I tried to delete on other browsers, but the error is the same :/

**To Reproduce**
1. Go to '[...](https://www.worldanvil.com/world/7258878b-c96a-4aeb-a86f-2e6b43d1bc27/edit)'
2. Click on 'DELETE WORLD'
3. Scroll down to 'DELETE THIS WORLD'

**Expected behavior**
Delete the World

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/117128541/199130829-0ca99d61-fcc9-47f6-a68c-4aed735687d3.png)

**Comment by Kordishal** [comment]
Hi,

The world likely refuses to delete because there are resources present it can't delete. Do any of the following steps that are applicable and then the world should delete:

- Delete any attached campaigns.
- Delete any attached manuscripts.
- Expel any RPG Characters from the world.
- Remove all authors and subscribers from the world.
- Remove subscriber groups from the world.
