### ISSUE TITLE
Moving article order in category not working

### ISSUE THREAD

**Issue by kiwibrowncoat** [worldanvil/worldanvil-bug-tracker#133]
**World Anvil Username**: kiwibrowncoat

**World / Campaign / RPG Character / Manuscript Title**: Fel'Wind

**Feature**: World category

**Related URLS** (To public & visible pages add screenshots otherwise): 

**Describe the Issue**
When I try and move an article to change the order within a category, it does not stay there. I am wanting the order of articles to be alphabetical but the alphabetise button doesn't work either.  The only option that works is to assign number weights to the articles one by one which is not ideal as there are a lot of articles in the category and there are new articles being made over time that will muck up the numbering order.

**To Reproduce**
1. Go to Articles and Categories
2. Move an article in the list upwards or downwards
3. The loading bar disappears before the end and before it says article moved
4. Refresh page and article is back where it was.

**Expected behavior**
The article should have moved to the new location

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Bug report 1](https://user-images.githubusercontent.com/82067201/113795810-d5f40500-97a1-11eb-81a1-08ae25c14ef2.png)
![bug report 2](https://user-images.githubusercontent.com/82067201/113796008-48fd7b80-97a2-11eb-9b69-3b1573c09ae8.png)
![bug report 3](https://user-images.githubusercontent.com/82067201/113796055-73e7cf80-97a2-11eb-8126-1160f0374951.png)

**Comment by iamromeo** [comment]
Hello @kiwibrowncoat I cannot be sure but this category looks like it has more than 20 articles on the same level? Is this the case?

**Comment by kiwibrowncoat** [comment]
@iamromeo Correct. There's well over 20 in the category, probably closer to 50 or more. I had this issue a while back and found that if I just moved articles up five steps at a time and waited for the 'article moved' message to appear, it would work, but now the progress bar doesn't even complete at all.

**Comment by iamromeo** [comment]
Categories should not have more than 20 articles. You can still have them but drag and drop would certainly not work. 
You can use still the numeric weight system.
