### ISSUE TITLE
all writing i have done is invisible in half of the stylist templates even though i change color :D

### ISSUE THREAD

**Issue by Gazoomy** [worldanvil/worldanvil-bug-tracker#1331]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**:

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 

**Operating System**:

**Browser**:

**Device / Device Model**:

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Hi, you will have to give us more information for us to be able to help you. It is however, most likely an issue with some CSS. You could also ask for help with this in the Discord servers css help channel.

Otherwise actually fill in the template provided for these reports. Can't help you just based on that title.

**Comment by Gazoomy** [comment]
No, I see!.. bit of message of annoyance, I apologize. The form is incredibly long and tedious though when u’r in a writing state of mind.. 😃 thanks for answer anyways!  Sent from Mail for Windows From: Jonas WaeberSent: 2. november 2022 18:38To: worldanvil/worldanvil-bug-trackerCc: Gazoomy; AuthorSubject: Re: [worldanvil/worldanvil-bug-tracker] all writing i have done is invisible in half of the stylist templates even though i change color :D (Issue #1331) Hi, you will have to give us more information for us to be able to help you. It is however, most likely an issue with some CSS. You could also ask for help with this in the Discord servers css help channel.Otherwise actually fill in the template provided for these reports. Can't help you just based on that title.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Kordishal** [comment]
Well if you want some help you will have to provide at least your World Anvil username and a link to the pages that are making problems. Invisible text does usually mean that the text is the same colour as the background. Its just there is several reasons why that could be.

Did you change the text colour in your styling setting? Did you add some custom CSS to change the colour?

**Comment by Gazoomy** [comment]
I figured out what I wanted!. Thank you very much for your time! Hope u have a good one homie 😃 Ludvig. Sent from Mail for Windows From: Jonas WaeberSent: 2. november 2022 21:45To: worldanvil/worldanvil-bug-trackerCc: Gazoomy; AuthorSubject: Re: [worldanvil/worldanvil-bug-tracker] all writing i have done is invisible in half of the stylist templates even though i change color :D (Issue #1331) Well if you want some help you will have to provide at least your World Anvil username and a link to the pages that are making problems. Invisible text does usually mean that the text is the same colour as the background. Its just there is several reasons why that could be.Did you change the text colour in your styling setting? Did you add some custom CSS to change the colour?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
