### ISSUE TITLE
Historical Entry Military Icons Aren't Consistent with Other Types of Icons

### ISSUE THREAD

**Issue by BeanMcDanny** [worldanvil/worldanvil-bug-tracker#1332]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**:
BeanMcDanny
**World / Campaign / RPG Character / Manuscript Title**:
Alkara (but I had someone on the Discord try it also, and it does it in their world too, so it's not world-specific)
**Feature**: 
Historical Entry Military Icons
**Operating System**:
Windows 11
**Browser**:
Google Chrome
**Device / Device Model**:
HP Laptop/???
**Related URLS** (To public & visible pages, add screenshots otherwise):
https://www.worldanvil.com/w/alkara-beanmcdanny/t/history-of-alkara-timeline
**Describe the Issue**
When creating Historical Events for Timelines, you may choose the type of event. When any under the military section are selected, the resulting icon when viewing it in the Timeline is noticeably smaller compared to other event-type icons and appears in the upper left rather than the center of the circle. Pictures below are of the military icons and another type for comparison.
**To Reproduce**
1. In Dashboard, go to Timelines -> List of All Events Under Linear Timelines -> Create New Historical Entry
2. In the prompts, set Type as Military Action, Military: War, Military: Skirmish (and possibly even Military: Battle, but I haven't tested that one).
3. Click Create Historical Event.
4. View it in the Timeline.

**Expected behavior**
The icon styling should be consistent with the other icons (the same size and appearing in the same area of the circle).
**Screenshots**
![ex 1](https://user-images.githubusercontent.com/117298097/199535920-29954ac7-8771-4cd3-a5ab-1f4a98917555.png)
![ex 2](https://user-images.githubusercontent.com/117298097/199535945-26fd178c-d8b7-47dd-8a18-5b8fdcf1c0e6.png)

**Comment by katerinach** [comment]
The icon styling has been fixed for the Military type Historical Entries.

**Comment by BeanMcDanny** [comment]
Thank you! You guys are great!
