### ISSUE TITLE
World Griamoris not accessible via link or listed in Your Worlds tab.

### ISSUE THREAD

**Issue by qSickBoss** [worldanvil/worldanvil-bug-tracker#1333]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: qSick

**World / Campaign / RPG Character / Manuscript Title**: Griamoris

**Feature**: World went complete 404 style

**Operating System**: Win10

**Browser**: Chrome

**Device / Device Model**: PC

**Related URLS** (To public & visible pages, add screenshots otherwise): cannot insert link as this world is completely gone, just account link then: https://www.worldanvil.com/author/qSick

**Describe the Issue**
So I had this world of mine which I am working on for last 2 years. Last time I edited something was about a week ago. Last time I used WorldAnvil was at October 30th at my friend place where I showed him a few articles from his PC via logging to my accout. After that I definitely logged out so there is no way someone deleted my world.

Today November 3th I tried to load my world at WA and encountered error 404. Moreover, this world dissappeared form "your worlds" list and every other place where I had a possibility to access it.

**To Reproduce**
Login into account
Proceed to cry

**Expected behavior**
Access my world ofc 

**Screenshots**
Just a screenshot of an article that was liked by other user at 6/12/21
![404](https://user-images.githubusercontent.com/117392372/199813705-25f57001-17fd-420e-ba9c-80ad15fa8f53.jpg)

**Comment by qSickBoss** [comment]
link for that world: https://www.worldanvil.com/w/griamoris-qsick

**Comment by iamromeo** [comment]
Hello there - this world was deleted, this is the reason it does not appear on your list and it is not accessible

**Comment by qSickBoss** [comment]
> Hello there - this world was deleted, this is the reason it does not appear on your list and it is not accessible

That is very interesting considering nobody could delete it since nobody has access to my account.
Even so, is there any option to restore my data, I dont care if it will lose all the editing, pictures, css etc, I just need my texts back at least. That is my 2-year long work and I`m not gonna roll with everything just disappearing.

Is there an option to back-track when and from where was launched a session when world was deleted?
Does ur site have some sort of back-up cloud copy from which my data can be restored?

Like anything will do, I just need to get it back....

**Comment by iamromeo** [comment]
Hello @qSickBoss first of all there is no way for a world to be deleted by the system - it is literally not coded and it requires your encoded action to do so - so whoever deleted your world had access with your credentials. 

I will see what I can do about your world right now and get back to you on this thread with any updates

**Comment by iamromeo** [comment]
**GOOD NEWS** your world was still on the final deletion pipeline. There was no loss of data. 

For your information your world was deleted at **2022-10-30 11:55:23 UTC** you might want to check who could have had access to your account at that time, this was not an internal action. 

Please keep in mind that this is a service that I can only provide to paying members, but it broke my heart to see 2 years of work lost. 

Happy worldbuilding! :)

**Comment by qSickBoss** [comment]
TYSM! I'm going to check right away who could do this at that time.

I would've definitely remained a paid member but since my country is banned from any transactions with EU banks I kinda lost every option to renew my subsciption. 

Bust still, huge thanks to you, idk what I would've done without your help!
