### ISSUE TITLE
Color BBCode active in Plato editor for Master accounts even though the BBCode is only usable by Grandmasters

### ISSUE THREAD

**Issue by Loink1** [worldanvil/worldanvil-bug-tracker#1334]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Loink

**World / Campaign / RPG Character / Manuscript Title**: Minecraftia(world)

**Feature**: Color text

**Operating System**: PC

**Browser**: Google Chrome

**Device / Device Model**: Unknown, all I know is I use Dell.

Urls
https://www.worldanvil.com/w/minecraftia-loink/a/end-poem-prose?preview=true

**Describe the Issue**
A clear and concise description of what the issue is.

When I was a Freeman account, I was unable to use color text. Hovering over the icon would have it tell me I needed to be a specific rank in order to use it. Then, I got Master rank and was able to click on the icon and use color text for my articles. However, the color doesn't show up anywhere except for the editing page, it defaults to black text on the actual article. I asked around on the WorldAnvil discord and found out that I shouldn't even be able to access color text until I have Grandmaster rank.

**To Reproduce**
1. Use a Master account
2. Go to an article's edit page
3. Highlight the chosen word/sentence/passage on an article to change its colors
4. Click on the color text icon
5. Choose color to change subject to
6. After successfully changing the color, View the article, the subject should have defaulted to black

Screenshots
![image](https://user-images.githubusercontent.com/103494999/199858767-bef1688c-3c8d-44fa-bd4f-2e5b4f33675a.png)
![image](https://user-images.githubusercontent.com/103494999/199858838-c2acc21f-2584-4bb4-8af8-804b3c5bca7b.png)

**Comment by iamromeo** [comment]
@Loink1 can you please show us the code that generates this?

**Comment by Loink1** [comment]
> @Loink1 can you please show us the code that generates this?

I'm not sure what you mean by code.

**Comment by Lyraine-Alei** [comment]
It is the [color: red] BBCode, from the buttons where one can type. I believe Loink uses the Plato Editor since they had mentioned being able to see the color changes on the edit side, despite being a rank other than a Grandmaster.

This was originally posted about in the #help channel on the discord

**Comment by Loink1** [comment]
I can confirm that I do use Plato Editor.

**Comment by Loink1** [comment]
I believe that because I use Plate Editor, I can't see the code, at least I don't know how to find it.

**Comment by Lyraine-Alei** [comment]
Click on the button that looks like >_ and that will open to Source Mode
and allow you to see the BBCode that the Plato Editor takes and displays as
it would appear in the article

**Comment by Loink1** [comment]
These are the two color codes I got:
#419dc1
#008e02

**Comment by iamromeo** [comment]
After discussions with the team this will not be addressed at this time
