### ISSUE TITLE
Linear Navigation Doesnt Work

### ISSUE THREAD

**Issue by Manlopjur** [worldanvil/worldanvil-bug-tracker#1336]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: erkhronistah

**World **: Ifa'ia

**Feature**:  Linear Navigation

**Operating System**: Windows 10

**Browser**: Opera GX

**Device / Device Model**: PC

**Related URLS** :

https://www.worldanvil.com/w/ifa-ia-erkhronistah/a/casa-starkjorn-organization

**Describe the Issue**
A clear and concise description of what the issue is.

Linear Navigation doesnt appear in editting an article, and the linear navigation previously set is not working

 
**To Reproduce**

**Expected behavior**

**Screenshots**
https://i.postimg.cc/gJv9MRFW/Captura.png
https://i.postimg.cc/3NBshTxf/Captura2.png

**Comment by Olaeradrik** [comment]
Same, Linear Naviguation not available in the article editor, and displays wrong information in article view.

![image](https://user-images.githubusercontent.com/36479234/200005127-db709010-c6ce-4c95-a334-0f4f3fdfde70.png)
![image](https://user-images.githubusercontent.com/36479234/200005289-a148c60e-0ab5-4d78-ba0b-2d3b79d75655.png)

**Comment by iamromeo** [comment]
Linear navigation is currently undergoing maintenance. It will probably be removed as a feature but we are still trying to fix it and find a viable solution.

**Comment by iamromeo** [comment]
Updates on this will be given on the DIscord Changelog channel as the issue develops

**Comment by woryk3112** [comment]
**World Anvil User Name**: Woryk

**World**: Hríonyr

**Feature**: Linear Navigation

**Operating System**: Windows 10

**Browser**: Firefox & Microsoft Edge

**Device / Device Model**: PC - HP

Hello. I've only come to realize just recently that the Linear Navigation is not available in my article editor, nor does it display the navigation links for any of my previously linked articles.

**URL**: https://www.worldanvil.com/w/hrionyr-woryk/a/ynellian-article

![image](https://user-images.githubusercontent.com/117616683/200219570-193f2297-aa8e-4b5e-b721-7b924b7d1ca8.png)
![image](https://user-images.githubusercontent.com/117616683/200219610-086b38b0-bc90-443e-9936-4b712abf0fdb.png)

**Comment by The-Toblin** [comment]
Just chiming in to say that Linear navigation is a rather vital portion of certain worlds. We can work around it using blocks and custom footers, but clear communication on this issue is vital so we can adapt our worlds swiftly.

**Comment by sclark9** [comment]
Also -- there's currently no way (as far as I can find) to remove the incorrectly formatted links/strings of characters where the previous/next articles would be linked because the linear navigation tab doesn't exist. It's not as severe as the actual issue of not having linear nav, but is a major eyesore.

**Comment by iamromeo** [comment]
@The-Toblin I am currently working on a resolution for this 
The first part will be the re-introduction of the links on the presentation and after that a new system to set the prev/next links from the editing interface.

**Comment by sclark9** [comment]
As of today, the links on the presentation of the articles work again.
