### ISSUE TITLE
An article with different author than myself is stuck in my world.

### ISSUE THREAD

**Issue by Nicholas12194** [worldanvil/worldanvil-bug-tracker#1339]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Brink DM

**World / Campaign / RPG Character / Manuscript Title**: Toril / Articles / World Atlas / Brink*
*Two articles are named Brink. One is authored by me (Brink DM), and the other is authored by Nicholas12194. The latter is the problem.

**Feature**: Article

**Operating System**: Windows 10

**Browser**: Google Chrome

**Device / Device Model**: PC

**Related URLS** (To public & visible pages, add screenshots otherwise): See screenshot

**Describe the Issue**
Somehow an article with an author other than the world owner (Nicholas12194) ended up in the world owned and authored by me (Brink DM), and now the article cannot be viewed, edited, or deleted. I am not a guild member and I have not added any other people to my world. Nicholas12194 is an alternative account of mine that I was using along with a friend. After we started our world we decided to make a new World Anvil account to work together on (Brink DM). We then began copying articles from the old world (on Nicholas12194's account) onto the new one (on Brink DM). After copying over a few articles, I noticed that one of the articles we had copied to Brink DM said it was authored by Nicholas12194, and that I now do not have permission to view or edit it. If I try to delete it, it reappears whenever I return to the World Atlas folder. As a note, I was signed in on Google Chrome using my Nicholas12194@gmail.com google account while I was signed in on World Anvil using my Brink DM account while I was copying articles. When I reached out on the support chat, Madeline told me that Nicholas12194@gmail.com was somehow associated with my Brink DM account, or at least my Tawk account.

**To Reproduce**
Steps to reproduce the behavior: Unknown action/cause.

**Expected behavior**
I had expected the article to be copied over cleanly, and that the article would have been considered to be authored by Brink DM rather than Nicholas12194. Also, if I am the world author, I should be able to view, edit, or delete any article in my world regardless of who authored the article.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

![Untitled](https://user-images.githubusercontent.com/58021378/200095291-9e2e5cd5-d747-4b71-b24e-43eabe03c8d1.png)

**Comment by iamromeo** [comment]
Hello @Nicholas12194 
There are two ways that this this can happened 
1. you had multiple tabs open on the same computer, one of you created the article and logged out with tabs still open and the other logged in and made any edit by mistake on the article
2. This is actually a HERO/CHARACTER in a campaign and should be there. 

Considering that you have no campaigns under your account this is probably the latter.

I can delete the article but I will need to have the **ID** or **presentation URL** of the article to do so

**Important Note:** Doing some investigating I have noticed an interesting daisy chain of users taking part in campaigns of each other which begs the question if this is a multi accounts issue or a big group of friends all using WA with a freeman account. - The accounts have been flagged. Please make sure you read the Terms of Service https://worldanvil.com/terms-of-service to prevent any account banning.

**Comment by Nicholas12194** [comment]
Thanks for getting back to me, Dimitris!

Since I was copying articles from one account to another, I believe the
first situation must have been how the problem occurred. To be clear, the
only reason I was doing this in the first place was to entirely migrate a
world from one account to the other. After the articles were copied to the
Brink DM account I removed them from the Nicholas12194 account.

This is the article link for the article that needs to be deleted. Is this
what you need in order to delete it?
@[Brink](settlement:00b17633-7569-4480-805e-2bc5c53aed11)

Thanks for the help

**Comment by iamromeo** [comment]
Yes that is what I needed - I will take care of it for you
