### ISSUE TITLE
404 error when trying to open a specific map

### ISSUE THREAD

**Issue by GwenStacy13** [worldanvil/worldanvil-bug-tracker#134]
Lightbringer

Comic Earth

**Feature**:  Map viewing/editing

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/world/map/0b6a784d-ae90-4a3b-a5bb-2778f1ce2a9a/edit

**Describe the Issue**
Whenever I try to view one particular map I get the 404 "You have reached the end of this world." message. Every other map in that world works when I go to view or edit it.

**To Reproduce**
1. Go to "Comic Earth."
2. Go to Maps.
3. Click to view or edit "The Lance" map.

**Expected behavior**
Go to maps, click on view or edit "the Lance" map, go into presentation or editing mode of "the Lance" map respectively.
![error](https://user-images.githubusercontent.com/82080378/113822569-97336000-974b-11eb-9434-442e3437247a.jpg)

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Hi, this is most likely caused by an error in a pin. We will not be able to debug this for you here. Please come to the [Discord](https://discord.com/invite/3XtQ8pC) for further assistance.
