### ISSUE TITLE
Disabling "WORLD ANVIL COMMUNITY SOCIAL FEATURES" doesn't work

### ISSUE THREAD

**Issue by Gabefm** [worldanvil/worldanvil-bug-tracker#1340]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**:Gabe Grimoire

**World / Campaign / RPG Character / Manuscript Title**: Agathok

**Feature**: WORLD ANVIL COMMUNITY SOCIAL FEATURES

**Operating System**: Windows

**Browser**: Opera GX

**Device / Device Model**: PC

**Related URLS** (To public & visible pages, add screenshots otherwise): 

**Describe the Issue**
Disabling/un-checking the "WORLD ANVIL COMMUNITY SOCIAL FEATURES" options doesn't actually disable it. I have a Master subscription too, if that matters.

**To Reproduce**
1. Go to Agathok world.
2. Click "Settings".
3. Click "Display".
4. See error (disabled yet still active).

**Expected behavior**
For the listed features (like "Discussion Board") to be disabled.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/58489493/200098314-7a2e66b2-fcf8-4acf-9e71-483b19c0fc32.png)
![image](https://user-images.githubusercontent.com/58489493/200098327-6d64f123-9de8-4315-b5dd-09841c50181e.png)
![image](https://user-images.githubusercontent.com/58489493/200098360-57e4d843-43bb-4294-8671-e9682ca1e794.png)

**Comment by Kordishal** [comment]
The reason is that this toggle is only available to Grandmasters and not to Masters. It is displayed because other options on that page are available to masters.
