### ISSUE TITLE
Mixed up Character Profiles

### ISSUE THREAD

**Issue by NovemberRain003** [worldanvil/worldanvil-bug-tracker#1341]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: November_Rain

**World / Campaign / RPG Character / Manuscript Title**: Quierccirq, Emory Acanthus, Vitskertur Fafnisbölvun

**Feature**: Character Profiles

**Operating System**: Linux

**Browser**: Chrome

**Device / Device Model**: Dell Latitude E5570

**Related URLS** (To public & visible pages, add screenshots otherwise): https://www.worldanvil.com/hero/36c33cad-33c9-4acb-b776-9b1b46b1270a, https://www.worldanvil.com/hero/3fc44295-040f-4a5a-91f5-68a833c93f99, https://www.worldanvil.com/hero/f8660ef0-9e6b-4cef-962c-3b8b2a33426c

**Describe the Issue**
A clear and concise description of what the issue is.
Sometimes, when I switch between character profiles, information from one profile (usually Quierccirq's) will populate for all three, or a mixture of information from 2 different profiles will appear. I might see Quierciirq's photo and name, but Emory's About info, for example. 

**To Reproduce**
1. Go to 'Switch to...'
2. Click on 'Quierciirq, Emory, or Vitskertur'
3. Click on the character's name with they eyeball icon

**Expected behavior**
I should see each character's respective photo, profile, and other information only, not a mixture of 2 or 3 characters.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Is this just a visual issue that resolves itself after you reload the page?

**Comment by iamromeo** [comment]
Closed due to inactivity
