### ISSUE TITLE
Article information isn't displaying

### ISSUE THREAD

**Issue by Graesonh** [worldanvil/worldanvil-bug-tracker#1342]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: GraeHawke

**World / Campaign / RPG Character / Manuscript Title**: Grimalon 

**Feature**: Arcticles

**Operating System**:

**Browser**:

**Device / Device Model**:

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue** When i or others view the world of grimalon we cant see any of the article information. i have checked to make sure it was both published and public
A clear and concise description of what the issue is.
When i or others view the world of grimalon we cant see any of the article information. i have checked to make sure it was both published and public
**To Reproduce**
1. Go to '...' view world
2. Click on '....' any article

**Expected behavior**
just want people to be able to see what ive written
**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
I see multiple articles with content. Can you link an example of an article that has content that is not visible?

**Comment by iamromeo** [comment]
@Graesonh can we please have a clarification on this?

**Comment by iamromeo** [comment]
Closed due to no response.
