### ISSUE TITLE
Custom URL Slow loading and interactivity. 

### ISSUE THREAD

**Issue by Tobuss** [worldanvil/worldanvil-bug-tracker#1345]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Tobus

**World / Campaign / RPG Character / Manuscript Title**: Solivity

**Feature**: Custom domain redirect

**Operating System**: Windows 10 and Android

**Browser**: Chrome and edge tested

**Device / Device Model**: Desktop and Google Pixel 

**Related URLS** (To public & visible pages, add screenshots otherwise): https://solivity.com domain is hosted through Google domains

**Describe the Issue**
Over the past few months my site was taking roughly 20 seconds to load and longer to open any codex folders to navigate to articles. There was no issue previously and there are still no issues if I get to my site through WA itself, I originalyl thought maybe my background image wasn't optimised, but upon check and even compressing the image it made no impact on the site loading times. The only thing that has made a significant impact is removing my Twitter embed on the homepage, this makes the page load up significantly faster but there is still a very noticable delay when trying to open any of the navigation folders. 

Comparison from before and after removing twitter embed. There is clearly something in the pipeline causing a delay in redirects from loading, and culling features from the page shouldn't be the solution to this.
![image](https://user-images.githubusercontent.com/33454600/200230066-0d1922a9-a8fa-403a-baff-8f7aeeba34c5.png)
![image](https://user-images.githubusercontent.com/33454600/200230407-8f431526-f9ef-4105-a295-9075b3e10c4c.png)

**To Reproduce**
1. Go to 'https://solivity.com'
2. Note the delayed load time.
3. Click on any folder and you will notice an obvious delay compared to the WA site.

**Expected behavior**
I'd expect loadtimes to be close to the native address, https://www.worldanvil.com/w/solivity.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Hello there @Tobuss  
Please do not resubmit issues :) 
We are aware of this issue and we already replied here #1282
