### ISSUE TITLE
Movine Map Pins

### ISSUE THREAD

**Issue by wanderwitch** [worldanvil/worldanvil-bug-tracker#1346]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: HarlieWitch

**World / Campaign / RPG Character / Manuscript Title**: Geirsa

**Feature**: Custom Map Pins

**Operating System**: WIn 10

**Browser**: Chrome

**Device / Device Model**: Custom

**Related URLS** (To public & visible pages, add screenshots otherwise): https://www.worldanvil.com/w/geirsa-harliewitch/map/47f38e84-8346-4e8a-a8f9-894e9aa01cc2

**Describe the Issue**
When the viewer of the page, tested by a public non user and myself, zooms the map out the custom map pins shift downwards where the normal map pins stay anchored

**To Reproduce**
1. go to map
2. zoom out
3. pins move

**Expected behavior**
The custom pins should act like the non custom pins and stay pinned when zooming in and out

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Hi, this is most likely due to how you set the anchor point of the pins. You can adjust the anchor points in the custom pin studio. I believe most if not all of the default pins have their anchor at the center bottom.
