### ISSUE TITLE
Requesting Ironsworn system

### ISSUE THREAD

**Issue by tnbprado** [worldanvil/worldanvil-bug-tracker#1348]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

Ironsworn
Ironsworn
**World Anvil Username**: tnbpr

**Website**: www.ironswornrpg.com

**Logo Image Link**: 

**Logo Usage Terms (URL)**:

**Comment by iamromeo** [comment]
Hey there @tnbprado 

Ironsworn and Ironsworn: Starforged is already in the list of systems

![image](https://user-images.githubusercontent.com/660175/200723095-db255105-ef59-4b9a-ba07-fb5cc370d104.png)
