### ISSUE TITLE
Category Panel does not show on Category Page/Book Cover Category

### ISSUE THREAD

**Issue by MetaverseRPN** [worldanvil/worldanvil-bug-tracker#1349]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**:SAGE_metaverse

**World / Campaign / RPG Character / Manuscript Title**:The Metaverse RPN

**Feature**: Category Page/World TOC

**Operating System**: Windows 11

**Browser**: Firefox

**Device / Device Model**: Dell G15

**Related URLS** (To public & visible pages, add screenshots otherwise):https://www.worldanvil.com/w/metaverserpn/c/the-eternal-codex-category, https://www.worldanvil.com/w/metaverserpn 

**Describe the Issue**
A clear and concise description of what the issue is. When viewing the Category page either via accessing the category page from the world Codex/TOC or via a Book Page Category, the Category Panel does not display for categories within the Category page you have accesed

**To Reproduce**
1. Go to Your World hompage
2. Click on either a Book Category or the arrow to view a Category page from the World TOC
3. Attempt to view a category inside the category page
4. See that the Category panel displaying the category description is not there.

**Expected behavior**
A clear and concise description of what you expected to happen. When I access a Category page via a Book Category, I would like to see the description of the categories within my Book Category

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/7560033/201177888-f09509e0-1559-42c6-87f3-44576b412f4a.png)

**Comment by iamromeo** [comment]
I am sorry but do not understand what the Category "Panel" is - can you please elaborate?

**Comment by iamromeo** [comment]
Reading above this is not a bug - this is a different type of display that does not exist.
