### ISSUE TITLE
Leader and Leader Title

### ISSUE THREAD

**Issue by Malireus** [worldanvil/worldanvil-bug-tracker#135]
**World Anvil Username**: N4th

**World / Campaign / RPG Character / Manuscript Title**: The Rippled Sea

**Feature**: Organization Template Specific Prompts & Connections

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
In the Organization Template Specific Prompts & Connections, the 'Leader' and 'Leader Title' links are the same (i.e. they link to a Character article).

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Organization'
3. Scroll down to 'Show Template Specific Prompts & Connections' and click on it.
4. Scroll down to 'Leader' and 'Leader Title.'

**Expected behavior**
I'm assuming that 'Leader Title' should link to a Title article and not to a Character article like 'Leader' does and should.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Thank you for reporting. It will be updated with the next code push :)

**Comment by Malireus** [comment]
Hi Dimitris,

Anytime! I'm a big fan of all the hard work you've put into WA, so I'm glad I could help.

Best,
James
________________________________
