### ISSUE TITLE
ability CHA doesn't save for weapon/attacks d&d5e1

### ISSUE THREAD

**Issue by teilyn** [worldanvil/worldanvil-bug-tracker#1351]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Teilyn

**World / Campaign / RPG Character / Manuscript Title**: Calliope/ Calliope 2022/ NPC: Bartrum Barlow Balthazar

**Feature**: Character sheet (2020) (Dungeons & Dragons 5e)

**Operating System**: Win 11 home version 10.0.22000 Build 22000

**Browser**: Chrome

**Device / Device Model**: Asus Laptop/ ROG Zephyrus G15

**Related URLS** (To public & visible pages, add screenshots otherwise): 
![image](https://user-images.githubusercontent.com/117956277/201237627-cd059ad6-c8f3-46b5-bfa0-0566208776fe.png)

**Describe the Issue**
A clear and concise description of what the issue is.

Every time i choose CHA as the ability modifier in the list of attacks /weapon panel shown in the screenshot, it reverts back to STR when i click save. All other ability modifiers save properly. 

**To Reproduce**
1. Go to 'Advanced tools>statblocks'
2. Click on 'Select a sheet type from the systems in (world name here)'
3. Scroll down to 'Character Sheet (2020) (Dungeons & Dragons 5e)'
4. Scroll down to Attacks /weapon, enter weapon name, choose CHA as ability modifier, input damage dice, then Save the sheet.
5. Scroll down to attacks /weapon and see that it reverted to STR

**Expected behavior**
I expected it to remain CHA, and add the CHA ability modifier into the attack roll feature when viewing the sheet
included screenshot of str selection by default, and of wisdom selection, then of wisdom selection saving/showing on the view page.
When choosing Charisma, it doesn't save, just reverts to strength.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/117956277/201238512-00bde3df-a088-4ccb-955b-5176c128ec59.png)
![image](https://user-images.githubusercontent.com/117956277/201238615-88d73bc9-0995-4347-a475-4c6106bcc163.png)
![image](https://user-images.githubusercontent.com/117956277/201238693-c0ef4e59-4875-49e4-b4f2-d5fe989782e8.png)

**Comment by iamromeo** [comment]
@Tillerz this is for you bud :)

**Comment by Tillerz** [comment]
Fixed. There was a typo in "charisma" in one location. :-(
