### ISSUE TITLE
Manuscript Default Interface Settings are user global?

### ISSUE THREAD

**Issue by Deleyna** [worldanvil/worldanvil-bug-tracker#1352]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Deleyna

**World / Campaign / RPG Character / Manuscript Title**:
All of my worlds, all of my manuscripts - Let's say: Spaceport world, The Spaceport - and - Classes world, How to Write a Novel in World Anvil

**Feature**: Manuscripts

**Operating System**: Windows 10

**Browser**: Firefox

**Device / Device Model**: Win 10 PC

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
When entering the default interface settings for a manuscript, it changes the default interface settings for all manuscripts in all worlds for that user.

**To Reproduce**
1. Go to Manuscripts and pick one
2. Click on Edit
3. Click on Manuscript title
4. On the right-hand side, change anything in the default interface settings and it will auto-save.
5. Go to any other world, any manuscript - the settings are now the same everywhere.

**Expected behavior**
I expected these default interface settings to be manuscript specific. If not that, at least world specific.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![WA-manuscript-settings](https://user-images.githubusercontent.com/4100767/201266957-66b24635-32bc-4fae-a8d0-53e515fd6b42.jpg)

NOTES:
This may not be a bug. It may be the intended behavior. In which case, maybe this is a feature request?

I've been doing a lot of work in this section of Manuscripts while working with my students and we tripped over this.

**Comment by iamromeo** [comment]
This is not a bug these are indeed the GLOBAL settings for Manuscripts. :) If you have a feature request for this please feel free to do so :)

**Comment by Deleyna** [comment]
Will do. Thanks!
