### ISSUE TITLE
Control-s in Manuscript produces an error

### ISSUE THREAD

**Issue by Deleyna** [worldanvil/worldanvil-bug-tracker#1353]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Deleyna

**World / Campaign / RPG Character / Manuscript Title**:
any of my manuscripts, but let's use World: Spaceport, Manuscript: The Spaceport

**Feature**: Manuscripts

**Operating System**: Windows 10

**Browser**: Firefox

**Device / Device Model**: Win 10 PC

**Related URLS** (To public & visible pages, add screenshots otherwise): 
Happens in the manuscript editor

**Describe the Issue**
A clear and concise description of what the issue is.
Sometimes we want to hit control-s to make sure something saves. Yes, there is auto-save, but as I think was noted elsewhere, sometimes that seems not to work, especially when importing larger sections from other platforms (so, y'know... when users are brand new... oof)

**To Reproduce**
1. Go to the Manuscript
2. Make changes <-this is important. Does not happen if nothing is changed.
3. Hit control-s
4. See error: Error: No form element found.

Note: control-s WORKS and does trigger the save, whether it is actually saving or just triggering the auto-save, I can't say. But it works perfectly, except for the error message.

**Expected behavior**
Saves, but no error seen.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Screenshot control-s-error](https://user-images.githubusercontent.com/4100767/201274567-e4c6e9bd-3c97-49fe-9203-abbf6bcffcb7.jpg)

**Comment by iamromeo** [comment]
Hey @Deleyna I cannot reproduce this actually - have you tried it on another browser or the same browser in incognito -

**Comment by Deleyna** [comment]
Hm. I usually use Firefox, and I get it consistently there. I just tested it in Chrome - which I rarely use - and I get it there as well. Several of my students have also reported getting it. It is 100% of the time for me, so I'm wondering if I didn't specify the steps well enough... or if it has something to do with new/old?

I made a screen recording...
https://www.dropbox.com/s/fz6g34k0jheynrt/Screen-capture-control-s.mp4?dl=0

My usual recording software was -of course- full, so I just used Zoom. (rolls eyes) Forgive that it isn't edited, but it is still pretty short. Here's what I did:

1. Used Chrome - not my usual browser
2. Went into new world
3. Created new manuscript
4. Went into first text space and made a change -> you'll see that the auto-save did work
5. hit control-s
6. Got the error
7. Fumbled for a bit to turn off the Zoom recording. (LOL)

Hopefully, seeing this will help you recreate it? I think it is fascinating that we get it consistently and you haven't been able to get it. Is there maybe a permission level issue somehow? Where the owner of a world might have a lower permission than you would (which would make absolute sense...)

Just throwing that out as an idea...

**Comment by iamromeo** [comment]
Hey @Deleyna I just realised what you meant - Ctrl+S is not a functioned we ever programmed on Manuscripts. Manuscripts autosave there is no manual saving system to it which is probably why Ctrl+S is showing that error - Why have you been using it?

**Comment by Deleyna** [comment]
When pasting in longer texts, it doesn't always auto-save. Regardless of
whether it is supposed to work or not, it actually DOES trigger the
auto-save...

I haven't been able to replicate when the not-saving thing happens, because
it seems inconsistent. But my students experienced it as well... so we just
started using Ctrl+S and haven't lost any work since!

No worries, though. Maybe it is just a feature of the amount we're
importing at one time???
