### ISSUE TITLE
Cannot Delete Manuscript

### ISSUE THREAD

**Issue by SolarCat02** [worldanvil/worldanvil-bug-tracker#1354]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: SolarCat02

**World / Campaign / RPG Character / Manuscript Title**: The Evacuation of Garnell

**Feature**: Manuscripts

**Operating System**: Windows 10?

**Browser**: Chrome

**Device / Device Model**: Android 

**Related URLS** (To public & visible pages, add screenshots otherwise): https://www.worldanvil.com/community/manuscripts/read/7628613786-solarcat02-the-evacuation-of-garnell
(Not that you can see anything there).

**Describe the Issue**
I tried to delete a manuscript, but instead it gave me a 404 error. When I returned to the manuscript to try to rename it instead, I realized that instead of deleting everything it only deleted the top item (that lets you change the book title and image and such), and removed everything from the folders. I now cannot use the manuscript at all.

Is it possible to delete it on your end?

**To Reproduce**
1. Go to 'Manuscripts'
2. Click on 'Delete Manuscript'
3. Type in the manuscript name
4. See the 404, and recheck the manuscript l

**Expected behavior**
I expected it to delete the manuscript. 
This was a very old manuscript created back when they were still fairly new so it is possible I hit a strange bug because of that? I just want it deleted from my profile so I don't see it when I go to edit my other Manuscripts. It was private, so won't appear on my public profile, but I like to keep my back end tidy too.

Thank you.

**Screenshots**
![20221112_000859](https://user-images.githubusercontent.com/65487082/201458630-f9598f68-7701-41ea-90c2-6c781c644a7e.jpg)

**Comment by Kordishal** [comment]
related to #206

**Comment by SolarCat02** [comment]
I was able to delete this on mobile this morning. Android with Chrome. I don't know what you did but it fixed it for me! Thank you!
