### ISSUE TITLE
World owner does not have access to sheets created by editors.

### ISSUE THREAD

**Issue by RAVaught** [worldanvil/worldanvil-bug-tracker#1355]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: RAVaught

**World / Campaign / RPG Character / Manuscript Title**: Flagstone

**Feature**: Advanced Tools>Statblocks 'Sheets'

**Operating System**: Win 10

**Browser**: Chrome/Vivaldi/Edge

**Device / Device Model**: Custom

**Related URLS** (To public & visible pages, add screenshots otherwise): 
![sheets permissions](https://user-images.githubusercontent.com/9615485/201487234-dc9c65ea-be56-4c45-8320-e385007745eb.PNG)

**Describe the Issue**
World owner does not have edit access to sheets used on their world if they are created by an editor.

**To Reproduce**
1. As Editor(other than owner), Go to 'Dashboard>Advanced Tools> Statblocks' and create a new sheet. Add to world. 
2. As Owner, Go to 'Dashboard>Advanced Tools> Statblocks' and check permissions on sheets list.

**Expected behavior**
World owner would be able to edit sheets used on their world. 

Additional Oddity:
After completing the steps above. Add the Owner as a Co-Owner for the world. The Owner will then have permission to edit. 
**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![sheets permissions3](https://user-images.githubusercontent.com/9615485/201487287-9e3e919c-0da9-494c-91b4-f23519e51898.PNG)
![sheets permissions2](https://user-images.githubusercontent.com/9615485/201487288-eb4cb626-220b-4ed2-905d-ffcc3b8da137.PNG)

**Comment by iamromeo** [comment]
This is not a bug - this is how the feature is meant to work, at least as it stands.
