### ISSUE TITLE
Delete Account Function Will Not Work

### ISSUE THREAD

**Issue by ZincCube** [worldanvil/worldanvil-bug-tracker#1357]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: LordOfCinder

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**:  Delete Account

**Operating System**: Android

**Browser**: Google Chrome

**Device / Device Model**: Samsung Galaxy A7 2018

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.
I have deleted my account using the delete account function in the Account page. After doing this I was sent to an error 404 page. When trying to create a new account, the email address was already in use, so I checked and my account I just deleted was still active. I tried deleting it again and was faced with the same issue. After waiting around 1 day, the account was still active
**To Reproduce**
1. Go to Account
2. Scroll down to the delete account box
3. Click on the red delete account button after entering username

**Expected behavior**
I expected the account to be deleted so that my email address was free to create a new account.
**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
The issue on the account was corrected and the account is deleted
