### ISSUE TITLE
Certain Font Awesome Icons Do Not Appear In Chronicles

### ISSUE THREAD

**Issue by generation359** [worldanvil/worldanvil-bug-tracker#1358]
**World Anvil Username**: ynix

**World / Campaign / RPG Character / Manuscript Title**: Chardovil

**Feature**: Chronicles (Advanced Timelines)

**Operating System**: Windows 10 Pro Version 21H2 (64-bit)

**Browser**: Firefox 106.0.5 (64-bit)

**Device / Device Model**: Custom Build (MSI Motherboard Model MS-7C56 BIOS 1.A0)

**Related URLS** (To public & visible pages, add screenshots otherwise):
Icon Visible in Title and Breadcrumb: https://www.worldanvil.com/w/chardovil-ynix/a/upstairs-gang-ascension-hub-article
The icon known to be affected: https://fontawesome.com/icons/shield-halved?s=solid&f=classic

**Describe the Issue**
An icon from Font Awesome, which displays properly across World Anvil, is not detected when attempting to add it to an Event in a Chronicle. Unknown if other icons are affected.

**To Reproduce**
1. Go to 'Timelines', and Create/Open a Chronicle
2. Create a new Event
3. Click 'Display' tab
4. Scroll to 'Timeline Display Icon'
5. Type 'fas fa-shield-halved'
6. See error 'No icon found with that name' below

**Expected behavior**
Expected icon to display left of typed icon name confirming its validity and for the icon to display for the event on the timeline.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
1. Icon Listed in Font Awesome
![image](https://user-images.githubusercontent.com/20841058/201781520-154744e8-079e-42d2-a59e-8ec1c072ad6a.png)

7. Icon Not Detected in Chronicle
![image](https://user-images.githubusercontent.com/20841058/201781023-9ad89a9f-14c4-47c6-a354-09bda199be72.png)

8. Icon Appearing in Article content
![image](https://user-images.githubusercontent.com/20841058/201781418-ea754bff-9e57-4425-9800-a030d3055a23.jpg)

**Comment by Kordishal** [comment]
Its because this icon is only available in v6. In v5 this shield is called `fas fa-shield-alt`  instead. Chronicles will be updated to v6 sometime in the future.

![image](https://user-images.githubusercontent.com/14262536/201839207-55870d87-0a25-400d-a04f-1f1ec3f8edce.png)
