### ISSUE TITLE
Sidebar appearing at the bottom of the article

### ISSUE THREAD

**Issue by CastleStanding** [worldanvil/worldanvil-bug-tracker#1359]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: CastleStanding

**World / Campaign / RPG Character / Manuscript Title**: Paskos/Campaign 1/

**Feature**: 

**Operating System**: Windows 11

**Browser**: Chrome & Firefox

**Device / Device Model**: Lenovo Laptop

**Related URLS** (To public & visible pages, add screenshots otherwise):
![image](https://user-images.githubusercontent.com/118317546/202072780-00ddd732-dc93-406c-8c4c-bf38c0921f36.png)

**Describe the Issue**
There is supposed to be sections dedicated to the sidebar, however they are now appearing at the bottom of the page, between the footnotes and the full width footer. This does not seem to be occurring to previous, or new articles. s

**To Reproduce**
***I can't seem to replicate the error. 

**Expected behavior**
I would like the sidebar to be moved back to the standard location on the side of the content. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Bar Darul - Sidebar Error](https://user-images.githubusercontent.com/118317546/202075613-879caba3-ed32-4bda-82ee-c54b7eee3c6a.PNG)

**Comment by Lyraine-Alei** [comment]
This happens when BBCode doesn't have a closing - go into source mode with
the >_ button and look for any missing [/p] or [/in] or similar closing
bits.

**Comment by CastleStanding** [comment]
Thank you very much that fixed my issue.
