### ISSUE TITLE
When creating a new article through "Articles" > "+ Article" under a category, vignette of custom article templates are blanked out.

### ISSUE THREAD

**Issue by CBairdAsh** [worldanvil/worldanvil-bug-tracker#1363]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**:
Kummer Wolfe

**World / Campaign / RPG Character / Manuscript Title**:
This happens with any world I have. Seems to be world independent.

**Feature**: 
Creating an article using a Custom Article Template through "Articles" > "+ Article" under a category

**Operating System**:
Windows 11

**Browser**:
Able to reproduce on the following browsers (latest versions):
Chrome
Brave
Edge
Safari
Firefox

**Device / Device Model**:
Surface Pro 8

**Related URLS** (To public & visible pages, add screenshots otherwise):
Screenshots attached

**Describe the Issue**
I use custom article templates for certain situations. In trying to create a new article using the pathway:

[1] "Articles" ( from left sidebar )
[2] Select a category
[3] Select "+ Article"
[4] Select a custom article template from drop down, but do not enter anything in the vignette
[5] Enter a title
[6] Select "Create Article"

The vignette blanks out any code, information, etc that has been placed in the vignette of the Custom Article Template. At this time, the only way I can maintain my workflow is to use the old "Dashboard" pathway instead and not use "Articles".

**To Reproduce**
See above

**Expected behavior**
Expected behavior is that when creating an article through this pathway:

[1] "Articles" ( from left sidebar )
[2] Select a category
[3] Select "+ Article"
[4] Select a custom article template from drop down, but do not enter anything in the vignette
[5] Enter a title
[6] Select "Create Article"

I expect the Custom Article Template to contain the pre-filled vignette bbcode, text, etc.

**Screenshots**

![contents of Custom Article Template vignette](https://user-images.githubusercontent.com/7758229/202853030-9b9031eb-ef0b-4bcf-8fbd-7ae2742810b0.png)

![new article made from article template with blank vignette](https://user-images.githubusercontent.com/7758229/202853027-d2d8df04-b858-4ad8-b7f0-a0354fb6c27c.png)

![creation of new article via articles using custom template with no vignette ](https://user-images.githubusercontent.com/7758229/202853029-92da0cf0-fb37-43a6-83ee-d45c1b145713.png)

**Comment by Kordishal** [comment]
This has always worked like this. The content would have to be added to the form for it to not overwrite the content. Not sure if the new interface will consider this.

**Comment by CBairdAsh** [comment]
Ok. That's rather problematic as it does reduce my ability to use the new workflows in World Anvil. But I'll find a workaround or code a browser add on to compensate. Thanks.
