### ISSUE TITLE
Sidebar: spouse entry is missing css classes for proper addressing

### ISSUE THREAD

**Issue by Tillerz** [worldanvil/worldanvil-bug-tracker#1364]
**World Anvil Username**: Tillerz

**World / Campaign / RPG Character / Manuscript Title**: Alana

**Feature**:  sidebar element css classes

**Related URLS**: https://www.worldanvil.com/w/alana/a/viola-calafado

**Describe the Issue**
There should be two classes for spouse entries: .spouse and .section-payload. Right now it is quite complicated to make all the different entries in the sidebar look the same.

![image](https://user-images.githubusercontent.com/63370525/202924127-194cd313-28e7-462f-bd3a-28019fa86395.png)

This is required just for the spouse:

`.user-css .character-relationships .character-spouses-header ~ .visibility-toggler`

If we had the .spouse and  .section-payload classes as the other entries do, it would be so much easier.

The whole block to make all elements look uniform looks like this:

```
.user-css .panel :is(.phrase-value, .section-payload, ul, dd, .tagged-articles-list, .sidebox, .listitem-hyphenated),
.user-css  .character-relationships .section-payload,
.user-css .character-relationships .character-spouses-header ~ .visibility-toggler {
  margin: 0 0 10px;
  background-color: #ffffff40;
  border-radius: 4px;
  -webkit-box-shadow: inset 1px 1px 4px 0 rgba(92, 92, 92, 1);
  -moz-box-shadow: inset 1px 1px 4px 0 rgba(92, 92, 92, 1);
  box-shadow: inset 1px 1px 4px 0 rgba(92, 92, 92, 1);
  list-style-type: none;
}

.user-css  .character-relationships .section-payload,
.user-css :is(.section-payload, .phrase-value),
.user-css .character-relationships .character-spouses-header ~ .visibility-toggler  {
  padding: 5px 5px 5px 10px;
}
```

Default article entry fields that go into the sidebar have .section-payload, and --key::value-- entries get grabbed by .phrase-value. Only the actual spouse payload has no specific class and needs a hack using  `~ .visibility-toggler`.

**Comment by katerinach** [comment]
@Tillerz the class  'section-payload' has been added to Spouses in the sidebar. Let me know if there's any issue with it.

**Comment by Tillerz** [comment]
Looks good, thank you! \o/
