### ISSUE TITLE
Spellbook within Character Sheet not Appearing Despite Prepared Spells Listed

### ISSUE THREAD

**Issue by livw314** [worldanvil/worldanvil-bug-tracker#1365]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: AtTheEndOfAllThings

**World / Campaign / RPG Character / Manuscript Title**: A World of Myth and Magic/ A World of Myth and Magic Campaign/ Quinn Quade

**Feature**: Spellbook within the character sheet (not in a separate tab in the character sheet)

**Operating System**:  macOS High Sierra version 10.13.6 (17G14042)

**Browser**: Chrome

**Device / Device Model**: MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)

**Related URLS** (To public & visible pages, add screenshots otherwise): https://www.worldanvil.com/sheet/1070471/view

**Describe the Issue**
A clear and concise description of what the issue is.  The spellbook within the character sheet (not in a separate tab in the character sheet) will not appear when I click view sheet despite spells being prepared listed in the correct section and the prepared checkbox being selected.  

**To Reproduce**
Steps to reproduce the behavior: Unknown

**Expected behavior**
A clear and concise description of what you expected to happen. I expect for a spellbook to appear between the attacks and features and traits sections of the character sheet.  I have included a screenshot of my own sheet showing that this is missing as well as a screenshot of my friend's sheet showing what it should look like.  

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
<img width="1074" alt="Screen Shot 2022-11-20 at 11 05 43 PM" src="https://user-images.githubusercontent.com/118709012/202970017-4cfbfa38-34da-4705-b3a4-dd126516622a.png">
<img width="744" alt="Screen Shot 2022-11-20 at 11 05 56 PM" src="https://user-images.githubusercontent.com/118709012/202970814-3e2e40f0-e5e7-4428-8542-377df91041e3.png">

I am also including a screenshot of the editing page to show how I have set this up for my own sheet as well as my friend's.  I have listed mine first.
<img width="826" alt="Screen Shot 2022-11-20 at 11 09 47 PM" src="https://user-images.githubusercontent.com/118709012/202970339-e94b21f9-012a-4e0f-9fce-9c02e5047770.png">
<img width="817" alt="Screen Shot 2022-11-20 at 11 12 32 PM" src="https://user-images.githubusercontent.com/118709012/202970657-d18aa197-5972-4d0e-a38a-b7e705d87002.png">

**Comment by Tillerz** [comment]
Hi,

sorcerer has the Spell Cast Ability "Charisma", the field in your sheet is set to NONE yet. Like this:

![image](https://user-images.githubusercontent.com/63370525/203070733-c1ecb475-3638-44b2-a8bf-0e375f9178b4.png)

**Comment by Tillerz** [comment]
Note to the form added:

![image](https://user-images.githubusercontent.com/63370525/203071736-4a0b71b9-cd4b-47fd-8652-c852fe063030.png)

**Comment by livw314** [comment]
Thank you!  This worked perfectly.
