### ISSUE TITLE
Spotify preview not appearing

### ISSUE THREAD

**Issue by CastleStanding** [worldanvil/worldanvil-bug-tracker#1366]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: CastleStanding

**World / Campaign / RPG Character / Manuscript Title**: Paskos

**Feature**: Spotify Embed

**Operating System**: Windows 11

**Browser**: Chrome

**Device / Device Model**: Lenovo Laptop

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
When I embed a spotify URL into an article, and although it appears on the editing page, the information for the song doesn't appear on the finished page (view page).

**To Reproduce**
1. Go to an article (the one I have this issue is a settlement)
2. Add a spotify song via the "spotify embed" option.
3. click on "view" on the left side of the article

**Expected behavior**
I expected there to be the same preview that I can see on the edit page, on the view page as well. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/118317546/203423320-3d901b9d-0a6a-4cd2-a82a-c739a32a476d.png)
![image](https://user-images.githubusercontent.com/118317546/203423395-2eb41b49-61ba-4b22-949e-8d9ab1ad35d5.png)

**Comment by iamromeo** [comment]
Hey @CastleStanding please read carefully the instructions on the codex. 
The viewer might be able to render the embed but there are specific instructions of which of the Spotify links to use in order for it to work the presentation :) 

This is not really a bug, more that the editor is over-eager to show the preview even with the wrong link to the song/album

**Comment by CastleStanding** [comment]
Thank you, I'm not sure where to find the "track code" in spotify, but I will look for it. Thank you! ^^

**Comment by iamromeo** [comment]
@CastleStanding right click on the link in spotify

![image](https://user-images.githubusercontent.com/660175/203469079-ac8f16c0-9366-4c2d-8a7e-fc906b90fb77.png)
