### ISSUE TITLE
Create a new supporting cast member issue in Google Chrome

### ISSUE THREAD

**Issue by golenrose8** [worldanvil/worldanvil-bug-tracker#1367]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**:  Goldenrose8

**World / Campaign / RPG Character / Manuscript Title**:  Althaneas / Upper Shulan

**Feature**: 

**Operating System**:  Windows

**Browser**:  Google

**Device / Device Model**: Windows11

**Related URLS** (To public & visible pages, add screenshots otherwise):  https://www.worldanvil.com/heroes/campaign/npc/new

**Describe the Issue**
When using google browser and in the campaign setting, clicking on " Create a new supporting cast member" brings up a page that cannot be edited.  I have attached a screen print below.  
The feature seems to work in Foxfire and Microsoft Edge but not Google Chrome.

**To Reproduce**
1. Go to '...'  https://www.worldanvil.com/heroes/campaign/character/list/non?type=npc
2. Click on '....'  Create a new supporting cast member

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Screenshot 2022-11-22 210806](https://user-images.githubusercontent.com/118866153/203456724-bf1effeb-6c34-4689-b97b-a976ffb34e4b.jpg)

**Comment by iamromeo** [comment]
That looks like the whole form is missing and there is no part of the code that can do that - have you tried this in incognito mode or another browser? 

It looks like a browser plugin is causing issues on your page.

**Comment by iamromeo** [comment]
Closed due to inactivity
