### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by littlekreen** [worldanvil/worldanvil-bug-tracker#1368]
**World Anvil Username**:Aureliangms@gmail.com

**World / Campaign / RPG Character / Manuscript Title**:World of Aurea

**Feature**: Internal Media

**Operating System**: Windows 10

**Browser**: Firefox

**Device / Device Model**: not applicable

**Related URLS** (To public & visible pages, add screenshots otherwise): https://www.worldanvil.com/images/markers/marker-icon-transparent.png

**Describe the Issue**
Internal resource is missing

**To Reproduce**
1. Go to map.
2. open console
3. See 404 error

**Expected behavior**
No 404s on internal resources to world anvil.

**Screenshots**

**Comment by iamromeo** [comment]
Hello there @littlekreen 

This marker icon is no longer used or available bud - I am not sure how you found it because this account has no worlds or characters. There is too little information to action this.
