### ISSUE TITLE
Failure to add location, XHR call returns 500

### ISSUE THREAD

**Issue by littlekreen** [worldanvil/worldanvil-bug-tracker#1369]
**World Anvil Username**: Aureliangms@gmail.com

**World / Campaign / RPG Character / Manuscript Title**:world of aurea

**Feature**: Adding Map Locations

**Operating System**: Windows 10

**Browser**: Firefox

**Device / Device Model**:

**Related URLS** (To public & visible pages, add screenshots otherwise): https://www.worldanvil.com/w/aurea-drykos/map/32a615b1-4613-472b-8f3f-cdad0668974c

**Describe the Issue**
when right clicking a spot on the map the call to complete the dialog just returns a 500 and waits indefinitely. Possible related issue is the XHR call has an unsanitized space in the URL for the lng parameter. Example https://www.worldanvil.com/marker/new?lat=1477&lng= 5161&mapId=32a615b1-4613-472b-8f3f-cdad0668974c Notable: Though it had gotten past this point occasionally the save button just highlights but does nothing.

**To Reproduce**
1. Go to map
2. Right Click on any cell
3. wait for loading tooltip to open
4. fails to ever open
5. console log indicates 500 error on the internal call

**Expected behavior**
Tooltip for adding a location opens a form

**Screenshots**
![500 related error](https://user-images.githubusercontent.com/8787657/204117308-99d2cb78-bdb5-48b7-aa7d-00f3d6286aee.png)
![console](https://user-images.githubusercontent.com/8787657/204117336-1d25ece5-e903-4090-8f45-7ae5591e9bff.png)

**Comment by iamromeo** [comment]
Hey @littlekreen I have now found your account so I can give you some more information. 
Your account is a **writer** in the world of another user. Writers (contrary to Editors) do not have access to the map editing features as it stands right now. The owner of the world can turn you into an Editor so you can get access to the feature.
