### ISSUE TITLE
Apostrophes appear as &#039; when mousing over markers in a map.

### ISSUE THREAD

**Issue by Dresdon** [worldanvil/worldanvil-bug-tracker#137]
**World Anvil Username**: Dresdon

**World / Campaign / RPG Character / Manuscript Title**: https://www.worldanvil.com/w/ravenloft-dresdon

**Feature**: Map mouse over of markers

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Apostrophes appear as &#039; when mousing over markers in a map.

e.g. "Dollmaker's Bridge" appears as "Dollmaker&#039;s Bridge"

**To Reproduce**
1. Create a map marker with an apostrophe in the name.
2. Mouse over it on a map.

**Expected behavior**
The text to appear with the ' symbol instead of the code &#039;

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
<img width="110" alt="wa_github_ss1" src="https://user-images.githubusercontent.com/7947589/114024655-394a6980-986c-11eb-96ff-024b2b615ef8.png">

**Comment by iamromeo** [comment]
This is a browser mouseover - will not fix
