### ISSUE TITLE
Getting 404 Error Page When Attempting to Join WA Campaign

### ISSUE THREAD

**Issue by wjgreen789** [worldanvil/worldanvil-bug-tracker#1370]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**:  CaptainN7heGM

**World / Campaign / RPG Character / Manuscript Title**:  Phabulous Phandalin (Campaign/World), Fflewddur Flynn (Character)

**Feature**:  Trying to join a campaign in WA with an existing and with a new character.

**Operating System**: Windows 10

**Browser**:  Brave, Chrome & Opera

**Device / Device Model**:  Custom PC

**Related URLS** (To public & visible pages, add screenshots otherwise):
Campaign invite link:  https://www.worldanvil.com/epic/I9eFeaeUlh5Uaj083pyqwbJhJM6pvI/join/zKng-PObl-VDpK8x

**Describe the Issue**
I am trying to join a WA campaign and am getting a 404 error page when attempting to join either using an existing character in my WA account or through the new character creation form displayed on the campaign invite link.

**To Reproduce**
1. Navigate to the campaign invite link.
2. Click the "Choose Fflewddur" button.
3. Get redirected to a 404 error page:  https://www.worldanvil.com/heroes/campaign//character/d6a626f5-f0b7-4c45-b24e-7526bea57c33/grant-access/zKng-PObl-VDpK8x/

1. Navigate to the campaign invite link.
2. Fill out "Name" and "Lastname" of new character form and click "Join Campaign".
3. Get redirected to a 404 error page:  https://www.worldanvil.com/epic//new-character

**Expected behavior**
My WA character Fflewddur Flynn is added to the WA campaign I've been invited to join.

**Screenshots**
<img width="922" alt="WA Bug Report (Campaign Invitation Page - Win10 Chrome)" src="https://user-images.githubusercontent.com/119260197/204158813-eca01b99-6c10-40cd-8ef9-3e555e8faec5.png">
<img width="933" alt="WA Bug Report (Campaign Join Error Page - Attempt to Join via Existing WA Character)" src="https://user-images.githubusercontent.com/119260197/204158816-651a637a-a9e0-40d3-9294-da78f85edbb7.png">
<img width="871" alt="WA Bug Report (Campaign Join Error Page - Attempt to Join via New WA Character)" src="https://user-images.githubusercontent.com/119260197/204158817-d2c40285-d6cd-41d0-aea4-445de171831b.png">

**Comment by iamromeo** [comment]
This is not a bug - if you have noticed on the top of the page there is no mention of the campaign's name. 
This means that the link used to go to this page is expired. The system could not find the campaign that is the reason the url has nothing between the two //. 

Please ask your GM to supply to you the correct or updated URL to join the campaign :)

**Comment by wjgreen789** [comment]
Thanks for taking the time to look into the issue! I will ask the GM to provide an new campaign invitation link.
