### ISSUE TITLE
Duplicate linear navigation displaying on worlds

### ISSUE THREAD

**Issue by tjtrewin** [worldanvil/worldanvil-bug-tracker#1373]
**World Anvil Username**: tjtrewin

**World / Campaign / RPG Character / Manuscript Title**: Melior

**Feature**: linear article navigation

**Operating System**: Windows

**Browser**: Firefox

**Device / Device Model**: PC

**Related URLS** (To public & visible pages, add screenshots otherwise):
https://www.worldanvil.com/w/Melior/a/enchanting

**Describe the Issue**
All articles that have assigned previous, next, or parent articles/category are displaying the linear navigation twice.
My friends are also experiencing the same issue.

**To Reproduce**
- make article
- assign parent article or category
- assign prev/next articles
- view article presentation

**Expected behavior**
No duplicates.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/52583614/204579295-3bb20a15-a6f5-42f2-b684-ad81efe4fd24.png)

**Comment by katerinach** [comment]
This is now fixed.
