### ISSUE TITLE
WorldEmber article entries - word count panel showing (potentially) wrong number

### ISSUE THREAD

**Issue by Meagan-Denton** [worldanvil/worldanvil-bug-tracker#1375]
**World Anvil Username**: StorytellerNat

**World**: Hyrule

**Feature**: Word Count panel (specifically for articles for WorldEmber 2022, as far as I can tell)

**Operating System**: Windows 11

**Browser**: Opera GX

**Device / Device Model**: Gaming Laptop (Acer Predator)

**Describe the Issue**
The word counter for an article eligible for WorldEmber is using the 10k word count for the entirety of WorldEmber, rather than 50 word minimum stated on the challenge page. This makes it seem like rather than 10k words of worldbuilding, each individual article has to be 10k words to be eligible for WorldEmber.
This doesn't appear on the progress page for WorldEmber, just on articles that are eligible for being WorldEmber entries.

**To Reproduce**
1. Create an article
2. Make it public and published (so that it shows the "WorldEmber 2022" panel on the side of the editor view)
3. Scroll down to the WorldEmber 2022 panel

**Expected behavior**
Normally, in WorldAnvil challenges, the panel for eligible articles has shown the minimum amount of words for an article to be eligible for the challenge. And the challenge page for WorldEmber 2022 shows that the minimum word count for a WorldEmber article is 50, and that the challenge itself overall is for 10k words. This implies that the WorldEmber 2022 panel for articles should show [x] / 50 words, rather than [x] / 10000 words.
Thankfully, as I said in #worldember-2022 on Discord, it's a very minor bug (assuming this is a bug, as GalaxyWolf said this could be intentional), and it doesn't stop me from working on my WorldEmber 2022 entries. It's just something that caught me off guard and confused me while I was working on said entries.
(And if this isn't a bug, and is in fact working as intended, then I'm sorry in advance, since I know things are really busy - especially for Dimi and Janet since they're moving to a new house)

**Screenshots**
Screenshot of the WorldEmber word count panel for an article:
![image](https://user-images.githubusercontent.com/90356084/205470220-00745e25-a41d-443f-8feb-c51b7b03cdba.png)
Screenshot of the word count panel on my WorldEmber progress page:
<img width="304" alt="image" src="https://user-images.githubusercontent.com/90356084/205470409-872e8246-da06-4a07-8a04-c8752e0a391d.png">

**Comment by iamromeo** [comment]
Hey @Meagan-Denton this is indeed a **visual** bug - we will not be handling it at this point since it really is not crucial for anything and we do not have the capacity due to the other projects currently running, but thank you so much for bringing it to our attention <3

**Comment by Meagan-Denton** [comment]
Yeah, I completely understand that. It's a really minor bug, it doesn't stop me from using the platform, and you guys are already really busy with so many other things (hopefully the move is going well!)
