### ISSUE TITLE
Timeline eras duplicate event when overlapping

### ISSUE THREAD

**Issue by Viruzodro** [worldanvil/worldanvil-bug-tracker#1376]
**World Anvil Username**: Viruzodro

**World / Campaign / RPG Character / Manuscript Title**: Esper

**Feature**: Timeline

**Operating System**: Windows 11

**Browser**: Chrome

**Device / Device Model**: Gigabyte / Areo 15

**Related URLS** (To public & visible pages, add screenshots otherwise): https://www.worldanvil.com/w/esper-viruzodro/t/history-of-the-world-timeline

**Describe the Issue**
When you add an event on the timeline that falls on the same year as the start of an era, the event will appear both before and after the era. I am using the inverted year function so that might have something to do with it. Thank you!

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Hi! This is working as intended. Make sure that your eras do not have an overlapping year.
