### ISSUE TITLE
Pirate Borg

### ISSUE THREAD

**Issue by danbrdg** [worldanvil/worldanvil-bug-tracker#1377]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name (RPG SYSTEM)**:
**List Name** (Name under which it should be listed on World Anvil):
**World Anvil Username**:

**Website**: https://www.limithron.com/pirateborg

**Logo Image Link**:

**Logo Usage Terms (URL)**:

**Comment by iamromeo** [comment]
@danbrdg can I please have your World Anvil username ?
