### ISSUE TITLE
Todo list not finding new articles

### ISSUE THREAD

**Issue by MrHales** [worldanvil/worldanvil-bug-tracker#1379]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Mr.Hales

**World / Campaign / RPG Character / Manuscript Title**: Trilogy

**Feature**: Todo list

**Operating System**: Ubuntu 22.10

**Browser**: Chrome (up to date)

**Device / Device Model**: ASUS X99 Deluxe

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
New articles are not added to Todo List upon creation outside of the Todo List. Articles created as Private, Draft, Work-in-Progress articles do not populate the list. I'm not sure how the list is supposed to be populated normally, but I don't believe it is functioning.

**To Reproduce**
1. Create a new article as Draft, Public or Private, WIP
2. Check Todo list
3. Same number of items on todo list as before

**Expected behavior**
Expect that new articles will populate Todo list. Articles created by linking to a nonexistent article seem to function properly. Accidentally created 3 more items in my list by correcting @Test_4(article) to Test\4 via typo and Test4. Todo count went up from 29 to 32 and all the created by link articles are now listed.

Minor issue: The trashcan icon makes it look like I'll be deleting the article in question, not the todo list item, and it's scary. Please improve the tooltip to be more specific than just "Delete".

**Comment by Kordishal** [comment]
The to-do list is populated automatically in two cases: 

1. Creation of an article via the placeholder template link.
2. Creation of an article via the purple quick ink well menu. 

When an article is created somewhere else then no to-do list item is created. This is working as intended.

The issue with bad todo items being created when the template link is incomplete is a known issue.
