### ISSUE TITLE
Map Pin Editing Permissions Error Co Editor

### ISSUE THREAD

**Issue by yndrelbosch** [worldanvil/worldanvil-bug-tracker#138]
**World Anvil Username**: yndrelbosch

**World / Campaign / RPG Character / Manuscript Title**: [The Forgotten World](https://www.worldanvil.com/w/the-forgotten-world-alexander-ranvir)

**Feature**: Map Pin Editing / Labels

**Describe the Issue**
I have been given Editor privileges on someone's world, I am a Grandmaster, he is a Journeyman, I was attempting to add a label on the map, but it tells me that is a Master+ feature. I don't know if this is a bug, or if it means we both need to be above Master level. But in case of bug, I'm posting it here.

**Expected behavior**
I would expect to be able to use my Grandmaster features on any world I have permission to, whether the owner has a high level or not.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

https://photos.app.goo.gl/aBz97bxAD1gdq1TBA

https://photos.app.goo.gl/p6xZXtcSbu4SGCSi9

**Comment by iamromeo** [comment]
hey @yndrelbosch  This is not a bug, the permissions are based on the world owner not the editor. 
Simply said, this is not your world and as such, it has no access to those features.
