### ISSUE TITLE
Whiteboard reset itself after internet disconnected

### ISSUE THREAD

**Issue by sondrex76** [worldanvil/worldanvil-bug-tracker#1381]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**:
sondrex76 
**World / Campaign / RPG Character / Manuscript Title**:
Whiteboard formerly called Animorian Pantheon, at the moment its name has been reset and is empty.
**Feature**: 
Whiteboard
**Operating System**:
Windows 10
**Browser**:
Firefox
**Device / Device Model**:
Device mode
**Related URLS** (To public & visible pages, add screenshots otherwise):
It is the following whiteboard, but it is currently private: https://www.worldanvil.com/world/whiteboard/a795a5d3-2a4e-479a-8e24-d4e9c3a32049
Image of its current state:
![image](https://user-images.githubusercontent.com/3610508/206757174-6cd1d88d-e362-45f7-af39-abb3d9ff60e4.png)
Image of older version of the whiteboard (outdated and consisting of multiple screenshots edited together previously):
![Untitled](https://user-images.githubusercontent.com/3610508/206757814-7dc85a2d-4611-4b7e-937e-9f00dd619149.jpg)

**Describe the Issue**
I lost my internet connection and a tab had the whiteboard open. Ater restarting my computer I later noticed that the whiteboard had become empty and reset.
A similar issue appeared to be present on one of my other whiteboards, but that one I had an unloaded tab that, when opened, had an at least somewhat updated version of the whiteboard ready for saving. I do not appear to have the same for the one in this issue.

**To Reproduce**
I am not sure, my internet disconnected and I restarted my computer while I had the whiteboard on a tab that was not actively in use.

**Expected behavior**
The whiteboard should not reset itself

**Screenshots**
Image of its current state:
![image](https://user-images.githubusercontent.com/3610508/206757174-6cd1d88d-e362-45f7-af39-abb3d9ff60e4.png)
Image of older version of the whiteboard (outdated and consisting of multiple screenshots edited together previously):
![Untitled](https://user-images.githubusercontent.com/3610508/206757814-7dc85a2d-4611-4b7e-937e-9f00dd619149.jpg)

**Comment by iamromeo** [comment]
@Duranzno can you please investigate?

**Comment by iamromeo** [comment]
Hey there - I am really sorry to hear that this happened - We cannot replicate it but seeing your work we decided to go ahead and create an export/import system that will allow you to also get a backup of your work. 

We tried to follow all the steps and we couldn't find a way to make it happen so we can understand what might have happened.

**Comment by iamromeo** [comment]
I am closing this but expect a new update with the importer/exporter soon :)
