### ISSUE TITLE
Won't Let Me Begin Worldbuilding

### ISSUE THREAD

**Issue by pay-a-een** [worldanvil/worldanvil-bug-tracker#1385]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: pay_a_een

**World / Campaign / RPG Character / Manuscript Title**: None - because it won't even let me create.

**Feature**: World Building

**Operating System**: Plato (?)

**Browser**: Safari

**Device / Device Model**: MacBook Pro

**Related URLS** (To public & visible pages, add screenshots otherwise): 

https://www.worldanvil.com/world/new

**Describe the Issue**
A clear and concise description of what the issue is.

So I log-in to my account on World Anvil. I just created this account yesterday, as my friend has been using this product and stands by it, so I figured I would try it out. After getting my account all set up how I like it, I click to begin my world. After I type the name, write my brief description, and select that it is for Dungeons and Dragons 5e, I press "Save and Proceed." It loads for 30 seconds and sends me to the URL, but it's just a large dragon with a typed "404" on it, saying "Thus you have reached the end of this world." I have tried using other devices, such as my smartphone, an iPhone 13, and another computer. I have even tried not selecting the RPG System and even not putting. in my brief description, but every time it will send me to the same page and not let me even begin to create with you product.

**To Reproduce**
1. Go to 'Homepage'
2. Click on 'Get Worldbuilding'
3. Type name of your world and press 'Save and Proceed'

**Expected behavior**

I would expect to actually be able to do all the things my friend has described, and use this amazing tool and website.

**Screenshots: These are in chronological order as they occur**

<img width="1440" alt="Screen Shot 2022-12-14 at 4 22 56 PM" src="https://user-images.githubusercontent.com/120602987/207717844-406e1e71-077e-4d5e-a2b5-f7ab564bfc28.png">
<img width="1440" alt="Screen Shot 2022-12-14 at 4 23 25 PM" src="https://user-images.githubusercontent.com/120602987/207717867-48935956-d18f-4847-9690-912255114d2e.png">
<img width="1440" alt="Screen Shot 2022-12-14 at 4 23 33 PM" src="https://user-images.githubusercontent.com/120602987/207717881-d02fa1b8-de03-4982-a517-cba08b8a7e1e.png">

**Comment by Kordishal** [comment]
You were able to resolve your issue?
