### ISSUE TITLE
Theme CSS Issues - Deadhouse Sonata

### ISSUE THREAD

**Issue by Ingleheimer** [worldanvil/worldanvil-bug-tracker#1386]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Ingleheimer

**World / Campaign / RPG Character / Manuscript Title**: Chromatiaverse

**Feature**: Theme (World Introduction + Discussion Board)

**Describe the Issue**
When using the **Dark Sonata** theme, footer elements (book categories, discussion board, followers, timelines, etc) all overlap each other on the introduction page. This occurs reliably in mobile browsers, and in desktop browsers the issue occurs if the window is shrunk enough. The effect is pictured in the attachment "Overlapping Elements". 

Additionally, Discussion Boards are aesthetically unusable. Most text appears to display in white text on top of a white backdrop, as pictured in the attachments "Discussion Board" and "Highlighted". 

**To Reproduce**
1. Set world theme to Dark Sonata. 
2. View world in either mobile browser or small desktop browser window (introduction page footer elements overlapping). 
3. View world discussion board (white text on white backdrop). 

**Expected behavior**
- Introduction elements should not overlap. 
- Discussion board should be backed by same dark backdrop as rest of pages in theme

**Comment by Ingleheimer** [comment]
Original post didn't seem to upload the pictures.

![Highlighted](https://user-images.githubusercontent.com/98876245/207726455-19be283f-c354-4a6e-9ff4-31339d35fb43.png)
![Discussion_Board](https://user-images.githubusercontent.com/98876245/207726458-057ebf1d-afdb-4e28-ac95-86a63a64c43f.png)
![Overlapping_Elements](https://user-images.githubusercontent.com/98876245/207726461-ef0fc26b-c249-47d2-bfeb-71536226e091.png)

**Comment by iamromeo** [comment]
Hey @Ingleheimer I am really sorry but I cannot replicate this and I cannot see your work - no public link was provided. 

- Have you tried replicating this with another theme? 
- Can this be an unclosed BBcode tag that breaks the page?

**Comment by Kordishal** [comment]
```css
.user-css .world-bookcase {
    height: unset;
}
```
This will fix the issue. The height of the world bookcase is fixed to 20px which causes the bookcase to overflow over the stuff bellow it when on mobile.

**Comment by Ingleheimer** [comment]
I can plug that in, yeah. But, given that's something the theme itself is doing, I just want to make sure it's getting addressed there too for other users who might also choose it and/or haven't caught it yet. 

Follow-up; what about the discussion boards (white text on white backdrop)?

**Comment by iamromeo** [comment]
@katerinach the theme in question is called **Deadhouse Sonata** we need to remove the  height from .world-bookcase

**Comment by katerinach** [comment]
@Ingleheimer the bug has been fixed. Let me know if you still have a issue with it.
