### ISSUE TITLE
404 and no saving error when trying to create historical entry on timelines

### ISSUE THREAD

**Issue by invaders-forever** [worldanvil/worldanvil-bug-tracker#1387]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: invadersforever

**World / Campaign / RPG Character / Manuscript Title**: Heroic Comics Universe

**Feature**: Timelines

**Operating System**: Chrome OS

**Browser**: Chrome

**Device / Device Model**: Hp Chromebook

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.
When I hit create historical entry after filling in the fields, it goes to a 404 page. If i look at my timeline later the entry will not be there even if the banner pops up to tell me the entry had been created.

This has repeated across the past couple days.

**To Reproduce**
1. Go to create historical entry on the timeline edit page
2. Click create historical entry and fill in the fields (i did title, timelines, and starting date)
3. Click create historical entry

**Expected behavior**
The 404 page will appear and the historical entry will not be part of the timeline.
**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
[Screen recording 2022-12-15 1.07.55 PM.webm](https://user-images.githubusercontent.com/120677989/207946372-a7beb42a-9418-43d4-81ce-388bfbe7c9a1.webm)

**Comment by iamromeo** [comment]
That looks like you are adding special characters or similar to the fields of the historical entry but without more specific information about what you are adding I cannot really give you an proper answer. This cannot be replicated as it is described. 
If you can give us a good example that we can replicate it - please do so and we can reopen this ticker and investigate
