### ISSUE TITLE
The vignette in the super-expanded view of the articles section doesn't save the text

### ISSUE THREAD

**Issue by Luppis** [worldanvil/worldanvil-bug-tracker#1389]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Kaladom

**World / Campaign / RPG Character / Manuscript Title**: Kaladom

**Feature**: Articles super-expanded view text

**Operating System**: ChromeOS

**Browser**: Google Chrome

**Device / Device Model**: Acer Chromebook 314

**Related URLS** (To public & visible pages, add screenshots otherwise):
I'm in the articles section, with super expanded view enabled,
![image](https://user-images.githubusercontent.com/44931365/208126201-221425cf-f725-439d-9956-809a5464d5a7.png)
I try writing something in the vignette, which should be saved,
![image](https://user-images.githubusercontent.com/44931365/208126515-94b64e15-8b65-497f-ad71-8d3878b81424.png)
Going to another page by clicking on the dashboard button
![image](https://user-images.githubusercontent.com/44931365/208126684-98effe72-94bd-4c65-8ebd-4aa5499df0a0.png)
Coming back to the articles page in super expanded view, the text that should have been saved is gone,
![image](https://user-images.githubusercontent.com/44931365/208127147-d0a54c5d-23cc-4677-8d44-4ac99c3e956c.png)
So it doesn't seem to save.

**Describe the Issue**
A clear and concise description of what the issue is.

The vignette in the super-expanded view of the articles section doesn't seem to save the text you write inside of it. I wrote a bunch of text and went to another page, and back, then it hadn't been saved and the text was gone. I talked to another person on discord who had the same issue, so it didn't seem localised to me, and she/he suggested that I do a bug report. I'm very new to world anvil.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Articles page'
2. Click on super expanded view
3. Write something in an article vignette.
4. Click on maybe the dashboard button
5. Go back to the articles section
6. The text that should have been saved in the vignette is gone

**Expected behaviour**
I wanted the text in the vignette of the super expanded view in the article page to save, and not delete the text that I wrote in the article when going to another page and coming back.
**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
I added some screenshots to the problem in related URLs.

**Comment by Kordishal** [comment]
It does not save successfully when the article is not selected of which you are editing the vignette. As long as the article is displayed on the right the saving does take place as intended.

**Comment by Luppis** [comment]
Ok I understand, but it would be a nice feature for it to be saved
regardless how what was selected. This way, you can quickly edit between
different articles and copy paste, etc and get a better overview.

Regards.

Den fre 16 dec. 2022 16:24Jonas Waeber ***@***.***> skrev:
