### ISSUE TITLE
Changes in "Articles and Categories" are not saved

### ISSUE THREAD

**Issue by Alresu** [worldanvil/worldanvil-bug-tracker#139]
**World Anvil Username**:
Alresu

**World / Campaign / RPG Character / Manuscript Title**:
Sapiera

**Feature**: 
Editing in "Articles and Categories"

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/world/athena/ (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When editing in "Articles and Categories", some fields save data and some don't.
The Tags-field does not save tags I add in Expanded view but does so in the normal one. But even in normal view I can not delete all tags: After deleting all tags from an article in this screen the deleting of the last one is reversed when switching to another article and back again.
Furthermore the Icon field behaves strangely. Adding data to it is saved (even in expanded view), but it can not be deleted after that.

**Expected behavior**
Every change should be saved.

**Comment by Kordishal** [comment]
1. Cannot reproduce tags not saving in the expanded view. Works just fine.
2. *Can* reproduce deleting all tags not saving properly. If you have a list of tags and delete all of them with backspace the last tag returns after a reload.
3. Cannot reproduce the issue with the icon field. Could remove all text and after a reload it stayed gone.

**Comment by Alresu** [comment]
> 
> 
>     1. Cannot reproduce tags not saving in the expanded view. Works just fine.
> 
>     2. _Can_ reproduce deleting all tags not saving properly. If you have a list of tags and delete all of them with backspace the last tag returns after a reload.
> 
>     3. Cannot reproduce the issue with the icon field. Could remove all text and after a reload it stayed gone.

Can confirm that 1. and 3. do not seem to be a general problem. Those problems seems to have fixed themselfes today.

**Comment by Alresu** [comment]
I have to retracht my previous comment.. The problem is back. It seems like I can add tags for one article in expanded view. After that I have to do a hard refresh to add ones to the next article. And even then it only works in about 50% of the cases. 
But it seems to reliably work for one article after restarting the whole computer, which is extra weird. 

(Tested on Firefox and Google Chrome to make sure it's not the browser's fault.)

**Comment by Kordishal** [comment]
Copy and pasting a list of tags into the field definitely doesn't work. That is a limitation of the library used.
