### ISSUE TITLE
Family Tree/Bloodline Bug

### ISSUE THREAD

**Issue by Yunnlith** [worldanvil/worldanvil-bug-tracker#1390]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Willow H.R. Harper

**World / Campaign / RPG Character / Manuscript Title**: Character page, regardless of world

**Feature**: Family Tree/Bloodline

**Operating System**: Windows

**Browser**: Chrome

**Device / Device Model**: PC

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
There is a bug regarding the Family Tree/Bloodline feature. 

The following request was denied, because the following feature "[showing] the entire lineage from the first of its name all the way to its descendants in a static image" is "already [existing] and it is called Bloodlines".
https://www.worldanvil.com/community/voting/suggestion/fbcedaf2-8eeb-44af-9f49-e0fb1fa26448/view

However, when going to the Codex, the Bloodlines feature displays "only the parents and the descendents of a character instead of the **full family tree**". This is, in fact, true. So, assuming there was an accidental slip-up when closing down the request, I tried the "Family Tree" feature instead.
https://www.worldanvil.com/w/WorldAnvilCodex/a/family-trees

However, that feature also doesn't show the "entire lineage from the first of its name all the way to its descendants in a static image". Instead, the **"full family tree"** limits itself to great-grandparents and great-grandchildren and excludes uncles, aunts, cousins, and so on.

**To Reproduce**
1. Copy-Paste the following
[familytree:50ac8d2b-0d08-451d-ac7a-3c7b058ed49d]
2. Copy-Paste the following to see an example of missing direct descendants.
[familytree:cf57c4a6-0d7e-431f-a3b9-45c61776b27e]
3. Copy-Paste the following to see an example of missing siblings/uncles/aunts, etc.
[familytree:8a28b756-263a-48cf-93ed-82f7675c30e1]

**Expected behavior**
I expected to see a **"full family tree"**, as stated by the codex. I assume there is a bug.

**Screenshots**
1. ![Capture d’écran (572)](https://user-images.githubusercontent.com/120929995/208297780-b22b551c-256d-435f-8168-fbeb5353583d.png)
2. ![Capture d’écran (571)](https://user-images.githubusercontent.com/120929995/208297775-fa817ec8-d2a6-4f58-930a-1b64819fea42.png)
3. ![Capture d’écran (570)](https://user-images.githubusercontent.com/120929995/208297754-cf21fef8-89e7-4c18-98e5-bdf5bfaca41c.png)

**Comment by Kordishal** [comment]
Hi, this is not a bug no. Both features are working as intended. The misunderstanding comes probably from your feature request having the title Lineage Line. The bloodline does display all the characters in a lineage. 

The full family tree as a static image was accepted here: https://www.worldanvil.com/community/voting/suggestion/42ce659c-b7c4-4d0c-b582-1264e776791d/view (though with a disclaimer). I am not sure what the current plans are but possibilities are to just generate the images or to have a tool like for the content trees, but to build family trees. These then could display any number of family members.

At the moment if you want a full family tree in one screen you could use a whiteboard.
