### ISSUE TITLE
Adding Steve Jackson Games GURPS System (Generic Universal Roleplaying System)

### ISSUE THREAD

**Issue by Dojon** [worldanvil/worldanvil-bug-tracker#1391]
**Full Name**:  Steve Jackson Games GURPS
**List Name**: GURPS: Generic Universal Roleplaying System
**World Anvil Username**: pmcneil

**Website**: http://www.sjgames.com/gurps/

**Logo Image Link**: http://www.sjgames.com/img/siteframe/gurps/logo.jpg

**Logo Usage Terms (URL)**: http://www.sjgames.com/general/online_policy.html

**Comment by iamromeo** [comment]
Hello @Dojon GURPS is there already - it's infact there since day 0

**Comment by Dojon** [comment]
Oh TY so much for the reply! Sorry to put that request in, it seemed to
prompt me for that, even though I then saw it in the list on another screen
later. I am still finding my way around the incredible software.

Thanks!
