### ISSUE TITLE
Recent Articles not showing up

### ISSUE THREAD

**Issue by HCoffman** [worldanvil/worldanvil-bug-tracker#1392]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: HUNTER_COFFMAN

**World / Campaign / RPG Character / Manuscript Title**: Thedas

**Feature**: Recent Articles

**Operating System**:

**Browser**: Chrome, Edge

**Device / Device Model**:

**Related URLS** (To public & visible pages, add screenshots otherwise): https://www.worldanvil.com/w/thedas-huntercoffman

**Describe the Issue**
When looking at my world's home page, I do not see the Recent Articles list pop-up despite having the setting enabled for my world for it to appear.

**To Reproduce**
1. Go to https://www.worldanvil.com/w/thedas-huntercoffman
2. Look for Recent Articles, see it's not there.

**Expected behavior**
I expect the Recent Articles to appear somewhere on my world's main page.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![error](https://user-images.githubusercontent.com/16968972/209275035-c70010a4-0cd5-47b7-a989-64782195c31a.jpg)

**Comment by iamromeo** [comment]
Hello @HCoffman just to clarify - have you announced any of your articles so they appear there ?

**Comment by HCoffman** [comment]
Hi, sorry for not responding to your inquiry -- Github did not inform me a response was made. If you're able to reopen this I'd appreciate it otherwise I can create a new bug.

I have many published, public articles. The Recent Articles section used to show up, though I don't know when it stopped appearing.

**Comment by Kordishal** [comment]
Articles being published or public is not enough by itself since January last year. You have to hit the Add to Recent button in the article editor or the articles interface!

**Comment by HCoffman** [comment]
Thank you so much; I must have missed when this feature was released. Thank you, @Kordishal!
