### ISSUE TITLE
Add After--Burner to World Anvil

### ISSUE THREAD

**Issue by Alecthar** [worldanvil/worldanvil-bug-tracker#1393]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first four points at least, otherwise the request will not be considered.

**Full Name (RPG SYSTEM)**: After\\Burner
**List Name** (Name under which it should be listed on World Anvil): After--Burner
**World Anvil Username**: Alecthar

**Website**: https://theyoungking45.itch.io/afterburner

**Logo Image Link**: https://img.itch.zone/aW1nLzk1NTQ1MzgucG5n/original/TWh3jL.png

**Logo Usage Terms (URL)**:

**Comment by iamromeo** [comment]
That looks really cool! Added to the list
