### ISSUE TITLE
Dragging categories to rearrange puts them in wrong spot

### ISSUE THREAD

**Issue by austinzheng** [worldanvil/worldanvil-bug-tracker#1396]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: austinzheng

**World / Campaign / RPG Character / Manuscript Title**: 'Tales of the Tianhai'

**Feature**: moving categories around in the 'Articles' tab by dragging them

**Operating System**: macOS 13

**Browser**: Google Chrome

**Device / Device Model**: Mac Studio

**Related URLS** (To public & visible pages, add screenshots otherwise): n/a

**Describe the Issue**
When I drag categories around in the Articles tab to rearrange them, they are not actually repositioned correctly.

**To Reproduce**
1. Go to the world dashboard
2. Click on 'Articles'
3. Make sure you have several categories, maybe 10 or so
4. Move a category to a different spot on the list by dragging it.

**Expected behavior**
The category should be moved to the position I specified.

(If I go to the world homepage, or I click the little refresh icon, I see the categories are rearranged incorrectly. See screenshots for an example of what I mean.)

**Screenshots**
See below. The first is what the list looks like immediately after I dragged one category to a new position. The second is what the list looks like after I pressed the refresh button, doing nothing in between. The category I tried moving is the seventh one in the first screenshot, but has become the third one in the second screenshot.

<img width="249" alt="after dragging" src="https://user-images.githubusercontent.com/3687054/209935158-333ac7dd-5ba0-4cc2-9df3-6579f3442e83.png">

<img width="243" alt="after refreshing" src="https://user-images.githubusercontent.com/3687054/209935170-71780d61-6c5b-49b9-b10d-415bac7e56ab.png">

**Comment by Kordishal** [comment]
Hi, this means that the categories have no or identical position weights assigned to them. This causes them to be arranged in a seemingly random order.

To resolve this issue select the categories and edit the number of the position in the category manually. Assigned different numbers to each category. They are ordered by the highest number on top. Once you've done this once the drag & drop should work as you would expect.

This issue will not be addressed as the interface will be replaced in the not so distant future.
