### ISSUE TITLE
Homebrew System Request: Final Beginning

### ISSUE THREAD

**Issue by alecells123** [worldanvil/worldanvil-bug-tracker#1397]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name (RPG SYSTEM)**: Final Beginning by Alec Ellsworth
**List Name** (Name under which it should be listed on World Anvil): Final Beginning
**World Anvil Username**: Alec_Ellsworth

**Website**: I use WorldAnvil as my site for now! 

**Logo Image Link**: Is there a placeholder I can use for now? 

**Logo Usage Terms (URL)**:

**Comment by iamromeo** [comment]
done :)

**Comment by alecells123** [comment]
> done :)

My god you guys are the best, thank you!
