### ISSUE TITLE
Manuscripts do not save formatting without editing text

### ISSUE THREAD

**Issue by JRCSalter** [worldanvil/worldanvil-bug-tracker#1400]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: JRCSalter

**World / Campaign / RPG Character / Manuscript Title**: Calnis

**Feature**: Manuscript

**Operating System**: Ubuntu 20.04.5 LTS

**Browser**: Firefox 108.0

**Device / Device Model**: N/A

**Related URLS** (To public & visible pages, add screenshots otherwise): https://www.worldanvil.com/community/manuscripts/read/4862522009-jrcsalter-allison-s-defeat/1ad86bf4-2755-4f18-8ce9-5a19943b4baf

**Describe the Issue**
A clear and concise description of what the issue is.

When editing only the formatting of a manuscript, such as text alignment and paragraph style, the manuscript does not save the progress. To work around this, I can enter in a single character into the file, and then it triggers the save.

**To Reproduce**
1. Open a manuscript.
2. Open a file that already has text inside.
3. Change some formatting only. Such as the paragraph style or italics. Or insert a horizontal line.
4. Click the View button or navigate to the public manuscript page.
5. The formatting has not changed.
6. Go back to editing the document.
7. Type in a letter, then delete that letter.
8. Click the View button or navigate to the public manuscript page.
9. The formatting has now changed.

**Expected behavior**
I expect the file to save whenever changes are made to any part of the manuscript; not just the text, but the look and style of the manuscript as well.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Deleyna** [comment]
I think this may be related to my prior issue #1353 - we were having problems with things not saving. We *were* predominantly working on formatting at the time. We started using control-s to trigger the save. (OP - it *does* trigger the save) Even though that isn't set up to work, I think this issue may be why we wandered down that rabbit hole.

**Comment by iamromeo** [comment]
that is true it is the same functionality - that will change on the next version of the editor
