### ISSUE TITLE
Cannot see text with Plato text editor

### ISSUE THREAD

**Issue by Dragon232347** [worldanvil/worldanvil-bug-tracker#1402]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: CalmDragon 

**Feature**: Plato text editor 

**Operating System**: ChromeOS 

**Browser**: Google Chrome 

**Device / Device Model**: Chromebook

**Describe the Issue**
You cannot see the text you are editing with the Plato editor on a free account due to the default text color being black and the Pluato background being black.

**To Reproduce**
1. Set text editor to Plato
2. Go to any page that has the text editor
3. Type anything
4. See issue

**Expected behavior**
That I'd be able to see the text.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![210881537-54355d2f-7abf-4c49-9e98-c705e8d011b5](https://user-images.githubusercontent.com/122056448/210882446-293dbed3-5bc1-44e8-bf90-269755ea6571.jpg)

**Comment by Kordishal** [comment]
Hi, I cannot reproduce this on any of the three themes. 

![image](https://user-images.githubusercontent.com/14262536/210884914-7e84aa99-07b6-4376-baa8-34f0e305223f.png)
![image](https://user-images.githubusercontent.com/14262536/210885140-95041bdf-d557-4c48-832c-0326f0a3b4a1.png)

I suspect this is something on your end. Try CTRL+F5 to clear the cache. It might not be loading something correctly. Alternatively check if this issue persists in a private window. If it does not that would mean that it is an issue with an extension of yours.
