### ISSUE TITLE
Calendar UI/UX issue when adding weekdays/months

### ISSUE THREAD

**Issue by SyntaxChick** [worldanvil/worldanvil-bug-tracker#1405]
**World Anvil Username**: SyntaxChick

**World / Campaign / RPG Character / Manuscript Title**: Estia

**Feature**: Calendar

**Operating System**: Windows

**Browser**: Brave

**Device / Device Model**: Desktop

**Describe the Issue**
When adding days/weeks to the calendar, any unsaved information within the list is erased. This does occur for me on months as well.

**To Reproduce**
1. Go to Calendar
2. Create a new calendar
3. Name the first day of your week (do not go back up and hit save)
4. Click "add weekday"
5. Previously entered data disappears

**Expected behavior**
I would expect the data I've entered to still be there until I saved or left the page.

**Comment by Kordishal** [comment]
Hi, calendar issues will not be addressed as this feature is no longer activity developed. It is planned to replace the feature at some point in the future, but there is no ETA or public roadmap currently on that.
