### ISSUE TITLE
Savage Worlds Adventure Edition

### ISSUE THREAD

**Issue by drswagbelly** [worldanvil/worldanvil-bug-tracker#1406]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name (RPG SYSTEM)**: Savage Worlds Adventure Edition
**List Name** (Name under which it should be listed on World Anvil): Savage Worlds Adventure Edition
**World Anvil Username**:  docswagbelly 

**Website**:

**Logo Image Link**:

**Logo Usage Terms (URL)**:

**Comment by drswagbelly** [comment]
Please add!

**Comment by iamromeo** [comment]
Added :)
