### ISSUE TITLE
Clicking article editor formatting buttons doesn't mark editor as dirty or auto-save

### ISSUE THREAD

**Issue by LuckyHyena** [worldanvil/worldanvil-bug-tracker#1408]
**World Anvil Username**:
LuckyHyena

**World / Campaign / RPG Character / Manuscript Title**:
Any

**Feature**: 
Article Editor

**Operating System**:
Windows 11

**Browser**:
Microsoft Edge

**Describe the Issue**
Clicking the formatting buttons in the article editor doesn't mark the editor as "dirty" with changes. The article doesn't auto-save after a click, and even if I click the "Save changes" button the formatting is not applied.

**To Reproduce**
1. Open any article with text
2. Use the mouse to select some text and click a format button like bold or underline. Do not type anything with the keyboard.
3. Observe there is no automatic "Saved" popup
4. Click Save changes and observe the "Saved" popup
5. Click View
6. The rendered article does not have the updated formatting

**Expected behavior**
Clicking any format button that modifies the text should cause an auto-save as if a key has been pressed.

**Comment by iamromeo** [comment]
That is true but not a bug - it is a lack of a feature that it will be addressed on the next version :)
