### ISSUE TITLE
Update Discord button not functioning.

### ISSUE THREAD

**Issue by MegaphoneMan0** [worldanvil/worldanvil-bug-tracker#1410]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**:
MegaphoneMan0
**World / Campaign / RPG Character / Manuscript Title**:
All
**Feature**: 
Update Discord in article
**Operating System**:
Windows
**Browser**:
Opera GX and Edge (likely others, these are the only ones I tested though)
**Device / Device Model**:
Mobile and Desktop
**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.
When I click the Update Discord button on any article, nothing happens. It doesn't even pop up the little green notification. I asked about it in the World Anvil discord help section, and another member confirmed that they were also experiencing this bug. This bug started sometime after yesterday (1/9) at 7PM, or potentially right around then.
**To Reproduce**
1. Go to 'any article'
2. Click on 'Update Discord'

**Expected behavior**
I expect a small update to appear in the channel I have bound the webhook to.
**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by MegaphoneMan0** [comment]
Update: the Webhook seems to have gone through at 3:39AM this morning. I was very asleep at this point, and only one of the many that I sent went through.

**Comment by iamromeo** [comment]
This is a Discord issue not a World Anvil issue but we will investigate just in case.
