### ISSUE TITLE
Attempts to delete a Hero are failing

### ISSUE THREAD

**Issue by moonflower-writer** [worldanvil/worldanvil-bug-tracker#1411]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: moonflower-writing

**World / Campaign / RPG Character / Manuscript Title**: Kaimon Ulric

**Feature**:  Heroes deletion

**Operating System**: Windows 10

**Browser**: Firefox

**Device / Device Model**: Laptop?

**Related URLS** (To public & visible pages, add screenshots otherwise):
https://www.worldanvil.com/hero/9d8e4c25-6a8c-4610-9503-55637c9aa828
https://cdn.discordapp.com/attachments/380013392653451264/1062560350513418370/2023-01-10_2.png
https://cdn.discordapp.com/attachments/380013392653451264/1062560753762185286/2023-01-10_3.png

**Describe the Issue**
A clear and concise description of what the issue is.

I (moonflower) ejected a Hero (well, all Heroes) from a campaign and deleted the campaign. A few weeks later, a player of mine (EtherianWorkshop) tells me that they cannot activate or delete the Hero that was ejected.

**To Reproduce**
1. Add a character to a campaign
2. Eject the character from the campaign
3. Delete the campaign
4. Attempt to access the character for deletion

**Expected behavior**

I expected to be able to access the character or at least be able to delete it.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
See "Related URLs"

**Comment by iamromeo** [comment]
You have ejected them from the campaign but ... have you removed them from your world?

**Comment by moonflower-writer** [comment]
I am unsure of how to do that when I cannot access the character. When the player accesses the character, the following screenshot is an example of what happens:
https://cdn.discordapp.com/attachments/964219220445515866/1062691493841743872/Screenshot_20230111-051440_Chrome.jpg

I really have no clue what's going on, but I was told it seemed like a bug

**Comment by Kordishal** [comment]
That is expected. You have to expel the character from the world. It is not possible for the player to leave the world. 

Open the world and then go to Player Characters under advanced tools.

**Comment by moonflower-writer** [comment]
Very sorry about this. Found what you're talking about, and it worked.
