### ISSUE TITLE
Homepage changes sometimes doing a rollback of previous changes (with multiple tabs)

### ISSUE THREAD

**Issue by RubenVDBr** [worldanvil/worldanvil-bug-tracker#1413]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**:
RubenVDB

**World / Campaign / RPG Character / Manuscript Title**:
Lotharren

**Feature**: 
Saving in Homepage custom content

**Operating System**:
Windows

**Browser**:
Google chrome

**Device / Device Model**:

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
Sometimes when I edit something in the homepage and then save, go do something else in another tab (like edit the css) and then I go back to edit something again in the homepage it sometimes reverts changes. For example, I had 4 images on my screen and they each had a header. I remove the h2's and borders. Do some editing in my css for about 5min, then go back to add another picture in my homepage and when I save suddenly I notice the headers are back with the borders. 

**To Reproduce**
I think this has something to do with me having lots of tabs of my world open maybe? I'm honestly not sure, I do have my css and homepage custom content both open at all times. This has happened about 4-5 times now and I'm fairly new to the platform.

**Expected behavior**
I expected it not to rollback some changes.

**Screenshots**

**Comment by Kordishal** [comment]
You are overwriting the changes. The CSS editor on the presentation also edits the World Configuration. Reload the page before saving that!
