### ISSUE TITLE
Problem with article visualization

### ISSUE THREAD

**Issue by Caca-Tecover** [worldanvil/worldanvil-bug-tracker#1414]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Caca_Tecover

**World / Campaign / RPG Character / Manuscript Title**: World: Desordem Demoníaca. Category: Divindades e Lordes Demônios. Article: Demogorgon

**Feature**: Articles

**Operating System**: Windows 11

**Browser**: Google Chrome

**Device / Device Model**:

**Related URLS** (To public & visible pages, add screenshots otherwise): https://www.worldanvil.com/w/desordem-demoniaca-cacatecover/a/demogorgon-person

**Describe the Issue**
Hello, I got a problem in viewing my article. The first image is how it looks when my cursor is out of the page. It has a darker part in it, and the strange thing is that it only happens in this article, and no other I have.
The second image is for when my cursor is on the darker part. The part that already was kinda hard to see becomes completely gray and I can't see anything.
The gray part seems to be a part of the article, because when I scroll down, it goes up together with it
The third image is what it looks when I have my cursor in the page and am in the middle of the article

**To Reproduce**
1. Go to the Article "Demogorgon" in the category "Divindades e Lordes Demônios" that is under the category "Enciclopédia" that is in the World "Desordem Demoníaca"
2. See error

**Expected behavior**
As with any other articles I have, I expected to not see a solid color obstructing what I wrote.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/122759472/212577546-4f417461-5c90-42cd-86b6-a1f7cbb90d1e.png)
![image](https://user-images.githubusercontent.com/122759472/212577555-5e169808-131f-4c7d-a970-cd20e121ed5e.png)
![image](https://user-images.githubusercontent.com/122759472/212577571-736ff0ab-6c65-41c2-a9b9-2c8e66763839.png)

**Comment by Kordishal** [comment]
Did you fix the issue? I cannot confirm it. It might be the view is only broken for you. Try resolving the issue by pressing CTRL+F5 making a hard refresh (if you use Firefox or Chromium based browser). If that doesn't work then see if the problem appears in a private / incognito page. If it doesn't appear there then the issue is caused by an extension of yours.

![image](https://user-images.githubusercontent.com/14262536/212633800-01329f06-e8d6-4031-83a5-d1fa27982da2.png)

**Comment by Caca-Tecover** [comment]
I didn't fix it. I tried the Ctrl+F5, and it didn't work, then I opened the page in icognito, and it worked. So I deleted all extensions I have, and then hard refresh it, and still. 
One thing I found: when I refresh the page, obviously it doesn't all load at the same time, and the dark part loads after the article. For a moment the article shows perfectly, and after it the dark part comes. Have no idea what it is. 
Also, thanks for the help.

**Comment by Kordishal** [comment]
Which browser are you using? If it worked in incognito then a cache or extension issue is the most likely culprit? Maybe try deleting all the data related to World Anvil?

**Comment by Caca-Tecover** [comment]
https://drive.google.com/file/d/1G8-8-kyLkXmRulI2TH8QJuxX54XPX0TG/view?usp=sharing

I made a video showing my problem (I made the loading parts faster in editing).
It's show that I really don't have any extesions and am using Chrome, I also opened it in icognito and showed that it works there.

I don't know how I would delete all the data realted to World anvil. Can you show me? Thanks in advance

**Comment by Caca-Tecover** [comment]
https://drive.google.com/file/d/1G8-8-kyLkXmRulI2TH8QJuxX54XPX0TG/view?usp=sharing

I made a video showing my problem (I made the loading parts faster in editing).
It's show that I really don't have any extesions and am using Chrome, I also opened it in icognito and showed that it works there.

I don't know how I would delete all the data realted to World anvil. Can you show me? Thanks in advance 

(By the way, I closed it in accident)

**Comment by Kordishal** [comment]
Does this only happen on the Demogorgon article?

**Comment by Caca-Tecover** [comment]
Yes. I can see articles I didn't write and all other articles I wrote perfectly.

**Comment by Kordishal** [comment]
Ok I see you have a secret attached to this article. It is very likely that this is causing the issue as it would explain all the symptoms we are seeing.

Try removing the secret from the article. If it fixes the issue check inside the secret. There is probably an unclosed BBCode tag in there.

**Comment by Caca-Tecover** [comment]
Thank you, it was the secrets. Now I can see it properly.
