### ISSUE TITLE
Something Didn't Save Properly

### ISSUE THREAD

**Issue by Stormhaven13** [worldanvil/worldanvil-bug-tracker#1415]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Stormhaven13

**World / Campaign / RPG Character / Manuscript Title**: The Severed Expanse

**Feature**: 

**Operating System**: Windows

**Browser**: Firefox

**Device / Device Model**:

**Related URLS** (To public & visible pages, add screenshots otherwise): https://www.worldanvil.com/w/the-severed-expanse-stormhaven13/a/azar-article?preview=true

**Describe the Issue**
Something didn't save properly, as about half of my information written is gone, and for some reason it is things I wrote earlier, not later. Things I wrote later are still there, other information seems to have been deleted

**To Reproduce**
One Time Process

**Expected behavior**
If the program failed to save, I would expect the latest pieces of information to have been deleted rather than older pieces of writing.

**Screenshots**
N/A

**Comment by Kordishal** [comment]
Hi, that most likely means you overwrote the text you wrote earlier with a new save. This can happen when you for example switch devices and use an old tab where you didn't load the changes you made, or if you have the editor of the article open twice in the same browser and then switch without reloading the tab to update the content.

Make sure that you always reload editors before making changes to ensure that the data is current. Unfortunately there isn't anything that can be done to restore the older data. This will likely change in the future.
