### ISSUE TITLE
Articles / Horizontal Navigation: shows uuid instead of label when shown in map sidebar

### ISSUE THREAD

**Issue by Tillerz** [worldanvil/worldanvil-bug-tracker#1416]
**World Anvil Username**: Tillerz

**World / Campaign / RPG Character / Manuscript Title**: 

**Feature**: Article Horizontal Navigation when in Map Sidebar

**Related URLS** (To public & visible pages, add screenshots otherwise): https://www.worldanvil.com/w/alana/map/8e637fec-d8df-46fc-912d-4201e4dc5713

**Describe the Issue**
The article hoizontal navigation bars are broken when shown in the map sidebar (after clicking a map marker with linked article):

![5b722ae673157fd4ce40489d8f786f4b](https://user-images.githubusercontent.com/63370525/212874488-5914ba59-315e-4e44-bde8-5ac7e68c498c.png)

**To Reproduce**
1. Open map: https://www.worldanvil.com/w/alana/map/8e637fec-d8df-46fc-912d-4201e4dc5713
2. Enable "Points of Interest"
3. Click the ruin "Citadel of Shartol" right underneath the Copper Mountain
4. Check the output in the sidebar (see screenshot)

**Expected behavior**
Show the article names instead of the article uuids.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Moving to new platform: https://www.worldanvil.com/udan-tracker/5da5c858-6485-4bbd-a67d-cc81f6d2c180/view
