### ISSUE TITLE
Missing reference in the "Referenced In..." feature (Article Advanced Tools & Options)

### ISSUE THREAD

**Issue by Utar94** [worldanvil/worldanvil-bug-tracker#1418]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: fpion

**World / Campaign / RPG Character / Manuscript Title**: Jourungar

**Feature**: Article Referenced In...

**Operating System**: Windows 11 Pro

**Browser**: Microsoft Edge Version 109.0.1518.55 (Official build) (64-bit)

**Device / Device Model**: PC

**Related URLS** (To public & visible pages, add screenshots otherwise):

- https://www.worldanvil.com/w/jourungar-fpion/a/isharata-location
- https://www.worldanvil.com/w/jourungar-fpion/a/norrigor-location

**Describe the Issue**
In the first article, **Isharata**, the **Norrigor** location (second article) is referenced in the "Geography" section (under "Show Template Specific Prompts & Connections"). The reference bbcode is `@[Norrigor](location:cfbf965d-5014-4ac0-8e93-aad1b3bc3978)`.

When I click the "Load References List" button in the **Norrigor** edit page, the result is "No matches found". When I move the reference bbcode in the main content editor of the **Isharata** article, then click the "Load References List" button, I can see the article **Norregor** is now referenced in the **Isharata** article.

**To Reproduce**
1. Create a first article, let's say a location.
2. Create a second article, a location again.
3. In the second article, under "Show Template Specific Prompts & Connections" in the "Geography" section, reference the first article.
4. Click the "Load References List" button in the first article "Advanced Tools & Options".

**Expected behavior**
Links created in Template Specific Prompts should also be indexed, so the "Load References List" button would display all references to the article, including reference in Template Specific Prompts.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Same here. Referenced in does not search template specific prompts. Only the generic prompts.
