### ISSUE TITLE
Full Search doesn't include Template Specified Prompts

### ISSUE THREAD

**Issue by Utar94** [worldanvil/worldanvil-bug-tracker#1419]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: fpion

**World / Campaign / RPG Character / Manuscript Title**: Jourungar

**Feature**: Article Full Search

**Operating System**: Windows 11 Pro

**Browser**: Microsoft Edge Version 109.0.1518.55 (Official build) (64-bit)

**Device / Device Model**: PC

**Related URLS** (To public & visible pages, add screenshots otherwise):

- https://www.worldanvil.com/w/jourungar-fpion/a/norrigor-location

**Describe the Issue**
In the article list page, the **Full Search** function includes the main article content, but doesn't search in "Template Specific Prompts".

**To Reproduce**
1. Create an article, let's say a location.
2. Type the word "potato" in the main article content.
3. Go back to the article list page, then check the "Full Search" option and search the term "potato". The article created in 1 will be found.
4. Return to your newly created article. Move the word "potato" from the main article content, to the "Geography" section under "Template Specific Prompts & Connections".
5. Go back to the article list page, then check the "Full Search" option and search the term "potato". The article created in 1 now won't be found.

**Expected behavior**
Template Specified Prompts should be indexed, so Full Search would be able to search in those fields also.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
This is working as intended. The Full search only includes generic prompts.
