### ISSUE TITLE
Unable to access players' character sheets via API

### ISSUE THREAD

**Issue by adajd** [worldanvil/worldanvil-bug-tracker#142]
**World Anvil Username**: AdaJDouglass

**Campaign Title**: Travels of the Frozen Hourglass

**Feature**: Aragorn API

**Related URLS** (To public & visible pages add screenshots otherwise): All related pages are set to private, as far as I'm aware.

**Describe the Issue**
You recently gave me access to the Aragorn API, which I had intended to use in a Python script (as part of a Discord bot) to automatically fetch the stats of the player characters in my RPG campaign. However, while I am able to access NPC statblocks through the API, attempting to access a player character's statblock results in a 403 error and a return value of None.

**To Reproduce**
1. Run the attached Python script (I'm not including my .env file since other users can see this, but I'd imagine you're able to look up my API keys).
[travlr_worldanvil_test.py.zip](https://github.com/worldanvil/worldanvil-bug-tracker/files/6283077/travlr_worldanvil_test.py.zip)
2. Look at the output, see how it displays the NPC's stat block, but for the PC's it just shows "<class 'NoneType'> None", even though the same code is used for both.

**Expected behavior**
I expected to be able to access statblocks for both PCs and NPCs through the API.

**Screenshots**
![PC Statblocks - WorldAnvil Website](https://user-images.githubusercontent.com/68634926/114126689-c9f56980-98ad-11eb-9ae3-d70e58eb1fa9.jpg)
![NPC Statblocks - WorldAnvil Website](https://user-images.githubusercontent.com/68634926/114126694-ccf05a00-98ad-11eb-969c-0dda61020068.jpg)
![Rosa Statblock - WorldAnvil API](https://user-images.githubusercontent.com/68634926/114126699-d11c7780-98ad-11eb-9226-24a52cf4986f.jpg)
![Bao Statblock Fail - WorldAnvil API](https://user-images.githubusercontent.com/68634926/114126703-d24da480-98ad-11eb-9f3c-85ccf7d1fb3e.jpg)
![Bao Statblock - WorldAnvil Website](https://user-images.githubusercontent.com/68634926/114126709-d4176800-98ad-11eb-867b-3da45a1bb039.jpg)

**Comment by Kordishal** [comment]
This is not an issue in the API, but instead an issue in the python client written by me. None is returned if there is an error on retrieving the content requested. This is due to the error handling of the API being not very helpful at the moment (it returns a HTML page that I would need to parse).

My most likely guess would be that you do not have access permissions to those sheets. The second issue could be that they are old Statblock System 1.0 Blocks which cannot be retrieved by the API at this time.

**Comment by Kordishal** [comment]
if you continue to have issues please contact me on Discord (SoulLink, Development Gremlin) or open an issue [here](https://gitlab.com/SoulLink/world-anvil-api-client).

**Comment by adajd** [comment]
Sorry, I couldn’t find you on Discord. 

The problem isn’t with your Python library, because I tried it with the standard ‘requests’ library too, and kept getting 403 errors. If I don’t have access permission for those sheets, how do I *get* access permission for those sheets? That’s the real issue here.

**Comment by Kordishal** [comment]
To get permission the players need to set their sheets to visible. 

![image](https://user-images.githubusercontent.com/14262536/114262539-d201f600-99e0-11eb-9f03-c23db3b5ad02.png)
They need to tick this box at the bottom of the sheet. However, I haven't tested this yet, so if this doesn't work then you just can't access the blocks of other people.

**Comment by adajd** [comment]
That seems to have worked! Thank you!
