### ISSUE TITLE
Whiteboard connection issue

### ISSUE THREAD

**Issue by LadyGrayish** [worldanvil/worldanvil-bug-tracker#1420]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Lady Grayish

**World / Campaign / RPG Character / Manuscript Title**: Campaigns Assorted

**Feature**:  Whiteboards

**Operating System**: Windows (I think 11, whatever's the newest one as of Jan 2023)

**Browser**: Mozilla Firefox

**Device / Device Model**: Acer Swift 3 laptop

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

My whiteboards will not load. Near as I can tell, the rest of the website is loading fine. When I try to open a whiteboard, it brings up the page and all it shows is a blank page with a blue "reconnecting" box at the top of the screen. Reloading does nothing. I have repeated this for two whiteboards. Both of them definitely were not blank before. I haven't accessed either one in a few months now.

I discovered this because a whiteboard linked in an article was showing as blank. The article loaded fine itself (https://www.worldanvil.com/w/campaigns-assorted-lady-grayish/a/pilot3A-the-space-between-plot?preview=true) just not the whiteboard.

**To Reproduce**
1. Go to 'Whiteboards'
2. Click on 'Any Edit Whiteboard button'
3. See error (blank whiteboard with blue "reconnecting" pop-up at the top of the screen.

**Expected behavior**

I expected to open the whiteboards and see a series of text boxes and links and such.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

![Whiteboards 2023](https://user-images.githubusercontent.com/123099598/213492906-3d61a16f-d5df-4394-9c00-84451fc84879.png)

**Comment by jseara** [comment]
Also experiencing this bug.

**Comment by BasicRin** [comment]
I also have the same problem, I use Chrome.

**Comment by Deleyna** [comment]
I'm also having it, and last night it was loading fine. I use Firefox.

**Comment by iamromeo** [comment]
This is a known issue - we will be working on it today - The server had a hiccup.

**Comment by GorkamWorka** [comment]
Phidias is back online, the deployment of new code triggered a server issue, This has been now resolved.
Thanks for reporting.
