### ISSUE TITLE
Character list on world page showing old characters

### ISSUE THREAD

**Issue by NorEtoc** [worldanvil/worldanvil-bug-tracker#1421]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**UserName**:Noretoc

**World Name**:Nor

**Feature**: World Homepage

**System**:Win 10

**Browser**:All

**[Related URLS]**:(https://www.worldanvil.com/w/nor-noretoc)

**Describe the Issue**
There are characters showing up in the character list that have been ejected from all campaigns and in one case was never in one of the campaigns.  Examples: Dylan Lionheart - Removed form Dragon Dominion Campaign; ee - removed from Society Campaign; Ser. Tiberius Validius - was never a part of any campaign that I rememeber.  Just a character belonging to one of my players.

**Expected behavior**
Should only show character currently in campaigns. (Thought i wish it would only show character in one campaign)

**Screenshots**
![image](https://user-images.githubusercontent.com/93835536/213612742-b1cf45d7-98dd-4ca7-92d2-9d9cc8beb390.png)
![image](https://user-images.githubusercontent.com/93835536/213612840-d4341cc0-e7a2-4fde-bae1-d9c9206d324b.png)
![image](https://user-images.githubusercontent.com/93835536/213612880-fc18afab-393e-47cc-b1e0-b90ce54d12d2.png)

**Comment by Kordishal** [comment]
Hi they are displayed because they are still in the world most likely. Under Advanced Tools open Player Characters and expel the old characters from there.

**Comment by NorEtoc** [comment]
If you mean the advanced tools of the **campaign** as I stated in the original ticket, they have been expelled already and as the screen shots show, they are **not** list under characters in the campaign.  
There is no Player character option under advanced tools in the **world** setting.

**Comment by Kordishal** [comment]
There normally is a Player Characters page under advanced tools.

![image](https://user-images.githubusercontent.com/14262536/213807268-ae652eaf-927f-4e38-88db-ff0a3624a0ba.png)

Did you activate just the world?

Alternatively search the characters in the Articles interface and expel them from there.
