### ISSUE TITLE
Ruler/Owner prompt of Location article not displaying in character article

### ISSUE THREAD

**Issue by sdegeiso** [worldanvil/worldanvil-bug-tracker#1422]
**World Anvil Username**: Goose80

**World / Campaign / RPG Character / Manuscript Title**: Asteria

**Feature**: BUILDING/LANDMARK Article Template prompt display within Character article

**Operating System**: Windows 10 / Android 13

**Browser**: Chrome

**Device / Device Model**: N/A

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
The Ruler/Owner of a location does not show up on the character article like Additional Rulers/Owners does. 

**To Reproduce**
1. Link a Character Article as the Ruler / Owner of a location
2. View Character Article and notice nothing shows
3. Link another Character Article as the Additional Ruler/Owners
4. View this other Character Article to see it shows up under Ruled Locations

**Expected behavior**
The Character Article to list the Articles where the Character is the owner. Since Additional Rulers/Owners show up, i would expect it to be listed there. Since it is not, it is confusing to find what the character actually owns.

**Screenshots**
Example Scenario from my world. Brother (Furk) / Sister (Belina) Each are listed as Owners of their respective Taverns in their building article. However, their Character Articles make it look like they only own the Tavern from the wrong town.

Furk Owns Siren's Tear Tavern - Auknes, but only Siren's Tear Tavern - Lakenes Shows
![Furk Block](https://user-images.githubusercontent.com/51136800/213703572-1354f7b4-5cc9-4b08-be32-f5652f8dac81.jpg)

Belina Owns Siren's Tear Tavern - Lakenes, but only Siren's Tear Tavern - Auknes Shows
![Belina Block](https://user-images.githubusercontent.com/51136800/213703899-1ed471fa-bcff-409c-940b-f84aebb50ef3.jpg)

Siren's Tear Tavern - Lakenes article block for reference
![Lakenes](https://user-images.githubusercontent.com/51136800/213705003-83c4495b-4e2b-4733-981c-ec1014140360.jpg)

Siren's Tear Tavern - Auknes article block for reference
![Auknes](https://user-images.githubusercontent.com/51136800/213705035-1fda6d21-41c3-442e-a98c-279abe8563ba.jpg)

**Comment by katerinach** [comment]
@sdegeiso the Ruled Location section now also displays a location where a character is the Onwer/Ruler (primary and secondary ownership is devided by a dotted line)
