### ISSUE TITLE
Pricing Page Typo

### ISSUE THREAD

**Issue by BTStolle** [worldanvil/worldanvil-bug-tracker#1423]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: BTStolle

**World / Campaign / RPG Character / Manuscript Title**: N/A

**Feature**: Pricing Page

**Operating System**: Any (found in Windows 11 and iOS 16.1.1)

**Browser**: Any (found in Chrome)

**Device / Device Model**: Any (found on PC and iPhone)

**Related URLS** (To public & visible pages, add screenshots otherwise):
https://www.worldanvil.com/pricing

**Describe the Issue**
A clear and concise description of what the issue is.
Typo:
“What you're purchasing is a recurring subscription, which means **you will be charged you** today and continue to be charged for your chosen period until you cancel your subscription.”

**To Reproduce**
1. Go to “Pricing”
2. Scroll down to the bottom of the page
4. See typo

**Expected behavior**
I would expect to see “you will be charged” or “we will charge you.”

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Fixed! Thank you - will deploy today :)
