### ISSUE TITLE
Pricing Page Tooltip Typo

### ISSUE THREAD

**Issue by BTStolle** [worldanvil/worldanvil-bug-tracker#1424]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: BTStolle

**World / Campaign / RPG Character / Manuscript Title**: N/A

**Feature**: Pricing Page

**Operating System**: Any (found in Windows 11 and iOS 16.1.1)

**Browser**: Any (found in Chrome)

**Device / Device Model**: Any (found on PC and iPhone)

**Related URLS** (To public & visible pages, add screenshots otherwise):
https://www.worldanvil.com/pricing

**Describe the Issue**
A clear and concise description of what the issue is.
Typo:
“Define **it’s** content using a super easy form…”

**To Reproduce**
1. Go to “Pricing”
2. Click on tooltip next to “RPG CHARACTER SHEET DESIGNER TOOLSET”
4. See typo

**Expected behavior**
I would expect to see “Define its content using a super easy form…”

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
thank you for the heads up
