### ISSUE TITLE
Timeline entries are buggy when adding @links

### ISSUE THREAD

**Issue by msz89** [worldanvil/worldanvil-bug-tracker#1427]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**:
MatthewSzwec

**World / Campaign / RPG Character / Manuscript Title**:
Echilburu
https://www.worldanvil.com/w/echilbiru-matthewszwec/t/echilbiru-development-changelog

**Feature**: 

**Operating System**:
Windows 10

**Browser**:
Chrome

**Device / Device Model**:
Dell XPS 13

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
When adding @links into the historical events strange things happen.
I have tried to make a bulleted list of the articles I worked on this week.
The colour of the text changed, some of the events dissapeared and the links don't display correctly.
At one point I even had the 'event' bubble on the RHS of the timeline and the text on the LHS.

**To Reproduce**

**Expected behavior**
I expect to be able to use bullets and @links to my articles in timelines

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
<img width="399" alt="Capture" src="https://user-images.githubusercontent.com/30629973/213904828-03feaba3-9629-4059-b0c9-2137c54ecd40.PNG">

**Comment by Kordishal** [comment]
This us due to the list and not the mention link. The timeline itself is a list as well, so the browser cannot display this properly in most cases. Avoid using them in historical events.
