### ISSUE TITLE
Category and article from someone else's world appearing in my world

### ISSUE THREAD

**Issue by illumiinae** [worldanvil/worldanvil-bug-tracker#1428]
**World Anvil Username**: illumiinae

**World**: Aidonia

**Feature**: Articles/Categories

**Operating System**: Windows 11

**Browser**: Chrome

**Describe the Issue A clear and concise description of what the issue is.**

A category called "Nation Atlas" appeared in my world despite me not creating it and none of the writers for my world having access to category creation. It contains the "Introduction to the Atlas" article in it, but I can't click on the article to view a preview, and trying to open it in-world leads to a 404 error. When hovering over the article from my dashboard, the url shows that it's not actually an article in _my_ world, it's an article in a world I follow and have an RPG character in.

**To Reproduce Steps to reproduce the behavior:**

Unsure, I just noticed it had appeared when I refreshed the page.

Screenshots:

This is the url that shows up when I hover over the article, and the new article and category with my other ones.

![url](https://user-images.githubusercontent.com/118077295/213942808-45322eef-2e41-4d1f-8d57-c085a69ea6bf.png)
![article](https://user-images.githubusercontent.com/118077295/213942914-18abc532-416f-4c1d-a8a6-f5a8c0cd6167.png)

**Comment by iamromeo** [comment]
This is not a bug, one of your co-authors had two windows open one on their world and one yours changed worlds and after doing so moved a folder. Ask your co-authors :)
