### ISSUE TITLE
I am receiving the error 404 “you have reached the end of your world” message whenever i try to access my character sheet.

### ISSUE THREAD

**Issue by MalacathStrumblthrumb** [worldanvil/worldanvil-bug-tracker#1429]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**:
neilthomascarrick@gmail.com
**World / Campaign / RPG Character / Manuscript Title**:
Malacath Strumblethrumb
**Feature**: 
Character sheet/Profile
**Operating System**:
ios
**Browser**:
google chrome
**Device / Device Model**:
ipad 7
**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.
Whenever i try and “view” my character sheet, i am redirected to the “Error 404” “you have reached the end of your world” page. I can still edit the sheet, and all the information is still available there and changable/saveable; but i cannot view it in its intended “usable” format.
**To Reproduce**
1. Go to 'choose world/character in side-bar menu. select Malacath.'
2. Click on 'Sheet, or Malacath'

**Expected behavior**
I would expect to be able to select either the “sheet” option or “malacath” character profile options to be brought to my “player character sheet” in its inteded playable format; IE usable during a game session. but instead i am redirected and receive the “Error 404”

**Screenshots**
![B07D8E6D-985F-424D-96FE-B135094D078C](https://user-images.githubusercontent.com/123402337/214110200-9dbad094-e464-4eac-a668-6b6717f2f0d1.png)
**we begin at the world anvil home navigation page, i have my Character selected in the navigation side bar; so all of his content should be loaded and ready to be viewed
![BEB64B63-0D2A-4C52-93E7-4450ACB725A5](https://user-images.githubusercontent.com/123402337/214110219-b0e14836-0613-4e84-9d11-b77edc3315b8.png)
One i select either the “Malacath” option to bring up the general character profile with the sheets and everything available; or the “Sheet” option to go directly to the character sheet, i am immediatly redirected to the “Error 404” page.

**Comment by MalacathStrumblthrumb** [comment]
Sorry i should have also noted that i am able to edit the sheet/view its contents throught the stat Block button, but that this is not a “playable” version of the sheet and its contents.

**Comment by MalacathStrumblthrumb** [comment]
It also appears to only be effecting the “Malacath Strumblethrumb” character sheet.

**Comment by Kordishal** [comment]
Hi, this means there is an error with the data you added to the statblock. So if you remove content that causes the issue it will be viewable again. Without knowing which template you are using or what the content is I cannot really assist in narrowing it down, but you could just remove content from one field after the other. Start with the most complex content and work your name down.

Furthermore statblock templates are created by the community. So if there is a bug then only the creator of that template would be able to fix it and not the world anvil team.
