### ISSUE TITLE
Can not delete world

### ISSUE THREAD

**Issue by ConquestPublishing** [worldanvil/worldanvil-bug-tracker#1431]
After trying to delete world(Earth) get the attached and it's not deleted.

**World Anvil Username**:Conquest Publishing

**World / Campaign / RPG Character / Manuscript Title**:Earth

Windows 10

Chrome

![404wa](https://user-images.githubusercontent.com/123667648/214937036-2314a1f1-a95d-4f1c-b11d-c8a6195d36f3.png)

**Comment by iamromeo** [comment]
Hey there @ConquestPublishing have you followed the instructions and removed subscribers/subscriber groups and other authors?

**Comment by ConquestPublishing** [comment]
Thanks but none of those entered.
   
   
   
    On 01/27/2023 12:04 AM EST Dimitris Romeo Havlidis ***@***.***> wrote:
    
   
     
    
   
     
    
     
   Hey there @ConquestPublishing have you followed the instructions and removed subscribers/subscriber groups and other authors?

**Comment by ConquestPublishing** [comment]
There are no subs/authors, the group that was auto created I tried to delete with the same error.
   
   
   
    On 01/27/2023 12:04 AM EST Dimitris Romeo Havlidis ***@***.***> wrote:
    
   
     
    
   
     
    
     
   Hey there @ConquestPublishing have you followed the instructions and removed subscribers/subscriber groups and other authors?

**Comment by ConquestPublishing** [comment]
Can the account be reset to fix this?

**Comment by iamromeo** [comment]
Hey there @ConquestPublishing accounts cannot be reseted but I will handle this for you - I will delete your world

**Comment by ConquestPublishing** [comment]
Thanks, we want a clean slate before we start entering the MMO/RPG bible into WA.  Will check on it soon.
   
   
   
    On 01/28/2023 2:02 AM EST Dimitris Romeo Havlidis ***@***.***> wrote:
    
   
     
    
   
     
    
     
   Hey there @ConquestPublishing accounts cannot be reseted but I will handle this for you - I will delete your world

**Comment by ConquestPublishing** [comment]
> Hey there @ConquestPublishing accounts cannot be reseted but I will handle this for you - I will delete your world

Any progress?

**Comment by iamromeo** [comment]
@ConquestPublishing you should be all set

**Comment by ConquestPublishing** [comment]
Thanks, off to make 2 MMO's.
   
   
   
    On 02/03/2023 11:13 AM EST Dimitris Romeo Havlidis ***@***.***> wrote:
    
   
     
    
   
     
    
     
   @ConquestPublishing you should be all set
