### ISSUE TITLE
Udan Tracker gives consistent 500 Internal Server Errors

### ISSUE THREAD

**Issue by 121GWJolt** [worldanvil/worldanvil-bug-tracker#1432]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: 121GWJolt

**World / Campaign / RPG Character / Manuscript Title**: N/A

**Feature**: [udan-tracker/](https://www.worldanvil.com/udan-tracker/)

**Operating System**: Windows 10

**Browser**: Firefox

**Device / Device Model**: Custom PC

**Related URLS** (To public & visible pages, add screenshots otherwise): [udan-tracker/](https://www.worldanvil.com/udan-tracker/)

**Describe the Issue**
When attempting to submit a bug report, I get a consistent 500 error from the server every time.

**To Reproduce**
1. Open new bug report screen
2. Fill out all the information as required
3. Press Report button

**Expected behavior**
It should let me successfully file a bug report instead of erroring and redirecting me to a 404 page.

**Comment by iamromeo** [comment]
Can you please give us the exact content you added to get a 500 error ? Have you used any emojis or special characters?

**Comment by 121GWJolt** [comment]
Title: (lost the exact title, but it was something like "Cannot delete Hero without removing character article from linked world" or something like that, might've been a bit longer)

Description:
> According to [url:https://www.worldanvil.com/w/WorldAnvilCodex/a/guide-to-character-creation]this page[/url] in the codex, I should be able to delete a character while leaving an article behind in the world. However, when I check the page and try to do this, no delete button is present until after I disconnect a character from the world, and after I do that, the character article is gone, too.
> 
> So, currently, despite what the codex says, I do not have a way to delete a Hero profile while leaving a character article behind in the world.

Related feature: "RPG Characters (Heroes)"
Operating System: "Windows"
Browser: "Firefox"

Related Element: [Left as-is because I couldn't link anything since everything was private; there seems to be some whitespace in the field by default for some reason? I tried to record it as-copied below, hopefully clipboard copied as-expected]

``` 
                ```                

Steps to reproduce:
> [ol][li]Create character[/li][li]Link character to world.[/li][li]Attempt to delete character (delete button is absent)[/li][li]Remove character from world; can now delete, but article is removed from the world at the same time as the hero[/li][/ol]

---

...Would you prefer I make the ticket for what I was trying to report via Udan here or wait until Udan lets me file this bug?

**Comment by iamromeo** [comment]
@katerinach "related entty cannot be null" - let's make sure it can be :) Also let's remover the white spaces :)

**Comment by katerinach** [comment]
@121GWJolt Bugs can now be created without a "Related Element" field without issue. Let me know if there's any further issue
