### ISSUE TITLE
Power Rangers/Essence 20 RPG addition

### ISSUE THREAD

**Issue by WookieeMatt** [worldanvil/worldanvil-bug-tracker#1433]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name (RPG SYSTEM)**: Essence 20
**List Name** (Name under which it should be listed on World Anvil): Essence 20
**World Anvil Username**: WookieeChan

**Website**: https://renegadegamestudios.com/blog/introducing-the-essence20-roleplaying-system/

**Logo Image Link**: https://renegadegamestudios.com/product_images/uploaded_images/essence20-logo-full.jpg

**Logo Usage Terms (URL)**: ?????

**Comment by iamromeo** [comment]
Essence 20 has been added :) Power Rangers seems like a flavour therefore it should be under one system
