### ISSUE TITLE
Requesting City of Mist RPG System

### ISSUE THREAD

**Issue by QHudspeth** [worldanvil/worldanvil-bug-tracker#1434]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name (RPG SYSTEM)**: City of Mist
**List Name** (Name under which it should be listed on World Anvil): City of Mist
**World Anvil Username**: QHudspeth

**Website**: https://cityofmist.co/

**Logo Image Link**: https://cdn.shopify.com/s/files/1/2508/6356/t/11/assets/logo.png?v=145723045754685312101604928642

**Logo Usage Terms (URL)**: ???

**Comment by iamromeo** [comment]
Hello there :) City of Mist is already in the list of RPGs you are more than welcome to create a sheet and when you do - please let me know so I can put it public for you and the rest of the community

**Comment by QHudspeth** [comment]
Thanks!
For some reason it wasn't coming up in the initial alphabetical drop 
down. But then I had the idea to start typing it to see if i could do a 
manual entry, and Lo! it appeared.

Q

--------------------------------------------------------------------------------
Quentin Hudspeth

3 Glenwood Terrace
Averill Park, NY   12018
518-937-8103
--------------------------------------------------------------------------------


------ Original Message ------
From "Dimitris Romeo Havlidis" ***@***.***>
To "worldanvil/worldanvil-bug-tracker" 
***@***.***>
Cc "QHudspeth" ***@***.***>; "Author" 
***@***.***>
Date 2/3/2023 1:01:56 AM
Subject Re: [worldanvil/worldanvil-bug-tracker] Requesting City of Mist 
RPG System (Issue #1434)
