### ISSUE TITLE
RPG for World Anvil inclusion

### ISSUE THREAD

**Issue by EpicQuill** [worldanvil/worldanvil-bug-tracker#1435]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name**: The Veil
**List Name**: The Veil
**World Anvil Username**: Steve Kraus

**Website**:  https://samjokopublishing.com/products/the-veil-cyberpunk-ttrpg

**Logo Image Link**:  https://www.worldanvil.com/i/4184177

**Logo Usage Terms (URL)**:  Unable to find on website or within their book.  Author can be reached at SAMJOKOPUBLISHING@GMAIL.COM

**Comment by iamromeo** [comment]
All done
