### ISSUE TITLE
Storyteller Content not saving correctly

### ISSUE THREAD

**Issue by Arnold-Muralt** [worldanvil/worldanvil-bug-tracker#1436]
When writing a plot using the Story teller prompts, I go and save the plot, and publish the page, when I go to view the  article, the non-story teller materials are where they should be but upon opening the storyteller content section, much of my work is missing.

**Comment by Arnold-Muralt** [comment]
I am accessing world anvil from Firefox, on Win 10

**Comment by Kordishal** [comment]
Hi there is currently an ongoing issue with the save. 

https://www.worldanvil.com/udan-tracker/bf317cf8-bd0b-45fa-8ebc-ebcb0e86c3a9/view

I will close this issue as we are no longer using this platform for bug reports.
