### ISSUE TITLE
Whiteboard: 2 problems: text mode switching to select mode & arrow placing rotating around instead of following mouse within a square shape

### ISSUE THREAD

**Issue by AbbieWolff** [worldanvil/worldanvil-bug-tracker#1437]
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: abbie-

**World / Campaign / RPG Character / Manuscript Title**: "Not-Yet-Titled" World

**Feature**: Whiteboard

**Operating System**: Windows 10 Home, 64-bit OS
version 22H2
installed on 3/26/2021
OS build 19045.2586
Windows Feature Experience Pack 120.2212.4190

**Browser**: Google Chrome web browser, up-to-date

**Device / Device Model**: Dell XPS 8700 desktop PC; i7-4790 CPU @3.60 GHz, 16GB ram

**Related URLS** (To public & visible pages, add screenshots otherwise): 
[whiteboard:c4d04e48-82ef-438b-a280-10eddb613370]
`https://www.worldanvil.com/world/whiteboard/c4d04e48-82ef-438b-a280-10eddb613370`

[whiteboard:177757a7-ae1f-4a25-878c-226b92e077e9]
`https://www.worldanvil.com/world/whiteboard/177757a7-ae1f-4a25-878c-226b92e077e9`

**Describe the Issue**
A clear and concise description of what the issue is.
(This issue description is a copy of my email, which includes the screen capture video attachment.)
Please see the attached screen capture video showing both issues in action, within an Incognito browser window.

Problem 1. On click, the Text function is auto-switching to the Select function without allowing input. 
(I did succeed at adding two text boxes of the several I tried, earlier today, but none the other day, and none since.) It's not a matter of clicking and dragging; I deliberately tried a brief mouse click, and the same problem is still occurring.

Problem 2. After creating a box shape (and presumably any shape) around a bunch of sticky notes, the arrow placement and movement process gets stuck in a rotating circle pattern around one point, typically starting in the center of the whiteboard / starting position. 

When I delete the shape, like the square around the entire mind map area, I can resume adding and moving arrows as normal. But, if I add the shape back again, the problem resumes. When there are no shapes, the arrows work as they should.

Both bugs are happening on both of my whiteboards. Not isolated to one particular whiteboard.

I made my whiteboards public temporarily while you're debugging, in case that helps. I'll privatize them again once things are sorted.

**To Reproduce**

Text Mode to Select Mode Issue:
1. Go to 'https://www.worldanvil.com/world/whiteboard/177757a7-ae1f-4a25-878c-226b92e077e9' and/or `https://www.worldanvil.com/world/whiteboard/c4d04e48-82ef-438b-a280-10eddb613370`
2. Click on Text icon in the bottom menu bar
3. Try clicking to start typing in a new text box
4. See error: auto-switches to Select Mode instead each time.

Arrow Rotation Issue:
1. 'https://www.worldanvil.com/world/whiteboard/177757a7-ae1f-4a25-878c-226b92e077e9' and/or `https://www.worldanvil.com/world/whiteboard/c4d04e48-82ef-438b-a280-10eddb613370`
2. Click on the Arrow icon in the bottom menu bar
3. Notice that the arrow is placed in a way that's centered on the midpoint or starting point in the middle of the whiteboard
4. Before you click to place the arrow, or rather, while the arrow placement is still happening, and/or once you select the arrow again to move it, moving the mouse in any direction leads the arrow to rotate in a wide circle instead of moving as normal, up/down/left/right/diagonally.
5. Delete the box shape(s) framing the outside of the whiteboard(s).
6. Try the same thing again with the Arrow Tool. It should behave normally and correctly.
7. Add a new box around the whole filled-in area of sticky notes. 
8. Try to add a new arrow.
9. Error recurs.

**Expected behavior**

I expected to be able to enter text in a text box when clicking with the Text Tool icon selected in the menu in the Whiteboard web app, rather than for it to switch modes to the Select Tool.

I expected to have the arrow move left, right, up, or down in concert with my mouse's direction, instead of rotating around in a circle in the direction ish where I moved the mouse. 

I expected the arrow length to resize with the motion of my mouse, as it normally does. I expected that the existence or location of a shape wouldn't impact the way arrows work, their location, length, or motion?

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

Please see the attached video I just emailed to contact@worldanvil.com from my user "abbie-" account-associated email address.

Thank you for your time and assistance! I appreciate it.

**Comment by iamromeo** [comment]
Thank you very much for this @AbbieWolff - can you please create two different bug reports for this so it can be tracked and do it to the bug tracker that is currently being used? https://worldanvil.com/udan-tracker
