### ISSUE TITLE
Contrast Issues in Hero View when using Dark Blue Interface Theme

### ISSUE THREAD

**Issue by Jan-Ka** [worldanvil/worldanvil-bug-tracker#146]
**World Anvil Username**: ka_jan

**World / Campaign / RPG Character / Manuscript Title**: kajan-plays-orilee

**Feature**: Hero 

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/hero/kajan-plays-orilee

**Describe the Issue**
Hero Subtitle and History have Contrast Issues when using Dark Blue Interface Theme.
Hero Subtitle has dark font-color on dark background while Hero History has light font-color on a light background.

Similar Issue has been reported with HBFR-2818

**To Reproduce**
1. Be logged in
2. Set Interface Theme to "Terror from the Deep (Dark Blue)" in Interface Settings
3. Open any Character (or provided Link) with a Subtitle and History (requires at least one Journal Entry)
4. Click "History" Tab

**Expected behavior**
Hero Subtitle should use correct (light) font-color. Timeline Content should provide contrast by having a dark background.

Don't explicitly set color `.template-character_sheet-dimitris-1`  (3 times?) 
`global.css` ( `.dark-timeline .vertical-timeline-content, .dark-timeline.center-orientation .vertical-timeline-content`) and `darkest.css` ( `.ibox-content`) fight about who gets to set `.vertical-timeline-content`. Should probably be `darkest.css`

**Screenshots**
Hero Subtitle:
![image](https://user-images.githubusercontent.com/11042838/114268376-084f6d80-9a01-11eb-93a6-3671d442cddf.png)

History:
![image](https://user-images.githubusercontent.com/11042838/114268380-0d142180-9a01-11eb-918e-885e5ec90d17.png)

**Comment by MGatta** [comment]
When viewed on Terror from the Deep, the header is still unredeable.
![image](https://user-images.githubusercontent.com/80196715/115185774-d0bb8200-a0e0-11eb-92d2-84c96352ae80.png)

Link: https://www.worldanvil.com/hero/648a24b6-cde5-4e6d-beec-dc1346a8a1cb
