### ISSUE TITLE
Hotswitch to Character not consistantly working

### ISSUE THREAD

**Issue by Tillerz** [worldanvil/worldanvil-bug-tracker#148]
**Describe the Issue**
When you are editing your world and want to switch to a character, WA just stays on the "Edit World" page.

**To Reproduce**
1. Go to "Edit world", eg https://www.worldanvil.com/world/0143de1a-bc3b-4452-8f36-fd784c6bf516/edit
2. Open the left side menu to switch to a character (e.g. my character "Cogent"), which is a link like https://www.worldanvil.com/heroes/character/773c2cbf-3ccb-40a6-aaab-4f637636fddb/hotswitch and click this link.
3. You are still on the URL of 1.

First going to the Dashboard and then trying a Hotswitch to the character works.

Maybe this is also not working for other start pages, didn't try. But at least this one doesn't work and this is usually the fastest way to go to a character after browsing your world.

Dimi, you are co-owner of my sheet-creation world, you should be able to click that link in 1. and be able to reproduce the problem.

**Comment by iamromeo** [comment]
Fixed will deploy soon
