### ISSUE TITLE
Variable values not displaying when viewer is not logged in to a WorldAnvil account

### ISSUE THREAD

**Issue by Masterfuzzfuzz** [worldanvil/worldanvil-bug-tracker#149]
**World Anvil Username**: Kalarian

**World / Campaign / RPG Character / Manuscript Title**: Norrath

**Feature**: Variables

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/norrath-kalarian/a/felwithe-settlement

**Describe the Issue**
When using "Term, Advanced" variables, the value does not appear if the user is not logged in to an account. It appears fine to the world creator, and any one with visibility so long as they are logged in to their WorldAnvil account. Otherwise, it has a perpetual load screen.

**To Reproduce**
1. Log out of any WorldAnvil account and go to this article https://www.worldanvil.com/w/norrath-kalarian/a/felwithe-settlement
2. Look for the "Koada'Dal" variable and hover your mouse over it to bring up the value.
3. See that the value is stuck to "Loading..." 

**Expected behavior**
Hovering over the "Koada'Dal" variable on the given URL should say "The original word for the High Elves"

**Screenshots**
Bug
![Bug](https://user-images.githubusercontent.com/12419144/114285855-4dd36100-9a28-11eb-9422-f54df102e22d.png)

Expected
![Expected](https://user-images.githubusercontent.com/12419144/114285867-65aae500-9a28-11eb-8d1a-2adebc3993f7.png)

**Comment by iamromeo** [comment]
@Masterfuzzfuzz all fixed :)

**Comment by Masterfuzzfuzz** [comment]
Amazing. Glad it was a quick fix!
