### ISSUE TITLE
Equipment Edit Controls Visible for Gamemaster, But Not Operative

### ISSUE THREAD

**Issue by mknnmknn** [worldanvil/worldanvil-bug-tracker#15]
Makonnen / Alemi.

Unsure which way the bug goes. Either the EDIT controls shouldn't be visible OR they should work. I (as the DM) go to CAMPAIGN / CAST and then click on a player, and see this under EQUIPMENT.

![image](https://user-images.githubusercontent.com/79889161/109593326-5904aa00-7ad6-11eb-986f-e1725783e162.png)

but nothing I do can either edit existing or add new equipment. Under add new, I can type things in the fields, but the ADD ITEM button does nothing. This is in Chrome. Players can add and edit their own equipment without issue.

**Comment by iamromeo** [comment]
Clarification request: In which page is this occuring?

**Comment by Kordishal** [comment]
Looks to me like the Equipment tab on the RPG Character Profile.

**Comment by iamromeo** [comment]
So the DM was trying to change the equipment of one of the characters on their campaign from the Player's profile? @mknnmknn is that correct?

**Comment by mknnmknn** [comment]
Sorry, yes. @Kordishal is correct.

**Comment by iamromeo** [comment]
This was not a feature - not a bug :) I have now added the ability for the Gamemasters to add, remove and update the equipment of their players (under their campaign)
