### ISSUE TITLE
@Mentions do not search through tags

### ISSUE THREAD

**Issue by Neverdusk** [worldanvil/worldanvil-bug-tracker#150]
**World Anvil Username**: Neverdusk

**World / Campaign / RPG Character / Manuscript Title**: Ocarina

**Feature**: Mentions, Tags

**Describe the Issue**
I recently suggested a feature where articles would be able to be mentioned through alternate names. After it reached 2800 points, I received a response that said "A new feature was implemented that now allows @ mentions to also search through your tags. This means that added alternative names as tags will allow you to achieve the above." The suggestion was also closed and moved to Implemented.

To test this, I added tags to several articles and tried to mention them through their tags. However, the @ mention system never detected any of the tags I added. 

**To Reproduce**
1. Go to and edit any article.
2. Add a tag.
3. Go to and edit a different article.
4. Mention the tag by typing @ + tag.
5. Tag does not show up in mention system.

**Expected behavior**
1. Go to and edit any article.
2. Add a tag.
3. Go to and edit a different article.
4. Mention the tag by typing @ + tag.
5. Tag shows up in mention system.
6. Finish editing.
6. Click mentioned tag to go to its article.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/79533944/114292205-c94e0600-9a5a-11eb-9dcb-dc98c19b8948.PNG)
![Capture1](https://user-images.githubusercontent.com/79533944/114292207-cbb06000-9a5a-11eb-81ca-e777c785d440.PNG)
![Capture2](https://user-images.githubusercontent.com/79533944/114292209-ceab5080-9a5a-11eb-9d42-aa0e716779f0.PNG)

**Comment by Kordishal** [comment]
It's not the tag that shows up. It's the article title. Your feature request was only partially implemented. As in the tags are searchable, but it will still default to the article title. Which you then have to edit to fit the context.

**Comment by iamromeo** [comment]
This is not a bug. the second part of the suggestion will not be implemented
