### ISSUE TITLE
Plot Screen stopped working if a plot looses its parent article possibly

### ISSUE THREAD

**Issue by conordjpc** [worldanvil/worldanvil-bug-tracker#151]
**World Anvil Username**: conordjpc

**World / Campaign / RPG Character / Manuscript Title**: Evis / Knives of the Gline Act 2 / Plot

**Feature**: Plots

**Related URLS** : https://www.worldanvil.com/heroes/campaign/plot/list 

**Describe the Issue**
Plots is returning a 500 error.

**To Reproduce**
1. **unknown series of steps to cause the issue initially. one article in the plot had its parent changed though**
2. Go to campaign home
2. try open plots

**Expected behavior**
The plot function to display correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/3105240/114301703-e4059680-9abd-11eb-8185-d60759136340.png)
This plot was setup with the tool originally. Mission 10 was in the wrong category

**Comment by Kordishal** [comment]
The plot list not being accessible usually means that you created a loop, which currently breaks this page. Reverting your previous change should resolve this.
