### ISSUE TITLE
Article Icon input field allows only 25 characters, which is too few for some icons

### ISSUE THREAD

**Issue by artyrambles** [worldanvil/worldanvil-bug-tracker#152]
**World Anvil Username**: arty

**World / Campaign / RPG Character / Manuscript Title**: /

**Feature**: Article/Category Icons

**Related URLS** (To public & visible pages add screenshots otherwise): Article Edit Page, Articles&Categories page

**Describe the Issue**
When I try to enter a long icon name in the article edit page, it won't let me because the character limit seems to be 25 letters. That makes some icons unusable. Longer icon names are possible to be entered in the Articles&Categories page, but seem to not get parsed beyond 25 characters. (Example icon: ra ra-perspective-dice-two)

**To Reproduce**
1. Edit an article
2. Go to Design>Icon
3. Attempt to enter a long icon name
4. Only 25 characters are possible

**Expected behavior**
The input field should be "long" enough to allow entering the full name of all available icons.

**Screenshots**
/

**Comment by iamromeo** [comment]
Increased to 50
