### ISSUE TITLE
Modify Username gives 404 error and logs out without change

### ISSUE THREAD

**Issue by da476** [worldanvil/worldanvil-bug-tracker#155]
**World Anvil Username**: da476

**World / Campaign / RPG Character / Manuscript Title**: N/A

**Feature**: Modify Username & Email

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/dashboard/user/account

**Describe the Issue**
Attempting to modify username results in a 404 error page. Clicking through the error page leads back to sign-in page. Signing back in reveals that username was not changed.

**To Reproduce**
1. Go to 'Account Details'
2. Change username
3. Enter password
4. Click on 'Update'
5. See Error 404 page

**Expected behavior**
If username cannot be changed because the new choice is already in use by another user, I would expect to see a message on the Account Details page instead of logging me out through a 404. (Ultimately, I don't need to change my username, but I was thinking about it.)

**Comment by iamromeo** [comment]
You cannot change username and password at the same time these are two different processes. 
If changing username fails it probably means that the username is already taken. 
This is already in the to-do list to be fixed.
