### ISSUE TITLE
World Export option doesn't appear

### ISSUE THREAD

**Issue by ShDrayker** [worldanvil/worldanvil-bug-tracker#156]
**World Anvil Username**: Drayker

**World / Campaign / RPG Character / Manuscript Title**: Troupe de l'Horizon

**Feature**: World Export for freeman

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Nothing appears when I expand the submenu. 

**To Reproduce**
1. Go to World Settings
2. Click on Export World submenu
3. See error

**Expected behavior**
Export world button showing

**Browser** : Chrome

**Screenshots**
![image](https://user-images.githubusercontent.com/82477852/114626939-b3d41880-9cb4-11eb-9283-61c605138e33.png)

**Comment by iamromeo** [comment]
Will be deploying fix later today
