### ISSUE TITLE
Interactive table - Advanced options descriptive text

### ISSUE THREAD

**Issue by MGatta** [worldanvil/worldanvil-bug-tracker#157]
**World Anvil Username**: MGatta

**Feature**: Interactive table

**Describe the Issue**
On an interactive's table "Advanced Options", the option "Copy Table" appears twice.

**To Reproduce**
1. Go to advanced options in an interactive table and scroll all the way down.

**Expected behavior**
The second row should read "Import Table"

**Screenshots**
![image](https://user-images.githubusercontent.com/80196715/114679008-13114780-9d0c-11eb-917c-1df209100679.png)

**Comment by Xuroth** [comment]
Thanks for reporting. This was a typo when I copied the option code from "Copy Table". A deployment containing the fix for this is pending and will be applied after approval.
