### ISSUE TITLE
Storyteller unable to edit player's sheet

### ISSUE THREAD

**Issue by LordVertion** [worldanvil/worldanvil-bug-tracker#159]
It recently came to my attention that WorldAnvil has an integrated system of play for TTRPG and was interested in seeing how it worked, after a few attempts at trying to make character sheets for my players that i could edit, i was directed to a specific comment on the official discord with instructions on how to do just that. That being the case, and following the instructions, as follows:
01. GM Create a sheet as a placeholder
02. GM sends Campaign invite
03. GM send World invite
04. GM Transfer sheet to username
(Bottom of the sheet view)
05. Player goes to character profile and chooses the now handed over sheet

Doing this and attempting to edit the character sheet results in a 404 error which the user who wrote these instructions tells me is not normal behavior as they and i attemped the process.
I am attaching a screenshot of a character profile which i am told should include an "activate" option but currently does not, and where any attempts to edit the character sheet, via direct link or simply clicking the button  result in a 404 error.
![Captura de pantalla (69)](https://user-images.githubusercontent.com/82548505/114796109-b470bb80-9d55-11eb-92fd-30444a735881.png)

**Comment by graylion-wa** [comment]
I had the opportunity to assist Vertion. And the same procedure used with five other users only leads to 404 after several attempts making sure the campaign was active, than the character was active.

This is also the method used in my world and I am able to access and edit 4 out of the 5 players. The 5th player happened different and I am not able to edit his character.

Graylion

**Comment by iamromeo** [comment]
Hey there! 

First of all, this is not the way that it is suggested for you to hand over a character to your players. 
Secondly you do not need to invite the player twice, inviting someone to your campaign automatically also invites them to your world. 

I have no information to confirm this but I can be reasonably sure that you still own the sheet. 

We will need to have more information in order to find out what the current situation is and solve it. 

I will need useraccounts, links to the characters, world, campaign etc to see what is going on :)

**Comment by LordVertion** [comment]
The Characters in question:
https://www.worldanvil.com/hero/75781181-07a5-4f1e-bdaf-3b061f9e3587
https://www.worldanvil.com/hero/54436476-1b5c-49bd-82e7-1ec86cebf1ce
https://www.worldanvil.com/hero/49496ff0-f9e3-49d0-b091-654048b7e42a

The campaign link:
https://www.worldanvil.com/heroes/campaign/a54f1a60-4974-4149-bc8e-3eed768f1070/dashboard

World link?
https://www.worldanvil.com/w/alephon-lordvertion

an my user account is Lord_Vertion

**Comment by LordVertion** [comment]
And Graylion's character that we tested with:
https://www.worldanvil.com/hero/b4b44486-b228-40df-9faa-2728e4fa4184

**Comment by graylion-wa** [comment]
I was not aware you did not use a world invite and Campaign invite. I have sent both to every player for my world an d Campaign 

⁣Get BlueMail for Android ​

**Comment by iamromeo** [comment]
Hey @LordVertion can you please 
- show me what exactly you clicked to transfer the sheet 
- give me the ID of the sheet that your player cannot edit 
- let me know how did the player added the sheet to the character (if that happened)

Also, are you on Discord?

**Comment by LordVertion** [comment]
i think theres been some kind of misunderstanding, it is I as the dungeon master who cannot edit the sheets after they are handed over, ive talked to the players and they can all do it

**Comment by iamromeo** [comment]
This will be resolved with the new security / privacy rules on Hercules release - on going
