### ISSUE TITLE
Notebook not Loading

### ISSUE THREAD

**Issue by IsaacAThom** [worldanvil/worldanvil-bug-tracker#16]
**World Anvil Username**: Isaac Thompson

**World / Campaign / RPG Character / Manuscript Title**: Tiyu Amara

**Feature**: Notebook

**Related URLS** (add URLs of the pages that do not work, make sure they are published and public!): https://www.worldanvil.com/studio/notebook/

**Describe the bug**
When attempting to open the Notebook, it stays stuck on "Loading your notes" indefinitely due to a 500 error.

**To Reproduce**
1. Go to 'Studio'
2. Click on 'Notebook'
3. See error

**Expected behavior**
The notebook should load and allow users to see their existing notes

**Screenshots**
![](https://i.imgur.com/cygbMkX.png) (includes console, showing the 500 error)
Link to discussion of bug in the help channel - [https://discord.com/channels/348060277989965844/380013392653451264/816176649665511444](url)

**Comment by Kordishal** [comment]
Yeah. Since #14 was fixed we can't load them anymore

**Comment by iamromeo** [comment]
I cannot reproduce this.
