### ISSUE TITLE
Going forwards and backwards in the feature suggestion create form loses data

### ISSUE THREAD

**Issue by MJHeijster** [worldanvil/worldanvil-bug-tracker#161]
**World Anvil Username**: MoonRaven

**World / Campaign / RPG Character / Manuscript Title**: https://www.worldanvil.com/community/voting/suggestion/d6ad2779-c8a1-443f-b450-2871ba0bfeff/view

**Feature**: Suggest a feature

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When creating a feature suggestion, I navigated to something else in the tab. I went back after that, the title and URL were still filled as what it was. I'm 85% sure the details also were still filled. After posting, the details were the default text. 

**To Reproduce**
1. Suggest a new feature
2. Browse to a different page
3. Navigate back
4. Post

**Expected behavior**
Either all the input data are empty or all are filled.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
There is nothing that can cause this on the world anvil side of things, this sounds more like a browser/plugin feature/issue.
