### ISSUE TITLE
RPG Character Content Advisory not working

### ISSUE THREAD

**Issue by Menasay** [worldanvil/worldanvil-bug-tracker#162]
World Anvil Username: Menasay

World / Campaign / **RPG Character** / Manuscript Title: Amanda Vigilantte

Feature: Content Advisory in the RPG Character editor

Related URLS: [Character profile](https://www.worldanvil.com/hero/a8dd5395-2040-4801-adcd-817bf990eda6) and [Character profile via the World she's in](https://www.worldanvil.com/w/earth-6977-menasay/a/amanda-vigilantte-person?preview=1)

This character's campaign has sexual stuff added to it and I've clicked on the advisory to queue a warning so that children can't just go in and see everything. I've had to remove a lot of her profile because this is not working.

To Reproduce Steps to reproduce the behavior:

Go to Characters
Click on A character of your choosing, go to edit them
Scroll down to Content advisory, checkmark it, save, log out, bring up the character profile
See that there is no warning for adult content on the character and that it goes directly to the page

What's expected? A warning of some kind for adult content on the character.
![content advisory](https://user-images.githubusercontent.com/82617542/114946015-696bac80-9e18-11eb-80b1-4bf18d344116.png)

**Comment by iamromeo** [comment]
This is not how advisory works on World Anvil. 
If youre account has NSFW filters deactivated (allowing adult content) you will always see NSFW content.

**Comment by graylion-wa** [comment]
Dimi, I tested this with the NSFW / 18+ button both enabled and disabled. Either way their was no warning.

![20210416_000610.jpg](https://user-images.githubusercontent.com/79761754/114970115-c9c61280-9e47-11eb-95ae-461dd68833f4.jpg)

**Comment by Kordishal** [comment]
And the user is logged out. For logged-out users, content warnings should always show.

**Comment by iamromeo** [comment]
thank you @Kordishal this is now fixed

**Comment by Menasay** [comment]
Are you _sure_ you fixed it? I'm still able to access my character's profile without a warning after logging out.

**Comment by Menasay** [comment]
@iamromeo Are you sure you fixed it? I'm still able to access my character's profile without a warning after logging out. Do I need to gifcam it to you so you understand what I'm trying to tell you is happening?
