### ISSUE TITLE
My worlds disappeared

### ISSUE THREAD

**Issue by mrobbins430** [worldanvil/worldanvil-bug-tracker#163]
**World Anvil Username**: MicaylaR

**World / Campaign / RPG Character / Manuscript Title**: World 1: Eremiya; World 2: Dream World

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is: I logged into my account where I had two worlds I was working on, worlds that I've worked hard on and had a lot of info on, and they're both gone. I don't know why they disappeared or if I can get them back-I always saved after writing something

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
The account under username MicaylaR never had any worlds in it.

**Comment by Kordishal** [comment]
Is it possible that you had created two accounts? And your worlds are on a different account? This had been another users issue in the past.
