### ISSUE TITLE
Sidebar and [row][col] BBCode

### ISSUE THREAD

**Issue by KajetanWrites** [worldanvil/worldanvil-bug-tracker#164]
**World Anvil Username**: KajetanWrites

**World**: The Galaxy

**Feature**: Articles

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I used [row][col] BBCode and wanted to turn off the sidebar as it was empty. However, when I did that the columns broke and the content in them was under one another instead of being side by side.

**To Reproduce**
Add [row][col] to an article and then uncheck the sidebar display box

**Expected behavior**
columns working properly both with and without the sidebar

**Screenshots**
![1](https://user-images.githubusercontent.com/80585282/114996153-da55a780-9e9e-11eb-994c-96f1bb99e2a2.png)

**Comment by Kordishal** [comment]
CSS issue with Dropcap
