### ISSUE TITLE
Minor Typo in World Settings Configuration Screen

### ISSUE THREAD

**Issue by 2199288c** [worldanvil/worldanvil-bug-tracker#166]
**World Anvil Username**: That_Scotsman

**Related URLS** (To public & visible pages add screenshots otherwise):

![image](https://user-images.githubusercontent.com/35373263/115051700-04c25780-9ed5-11eb-96f6-e2c6bded24da.png)

**Describe the Issue**
Minor typo - means is spelt maens

**To Reproduce**
1. Go to the configuration screen of world settings
2. Click on the display tab
4. See error under the open secrets section.

**Comment by iamromeo** [comment]
Thank you :)
