### ISSUE TITLE
Duplicated text when centering text

### ISSUE THREAD

**Issue by Catoblepon** [worldanvil/worldanvil-bug-tracker#167]
**World Anvil Username**: Catoblepon

**World / Campaign / RPG Character / Manuscript Title**: Khulgran

**Feature**: Euclid editor

**Related URLS** (To public & visible pages add screenshots otherwise): https://gyazo.com/1a03f33aad312726cde0492ba7bddb7d (selecting the text to centre)
https://gyazo.com/6be0127ac54c6c5484685ebd80a7b7b8 (after centring the text with the button)

**Describe the Issue**
When selecting a couple of short sentences for centring them afterwards with the centre text button, it duplicates text and centres the selected text.

**To Reproduce**
1. Go to edit an article
2. Select with control a sentence
3. Select another sentence while pressing control (so both sentences are selected)
4. Click the centre text button
5. See the error

**Expected behavior**
Rather than duplicate the text, it should surround the text with the centre BBCode tags

**Screenshots**
before
![](https://i.gyazo.com/1a03f33aad312726cde0492ba7bddb7d.png)
after
![](https://i.gyazo.com/6be0127ac54c6c5484685ebd80a7b7b8.png)

**Comment by Kordishal** [comment]
This is not a bug but a feature. Multiline edit is very much there on purpose.
