### ISSUE TITLE
Article Template downloaded from article template page seems to be out of date (organization template)

### ISSUE THREAD

**Issue by Tiirikka** [worldanvil/worldanvil-bug-tracker#169]
**World Anvil Username**: Tiirikka

**Feature**: Creator's Studio: Article Templates

**Describe the Issue**
Hi! I'm sorry to bother you, but I ended up in a bit of a pickle.

I tried to update HTML and the variables on my custom organization template but noticed that when I loaded the default templates from "download resources"-bit, I noticed that the template downloaded did not match with the template that organizations use as default. 

The new template, judging by source code, seems to use divs in the sidebar for the information that is printed out with classes "section-title" and "section-payload", where on the default template I got from the link these elements are dt and dl elements. Also, the template doesn't print out stuff like the organisation leader title. 

**To Reproduce**
I'm using Chrome (Version 89.0.4389.128). 

I went to Creator's Studio: Article Templates section, clicked the Download button under the Download Resources section and got the zip file, unzipped it, and opened the organization template. 

First I tried to just copy-paste the template code to the HTML structure bit, but notice that something was off, so I took a page that was made with the current default organization template and compared the source code with the template I got. It didn't match.

**Expected behaviour**
Is it possible to get the up-to-date organization template to the resources bundle. ^^ It would help me a lot! I am able to easily update the HTML to my custom one myself, but I am not sure what the twig-values for things like the missing leader title are, so I'm unable to fix that. 

Thank you for all your hard work!

- Tiirikka

**Comment by Tiirikka** [comment]
Eep! Forgot to mention: I'm experiencing this problem with the world Melyria. Haven't tried in other worlds. I have no CSS theme marked in my world, so I am having my own custom CSS on top of the default theme if that matters with solving this mystery. ^w^

**Comment by iamromeo** [comment]
Not a bug added in the features pipeline to refresh all the custom templates.
