### ISSUE TITLE
"View Article" button missing from the articles list

### ISSUE THREAD

**Issue by The-Toblin** [worldanvil/worldanvil-bug-tracker#17]
When looking at the articles and categories list (Athena), the "View Article in World" button is missing from top-level articles. It's still visible on child articles, but for top level articles, only "Copy Article Link", "Edit" and "Delete" are visible.
![Skärmbild från 2021-03-02 20-16-23](https://user-images.githubusercontent.com/79937532/109702174-2faa5380-7b94-11eb-9127-d2ea58b1b1d5.png)

**Comment by Kordishal** [comment]
Yeah, I'd rather have them back as well. It saves a click and they are not in the way.

**Comment by The-Toblin** [comment]
It's even more confusing when it's there on child articles, but not the top level/parent.
