### ISSUE TITLE
Cross-Reference Tags Don't Support Apostrophes

### ISSUE THREAD

**Issue by Sylvan012** [worldanvil/worldanvil-bug-tracker#170]
**World Anvil Username**: Sylvan_Scott

**World / Campaign / RPG Character / Manuscript Title**: Talvali: the Skylands

**Feature**: Creating Cross-Reference Tags for Timeline Events

**Related URLS** (To public & visible pages add screenshots otherwise): I don't know if this is public or not. I just lost everything I'd been trying to document for the past HOUR and am extremely frustrated. But, if this is public-facing, you can see the bug, here: https://www.worldanvil.com/w/talvali3A-the-skylands-sylvanscott/h/9fef98cf-5442-43e9-98bf-8fb8033c892d

I'll try to include a screenshot without accidentally closing my browser, this time. (I fat-fingered something and lost it all!)

When entering a tag's text, if it contains an apostrophe (such as tagging an event as part of "Reynard's Folly" or the tag having a name that contains an apostrophe such as "Ki'an-Cocarra"), that the apostrophe becomes malformed with a partial URL-encoding: replacing it with "&039;". Then, when clicking on that tag, it does not locate any of the other tags with that malformed name.

**To Reproduce**
1. Go to https://www.worldanvil.com/w/talvali3A-the-skylands-sylvanscott/h/9fef98cf-5442-43e9-98bf-8fb8033c892d 
2. Scroll down to 'Related timelines & articles' > 'The First Millennium Post-Fall'
3. See malformed tag, "Ki&039;an-Cocarra"

**Expected behavior**
I expect the apostrophe, like all common punctuation, to be maintained. My perspective comes from being a professional coder since '94. In my experience, the functionality of taking a form's input-field and parsing out everyday non-alphanumeric characters, such as the apostrophe within a possessive noun, is commonplace and has been for decades ... even back in the original LiveJournal days.

I already am replacing spaces with hyphens (as they are harder to convert for coders and are still something that are not allowed in quite a few Web-based applications' input-fields) but single apostrophes are pretty much permitted every place. This is especially important when you are trying to tag entries for cross-correlation in Speculative Fiction settings. After all, SF commonly uses apostrophes in place names or made-up names. Heck, using words from non-English languages that possess an apostrophe when written in English (as I frequently do for naming regions, creatures, or other such things) becomes impossible to denote without such support.

**Screenshots**
Screenshot showing the apostrophe-bug in a cross-reference tag:
![screenshot-apostropheBug](https://user-images.githubusercontent.com/5871260/115123603-7953cf80-9f83-11eb-9992-262c09788e32.png)

**Comment by iamromeo** [comment]
I am sorry but this is not really a bug, tags are really not made in any system to support quotes. 
I will see what I can do to prevent it from even being saved :)
