### ISSUE TITLE
Co-Owners Cannot Edit World Meta

### ISSUE THREAD

**Issue by yungTylenol420** [worldanvil/worldanvil-bug-tracker#171]
**World Anvil Username**: yungTylenol420

**World / Campaign / RPG Character / Manuscript Title**: Ex Bellum Nōs

**Feature**: World Meta, Co-Ownership

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/ex-bellum-nC58Ds-yungtylenol420/meta

**Describe the Issue**
I added Ketamineboofgod as a co-owner to this universe, but he has never been able to edit the meta data. I do have it set to public visibility, and he can view it that way, but cannot edit from his dashboard.

**To Reproduce**
1. Create a world with two or more co-owners.
2. Go to the dashboard
3. Look for the option to edit the world meta
4. Note the absence of the option to edit the world meta

**Expected behavior**
I assumed that as co-owner, Ketamineboofgod would be able to access and edit everything that I can as creator.

**Screenshots**
N/A

**Comment by iamromeo** [comment]
This is not a bug, this was done on purpose.
