### ISSUE TITLE
Euclid buttons in Terror from the Deep lack constrast

### ISSUE THREAD

**Issue by MGatta** [worldanvil/worldanvil-bug-tracker#173]
**World Anvil Username**: MGatta

**Feature**: Editor

**Describe the Issue**
Can't see euclid's buttons in terror of the dark properly, they lack contrast.

**To Reproduce**
1. Open Euclid's editor while in Terror from the Deep

**Expected behavior**
Easier to see buttons.

**Screenshots**
![image](https://user-images.githubusercontent.com/80196715/115153707-a7b2d700-a077-11eb-95ca-84c0396d5c92.png)

**Comment by iamromeo** [comment]
This was not a bug, this is a matter of personal preference. 
Regardless, I have upped the contract a bit.
