### ISSUE TITLE
Renaming block templates does not transfer to the public list

### ISSUE THREAD

**Issue by The-Toblin** [worldanvil/worldanvil-bug-tracker#18]
When a block template is renamed (the title is changed) it does not transfer over to the public blocks list when viewed by others. See example.

The block was renamed from "Racial traits" (a problematic wording I wanted to change) to "CD10: Species Starting Traits". However, when viewing the public blocks list, the old name is still there and I'm unable to change it.

![Skärmbild från 2021-03-02 20-17-37](https://user-images.githubusercontent.com/79937532/109702348-65e7d300-7b94-11eb-9091-3f28fb5a909e.png)
![Skärmbild från 2021-03-02 20-17-59](https://user-images.githubusercontent.com/79937532/109702349-66806980-7b94-11eb-8e9e-e6967eee0439.png)

**Comment by Kordishal** [comment]
Technically this is a known issue. It says in the guide to not use a placeholder name. But I guess it would be good to change it in this case.

**Comment by The-Toblin** [comment]
This was hardly a "placeholder" issue though. This was maturing as an individual and wanting to get rid of problematic language. This isn't the only template that suffers from this either. It was just the example I used.

Is there no way to fix this?

**Comment by iamromeo** [comment]
This is the List name of the block versus the Template name - these are two different things - this is not a bug. 
Please message me with details of the required change
