### ISSUE TITLE
Viewing Maps sometimes result in labels all having default style

### ISSUE THREAD

**Issue by Nogone** [worldanvil/worldanvil-bug-tracker#180]
**World Anvil Username**:
00jacnie

**World / Campaign / RPG Character / Manuscript Title**:
The world "Kampanjen" dont  know first time

**Feature**: 
Maps

**Related URLS** (To public & visible pages add screenshots otherwise):
Started here:
https://www.worldanvil.com/world/map/list  --(but for maps for "Kampanjen" then)
Ended here:
https://www.worldanvil.com/w/campaign-00jacnie/map/75fe9ec8-035a-4913-975d-c1ee09c58fb0
Looking like:
![Screenshot 2021-04-21 at 00 24 26](https://user-images.githubusercontent.com/70641641/115471253-f5763d80-a237-11eb-8014-d9d03a1aa5e0.png)

How I thought it would look:
![Screenshot 2021-04-21 at 00 22 18](https://user-images.githubusercontent.com/70641641/115471066-aaf4c100-a237-11eb-9745-a5e1937a0f2e.png)

**Describe the Issue**
A clear and concise description of what the issue is.
Encountered problem regarding maps and when trying to view a map, to see how it would look in article, entering presenters view instead. (If this is intended disregard this whole report and sorry to bother, as it seems to happen when trying to look at a map in full view as well)

**To Reproduce**
Enter maps, 
clicking on view
Error? 
Or
See map in article
click on see full.

**Expected behavior**
(See picture 2)

**Screenshots**
How entering view on map Looked like:
![Screenshot 2021-04-21 at 00 24 26](https://user-images.githubusercontent.com/70641641/115471253-f5763d80-a237-11eb-8014-d9d03a1aa5e0.png)

How I thought it would look:
![Screenshot 2021-04-21 at 00 22 18](https://user-images.githubusercontent.com/70641641/115471066-aaf4c100-a237-11eb-9745-a5e1937a0f2e.png)

-- Once again I want to add that if this is intended.. Im sorry to have taken up your time.

**Comment by Kordishal** [comment]
Why do you expect the labels to show up as they do on the second image? When I open the map I see the first version. But you do not explain why you think it should look like the second one. Do you have some CSS on your world that makes it look like that? Or did it look like that in the past?

**Comment by iamromeo** [comment]
This can continue to be discussed here 
but this is not a bug, the system works as expected.

**Comment by Nogone** [comment]
Thought the use of the different label-types would be for it to be visible
as different "fonts" and was a bit baffled when it went all default on me,
but as I was testing things for a more complete report it hit me that it
might be intentional.

My thought is then how the presenter's-view is meant to be used if it
doesn't contain all information that is in the map.
Is it as a preview? Or is there a different purpose?

**Comment by Kordishal** [comment]
Ok now I see what you mean. I don't see how that would be intentional. 

@iamromeo 

When having a label with this style selected:
![image](https://user-images.githubusercontent.com/14262536/115750553-9419b000-a398-11eb-9b59-15a2c109118b.png)
It looks like the image below in the editor:
![image](https://user-images.githubusercontent.com/14262536/115750685-bad7e680-a398-11eb-85a0-b2767e7062be.png)
And looks like the image below in presentation view:
![image](https://user-images.githubusercontent.com/14262536/115750766-d2af6a80-a398-11eb-9cef-49f2f91d9106.png)
And like this in the advanced edit screen:
![image](https://user-images.githubusercontent.com/14262536/115750898-f07ccf80-a398-11eb-8e32-a04635d59487.png)

So it seems the style is not consistently applied.

**Comment by iamromeo** [comment]
In article
![Screenshot 2021-04-23 at 08 54 27](https://user-images.githubusercontent.com/660175/115825017-85231400-a411-11eb-83cd-a8729d37c971.png)
View Mode
![Screenshot 2021-04-23 at 08 53 50](https://user-images.githubusercontent.com/660175/115825043-8b18f500-a411-11eb-9975-aeff40b673ad.png)
Edit mode
![Screenshot 2021-04-22 at 15 08 19](https://user-images.githubusercontent.com/660175/115825048-8d7b4f00-a411-11eb-9787-29bf009e3862.png)

I am sorry but I cannot reproduce this - I am not sure if it's broken CSS on your end or cache but this is not an issue.

**Comment by Kordishal** [comment]
https://www.worldanvil.com/w/breaking-anvil-soullink/map/568e9560-7a2c-4c48-b990-5343306a151c

All those three labels use one of the styles. The CSS classes are there, but the CSS for those classes (label-default, label-wob, label-bow) is not there on this map. 

* Issue persists in a private window and after clearing the cache.
* The world has no custom CSS.

There must be an issue somewhere.
