### ISSUE TITLE
Main Page Showing Serious Bugs

### ISSUE THREAD

**Issue by Spiritwolfster** [worldanvil/worldanvil-bug-tracker#181]
Hey. Something is terribly wrong with my main pages on WorldAnvil.

I am publishing articles, but they are not appearing on my main page, only one appeared - after numerous tests I made by creating new articles. Anyway, the "Recent Articles" section remains completely blank and has no updates of any kind. 

I created another world to test the problem, but the issue persists... 

This is being discouraging.

I looked for help on Discord and they said after 1 hour the article would appear normally, but this tip did not help much. So I really wanted to solve it.

Another, slightly smaller problem is that the "ARTICLE COVER IMAGE (HEADER)" is not showing up as it used to, above the name of the person/place on the main page, as you can see below the image (I don't know if this has anything to do with the main bug).

![12](https://user-images.githubusercontent.com/82912991/115472153-a87e7100-a20f-11eb-920d-9d1273124c17.jpg)

Smash that bug for me, please. Thanks anyways, sir.

**Comment by Kordishal** [comment]
Hi, these are not bugs.

Recent Articles is filled with articles where you press the Notify Followers button on the sidebar. It takes up to 1 hour for it to be updated.

Article covers can be disabled via configuration. See [here](https://www.worldanvil.com/w/WorldAnvilCodex/a/configuration#global-options).
