### ISSUE TITLE
"Characters in Location" ignores character's position

### ISSUE THREAD

**Issue by JohanFalt** [worldanvil/worldanvil-bug-tracker#182]
If you have a location article and to this you connect a few characters. You sort these under Navigation giving them a Position value. This is nicely listed in the meny and in the bottom of the location article.

But in the "Characters in Location" (in the area to the right of the main text) that list doesn't check the value of Position.

**Comment by iamromeo** [comment]
The "position" of an article has only to do with their order or appearance on navigation. 
This is not a bug, if anything it is a lack of functionality 

All lists of associated entities, in this case "characters in location" follow alphabetical ordering.
