### ISSUE TITLE
Cannot created a world with my chosen name nor change it after the fact. Goes to 404

### ISSUE THREAD

**Issue by Tirjasdyn** [worldanvil/worldanvil-bug-tracker#184]
**World Anvil Username**: Tirjasdyn

**World / Campaign / RPG Character / Manuscript Title**:
Eidmaharia-World

**Feature**: World Name

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/eidmaharia-world-tirjasdyn

**Describe the Issue**
When I name my world, Eidmaharia, I am directed to 404 page. I had to append the word world to for it to save. I don't want that, I need the word World to be removed so it just says Eidmaharia. 

**To Reproduce**
1. Go to  World Settings
2. Click on Configuration
3. Change World name to Eidmaharia
4. Click Save
5. See the 404 page

**Expected behavior**
I expect to be able to click save and it save my world name to Eidmaharia

**Screenshots**
![Screen Shot 2021-04-21 at 11 07 20 AM](https://user-images.githubusercontent.com/10961682/115593506-ce4c5a00-a291-11eb-87a3-ffb1b32508a1.png)

**Comment by Kordishal** [comment]
It could be that the deleted world is preventing the new world from being named that? 

https://www.worldanvil.com/community/search?term=Eidmaharia

**Comment by Tirjasdyn** [comment]
Can this be fixed? If I created it before it was an earlier test a long time ago. I can't view that world (it also goes to 404).

**Comment by iamromeo** [comment]
Released Copyright lock
