### ISSUE TITLE
Map Tag on Sidebar Top cannot be edited

### ISSUE THREAD

**Issue by RerollAgain** [worldanvil/worldanvil-bug-tracker#185]
**World Anvil Username**:RerollAgain

**World / Campaign / RPG Character / Manuscript Title**:Saundra

**Feature**: Article Editing, Settlement, Sidebar: Top, 

**Related URLS** (To public & visible pages add screenshots otherwise):https://www.worldanvil.com/world/settlement/0c070188-d0ec-4d7a-b303-2c805c09db68/edit

**Describe the Issue**
Attempted to add a map embed tag to my article. I cannot edit the map embed after placing it. Tried to paste a second embed over the first one. I now have two embeds that I cannot edit.

**To Reproduce**
1. Create a map.
2. Create an article and copy paste in an embed for the map on the Sidebar: Top section
3. Attempt to edit the embed but the text editor will not recognize it.

**Expected behavior**
Should be able to change and remove map embeds

**Browser**
Firefox 87.0(64-bit) on an macOS Version 10.14.4

**Comment by iamromeo** [comment]
Hey @RerollAgain this sounds like you are using the Plato (What you see is what you get) editor with an advanced tag :) 

You have two options
1. You can use the >_ Source button on the top right of your editor to edit/delete your map embed tag
2. You can flip to the advanced editor Euclid which is made to tackle the advanced tags. You can do that here: https://www.worldanvil.com/dashboard/user/interface
