### ISSUE TITLE
Article comments are visible in map-pin sidebar

### ISSUE THREAD

**Issue by iamthetot** [worldanvil/worldanvil-bug-tracker#187]
**World Anvil Username**: iAmTheTot

**World / Campaign / RPG Character / Manuscript Title**: Aedelor

**Feature**:  Map pins

**Describe the Issue**
When an article has comments in its vignette, then that article is linked to a map pin, the sidebar that opens when viewing the map in presentation mode previewing the article will contain the comments as opposed to them being invisible.

**To Reproduce**
Make an article. Add /* comments */ to the vignette. Make a map. Add a pin. Link that pin to your created article with comments. Go to the new map in presentation mode and click on the pin. The sidebar opens up offering a preview of the article, specifically of its vignette. Any comments will fully render there.

**Expected behavior**
Comments would be removed as they are when viewing the article proper.

**Screenshots**
![2RWLRsb](https://user-images.githubusercontent.com/53080404/115746891-f69b8d80-a351-11eb-8a91-2d6c6070f092.png)

**Comment by graylion-wa** [comment]
I also reported this on Jira.

**Comment by iamromeo** [comment]
Not a bug, probably a lack of implementation, but it's clearly written on the description for comments that are only usable in articles. :)

I will have a look to see if it can be rectified.

**Comment by kaiohon** [comment]
The same thing happens now except with hidden containers. When I create a container on an article page, then toggle its visibility t hidden by clicking the eye, the content still appears visible to the players when the article is linked to a map pin and its preview is open in the side bar of a map in presentation view. 

I mean this visibility toggler:
![image](https://user-images.githubusercontent.com/34840988/135717304-de414d8a-3207-49bc-be43-54ff08af783a.png)

On the article page itself the container is hidden as it should be.

**Comment by esullivan88** [comment]
I  have the same issue as kaiohon. The second line in this description is hidden in the visibility toggle, but shows up in the article preview on the map pin.
![Capture 1](https://user-images.githubusercontent.com/31042473/174488124-e3a9b771-b17a-427b-8a98-aa6d5fdfe115.PNG)
![Capture 2](https://user-images.githubusercontent.com/31042473/174488126-a0e98044-51f0-4a8a-bc33-7ab6fc626210.PNG)
