### ISSUE TITLE
Map description tooltips on embedded maps do not render BBCode

### ISSUE THREAD

**Issue by iamthetot** [worldanvil/worldanvil-bug-tracker#188]
**World Anvil Username**: iAmTheTot

**World / Campaign / RPG Character / Manuscript Title**: Aedelor

**Feature**: World presentation?

**Describe the Issue**
Mentions using the @ system can be placed into a map's description. However, when you embed that map into an article, the accompanying tooltip of that description will not properly render the link.

**To Reproduce**
Create an article. Create a map. In the description of your map, make a @ mention of the created article, which inside of the description's editor will render correctly. Embed your map into any article. When viewing the article, the embedded map as an info tooltip by its name which renders the map's description upon hover. However, the @ mention link will be rendered incorrectly.

**Expected behavior**
@ mention will create a link to the mentioned article.

**Screenshots**
![32FCQWC](https://user-images.githubusercontent.com/53080404/115754999-1040d300-a35a-11eb-8187-de656a709c19.png)

**Comment by iamthetot** [comment]
Upon further inspection, it appears that no BBCode renders correctly. 
![3xpYOer](https://user-images.githubusercontent.com/53080404/115755283-6b72c580-a35a-11eb-961c-237419302555.png)

**Comment by Kordishal** [comment]
It would make sense to have BBCode support here as BBCode is rendered in the map presentation sidebar.

**Comment by iamromeo** [comment]
This is just a description tooltip - doing that will end up breaking the whole page.

**Comment by iamromeo** [comment]
Found another solution - will deploy today 


https://user-images.githubusercontent.com/660175/115841805-d89f5d00-a425-11eb-8ae3-2ae0e119a74d.mov
