### ISSUE TITLE
DTRPG link with tracking and affiliate gives 404

### ISSUE THREAD

**Issue by MGatta** [worldanvil/worldanvil-bug-tracker#189]
**World Anvil Username**: MGatta

**World / Campaign / RPG Character / Manuscript Title**: [https://www.worldanvil.com/author/MGatta](https://www.worldanvil.com/author/MGatta)

**Feature**: Profile - journal entry

**Related URLS** (To public & visible pages add screenshots otherwise): [https://www.worldanvil.com/dashboard/user/post/e0d158a8-204f-4358-afd7-5c66fa0c1178](https://www.worldanvil.com/dashboard/user/post/e0d158a8-204f-4358-afd7-5c66fa0c1178)

**Describe the Issue**
WA gives a 404 when using a link that contains several "modifiers", such as a sales tracking ID, an affiliate link, and a built-in discount for DriveThruRPG's webpage. The [link itself works](www.drivethrurpg.com/browse.php?discount=9f5e532b1e&affiliate_id=1945677&src=WA), but when linked within WA, it gives a 404.

Note that a single one of those things work, such as the discount by itself.

**To Reproduce**
1. Go to [here](https://www.worldanvil.com/dashboard/user/post/e0d158a8-204f-4358-afd7-5c66fa0c1178)
2. Click on the sentence "Anyone buying the module from this link will get over 50% off when purchasing the adventure"
3. See the 404

**Expected behavior**
For a link that works outside of WA to work within WA.

**Screenshots**
![image](https://user-images.githubusercontent.com/80196715/115847737-88bf9680-a423-11eb-85d0-24ae0f5204b5.png)

**Comment by Kordishal** [comment]
Link was added without https:// prefix to [URL] BBCode. This causes World Anvil to interpret it as a relative link and adds the world anvil base URL to it.
