### ISSUE TITLE
Mention system does not work if article/person title is in Greek

### ISSUE THREAD

**Issue by nikizak** [worldanvil/worldanvil-bug-tracker#192]
**World Anvil Username**: Nefelrith

**World / Campaign / RPG Character / Manuscript Title**:  Ανατολή (Anatoli)

**Feature**:  Mention system does not work if article/person title is in Greek

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Hello!
I am working on a world that is based on a campaign setting in Greek and I write the articles in Greek. I would like to give the highest possible immersion to my players and for this reason, the article names are in Greek. There are some issues with using Greek, but I can find some workarounds in some cases. One of my main issues is the mentioning system.

I am trying to link the articles/persons through the mention system but it doesn't work. I tried to rename the article in English and the mention system worked fine. However, if I add the link by copy-pasting the block or textual link, then the link works. It is only the mention system that it doesn't work with Greek.

**To Reproduce**
1. Create an article with Greek in the "GENERIC ARTICLE TITLE", save it and publish it
2. Create another article and type "@[..." to initiate the mention system and try to mention the previous article
3. No link appears. Same process works with an article in Latin characters

**Expected behavior**
I expect that whenever I initiate the mention system by type "@" and/or "@[" to present me with the list of matching articles that are in Greek characters.

**Screenshots**
![image](https://user-images.githubusercontent.com/10451894/115961253-f5b35900-a515-11eb-997f-5befef298bbc.png)
![image](https://user-images.githubusercontent.com/10451894/115961277-0cf24680-a516-11eb-98cb-5ef6d934ef15.png)

**Comment by Kordishal** [comment]
Hi. You could use Latin letter tags until this is fixed! Tags are searched by the mention system as well.

**Comment by iamromeo** [comment]
This will not be possible to be addressed for the time being if ever. Sadly this is an encoding issue with the database.

**Comment by nikizak** [comment]
Hi! I understand the difficulty to address non-ANSI characters. I didn't know about the use of tags for mentioning, I must have somehow missed it. This could definitely do the trick. Thanks for taking a look into this!
