### ISSUE TITLE
Out of proportion edit button.

### ISSUE THREAD

**Issue by Jacob-W5570** [worldanvil/worldanvil-bug-tracker#193]
**World Anvil Username**: 
_Jacob-W_

**World / Campaign / RPG Character / Manuscript Title**: 
_Red Sunrise_

**Describe the Issue**
_The pencil button gets pulled out of proportions._ 
![edit button](https://user-images.githubusercontent.com/82756622/115968189-e8f32d00-a536-11eb-8323-4e5ed6a03003.png)
_It's not only this page of the screenshot, it's others too, multiple template.
I use a standard and updated chrome as my browser if that is of importance._ 

**To Reproduce**
_I don't think you can see what I see if you are not logged in as me?_

**Expected behavior**
_An squarish button?_

**Comment by Kordishal** [comment]
This happens when the pencil button is inside of an [in] indent paragraph.
