### ISSUE TITLE
Grandmaster Sub - cannot create more than a single campaign

### ISSUE THREAD

**Issue by callinl** [worldanvil/worldanvil-bug-tracker#194]
**World Anvil Username**: Szoradrin

**World / Campaign / RPG Character / Manuscript Title**: Faerun - Zion Gamers

**Feature**: Campaign Management

**Related URLS** (To public & visible pages add screenshots otherwise):  https://ibb.co/DQ48dcz

**Describe the Issue**
I have a Grandmaster subscription, which, means I should have access to unlimited campaigns. However, I get the error I attached when trying to add a new campaign.

**To Reproduce**
1. Ensure I am logged in and that my sub is correct.
2. Click on the drop down "switch to" menu. 
3. Click on +New Campaign
4. I get a window telling me "Hold on there partner!
Sadly you do not have enough campaign slots to create a new campaign."

**Expected behavior**
A new campaign should be created and asking for detail??

**Screenshots**
https://ibb.co/DQ48dcz

**Comment by callinl** [comment]
Added another world as a test to see if I could create a new campaign under it; I get the same error.

**Comment by iamromeo** [comment]
This was a bug introduced yesterday during a "fix" :P it happens - all fixed now - deploying and should be corrected in about 15 minutes

**Comment by callinl** [comment]
Understandable; I am in software engineering also. Thanks for your help.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
