### ISSUE TITLE
WA doesn't seem to support multiple tabs

### ISSUE THREAD

**Issue by umbralwarrior** [worldanvil/worldanvil-bug-tracker#195]
**World Anvil Username**: umbralwarrior

**World / Campaign / RPG Character / Manuscript Title**: Exillis / Ryoto Jin character

**Feature**: Multiple tab  / browser support

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Tonight, I was playing in a game, based in the Exillise world (a world I author on my account).  As part of this game, I also had my character open in another tab, so I could create a journal entry whilst playing.  I updated the journal enmtry as I played and, at the end of the night, I tried to save the journal to be told I couldn't create the journal entry as I didn't have an active character.

**To Reproduce**
Order of actions
In Firefox browser.
Accessed the character
Started a journal entry
Created a new tab
Accessed the Exillis world.
Updated the journal entry in the original tab
Tried to save the journal to be told that a journal entry couldn't be created as I didn't have an active character.

I tried again, using Chrome (with the world still open in Firefox as I needed details from the page I was on).
On saving the journal, even though the two open tabs were in different browsers, I received the same error.

**Expected behavior**
Open tabs should be treated completely separately.  I should be able to have a world open in one and a character open in another and be able to save journal entries, whilst viewing world details

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
This has always been the case and is working as intended. If anything this would be a feature request, but would likely be a complete rebuild on certain aspects. The active resource is based on the account and not the browser window.
