### ISSUE TITLE
Redirect Category to Article link doesn't work in World Codex/World ToC

### ISSUE THREAD

**Issue by daniadventures** [worldanvil/worldanvil-bug-tracker#198]
**World Anvil Username**:  DaniAdventures

**World / Campaign / RPG Character / Manuscript Title**: To Do List Adventures

**Feature**:  Redirect Category to Article

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/todolistadventures

**Describe the Issue**
After setting the Category to redirect to a specific article, clicking the Category name on the World Codex still opens the expanded box in the right two columns as usual (even if it is empty), instead of redirecting. 

**To Reproduce**
1. Go to https://www.worldanvil.com/w/todolistadventures
2. Scroll down to the World Codex links (bottom left column).
3. Click the "Curious? Try the Tutorial!" link.
4. It opens the box to the right, but it should be directly going to https://www.worldanvil.com/w/todolistadventures/a/tutorial-quest-article instead.

**Expected behavior**
After setting the Category to redirect to a specific article, clicking the Category name on the World Codex redirects to the article immediately. 
![RedirectCategoryOpensBox](https://user-images.githubusercontent.com/81049897/115982616-9d5a7680-a56a-11eb-9114-434dd89afe05.png)

**Screenshots**
![RedirectCategorySetting](https://user-images.githubusercontent.com/81049897/115982664-de528b00-a56a-11eb-9a6c-794304fc6466.png)

**Comment by Kordishal** [comment]
This is how categories have always been working. Directly opening the article is done with the small icon next to it.

Otherwise, you would not be able to expand the category.
