### ISSUE TITLE
Issue Formatting VS Source Views

### ISSUE THREAD

**Issue by th3razzer** [worldanvil/worldanvil-bug-tracker#20]
**World Anvil Username**: thepocketGM

**World / Campaign / RPG Character / Manuscript Title**: https://www.worldanvil.com/w/aumelamar-thepocketgm, Aumélamar

**Feature**: Article editing.

**Related URLS** (add URLs of the pages that do not work, make sure they are published and public!): https://www.worldanvil.com/world/article/5a5be75f-5394-4c71-8905-aaef4ff46c52/edit

**Describe the bug**
When editing my article the views between formatting and source do not seem to "fully switch" over. Some items (like [ul][/ul] and what have you) show up properly as the bullet list items, but some show up with the code still there. Other elements like [h4][/h4] and such appear near the top but not near the bottom of the view. Everything in the View Source area seems normal, but no matter what I do the article doesn't "fully switch over" to show the elements as they would appear outside of the source. When outside of editing the page appears perfectly fine on the "customer-facing" side or Preview.

**To Reproduce**
I am not sure that I could reproduce this effect (nor would I want to) on other pages/articles.

**Expected behavior**
I expect when the CTRL+SHIFT+S or button to switch between View Source and Presentation (or whatever mode it's called by default) should switch the elements so that it appears formatted (for example, text should be **bold** when [b][/b] is used in the source code, but not show the BBcode when outside of source view.
![bugreport](https://user-images.githubusercontent.com/46483240/109742268-1d6efa80-7c12-11eb-8922-f38e5f59d727.png)

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
@th3razzer until this is looked at - I would suggest potentially flipping to Euclid as your editor. https://www.worldanvil.com/dashboard/user/interface 

As a way for us to reproduce it, can you please paste the full content of that content area as a txt file and drop it here?
