### ISSUE TITLE
QoL: Save/View/Delete button location 

### ISSUE THREAD

**Issue by RAVaught** [worldanvil/worldanvil-bug-tracker#204]
**World Anvil Username**: R.A.Vaught

**World / Campaign / RPG Character / Manuscript Title**: Flagstone

**Feature**: Statblock

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
The save/view/delete buttons are at the bottom of the page.

**To Reproduce**
1. Go to 'World page'
2. Click on 'Statblock'
3. Scroll down to 'Bottom'
4. See Save/View/Delete buttons

**Expected behavior**
For uniformity and QoL, these would be better placed at the top right of the page as they are in other pages. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
The reason the buttons are in the bottom of the page is because sheets tend to be wide elements that need that width to display correctly. Puttin the save button or any other buttons on the top right sidebar will make them lose over 33% of that width. 

This is the reason they are where they are. I will investigate if there are any good alternatives.

**Comment by RAVaught** [comment]
I posted it there because I was instructed to. It is mainly a
workflow issue because most of the pages have all of those elements in a
standardized location. If it can't be moved it can't be moved. However, if
you look at the two images linked below, you will note that the margins on
the right and left of the Statblock page are significantly wider than those
on the articles page. It is difficult to tell precisely, and I may be
wrong, but it also seems as if the right side panel on the Statblocks page
is also wider. You might be able to reclaim some screen real estate by
reclaiming the unused space and making the right hand column uniform.

**Comment by iamromeo** [comment]
I am sorry but your images are not visible here

**Comment by Kordishal** [comment]
![statblock](https://user-images.githubusercontent.com/9615485/116186392-25ff2100-a6e9-11eb-8d2f-9d70181633eb.png)

**Comment by Kordishal** [comment]
![article](https://user-images.githubusercontent.com/9615485/116186389-25ff2100-a6e9-11eb-96b1-8f006cfba3a3.png)

**Comment by Kordishal** [comment]
I think the idea is simply to remove the margins present on the statblock editor page similar to how there are no margins on the article editor page.

This would improve the situation on large screens.

**Comment by RAVaught** [comment]
Yes, and, if the right side columns are not uniform, that could be
adjusted. Not sure why the images didn't show, but thank you Jonas for
reposting them.

**Comment by graylion-wa** [comment]
Apologies to be late to this item. I have some feedback for myself and the few others that build character sheets.

I agree and have always wanted the save at the top, it would be a better placement and faster to save, which I why I add in a save buttons at each major content box. Anyway I'm trailing off. I am always very excited to see members suggesting improvements and quality of life items. This suggestion works fine for the edit sheets of simple statblocks like a weapon, armor, spell and such but quickly consumes a lot of space for full character sheets.

The real estate of the character sheet is 12 columns wide and ranges from 2000-5000px high for an average sheet like D&D or pathfinder or other. The new placement of the Save section is 4 out of those 12 columns x 560px high (or 33% of usable width). All of the white space under this box is now lost to the character sheet. This means that every character sheet in the system just lost a lot of usable real estate. Some of the two column sheets won't be hit so hard but any of the three column sheets gets crushed. This is not even considering that smaller laptop screens and tablets need all of this width to be useful when entering text for character sheets.

In addition when designing sheets we go to a lot of effort to have the edit sheet and the view sheet matched or similar, which will no longer be the case.

I think the Save | View could be on the same row as the Name | Copy 

Name | Save | View | Copy Block | Copy Link

Maybe and the rest of the Tag | World | Folder could be a pop out like the CSS Editor or world Nav or go back to the bottom.

Im sure there are other creative ways to place this.

Even appearing at the bottom of the Left Side menu only here on the statblock page? Not sure if that's even a good idea.

I hope my feedback makes sense.

Images on the next post.

**Comment by graylion-wa** [comment]
A few image examples ...

This is an example of the Character Sheet View using all the Width
![Stat Block View](https://user-images.githubusercontent.com/79761754/116212971-5f4c8680-a713-11eb-993e-d441df1e0403.jpg)

This is two examples of the Character Sheet Edit 
![Statblock Content](https://user-images.githubusercontent.com/79761754/116213183-8dca6180-a713-11eb-896f-bcb51fd8e3ab.jpg)
![Statblock Less 33](https://user-images.githubusercontent.com/79761754/116213189-8efb8e80-a713-11eb-91c0-91846c68e811.jpg)

**Comment by graylion-wa** [comment]
![20210427_045228.jpg](https://user-images.githubusercontent.com/79761754/116214229-8192d400-a714-11eb-8993-4286c6c74b17.jpg)

**Comment by graylion-wa** [comment]
Other view from smaller screens.

![20210427_122359.jpg](https://user-images.githubusercontent.com/79761754/116277732-c1c57700-a753-11eb-8be3-b095bcaa68bf.jpg)

![20210427_122336.jpg](https://user-images.githubusercontent.com/79761754/116277747-c68a2b00-a753-11eb-818e-61da8a529ce4.jpg)

![20210427_122314.jpg](https://user-images.githubusercontent.com/79761754/116277762-cab64880-a753-11eb-84f7-c0dff65c9805.jpg)

![20210427_122256.jpg](https://user-images.githubusercontent.com/79761754/116277784-ce49cf80-a753-11eb-83b2-6efb3fdc39a7.jpg)

![20210427_122223.jpg](https://user-images.githubusercontent.com/79761754/116277799-d30e8380-a753-11eb-8714-9aa58ac62c98.jpg)

![20210427_122155.jpg](https://user-images.githubusercontent.com/79761754/116277831-d99cfb00-a753-11eb-829e-2c10e6448b1e.jpg)

**Comment by graylion-wa** [comment]
D&D Sheet on a tablet 800x600 used to be two columns is now 1 column

![D D Tablet 1](https://user-images.githubusercontent.com/79761754/116280409-a14aec00-a756-11eb-81e5-904e225692fd.jpg)

![D D Tablet 2](https://user-images.githubusercontent.com/79761754/116280418-a27c1900-a756-11eb-9c26-1feb84b14951.jpg)

![Sheets D D 1](https://user-images.githubusercontent.com/79761754/116280452-adcf4480-a756-11eb-9870-86bd1fa604ce.jpg)

![Sheets D D 2](https://user-images.githubusercontent.com/79761754/116280482-b889d980-a756-11eb-9fd0-a8e98e565ef4.jpg)

**Comment by graylion-wa** [comment]
Expanse Sheet Overlaping and squeezed 

Epanse 1000x800

![Uploading Expanse Sheet 1000x800.jpg…]()


![Expanse Sheet](https://user-images.githubusercontent.com/79761754/116281155-6bf2ce00-a757-11eb-9bb4-2f4154ebd149.jpg)

**Comment by graylion-wa** [comment]
Cyberpunk Red

![CyberpunkRed 800x1000](https://user-images.githubusercontent.com/79761754/116283286-b5dcb380-a759-11eb-9458-7c9b1512975e.jpg)

![CyberpunkRed](https://user-images.githubusercontent.com/79761754/116283289-b7a67700-a759-11eb-8d5a-2467f360503a.jpg)

**Comment by graylion-wa** [comment]
Please note the sheets for D&D, Expanse and Cyberpunk Red are not my sheets or design just examples.

**Comment by Kordishal** [comment]
I think putting the save & view buttons above & sticky. And the metadata into an overlay would be the best way to make sure it works. Just need to make sure that it works for mobile.

**Comment by iamromeo** [comment]
I have expanded the content to the full page - this should fix this issue. If not please provide **FULL PAGE**  screenshots

**Comment by graylion-wa** [comment]
My request is that this box of saves, views and other thing goes above or below and the column is returned to the full 12.
Is there a reason to leave this box in the 4 ( now 3 columns )?
Not everyone is blessed with abundant screen real estate.
Not everyone uses a desktop.
You have medium notebooks, small notebooks, and tablets.

The top row which has the name has plenty of room for save and view, is there a reason they can not go there?

**Name | Save | View | Copy Block | Copy Link**

**The other items tags, worlds and public are usually set one time and left alone.**
Why would those need to be anywhere except at the very bottom out of sight.

**This is not an article its a character sheet.** 
Its primary function is a character sheet.
When a player logs into to edit, it is to fill out the character sheet. 
Maximum real estate in my opinion should be for the character sheet.


### Several Laptop Sizes and Tablets Sizes below.

This is a 1024 x 768 iPad Screen Shot or Samsung Tablet

![Cyberpunk Red ipad 2](https://user-images.githubusercontent.com/79761754/116356185-f32c5a00-a7c8-11eb-9d51-6d2e1648671e.jpg)

![Cyberpunk Red ipad 3](https://user-images.githubusercontent.com/79761754/116356208-faebfe80-a7c8-11eb-82f8-288915248a20.jpg)


### Laptop of 1280 x 950 Slightly better

![CyberpunkRed Laptop 1280 x 800](https://user-images.githubusercontent.com/79761754/116356984-f5db7f00-a7c9-11eb-89df-08163d6f2bce.jpg)

**Comment by graylion-wa** [comment]
This is the view sheet as displayed on ipad

The print | json | edit

These do not take up any width

the other function buttons at the bottom do not take up width the are below the sheet.

Why are we torturing the sheet you actually type words and number into for width?

![Cyberpunk Red View Sheet ipad 1](https://user-images.githubusercontent.com/79761754/116362246-dc3d3600-a7cf-11eb-9cb2-56997a57e8fc.jpg)

![Cyberpunk Red View Sheet ipad 2](https://user-images.githubusercontent.com/79761754/116362250-dcd5cc80-a7cf-11eb-9639-0e1fa599b89e.jpg)

**Comment by graylion-wa** [comment]
After spending three days chasing this, researching and opening sheets to show where they break on the MD and lower sizes (medium laptops and tablets especially). Taking screenshots emulating medium laptops and tablets. I have shown three sheets that are not mine and one sheet that is mine. 

This does not seem to be enough to convey the message. Since the inference was my images were useless, I have removed all my previous posts.

The short and simple is the box should not be on the right in a column for md, sm, xs. The main content sheet column should be 12 on md, sm, and xs. The box should be above or below for md, sm, xs.

Thank you.

**Comment by iamromeo** [comment]
![Screenshot 2021-04-29 at 10 13 37](https://user-images.githubusercontent.com/660175/116514349-92d60f00-a8d3-11eb-9e80-b6f6da220fb7.png)

Implemented solution as suggested by @graylion-wa

**Comment by graylion-wa** [comment]
@iamromeo 
Thank you, I assume this has not been pushed out yet. As they are not present after a CTRL + F5?
