### ISSUE TITLE
Statblock dropdown menus

### ISSUE THREAD

**Issue by KajetanWrites** [worldanvil/worldanvil-bug-tracker#207]
**World Anvil Username**: KajetanWrites

**Feature**: Statblocks, D&D 5e

**Describe the Issue**
Dropdown menus in statblocks are unreadable in dark mode (dark blue)

**Screenshots**
![bug statblock](https://user-images.githubusercontent.com/80585282/116256269-54c1d980-a773-11eb-8bb1-a492c0c8e2e1.png)

**Comment by Kordishal** [comment]
@Tillerz Is that one of yours?

**Comment by iamromeo** [comment]
@Kordishal @KajetanWrites Whitch statblock is this? There are over 10 DnD 5e statblocks

**Comment by KajetanWrites** [comment]
Item, but I wouldn't be surprised if other had that problem too

**Comment by Tillerz** [comment]
Fixed. Will also check the other templates and adjust them accordingly.

**Comment by Tillerz** [comment]
- title font changed
- nicer 'source' label
- input fields larger so the text fits in
- input field color/background color readable
- input field font size doesn't change on focus/onfocus anymore
- smaller things when I found some
- statblocks with image (monster, npc) display the image on the side now, not above the block

templates that also got an update: race, spell, monster, class, npc
