### ISSUE TITLE
Starfinder Sheets 404

### ISSUE THREAD

**Issue by graylion-wa** [worldanvil/worldanvil-bug-tracker#208]
**World Anvil Username**:

Graylion

**Feature**: 

Starfinder Character Sheets

**Related URLS** (To public & visible pages add screenshots otherwise):

https://www.worldanvil.com/community/rpg/system/starfinder

**Describe the Issue**
A clear and concise description of what the issue is.

It would appear all the Starfinder Character sheets are 404?

**To Reproduce**
1.Click the the url above
2.Click view on a Starfinder Character 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

![20210427_134239.jpg](https://user-images.githubusercontent.com/79761754/116287779-cc393e00-a75e-11eb-90b9-756632320271.jpg)

404 screenshot is from the first character

![20210427_134536.jpg](https://user-images.githubusercontent.com/79761754/116287893-ec68fd00-a75e-11eb-9c9d-dee58ea24750.jpg)

**Comment by Kordishal** [comment]
Who's template is that? Not really much Dimitris can do about it. Or is it one of the old ones?

**Comment by graylion-wa** [comment]
Maybe Gorkam?

⁣Get BlueMail for Android ​

**Comment by Kordishal** [comment]
Ok but I am starting to think that there is a bug in the system. Toblin reported the same issue on some of his sheets.

This obviously hasn't been touched in forever, and you can see them when they are embedded in an article. And it affects all of them.

**Comment by Kordishal** [comment]
Toblin resolved the issue on his sheets by removing CSS comments. This might be the case here as well.

**Comment by iamromeo** [comment]
`Key "1" for array with keys "0" does not exist in __string_template__bc3db1df3cb40d4c92afbaff8cbfb518fb63ac0e739dc03eee3242e73cab39b8 at line 9.
`
This is the error returned, I know it's not very helpful but this is it.

**Comment by iamromeo** [comment]
It was the comments - oddly enough that was not a change in the codebase.
