### ISSUE TITLE
Top Margin for Editor View only applied to Articles, not Categories.

### ISSUE THREAD

**Issue by Oneriwien** [worldanvil/worldanvil-bug-tracker#21]
**World Anvil Username**: Oneriwien

**World / Campaign / RPG Character / Manuscript Title**: Any world.

**Feature**: Categories

**Related URLS** (add URLs of the pages that do not work, make sure they are published and public!):

**Describe the bug**

**To Reproduce**
1. Go to any article in editor view, look at #visual-container, and see it has "margin-top: 46px;
2. Go to any category in editor view, look at #visual-container and see it has no such margin.

**Expected behavior**
I want both to have margin-top: 46px; ONLY for editors viewing the page. This way when you use the GLOBAL HEADER BLOCK the #world-editor-bar doesn't get in the way.

**Screenshots**
![image](https://user-images.githubusercontent.com/36694877/109758372-f1af2e80-7b97-11eb-86f6-93c8d942ef19.png)
![image](https://user-images.githubusercontent.com/36694877/109758421-0390d180-7b98-11eb-95a6-4080156ab4ec.png)

**Comment by iamromeo** [comment]
Cannot reproduce and and no URL has been provided in order to review.

**Comment by Oneriwien** [comment]
Trying to explain the problem with a GIF, the quality is slightly shot.

Here are the two pages I visit during the GIF. I am unsure if you will be able to see the problem as it only shows up for editors, not guests.
https://www.worldanvil.com/w/mernac/c/legends-category
https://www.worldanvil.com/w/mernac/a/grumby26230393Bs-path-to-wisdom-prose

![Category-Article-46](https://user-images.githubusercontent.com/36694877/109911985-9fcddd80-7c57-11eb-9f15-53e49502b7d3.gif)

**Comment by iamromeo** [comment]
I am sorry bud, but even in my world, this cannot be reproduced. 
I have added a new class just in case there is an issue with the world assignment on your category. c
Can you please go to 
https://www.worldanvil.com/w/mernac/c/legends-category
and paste here the CCS classes assigned to the visual-container 
it should like something like: 
col-xs-12 user-css-viewer world-0b00e34e-7ef2-4443-876b-95787361a82c
