### ISSUE TITLE
Pasting containers stopped edit capabilities

### ISSUE THREAD

**Issue by craig-jong** [worldanvil/worldanvil-bug-tracker#210]
**World Anvil Username**:
FourFangedCow
**World / Campaign / RPG Character / Manuscript Title**:
Alecia
**Feature**: 
Articles
**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/alecia-fourfangedcow/a/terrowin-mowbray-article

**Describe the Issue**
I copy and pasted a large block of BBCode (with a bunch of nested containers) and it somehow bricked the edit page. When I try to edit the page, I can't delete any of the containers and clicking on "view source" does nothing except seemingly expand the text area for some reason.

Initially
![image](https://user-images.githubusercontent.com/18184943/116390905-60dd8380-a7d3-11eb-82da-6a500b564eb4.png)

After clicking "view source"
![image](https://user-images.githubusercontent.com/18184943/116390948-6dfa7280-a7d3-11eb-9bae-2bc180aa2724.png)

**To Reproduce**
I don't really want to try to reproduce this, but the block of text I pasted is as follows:
`[container:ch-wrapper]
[container:ch-stat-block]
[container:ch-stat][container:ch-stat-header]STR[/container]8[container:ch-stat-sub]-1[/container][/container]
[container:ch-stat][container:ch-stat-header]DEX[/container]13[container:ch-stat-sub]+1[/container][/container]
[container:ch-stat][container:ch-stat-header]CON[/container]14[container:ch-stat-sub]+2[/container][/container]
[container:ch-stat-p][container:ch-stat-header]INT[/container]20[container:ch-stat-sub]+5[/container][/container]
[container:ch-stat-p][container:ch-stat-header]WIS[/container]18[container:ch-stat-sub]+4[/container][/container]
[container:ch-stat][container:ch-stat-header]CHA[/container]17[container:ch-stat-sub]+3[/container][/container]
[/container]
[i]Medium • Human • Chaotic Neutral[/i][br]
[b]Class.[/b] Transmutation Wizard 15[br]
[b]AC.[/b] 12 [b]HP.[/b] 72 [b]Speed.[/b] 30 ft[br]
[b]Proficiency Bonus.[/b] +5[br]
[b]Skills.[/b] Arcana +10, History +10, Insight +9, Investigation +10, Religion +10[br]
[b]Languages.[/b] Common, Thieves' Cant (Golden Hand), Elvish, Abyssal, Draconic[br]
[b]Wizard.[/b] Alaina is a 15th-level Transmutation Wizard and has access to all relevant class features.[br]
[b]Spellcasting.[/b] Alaina has the following spells in her spellbook:[br]
Cantrips (at will): [i]Dancing Lights, Mage Hand, Message, Acid Splash[/i][br]
1st level (4 slots): [i]Magic Missile, Expeditious Retreat, Find Familiar, Mage Armor, Shield[/i][br]
2nd level (3 slots): [i]Misty Step, Hold Person, See Invisibility, Alter Self, Locate Object, Knock[/i][br]
3rd level (3 slots): [i]Lightning Bolt, Hypnotic Pattern, Clairvoyance, Fly, Haste[/i][br]
4th level (3 slots): [i]Dimension Door, Locate Creature, Private Sanctum, Arcane Eye, Fabricate[/i][br]
5th level (2 slots): [i]Passwall, Hold Monster, Arcane Hand[/i][br]
6th level (1 slots): [i]Guards and Wards, True Seeing[/i][br]
7th level (1 slots): [i]Reverse Gravity, Teleport[/i][br]
7th level (1 slots): [i]Mind Blank, Power Word Stun[/i][br]
[/container]`

1. Edit a page
2. Paste the block of text above directly into the content text area

**Expected behavior**
I expected the text I pasted to be editable. I'm guessing if I had pasted it into the the "view source" view in the first place it probably would've been fine.

**Screenshots**

**Comment by Xuroth** [comment]
Nested containers are a known issue/limitation on Plato (the editor you're using). They are an "advanced" feature, and should be used in Euclid (you can go to Interface Settings to change). Unfortunately the issue is rooted in the core library Plato uses, so until a suitable alternative can be adapted, we have to encourage using containers only in Euclid.

My apologies for the inconvenience.
