### ISSUE TITLE
Associated RPG Blocks cause a horizontal scrollbar

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#211]
**World Anvil Username**: SoulLink
**Feature**: World Presentation

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/breaking-anvil-soullink/a/introduction-to-the-atlas-article

**Describe the Issue**
When an article has an associated RPG Block a horizontal scrollbar appears on the article page at the bottom. This is caused by the fact that the row inside of the `.user-css-rpgblock` is not inside of a container.

When adding a the container class to the .user-css-rpgblock div the issue is resolved.

**Comment by iamromeo** [comment]
> When adding a the container class to the .user-css-rpgblock div the issue is resolved.

Can you please elaborate?

**Comment by Kordishal** [comment]
![image](https://user-images.githubusercontent.com/14262536/116509665-fd7f4e80-a8c3-11eb-90cc-3cb22acc7718.png)
