### ISSUE TITLE
Image link goes to 404 Dragon page

### ISSUE THREAD

**Issue by dimalique** [worldanvil/worldanvil-bug-tracker#213]
Kwyn Marie

Wellspring Dragons, Lapis of Nicodem

Clicking on images to access URL page takes me to 404 Dragon Page

https://www.worldanvil.com/i/2228861 from a test pic I uploaded today

 I was initially attempting to access the URL page of a picture from Images and Files. Normally I click on the right hand upper image and it sends me to a page that then gives me the link to the URL page. I clicked on the image in the upper right hand corner, and it went to the 404 dragon page instead. I can still use the image:id on pics I tested, but I can't access the URL page.  All the pictures in both worlds that I've tested have all ended in the 404 page when I attempt to do so.

Thank you.

**Comment by iamromeo** [comment]
This has nothing to do with the image. The error presented has to do with misuse of BBcode in the description of the image nad not the image itself - it looks like somewhere in the description there is a link article that is using an image id
