### ISSUE TITLE
Category Toc 

### ISSUE THREAD

**Issue by Jacob-W5570** [worldanvil/worldanvil-bug-tracker#214]
**World Anvil Username**:
Jacob-W

**World / Campaign / RPG Character / Manuscript Title**:
Red Sunrise

**Feature**: 
Category toc , the new horizontal view. 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
There is a hiccup in how it is presented when the main category has articles and sub-categories with articles. 

**Screenshots**
I link to my first discord message, as we talked about it there
https://discordapp.com/channels/348060277989965844/413706576470474753/837061258347675669

**Comment by iamromeo** [comment]
Fixed!
