### ISSUE TITLE
Drafts and Access Denied articles are indistinguishable for the end user

### ISSUE THREAD

**Issue by The-Toblin** [worldanvil/worldanvil-bug-tracker#215]
**World Anvil Username**:
Toblin
**World / Campaign / RPG Character / Manuscript Title**:
Cinders of the Cataclysm https://www.worldanvil.com/w/CD10-CotC/

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/CD10-CotC/a/cd10-psionics
https://www.worldanvil.com/w/CD10-CotC/a/transdermal-injector-technology

**Describe the Issue**
For an outside user, they cannot tell if they hit a Draft or if they don't have access to an article. In a Sage+ world with custom access denied page, the user is sent to the access denied page in BOTH cases. So they can't tell if the author forgot to give them access, they don't have access or if the page simply isn't published (redlinks are active on monetized worlds with custom access denied pages)

**To Reproduce**
1. Go to The two URLS linked above, while being logged out. 
Both send you to the same access denied page. The Psionics one is access restricted to subscriber groups, the Transdermal injector is a draft.

**Expected behavior**
A subscription "Access Denied" should lead to the custom access denied page.
A draft should send the user either to multipass or a specific page saying "The page you tried to access is a draft and not published" or something to that effect.

**Comment by iamromeo** [comment]
I am not even sure if this is considered a bug ...

**Comment by Kordishal** [comment]
It's definitely not a bug. Just a user experience issue. But it could also be considered to require a feature expansion request as it adds another version of the access denied page for draft articles.

**Comment by The-Toblin** [comment]
It's probably a feature expansion. But I'm being yelled at by my patreons, so I figured I should report this in case it's unintended behaviour.

It also felt excessively "braggy" to make a feature request that really affects a tiny portion of the user base: Sage+.

**Comment by Lyraine-Alei** [comment]
(Grandmasters have access to "Custom Access Denied/Redirection" pages)

(just an additional note)
