### ISSUE TITLE
Variable in Calendar Descriptions 

### ISSUE THREAD

**Issue by graylion-wa** [worldanvil/worldanvil-bug-tracker#216]
**World Anvil Username**:
Graylion

**World / Campaign / RPG Character / Manuscript Title**:

World = Creation

**Feature**: 

Calendars

**Related URLS** (To public & visible pages add screenshots otherwise):

https://www.worldanvil.com/w/creation/a/ptolus-calendar-article?preview=true

In the linked calendar article the first month has a variable in the description.

[var:ptolus-month-1-graylion]

**Describe the Issue**
A clear and concise description of what the issue is. Not really if its even a big or just not implement yet, as variable are new.

Variable Fragments do not render in the Calendar Description field.

**To Reproduce**
1. Create a Variable Fragment with some test text and bbcode
2. Add variable to calendar month description.
3. Embed calendar in article
4. View article and month

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

First Month with Variable 

![20210429_193012.jpg](https://user-images.githubusercontent.com/79761754/116631106-73b29e00-a922-11eb-8e0b-e1e537d417db.jpg)

Second Month without Variable 

![20210429_193037.jpg](https://user-images.githubusercontent.com/79761754/116631153-8b8a2200-a922-11eb-90da-e93094690fe5.jpg)

**Comment by iamromeo** [comment]
This will not be addressed. The calendars system is currently in limbo and the two systems are incompatible.

**Comment by graylion-wa** [comment]
I figured that may be the case. Thank you.

⁣Get BlueMail for Android ​
