### ISSUE TITLE
Canceling "delete all notifications" deletes the notifications anyway

### ISSUE THREAD

**Issue by iamthetot** [worldanvil/worldanvil-bug-tracker#217]
**World Anvil Username**: 
iAmTheTot

**Feature**: 
Notifications

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/notification/

**Describe the Issue**
If you press "Delete All" on your notifications page, you are given a prompt asking you to confirm that is what you wanted to do. Pressing "cancel" on this prompt still deletes all the notifications, anyway.

**To Reproduce**
Have notifications.
Press "Delete All"
Press cancel when prompted to confirm.
Poof go notifications.

**Expected behavior**
Pressing cancel will not delete any notifications.

**Comment by iamromeo** [comment]
Thank you for reporting this @iamthetot it's a long time that it sits there - it should get some attention

**Comment by iamromeo** [comment]
A double check system was implemented to fix this
