### ISSUE TITLE
No specific CSS class to target footnote content only

### ISSUE THREAD

**Issue by ProgrammerSS2020** [worldanvil/worldanvil-bug-tracker#219]
**SS2020**:

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: Missing tag on FOOTNOTES in the Sections Footer:Sections

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
It seems this box in the Sections Footer:Sections, has no tag while the other boxes around it do. We tried in the Guild-css-help and no one seems to know what the class is for that. We could not see it when looking at the code.

**Expected behavior**
We would like to see a class to address elements specifically in that box. We tried full bottom and full footer and a few others we could not address it.

**Screenshots**
![visual](https://user-images.githubusercontent.com/80294034/116836171-c25e7300-ab82-11eb-8971-8d7a0717037f.png)

**Comment by Kordishal** [comment]
There is no class because the footnote is simply at the bottom of the general main content div. It does not currently have its own container. I guess it could be helpful to have a container for the footnote content.

**Comment by ProgrammerSS2020** [comment]
Jonas, 

 

Thanks for the quick response.

 

It seems like a great idea, and you have to figure if you are going to let us put stuff there, we would need a way to address it. I know I will.

 

I put an idea to the Guild. If someone has the info, could they use the Anatomy of an Article and put the classes on it for reference. It would save a lot of questions in the future.

 

Thanks for the reply. I appreciate all your hard work. 

 

Regards,

 

Scott

**Comment by iamromeo** [comment]
We can add a class - not a biggie -

**Comment by iamromeo** [comment]
Wait there is one 
                                    <div class="row article-content-full-footer article-content-full-bottom">

What am I missing

**Comment by Kordishal** [comment]
That is the full footer. We are talking about the footnote. 

![image](https://user-images.githubusercontent.com/14262536/116863110-13fc1180-ac06-11eb-92b0-a5197748be93.png)

The footnote just lives in the main content area way at the bottom. So you always target everything else as well

**Comment by RiverFang13** [comment]
Recently, a bar has appeared at the bottom of many of my articles (Ex. https://www.worldanvil.com/w/isekai/a/world-tags) 
When inspected, this bar reads as the footnotes. 
I was told to make note of it here, as this bar appears at the bottom of every article and did not appear before this change.

**Comment by Kordishal** [comment]
The reason for this is that the new container adds the user-css class in addition to the footnotes class. The bar is the borders around the article page.
