### ISSUE TITLE
ToDo Item Creation on Article Creation Inconsistent

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#22]
**World Anvil Username**: SoulLink

**World / Campaign / RPG Character / Manuscript Title**: -

**Feature**: ToDo List

**Related URLS** (add URLs of the pages that do not work, make sure they are published and public!): -

**Describe the Issue**
When creating an article with a template placeholder or with the purple creation tool, the system automatically creates a ToDo item. However, if the article is created with the buttons on the Dashboard or the green quick creation hammer no ToDo item is generated.

**To Reproduce**
Create an article with the green quick creation or on the dashboard and check ToDo list.

**Expected behavior**
I would expect there to either always be a ToDo item or clear documentation that some options do not create a ToDo item or a toggle to switch the behaviour globally.

**Comment by iamromeo** [comment]
Only placeholders are meant to create TODO entries automatically. 
**If the purple button is creating a TODO entry is a bug**

**Comment by Kordishal** [comment]
Does that make sense? You hinted recently that a majority of articles created this way are deleted. So adding a ToDo item clustering up the ToDo list with items nobody uses makes little sense to me?

And why should not all created articles make a ToDo item?

**Comment by iamromeo** [comment]
You are kind of referring to another bug here, but to answer your question about why it makes sense: 

The placeholder system created TODO items because these are literally articles that have not been created but there is an intention for them to be created in the future. 

Using the purple button or creating a new article means that you are currently working on that article or the article already has content in it. In both cases, this would create a TODO list item which will just add to the list, cluttering it.

**Comment by Kordishal** [comment]
I understand your point. It makes sense that template placeholders create TODO items automatically, as this is the only way to systematically track them down after creation. Otherwise, you'd have to go through each article and find them.

So in the case of creating articles directly, the intended workflow is that you manage the creation of TODOs manually instead of having them added every time. 

So I guess changing this to automatic would be a feature request as the user who was confused by it wanted to always have a TODO item, but I believe they opted to use the WIP filter in Athena instead.

(and sorry about bringing in the bug on this issue, I guess you are aware of the issue)
