### ISSUE TITLE
Child comment of deleted parent comment on article cannot be deleted

### ISSUE THREAD

**Issue by orpheus-tc** [worldanvil/worldanvil-bug-tracker#220]
**World Anvil Username**: thechangeling

**World / Campaign / RPG Character / Manuscript Title**: Interarcanum

**Feature**: Comments

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/interarcanum-thechangeling/a/ketopsians-ethnicity

**Describe the Issue**
I cannot seem to be able to delete a comment written on my article- when I click on the Delete link it leads to a 404 page

**To Reproduce**
1. Go to a comment section on an article
2. Click on "Delete" beneath a comment

**Expected behavior**
I expected the comment to be deleted, but it wasn't.

**Comment by Kordishal** [comment]
Which of the comments can't you delete? And can you check what happens when you click the delete link in the Console?

And copy the delete comment link here? That leads to a 404.

**Comment by orpheus-tc** [comment]
The comment I cannot delete is this one
<img width="713" alt="Screenshot 2021-05-04 at 10 04 36" src="https://user-images.githubusercontent.com/83596462/116975754-64d04080-acc0-11eb-8b90-24e0a9a8de61.png">

This is what I get in the Console when I click on the Delete link (sadly its in french and I know nothing of programming so I cannot provide a translation)
<img width="1373" alt="Screenshot 2021-05-04 at 10 06 47" src="https://user-images.githubusercontent.com/83596462/116975823-7fa2b500-acc0-11eb-86d0-68d41a0a86e7.png">

And this is the link to the delete comment here:
https://www.worldanvil.com/comment/46bd21a6-1d4f-41aa-8b40-89c116dc2b24/delete

**Comment by iamromeo** [comment]
Have you tried deleting the child comment first ?

**Comment by Kordishal** [comment]
There is no delete button on the child comment? So I assume that link is of the child comment?

**Comment by orpheus-tc** [comment]
> Have you tried deleting the child comment first ?

There is no delete button for the parent comment, I've only been able to try delete the child comment. I will mention that there was another child comment written by myself before that (same comment thread) that I have been able to successfully delete.

**Comment by Kordishal** [comment]
Well then that might be the problem? Did you delete your comment first? And now can't delete its child comment?

**Comment by orpheus-tc** [comment]
That could be it? The original parent comment is still there however so I don't know why I'm not able to delete the child (and why the 404 still happens).

**Comment by Kordishal** [comment]
Because it's a child of a child. (even if it's not visually displayed as such). But then it's surprising that the comment is still displayed without a problem.

**Comment by orpheus-tc** [comment]
Gotcha. Its also surprising I could delete its parent without any issue.. also, what should I do to be able to delete it?

**Comment by Kordishal** [comment]
Yep just tested it. (For some reason when the same person writes all the comments it doesn't fail)

Steps to Reproduce:

1. Reader writes comment 1 on article
2. Author replies with comment 2 on comment 1.
3. Reader replies with comment 3 on comment 2.
4. Author deletes comment 2.
5. Author attempts to delete comment 3 but cannot.

The reader is still able to delete their comments.

@orpheus-tc all you can do right now is wait for it to be fixed or ask the user to delete their comments.

**Comment by iamromeo** [comment]
After extensive testing this can no longer be reproduced.
