### ISSUE TITLE
Hoizontal Listings with [categorytoc] can sometimes duplicate links when opened/shut too fast.

### ISSUE THREAD

**Issue by BlackjackMKV** [worldanvil/worldanvil-bug-tracker#221]
**World Anvil Username**: BlackjackMKV

**World / Campaign / RPG Character / Manuscript Title**: Emere

**Feature**: CategoryTOC Horizontal listings

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/emere-blackjackmkv/a/aetherial-mana-generator

**Describe the Issue**
Rapidly clicking on one of the subcategories listed in the [categorytoc] tag's horizontal listings can cause it to show multiple lines of the same articles, duplicating the links instead of disposing of the old ones properly.

**To Reproduce**
1. Go to any page with the [categorytoc] tag set to horizontal with child categories.
2. Click on a subcategory rapidly.
4. Links should end up with multiple duplicated lines.

**Expected behavior**
Clearing the old links away when the categories are toggled open and shut.

**Screenshots**
![image](https://user-images.githubusercontent.com/26011725/116931673-88db4580-ac1e-11eb-85a9-e68f29e84afc.png)

**Comment by Kordishal** [comment]
This happens with not horizontal category toc's as well.

**Comment by iamromeo** [comment]
Not going to fix
