### ISSUE TITLE
Mentions/Embed function in Heroes

### ISSUE THREAD

**Issue by thedumbowl** [worldanvil/worldanvil-bug-tracker#222]
**World Anvil Username**: TheDumbOwl

**World / Campaign / RPG Character / Manuscript Title**: Character, Meesinei Sareet on Heroes

**Feature**: Heroes / Mentions

**Related URLS** (To public & visible pages add screenshots otherwise): Profile: https://www.worldanvil.com/hero/Meesi-snekgirl Link to post: https://www.worldanvil.com/hero/log/post/38c52f48-924d-49ee-8e10-ebb4aded3226

**Describe the Issue**
The mention function on Heroes does not appear to work; when copying the link from the character's profile it displays it as plain text rather than embedding a link to the other character's profile.

**To Reproduce**
1. Copy the text from the link/embed format from a heroes character profile.
2. Create a new post/reply with the embed in it.
3. Submit post.

**Expected behavior**
The post should contain an embedded link that notifies the other user, as well as link back to their profile.

**Screenshots**
https://i.imgur.com/DgX4BLW.png
https://i.imgur.com/fAIMYYN.png
Expected result: https://i.imgur.com/8J8YS1K.png

**Comment by Kordishal** [comment]
The reason that this does not work is that the Link Copy is the wrong identifier. It works in general.

Kimi: https://www.worldanvil.com/hero/f7bf3db3-452f-4d36-abe4-5e70a208f212

![image](https://user-images.githubusercontent.com/14262536/116964149-19f7fe00-acab-11eb-8d12-8c6aa4d76ab1.png)

@f48605e0-ed97-4a82-9958-b5ead8219609 

[hero:f48605e0-ed97-4a82-9958-b5ead8219609]

Both of these should use the identifier above in the link and not this one. So until Dimitris finds the reason for this mismatch just make sure that these are the same.

**Comment by iamromeo** [comment]
Fixed but I am not sure what happened there
The character was a character of a freeman with altered slug

Unless some spoopery happened here - this is magic

**Comment by thedumbowl** [comment]
Blessed be the developer fairies and their mysterious magics! Many thanks for taking a look into it, as bizarre as the issue was.
