### ISSUE TITLE
Edit Session button leads to 404 page

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#224]
**World Anvil Username**: SoulLink
**Feature**: Session Reports

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
The button to Edit Session in the campaign leads to a 404 page.

**To Reproduce**
1. Create Session Report Article with Campaign in World
2. Click edit session button
3. 404 page

**Expected behavior**
That button should not be there if the session report was not created via the campaign interface.

**Screenshots**
![image](https://user-images.githubusercontent.com/14262536/116968925-b6270280-acb5-11eb-8017-4790c60a9fbd.png)

**Comment by iamromeo** [comment]
This should no longer be here - this page no longer exists  I will remove this link
