### ISSUE TITLE
404 end of the world

### ISSUE THREAD

**Issue by GranTorino0** [worldanvil/worldanvil-bug-tracker#225]
**World Anvil Username**: MartinSchinca

**World / Campaign / RPG Character / Manuscript Title**: Khardum

**Feature**: Articles not visibles

**Related URLS** (To public & visible pages add screenshots otherwise): 
![Sin título](https://user-images.githubusercontent.com/41279769/116984377-908ffe00-aca1-11eb-998c-dd5f90940940.png)

**Describe the Issue**
When i try to view my articles in "View world", it shows a 404 error and it says i reached the end of this world.

**To Reproduce**
1. Go to '...' View world
2. Click on '....' Any article
3. Scroll down to '....' Anywhere

**Expected behavior**
Just can see my things lol

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Dimitris is working on it. Will be back.

**Comment by Kordishal** [comment]
Resolved
