### ISSUE TITLE
World Anvil 404 on entire project

### ISSUE THREAD

**Issue by Joshible** [worldanvil/worldanvil-bug-tracker#226]
**Joshible**:

**Wildemount Campaign**:

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I cannot access any portion of the campaign project I'm working. It seems any document I've produced for the world is missing and not viewable. None of the project is monetized, it's strictly for my personal DnD campaign, so there shouldn't be any copyright problems with it. 

**To Reproduce**
1. Go to 'Wildemount Campaign'
2. Click on 'Any article written'

**Expected behavior**
I expected to be able to see the documents I've produced as references to my players. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Dimitris is working on it. Will be back soon.

**Comment by Kordishal** [comment]
Resolved
