### ISSUE TITLE
I can't open my articales in my world 

### ISSUE THREAD

**Issue by firethorndragon** [worldanvil/worldanvil-bug-tracker#227]
**World Anvil Username**: Firethorndragon

**World / Campaign / RPG Character / Manuscript Title**: Aurin

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/aurin-firethorndragon/a/smoke-moss-species-1?preview=true%3F
 
**Describe the Issue**A clear and concise description of what the issue is.

I can't open anything in my world. Everytime I click on an artical it sayes 404 “Thus you have reached the end of this world." I have tried signing out and signing in again but the problem is still there. I can't open up other world builders articales either. Everytime I try it says 404 "thus you have reached the end of this world." It comes up everythime I try to view it. But I can open it to edit but I can't view my articales. Everythinge else I can open like my maps, and timelines, but not articales. 

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Fix is being deployed.

**Comment by Kordishal** [comment]
Resolved
