### ISSUE TITLE
Article Data loss

### ISSUE THREAD

**Issue by NilsCordes** [worldanvil/worldanvil-bug-tracker#228]
**World Anvil Username**: NilsCordes

**World / Campaign / RPG Character / Manuscript Title**: Habiba Papadopoulos

**Feature**: Article, Character. Data loss.

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
This article was filled with text a couple of weeks ago. When I now opened it most of the content is missing. There were many hours of work put into that article and I would like it back.

**To Reproduce**

**Expected behavior**
I expect to get the missing content back.

**Screenshots**
![Article_Habiba](https://user-images.githubusercontent.com/83673794/117068897-21132080-ad2c-11eb-8a19-d420181e276a.jpg)

**Comment by Kordishal** [comment]
Unfortunately, it is not possible to restore single articles for World Anvil. What most likely happened is that you saved over the content with an old editor window that autosaved. Make sure to always only have one window with the same article editor open (on any device).
