### ISSUE TITLE
My community signature doesn't appear in the comments i write

### ISSUE THREAD

**Issue by Gegee16** [worldanvil/worldanvil-bug-tracker#229]
**World Anvil Username**: Gege16

**World / Campaign / RPG Character / Manuscript Title**: Kingdom of Moskova

**Feature**: Community signature

**Describe the Issue**
I have settled a community signature to be displayed in my comments: "Explore [world block code] with me!" But it doesn't show in any of my comments. It is visible in my user tag though. I have tried several times since I joined the site, but it is still not showing. 
**Expected behavior**
The text I wrote in the "community signature " section while editing my profile should be visible below my comments, like how it is displayed in this user's comment.
![Screenshot_20210504-211537_Samsung Internet](https://user-images.githubusercontent.com/83679544/117084570-e73b1d80-ad1d-11eb-8db0-384ee798c7e6.jpg)

**Screenshots**
![Screenshot_20210504-210859_Samsung Internet](https://user-images.githubusercontent.com/83679544/117084238-13a26a00-ad1d-11eb-82f0-4bb0604b8b4e.jpg)
![Screenshot_20210504-210756_Samsung Internet](https://user-images.githubusercontent.com/83679544/117084231-0c7b5c00-ad1d-11eb-831d-c97e948178fa.jpg)

**Comment by Kordishal** [comment]
Did you make this comment before or after you changed the signature? The signature is not applied retroactively.

**Comment by Gegee16** [comment]
> Did you make this comment before or after you changed the signature? The signature is not applied retroactively.

Hi! I added the signature time before the comment.

**Comment by Kordishal** [comment]
Then it might be an issue with the Plato editor and the world BBCode not working. Or you didn't actually save.

**Comment by Gegee16** [comment]
Hmmmm,I saved it tapping  the "save" button that's at the bottom of the page several times, maybe then is something with the editor/code like you said...

**Comment by iamromeo** [comment]
Why is this a bug? @Gegee16  is a free member - they have no access to signatures.
