### ISSUE TITLE
Article Template Editor Documentation is Outdated

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#23]
**World Anvil Username**: SoulLink

**World / Campaign / RPG Character / Manuscript Title**: -

**Feature**: Article Templates

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
The documentation provided for the article is very outdated and even misleading! The currently linked templates cause 404 errors when used.

Broken Templates

* Documents
* Vehicle

**Expected behavior**
Update the documentation text and update broken templates.

**Screenshots**
![image](https://user-images.githubusercontent.com/14262536/109803593-86aa3a00-7c21-11eb-9512-00a5dc67f758.png)

**Comment by iamromeo** [comment]
oh man, reading your expected to happen made me want to just delete and forget this all together :P Mr. Passive Aggressive enough :P 
I will be taking a look at this

**Comment by iamromeo** [comment]
Tested randomly **spell**, **condition** and **organization** none of them seem to be having any issues. 
Can you please elaborate which templates you have seen issues with?

**Comment by iamromeo** [comment]
The security issue that prevented document from being rendered has been rectified and tested
