### ISSUE TITLE
How long must I wait about the deleted of the archived campaigns?

### ISSUE THREAD

**Issue by Dauron24** [worldanvil/worldanvil-bug-tracker#230]
Dauron

Campaign:

Create a new Campaign:

https://www.worldanvil.com/heroes/campaign/new:

I have deleted all my old Campaign, and now I can't crate a new Campaign. I am a free user.

-   I go to the "new Campaign" open.

And The result is,

-   Warte kurz, Partner! Sadly you do not have enough campaign slots to create a new campaign. 

Expected behavior
To create a new Campaign

PS:
At this point, free accounts have access to 2 campaigns, including ARCHIVED campaigns. I can see from your account that there are currently 2 archived campaigns in system waiting for deletion.

_Originally posted by @iamromeo in https://github.com/worldanvil/worldanvil-bug-tracker/issues/190#issuecomment-826026954_

**Comment by iamromeo** [comment]
Please do not repost issues
You can always comment to your previous one and let us know you are still having an issue
We tested this and found to be working. If you are still have a problem, you can always message us. 

On the matter of how long: as a free member your requests have lower priority than the requests of the project's supporters.
