### ISSUE TITLE
Creating multiple historical events requires a lot of extra steps

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#231]
**World Anvil Username**: SoulLink
**Feature**: Timelines

**Describe the Issue**
It is very awkward to create multiple events at once.

**Expected behavior**
There should be a create historical event somewhere in that screenshot below.

**Screenshots**
![image](https://user-images.githubusercontent.com/14262536/117122203-ec3bb380-ad95-11eb-8d65-7b9da9be431a.png)

**Comment by iamromeo** [comment]
Althought this is true this is not a bug. This is a feature request or something to be discussed of how we can do better.
