### ISSUE TITLE
Error 404 when creating a new world on a new account

### ISSUE THREAD

**Issue by Marlock101** [worldanvil/worldanvil-bug-tracker#232]
**World Anvil Username**: Marlock101

**World / Campaign / RPG Character / Manuscript Title**: World

**Feature**: World writing

**Related URLS** (To public & visible pages add screenshots otherwise):
![image_2021-05-05_043352](https://user-images.githubusercontent.com/79076418/117134908-17ed7800-ad5b-11eb-9dfe-d5c0a4ddcc68.png)

after clicking save and proceed: 

![image](https://user-images.githubusercontent.com/79076418/117134948-289dee00-ad5b-11eb-8694-f80f0ec81c3a.png)

**Describe the Issue**
I go to create a world, I type in all the information, and no matter what, I get the error 404. I've tried on 3 separate browser engines (OperaGX, Google Chrome, and Microsoft Edge). I am not sure why it is happening.

**To Reproduce**
1. Go to 'Your Global Dashboard'
2. Click on 'Get world Building'
3. Enter in information
4. Click on Save and Continue
5. See error

**Expected behavior**
I excepted it to move onto the next page to continue creating a world.

**Comment by iamromeo** [comment]
The fix for this is being deployed
