### ISSUE TITLE
Error 404 When Creating Worlds

### ISSUE THREAD

**Issue by VixenWindsong** [worldanvil/worldanvil-bug-tracker#233]
**World Anvil Username**: Vixen Windsong

**World / Campaign / RPG Character / Manuscript Title**: Eprora - Public

**Feature**: N/A

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I'm trying to name a world Eprora - Public, and it won't let me create it because I used to have a world with the same name that I have since deleted. Update: I have tested this with other names that I know I haven't used yet, and it still gives me the error 404 message.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
The fix for this issue is being deployed

**Comment by iamromeo** [comment]
Please give it 15 - 20 minutes
