### ISSUE TITLE
Edit in Athena Extra Buttons

### ISSUE THREAD

**Issue by graylion-wa** [worldanvil/worldanvil-bug-tracker#235]
**World Anvil Username**:

Graylion

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 

Edit Articles in Athena 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

After clicking and article in Athena, I edit the category on the side menu, and the next article I clicks has an extra row of formatting buttons (see screen shot).

I stopped at 5 rows.

Editor - Legacy
Chrome Android

**To Reproduce**
1. Go to Athena click an article, specifically an uncategorized. The new amazing edit box is open an visible.
2. Click the edit category on the right for the article and select a new category.
3. Click the next article and there will be another or extra set of formatting buttons.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

![20210506_002652.jpg](https://user-images.githubusercontent.com/79761754/117242058-7ae61a00-ae02-11eb-8580-eb2ff88c1d25.jpg)

**Comment by graylion-wa** [comment]
![20210506_003307.jpg](https://user-images.githubusercontent.com/79761754/117242141-a8cb5e80-ae02-11eb-942c-9a8bbe683d47.jpg)

**Comment by iamromeo** [comment]
The extended version will be removed since it has no reason to exist due to the introduction of the quick edit / quick create and the reviewer

**Comment by Kordishal** [comment]
You misunderstood this one, Dimitris. It's about the duplication of the buttons. But now that I think about it I am not sure why I didn't just close it. Because it can't be reproduced consistently.

And in this case, I don't actually have an editor active on the vignette of the content edit in Athena.

![image](https://user-images.githubusercontent.com/14262536/117569356-97fe3f80-b0c5-11eb-8a9d-075944d8b5e9.png)

**Comment by iamromeo** [comment]
Actually I didn't - it's a bug that is craeted because the expanded view is there :P 
if you click on it and hten go back and try to edit anything loaded currently you will see it :)

**Comment by graylion-wa** [comment]
Just wanted to mention this is still present and happens on my laptop as well as my mobile.

![Cats   Arts Extra Button Rows](https://user-images.githubusercontent.com/79761754/119413074-f416b580-bcba-11eb-9b83-c58be7d873a1.jpg)

**Comment by Kordishal** [comment]
Which makes sense since Dimitris hasn't worked on it yet.

**Comment by graylion-wa** [comment]
Got it, I only commented because it was closed...

⁣Get BlueMail for Android ​

**Comment by graylion-wa** [comment]
Similiar behavior as above when creating new articles in the Articles & Category section.

This shows extra rows of buttons after creating a single article.

![Articles   Categories Extra Buttons](https://user-images.githubusercontent.com/79761754/124387151-5e077f00-dcab-11eb-8e6e-8e87d8acf610.jpg)
