### ISSUE TITLE
Add Lyonesse RPG System

### ISSUE THREAD

**Issue by RobertRoccio** [worldanvil/worldanvil-bug-tracker#236]
**Full Name (RPG SYSTEM)**: Lyonesse A Fantasy Roleplaying Game Based on the Novels of Jack Vance
**World Anvil Username**: hierophantX

**Add links to the RPG System Website**: http://thedesignmechanism.com/Lyonesse.php

**Add a Logo Image (only with a link to the terms of how this logo may be used and where it is from)**:

**Comment by iamromeo** [comment]
Added
