### ISSUE TITLE
Empty lines in D&D 5e Features & Traits w/ table WABBC

### ISSUE THREAD

**Issue by JHaller27** [worldanvil/worldanvil-bug-tracker#237]
**World Anvil Username**: MemberOfTheOrder

**World / Campaign / RPG Character / Manuscript Title**: Efferil Tiltathana

**Feature**: D&D 5e Sheet > Features & Traits section

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/sheet/719838/view

**Describe the Issue**
A clear and concise description of what the issue is.

There is a ton of `<br>` tags inserted above the `<table>` section within the Features & Traits section (not sure if it happens with other sections).

**To Reproduce**
1. Go to a hero sheet
2. Set System to "Dungeons & Dragons 5e"
3. Choose Statblock Type "Character Sheet (2020)"
4. Scroll down to Features & Traits section in editor
5. Insert `[table]...[/table]` section
6. Save & view sheet
7. Scroll down to Features & Traits section in sheet view
8. See way too much blank space
9. (Optional) Open HTML inspector, and inspect the "whitespace" - see that it's repeated `<br>` tags

**Expected behavior**

Table should be justified to top of section, given that no content precedes it

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

_Lots of whitespace_
![Lots of whitespace](https://user-images.githubusercontent.com/16120350/117412307-7fc1d100-aec9-11eb-8a04-2692d8d4f082.png)

_WABBC (no content before table)_
![WABBC (no content before table)](https://user-images.githubusercontent.com/16120350/117412346-8d775680-aec9-11eb-96e6-e2c0bd9119a8.png)

**Comment by Kordishal** [comment]
This is likely not something that will be changed. What should help a lot is to make sure that there is no line in your text with just BBCode. That should eliminate the line spacers.
