### ISSUE TITLE
Child Order in Bloodlines vs. Family Trees

### ISSUE THREAD

**Issue by eccbooks** [worldanvil/worldanvil-bug-tracker#238]
**World Anvil Username**: eccbooks

**World / Campaign / RPG Character / Manuscript Title**: Clarkwoods Literary Universe

**Feature**: Family Trees/Bloodlines

**Related URLS** (To public & visible pages add screenshots otherwise): https://echristopherclark.com/a/the-silver-family

**Describe the Issue**
I just noticed that the feature suggestion to "Sort Children by Birth Year" was listed as implemented, and I was psyched. However, on checking my page, I noticed that it's implemented for Family Trees but not for Bloodlines.

Family Tree, where it's correct
<img width="1552" alt="Family Tree - Correct" src="https://user-images.githubusercontent.com/83819488/117445288-83c11380-af08-11eb-929d-f8c12832f1f2.png">

Bloodline, where it's not
<img width="1552" alt="Bloodline - Incorrect" src="https://user-images.githubusercontent.com/83819488/117445349-92a7c600-af08-11eb-820e-68ed16e501e3.png">

**To Reproduce**
1. Go to 'https://echristopherclark.com/a/the-silver-family'
2. Scroll down to 'The Bloodline of John Silver'
3. Within the bloodline, scroll to 'Silas Silver VII'
4. Note the order of his children, which are displayed alphabetically rather than by birth year.

**Expected behavior**
1. Scroll further down the page to 'The Family Tree of Eli Silver'
2. Within that tree, scroll up to find Silas Silver VII.
3. Click on his image to re-center the tree on him.
4. Note the correct order of his children, which are now displayed by birth year.

**Comment by iamromeo** [comment]
@Xuroth can we prioritize this if it's not very difficult please?

**Comment by Xuroth** [comment]
Wow, I missed the notification here, despite the ping...
Yes, I'll set aside a small window today to implement this.
