### ISSUE TITLE
URL Inconsistency With Custom Domains

### ISSUE THREAD

**Issue by eccbooks** [worldanvil/worldanvil-bug-tracker#239]
**World Anvil Username**: eccbooks

**World / Campaign / RPG Character / Manuscript Title**: Clarkwoods Literary Universe

**Feature**: Custom URL for Sage Tier Members

**Related URLS** (To public & visible pages add screenshots otherwise): 
https://echristopherclark.com 
(which is the custom URL for https://worldanvil.com/w/eccbooks)

**Describe the Issue**
When clicking on a link from "Recent Articles," you get the expected URL structure of `customurl.com/a/article-name`

BUT, when clicking on a link from "World Codex" or from the "Search Box," you get a less elegant URL structure `customurl.com/w/world-name/a/article-name`

Links clicked from within the article then follow the structure of however you got there. That is, links from a page with the /a/article-name structure go to /a/article-name and links from a page with the /w/world-name/a/article-name structure go to a /w/world-name/a/article-name page

**Comment by iamromeo** [comment]
That might not be possible to be fixed due to the way caching works. 
Since the only issue here is a less nice looking URL I will be closing this. 

There is already some backend work scheduled that might fix this.
