### ISSUE TITLE
Export World button missing

### ISSUE THREAD

**Issue by Miruvor88** [worldanvil/worldanvil-bug-tracker#24]
**World Anvil Username**: Miruvor88

**World / Campaign / RPG Character / Manuscript Title**: Isra / Platinum Band

**Feature**: Export World

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/world/0e1a34a9-1d3b-4742-9685-c218d12e5a63/edit

**Describe the Issue**
I want to export my data. Everything I've searched says the button should appear on my World Configurations page. It isn't there.

**To Reproduce**
1. Go to '...' World Configurations page
2. Click on '....' Any tab
3. Scroll down to '....' Anywhere
4. See error No Button

**Expected behavior**
I expect to see the button.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
It was announced some weeks ago that the system will go dark as we deploy and test the new version. The system will be live again today.
