### ISSUE TITLE
Quick edit

### ISSUE THREAD

**Issue by KajetanWrites** [worldanvil/worldanvil-bug-tracker#241]
**World Anvil Username**: KajetanWrites

**Feature**: Quick edit in articles and categories

**Describe the Issue**
When opening quick edit through clicking on an article when the list is expanded it collapses other articles.

**To Reproduce**
1. Go to "Articles and Categories"
2. Make sure you have the expanded view on the article list
3. click on any article to open quick edit
4. all other articles will be collapsed to the smaller view

**Expected behavior**
Other articles not collapsed

**Comment by iamromeo** [comment]
works as intended
