### ISSUE TITLE
Import from JSON data fails silently for stat block creation

### ISSUE THREAD

**Issue by anathemamask** [worldanvil/worldanvil-bug-tracker#243]
**World Anvil Username**: anathemamask

**World / Campaign / RPG Character / Manuscript Title**: Farrago (world ID 7b0af352-3335-4b77-8375-5c7d76a781a7)

**Feature**: Blocks - JSON Import

**Related URLS** https://www.worldanvil.com/sheet/722607/view

**Describe the Issue**
Attempting to import block data using valid JSON seems to fail without error, only updating the `jsondata` key with the json and not changing any values of the stat block.

**To Reproduce**
1. Access a statblock and export it as a json file to ensure you have a valid template JSON to work from
2. Fill a number of JSON keys with correct data
3. Access or create a new stat block and paste your JSON data in
4. Click save changes

**Expected behavior**
Statblock should update from imported JSON data, instead it seems to have no effect on the statblock.

**Comment by Kordishal** [comment]
Ok after some discussion. Turns out this isn't a bug. It just lacks documentation and doesn't work the way you'd expect it to at first glance. Will see if I can rig up a small guide.

**Comment by Kordishal** [comment]
Well actually I've tried all sorts of things and I haven't found a way to read the JSON data object from the display twig. So I can't figure out what I am doing wrong or it really doesn't work.

**Comment by Kordishal** [comment]
Ok the jsondata elements can be targeted with 

`{{ variables.imported.fieldname }}`

So there was a bug, but it works now :)

**Comment by iamromeo** [comment]
Extra point - if you are not checking if it's defined you might run into trouble
so make sure you check
