### ISSUE TITLE
Mention system will not function for certain articles.

### ISSUE THREAD

**Issue by ScribeCarlson** [worldanvil/worldanvil-bug-tracker#245]
**World Anvil Username**: Head Librarian Carlson

**World Title**: BoS: Operation hOpe4FUTURE

**Feature**: Mention system

**Related URLS** (To public & visible pages add screenshots otherwise):

https://www.worldanvil.com/w/bos3A-operation-hope4future-head-librarian-carlson/a/nymith-carlson-article

https://www.worldanvil.com/w/bos3A-operation-hope4future-head-librarian-carlson/a/scorched-article

https://www.worldanvil.com/w/bos3A-operation-hope4future-head-librarian-carlson/a/super-mutant-species

https://www.worldanvil.com/w/bos3A-operation-hope4future-head-librarian-carlson/a/the-mire-article

Test page that was created to assist in troubleshooting in ticket 176: 

https://www.worldanvil.com/w/bos3A-operation-hope4future-head-librarian-carlson/a/scorched-species

**Describe the Issue**

The mention system on our world has stopped functioning for certain articles. It is impossible to link to an affected article via the mention system. This was not always the case and we have many preexisting links made through the mention system to all of the affected articles. 

**To Reproduce**
1. Create a new article, or edit an old article on our world
2. attempt to @ mention any of the afflicted articles (right now, @carlson, @scorched, @super mutant, @The Mire,  are known affected)
3. The @ results for the attempt will return no results and you will be unable to complete the link as intended.

**Expected behavior**

When using the mention system you should be able to use @ followed by either a full or partial word to refer to the selected article in a link. 

**Screenshots**

Videos of the error are recorded in the previously closed report (problem still persists)

https://github.com/worldanvil/worldanvil-bug-tracker/issues/176

**Comment by iamromeo** [comment]
Good day Librarian! 

Why was this not posted as a reply to #176 ? 

Fist of all, specifically for Scorched you have 2 articles with exactly the same name. 

This is not the same for some of the rest of the articles but by doing a very quick review of your world, you have some very suspect **article title** conventions that could have caused the scripts to fail. 

Just as an example "Tick (Giant Tick)" use of parenthesis and extensive use of special characters, commas, Double/single quotes etc. 

These are all not allowed characters that somehow you managed to add :P 

I cannot be certain that this is causing your issue but it certainly does not look good. 

If you can add me as a co-owner in your world username "Dimitris" I can have a quick look to see if there is a clear error I can trace.

**Comment by ScribeCarlson** [comment]
Hello Dimi! 

The 2nd scorched article was made at the suggestion of your support folks and didn't exist prior, but the problem was still happening before we made it. 

The Tick (Giant Tick) and all other articles using parenthesis are legacy articles, we made them before it became impossible to do so. We had no idea it could become an issue when we made those articles. 

I would love to add you as a co-owner but I am all out of slots! This is actually a constant issue for me :(

I need to talk to my scribes to find out who is willing to step down for a bit to make room for you, so I will get back to you if that is okay?

-Carlson

Also, we love you folks! Thank you so much for bringing this platform into the world!
    On Wednesday, May 12, 2021, 08:35:14 PM MST, Dimitris Romeo Havlidis ***@***.***> wrote:  
 
 


Good day Librarian!

Why was this not posted as a reply to #176 ?

Fist of all, specifically for Scorched you have 2 articles with exactly the same name.

This is not the same for some of the rest of the articles but by doing a very quick review of your world, you have some very suspect article title conventions that could have caused the scripts to fail.

Just as an example "Tick (Giant Tick)" use of parenthesis and extensive use of special characters, commas, Double/single quotes etc.

These are all not allowed characters that somehow you managed to add :P

I cannot be certain that this is causing your issue but it certainly does not look good.

If you can add me as a co-owner in your world username "Dimitris" I can have a quick look to see if there is a clear error I can trace.

**Comment by ScribeCarlson** [comment]
Okay! You are now listed as a co-owner of Operation hOpe4FUTURE!

Also on the comment thing, I didn't know that was possible as it was a closed bug, so I made a new report. I'm not really familiar with Github :(
    On Wednesday, May 12, 2021, 08:35:14 PM MST, Dimitris Romeo Havlidis ***@***.***> wrote:  
 
 


Good day Librarian!

Why was this not posted as a reply to #176 ?

Fist of all, specifically for Scorched you have 2 articles with exactly the same name.

This is not the same for some of the rest of the articles but by doing a very quick review of your world, you have some very suspect article title conventions that could have caused the scripts to fail.

Just as an example "Tick (Giant Tick)" use of parenthesis and extensive use of special characters, commas, Double/single quotes etc.

These are all not allowed characters that somehow you managed to add :P

I cannot be certain that this is causing your issue but it certainly does not look good.

If you can add me as a co-owner in your world username "Dimitris" I can have a quick look to see if there is a clear error I can trace.

**Comment by iamromeo** [comment]
Thank you @ScribeCarlson will be checking first thing tomorow

**Comment by ScribeCarlson** [comment]
Also FYI we're going through all of the articles today and eliminating the use of ( and ) just in case that is causing issues. 
    On Thursday, May 13, 2021, 10:03:38 AM MST, Dimitris Romeo Havlidis ***@***.***> wrote:  
 
 


Thank you @ScribeCarlson will be checking first thing tomorow

**Comment by iamromeo** [comment]
ok so, first of all **there is no bug**.

**Re: Carlson**
This is what is: 
-  A world with over 1300 articles THAT hundreds of them mention Carlson. Of course I cannot show on any dropdown or list of search hundreds of articles. The term is simply too common. 
- To make things worst the article is not called Carlson but **Nymith Carlson** 
- Searching for **Nymith** only shows two articles, the one you wish being one of them 

**Re: Scorched**
- As with Carlson too used of a term, tens and tens of articles

**Re: Super Mutant**
- "Super" as a word (which how the system works) also overly used so is not a viable search term

**Re: The Mire**
- I think I should not explain with "The" is not a viable search term :P 

Now, before closing this solution: 
The @ system searches title and content but also tags. For all but Carlson just create a unique tag on the aritcle that you can summon for example. I have added the tag "supermutant" on the super mutant article, that is the result: 

![Screenshot 2021-05-14 at 06 05 43](https://user-images.githubusercontent.com/660175/118215577-6d700600-b47a-11eb-9164-d52c2ce774a7.png)

For Carlson, for the great spaghetti monster's sake USE **NYMITH**

**Comment by ScribeCarlson** [comment]
So we have a workaround, and we will do what we can to adhere to that workaround, but it has me concerned that we keep running into these limitations in regards to the "engine" of world anvil. 

We've already run into this with the auto-sort feature, and now this issue. 

Is there any way that features like this can be "enhanced" to the point where we will not have to worry about how many articles mention an invididual article or how many articles need to be autosorted? This honestly feels like punishment for trying to do the very thing that the platform is geared for, making everything click together. 

I hope this isn't taken as a slam, it isn't, at all, but even if we are an edge case in the number of articles, we seem to be very good at finding the walls of what can be done with these systems we are being advised to use for things.

I ask because I don't see this getting anything but worse as we add more articles and connect more dots. We're already feeling kind of boxed in, even with the co-author situation. 






    On Thursday, May 13, 2021, 08:06:52 PM MST, Dimitris Romeo Havlidis ***@***.***> wrote:  
 
 


ok so, first of all there is no bug.

Re: Carlson
This is what is:
   
   - A world with over 1300 articles THAT hundreds of them mention Carlson. Of course I cannot show on any dropdown or list of search hundreds of articles. The term is simply too common.
   - To make things worst the article is not called Carlson but Nymith Carlson
   - Searching for Nymith only shows two articles, the one you wish being one of them

Re: Scorched
   
   - As with Carlson too used of a term, tens and tens of articles

Re: Super Mutant
   
   - "Super" as a word (which how the system works) also overly used so is not a viable search term

Re: The Mire
   
   - I think I should not explain with "The" is not a viable search term :P

Now, before closing this solution:
The @ system searches title and content but also tags. For all but Carlson just create a unique tag on the aritcle that you can summon for example. I have added the tag "supermutant" on the super mutant article, that is the result:



For Carlson, for the great spaghetti monster's sake USE NYMITH

**Comment by iamromeo** [comment]
(no slam was assumed) 

But, this is not a work around this is a working method. you have a huge codex (which is awesome) that some words are overused. 

In the case of Carlson this is not even an issue that needs a workaround, Nymeth Carlson is the name of the article, using numeth to summon it is not an issue, is exactly as it is supposed to be. 

In the case of "the" I think that you will agree that this is a non-issue

In the case of all the rest is a matter of having the ability to summon articles using their tags and names. 
There is no enhancement that can be made to fix this even if I wanted to unless you consider loading a dropdown of 100s of articles which will be much harder to navigate.

**Comment by Kordishal** [comment]
Hi!

Dimitris and I discussed your issue a bit further and have found the root of the problem within your world.

Not too long ago there was an enhancement to the mention-search to not only search title and then content but actually title+tags and content.

This helps with certain use cases such as non-Latin characters, two-letter titles, similar / duplicated titles and more.

Unfortunately for your system, it has the side-effect of now bringing up all these related, but not titular articles in the search result. Since you tag a lot of things with `scorched` and `carlson`.

There are three ways you can handle this issue

1. Use different parts of the names to search the right article (e.g. in the case of carlsons use the first names)
2. Add unique tags which distinguish these types of articles from others and bring up the right articles when searched.
3. Rework your entire tagging system to address this change.

I realize that considering the size of your project this is not optimal, but due to the benefits of tag-based searching, there will be no change on the side of World Anvil.

There is a tag manager on the roadmap. It's not right around the corner so it might be a bit until it becomes a reality, but it will certainly help with 2 and 3. So if you can live with it as is it might be worth the wait.

Feel free to contact me on Discord in one of the help channels or any other really. (`SoulLink | World Behind the Veil`, there are two. I am the one with the Honorary Forge Gremlin role). Or simply ask here for ideas on how to use tags to improve managing your world and articles.

**Comment by iamromeo** [comment]
Note: to ease the issue slightly I have just changed the max search return results from 50 to 100

**Comment by iamromeo** [comment]
https://user-images.githubusercontent.com/660175/118248750-58f93100-b4ad-11eb-9d37-c6a4fa716ef3.mov
