### ISSUE TITLE
When printing an article, it's not readable anymore

### ISSUE THREAD

**Issue by shyredfox** [worldanvil/worldanvil-bug-tracker#248]
**World Anvil Username**: shyredfox

**World / Campaign / RPG Character / Manuscript Title**: https://www.worldanvil.com/w/liminal-chronicles-shyredfox

**Feature**: Printing articles

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/liminal-chronicles-shyredfox/a/liminal-chronicles-fill-in-the-blanks-game-232-article (The example)
https://www.worldanvil.com/w/hacks-and-help-shyredfox/a/css3A-fill-in-the-blank-game-article (what I had to do to get it to print nice. I feel it treads into questionable CSS and I'd rather not have to do that to get the article page to print.)

**Describe the Issue**
When I go to print an article it's practically unreadable. I had to use some questionable CSS foo to get it readable. :(

**To Reproduce**
1. on a WA article, print it with CTRL-P

While I can print only a selected area and get a clean print, that's not ideal either, especially on long articles.

I did a quick test on a manuscript - it's much better.

**Expected behavior**
I would like to print a readable page.

**Screenshots**
This is what printing looks like from Chrome and Firefox and from my ipad Chrome. Same issue if use incognito. 
![Screenshot_12](https://user-images.githubusercontent.com/59369948/118288967-7bce1a00-b49a-11eb-8271-57a975b54fd7.png)

**Comment by Kordishal** [comment]
You should export the article and then print that page. That will be a much better result.

**Comment by shyredfox** [comment]
That does help for general articles for myself. Thanks! 

Though it doesn't help with my case of a printable game for others to use. Nor would it help for say someone wanting to print a set of RPG rules in a world. There are several cases where a good easy to print page is needed.

**Comment by shyredfox** [comment]
The export stripped out all my CSS for the game page too. If a page relies on CSS formatting, the export is not a good option.

**Comment by shyredfox** [comment]
I can see that the above dissuades people from just printing out and using other people's work. I don't know if that is the intention.

**Comment by iamromeo** [comment]
**WA is not meant to be printed**. this is not a feature so it cannot be a bug.
 There are classes that can help with something being printed

**Comment by shyredfox** [comment]
> There are classes that can help with something being printed

Cool. I do not see this in the Codex. how do I find them?

**Comment by Kordishal** [comment]
There is nothing on that on the codex. But basically, you can use CSS to tell it how to layout printed pages separately from other layouts with the @print rule scope. 

So the idea is to use this special CSS to make sure that the important pages are printed properly.

**Comment by shyredfox** [comment]
Maybe I misunderstood Dimi's answer. I was using @media print to strip away everything but the few things I needed and putting it into the page only CSS. But that involved stripping out some things I felt that approached what are AREN'T supposed to do with CSS. So this is why I wrote up the issue in the first place.

**Comment by Kordishal** [comment]
Ah yeah its

```css
@media print {
    stuff for print
}
```
so got that right. As for you breaking the CSS rules... you can't CSS rules only apply to Journeymen, Masters & Grandmasters. You are paying for being able to do all the things.

**Comment by shyredfox** [comment]
So I'll just have to be very careful if I write a tutorial on how to make a game page like mine. Ok Thanks for the clarification! <3
