### ISSUE TITLE
Broken visibility toggle

### ISSUE THREAD

**Issue by LukasHDyreborg** [worldanvil/worldanvil-bug-tracker#249]
**World Anvil Username**: SakulBadger

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: Visibility toggle, and article link

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When I link to an article within a container the visibility toggle breaks.

**To Reproduce**
1. have 2 articles
2. in article 1 create a container
3. write text in container
4. link to article 2 within container
5. view article 1
6. toggle invisibility for the container
7. check article 1 in incognito or another user
8. the invisible part should still be visible

**Expected behavior**
you cannot toggle a container's visibility and have it work for other users.

**Screenshots**
article is published and the text is in containers
![image](https://user-images.githubusercontent.com/62420691/118291881-5a8c1e80-b4d8-11eb-8fe1-e4dec6b14a66.png)

on the left is the page when I open it via view, on the right is it opened using inkognito
![image](https://user-images.githubusercontent.com/62420691/118292152-9fb05080-b4d8-11eb-92f9-c47158d55f74.png)

when I press visibility toggle
![image](https://user-images.githubusercontent.com/62420691/118292245-b8b90180-b4d8-11eb-9b49-c683630bc277.png)

I add the link to article 2
![image](https://user-images.githubusercontent.com/62420691/118292464-f158db00-b4d8-11eb-836c-5e98c95720b6.png)

the link to article 2 is now visible
![image](https://user-images.githubusercontent.com/62420691/118292685-2e24d200-b4d9-11eb-9fae-77e683c385a8.png)

I click the visibility toggle (it should now be invisible on both pages and I have reloaded) but the inkognito can still see the container that should be invisible
![image](https://user-images.githubusercontent.com/62420691/118292891-662c1500-b4d9-11eb-85d3-c64122a37cec.png)

and here is a picture of article 2 if it should be needed
![image](https://user-images.githubusercontent.com/62420691/118293058-8d82e200-b4d9-11eb-98da-9524d598c939.png)

**Comment by iamromeo** [comment]
I am really sorry but this is not broken/ Visibility toggle does not work with mentions. This should be documented already.

**Comment by Kordishal** [comment]
With all of them? When we talked about this last it was only broken by draft article mentions. Not all of them (I updated the codex to reflect this, just to confirm).
