### ISSUE TITLE
Text editor issues occurring in conjunction with autosave

### ISSUE THREAD

**Issue by ReksUni** [worldanvil/worldanvil-bug-tracker#25]
**World Anvil Username**: ReksUni

**World / Campaign / RPG Character / Manuscript Title**: Vanis

**Feature**: Autosave/Text Editing

**Related URLS** (To public & visible pages add screenshots otherwise): 
N/A

**Describe the Issue**
While editing an article for one of my continents, I attempted to place new line breaks near the top of my article through use of the enter key. Each time I did so, it would instead jump my cursor to the bottom of the paragraph and insert the line break there. I attempted to rectify this by hard-coding line breaks using the functions at the top of the screen, but after doing so, the editor refused to allow me to interact with the BBcodes I had placed, or to place text in front of them or remove them. Each time I interacted with the text in any way, even though the editor would not actually change anything present, the saving icon would appear in the top of the page. After fully refreshing the page, I was able to remove the placed BBcodes, but the moment the page autosaved again, all of the issues began once more. At the moment, I am essentially unable to add any new text before the paragraph I had created. This seems somehow linked to the autosave function, as issues only begin to occur once the page has autosaved for the first time. Further, after managing to remove the BBcodes, manually saving, and refreshing the page, the codes have reappeared, which seems to indicate that the page is not in fact saving at all.

For context, I have recently begun using Firefox as my browser. I did not experience this issue on Chrome. I am uncertain if this has anything to do with the problem.

**To Reproduce**
1. Create a new Geographic (or possibly any) Article
2. Fill in the main content box with any amount of text
3. Allow autosave to occur
4. Attempt to place new edits before existing text

**Expected behavior**
Should function as normal for a text editor

**Screenshots**
N/A

**Comment by Kordishal** [comment]
Hi! 

The Plato editor will be reworked in the future and current issues will not be fixed. In the meantime, you can switch to the Euclid editor (see [here](https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors)).

The issue you encounter might be caused by an extension or plugin you installed in Firefox.
