### ISSUE TITLE
Custom column widths in markup tables are lost when switching between WYSIWYG and BBcode editors

### ISSUE THREAD

**Issue by TheAks999** [worldanvil/worldanvil-bug-tracker#250]
**World Anvil Username**: TheAks999

**World / Campaign / RPG Character / Manuscript Title**: Refuge

**Feature**: Text Editor

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When custom column widths are added to the text of a page using the bbcode editor, you can see the effects in the preview or view page. However, when you return to the editor, or swap between WYSIWYG and BBcode editors those column widths are lost.

**To Reproduce**
1. Edit an article
2. Click on "Insert a Table" and insert a 2x2 table with headers
3. Click on "View Source" or (ctrl+shift+s)
4. Edit the [th] tags to be [th:20] (there should be 2)
5. Save the page
6. Switch back to WYSIWYG mode - Click on "View Source" or (ctrl+shift+s)
7. Switch back to BBCode mode - Click on "View Source" or (ctrl+shift+s)
8. The custom edits to the [th] tags will be missing

**Expected behavior**
Returning to BBCode mode should keep the custom tag edits

**Screenshots**
On request

**Comment by Kordishal** [comment]
This is not a bug but a lack of feature. These options simply have not been added to the Plato editor.

**Comment by TheAks999** [comment]
This could probably be partially supported if the metadata was just stored in the Plato editor when swapped to so swapping back and forth doesn't lose formatting. Easier than a full on editor feature at least.

**Comment by Kordishal** [comment]
Yeah, but the editor is based on tech that was discontinued and has various issues. It will be rebuilt soonish. In the meantime using the BBCode editor will avoid all those issues.

So it is just not worth investing the time even in a workaround.
