### ISSUE TITLE
Bug with '[abc' link insertion feature when selecting via the mouse.

### ISSUE THREAD

**Issue by Dresdon** [worldanvil/worldanvil-bug-tracker#251]
**World Anvil Username**:
Dresdon

**World / Campaign / RPG Character / Manuscript Title**:
Nightwinter Tales

**Feature**: 
The '[abc' feature to link to other articles.

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When you use the mouse to select a link to an image/map etc that appears due to doing '[abc' the link looks like it has been inserted into the document but if you save, then view the page, you will see '[abc' instead of the full link.

**To Reproduce**
1. Create a new generic article and give it a title
2. In the vignette box type '[abc' where 'abc' matches an image/map to be linked to in your collection.
3. Select the item using the **_Mouse_** list that appears. You'll see the link inserted into the text box.
4. Click Save changes.
5. Click Ctrl + View to open the view in a new tab. 
6. Navigate back to the article via the Articles & Categories and reopen it.
7. You can see in the vignette box now '[abc' instead of the link was actually saved.

**Expected behavior**
The link to be inserted correctly and the image/map etc to show in the view tab.

Note, did a bit of troubleshooting on this with someone in discord. If you press space or enter after the link is inserted the link does get inserted correctly. So the behaviour is purely linked to selecting from the mouse and then saving and viewing.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
<img width="214" alt="bug01" src="https://user-images.githubusercontent.com/7947589/118357262-1bf67280-b571-11eb-8b2d-f301f9293516.png">
<img width="132" alt="bug02" src="https://user-images.githubusercontent.com/7947589/118357265-1f89f980-b571-11eb-89b8-5cb903105483.png">
<img width="347" alt="bug03" src="https://user-images.githubusercontent.com/7947589/118357271-24e74400-b571-11eb-8d5e-1d2308f4cf9b.png">
<img width="255" alt="bug04" src="https://user-images.githubusercontent.com/7947589/118357273-287acb00-b571-11eb-8124-cb0252ed6bfa.png">

**Comment by Kordishal** [comment]
This is not a bug. Mouse clicks are not registered by the auto-save. Just press any key on your keyboard after selecting with the mouse.

**Comment by Dresdon** [comment]
Whilst it may not trigger the autosave, I manually clicked the save changes button after clicking the mouse to insert the link.
So even if mouse clicks don't trigger the autosave, I'd expect directly clicking 'save changes' to do so.
The behaviour is also misleading, I'm surprised you just closed this as not a bug.
    On Saturday, 15 May 2021, 12:00:03 BST, Jonas Waeber ***@***.***> wrote:  
 
 


This is not a bug. Mouse clicks are not registered by the auto-save. Just press any key on your keyboard after selecting with the mouse.

**Comment by Kordishal** [comment]
Hi, there is no save button for that field actually. But in the editor, you are right that it is not applied. Dimitris will investigate if there is a solution for that, but it is not a high priority.
