### ISSUE TITLE
Custom CSS Class not being applied to Markers when they belong to a Marker Group

### ISSUE THREAD

**Issue by GeckoOBac** [worldanvil/worldanvil-bug-tracker#255]
**World Anvil Username**: GeckoOBac

**World / Campaign / RPG Character / Manuscript Title**:  The Winter Vanguard Campaign

**Feature**:  Custom CSS Class on Map Markers

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/the-winter-vanguard-campaign-geckoobac/map/08c09384-58e4-4038-b247-4c3b401903e0

Screenshot exemplyfying the issue:
https://i.imgur.com/LBZS2HM.png

**Describe the Issue**
If a map marker belongs to a Marker Group, the custom CSS class doesn't get applied on the rendered page.
This can be seen in the above screenshot: the top "battle marker" has a custom class applied but belongs to a marker group, while the bottom one has the same class but isn't in a marker group and the CSS is correctly applied.

**To Reproduce**
1. On a map, create a new marker and assign it a custom CSS class
2. Create a marker group on that same map
3. Add some CSS styling to the custom class
4. See it applied on the marker on the map view
5. Assign the marker to the marker group
6. Check that the class is no longer applied and the styling is gone.

You can switch back and forth by assigning/unassigning the marker group.

**Expected behavior**
The CSS Styling and CSS class should be always applied, regardless of whether the marker belongs to a marker group.

**Screenshots**
Screenshot of the working styling:
https://i.imgur.com/UICE2Yg.jpeg

Screenshot of the broken marker:
https://i.imgur.com/pAHOKL5.jpg

Screenshot of the previously broken marker, now removed from its marker group:
https://i.imgur.com/QxGuHlu.jpg

**Comment by iamromeo** [comment]
This should now be fixed. - will. be deploying within the hour

**Comment by Kordishal** [comment]
Can confirm that this still happens.

**Comment by iamromeo** [comment]
I will need an example guys because I cannot replicate it

**Comment by GeckoOBac** [comment]
Sure:
https://www.worldanvil.com/w/the-winter-vanguard-campaign-geckoobac/map/08c09384-58e4-4038-b247-4c3b401903e0

This is the map I used to open the ticket. I set it up so there are 2 marker groups atm, and the two "battle" markers both use a custom css class to change the look and give a different background color.

Right now I set it up so the "Enraged Owlbear" is without a group: and (in presentation mode) the class is correctly applied and visualised.

The "Goblin Ambush" marker is instead in marker group 1, has a similar class applied in the settings but it doesn't get applied in the presentation mode.

Adding or removing the markers to a marker group affects whether the CSS class is applied or not and I can freely switch back and forth on either marker just by assigning/unassigning the marker to a marker group. Checking in the F12 panel in Chrome shows that it's not a rendering issues: the class doesn't get applied to the marker element at all when the marker is in a marker group.

If you need me to do some specific tests I'm available.

**Comment by iamromeo** [comment]
This is added as a note for Atlas this bug will not be addressed to the version since Atlas will replace the current system
