### ISSUE TITLE
Small typo 

### ISSUE THREAD

**Issue by 777-77** [worldanvil/worldanvil-bug-tracker#256]
**World Anvil Username**:jesse.j777 

**World / Campaign / RPG Character / Manuscript Title**: Heltat 

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/WorldAnvilCodex/a/bbcode#full-layout

This is the URL where the typo is found 

**Describe the Issue**
A clear and concise description of what the issue is.

Merely scroll down to where the category of adding a follow button on our articles using the bbcode. 
And you'll notice a typo. 
It says 
"To number after follow: is the World's id."

I believe it should be

"The number after follow: is the Worlds I.d"

**To Reproduce**

**Expected behavior**

I expected the words to be right.
Haha jk :)

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Screenshot_20210515-180110_Firefox](https://user-images.githubusercontent.com/84044229/118380615-c342cc00-b5a8-11eb-960a-f799735359dd.jpg)

**Comment by Kordishal** [comment]
Thanks!
