### ISSUE TITLE
Enter key behaviour is incorrect.

### ISSUE THREAD

**Issue by admiralnlson** [worldanvil/worldanvil-bug-tracker#258]
**World Anvil Username**: admiralnlson

**Feature**: WYSIWYG editor

**Describe the Issue**
Pressing Enter in the middle of header just moves the cursor to the next line, which is quite ridiculous (Enter != down arrow).

**To Reproduce**
1. Edit any page with the WYSIWYG editor
2. Create or go to a H1 header
3. Click in the middle of it
4. Press Enter

**Expected behavior**
Enter key behaves like it would in any other text editor.

**Comment by Kordishal** [comment]
Hi, this is a known issue and will be dealt with the rebuild of the Plato Editor. This will not be fixed until then.
