### ISSUE TITLE
Auto-Save causing lag in large articles

### ISSUE THREAD

**Issue by hoodwink107** [worldanvil/worldanvil-bug-tracker#259]
**World Anvil Username**: hoodwink

**World / Campaign / RPG Character / Manuscript Title**: Umbra/ Wizard

**Feature**: Content/Article/Auto-save?

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I keep getting serious, what appears to be input, lag when working on all my articles. It appears that the article is auto-saving with each keystroke or after a short amount of characters, causing me to have to wait upwards of 10-15 seconds each time I write something and I can't see what I'm typing until it auto-saves and suddenly appears. When I go back to amend any errors, the same lag-inducing error occurs after I make the change.

I've tried resetting my cache, not having any other browser windows open, closing other programs to reduce any potential memory conflicts, etc. Nothing has improved the situation.

This occurs in all of my articles I've tested it on.

Overall, this is greatly killing my desire to keep using this platform, which is a huge bummer since I enjoy lots of the other functionality.

**To Reproduce**
_1. Go to_ 'https://www.worldanvil.com/world/article/7b81f239-22b2-4467-89ba-c06b6144ec54/edit' or any of my other articles.
_2. Click on_ 'the text/article editor.'
_3. Begin begin typing in the field_
_4. See error_

**Expected behavior**
Exactly what I experience when I type in fields on literally any other website I visit (like right now on GitHub!). Instant, real-time typing experience and no lag, input or auto-save generated.

**Screenshots**
The first shows when I started typing. The second shows the sentence finally resolving and showing up, after 37 seconds.
![WA Error 1](https://user-images.githubusercontent.com/84288323/118409271-d4dab100-b646-11eb-96e7-a9f12a3d180c.jpg)
![WA Error 2](https://user-images.githubusercontent.com/84288323/118409274-da37fb80-b646-11eb-8727-057e282783c0.jpg)

**Comment by Kordishal** [comment]
Hi, this is not a general issue. My test article with 100k words still saves in ms and not seconds. The most likely cause is either that you have a lot of content in one of the prompt fields which is not considered a bug as you are not supposed to put more than a few paragraphs in there.

If you do not have a lot of content in any of the small prompt sections then this is most likely a bad interaction with an extension. Try to edit an article in a private window and see if the issue persists. If not then disable your extensions.

**Comment by iamromeo** [comment]
This can also be an issue caused by extensions loaded on the browser or a computer with low capabilities or spyware weighing on the browser
