### ISSUE TITLE
Dead Link Causes 404

### ISSUE THREAD

**Issue by Lenosallose** [worldanvil/worldanvil-bug-tracker#26]
**World Anvil Username**: 
Lenosallose.

**Describe the Issue**
A dead article link, to a deleted character article, connected to a deleted Player Character, causes a 404.

**To Reproduce**
1. Create a player character.
2. Create a character article connected to player character. (Unless it is created automatically).
3. Link character article on another article. 
4. Delete player character. 
5. Delete character article connected to player character. (Unless it was deleted alongside the player character).
6. Click on the article the character article link is located.

PS: This bug can be resolved by simply deleting the link and leaving the name of the article. Though it has to be done manually.

**Comment by iamromeo** [comment]
I am sorry but I am confused. What was the link for? The character ARTICLE or the character PROFILE and can I have an example of that "link"

**Comment by Kordishal** [comment]
This does not actually happen if you follow the steps you outlined Leno. There must have been some other issue causing the error even if the removal of the link resolved it.
