### ISSUE TITLE
Saving articles creates long text in boxes

### ISSUE THREAD

**Issue by WritesBooks** [worldanvil/worldanvil-bug-tracker#260]
**World Anvil Username**: KeeperofallTales

**World / Campaign / RPG Character / Manuscript Title**: Elves (first link) AND Perli (second link)

**Feature**: Articles

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/world/species/2d4a7d90-307a-4317-8cd1-9f1137c3b2b9/edit       AND     https://www.worldanvil.com/w/perli-keeperofalltales

**Describe the Issue**
A clear and concise description of what the issue is.  
When I save my article, a long text of what looks like code appears in all boxes, with or without writing. 

**To Reproduce**
1. Go to the links that I shared. 
2. For the first link, click on the button at the bottom of the page that says "Show Template Specific Prompts & Connections". 
3. Scroll down to the box labelled: ANATOMY & MORPHOLOGY and scroll to the bottom of the actual text. 
5. For the second link, scroll to the first paragraph and go to the bottom of the real text. 
6. See error

**Expected behavior**
I expected the article to save normally without extra text.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Screenshot 2021-05-17 8 03 47 AM](https://user-images.githubusercontent.com/84323638/118485686-b9bf7e00-b6e6-11eb-99e4-8c4ed2b641d0.png)

**Comment by Kordishal** [comment]
Hi, this is a known issue and happens in the Plato editor. Switching to the Euclid editor should resolve the issue (you might have to remove the code out of the content boxes). Once you've resolved the issue you should be able to return to the Plato editor, but we do not know at this time under which circumstances this happens.

Find more out about the editors [here](https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors).
