### ISSUE TITLE
Cannot create historical events

### ISSUE THREAD

**Issue by blaster17** [worldanvil/worldanvil-bug-tracker#261]
**World Anvil Username**: blaster17

**World / Campaign / RPG Character / Manuscript Title**: Mundus

**Describe the Issue**: In some editing formats, such as timelines (creating a historical event) and the date and time of configure my world, the save changes button at the top right of the screen doesn't do anything when you click it. I can't create historical events or change the time settings of my world. I don't know if this happens in other places on the page or if it is a problem with my devices, but I have tried on my computer and phone and the same thing happens.

**To Reproduce**
1. Go to timelines.
2. click in the "historical events" button
3. click in the "create new historical event" button
4. Fill the options and click the "create historical entry" button

**Expected behavior**: nothing happens (The same thing happens with the save button of date and time)

**Screenshots**
![image](https://user-images.githubusercontent.com/58350595/118491502-702a5f80-b6f5-11eb-8155-3882c869d82b.png)

**Comment by Kordishal** [comment]
Hi, have you attempted to create a minimal event by just adding a simple title and nothing else? This is not a general issue event creation works fine. If the issue persists we will need more detailed instructions on what you do.  Alternatively please come by the [Discord](https://worldanvil.com/discord) for additional help. 

PS: you can continue to answer hereafter the issue is closed.

**Comment by blaster17** [comment]
Hi, thanks for your response. if by minimal event you mean creating a normal historical event with just a simple name it doesn't work for me. If there is another way to create an event let me know. For more information when I click the "create" button it doesn't change the page at all. I don't know if this is what should happen or if something is happening to me in particular.

**Comment by blaster17** [comment]
It doesn't seem that the historical event button is the particular problem. It seems that my problem is the button itself, because the same happens in parts of the page where the same button is seen, such as historical events, date and time and map creation.

**Comment by Kordishal** [comment]
Then I am not sure what the issue is. Sounds like something prevents you from creating new content in general. Never heard of anyone having this issue before.

**Comment by blaster17** [comment]
Well, thanks for your help anyway!

**Comment by blaster17** [comment]
I have been able to create a couple of eras in my timeline but I have not been able to create historical events. I have also been able to create an article of a material, a metal. I don't know what could be happening.
