### ISSUE TITLE
Articles completely or partially erased

### ISSUE THREAD

**Issue by Grise-art** [worldanvil/worldanvil-bug-tracker#262]
**World Anvil Username**: Grise

**World / Campaign / RPG Character / Manuscript Title**: Les Voileterres

**Feature**:  

**Related URLS** (To public & visible pages add screenshots otherwise):
Here are the articles with the issue (I fixed them since)
https://www.worldanvil.com/w/les-voileterres-grise/a/28en29-encounter-article
https://www.worldanvil.com/w/les-voileterres-grise/a/le-llahe-article
https://www.worldanvil.com/w/les-voileterres-grise/a/nepo-article
https://www.worldanvil.com/w/les-voileterres-grise/a/le-kappu-article

**Describe the Issue**
I had not browsed my worldanvil page for a while, but when I did a few days ago I realized some of the articles were incomplete, and one of them was even completely erased (the article still existed but it was blank). For the others, a random amount of text was missing at the end. 

Fortunately, I write everything on google drive before I copy it on WorldAnvil so it was an easy fix, however I feel like it could be a big problem and that you guys should know.

For a little context, my account downgraded from Grandmaster to Freeman recently and I did not browse it since the big update on the WorldAnvil interface, so maybe it could come from one of these events.

**To Reproduce**
I fixed it so you can't see it anymore ?

**Expected behavior**
/

**Screenshots**
Screenshot I made of the completely blank article (before fix) :
![image](https://user-images.githubusercontent.com/84344695/118534851-02f4e980-b74a-11eb-9cba-84576340c81c.png)

**Comment by iamromeo** [comment]
World Anvil has no functionality that would for any reason delete content from articles and I have no way to reproduce this Grise. 
The chances are that this is an overwritten article(s)
