### ISSUE TITLE
Map Creation Problem

### ISSUE THREAD

**Issue by Megagitzer** [worldanvil/worldanvil-bug-tracker#263]
**World Anvil Username**: Fenrir_growl

**World / Campaign / RPG Character / Manuscript Title**: Aton

**Feature**: Map

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/world/map/new

**Describe the Issue**
A clear and concise description of what the issue is.

Creating/Uploading a Map failed about a hundred times on different browsers and devices. Filesize is in allowed range and .png, but i´ve tried other images as well. I´m getting different error messages depending on browser used, including Secure connection failed on Firefox, on Chrome it stops at uploading: 0% in the bottom left corner and displays this message: website https://www.worldanvil.com/world/map/new is currently not available. (or something to that extent, its german.)
ERR_HTTP2_PROTOCOL_ERROR. 

**To Reproduce**
1. Go to '...' https://www.worldanvil.com/world/map/new
2. Click on '....' NEW MAP (after selecting image, inserting title.)
3. Scroll down to '....' just wait for about a minute
4. See error. again and again

**Expected behavior**

i expected my shiny map, on which i´ve spent dozens of hours, to pop up. only to be disappointed.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

![grafik](https://user-images.githubusercontent.com/84348842/118545707-7b59ab80-b746-11eb-9fda-4eeafa25abdc.png)

thank you very much.

**Comment by iamromeo** [comment]
Can you please provide the file you are trying to upload

**Comment by Megagitzer** [comment]
well, i cant upload it here because its bigger than 10mb (13.8mb)
so, where´s it supposed to be going?

**Comment by Megagitzer** [comment]
![atonalpha12](https://user-images.githubusercontent.com/84348842/118562800-ec0bc280-b75c-11eb-9d7c-45382133bff4.jpg)

it´s .jpg now, but i cant upload this one, either. so it´ll do i guess.

**Comment by Megagitzer** [comment]
[atonalpha123.zip](https://github.com/worldanvil/worldanvil-bug-tracker/files/6497239/atonalpha123.zip)

it´s .jpg now, but i cant upload this one, either. so it´ll do i guess.

**Comment by Megagitzer** [comment]
i actually managed to fix the issue, it was something related to norton security. kinda thought so from the start. i could upload the map after deactivating the lot for the time being. sorry for wasting your time i guess and keep up the good work. you´ ve got some pretty cool stuff going on here. :)
