### ISSUE TITLE
Form Background Color not applied to editors

### ISSUE THREAD

**Issue by buckwell0** [worldanvil/worldanvil-bug-tracker#264]
**World Anvil Username**: buckwell

**World / Campaign / RPG Character / Manuscript Title**: End Of Everything

**Feature**: ?

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Issue is, even when I chose the form background color -lets say white- some of the places remains still black-gray. You can see almost everywhere except a little places. It's not applying itself to where it should. For instance, in any chosen character, any article is still black despite the fact that I've chose the white color for it.
**To Reproduce**

**Expected behavior**
I expect that when I chose the color, I'd want to see it working properly in everywhere.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Bug](https://user-images.githubusercontent.com/84354328/118561925-77dd1900-b774-11eb-8ba4-a4891db4c84b.png)

**Comment by iamromeo** [comment]
These styling rules are not relevant to Euclid and they cannot be since it will require a complete colour theme change across the board for each of the tags which of course cannot be done safely. 

I will be adding a note to the interface editing page but this cannot be resolved.

**Comment by iamromeo** [comment]
Oddly enough these shouldn't even be visible since they are only applied / relevant to the legacy editor.

**Comment by Kordishal** [comment]
#172
