### ISSUE TITLE
Original RPG Systems

### ISSUE THREAD

**Issue by Chierri** [worldanvil/worldanvil-bug-tracker#266]
**Full Name (RPG SYSTEM)**: Original System
**List Name** (Name under which it should be listed on World Anvil): Original System
**World Anvil Username**: W.Cherry

**Website**:

**Logo Image Link**:

**Logo Usage Terms (URL)**:

**Comment by iamromeo** [comment]
I am sorry but I could not find any reference to this system - this is closed - feel free to provide more information so I can add it to the list
