### ISSUE TITLE
Prose articles use #000!important text on #000!important background in Area 51 theme.

### ISSUE THREAD

**Issue by rokiyo** [worldanvil/worldanvil-bug-tracker#268]
**World Anvil Username**: Rokiyo

**World / Campaign / RPG Character / Manuscript Title**: Watchtower Archives

**Feature**: Prose article

**Article appearance**
![image](https://user-images.githubusercontent.com/4364040/118789910-99efac00-b8d8-11eb-9846-81a033298493.png)

**Article appearance with text highlighted**
![image](https://user-images.githubusercontent.com/4364040/118789927-9e1bc980-b8d8-11eb-8486-1bfad6cbf28f.png)

**Describe the Issue**
style.css is specifying a black background:
![image](https://user-images.githubusercontent.com/4364040/118790254-ed61fa00-b8d8-11eb-8352-fa552fd20e47.png)

style.css is attempting to specify moonrock text colour, by is being overridden by display.css
![image](https://user-images.githubusercontent.com/4364040/118790312-fc48ac80-b8d8-11eb-8ee4-f31fb2ac102d.png)

**To Reproduce**
1. Switch world to Area 51 theme.
2. Create a prose article
3. Fill it with sample text
4. View the page

**Expected behavior**
The text should be a different colour from the background.

**Screenshots**
As above.

**Comment by iamromeo** [comment]
@Kordishal can you please let Timepool know about this?

**Comment by Kordishal** [comment]
Messaged timepool.

**Comment by Timespool** [comment]
I got it! It's an easy fix, I'd just like to wait on sending over the updated file til I've finished styling the other bits and bobs that have come out and changed since the last update. If this is urgent to you, however, I'll send over the fixed version ASAP.

**Comment by rokiyo** [comment]
While you're at it, might I suggest something along these lines for fixing the org tree?

```
.user-css-extended .orgtree li a,
.user-css-extended .orgtree li a:hover {
font-family: Aldrich;
text-transform: uppercase;
font-style: normal;
border: 2px solid var(--MartianJuice);
}
```
This stops the org tree from resizing based on where you mouseover, while still keeping all of the recoloring.

**Comment by iamromeo** [comment]
> While you're at it, might I suggest something along these lines for fixing the org tree?
> 
> ```
> .user-css-extended .orgtree li a,
> .user-css-extended .orgtree li a:hover {
> font-family: Aldrich;
> text-transform: uppercase;
> font-style: normal;
> border: 2px solid var(--MartianJuice);
> }
> ```
> 
> This stops the org tree from resizing based on where you mouseover, while still keeping all of the recoloring.

is this a fix for this theme or a generic fix?

**Comment by rokiyo** [comment]
I haven't seen this issue on other themes, but I can't tell you if this is a case of every other theme I've checked manually fixing a common issue, or if this an issue created by this theme.

Default appearance:
![image](https://user-images.githubusercontent.com/4364040/119254410-7c348680-bbf9-11eb-87a4-8153b927ac5f.png)

Mousing over "Kardia Residential Hub":
![image](https://user-images.githubusercontent.com/4364040/119254415-835b9480-bbf9-11eb-9717-358e19fe5ec8.png)

Issues:
- Children of the moused-over element lose the 2px border, making them 4px narrower & shorter overall.
- The moused-over element changes to a different font-family, significantly altering the width of that element.
- The tree as a whole is using Arial font, while the rest of the theme uses a mix of Aldrich & Gayathri

**Comment by Timespool** [comment]
Yeah I can fix all of that, that one is totally my bad! Thanks for noting it!

**Comment by iamromeo** [comment]
@Timespool do we have an update / estimate on this? Is there a plan to be fixed or should this issue be closed?

**Comment by Timespool** [comment]
Apologies, I was recovering from my second vaccine dose last week and was away from my email.

Yes, I should be able to get this fixed sometime this month. I've got a lot of squished time between my job search, commissions, and studying, so it'll have to be done in smaller chunks.

**Comment by iamromeo** [comment]
@Timespool will this be fixed or shall I close this bug

**Comment by Timespool** [comment]
This was fixed with the new version I sent you a few weeks ago.

**Comment by iamromeo** [comment]
@Timespool duh! Thank you!
