### ISSUE TITLE
Profile Images don't take into account Guild File Size Increases

### ISSUE THREAD

**Issue by IsaacAThom** [worldanvil/worldanvil-bug-tracker#269]
**World Anvil Username**: Isaac Thompson

**Feature**: Profile

**Describe the Issue**
When uploading an image for use as a profile banner or profile picture, anything over ~1.5mb fails to upload, despite having a maximum file size of 10mb as a Grandmaster.

**To Reproduce**
1. Go to 'Edit your profile'
2. Select an image over 1.5mb for your profile or banner image
3. See "Your have tried to upload a file over your upload limit OR your file storage is full." Error

**Expected behavior**
The profile should allow for images up to the guild limit.
Alternatively, the page should clearly state that the file size limit for profiles is different from the normal. (This might be preferable, to ensure that profiles load smoothly)

**Comment by iamromeo** [comment]
never did never will
