### ISSUE TITLE
PC character Sheet 404 error

### ISSUE THREAD

**Issue by Sombrelapin** [worldanvil/worldanvil-bug-tracker#27]
**World Anvil Username**:Jimmy Dallaire

**World / Campaign / RPG Character / Manuscript Title**:Sky City / Les Urban Defenders / Testy McTest (character Created by Saggeek)

**Feature**: Edit PC character Sheet

**Related URLS** (To public & visible pages add screenshots otherwise):

https://www.worldanvil.com/heroes/character/f21a3056-7002-4988-9dd9-6b68aa613707/activate

https://www.worldanvil.com/heroes/sheet/673789/edit

**Describe the Issue**
"Saggeek" Created a character for my campaign and add a sheet to it. When I go to "Sheet" I see the charactersheet BUT there is a prompt to "activate" the character sheet option (see bug.png screenshot). When I clic on it i get a white page (first URL ending by "/activate"). When I'm on the "Cast" page and clic "edit sheet" (see bug2.png screenshot) i get a 404 error (see second URL ending by "/edit").

**Screenshots**
![bug](https://user-images.githubusercontent.com/80038332/109950570-a76aa200-7caa-11eb-8f4a-528575213739.png)

![bug2](https://user-images.githubusercontent.com/80038332/109951152-55764c00-7cab-11eb-9eae-25bb96752db4.png)

**Comment by iamromeo** [comment]
The bug is that the Activate button is there, not that it doesn't work. :) 
You should not be able ot activate someone else's character

**Comment by iamromeo** [comment]
Logic examined and fixed. This should only appear now to the owner of the character
