### ISSUE TITLE
User interface settings page goes 404 when trying to switch away from Legacy Editor

### ISSUE THREAD

**Issue by polymorphic2346** [worldanvil/worldanvil-bug-tracker#270]
User: polymorphic

Issue: 

- I opened user interface settings: https://www.worldanvil.com/dashboard/user/interface
- I changed to Legacy Editor. _I do not remember if I pressed save at this point._
- I swapped themes
- I pressed save, got a 404
- I used browser "back" button
- Some settings saved, such as the editor type. 
- But now whenever I try to change editor, editor legacy settings, or themes, it will not save and reloads https://www.worldanvil.com/dashboard/user/interface to 404.

- I honestly don't know as I can't get the issue to revert.

Additional Notes
- Whenever I load a functioning page and go to https://www.worldanvil.com/dashboard/user/interface from there, it will load. HOWEVER it has the "your settings have been updated" badge on it.
- I can still change from light to dark themes by using the toggle in the upper right hand corner of the UI. But when I try to change themes from https://www.worldanvil.com/dashboard/user/interface, it will not save.
- I tried logging out, deleting **all** of my browser data, logging back in, and the problem was still there.

Screenshot:
![Pic 1](https://user-images.githubusercontent.com/84359009/118849178-79563080-b89d-11eb-9e58-e9e5d32e1f2e.PNG)
![pic 2](https://user-images.githubusercontent.com/84359009/118849191-7c512100-b89d-11eb-8b52-dbc494da7bad.PNG)

**Comment by Kordishal** [comment]
The save still works, but the page does not work when the Legacy editor settings are removed. After navigating back to it everything is fine again.

**Comment by polymorphic2346** [comment]
Hi friends, just to clarify: after this error, no new settings will apply when using the interface page. 

- After hitting the browser back button and navigating away from the interface settings page, then navigating back, the interface page shows none of my values or new selections (ie, form background is reverted to 000000 ). That is why I thought it wasn't saving—none of the changes are being reflected elsewhere in my account. This is also true for trying to switch editors. I select the new editor, save, get 404, hit back, and finde that the Legacy editor is still loading on my other pages. When I open interface settings again, it says Legacy Editor as though I never changed it. :)
- I can't switch to villains theme, for the same reason. I am limited to the blue and white themes (and those must be switched using the toggle in the upper right hand corner, not the interface page).

I hope that helps. Thanks!

**Comment by Ademal** [comment]
Seeing this as well. I encountered it when testing a claim on the discord that someone was getting a 404 when they tried to switch out of Legacy.

I cannot edit articles while in Legacy as Legacy breaks my articles, so this becomes a blocking issue.

**Comment by Kordishal** [comment]
I, unfortunately, can confirm this now... 

But how does legacy break your articles? Its just a text area...

**Comment by solstislucifer** [comment]
I can't save any setting on the interface page anymore. Even if I save without changing anything, it sends me to the 404 page

**Comment by Ademal** [comment]
> I, unfortunately, can confirm this now...
> 
> But how does legacy break your articles? Its just a text area...

Legacy struggles with the container tag, and will often convert all BBCode in it into HTML, then save it. Last time this happened it was to my critical Introductory article, and took me all day to fix.

Known issue.
