### ISSUE TITLE
Quick article creation on mobile is covered by quick menu bar

### ISSUE THREAD

**Issue by 777-77** [worldanvil/worldanvil-bug-tracker#271]
**World Anvil Username**: Jessej777

**World / Campaign / RPG Character / Manuscript Title**: Heltat 

**Feature**: Quick Ink Well Form

First the good👍
I believe the plus button at the bottom right is great! 
I feel it may have been intended for the users of WorldAnvil,  to be able to create an article "on the fly", fast, and which helps when ideas come up in our minds. 
Which honestly the button has incredible placement on the screen, and feels nice to interact with using. 
I hope this feature stays. 
I also love that I see it on many pages of WorldAnvil, which leaves me to feel i can explore WorldAnvils website and community 
And still write as it flows to my mind. 
So just wanted to start off with the good! Haha 👍

**The problem**
The `Create Article` button in the quick ink well form is sometimes obstructed by the quick menu bar. Which can lead to the loss of content when a missclick happens.

**Steps to Reproduce**:
1. Click Quick Menu Button.
2. Click purple quick ink well for article creation. 
3. Now I fill out the form
4. Sometimes the `Create Article` button is obstructed by the quick menu buttons. And when this is accidentally clicked the form is removed/refreshed and the content cleared.

**Expected behavior**
The create article button should not be obstructed by the quick menu buttons in any case.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Screenshot_20210519-153106_Firefox](https://user-images.githubusercontent.com/84044229/118881469-bc71cd00-b8b8-11eb-942f-000893a9d7ad.jpg)

**Comment by 777-77** [comment]
![Uploading 20210519_160447.jpg…]()

**Comment by iamromeo** [comment]
This is already in the works with the Mobile interface menu update

**Comment by 777-77** [comment]
I'm so very glad to hear it. Yeah, I lost a few articles after they werent saved. But if that got fixed, that bottom right hand corener will be an amazing feature of the site.  I personally really like it, and find it incredibly useful! --Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 5/20/21, 11:50 PM Dimitris Romeo Havlidis ***@***.***> wrote:

   
  This is already in the works with the Mobile interface menu update
