### ISSUE TITLE
Webp transparency in article header

### ISSUE THREAD

**Issue by jerry2478** [worldanvil/worldanvil-bug-tracker#272]
**World Anvil Username**:jerry247

**World / Campaign / RPG Character / Manuscript Title**:world of latter earth

**Feature**: Images

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/the-world-of-latter-earth-jerry247/a/712---akan-lai-location-1

**Describe the Issue**
No transparency for webp in the header

**To Reproduce**
1. Go to https://www.worldanvil.com/w/the-world-of-latter-earth-jerry247/a/712---akan-lai-location-1
2. look at header
3. See error

**Expected behavior**
The image transparency should be respected for webp images.

**Comment by iamromeo** [comment]
This is not a bug, it works as intended - put a feature suggestion for raw headers - Tillerz had something similar.

**Comment by jerry2478** [comment]
> This is not a bug, it works as intended - put a feature suggestion for raw headers - Tillerz had something similar.

Could you explain this a bit more please? I'm not sure I can word a feature well not understanding why this is the way it is. Thanks.
