### ISSUE TITLE
Blocking -- Cannot Leave Legacy Editor

### ISSUE THREAD

**Issue by Ademal** [worldanvil/worldanvil-bug-tracker#275]
**User**: Ademal

**Feature**: Editor

**Describe the Issue**
If you set your editor to Legacy and attempt to change it back, you get a 404. 

This is personally blocking because my BBCode breaks in the Legacy editor and is converted to HTML.

Found while helping @Shikya Karaskage#1337, who reported they were stuck on the Legacy Editor. In recreating it, I got the same issue.

**Comment by Kordishal** [comment]
Duplicate of #270
