### ISSUE TITLE
Inconsistent behaviour

### ISSUE THREAD

**Issue by DMSledge** [worldanvil/worldanvil-bug-tracker#276]
DMSledge reporting problems:

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 
Autosave and basic navigation

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Some areas have autosave, others don't. No sign of edit history.
Some areas back takes you back one step, others it kills the app and forces you to go back to the main page before proceeding.

**To Reproduce**
Seems like "meta" specifically has no autosave and also breaks navigation.

**Expected behavior**
Autosave to be consistent everywhere and navigation to also be consistent.

**Comment by Kordishal** [comment]
This is not something that is just a quick fix. World Anvil is under heavy development and some inconsistency is to be expected as features are upgraded. 

Having auto-save added is more of a feature request than a bug report.

However, can you elaborate on what you mean with:

`Some areas back takes you back one step, others it kills the app and forces you to go back to the main page before proceeding.`? 

I am not sure what you mean by breaking navigation. As in when you click the save button?

**Comment by iamromeo** [comment]
This conversation can be continued but it is not a bug.
