### ISSUE TITLE
Article links found in the ToC are no longer H6's.

### ISSUE THREAD

**Issue by Timespool** [worldanvil/worldanvil-bug-tracker#279]
**World Anvil Username**: Timepool

**World / Campaign / RPG Character / Manuscript Title**: Qet

**Feature**:  Table of contents

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/qet , https://www.worldanvil.com/w/desolate-wastes-of-css-timepool (the latter is the most relevant here)

**Describe the Issue**
Articles listed under table of contents folders are no longer H6s. Uncategorized articles in the ToC are still H6's, and appear as expected— as well as offer an example of how the rest previously appeared. This has impacted several of my themes, including These Are the Voyages.

**To Reproduce**
1. Go to a previously styled ToC.
2. Click on a folder.
3. See error

**Expected behavior**
Article links as H6's, in my particular case, they should be using a different font family than the body text font. I should note that if this was a purposeful change, it makes styling article links in the ToC extremely difficult to do now— if not outright impossible in the case of ToCs with nested categories—  and would like to request a unique class be applied to them in lieu of them being H6's.

**Screenshots**
![image](https://user-images.githubusercontent.com/51835701/119165398-4aad9680-ba12-11eb-8309-17d45255e6f6.png)
![image](https://user-images.githubusercontent.com/51835701/119165430-5305d180-ba12-11eb-83d9-94459e8d3d26.png)
![image](https://user-images.githubusercontent.com/51835701/119165466-5c8f3980-ba12-11eb-941c-a91cdbf5139e.png)
![image](https://user-images.githubusercontent.com/51835701/119165536-6f097300-ba12-11eb-91a7-6480a1ffe65b.png)

**Comment by iamromeo** [comment]
The issue is that the extra articles are still h6 not the other way around :P

**Comment by iamromeo** [comment]
@Kordishal @Timespool h5 removed from uncategorized articles as well 
BUT added css classes on both the LI and the A 
![Screenshot 2021-05-23 at 10 40 53](https://user-images.githubusercontent.com/660175/119252169-5be1d900-bbb3-11eb-9716-cd4b22ab594f.png)
