### ISSUE TITLE
Athena sidebar editor not saving excerpt changes

### ISSUE THREAD

**Issue by Lethann** [worldanvil/worldanvil-bug-tracker#28]
**World Anvil Username:**
Lethann

**Describe the Issue**
In the Athena view I click on an article to get the preview on the right to show for that article. Adding tags and an icon work fine, but any changes in the excerpt box are not saved.  Going into the Design tab and editing it there works fine.

**To Reproduce**

1. go to Articles & Categories (Athena)
2. click on any article
3. use preview on the right of screen to edit the excerpt box
4. click on another article/refresh page/open edited article
5. go back to original article and excerpt is still empty/unchanged.

**Comment by iamromeo** [comment]
Reproduced, found, fixed. 
Thank you for reporting!
