### ISSUE TITLE
Adding New Category Scrambles Category List

### ISSUE THREAD

**Issue by Neverdusk** [worldanvil/worldanvil-bug-tracker#282]
**World Anvil Username**: Neverdusk

**World / Campaign / RPG Character / Manuscript Title**: Ocarina

**Feature**: Article Categories

**Describe the Issue**
Adding a new category and moving it or making it a sub-category to another will randomly scramble the list of categories.

**To Reproduce**
1. Go to Articles & Categories Page
2. Enter category name under "Add a New Category" and click "+" icon.
3. Drag category to a different place.
4. (Optional) Make category a subcategory of a category that already has multiple categories.
5. Refresh page or click "Refresh list" icon.
6. If dragged without making it a subcategory, the entire category list will be scrambled. If made a subcategory, all subcategories under that category will be scrambled.

**Expected behavior**
1. Go to Articles & Categories Page
2. Enter category name under "Add a New Category" and click "+" icon.
3. Drag category to a different place.
4. (Optional) Make category a subcategory of a category that already has multiple categories.
5. Refresh page or click "Refresh list" icon.
6. Category and all other categories and subcategories are in the same order you left them in.

**Comment by Neverdusk** [comment]
To prevent the issue, after adding the new category, it has to be moved from top to bottom of the category list (or neighboring subcategories if made a subcategory) one-by-one, dropping and then picking it up again at each step - and only afterward can it be placed in the correct position without any scrambling / random reordering occuring.

**Comment by Kordishal** [comment]
This has been a known issue for a while but unfortunately does not happen consistently. I cannot reproduce the behaviour with the steps you provided.

Can you attempt to reproduce this in a private window of your browser? This will tell us if the issue is related to an extension or cache if it does not happen. And if it does it is likely a WA issue.

**Comment by iamromeo** [comment]
@Kordishal @Neverdusk that only happens if for some reason the categories or articles  under a category do not have assigned weights.

**Comment by Neverdusk** [comment]
@iamromeo When adding a new category and dragging it to a different position, it forcefully CHANGES the weights of every article beneath it. It sets its own weight to 1000 and the ones below to 990, 980, etc, regardless of what they were before - even if I gave them custom weights.

**Comment by Neverdusk** [comment]
Sorry, every "category" beneath it on the same list.

**Comment by Neverdusk** [comment]
The categories all had assigned weights. Just to make sure, I checked and then manually edited their weights myself (starting from 1000, going down, in the correct order). 

After adding a new category and dragging it up, it scrambled the weights of every category beneath it.
