### ISSUE TITLE
Failed subscription hint should include email

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#283]
**World Anvil Username**: SoulLink
**Feature**: Subscription

When purchasing a subscription fails users are asked to contact the team. This message should include the email `contact@worldanvil.com` as they often come to the Discord instead where we cannot help with these issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/14262536/119218888-d68ef380-bae2-11eb-8704-71ece7057475.png)

**Comment by iamromeo** [comment]
Not something we can do about that - this is an issue with FastSpring that is where this is coming from
