### ISSUE TITLE
I just want a no-system or play by post option please

### ISSUE THREAD

**Issue by Brickosaur** [worldanvil/worldanvil-bug-tracker#284]
**Full Name (RPG SYSTEM)**: Play by post freestyle
**List Name** (Name under which it should be listed on World Anvil): Whatever you think best communicates the idea
**World Anvil Username**: Brickosaur

**Website**:

**Logo Image Link**:

**Logo Usage Terms (URL)**:

**Comment by Kordishal** [comment]
Why not just use Homebrew? It is kind of pointless to have a system that doesn't need statblocks.

**Comment by iamromeo** [comment]
And that everyone would dump statblocks in :0
