### ISSUE TITLE
Alterra LARP System

### ISSUE THREAD

**Issue by jediaelthewise** [worldanvil/worldanvil-bug-tracker#285]
**Full Name (RPG SYSTEM)**: Alterra LARP
**List Name** (Name under which it should be listed on World Anvil): Alterra LARP
**World Anvil Username**: alterralarp

**Website**: www.alterralarp.com

**Logo Image Link**: https://drive.google.com/file/d/1zbwyVMwKqHqbrqbtWczf33FJ980HhNsR/view?usp=sharing

**Logo Usage Terms (URL)**: I didnt see much details as far as what the process is involved for us to work our system into world anvil so please let me know what the best way for us to do this is and/or work with you guys so we can leverage your platform for our game. Thank you!

**Comment by Kordishal** [comment]
Hi! You will want to create statblock templates which then can be shared with all users of the platform. The logo will be used for selecting your system once you have a character sheet submitted for community sharing.

The easiest way to get started with the process is to check on the Discord server. Join [here](https://worldanvil.com/discord). There is the channel #twig-help with a lot of resources and guides on how to do that.

**Comment by iamromeo** [comment]
Alterra LARP added to the list
