### ISSUE TITLE
Repeat insert header increases font size

### ISSUE THREAD

**Issue by tjdavis31398** [worldanvil/worldanvil-bug-tracker#286]
**World Anvil Username**:
tjdavis

**World / Campaign / RPG Character / Manuscript Title**:
Ultor

**Feature**: 
Edit mode for articles.

**Related URLS** (To public & visible pages add screenshots otherwise):
All

**Describe the Issue**
Repeatedly clicking H1, H2, H3, H4 continually increases font size instead of toggling heading font and normal font.

**To Reproduce**
1. Go to any article edit
2. Click on H3 repeatedly, cursor size will increase each time.
3. Resolve issue by going into source view and out again. Appears to reset cursor size.

**Expected behavior**
Expected heading font and regular font to toggle on/off on multiple clicks of H3.

**Comment by Kordishal** [comment]
This is not really a bug, just not implemented. To remove styling you need to delete it.
