### ISSUE TITLE
Broken RSS Feed

### ISSUE THREAD

**Issue by BeanQuee** [worldanvil/worldanvil-bug-tracker#288]
**World Anvil Username:** BeanQuee

**World / Campaign / RPG Character / Manuscript Title:** Infinia

**Feature:** RSS Feed

**Related URLS (To public & visible pages add screenshots otherwise):**
https://www.worldanvil.com/w/infinia-beanquee
https://www.worldanvil.com/w/infinia-beanquee/opendata/rss

**Describe the Issue:** The RSS feed url doesn't work, it shows a page with code and won't set up with a webhook to my discord

**To Reproduce**
1. Click on https://www.worldanvil.com/w/infinia-beanquee/opendata/rss

**Expected behavior**
I wanted to see my RSS feed? I don't know what it's supposed to look like

**Comment by Kordishal** [comment]
That is what RSS is a bunch of code. It only gets interesting once you use it in another platform/service.

https://www.worldanvil.com/w/WorldAnvilCodex/a/rss

This guide explores various ways you can use your RSS Feed.

Your RSS feed is also empty. It will contain information on your articles for which you press the `Notify Followers` button.
