### ISSUE TITLE
Save button does not actually save

### ISSUE THREAD

**Issue by iamthetot** [worldanvil/worldanvil-bug-tracker#290]
**World Anvil Username**: iAmTheTot

**World / Campaign / RPG Character / Manuscript Title**: Aedelor

**Feature**: Article editing

**Related URLS** (To public & visible pages add screenshots otherwise): any Article editing page

**Describe the Issue**
Pressing the save button triggers a "saved" notification and even updates the "last saved" time, but it does not actually save progress.

**To Reproduce**
Create article.
Write content.
Highlight some text and apply BBCode with either a button or hotkey shortcut.
Press "Save"
Preview article and find the BBCode has been been saved.

**Expected behavior**
Pressing "Save" should save your progress.

**Screenshots**
![3oJBNPz](https://user-images.githubusercontent.com/53080404/119382483-4df98a00-bc7f-11eb-8b20-6bf7f2434765.gif)

**Comment by Kordishal** [comment]
This is a known issue and will not be fixed at this time. Just make a single keyboard key press and it will be registered.

**Comment by iamthetot** [comment]
The fact that the "save" button says "saved" but hasn't actually saved is not considered an issue worth fixing...? It strikes me as incredibly important for a platform like this that users can be confident that their work is saved when, you know, you press "save."

**Comment by Kordishal** [comment]
The thing here is that the issue isn't related to the button. It's related to how auto-save is implemented. The button just triggers auto-save and exists merely because some people get anxious when they can't press save. 

And as I said. It does save anything that you type. It just doesn't save if all you do is click with the mouse.

**Comment by iamthetot** [comment]
This is inconsistent with almost all of the rest of the website from a UX perspective. When editing details of a Party, I must press "Save Changes." When configuring world settings, I must press "Save Changes." When I alter a custom template, I must press "Save Changes." My world meta, editing a timeline, map settings, editing a secret, advanced edit an image, etc... all of these have buttons that say "Save Changes" that, when pressed, actually save your changes.
