### ISSUE TITLE
Manuscript Deletion and Formatting

### ISSUE THREAD

**Issue by SerenPedac** [worldanvil/worldanvil-bug-tracker#291]
**World Anvil Username**: A Suffering Elder God

**World / Campaign / RPG Character / Manuscript Title**: Scene Outline (Manuscript Title)

**Feature**: Manuscript deletion, scene and folder deletion within a manuscript, manuscript paragraph formatting

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I have three issues with the manuscript feature. The first two issues may be related? 

The first (issue 1) is that I deleted a manuscript but the deleted manuscript icon still appears alongside my other manuscripts. When I click on it, I get an error message.

The second issue (2) is that, in other manuscripts, I am unable to delete scenes and folders within the manuscript. Yes, I can place them in the trash folder, but I want them gone permanently and unrecoverable. At the moment, this does not seem possible. 

The third issue (3) is one of paragraph formatting within the scene editing part of the manuscript. In word and google docs, there is an "add or remove space after paragraph feature." This feature does not exist for my manuscripts and all my manuscripts add a default space between every paragraph. As gaps between paragraphs generally indicate scene breaks or switches in the POV, I find this quite confusing and irritating. Every time I have to create a new line for dialogue, it looks format-wise like I am changing the scene and it creates awkward space between lines of rapid fire dialogue. Since this manuscript software has made the fancy choice of adding spaces in the first place, I would assume there should also be an option to remove them? "Remove space after paragraph" seems like pretty standard feature of most word processing applications. TL;DR I would assume Manuscript has this feature and it just isn't showing for me, else I would like it to have this feature.

**To Reproduce**
For Issue 1
1. Click on "Delete Manuscript", which appears as a red bar when hovering the curser over the manuscript icon
2. Type in full name of manuscript, _Scene Outline_. 
3. Click "I am entirely sure I want to delete my hard work"
4. Error 404
Now if I:
5. Select "Manuscripts" from the left side bar on my homepage.
6. _Scene Outline_ still exists as an icon on the same page as my undeleted manuscripts.
7. Click on _Scene Outline_
8. Error 404

For Issue 2
1. Open manuscript
2. Expand "Bin" folder
3. Select scene or folder I wish to delete
4. Click on "Move to trash", the red button on the far right side bar
5. Nothing happens (maybe nothing is supposed to happen but I would still like a way of permanently getting rid of random folders and scenes that have no text in them.)

**Expected behavior**
For issue 1: deleted manuscript does not show amongst my in progress and completed manuscripts.
For issue 2: scenes and folders moved to trash can be permanently and unrecoverably deleted. 
For issue 3: I can get rid of that annoying space between every new line. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Plese do not report more than 1 issue per task
1. There is alraedy a bug report about this, please make sure. you go through open issues before reporting @Kordishal can you please merge

2. Works as intended

**Comment by Kordishal** [comment]
Issue 1: Problems with deleting manuscripts seem to exist. So far we have been unable to recreate a manuscript that does fail. This is why the issue can't be fixed currently as it is not a general issue. Most manuscripts delete fine. 

Issue 2: This is working as intended. Not sure if this functionality is planned (maybe Dimitris can comment on it). Otherwise, you'll have to make a feature request.

Issue 3: Issue three is a feature request and in the manuscript editor possible via the editor settings.

**Comment by Kordishal** [comment]
duplicate of #206

**Comment by SerenPedac** [comment]
> Issue 1: Problems with deleting manuscripts seem to exist. So far we have been unable to recreate a manuscript that does fail. This is why the issue can't be fixed currently as it is not a general issue. Most manuscripts delete fine.
> 
> Issue 2: This is working as intended. Not sure if this functionality is planned (maybe Dimitris can comment on it). Otherwise, you'll have to make a feature request.
> 
> Issue 3: Issue three is a feature request and in the manuscript editor possible via the editor settings.

Thanks! Sorry if this was a duplicate on an existing issue. I'm really new to all this and trying to figure out how things work.
