### ISSUE TITLE
Variables not showing up correctly in tooltips

### ISSUE THREAD

**Issue by theavandiepen** [worldanvil/worldanvil-bug-tracker#292]
**World Anvil Username**: theavandiepen

**World / Campaign / RPG Character / Manuscript Title**: Spirits & Nanotech

**Feature**: Variables and Tooltips

**Related URLS** (To public & visible pages add screenshots otherwise): (see screenshots below)

**Describe the Issue**
When the tooltip shows up, a bunch of ugly html renders around said tooltip. This happens with simple, advanced, and rendered text variables.

If the variable has any bbcode in it (for example, to italicize a word), it breaks the tooltip even further, with the first part of the html showing up in the tooltip and the variable itself showing up in the article.

**To Reproduce**
1. In an article, put in bbcode to show a variable (ex. [tooltip:[var:terms-da]]da[/tooltip] )
2. View the article
3. Hover over the tooltip text

**Expected behavior**
When I hover over the tooltip text for the tooltip to show up, saying "noun: Essence, seed, origin and nature of a thing's being and action, a thing's like", with no extra html. With the bbcode in the variable, the tooltip text should say "da" and the tooltip itself should say "_noun:_ Essence, seed, origin and nature of a thing's being and action, a thing's like". Aka the way the example tooltips with variables show up in the World Anvil Codex: https://www.worldanvil.com/w/WorldAnvilCodex/a/variables

**Screenshots**
When the variable has no bbcode in it:
![2021-05-24 (2)](https://user-images.githubusercontent.com/84762309/119443220-76689f00-bce6-11eb-96ff-9d7de327f28e.png)

When the variable has bbcode in it: 
![2021-05-24 (4)](https://user-images.githubusercontent.com/84762309/119444282-31de0300-bce8-11eb-90e6-1f5c4768e279.png)

**Comment by Kordishal** [comment]
Working as intended. Use Advanced Term variables if you wish to use BBCode in a tooltip.
