### ISSUE TITLE
Hard Wired Island

### ISSUE THREAD

**Issue by matt-ramcharan** [worldanvil/worldanvil-bug-tracker#294]
**Full Name (RPG SYSTEM)**: Hard Wired Island
**List Name** (Name under which it should be listed on World Anvil): Hard Wired Island
**World Anvil Username**: ramcharan

**Website**: https://ettin.itch.io/hard-wired-island

**Logo Image Link**: https://img.itch.zone/aW1nLzU4OTkxMTAuanBn/original/7SgmP6.jpg

**Logo Usage Terms (URL)**: https://ettin.itch.io/hard-wired-island

**Comment by Kordishal** [comment]
Hi, thank you for your request! The request will be added to the waiting list. It will be added once a Grandmaster account requests it. 

The reason for this is that only Grandmasters can create statblocks for a system. Without statblocks, a system has no purpose. Use Homebrew in the meantime.
