### ISSUE TITLE
Add DNDestiny RPG system

### ISSUE THREAD

**Issue by ArneSaknussemm89** [worldanvil/worldanvil-bug-tracker#295]
**Full Name (RPG SYSTEM)**: Dungeons & Destiny
**List Name** (Name under which it should be listed on World Anvil): Dungeons & Destiny
**World Anvil Username**:

**Website**: https://dndestinyproject.com/

**Logo Image Link**:https://images.squarespace-cdn.com/content/5b224b7cd274cb79a2da5175/1530754229826-LNXWOOM0PTSSE4X5WZBN/Logo_180623.png?content-type=image%2Fpng

**Logo Usage Terms (URL)**: https://dndestinyproject.com/more

Not sure of the logo usage, but this system is a beautiful blend of 2 of my favorite things so I would love to see it in my favorite world building tool!

**Comment by Kordishal** [comment]
Hi, I will need your World Anvil Username. Only systems which have the support of a Grandmaster user are added.

**Comment by ArneSaknussemm89** [comment]
Sorry! I didn't realize I hadn't added it. Also did not know about the Grandmaster support required.
