### ISSUE TITLE
Apostrophe in Map Marker name prevents saving

### ISSUE THREAD

**Issue by artyrambles** [worldanvil/worldanvil-bug-tracker#296]
**World Anvil Username**: arty

**World / Campaign / RPG Character / Manuscript Title**: The Hummelverse

**Feature**: Map Pins

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/the-hummelverse-arty/map/70f9cbd4-ecd8-495d-b9ab-78b9cf239be0

**Describe the Issue**
When creating a new map pin from the map edit screen, you cannot have an apostrophe in the marker's name. It will not save properly.

**To Reproduce**
1. Go to map's edit page
2. Drag the new marker
3. Fill out the form, giving the title a name with an apostrophe in it
4. Click "Create Marker" button
5. The name will be cut off at the apostrophe and nothing else about the marker will save correctly

**Expected behavior**
When clicking the Create Marker button, the map pin should be saved correctly, even if the title contains an apostrophe. It's possible to add an apostrophe to the title when editing the marker directly from the marker's "Advanced Edit" page.

**Screenshots**
![maperror2](https://user-images.githubusercontent.com/29456646/119700915-16900680-be54-11eb-8537-f6759f3050cd.JPG)
![maperror1](https://user-images.githubusercontent.com/29456646/119700934-1bed5100-be54-11eb-8993-c853f54118bc.JPG)

**Comment by iamromeo** [comment]
This is a known issue - it only applies to pins created via the quick interface. It will probably be fixed with Atlas
I will not be working on this before that.
