### ISSUE TITLE
Adding content to Species Sidebar Bottom slows down site and crashes

### ISSUE THREAD

**Issue by android272** [worldanvil/worldanvil-bug-tracker#297]
**World Anvil Username**: android272

**World**: Thisrea

**Feature**: Species Sidebar Bottom

**Describe the Issue**
Adding content to Species Sidebar Bottom slows down the site and crashes. Sidebar does not even show my content properly if I do get it to save before crash.

**To Reproduce**
1. Go to 'Edit Species page'
2. Click on 'Sections'
3. Scroll down to 'SIDEBAR: CONTENT PANEL BOTTOM'
4. Add '--Hair color(s)::Black, Gray--' to 'SIDEBAR: CONTENT PANEL BOTTOM' along with other data and the site should slow down and crash.

**Expected behavior**
I expect it not to slow down and crash, as well as show my content properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/5912527/119703799-ebda8980-be24-11eb-87cf-a94f81652264.png)

**Comment by Kordishal** [comment]
Hi, this is likely related to a glitch in the editor. Try switching to a different one or to Source Mode to resolve the issue.

Check out [this guide to figure out how to do that.](https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors).

I will close this but you can continue to post here should this not resolve this issue.
