### ISSUE TITLE
Justified text becomes white in deep blue interface theme on historical events in timelines

### ISSUE THREAD

**Issue by Carter2083** [worldanvil/worldanvil-bug-tracker#298]
**Carter2083**:

**Timeline**:

**Timeline preview**: 

**(Used Screenshot)** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
On the Timeline preview, if the text is justified on a historical entry, it appears white. This is problematic if you are using dark mode and have the historical entry as 'Era changing' which makes it's background white. This makes the text unreadable.

**To Reproduce**
1. Go to Timeline preview of a created timeline.
2. Create an 'Era-changing' historical entry
3. Write text in the Historical entry 'Short description / excerpt' and then justify it.
4. Return back to the timeline,
5. See error.

**Expected behavior**
I expect the text to appear black as it does in the above screenshots (when the text is non-justified).

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
Un-highlighted:
![image](https://user-images.githubusercontent.com/63514945/119790273-b472e800-becb-11eb-8e9d-b8398d15313c.png)
Highlighted:
![image](https://user-images.githubusercontent.com/63514945/119790329-c05eaa00-becb-11eb-87bd-bf7de9093757.png)

**Comment by iamromeo** [comment]
Fixed, will deploy later today

**Comment by Carter2083** [comment]
What a legend. Your doing a great service. Thank you so much.

Peace upon you.

Jack
