### ISSUE TITLE
Ilaris

### ISSUE THREAD

**Issue by JoergRue** [worldanvil/worldanvil-bug-tracker#299]
**Full Name (RPG SYSTEM)**: Ilaris
**List Name** (Name under which it should be listed on World Anvil): Ilaris
**World Anvil Username**: Galjan

**Website**: https://ilarisblog.wordpress.com/was-ist-ilaris/

**Logo Image Link**:

**Logo Usage Terms (URL)**:

**Comment by Kordishal** [comment]
Added to the waiting list. Will need a second from a Grandmaster account.
