### ISSUE TITLE
new edit pens showing above the css edit window

### ISSUE THREAD

**Issue by Tillerz** [worldanvil/worldanvil-bug-tracker#3]
Tillerz:

**Article / Sidebar**:

**Edit pen icons**: 

**Related URLS** (add URLs of the pages that do not work!):
https://www.worldanvil.com/world/location/d4ca7e6d-f36f-45d4-88d2-66b20f0d6178/edit

**Describe the bug**
Several components are not behaving and showing ontop of the world owner tools like the CSS edit window. The recently introduced edit pen icons do so.

**To Reproduce**
1. Create Article with map in sidebar
2. Save and view the article
3. Open the CSS Editor so that it overlaps the sidebar map

**Expected behavior**
All hovering elements should be ALWAYS ABOVE all content: usability icon, Edit World button at the bottom left, Create buttons at the bottom right, CSS editor window, top bars.

**Screenshots**

![f17f06d235ac04cc5cd34ac29cd93900](https://user-images.githubusercontent.com/63370525/109385362-7fb6bb00-78f3-11eb-85f8-e9796795fc51.jpg)

PS: those pen icons are just one example, there are some other overlapping things with embedded maps and the css editor.

**Comment by iamromeo** [comment]
@Tillerz the CSS that renders this sidebar is not the basic CSS, this looks like custom made CSS, which theme are you using as a base, just so I can test the theme specifically

**Comment by Tillerz** [comment]
Theme is Elven Forest. Apparently the CSS is always very narrow, that's why it doesn't overlap the maps in the sidebar by default. I made it wider, that's why the problem got apparent, so the default user won't have a problem.

The CSS window now works like this for me, after some fiddling with the z-index. Not sure if any of that css code is maybe useful:

- the css palette window is all neutral colors
- the palette doesn't move when scrolling the content
- it's wider and has a larger edit window than the default

I am not sure if the @media block at the top is actually needed.

```/*Editor Specific*/
@media (min-width: 768px) {
    .col-sm-2   {  width: 32%;}
    .col-sm-10 {  width: 68%;}
}

#css-palette-panel {
    position: fixed !important;
    width: 32% !important;
    top: 0px !important;
    background: lightgrey;
    z-index: 10000;
}

#css-palette-panel .form-group {
    margin-bottom: 5px;
    background: lightgrey;
    border-radius: 3px;
    padding: 5px;
}

#css-palette-panel textarea.form-control { height: 0; }
#css-palette-panel textarea { min-height: 55vh !important; }
#hidden-sidebar, .hidden-xs { background: transparent; }

.hidden-xs .fa-palette {
    background: white;
    border-radius: 5px;
    padding: 3px;
    top: 200px !important;
    border: 2px solid;
    margin-left: -9px;
    border-left: white;
    border-style: outset;
    position: fixed !important;
    left: unset !important;
    z-index: 10001;
}```

Looks like this: 
![4324b9ff21a6f8f62fe71eb2301d43be](https://user-images.githubusercontent.com/63370525/109391144-efd63880-7915-11eb-97a2-f53c17368003.jpg)

**Comment by iamromeo** [comment]
Completely new and improved Styling sidebar in place. 
- Fixed on position
- Mobile friendly
- Dark, because, dark things are apparently cooler! 

https://user-images.githubusercontent.com/660175/109409937-666b4880-799f-11eb-924c-5d135d21ab16.mov
