### ISSUE TITLE
Article edit Chrome spell check changing text color

### ISSUE THREAD

**Issue by jonwessels** [worldanvil/worldanvil-bug-tracker#300]
**World Anvil Username**: Xoorauch

**World / Campaign / RPG Character / Manuscript Title**: The Celestial Heart: Empire of Maar

**Feature**: Article edit

**Related URLS** (To public & visible pages add screenshots otherwise): https://streamable.com/jg7e4t

**Describe the Issue**
Using Google Chrome browser, incorrectly spelled words are underlined in red. Upon right clicking the word and selecting a suggestion for spelling, the entire paragraph gets converted to red text, except for the corrected word. Pushing Ctrl + Z will undo this perfectly though. If looking at the source view, you can see that the color tags are added in.

**To Reproduce**
Reproduction has been difficult, as the issue seems to be completely fixed once I manually remove the newly added [color] tags.

**Expected behavior**
Text changed to corrected text, without affecting paragraph formatting.

**Screenshots**
https://streamable.com/jg7e4t

**Comment by Kordishal** [comment]
Hi, thank you for your report. This is a known issue of the editor (Plato). This editor will be rebuilt from scratch in the future.

You could switch editors, check [this guide](https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors) to see how.
