### ISSUE TITLE
Viewing the world leads to Error 404

### ISSUE THREAD

**Issue by EnaShosuro** [worldanvil/worldanvil-bug-tracker#301]
**World Anvil Username**: RibenLARP

**World / Campaign / RPG Character / Manuscript Title**:Riben

**Feature**: -

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/riben-ribenlarp

**Describe the Issue**
Since yesterday I can't reach the public page of my world. Neither through "view world" nor from a differnet browser using the above posted link nor when viewing the manuscript and than following the "visit Riben" button. The manuscripts are reachable as well as public content within my world. The world is set on public, I tried Chrome and Firefox, deleated cookies and tried again, but the issue still occurs. Even after rebooting and trying it from different devices. I also tried making the world private and than public again, still no change.

**To Reproduce**
A:
1. Go to https://www.worldanvil.com/w/riben-ribenlarp
2. See error 404

B:
1. Go to https://www.worldanvil.com/community/manuscripts/read/0200136388-ribenlarp-riben-no-zappo
2. Click at "visit Riben"
3. See error 404

**Expected behavior**
Following the link and also following the "visit Riben" buttons should show the worlds pages.

**Screenshots**
![Screenshot 2021-05-28 171126](https://user-images.githubusercontent.com/33224386/120005249-f7ba7d00-bfd7-11eb-828f-5dd386b3c014.jpg)
![Screenshot 2021-05-28 171218](https://user-images.githubusercontent.com/33224386/120005253-f8531380-bfd7-11eb-93a4-45423db9ebcb.jpg)
![Screenshot 2021-05-28 171253](https://user-images.githubusercontent.com/33224386/120005261-f9844080-bfd7-11eb-8a90-247031bd8023.jpg)

**Comment by Kordishal** [comment]
Hi, the most likely cause is some bad content on your homepage. I assume you can still edit the world configuration? Try removing bits of it until the homepage is back.

**Comment by EnaShosuro** [comment]
It actually did help. Sorry for opening a bug for this.
