### ISSUE TITLE
Agonia Ponura Gra Fabularna

### ISSUE THREAD

**Issue by Nyanthotep** [worldanvil/worldanvil-bug-tracker#302]
**Full Name (RPG SYSTEM)**: Agonia: Ponura Gra Fabularna
**List Name** (Name under which it should be listed on World Anvil): Agonia: Ponura Gra Fabularna
**World Anvil Username**: Nyanthotep

**Website**: https://hengal.pl/agonia-3-edycja/

**Logo Image Link**: https://sklep.hengal.pl/174-large_default/agonia-3-edcyja-wspieramto.jpg

**Logo Usage Terms (URL)**: The artwork is owned by Henegal, but I have no idea what the terms of use are.

**Comment by iamromeo** [comment]
The user is not capable of adding a system to the list at this time. In order to add a system to the list you need to have a Grandmaster membership or above.
