### ISSUE TITLE
Character Bio completely overwritten

### ISSUE THREAD

**Issue by SirOllowain** [worldanvil/worldanvil-bug-tracker#303]
**World Anvil Username**: SirOllowain

**RPG Character**: Senwyn Falah / Paran Mekhar

**Feature**: Heroes Character Profile 

**Describe the Issue**
The complete information in the hero profile of the character "Senwyn Falah" has been overwritten by an older hero character ("Paran Mekhar"). 
All information in the newer character's profile was deleted and overwritten except the name and profile picture.

**To Reproduce**
1. Older character was in a deleted campaign of the same user (Nameseeker) as the new character.
2. Added new character and new bio information for new campaign.
3. Checked in after a couple of days and saw all info has been exactly copied from older to newer character without user intervention.

**Expected behavior**
To retain the separate information in both hero profiles, regardless of campaign.

**Screenshots**
![character_old](https://user-images.githubusercontent.com/85078820/120117868-ace36580-c18f-11eb-8df5-a55d3396ce37.PNG)
![character_new](https://user-images.githubusercontent.com/85078820/120117874-b4a30a00-c18f-11eb-82ef-6d1255dc8f2d.PNG)

**Comment by iamromeo** [comment]
User most probably opened multiple windows activating another character before saving another. This is not a bug, and it is clearly discouraged.
