### ISSUE TITLE
Lost an entire article

### ISSUE THREAD

**Issue by TrentTroop** [worldanvil/worldanvil-bug-tracker#304]
Article written 5/25, seems to have fully been eaten by the autosave. Found missing on the following Friday.

Original article was at: 
https://www.worldanvil.com/w/after-the-fall3A-children-of-an-obsolete-apocalypse-toyeticmechanic/a/canoid-2F-dog-species

**Comment by Kordishal** [comment]
Sorry that you lost your content! However, the auto-save does not generally *eat* articles. The most likely scenario is that you had the article editor of this article open in two tabs. Then one editor view went stale and then you saved the old version over the new one. Make sure to always only open up each editor in a single tab / device!
