### ISSUE TITLE
Chronicles of A Broken Path

### ISSUE THREAD

**Issue by Mino1984** [worldanvil/worldanvil-bug-tracker#306]
**Chronicles of A Broken Path (RPG SYSTEM)**:
**Chronicles of A Broken Path** (Name under which it should be listed on World Anvil):
**Chronicles of A Broken Path**:

**https://ballisticblade.com/ballistic-blade-entertainment/projects/*:

**Logo Image Link**:

**Logo Usage Terms (URL)**:

**Comment by iamromeo** [comment]
Please read through the instructions
For a system to be added to World Anvil the user submitting needs to have an active Grandmaster subscription.
