### ISSUE TITLE
Firefox does not allow to click and place the cursor in certain sections

### ISSUE THREAD

**Issue by MGatta** [worldanvil/worldanvil-bug-tracker#307]
**World Anvil Username**: MGatta

**Feature**: Image gallery & Athena sidebar

**Describe the Issue**
While changing details in the image gallery, you are unable (in Firefox) to place your cursor where you click. You must use your arrow keys to get where you want within the fields of text.

**To Reproduce**
1. Open WA in Firefox
2. Open an image in the image gallery
3. Click somewhere in the name (preferably, not the beginning)
4. See error (your cursor is not placed where you dropped it)

**Expected behavior**
For the cursor to be placed where I put it.

SoulLink has replicated the issue, as well as found this [Mozilla known issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1020973).

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/80196715/120544881-34c6ab00-c3ee-11eb-997b-7f671cd04dc4.png)

**Comment by MGatta** [comment]
According to Spartango it's because the input field has user-select: none; in its CSS

**Comment by iamromeo** [comment]
Will not pursue browser specific issues - the user-select: none; was removed from the field css but this is an extremely common CSS rule used across bootstrap.
