### ISSUE TITLE
Secrets by editor not visible by World Owner

### ISSUE THREAD

**Issue by graylion-wa** [worldanvil/worldanvil-bug-tracker#311]
**World Anvil Username**:
Graylion

**World / Campaign / RPG Character / Manuscript Title**:

Creation 

**Feature**: 

Secrets

**Describe the Issue**

A Secret created and pasted inline by editor does not display in the article and cannot be edited by the owner of the world. In addition I could not edit the secret. I was able to delete it.

**To Reproduce**

An editor in my world (Creation) was editing an article he is assigned as the Author on . He pasted the secret into an article section.

**Expected behavior**

A secret added by an editor be visible in the article and editable by the world owner.

**Comment by graylion-wa** [comment]
Here is another article as an example ...

Here is an image showing the presentation view from the editors access, including the two secrets.
* Emerald Moss
* Warehouse sewer access

![Editors   Secrets 001](https://user-images.githubusercontent.com/79761754/120909286-a0548680-c641-11eb-8e27-686bef6fe184.jpg)

This image shows the same article from my access as the world owner, where the secrets are not visible.

![Editors   Secrets 002](https://user-images.githubusercontent.com/79761754/120909292-b7937400-c641-11eb-9b61-04341ea59ea7.jpg)

This image shows the edit side of the article with the inline secrets ...
* [secret:257eeb28-99cd-4c2f-b227-97cffde48e8b] 
* [secret:732027d4-a1a6-4698-bd70-44e2706dd7fb]

![Editors   Secrets 003](https://user-images.githubusercontent.com/79761754/120909325-ff1a0000-c641-11eb-8182-960b15f118f3.jpg)

Article link
[https://www.worldanvil.com/w/creation/a/torbrin-dock-warehouse-landmark](url)

**Comment by Kordishal** [comment]
This is not a bug. There is a setting on purpose. So people can share their worlds and keep secrets from each other. The setting is under World Configuration > Display > Global Options > Open Secrets.
