### ISSUE TITLE
The privacy state in the quick edit form on dashboard always defaults to private

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#315]
**World Anvil Username**:
**Feature**: Quick Edit Dashboard

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
The quick edit form privacy status dropdown is always on private regardless of article state. This means that public articles are switched to private when saved without changing it back.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

![image](https://user-images.githubusercontent.com/14262536/121080322-94043100-c7db-11eb-8cd2-94514f1d9694.png)

**Comment by Kordishal** [comment]
https://www.worldanvil.com/community/voting/suggestion/a82da243-3c81-425f-a4ef-1efa6d265f0e/view

**Comment by iamromeo** [comment]
that, that was a typo 🤦  - Fixed
