### ISSUE TITLE
Copyright Lock on the World Name Hildring

### ISSUE THREAD

**Issue by Britt-of-Arc** [worldanvil/worldanvil-bug-tracker#316]
Hello, I am receiving a 404 error "Thus you have reached the end of this world" when I try to create my first world. 

Please advise.

**Comment by Kordishal** [comment]
Hi,

Please attempt to create a world just with a simple title (such as title or test). You can change these things afterwards.

This is not a general issue so I will be closing this ticket, but feel free to answer here should this not work.

**Comment by Britt-of-Arc** [comment]
Thank you Jonas.

Test works as a world name, but it still gives me the 404 error when I try
to change it back to its original name.

Is the only workaround to create another world?

**Comment by Kordishal** [comment]
What is the name you want it to change to? It likely contains an illegal character.

**Comment by Britt-of-Arc** [comment]
Hildring. For some reason it doesn't like it - possibly because I deleted a
basic tier account with the same world name just prior to creating this one?

**Comment by Kordishal** [comment]
Ah yes, of course. That is the copyright lock. Post your World Anvil username and and the username of the other account. So Dimitris can have a look.

**Comment by Britt-of-Arc** [comment]
Thanks Jonas.

Username of old account was: Doyen Cymancer
Username of current account is: Britt of Arc

**Comment by iamromeo** [comment]
This should be now fixed. but when searched I did found two worlds called Hildring so - I am not sure if something changed in between. 
Also the problem should not have been present if the two accounts had different usernames to begin with
