### ISSUE TITLE
Comments & RPG Heroes Stream posts with unclosed bbcode tags leak the tag formatting

### ISSUE THREAD

**Issue by Hanhula** [worldanvil/worldanvil-bug-tracker#318]
**World Anvil Username**: Hanhula

**World / Campaign / RPG Character / Manuscript Title**: N/A

**Feature**: Comments & Heroes Stream Posts

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/hero/log/post/73d6f4d3-5a60-4101-b3cb-ef1fea3e4a8a 

**Describe the Issue**
Typing a comment on an article, or on the RPG Heroes Stream, and not correctly closing the BBCode tags used impacts the entire page until someone comments with the correct closing tag.

**To Reproduce**
1. Write a comment or Heroes post with a tag like [b] or [i]
2. Do not close the tag.
3. Post the comment.

**Expected behavior**
Comment posts, tag is either posted with it (displays visually) or 

**Screenshots**
![](https://i.imgur.com/zr905RL.png)

**Comment by iamromeo** [comment]
Sadly that cannot be fixed - with great power comes great...responsibility?
