### ISSUE TITLE
new article category

### ISSUE THREAD

**Issue by ivan-BRHM** [worldanvil/worldanvil-bug-tracker#319]
**World Anvil Username**:ivanheo jr.

**World / Campaign / RPG Character / Manuscript Title**:Elsol

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is:
when i click to create a new article, of the land category, on the dashboard, it creates the article as the organisation category instead.

**To Reproduce**
1. Go to '...'dashboard
2. Click on '....'country
3. Scroll down to '....'--

**Expected behavior**
A clear and concise description of what you expected to happen:
i would expect it to create a 'land' article, but it creates a 'organisation' article instead.

![Skærmbillede (9)](https://user-images.githubusercontent.com/83637011/121411446-ed976780-c963-11eb-8f3b-2f1da2611093.png)
![Skærmbillede (10)](https://user-images.githubusercontent.com/83637011/121411469-f5efa280-c963-11eb-9ce0-aff9b7aab656.png)

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
This works as intended. There is no country template it's just a redirect to the organization template. That template contains all the prompts for countries in the Geo political tab.
