### ISSUE TITLE
"AbortSpellChek" appeares at the bottom of all the text boxes that I edit.

### ISSUE THREAD

**Issue by Nanika1** [worldanvil/worldanvil-bug-tracker#32]
**World Anvil Username**: Nanika1

**World / Campaign / RPG Character / Manuscript Title**: Yggdrasil

**Feature**: Article "Módi Thorson Thundershield"

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When I edit, or accidentaly enter, a text box "AbortSpellChek" appeares at the bottom quite a few lines down. There appeares two of them, separated by a few lines.
If I edit a text box with the "AbortSpellChek" in it, it happens again. Witch means it stacks.

I tried to find out if the problem is on my part. I turned of all spell checking programs that I know of that might have caused the issue. But it did not have an effect on the issue.

**To Reproduce**
I have not bean able to discern how to reproduce the behavior.

**Expected behavior**
"AbortSpellChek" appeares at the bottom of all text boxes that is edited.

**Screenshots**
![image](https://user-images.githubusercontent.com/80038416/110093444-03145880-7d9b-11eb-8271-920c450a48a6.png)

**Comment by Kordishal** [comment]
Hi. This is certainly an unusual issue. Have you tried using a different browser and see if the issue appears there?

**Comment by Nanika1** [comment]
> Hi. This is certainly an unusual issue. Have you tried using a different browser and see if the issue appears there? This isn't something caused by World Anvil.

It is not an issue on Microsoft Edge. Maby my Google Chrome is just broken. Thank you for helping me.

**Comment by Kordishal** [comment]
Then it probably caused by an extension you didn't turn off and might not expect to do this.
