### ISSUE TITLE
Cannot Change Article Authors

### ISSUE THREAD

**Issue by ethawyn** [worldanvil/worldanvil-bug-tracker#321]
**World Anvil Username**: Ethawyn

**World / Campaign / RPG Character / Manuscript Title**: The Great Pendragon Campaign

**Feature**: Advanced Author

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/the-great-pendragon-campaign-ethawyn/a/felix-person

**Describe the Issue**
I have added one of my players as an advanced author on my world. I go to the article I want her to be able to edit and select "special actions" and go to "select new author." I select her and click "change author." World Anvil says "You have successfully changed the author of this article!" However, I still show as author and when my player tries to edit the article is says she does not have permission. 

**To Reproduce**
1. Go to any article (I discovered it with a character article).
2. Click on 'Open Advanced tools & Options'
3. Scroll down to 'Special Actions' accordion and open it up. 
4. Use the 'select new author' dropdown to select a new author. 
5. Select a different author. I was trying to select 'kmsteinke.' 
6. Click 'Change Author.' 
7. World Anvil will say that the author has changed. It has not. 

**Expected behavior**
I should be able to change the author so that my advanced author can edit the article.

**Comment by Kordishal** [comment]
Does this happen with all the authors in your world or just the one?

**Comment by ethawyn** [comment]
All that I have tested, yes.

**Comment by Kordishal** [comment]
For me kmsteinke is the author of the article when I look at the article that you linked. Are they actually an advanced writer? And not just a writer? Because writers cannot edit published articles.

**Comment by ethawyn** [comment]
It appears to be working now. Not sure what the problem was yesterday, she
was definitely already an advanced author.
