### ISSUE TITLE
'report.html.twig' file does not work with a custom URL for Campaign

### ISSUE THREAD

**Issue by katili** [worldanvil/worldanvil-bug-tracker#322]
**World Anvil Username:** katieplays

**World / Campaign / RPG Character / Manuscript Title:** Verona

**Feature:** Article Template

**Related URLS (To public & visible pages add screenshots otherwise):**

**Describe the Issue**
When using the 'report.html.twig' file in the template downloads as a base for a custom Session Report template, the portion of code that should link to the campaign page doesn't work with custom URLs. It links to what is presumably the default URL (with a long random string) which generates a 404 page. 

**To Reproduce**

1. Create an article template with the Report parent. Apply to a session report on a campaign with a custom URL.
2. View the report; the link to the campaign works normally.
3. Copy and paste all the code from the downloaded 'report.html.twig' to the Advanced HTML structure box and save
4. View the report gain; the link to the campaign now leads to a 404 page

**Expected behavior**
I expect everything the link to point to the correct place

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by katili** [comment]
Upon further investigation this also seems to happen with the Player Journal links, I can log a new issue for that if needed but didn't want to flood the requests.

**Comment by Kordishal** [comment]
This is potentially related to #320 as it could be caused by an outdated template as well.

**Comment by iamromeo** [comment]
- Upgraded report.html.twig to the 2021 template version (massive rehaul) 
- Added changelog.md to zip file
- Updated link to the download
