### ISSUE TITLE
Freemen are unable to change global world header/cover

### ISSUE THREAD

**Issue by SomewhereOutInSpace** [worldanvil/worldanvil-bug-tracker#323]
**World Anvil Username**: SomewhereOutInSpace

**World / Campaign / RPG Character / Manuscript Title**: Permanence

**Feature**: World/global header

**Related URLS** (To public & visible pages add screenshots otherwise): N/A

**Describe the Issue**

According to the helpful folks on Discord, the fact that I can't change my world's global cover/header image from the Settings > Styling page is probably not intentional. Screenshot below.

![image](https://user-images.githubusercontent.com/29698690/121448248-3996dc00-c965-11eb-9c4b-6203ea1cc759.png)

**To Reproduce**
1. Open World Settings > Styling on a Freeman account.
2. The option to change the world cover image is not visible. (Verified on my account and on the test account of an Anvil Assistant.)

**Expected behavior**
The world cover image selector should be visible.

**Comment by iamromeo** [comment]
I do not see that changing and freemen will not be getting access to styling. 
What we might implement is a hard reset to remove global headers but this might hurt people that remove their membership temporarily
