### ISSUE TITLE
Theme Deadhouse Sonata Issue

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#327]
**World Anvil Username**: SoulLink

**Feature**: Deadhouse Sonata Theme

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/WBtV/a/adirondack-mountains

**Describe the Issue**
The new description collapsible element has a white background with white text.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/14262536/121512913-8a044d00-c9ea-11eb-8cb2-7030a2b74559.png)

**Comment by melior64** [comment]
> .user-css .well {
  background: transparent;
  border: none;
}

**Comment by iamromeo** [comment]
Thank you so much @melior64 - will release asap.
