### ISSUE TITLE
Custom CSS container with a link inside causes issues when saving

### ISSUE THREAD

**Issue by rznwang** [worldanvil/worldanvil-bug-tracker#328]
**World Anvil Username**:TrekEenBak

**World / Campaign / RPG Character / Manuscript Title**: Aragani

**Feature**: Custom container class

**Related URLS**: https://www.worldanvil.com/w/aragani-trekeenbak

**Describe the Issue**
Whenever I save the world settings while an already existing container with a custom css class containing a link is present in any of the text boxes. The content of the container will go nuts trying to insert its own code into itself.

**To Reproduce**
1. Go to world settings
2. Create a container e.g. `[container:class1][url:https://worldanvil.com]https://worldanvil.com[/url]‌[/container]`
3. Save world settings
4. Edit something else in the world settings and save again
5. Container content will now change from 
`[url:https://worldanvil.com]https://worldanvil.com[/url]‌` 
to
`<span data-wa-base-url="1" contenteditable="false" data-wa-url-link="https://worldanvil.com"><span class="tag" style="display: inline;"></span><span contenteditable="true" data-wa-url-display="">https://worldanvil.com</span><span contenteditable="false" class="tag" style="display: inline;"></span></span><span></span>`

The container will also change from 
`[container:class1][url:https://worldanvil.com]https://worldanvil.com[/url]‌[/container]`
to
`[container:class1]https://worldanvil.com" >[url:https://worldanvil.com]https://worldanvil.com[/url]‌[/container]‌`

**Expected behavior**
The expected behaviour is that the link will remain untouched and not be replaced by a bunch of HTML tags.

**Screenshots**
1+2:
![image](https://user-images.githubusercontent.com/74993152/121610189-be612300-ca55-11eb-9f2d-a00209dc9e6a.png)

3:
![image](https://user-images.githubusercontent.com/74993152/121610220-cd47d580-ca55-11eb-93b9-4e2f035c1579.png)

4:
![image](https://user-images.githubusercontent.com/74993152/121610240-dafd5b00-ca55-11eb-9bee-12af1d50b957.png)

5:
![image](https://user-images.githubusercontent.com/74993152/121610266-e5b7f000-ca55-11eb-855d-496287dac6d8.png)
![image](https://user-images.githubusercontent.com/74993152/121610278-ebadd100-ca55-11eb-9387-e232d4d0eb0e.png)

**Comment by iamromeo** [comment]
containers and any other advanced BBcode cannot be used in the simple / WYSIWYG editor. If you wish to use advanced formatting you will need to upgrade to Euclid you can do this from the Interface Settings on the top right 
https://www.worldanvil.com/dashboard/user/interface

**Comment by Kordishal** [comment]
Some more background information on the editors: https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors

**Comment by rznwang** [comment]
Oh, I completely missed this setting. Thank you!
