### ISSUE TITLE
Editor/Viewer Button Not Working

### ISSUE THREAD

**Issue by Theiket** [worldanvil/worldanvil-bug-tracker#330]
**World Anvil Username**: Theiket

**Chronicle Title**: The Timeline of Everything

**Chronos System**

**Describe the Issue**
The Editor/Viewer button doesn't switch after refreshing from the blank chronicle screen to let the timeline ruler appear. 

**To Reproduce**
1. Make a new Chronicle
2. Ensure all steps were taken to make a new Chronicle
3. When timeline ruler doesn't show, refresh.
4. Press green Editor button to try to switch to Viewer
5. Witness not working

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Xuroth** [comment]
This is related to Navigation and Plus Buttons also not triggering. Due to a CSS issue. Will be fixed in next update

**Comment by Xuroth** [comment]
Resolved
