### ISSUE TITLE
RPG Awesome Icons do not display

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#331]
**World Anvil Username**: SoulLink

**Chronicle Title**: The Second Breaking in Breaking Anvil

**Chronos System** Events

**Describe the Issue**
A clear and concise description of what the issue is.
When selecting an icon from RPG Awesome it does recognize it as such. But then does not display it both in the UI and on the timeline.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Xuroth** [comment]
DOH! Yup. That's correct. I notice this just now!

**Comment by iamromeo** [comment]
This is now fixed
