### ISSUE TITLE
Year field in creating an event displays decade-level only

### ISSUE THREAD

**Issue by Hanhula** [worldanvil/worldanvil-bug-tracker#333]
**World Anvil Username**:
Hanhula

**Chronicle Title**:
testytest

**Chronos System**
Create Event

**Describe the Issue**
Creating an event gives you Start and End date fields. The year-level fields in these do not seem to function correctly: the Start date lists years into a decade (e.g. it's 2021 IRL, so the field would show 1) and does not allow you to go below 0, and End date seems to be stuck on 0.

**To Reproduce**
1. Go to Chronos
2. Right-click and press Create Event
3. Scroll to the Start and End sections
4. Attempt to adjust year column via calendar picker

**Expected behavior**
Year should reflect what is written.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![](https://cdn.discordapp.com/attachments/852195433370615868/852840556828426260/unknown.png)

**Comment by Xuroth** [comment]
Resolved. Due to Granularity issue, caused by CSS invisible window
