### ISSUE TITLE
Map always zooms to top right on open

### ISSUE THREAD

**Issue by The-Toblin** [worldanvil/worldanvil-bug-tracker#338]
**World Anvil Username**:
Toblin
**Chronicle Title**:
Test History
**Chronos System**
?
**Describe the Issue**
When loading a chronicle, the map always zooms to the top right corner of the map.

**To Reproduce**
1. Create a chronicle
2. Add a map
3. Open chronicle
4. Observe zoom to top right

**Expected behavior**
Should zoom to center of map, or there should be a configuration to change zoom origin on load.

**Comment by Xuroth** [comment]
There is an issue where the custom selected coordinates are being overridden by the default setting. I need to run an additional check server-side to ensure the MapImage's data is used instead.

**Comment by Xuroth** [comment]
This should be resolved. However, I did find a separate issue (unrelated) that I must now fix.
