### ISSUE TITLE
Map Marker Polygons Issue with Co-Owners

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#34]
**World Anvil Username**: SoulLink
**Feature**: Co-Owner / Maps

**Describe the Issue**
Co-owners cannot view, edit or create polygon & circle markers on worlds owned by Grandmasters (including when the co-owner is grandmaster themselves).

**Expected behavior**
Be able to view, edit and create polygon and circle map markers.

**Comment by iamromeo** [comment]
This is now scheduled for the next sprint

**Comment by iamromeo** [comment]
@Kordishal  This could not be reproduced. 
After investigation I found the following: 
- The current user's rank is irrelevant
- The OWNER of the world determines access to a feature or not. 

I will need to know the username of the owner in order to confirm but the code does not confirm the above

**Comment by iamromeo** [comment]
Confirmed - if the owner has access to the feature the features are available to the co-authors

**Comment by Kordishal** [comment]
Must have been that they were not master, but still had some inactive polygons.

**Comment by iamromeo** [comment]
Cannot say until I have more information :)
