### ISSUE TITLE
Events are always created in the First Lane

### ISSUE THREAD

**Issue by Satrium** [worldanvil/worldanvil-bug-tracker#344]
**World Anvil Username**: Satrium

**Chronicle Title**: First Test

**Chronos System**

**Describe the Issue**
Browser: Chrome
No matter which Lane I click inside of a timeline, it will create the event inside the first Lane, not the one I clicked on.

**To Reproduce**
1. Right Click on a Lane that's not the first
2. Click on 'Create new Event'
3. Fill out the form and click 'Create event' 
4. See the event appear in the first lane

**Expected behavior**
The event should appear in the clicked lane, not the first one.

**Comment by Xuroth** [comment]
Found the culprit and tested. WIll be part of next update.

**Comment by Xuroth** [comment]
Should be resolved.
