### ISSUE TITLE
Campaign Invites Broken

### ISSUE THREAD

**Issue by bloodiedporcelain** [worldanvil/worldanvil-bug-tracker#356]
**World Anvil Username**: Bloodied Porcelain

**World / Campaign / RPG Character / Manuscript Title**: Campaign: Limitless Legends World: Talav Mor

**Feature**: Campaign Invite Link/Email

**Related URLS** (To public & visible pages add screenshots otherwise): Campaign: https://www.worldanvil.com/epic/mVuLwoPMff4VpCEJBqMu8FDWBe6pvA

current invite link: http://www.worldanvil.com/epic/mVuLwoPMff4VpCEJBqMu8FDWBe6pvA/join/Mdws-NIYT-3UMvsw

**Describe the Issue**
The Campaign Invite Link/Email returning 404 errors. I have tried both providing links (including generating a new link when the first one I had stopped working) and using the email invite system, but neither seems to be working. Both are returning 404 pages. 

**To Reproduce**
1a. Click link provided above 
1b. Click link provided in email invite
3. See 404 page. 

**Expected behavior**
Players should be able to select their character to join the campaign with. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by graylion-wa** [comment]
I also tried to assist this WA user. 

My attempt to join their campaign resulted in a 404.

Attempts to join my campaign resulted in 404.

Thanks

**Comment by iamromeo** [comment]
Fixed
