### ISSUE TITLE
Article cover image not appearing

### ISSUE THREAD

**Issue by RedKerr1000** [worldanvil/worldanvil-bug-tracker#358]
**World Anvil Username**:
RedKerr
**World / Campaign / RPG Character / Manuscript Title**:
Aeris/ Lolth article
**Feature**: 
Article cover image
**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.
Im trying to add a cover image to my article on lolth but no matter what I do the image doesn't appear and the top of the screen gets kinda crushed. I've tried cutting down the image, erasing large parts of my writing but nothings working. I tried making a new article, and gave that one a cover image but the same issue of it not showing up and compressing the top of the screen occurred
**To Reproduce**

**Expected behavior**
I expected to just be able to place the image in
**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by RedKerr1000** [comment]
I've started another article and tried adding a cover image but that didn't work either

**Comment by rznwang** [comment]
I've got the same issue, images uploaded earlier do seem to work. New images seem to cause an issue however.

**Comment by RedKerr1000** [comment]
> I've got the same issue, images uploaded earlier do seem to work. New images seem to cause an issue however.

Glad I'm not the only one

**Comment by iamromeo** [comment]
This is now resolved. the cache got full - we have been experimenting with the time required to clear it and we underestimated a bit :)

**Comment by RedKerr1000** [comment]
> This is now resolved. the cache got full - we have been experimenting with the time required to clear it and we underestimated a bit :)

Thank you very much! no worries!
