### ISSUE TITLE
Images not appearing in Image and Files nor in Articles covers and blocks

### ISSUE THREAD

**Issue by ShadowMalachi** [worldanvil/worldanvil-bug-tracker#359]
**World Anvil Username**: ShadowMalachi

**World / Campaign / RPG Character / Manuscript Title**: Daemonium

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise): Crap  Lighting image of a article not having its article image showing ( Second Screenshot )
![Crabs picture showing article image not appearing](https://user-images.githubusercontent.com/80189593/121763302-de9dea00-cb08-11eb-9d09-1c56bf49abd6.png)

**Describe the Issue**
Images aren't working, nor are article covers (on both the articles and article blocks 

**To Reproduce**
1. Go to Images and files
2. Click on A Image, Any image and look at the side where it should be deplayed. It shows the name of the picture but no actual image
4. In the screenshot, I am hovering over a recent upload of a kings face, It is not showing up in the display section, It is saying the name of the image but no image in the preview/ Display section

**Expected behavior**
Images are not being  properly displayed in the image and file section, Some images do appear but its almost random which ones will not appear and which ones will appear on the screen. Some have said anything before a certain Date works, But for others it does not work either. Some have reported that article the picture is in the picture does not appear, And the cover images does not appear with said picture 

**Screenshots**
![No image](https://user-images.githubusercontent.com/80189593/121763213-27a16e80-cb08-11eb-82dc-8cdba4f4334a.png)

**Comment by iamromeo** [comment]
Do not double report issues, there was an issue raised exactly about this RIGHT before this one. 
https://github.com/worldanvil/worldanvil-bug-tracker/issues/358
