### ISSUE TITLE
Corrupted Marker prevents all layers & pins from loading.

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#36]
**World Anvil Username**: SoulLink
**Feature**: Maps

**Describe the Issue**
When there is an issue in loading a marker it breaks the entire map. Tracking this error down is almost impossible without intimate knowledge of the code and developer codes. The issue on the screenshot below is that mapMarker51ec88 is not defined within the map script at all. This throws a Reference Error.

**Expected behavior**
Catch the reference error (or resolve the underlying issue) and prevent a single marker from disabling the entire layer, group & marker display. This would aid in tracking down localized issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/14262536/110215458-35f94200-7eaa-11eb-8769-84a83db35caa.png)

**Comment by iamromeo** [comment]
Not enough information to action this at this time.
