### ISSUE TITLE
Window size where sidebar cannot be hidden away in WA interface

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#360]
**World Anvil Username**: SoulLink

**Feature**: World Anvil Interface

**Describe the Issue**
In small windows the sidebar is closed by default. In larger windows the sidebar is open by default.

Between this there is a small zone where the sidebar is open but cannot be closed because it is assumed to be closed. 

This is caused by the class `body-small` on the `body` element. This class is removed from the element later than the sidebar becomes open by default. In this case the closing mechanism attempts to open the open sidebar.

![image](https://user-images.githubusercontent.com/14262536/121769760-b98b9480-cb65-11eb-9242-e046cd94aad1.png)

**Comment by iamromeo** [comment]
Will not be addressed - minor chances of happening and the upgrade to BS5 and the new interface down the line will fix this issue
