### ISSUE TITLE
Problem creating a character : the "create a new article and link it" creates the wrong type of article

### ISSUE THREAD

**Issue by Gentle-Max** [worldanvil/worldanvil-bug-tracker#361]
**World Anvil Username**: MW

**World / Campaign / RPG Character / Manuscript Title**: Oramir

**Feature**: Article creation (character)

**Describe the Issue**
When I go to the edit page for my article, which is a character, and I use the "create a new article and link it" feature to add ethnicities that don't have an article yet, the ethnicities can't be selected when I save and refresh the edit page : instead, when I look at the article that was automatically made, it is listed under the 'Condition' article type rather than the 'Ethnicity' type, which prevents me from using it properly. It's the same for Family, which puts the articles in the Ethnicity category instead of the character category.

I don't know if it matters, but I'm using the French translation of World Anvil.

**To Reproduce**
1. Make a character article
2. Edit it
3. Scroll down to the 'Show Template Specific Prompts & Connections'
4. Go to the 'Generic' Tab
5. Scroll down to 'Ethnicity'
6. Click on the 'Create a new article and link it', and input a new ethnicity
7. Save and reload the article
8. If you scroll down again, there should be no ethnicity selected and when you try to find one, it says 'no results found'. If you go to the world's article, it should be tagged under the 'Condition' article type.

**Expected behavior**
Normally, it should just create an Ethnicity article and not a Condition article...

**Screenshots**
First I set up the 'Nordique' Ethnicity...
![Capture1](https://user-images.githubusercontent.com/85789345/121774298-2f055e00-cb82-11eb-9a8e-600517f85921.PNG)

Then, when I save and reload, the 'Nordique' Ethnicity isn't there anymore and I can't use it...
![Capture2](https://user-images.githubusercontent.com/85789345/121774306-404e6a80-cb82-11eb-85fa-29dc1fb8fe74.PNG)

And when I look in my recently edited articles, I see that there is a 'Nordique' article... but it's a Condition...
![Capture3](https://user-images.githubusercontent.com/85789345/121774330-52c8a400-cb82-11eb-9f7b-d471fbdfdee6.PNG)

**Comment by Kordishal** [comment]
Can confirm that the secondary ethnicity `create new article and link it` creates conditions instead of ethnicties.

There is also a weird block below it that doesn't seem necessary?

![image](https://user-images.githubusercontent.com/14262536/121782439-bca87400-cba9-11eb-81cd-af2042ab09ed.png)
