### ISSUE TITLE
Copy pasting external formatting breaks accessibility features of manuscripts

### ISSUE THREAD

**Issue by buckwell0** [worldanvil/worldanvil-bug-tracker#362]
**World Anvil Username**: buckwell

**World / Campaign / RPG Character / Manuscript Title**: "Kayıp Bir Ruha Dair"

**Feature**: Manuscript

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/community/manuscripts/read/7261181100-buckwell-kayC4B1p-bir-ruha-dair

**Describe the Issue**
Issue, when I go to my manuscript as others' view and do zoom in and out, only thing that happens line heights between up and above increases and decreases. Not even a character is changes in that 'size'

**To Reproduce**
1. Go to 'The manuscript I mentioned'
2. Click on 'Table of contents / Başlangıcın Başlangıcı'
3. Do 'Start reading'
4. See error: Click on and see the bug.
![Zooms](https://user-images.githubusercontent.com/84354328/121787555-5b939700-cbcf-11eb-80ad-88301d7e1523.png)

**Expected behavior**
I expect the words size becomes bigger or smaller. But it just affects the line height between lines.

Thank you so much!

**Comment by iamromeo** [comment]
This caused by the user pasting pre-formatted text from word or another system that forces detault styling. WA cannot change the code of the mess that Word  / 365 / Open Office creates on the actual text

**Comment by buckwell0** [comment]
I didn't copy paste. I just go change the text's font in the app. No other sources used.

**Comment by buckwell0** [comment]
> 
> 
> I didn't copy paste. I just go change the text's font in the app. No other sources used.

If you don't believe, please give it a try.

- go manuscript
- create text page
- start writing and select the text to reform the font and size. 
- and publish it.

**Comment by iamromeo** [comment]
https://user-images.githubusercontent.com/660175/122243591-eaa0f780-cecc-11eb-8d4d-b51b4e12a250.mov
