### ISSUE TITLE
Article, Sidebar Section

### ISSUE THREAD

**Issue by buckwell0** [worldanvil/worldanvil-bug-tracker#363]
**World Anvil Username**:buckwell

**World / Campaign / RPG Character / Manuscript Title**:Her Şeyin Sonu

**Feature**: Articles

**Related URLS** :
Here's what I see. Empty sidebar sections.

![Bug-Sidebar](https://user-images.githubusercontent.com/84354328/121791312-51829000-cbf1-11eb-9cd1-aaf91c151bd1.png)

**Describe the Issue**
I created a 'Prose' article and when I go to edit it and click on sidebar sections, there's nothing but empty space.

**To Reproduce**
1. Go to the creating Prose article
2. Click on Edit
3. Scroll down to  Sidebar Sections
4. See error.

**Expected behavior**
I was expecting there's a sidebar section :D What I can I say.

**Screenshots** I attached above.

Thank you. Have a great day.

**Comment by Kordishal** [comment]
The sidebar is not present in the prose article on purpose. The prose article is intended to write full body prose.

**Comment by buckwell0** [comment]
Prose doesn't necessarily means that all page is filled with text without sidebar. I think it'd be useful whether allowing it or not is decided by users as in the other things there's selection about displayin it or not shown.

**Comment by buckwell0** [comment]
I got one thing and didn't want to start a new issue about it. The secrets is cannot viewable before we share, I guess this intented too but I just wanted to make sure of it.

**Comment by Kordishal** [comment]
If you wish to use the sidebar, use a different template. This is not gonna change its a design descision.

And yes. Secrets can only be viewed while embedded in an article or attached to an article. They do not have a page of their own.
