### ISSUE TITLE
Bug within "Articles & Categories"

### ISSUE THREAD

**Issue by Derkmeister** [worldanvil/worldanvil-bug-tracker#364]
**Derkmeister**:

**World "[PH] Patris's Adventure"**

**Describe the Issue**
When using the "Add Article" within the Articles & Categories, more lines of "text modifier buttons" for the vignette appear after creating the article, this seems to grow indefinitely. 

**To Reproduce**
1. Go to 'Articles & Categories'
2. Click on 'Add Article and continue making more articles under one category'
3. See error

**Expected behavior**
I don't expect more buttons to appear each time I add an article in this manner

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Screenshot (2)](https://user-images.githubusercontent.com/25417990/121823716-5f92e800-cca7-11eb-963f-1cfc6b06a329.png)
![Screenshot (3)](https://user-images.githubusercontent.com/25417990/121823718-66215f80-cca7-11eb-9d86-9035ddf1df4e.png)
![Screenshot (4)](https://user-images.githubusercontent.com/25417990/121823724-6ae61380-cca7-11eb-896e-6509ff2b6256.png)

**Comment by Kordishal** [comment]
This is a known issue and will not be fixed at this stage. Reloading the page should remove the extras. And it should also not happen all of the time. If it does please try to do this in a private window.

If it does not happen again then it is caused by an extension. Otherwise write here again.
