### ISSUE TITLE
Cannot create new timeline without a subscriber group in private world

### ISSUE THREAD

**Issue by winterbourne** [worldanvil/worldanvil-bug-tracker#365]
**World Anvil Username**: winterbourne

**World / Campaign / RPG Character / Manuscript Title**: Shadowlands

**Feature**: Timeline

Url: htps://www.worldanvil.com/world/timeline/list

Issue:
I am unable to create a new timeline.

I created a timeline a while ago and spent all day working in it today without much issue.

When I tried to create a second timeline for a novel, to use for my own reference, no matter what options I used to create it, every time I clicked Create Timeline, I was directed to a 404 message.

Error messages:
When I was prompted to try again and look at the console by SoulLink on the Discord server, I got these:

![timelineerror](https://user-images.githubusercontent.com/22160903/121882837-e5be2700-ccc5-11eb-8a76-f7ccc5667770.PNG)

I have tried different options -- standard vs master, hidden vs. subscribers, related to existing articles/unrelated to existing articles, etc, and it's the same every time: click Create Timeline, get a 404.

I am running Firefox on Windows 10. The problem occurred in both Private and normal windows.

I also tried with Microsoft Edge and got the same problem.

**Comment by Kordishal** [comment]
Ah one thing I have seen in the past: Do you have an anti-virus software that could interfere? I cannot find a way to reproduce this unfortunately.

**Comment by winterbourne** [comment]
Just Windows Defender.

Same issue in Chrome, btw. I have different extensions for Firefox and Chrome, and Edge is in its default state.

What should I do?

**Comment by Kordishal** [comment]
Does this also happen in other worlds or just in this one? Including a new world?

Otherwise wait until Dimitris has a chance to look at this.

**Comment by winterbourne** [comment]
I can create a new one in one of my other worlds.

**Comment by Kordishal** [comment]
That at least slims down the potential problems. How many timelines do you have?

**Comment by winterbourne** [comment]
In total, two, one for that world and one for a different world.

**Comment by iamromeo** [comment]
We will need much more detailed information in terms of what is being inputted during the creation of the timeline

**Comment by winterbourne** [comment]
I found a pattern! 

Subscriber groups, and using the New Historical Event/New Timeline _pages_ instead of Quick Content Creation.

Before, the timeline info was:

Title: Novel Timeline
Description: Test of novel timeline.
Type: Normal/parallel
Related Calendar: Reckoning of Crow Talon (my customized calendar)
Related article: none
Related category: none
Display in table of contents: no
Access: private
Subscriber group: none

Result: 404.

I had tried various combinations to see if anything made a difference. I would get the same thing if it's a Major (master) timeline, if I filled out the various related fields or left them blank, and if I display it in the TOC or not. Always set to private.

The one thing I never did was give it a subscriber group. 

I left it blank this whole time because I don't _want_ subscribers to be able to see it, it's for my use only, and I didn't want to worry about sloppy permissions housekeeping on my part, so I removed the default sub group. I hadn't had issues with it before.

In that case, if I was on the timeline page, once I assigned a subscriber group, I _was_ able to create a new timeline. I created both standard and master timelines this way.

I removed the subscriber group for the standard timeline as a whole, and made a dummy historical event entry, to see if it there was some error generated and tied to the timeline itself. Nope -- 404 if I tried to make an event with no sub group from the New Event page. Add a sub group, change nothing else, and it works just fine. Same with the second master timeline.

I didn't get this issue _at all_ in two other circumstances, which threw me off:

1. Making wiki articles without sub groups. Got a bunch of those.

2. When adding historical events to a pre-existing master timeline I made a while ago and just never populated until now, BUT I was using the Quick Content Creation tool to do so.

I can make entries without sub groups if I'm using the Quick Content system. It was more efficient, so I used it for my earlier timeline, so I never triggered the conditions for the 404. I left the sub group blank and it went through just fine that way.

So yeah, it seems to be some interaction of no sub groups plus the timeline/historical event pages, and whatever it is the QCC tool seems uninvolved.

Now, sleeeep. Then back to work after.

**Comment by iamromeo** [comment]
I still cannot reproduce this
Creating a timeline in a private world without a subscriber group is possiblle.

**Comment by winterbourne** [comment]
Further _potentially_ relevant information _potentially_ pointing to sub groups.

The private world that I had no problems making a new timeline on, call it Private World B, has no subscriber groups associated with it in World Settings > Access. It throws no 404 if I make an entity without a sub group attached.

- Both these worlds are private.
- Both have additional authors, with one author having access to both Private World B and Shadowlands.
- Private World B has no subscribers and no subscriber groups, just 1 additional author.
- Shadowlands has subscribers and one subscriber group, and 2 additional authors.

The only meaningful access difference that I can see -- because that same 404 comes up when someone doesn't have access privileges to the articles -- is subscribers and subscriber groups. It is the absence of subscriber groups that makes the difference on the 404 error, at least when I trigger it.

I think that's the extent of my insight, though.

**Comment by iamromeo** [comment]
I am sorry but I cannot replicate this and nobody else has reported it to get any other data points. I will need access to your account to try it out. 
Can you please: 
- Send an email to hello@worldanvil.com
With: 
- Your username
- Your password (After you reset it to something temporary but secure)
- The world you are trying to add the timeline to
- The EXACT information you are trying to input when you are trying to create the timeline

**Comment by winterbourne** [comment]
Will do.

**Comment by iamromeo** [comment]
Ok, so, yes it does 404. what you did left out is thet your Subscriber Group "Cool Peeps" is a **default** group that you have been forcing to be removed. 

Since you have set this as your default group the system expects it to be in the list. 

This is not an issue with the timeline but with the group. If you do not wish for that group to be added to ALL private entities you can either
- Remove the default checkbox 
or 
- Create the timeline with the default group and remove it afterwards
