### ISSUE TITLE
Extra characters at bottom of screen

### ISSUE THREAD

**Issue by SwiftWolf113** [worldanvil/worldanvil-bug-tracker#367]
**World Anvil Username**: SwiftWolf

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/dashboard/
https://www.worldanvil.com/world/athena/
and more

**Describe the Issue**
When viewing any of the WA pages, if you scroll all the way to the bottom in the outer scroll, you can see the characters '#}' in the bottom left. I believe this is also creates an unnecessary scroll on some of the shorter pages.
The characters are hidden by the sidebar, but you can still the the dark blue bar across the bottom of the screen.
(This does not affect viewing worlds)

**To Reproduce**
1. Go to the WA homepage
2. Hide the left sidebar
3. Scroll down to the very bottom in all scroll panes
4. See extra characters in the bottom left corner and the bar going across the entire screen.

**Expected behavior**
I believe that this adds additional scroll when it is not needed, for example the dashboard has a page scroll which only scrolls down to reveal this bar.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
I am sorry but I cannot see anything and there is no screenshot

**Comment by Kordishal** [comment]
![image](https://user-images.githubusercontent.com/14262536/122173176-c8ce5300-ce81-11eb-8375-cde520359465.png)
Lower left corner. They only appear when the sidebar is closed.
