### ISSUE TITLE
Viewport issue on World Dashboard on small window size before mobile mode

### ISSUE THREAD

**Issue by SwiftWolf113** [worldanvil/worldanvil-bug-tracker#368]
**World Anvil Username**: SwiftWolf

**Feature**: Editor Dashboard

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When viewing the editor's dashboard, if you size the browser window smaller to the point when the article selector disappears, it becomes impossible to scroll down. 

**To Reproduce**
1. Go to the WA dashboard
2. Put the browser into windowed mode
3. Horizontally scale the window until the article list disappears from the left side of the screen
4. Try and scroll down (for me the default view ends at the 'Title, Session Report, Settlement and Species' quick create buttons and I can't get to the following row.

**Expected behavior**
You should still be able to scroll down to view the entire page.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
considering this this can be solved by simply refreshing the page - it will not be addressed at this point
