### ISSUE TITLE
 Display the title of the article in presentation mode unchecked in freeman account

### ISSUE THREAD

**Issue by Eallixy** [worldanvil/worldanvil-bug-tracker#369]
**World Anvil Username**: Eallixy

**World / Campaign / RPG Character / Manuscript Title**: World building collection

**Feature**:  Display the title of the article in presentation mode checkbox

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/world-building-collection-eallixy/a/phantomforce-prosthetics-technology

**Describe the Issue**
The "Display the title of the article in presentation mode" checkbox in the preferences tab of the article is unchecked while I have a Freeman account, resulting in a missing Title Element on the page. 

**To Reproduce**
1. Go to 'https://www.worldanvil.com/w/world-building-collection-eallixy/a/phantomforce-prosthetics-technology'
2. Observe missing page title
3. Check preferences tab in edit window 
4. See unchecked box for Display the title of the article in presentation mode

**Expected behavior**
Have it so that the "Display the title of the article in presentation mode" is checked again and the title visible.

**Comment by iamromeo** [comment]
Just to confirm you used to be a guild member that left the guild?

**Comment by Eallixy** [comment]
Yes I got a 3 month membership as a gift, but stopped actively using WA before the membership was up, but I don't remember unchecking that box.

**Comment by iamromeo** [comment]
Resave your article later today
