### ISSUE TITLE
Articles and Categories page is spending a long time loading

### ISSUE THREAD

**Issue by Lyraine-Alei** [worldanvil/worldanvil-bug-tracker#37]
https://discord.com/channels/348060277989965844/380013392653451264/817991607059873812

Can replicate on FireFox Mobile, but appears on desktop Firefox as well and Chrome.

The Articles and Categories page doesn't load the articles or categories even after the page itself has loaded up.

Might be tied to Dark/Terror from the Deep Mode? Edit: Nevermind, on person waa using Light Mode

**Comment by skleinjung** [comment]
The article list (and category list, as well) never loads for me as well. I am using Firefox with light mode:

![wa-bug](https://user-images.githubusercontent.com/17599474/110230551-6c998180-7ed7-11eb-92cc-b51751062f49.png)

I am still able to edit articles if I can navigate to the edit screen from elsewhere (such as the recents list).

**Comment by ShadowMalachi** [comment]
![Bug](https://user-images.githubusercontent.com/80189593/110230589-11b85800-7ee0-11eb-94e1-49c6b7512462.png)
Getting this with dark mode as well

**Comment by skleinjung** [comment]
All network requests look normal, except a 403 to fontawesome (which I assume isn't causing this.) Browser console shows the following error, although I have no idea if it is related or not:

```
Uncaught ReferenceError: athena_urls is not defined
    init https://www.worldanvil.com/world/athena/:645
    <anonymous> https://www.worldanvil.com/world/athena/:800
    e https://www.worldanvil.com/js/compiled/global.js?v=01523:1
    t https://www.worldanvil.com/js/compiled/global.js?v=01523:1
    setTimeout handler*l/< https://www.worldanvil.com/js/compiled/global.js?v=01523:1
    c https://www.worldanvil.com/js/compiled/global.js?v=01523:1
    fireWith https://www.worldanvil.com/js/compiled/global.js?v=01523:1
    fire https://www.worldanvil.com/js/compiled/global.js?v=01523:1
    c https://www.worldanvil.com/js/compiled/global.js?v=01523:1
    fireWith https://www.worldanvil.com/js/compiled/global.js?v=01523:1
    ready https://www.worldanvil.com/js/compiled/global.js?v=01523:1
    B https://www.worldanvil.com/js/compiled/global.js?v=01523:1
    EventListener.handleEvent* https://www.worldanvil.com/js/compiled/global.js?v=01523:1
    <anonymous> https://www.worldanvil.com/js/compiled/global.js?v=01523:1
    <anonymous> https://www.worldanvil.com/js/compiled/global.js?v=01523:1
athena:645:13
```

**Comment by woodjm** [comment]
The article and category list(s) never load and I get a perpetual "Loading Articles list..." message.  Currently using dark mode.  I've tried both Firefox and Chrome browsers.
![WorldAnvil_Art_Cat_Bug](https://user-images.githubusercontent.com/3219296/110230656-8095b100-7ee0-11eb-9046-de571eec1a1c.PNG)

**Comment by iamromeo** [comment]
Deployment to fix this is under way.
