### ISSUE TITLE
Spotify media not showing in article

### ISSUE THREAD

**Issue by Pips98** [worldanvil/worldanvil-bug-tracker#371]
Pips98:

Vekuth:

Spotify Embedded Media: 

https://www.worldanvil.com/w/vekuth-pips98/a/spotify-bug-demo-article:

**Describe the Issue**
Spotify playlists showing up fine in the editor, but not when viewing world.
Not fixed by making playlist public, changing CSS theme, changing from draft/WIP to published/done.
Also present using Safari on my iPad.

**To Reproduce**
1. Create/edit an article.
2. Click on 'Additional Options'
3. Click on 'Insert Spotify Media'
4. Enter playlist URL
5. Click on 'Save changes'
6. Click on 'View'
7. See error ("Bad Request")

**Expected behavior**
Spotify playlist to be visible in

**Screenshots**
![Screenshot 2021-06-17 140042](https://user-images.githubusercontent.com/86035564/122330008-ba616380-cf75-11eb-9618-4f4b8484803e.png)
![Screenshot 2021-06-17 140155](https://user-images.githubusercontent.com/86035564/122330012-bc2b2700-cf75-11eb-8cb6-7511db848d9a.png)
![Screenshot 2021-06-17 140847](https://user-images.githubusercontent.com/86035564/122330016-bcc3bd80-cf75-11eb-9944-ad09fe3b9323.png)
 article.

**Comment by Kordishal** [comment]
This is an issue with the Plato editor. The button creates outdated spotify embed BBCode. Go into source mode and switch to this:

https://www.worldanvil.com/w/WorldAnvilCodex/a/bbcode#embedding

How to access source mode: https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors

This issue will not be addressed until the rework of plato.
