### ISSUE TITLE
World Export - "Job failed: AttributeError: 'NoneType' object has no attribute 'strip'" error

### ISSUE THREAD

**Issue by shyredfox** [worldanvil/worldanvil-bug-tracker#372]
**World Anvil Username**: shyredfox

**World / Campaign / RPG Character / Manuscript Title**: All Worlds

**Feature**: WorldExporter

**Related URLS** (To public & visible pages add screenshots otherwise):
https://toolbox.soullink.docker.worldanvil.com/backup/form

**Describe the Issue**
When I try to export all my worlds at once, I get the following error: "Job failed: AttributeError: 'NoneType' object has no attribute 'strip'"

**To Reproduce**
1. Go to https://toolbox.soullink.docker.worldanvil.com/backup/form
2. Fill in email and Authentication Token Click on "Start"
3. Wait for message in window.

Also am trying world by world export. It appears to only happen with the Anvilite Streamers Corps world ( https://www.worldanvil.com/w/anvilite-streamers-corps ). It's a shared world with several users. Let me know if you need any more details.

**Expected behavior**
I expected a message that said "Finished export for user shyredfox." and an email with the link.

**Screenshots**
![Screenshot_33](https://user-images.githubusercontent.com/59369948/122459840-07920500-cf77-11eb-9fcf-33bbee2f76fa.png)
I covered up my email and token. DM me if this is needed.

**Comment by Kordishal** [comment]
Hi, this might be fixed. Can you run the the broken world again?
