### ISSUE TITLE
Image tag breaks spoiler tag

### ISSUE THREAD

**Issue by Lethann** [worldanvil/worldanvil-bug-tracker#379]
**World Anvil Username**: Lethann

**World / Campaign / RPG Character / Manuscript Title**: The Chronicles of Bennoria

**Feature**:  img & spoiler tag

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/the-bennorian-chronicles-lethann/a/my-summer-camp-2021-worldbuilding-pledge-document-article

**Describe the Issue**
Using image bbcode with alignment/width specified breaks the [spoiler] bbcode

**To Reproduce**
1. Go to any article page
2. Create an image tag inside a spoiler tag, being sure to use the specifications for the image tag:: [spoiler][img:2385241|center|500] | custom text[/spoiler]
3. Save and preview/view the page
4. The custom text will be changed to the 'alignment' (in this case center) and the rest of the tag will be broken, preventing the image from showing.

**Expected behavior**
The spoiler tag should not pick up any | characters that are inside other codes. 

**Screenshots**
![Screenshot 2021-06-19 225103](https://user-images.githubusercontent.com/25929754/122661627-de799c00-d151-11eb-9f96-3c33f64b392e.png)
![Screenshot 2021-06-19 225134](https://user-images.githubusercontent.com/25929754/122661628-e1748c80-d151-11eb-8b0d-ccfd34cff732.png)

**Comment by iamromeo** [comment]
That is an issue with spoilers and the use of | - this will not be resolved for the time being.
