### ISSUE TITLE
Private maps create public or private markers depending on marker tool used

### ISSUE THREAD

**Issue by MGatta** [worldanvil/worldanvil-bug-tracker#38]
Hello!

A private map (created private in a public world), creates markers that are either public or private. Markers created in the edit mode default to public. Markers created in the presentation mode default to private (markers created without touching the advanced options & privacy settings). Ideally, both marker creation methods result in the same privacy setting.

![image](https://user-images.githubusercontent.com/80196715/110235704-cf1f6b80-7f31-11eb-9f24-5f5f3ce80c7d.png)
![image](https://user-images.githubusercontent.com/80196715/110235707-d34b8900-7f31-11eb-9279-b139540e396e.png)

**Comment by iamromeo** [comment]
this is scheduled for development :) fix coming up right up
