### ISSUE TITLE
Relationship values are missing CSS classes on cols

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#381]
**World Anvil Username**: SoulLink

**Feature**: Relationships

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/WBtV/a/teyla-orairo-person

**Describe the Issue**
The status icons are missing some margins on the cols. This makes them misaligned with the info text at the end.

**Screenshots**
![image](https://user-images.githubusercontent.com/14262536/122757952-81d4c900-d298-11eb-9747-eb565226f218.png)

**Comment by Kordishal** [comment]
That fix worked for the left side. The right side is not fixed yet 

![image](https://user-images.githubusercontent.com/14262536/122872334-9c5a8100-d330-11eb-991b-10f7eac0ec30.png)

**Comment by iamromeo** [comment]
We do not like the right side - we prefer to be wrong :P
