### ISSUE TITLE
Dark Souls

### ISSUE THREAD

**Issue by Rrios249** [worldanvil/worldanvil-bug-tracker#383]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name (RPG SYSTEM)**:
**List Name** (Name under which it should be listed on World Anvil):
**World Anvil Username**:

**Website**:

**Logo Image Link**:

**Logo Usage Terms (URL)**:

**Comment by Kordishal** [comment]
Hi, could you at least fill in your username and a link to the website?

**Comment by iamromeo** [comment]
The user is a freeman and also unable to follow instructions - this is closed
