### ISSUE TITLE
Dashboard UI/UX in World pushing right sidebar down on wide (1920px) monitor

### ISSUE THREAD

**Issue by CBairdAsh** [worldanvil/worldanvil-bug-tracker#386]
**World Anvil Username**: Kummer Wolfe

**World / Campaign / RPG Character / Manuscript Title**: Tales of Justice (however it is happening on all worlds) 

**Feature**: Dashboard UX/UI display

**Related URLS** (To public & visible pages add screenshots otherwise): No public URL since it is the dashboard of the world

**Describe the Issue**
I opened the Dashboard of my world Tales of Justice and found the Dashboard filling the entire right side of the display. All widgets, and all controls that had appeared to the right of the Dashboard have been pushed below the Dashboard. 

See screenshots for visual capture of instance.

The Dashboard is still usable, however this was not happening this morning ( 6.24.2021 ) when I was logged into World Anvil.

This new UX/UI rendering on a wide monitor does not present itself in the friendliest manner. The "Continue Working", "Campaign List", etc is more useful for me than Statistics widget. 

Viewed on Google Chrome 91.0.4472.114

**To Reproduce**
1. Open a world's Dashboard on a monitor with 1920px width

**Expected behavior**
The expected UI / UX was that the Dashboard would have the "Continue Working", "Campaign List" to the right and the "Statistics" widget below the Dashboard.

**Screenshots**
Screenshots attached
![Screenshot 2021-06-24 140537 1](https://user-images.githubusercontent.com/7758229/123320313-310edb80-d4f7-11eb-83f2-7eeffd0beb45.jpg)
![Screenshot 2021-06-24 140638 4](https://user-images.githubusercontent.com/7758229/123320316-31a77200-d4f7-11eb-958d-662849071603.jpg)
![Screenshot 2021-06-24 140615 3](https://user-images.githubusercontent.com/7758229/123320318-32400880-d4f7-11eb-8df6-1ad7c69f77a6.jpg)
![Screenshot 2021-06-24 140555 2](https://user-images.githubusercontent.com/7758229/123320320-32d89f00-d4f7-11eb-8872-492cfb746efc.jpg)

**Comment by CBairdAsh** [comment]
**Updated information** 

This only appears to happen when the Global Announcement Wrapper is active. The HTML structure is different at that point and caused the above. 

Now that the global announcement of a stream is not active, the UI is back to what I was expecting.

**Comment by iamromeo** [comment]
Hey Kummer - I cannot replicate this bud. 
There was an issue for 5 minutes when we went live - I made a mistake but I will check again today when the announcement goes up

**Comment by CBairdAsh** [comment]
No worries, Dimitri. Hopefully, it's resolved!
