### ISSUE TITLE
The mention copy code on the heroes does not match the real code

### ISSUE THREAD

**Issue by shakusaurus** [worldanvil/worldanvil-bug-tracker#389]
**World Anvil Username**: shakusaurus

**World / Campaign / RPG Character / Manuscript Title**: Naemos or whatever https://www.worldanvil.com/hero/0d7b52e0-94af-4f45-b640-7527b500c30d
and Olivier https://www.worldanvil.com/hero/277e6e13-c636-4190-9148-c01aea2de09f

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.
The codes needed to @ link/mention to these characters do not work. 

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
I am sorry but this bug report makes little sense and there are  no examples of location or way of reproducing

**Comment by Kordishal** [comment]
![image](https://user-images.githubusercontent.com/14262536/123517115-a1f0f780-d69f-11eb-9056-4951d910e7e0.png)

vs

https://www.worldanvil.com/hero/0d7b52e0-94af-4f45-b640-7527b500c30d

------------

![image](https://user-images.githubusercontent.com/14262536/123517145-b46b3100-d69f-11eb-931c-068e6ce7ae2c.png)

vs

https://www.worldanvil.com/hero/277e6e13-c636-4190-9148-c01aea2de09f

**Comment by shakusaurus** [comment]
Thanks, Jonas :)

**Comment by iamromeo** [comment]
This mention is not an article mention - it's exclusive to the heroes stream - not a bug

**Comment by Kordishal** [comment]
The code is different Dimitris. That has happened once before. Last time it was caused by the character being a paid account before or something.

The copy button should copy the correct code. Not whatever it is that it copies. Thats why it doesn't work.

**Comment by shakusaurus** [comment]
You're my hero, Jonas. We're just trying to be able to @ each other easily
in our journal and comment posts, but the code is incorrect in that
copypaste area (doesn't match the character's code). It happened to both of
our accounts. I just checked, and this also occurred on our friend who just
joined, so adding this to the ticket.

Here's his character page (you can see where the code needed, indicated in
the URL, does not match the copypaste mention code in the bottom section),
so we would, therefore, not be able to @ or [hero] him in any fashion using
the copypaste codes.
https://www.worldanvil.com/hero/5f7a8d3b-cec0-4dbc-a4c2-8a9cb6008b2a

This seems to be a fairly prevalent issue, which is why my initial request
was so brief. I assumed you guys were already aware. I looked in the global
stream of characters and the first few that I clicked on had the same issue.

Here are a few more randos from the global stream with the same issue:
https://www.worldanvil.com/hero/616c9315-89a5-4c8e-9471-91a3c6a14528
https://www.worldanvil.com/hero/2363e2f0-a2b0-4d63-9dd7-d4606c8d12ea
https://www.worldanvil.com/hero/0adb5b88-76d4-45c7-9e27-05937aefcce3

This is just from the top few. I didn't search very long.

I think your autogenerate is mismatched when new characters are created.
Hope this helps!

- Jessica

**Comment by iamromeo** [comment]
It seems that for some reason these characters had alternative url slugs
the old slugs might. now work any more but they will now be in par with the slug as it was supposed to be

**Comment by shakusaurus** [comment]
https://www.worldanvil.com/hero/5f7a8d3b-cec0-4dbc-a4c2-8a9cb6008b2a
This friend's is still broken. Thank you for fixing ours!
