### ISSUE TITLE
Character name change doesn't propagate to Family Tree node label, and character page

### ISSUE THREAD

**Issue by ErikjeMS** [worldanvil/worldanvil-bug-tracker#391]
**World Anvil Username**: erikfrog

**World / Campaign / RPG Character / Manuscript Title**: Deadlands campaign

**Feature**: Relationships

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I changed the name of a character (Malachi McCracken to Moses McCracken). The name change replicated to everywhere except:
- The pre-existing Family Tree still shows the old name for the node.
- Moses McCracken character page child list. It still says
    - Malachi McCracken
    - Biological parent of Lemuel McCracken   

**To Reproduce**
1. Create some characters.
2. Create some family relationships between the characters.
3. For a character with a spouse and a child, change the characters name.
4. Go to character's page and see the old name still over the child's name. Also, the old name still appears in the Family Tree.

**Expected behavior**
The new name should replace the old name in Family Tree node and the character is parent section.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![wabug1](https://user-images.githubusercontent.com/15129944/123530171-54c75280-d6ac-11eb-901f-699266f4755e.GIF)
![wabug1b](https://user-images.githubusercontent.com/15129944/123530172-598c0680-d6ac-11eb-8bc6-17a1f328a82f.GIF)

**Comment by Kordishal** [comment]
The first name is the title of the article.

The second name is in the naming tab. The family tree uses the naming tab if present. You'll have to change it there as well.
