### ISSUE TITLE
Map Label Marker Delete Issue

### ISSUE THREAD

**Issue by cyberianfrontier** [worldanvil/worldanvil-bug-tracker#393]
**World Anvil Username**: Buzzard

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: Maps, Delete Label Marker

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When deleting a Label Marker from a Map via the Edit Map interface, the marker deletes as expected, but the resulting page is blank except for the text '200', which I expect is simply a status code indicating success.

**To Reproduce**
1. Go to Edit Map
2. Select a Label Marker in the map to display the 'Delete' button.
3. Click Delete button.  You should be redirected to a URL similar to this: 'https://www.worldanvil.com/world/map/marker/bd495a3d-7eb9-4797-9c91-b0dba7ea88f0/delete'
4. See attached screen capture of the resulting page/display.

**Expected behavior**
I would expect to be redirected back to the Edit Map interface or to a branded page within the admin with a message that says 'Marker deleted...' and then provided a link back to the Edit Map interface.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/81428411/123553011-d3180900-d72d-11eb-9cab-7e1b6ccd4fd2.png)

**Comment by Kordishal** [comment]
Did you per chance press the middle mouse button to delete that label? Because thats just the response in a new tab. Can't make this happen otherwise.

**Comment by cyberianfrontier** [comment]
I'm sorry.  There was an error in my bug report.  This issue didn't happen in the Edit Map screen.  It happened in the Edit Marker screen.  If you go to Edit Marker, then select the Marker, the Delete button there will drop you off at the blank page with the 200 status code.

![image](https://user-images.githubusercontent.com/81428411/123664160-f3a69880-d7eb-11eb-90ff-412dac180397.png)
