### ISSUE TITLE
Json message when deleting a marker in edit

### ISSUE THREAD

**Issue by aschnik** [worldanvil/worldanvil-bug-tracker#394]
**World Anvil Username**:
Jonas Jillerholm
**World / Campaign / RPG Character / Manuscript Title**:
Uthardin
**Feature**: 
Delete marker from EDIT marker view
**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
1. Edit a marker on a map
2. Click on the marker on the map that is shown at the top of the edit page.
3. Choose delete
A json message of 200 (think it means successful return if i am not mistaken) i shown in the page because you end up in a json return view:

**To Reproduce**
1. Edit a marker on a map
2. Click on the marker on the map that is shown at the top of the edit page.
3. Choose delete
A json message of 200 (think it means successful return if i am not mistaken) i shown in the page because you end up in a json return view:

**Expected behavior**
Propably a submit redirect back to the map

**Screenshots**
![unnamed](https://user-images.githubusercontent.com/86602225/123625207-d1bf0d00-d80f-11eb-8b72-b64a9e8dfa3e.png)

**Comment by cyberianfrontier** [comment]
This is the issue that I reported yesterday (#393), but I incorrectly reported that the issue happened on the Edit Map screen.  The issue happens on the **Edit Marker** screen.  My apologies for the error.

**Comment by Kordishal** [comment]
@cyberianfrontier No worries, thanks for linking!

**Comment by iamromeo** [comment]
Brutally came to an end
