### ISSUE TITLE
Quick Article Creation is broken for me, constantly tells me to add a title

### ISSUE THREAD

**Issue by nonplayer** [worldanvil/worldanvil-bug-tracker#397]
**World Anvil Username**: nonplayer

**World / Campaign / RPG Character / Manuscript Title**: https://www.worldanvil.com/w/the-glitterbois-megaverse-nonplayer

**Feature**: Quick Article Creation

**Describe the Issue**
If I use the + button to add a quick article, it always fails. Every time, no matter what I enter, it tells me "You might want to add a title to this! :)"

I have already added a title. For some reason it cannot see it.

**To Reproduce**
1. Go to Articles and Categories page
2. Select a category
3. Use the Quick Article button to add a Generic article,with a title.
4. Hit "Create Article"

**Expected behavior**
Article should be added.

**Screenshots**

![image](https://user-images.githubusercontent.com/5161177/123810586-6163ca80-d8a7-11eb-860e-a012ab4e37d0.png)
![image](https://user-images.githubusercontent.com/5161177/123810615-66c11500-d8a7-11eb-8747-b27714bff31d.png)

**Comment by iamromeo** [comment]
This only happens if you are in the Aritcles & Categories page because there is the actual Articles & Categories article creation system interfering. 

This is an known issue but not a bug as described above :)

**Comment by nonplayer** [comment]
> This only happens if you are in the Aritcles & Categories page because there is the actual Articles & Categories article creation system interfering.

Can you explain this a bit more? Because your response does not actually help me in any way. The issue is still there, using a feature on that page. If a feature of the toolset isn't working as designed, that's a bug. 

Where is this so-called "known issue" even posted? How am I supposed to know this? it certainly wasn't known to me, otherwise I would not have opened the bug report. As it stands, despite you closing this, I still cannot quick add articles on that page. Call it a known issue if you like, but it's still a bug.

If the Quick Article Creation button isn't working on that page, then it shouldn't be available on that page. Either remove the button, or fix it. There's no point having a broken tool.

**Comment by iamromeo** [comment]
Just to clarify - I am removing the button as we speak

**Comment by nonplayer** [comment]
Thanks! <3

**Comment by nonplayer** [comment]
Follow-up: I see the article button is removed (nice!) but the default content creation still defaults to article format:

![image](https://user-images.githubusercontent.com/5161177/123835141-0b018680-d8bd-11eb-898b-12548cc98ede.png)

1. Click Quick Actions Button
2. Click Quick Content Creation Button
3. Article form is opened by default, despite the article button missing.
