### ISSUE TITLE
Add docs link to csv import feature

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#40]
**World Anvil Username**: SoulLink
**Feature**: Interactive Tables

**Describe the Issue**
The interactive tables feature has a number of limitations that are currently not documented on the page.

**Expected behavior**
It would help if there were a link to https://www.worldanvil.com/w/WorldAnvilCodex/a/csv-import.

There are most, if not all of the issues documented. This should help people import tables successfully.

**Comment by iamromeo** [comment]
Will be releasing soon
