### ISSUE TITLE
Spaces in URLs (at least in user's signatures) break the code both in articles and on the website

### ISSUE THREAD

**Issue by Naeliner** [worldanvil/worldanvil-bug-tracker#400]
**World Anvil Username**: Naelin

**World / Campaign / RPG Character / Manuscript Title**: Symbols of Power

**Feature**: User's signature

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/shakiraverse-thechangeling/a/welcome-to-shakiraverse-law
https://www.worldanvil.com/w/symbols-of-power-naelin/a/the-silent-ones-myth
https://www.worldanvil.com/author/thechangeling
https://www.worldanvil.com/w/omari-dappercapricorn/a/kobold-s-crockpot--landmark

**Describe the Issue**
Anywhere where a certain user's signature appears is breaking, making footers look bigger, sidebars move to the full footer, widening sections, etc. The only thing that seems to be wrong with the user's signature is (seemingly) a space just before the URL of their ko-fi page.
![image](https://user-images.githubusercontent.com/86533873/124205415-8e86c780-dab7-11eb-8e63-038b3a5a14b2.png)

**To Reproduce**
1. Go to https://www.worldanvil.com/author/thechangeling
2. Navigate to the guestbook.
-
1. Create a user's signature with a custom URL
2. Add a space just before "https"
3. Post a comment somewhere on the site

**Expected behavior**
Spaces on URLs should be ignored

**Screenshots**
![image](https://user-images.githubusercontent.com/86533873/124205395-86c72300-dab7-11eb-9783-79bafb2c3e6d.png)
![image](https://user-images.githubusercontent.com/86533873/124205450-a1999780-dab7-11eb-9aab-b62800a753ad.png)
![image](https://user-images.githubusercontent.com/86533873/124205518-c5f57400-dab7-11eb-9914-1db8d7b3b9b3.png)
![image](https://user-images.githubusercontent.com/86533873/124205560-dc033480-dab7-11eb-9503-9a5359c0c8e4.png)

**Comment by Lyraine-Alei** [comment]
I would reach out to the user and have them check out their community signature just in case they have a [url: LinkHereWithASpaceInFront] Words[/url] but I've tagged these for if it turns out not to be a space in the BBCode.

**Comment by iamromeo** [comment]
This is a user input mistake, I cannot just start randomly removing spaces from urls to make them work :P It will break the world :P
