### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by Jester4** [worldanvil/worldanvil-bug-tracker#401]
**World Anvil Username**: Jester%

The Sagas

Bloodlines

https://www.worldanvil.com/world/condition/2b32edda-c9b9-4d58-b27f-fb78d969b51b/edit

**Describe the Issue**
When trying to go on to the article a black screen appears in front of it and the article is still visible, but when a mouse is moved onto it is completely black until it is removed.

**To Reproduce**
go onto article
move mouse cursor onto it

**Expected behavior**
screen goes black
![Screenshot (7)](https://user-images.githubusercontent.com/83615364/124208028-baed1480-dab4-11eb-8d66-0777fd29f951.png)
![Screenshot (6)](https://user-images.githubusercontent.com/83615364/124208047-c7716d00-dab4-11eb-9823-ee06f10f203a.png)

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Lyraine-Alei** [comment]
This looks like a CSS issue, and the Discord has a CSS channel who will be able to help you further identify the issue.

**Comment by Lyraine-Alei** [comment]
Additionally, could you rename this to "Article Body Goes Black on Mouseover" instead of "Black Screen, as the suggested is more specific to what you're having than the latter (Black Screen usually implied, at least to me, that your entire screen is turning black)

**Comment by iamromeo** [comment]
That actually looks like an unclosed tag somewhere. 
This cannot be replicated since this article is not accessible
