### ISSUE TITLE
Error 404 when editing email address

### ISSUE THREAD

**Issue by MJHeijster** [worldanvil/worldanvil-bug-tracker#402]
**World Anvil Username**: MoonRaven

**Feature**: Account Details

**Related URLS** (To public & visible pages add screenshots otherwise):https://www.worldanvil.com/dashboard/user/account

**Describe the Issue**
When editing my email on https://www.worldanvil.com/dashboard/user/account, it goes to https://www.worldanvil.com/profile/edit . That page returns an error 404.

**To Reproduce**
1. Click your avatar in the top right 
2. Click Account Details
3. Modify your Email
4. Fill your current password
5. Press Update

**Expected behavior**
A page shows up that says it was updated.

**Comment by Kordishal** [comment]
It probably does because your username is the same. As the form 404s when the username already exists,

**Comment by MJHeijster** [comment]
> 
> 
> It probably does because your username is the same. As the form 404s when the username already exists,

I can confirm I don't edit my username.

**Comment by iamromeo** [comment]
THe chances are that the email you are trying your account to, already has a record on the system.
