### ISSUE TITLE
Timelines Not Adding Images Issue

### ISSUE THREAD

**Issue by rks18b** [worldanvil/worldanvil-bug-tracker#404]
**World Anvil Username**: rks18b

**World / Campaign / RPG Character / Manuscript Title**: Alethea Post Arrival

**Feature**: Timeline

**Related URLS** (To public & visible pages add screenshots otherwise):  https://www.worldanvil.com/w/alethea-rks18b/t/alethea-post-arrival-timeline?preview=1

**Describe the Issue**
Hey, I tried to add images to my timeline, which I couldn't get to work so I took it out. But, seems like I've done something to completely bug out my timeline from the entry I tried it on forward. 

**To Reproduce**
1. Go to Alethea Post Arrival
2. Scroll down to see the weirdness after the "Era of Anti Magic"

**Expected behavior**
It to not (?) look like it does and look like the timeline above thee "Era of Anti Magic"

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

<img width="619" alt="Screen Shot 2021-07-02 at 1 16 54 PM" src="https://user-images.githubusercontent.com/41344667/124308858-dfd69b80-db37-11eb-9e24-a9c041fdab0f.png">
<img width="1309" alt="Screen Shot 2021-07-02 at 1 17 22 PM" src="https://user-images.githubusercontent.com/41344667/124308872-e49b4f80-db37-11eb-9b69-ce32581364f2.png">

Thank you!

**Comment by Lyraine-Alei** [comment]
This looks like some unclosed BBCode somewhere. If you're using the Plato editor (the one that looks like a Word Processor) go into Source Mode by hitting the button that looks like a >_ and then see if the image you were wanting has been properly closed with a ] or similar, and check to see if you have any [p] or [in] tags missing a [/p] or [/in]

**Comment by rks18b** [comment]
Thank you! All good now. Such a silly mistake.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Lyraine-Alei** [comment]
Not a problem - don't hesitate to ask for help on the Discord as well!
