### ISSUE TITLE
Codex Links disappear when edited and don't open when they do show up.

### ISSUE THREAD

**Issue by Thkaal** [worldanvil/worldanvil-bug-tracker#407]
**World Anvil Username**: Thkaal

**World / Campaign / RPG Character / Manuscript Title**: World?

**Feature**:  Player Handbook

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/people-of-el-thkaal
https://www.worldanvil.com/w/people-of-el-thkaal/c/player-handbook-category
https://www.worldanvil.com/w/people-of-el-thkaal/c/player-options-category

**Describe the Issue**
In the Player Handbook, clicking on a category does not open the category page unless I open in a new window.  Edited categories actually disappear from the codex.

**To Reproduce**

**Expected behavior**
I expect that when a link is clicked, the item opens, either as a page, or as a tooltip

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Categories do not open in new pages unless you clik on the symbol on the right hand side - this is not a bug.
