### ISSUE TITLE
article content disappearing

### ISSUE THREAD

**Issue by Shinteetah** [worldanvil/worldanvil-bug-tracker#408]
LauraVAB

Shard of Elan, article: The Blue Dare Milking Cow

https://www.worldanvil.com/world/species/f0f4c01b-e57e-4948-87aa-25bc7c66eb74/edit

**Describe the Issue**
Euclid editor: When spellcheck is enabled, pasting text into a template-specific prompt box will delete irrevocably text from the main content.

**To Reproduce**
1) Type article in main content.
2) Spellcheck main article. Leave spellcheck on.
3) Select bit of text that would better fit in another section. Copy.
4) Scroll down to template-specific prompts. Paste.
5) Note green "Saved" indicator at top right.
6) Scroll up to main article content.
7) It's gone, reverted back to (apparently) first save with less than a full sentence. 
8) Control-Z will not bring back missing text.

I was able to duplicate this effect several times. I composed my article in Notepad and then pasted, but it seems to not be an issue if spellcheck is off.

**Comment by iamromeo** [comment]
I am really sorry to hear that and certainly sorry that you have lost some of your work. 

I have tried to follow your steps to replicate and I was not able to do that - can you give me some more details on this, as in the browser you have been using? As it stands this cannot be replicated.

**Comment by Shinteetah** [comment]
I was able to get a screen recording of it!

https://api.vadoo.tv/landing_page?vid=iteYYWOjHZ21p56rLnOrYwlhSmG7yXQ8

I am using Chrome, latest updates.

**Comment by Shinteetah** [comment]
And one more, where it reverted to a saved version and replaced the missing
text -- which is less scary, but still interesting.

https://api.vadoo.tv/landing_page?vid=abbHldW6qOb8406HBrbXM6Ov1V47xB9n

**Comment by iamromeo** [comment]
I am sorry but this is really an edge of an edge case and certainly a misuse of how the feature is meant to be used. I will freeze this

**Comment by Shinteetah** [comment]
I expected it to be a fringe case, since few people were affected, just
thought it might be useful to know. I didn't realize I was certainly
misusing the site.

Thanks for your time.

**Comment by iamromeo** [comment]
@Shinteetah thank you for reporting - I have kept a note of this for future reference
