### ISSUE TITLE
To-do items created without @ feature intervention

### ISSUE THREAD

**Issue by MGatta** [worldanvil/worldanvil-bug-tracker#41]
**World Anvil Username**: MGatta

**Feature**: To-do list

**Describe the Issue**
To-do items are created at random without the intervention of using the @ feature to create a draft. I am certain it is not necessarily related to the use of the @ feature in general, thanks to tracking/backtracking to-dos created back to the original text (see screenshots below). So at least some of these random to-dos are not related to the @ feature.

Please note I have previously reported this issue, but SoulLink recommended that I submit it again, since the issue continues to happen.

**Expected behavior**
For random items to not be created and added into the to-do list.

**Screenshots**
![image](https://user-images.githubusercontent.com/80196715/110244021-1cfd9900-7f5d-11eb-97d3-2b8b3043e52b.png)
![image](https://user-images.githubusercontent.com/80196715/110244046-31419600-7f5d-11eb-8439-12ecc9efbfb6.png)
![image](https://user-images.githubusercontent.com/80196715/110244060-43bbcf80-7f5d-11eb-8b97-85e996611484.png)

**Comment by Kordishal** [comment]
Duplicate with #39 

And this text does not create a TODO item when writing as it is. What most likely did occur is that you typed an @ and then stack while writing this after the of. That would explain why the part `ing fortune (4.875 gp)` is missing from the TODO title.

I already created the ticket after you gave up. Sorry about that, should have messaged you :)
