### ISSUE TITLE
Summer Camp Submitting

### ISSUE THREAD

**Issue by foxteeth** [worldanvil/worldanvil-bug-tracker#412]
**World Anvil Username**: foxteeth

**World / Campaign / RPG Character / Manuscript Title**: Kaleva

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise): 
https://www.worldanvil.com/w/kaleva-foxteeth/a/vellamas-tod-myth (link to the article the screenshot is of)

**Describe the Issue**
I'm having issues submitting articles for the summer camp challenge. I've tried it with multiple articles all of which had been created after July 1st, have over 300 words, are public and published. My world is set on public too and I already checked in with the Discord community, but nobody had an idea what could be the problem.
The Community Challenge panel just never shows up in the edit screen. The only thing below the Metadata panel is the Design Tags Reference link.

**To Reproduce**
/

**Expected behavior**
/

**Screenshots**
![Screenshot 2021-07-05 at 20-36-41 Worldbuilding- und RPG Kampagnen-Verwaltung World Anvil](https://user-images.githubusercontent.com/86981414/124508788-d320a480-ddd0-11eb-8b42-686416be8dd5.png)

If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Xuroth** [comment]
Please try clicking on "Open Advanced Tools & Options" in the sidebar (the area you have posted an image of), then you should see near the bottom a tab labelled "Worldbuilding Summer Camp 2021". Click there, and the SC prompt should appear, simply click that and your article is submitted.

Please note: If you created the article manually (as opposed to clicking the relevant button on the Challenge page to create it), you MUST ensure that the article's template matches the required template type for the prompt. IE, if you're creating an article to answer the "Describe a medical condition that is feared by some" prompt, the article has to be a "Condition" article. If the template is not the correct one for the prompt, the option to submit will be absent.

Tip: To avoid confusion with manual entries (noted above), you can simply go to https://www.worldanvil.com/community/challenge/summercamp-2021/homepage and click the appropriate "Write Prompt" button. The prompts listed on this page also have the required template type listed in a blue label for each prompt.

I've attached the image of how the submit option should look on manually created entries:
![SC21-Manual-Entry](https://user-images.githubusercontent.com/3972262/124523343-91c9ce00-ddab-11eb-9471-9cbc1570fb88.png)

**Comment by foxteeth** [comment]
Thanks for the answer. I created each article over the "write prompt" option on the sumer camp page and also manually checked the templates. They're all part of the first 10 worldbuilding prompts so that can't be the issue.
The "worldbuilding summer camp 2021" panel just does't show up ony any of those articles, no matter the word count or publication state. There's nothing below the metadata panel, when I open advanced tools & options.

**Comment by foxteeth** [comment]
Ok seems the ticket is closed anyway but I'll leave this here just in case. Seems I had community features disabled, something which I didn't even know could be done. Everything's working now.
So sorry for the fuss and thanks for the help!
