### ISSUE TITLE
Custom access denied page not showing on drafts

### ISSUE THREAD

**Issue by Naeliner** [worldanvil/worldanvil-bug-tracker#414]
**World Anvil Username**: Naelin

**World / Campaign / RPG Character / Manuscript Title**: Tierras Mágicas and Around

**Feature**: Custom access denied pages

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/tierras-magicas-and-around-naelin/a/the-lions-of-vintiver-organization

**Describe the Issue**
I have set a [Custom access denied page](https://www.worldanvil.com/w/tierras-magicas-and-around-naelin/a/it-never-stops-sinking-article) for [this world](https://www.worldanvil.com/w/tierras-magicas-and-around-naelin), which is showing correctly on private articles. 
However, for draft articles such as [this one](https://www.worldanvil.com/w/tierras-magicas-and-around-naelin/a/the-lions-of-vintiver-organization), the generic Multipass page with the draft message is showing. When I asked if there was a way to make it show for drafts, Hanhula indicated it does for her without any particular action taken on her side.

**To Reproduce**
1. Go to any draft in this world such as this one: (https://www.worldanvil.com/w/tierras-magicas-and-around-naelin/a/the-lions-of-vintiver-organization
2. See error

**Expected behavior**
The custom access denied page should show for drafts

**Screenshots**
![image](https://user-images.githubusercontent.com/86533873/124680666-36780880-de9d-11eb-8640-588b09883e65.png)

**Comment by iamromeo** [comment]
This is not a bug, the custom access denid page never showed on drafts. What showed was this page without the message on the top
