### ISSUE TITLE
Need to have several manuscripts deleted...

### ISSUE THREAD

**Issue by ONI-Aeon** [worldanvil/worldanvil-bug-tracker#415]
**World Anvil Username**: Shadows Nocturne

**World / Campaign / RPG Character / Manuscript Title**: Shadows Aria, Shadows' Requiem, Shadows' Nocturne, and Shadows' Sonata

**Feature**: These are alpha manuscripts and when I delete them, I get a 404 error.  I would like all four of them deleted so that I can work on them in the new format.  ^_^  

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
There is already a documented bug for this - in the future please check below before submitting
