### ISSUE TITLE
Unable to Delete a Manuscript

### ISSUE THREAD

**Issue by crauscher** [worldanvil/worldanvil-bug-tracker#416]
**CRauscher**:

**AfterThePulse/Reboot (manuscript)**:

**Delete Manuscript**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I attempted to delete a manuscript titled "Reboot", but it is still showing up on my list of manuscripts. The main document is no longer present, only the folders and bin remain (I stripped out the content once I realized they wouldn't be removed.)

**To Reproduce**
1. Go to 'Manuscripts List'
2. Click on the delete option for the manuscript titled 'Reboot'.
3. Type in the title of the manuscript ("Reboot") and click 'Delete"
4. Confirm deletion by clicking the "Ok" button on the pop-up window.
5. See error (you are taken to a 404 Error page)

**Expected behavior**
After typing in the title and confirming deletion. I expected to be returned to the manuscripts list and find the manuscript no longer there.

**Screenshots**
![manuscripts-list](https://user-images.githubusercontent.com/5396338/124982695-0186c580-e005-11eb-936d-b25bb5a450a7.jpg)
![manuscript-delete](https://user-images.githubusercontent.com/5396338/124982697-0186c580-e005-11eb-88c9-46c55efb1091.jpg)
![404-error](https://user-images.githubusercontent.com/5396338/124982696-0186c580-e005-11eb-9989-7fba6c1422d2.jpg)

(Here's what the manuscript looks like now. Note the missing core data.)
![manuscript-edit](https://user-images.githubusercontent.com/5396338/124982694-00ee2f00-e005-11eb-8e55-144962754a0d.jpg)

**Comment by Lyraine-Alei** [comment]
This reads as a duplicate bug report, please look into the closed bug reports as Closed does not always mean "fixed."

**Comment by iamromeo** [comment]
There is NON closed report already in the board on that.

**Comment by Lyraine-Alei** [comment]
Apologies, and thanks for the correction!
