### ISSUE TITLE
Manuscript chapter and scene names unreadable when using dark mode and a label

### ISSUE THREAD

**Issue by Nahbyr** [worldanvil/worldanvil-bug-tracker#417]
**World Anvil Username**: Nahbyr

**World / Campaign / RPG Character / Manuscript Title**: Godlings

**Feature**:  Chapter/Scenes with a label

**Related URLS** (To public & visible pages add screenshots otherwise):
![image](https://user-images.githubusercontent.com/5855327/125078358-913e7980-e0c2-11eb-9045-b71ef1f9f484.png)
![image](https://user-images.githubusercontent.com/5855327/125080166-c77cf880-e0c4-11eb-91d0-828959e3d025.png)

**Describe the Issue**
Dark mode (any) + labels = unreadable chapter and scene names because the colour of the font does not change and stays a light grey.

**To Reproduce**
1. Go to manuscripts (and/or click next on a chapter)
2. Click on change to dark mode
3. Add label to a chapter or scene

**Expected behavior**
Readable text. Maybe have it contrast according to what you've set as the background?
Or maybe shift the colour of the labels when you change to dark mode to a more dark mode friendly colour? Now it looks pretty when using labels in light mode, but when you switch to dark mode it'll burn out your eyes. If you could shift the hex colour code to something more dark mode friendly then that would eliminate the need to change the colour of the font if it has a label

**Screenshots**
![image](https://user-images.githubusercontent.com/5855327/125078358-913e7980-e0c2-11eb-9045-b71ef1f9f484.png)
![image](https://user-images.githubusercontent.com/5855327/125080166-c77cf880-e0c4-11eb-91d0-828959e3d025.png)

**Comment by iamromeo** [comment]
This is a user defined parameter :) if you wish to change the colour of the labels to something darked please go right ahead :) 
You can do it from your Manuscript's configuration :)
