### ISSUE TITLE
Random generator BBCode does not work in journal entries

### ISSUE THREAD

**Issue by kjanowski** [worldanvil/worldanvil-bug-tracker#418]
**World Anvil Username**:
Kaleidechse

**Feature**: Journal Entries

**Related URLS**
https://www.worldanvil.com/dashboard/user/post/c6fe7894-66a0-47fa-a025-7c5645bc40ee
https://www.worldanvil.com/random-generator/generic-prophecy-kaleidechse

**Describe the Issue**
The BBCode embed for a random generator does not work properly in journal entries. When the "generate" button is clicked, the browser window is cleared and displays the raw HTML code for the element containing the generator result.

**To Reproduce**
1. Go to the page of a publicly available random generator.
2. Click on "copy into article" on the right.
3. Go to your author page.
4. Create a new journal entry and embed the copied BBCode.
5. Publish the journal entry.
6. Click on the "generate" button embedded in the journal entry.
7. See the browser tab's content get replaced by the raw HTML code for an orphaned element.

**Expected behavior**
The random generator's result should be displayed within the journal article.

![journal_RG-button](https://user-images.githubusercontent.com/8113752/125113396-e8efdb80-e0e8-11eb-9b67-05411e93aca0.png)
![journal_RG-result](https://user-images.githubusercontent.com/8113752/125113410-ed1bf900-e0e8-11eb-9d46-aa489e1a8123.png)

**Comment by iamromeo** [comment]
I MIGHT have added this - we will see when it's deployed :)

**Comment by iamromeo** [comment]
It works now!
