### ISSUE TITLE
Cannot delete World. Get a 404 instead

### ISSUE THREAD

**Issue by Lenosallose** [worldanvil/worldanvil-bug-tracker#419]
**World Anvil Username**: Lenosallose

**World Title**: Alézun'Teran. 

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/alezun-teran-lenosallose

**Describe the Issue**
When I click Delete World in Configuration, I get sent a 404. I do not know why this is so.

**Expected behavior**
I expected the world to simply be deleted, as has happened previously with other worlds.

**Comment by iamromeo** [comment]
Does this world have any editors / subscribers? have you tried deleting th em

**Comment by Lenosallose** [comment]
It was the subscriber group, yes. When I deleted it, I managed to delete the world. Thank you.

**Comment by iamromeo** [comment]
Amazing - happy to hear it
