### ISSUE TITLE
To-do items created through the use of the purple button

### ISSUE THREAD

**Issue by MGatta** [worldanvil/worldanvil-bug-tracker#42]
**World Anvil Username**: MGatta

**Feature**: To-do list

**Describe the Issue**
To-do items are created when making pages with the purple button.

**To Reproduce**
1. Go to the purple button.
2. Write a title and select a template
3. Click create article
4. See new to-do list item

**Expected behavior**
No new to-do items when using the purple button.

**Screenshots**
![image](https://user-images.githubusercontent.com/80196715/110244225-fd1aa500-7f5d-11eb-85eb-0c1011637e23.png)
New articles were created, one as a draft, one as a complete item. Both resulted in to-do list items:
![image](https://user-images.githubusercontent.com/80196715/110244362-ad88a900-7f5e-11eb-81a4-32344524652b.png)
![image](https://user-images.githubusercontent.com/80196715/110244365-b1b4c680-7f5e-11eb-84b3-8189ee26b71a.png)

**Comment by iamromeo** [comment]
Will be deploying later today
