### ISSUE TITLE
Unfollow own world

### ISSUE THREAD

**Issue by Hertzbube** [worldanvil/worldanvil-bug-tracker#420]
**World Anvil Username**: Hertzbube

**Screenshot**
![grafik](https://user-images.githubusercontent.com/80397163/125171833-aac0ed80-e1b6-11eb-912f-19770606602c.png)

**Link** (Here you can find myself as my own world's follower)
https://www.worldanvil.com/w/dvds-hertzbube/followers

**Describe the Issue**
I accidentally followed my own world by clicking on a follower button generated by the BBCode. Now I can't unfollow her because the option to do so doesn't appear on the 'followed worlds' pages.

**To Reproduce**
1. Add BBCode for follower Button
2. Click on it
3. Visite you're page where your world followers get listed.

**Comment by iamromeo** [comment]
You can unfollow your world from any article in your world but I also added this to the list of worlds. It will be deployed at a later date.
