### ISSUE TITLE
Updated Fate Accelerated character sheet template

### ISSUE THREAD

**Issue by Snake-Venom** [worldanvil/worldanvil-bug-tracker#421]
Hi, I made the FAE character sheet template (2020) last year and have now spent some time improving it and wish to see it implemented.
The main changes are:
- significantly better support for screen readers
- a few visual improvements

These changes are made while maintaining backwards compatibility with the 2020 version by using the same variable names and functionality, so this should be a drop-in replacement.

Sheet demonstration: [https://www.worldanvil.com/sheet/774473/view](url)
Embedded sheet demonstration [https://www.worldanvil.com/w/miscellaneous-creations-snakevenom/a/fae-character-sheet-2021-demo-article](url)

**Comment by iamromeo** [comment]
Hey Bud, just to clarify we want to add this in FAE as the 2021 version and get the previous one down?

**Comment by Snake-Venom** [comment]
Yes,
add it as the 2021 template version, remove the 2020 version.

If doing that also makes all 2020 character sheets use the 2021 template, then you can ignore the following paragraph.
I do not know how WA handles character sheet data, but if it is stored alongside with a flag/tag that indicates which character sheet template is being used, then that tag can safely be updated to use the 2021 version. This is because the aforementioned backwards compatibility.

**Comment by iamromeo** [comment]
Done
