### ISSUE TITLE
Wrapping a link around a 'nolink' image creates a phantom link

### ISSUE THREAD

**Issue by iamthetot** [worldanvil/worldanvil-bug-tracker#422]
**World Anvil Username**: iAmTheTot

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/aedelor-iamthetot/a/human-species

**Describe the Issue**
Wasn't entirely sure what to title it, hope it was accurate enough. It seems to be that when you put an image bbcode inside of a url bbcode, the rendered html on the page includes a mysterious phantom link that I can't really explain where it's coming from.

**To Reproduce**
Create an article.
Place an image bbcode into the vignette with the "nolink" parse.
Place that image bbcode inside of a url bbcode.
Preview the article and inspect the html.

**Expected behavior**
It's not really messing anything up at the moment, it seems? So I'm not sure if it's really doing harm it just seems really odd and I thought I would report it.

**Screenshots**
The BBCode:
![3hXyWiX](https://user-images.githubusercontent.com/53080404/125180580-dfce3f80-e1b8-11eb-9da6-3e78d98feb7f.png)

The part of the page as it renders (obviously cannot see phantom link here, just including for reference):
![3e505Q2](https://user-images.githubusercontent.com/53080404/125180590-e65cb700-e1b8-11eb-9de4-21c5d28fcad5.png)

The HTML per page inspect, arrow pointing to mysterious link:
![3yLLfFW](https://user-images.githubusercontent.com/53080404/125180596-fd030e00-e1b8-11eb-820a-64c839dab687.png)

**Comment by iamromeo** [comment]
Not a bug :)
