### ISSUE TITLE
Issue with Genesys System, Archetypes Statblock Templet

### ISSUE THREAD

**Issue by TEsrafa** [worldanvil/worldanvil-bug-tracker#423]
**World Anvil Username**: Bloodgarde
**Discord Username**: TEsrafa#4151

**World / Campaign / RPG Character / Manuscript Title**:  Does Not Apply

World Theme: Deven Rue (This maybe relevant to issue 2. After testing Theme does not seem to matter. Leaving the data anyway, but the problem persisted across multiple themes.)

RPG System: Genesys

**Feature**: Archetypes Statblock Templet

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Two Issues...

Issue 1: The templet requires you enter a characteristic value of 2 or higher in order to save the stat block. This is in error. Many of the RAW Archetypes have at lease one characteristic of 1. The correct values for characteristics should be a value between 1 and 5 as per RAW you can not have a characteristic outside those values for an Archetype. (This use to work properly by the way, I have several previously saved stat blocks with a characteristic of 1.)

**To Reproduce**
1. Create or Go to any Genesys System, Archetype Statblock.
2. Completely fill it out using a value less then 2 (aka 1) for any characteristic.
3. Attempt to Save the Statblock.

**Expected behavior**
I expect to be able to duplicate RAW by having characteristics of 1 in my Archetypes. 

**Screenshots**
Not sure this is needed, please contact me if it is. 

Issue 2: The Genesys System Archetypes Templet has a blank for Special Abilities. When displayed as apart of a article, these special abilities do not appear in the statblock. (Unlike issue 1, this has never worked properly so I have simply added the special abilities as text below the stat block as a work around.)

**To Reproduce**
1. Create or Go to any Genesys System, Archetype Statblock.
2. Completely fill it out with any text in the "special ability" entry box.
3. Successfully Save the Stat Block.
4. Copy the link for the stat block.
5. Paste the link into an article and save it.
6. View the Article.
4. See error, the text entered in the special ability area is omitted from the stat block.

**Expected behavior**
The text entered into the special ability prompt of Genesys System, Archetype Statblock should be displayed below the starting experience line of the stat block when used as apart of an article. 

**Screenshots**
[https://1drv.ms/u/s!AjM6sddeVvLKg7w_SqwP8E2iBZEQNA?e=l0syin](https://1drv.ms/u/s!AjM6sddeVvLKg7w_SqwP8E2iBZEQNA?e=l0syin)

**Comment by iamromeo** [comment]
System sheets are created by the community they are not part of World Anvil's development remit. 
I will inform the creator but that is as far as we can go with this bud :)

**Comment by iamromeo** [comment]
Response from developer:

Issue one is fixable.
Issue two will look into.
But no timeframe at all.

**Comment by iamromeo** [comment]
Closing this but will update the task with new information when it comes
