### ISSUE TITLE
Pictures disappearing from articles

### ISSUE THREAD

**Issue by erica447788** [worldanvil/worldanvil-bug-tracker#424]
Username: Girlhead

World:Alloria/ Campagin: For Alloria/ Article: links below 
Feature: NPCs 

**Related URLS** 
**Article**
https://www.worldanvil.com/w/alloria-girlhead/a/-kimnola-mudtoe-person
**Picture**:
https://www.worldanvil.com/i/2164411

**Article**
https://www.worldanvil.com/w/alloria-girlhead/a/grath--person
**Picture**:
Gone.  I have no idea and don't think I would have possibly deleted it.

**Article**:
https://www.worldanvil.com/w/alloria-girlhead/a/-alexander-thisledown-person
**Picture**:
https://www.worldanvil.com/i/1297005

**Article**:
https://www.worldanvil.com/w/alloria-girlhead/a/-lane-thisledown-person
**Picture**:
https://www.worldanvil.com/i/1297071

**Describe the Issue**
The pictures from these articles randomly disappeared from their NPC articles, but they are still in the gallery

**To Reproduce**
1. Go to the link for article, see there is no picture
2. Go to image link- you can see it's still in the gallery

**Expected behavior**
I think I described it above.  I am beyond frustrated with all of the issues I've had with this tool lately. I recently lost hours of work due to the way the tool functions, I have been having a ton of trouble with the editor, and now things are randomly disappearing on me.  

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
I am really sorry but I cannot replicate this issue and all the links above are private links

**Comment by iamromeo** [comment]
Where are those images supposed to be in the article, how are they embedded

**Comment by erica447788** [comment]
Image 1 is how I uploaded these images- I dragged and dropped them into
the NPC profile.
Image 2 is an example of what these articles looked like. The Image was at
the top left.

**Comment by iamromeo** [comment]
I am sorry but which images are you reffering to?
