### ISSUE TITLE
Unwanted Bold lettering

### ISSUE THREAD

**Issue by LoneGirl88** [worldanvil/worldanvil-bug-tracker#425]
**World Anvil Username**: UnknownWriter88

**World / Campaign / RPG Character / Manuscript Title**: Andorra

**Feature**: none

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/andorra-unknownwriter88/a/dwarf-species?preview=true

**Describe the Issue**
Lettering becoming bold when it doesn't need to be

**Comment by iamromeo** [comment]
This article is private and the issue cannot be reproduced also the description given is not sufficient to debug in any way
