### ISSUE TITLE
Previewer Scroll problem

### ISSUE THREAD

**Issue by Nogone** [worldanvil/worldanvil-bug-tracker#426]
**World Anvil Username**:
Happypill
**World / Campaign / RPG Character / Manuscript Title**:
Haturna (?)
**Feature**: 
Previewer (alt + enter)
**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When the previewer encounters enough articles (so that the interface needs to scroll) all articles are not visible, the last one gets clipped right above the text.

**To Reproduce**
1. Make something like 8 articles that can be found with the same search in previewer
2. Open up previewer
3. Scroll down

**Expected behavior**
What I expect is to be able to see the last article.
(when the search becomes specific enough the article is visible)

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Screenshot 2021-07-12 at 09 37 44](https://user-images.githubusercontent.com/70641641/125249401-7dc72480-e2f5-11eb-8367-7d7d3a48ff92.png)

**Comment by iamromeo** [comment]
The previewer has a bar appearing and also can be expanded downwards if that is the issue. I see what you mean but this is not necessarily a bug, it's an issue with calculaations on your screen size :) 

I will have a look, but simply enough until then you can drag it from the lower right corner when this incurs

**Comment by iamromeo** [comment]
Moved to dev check list

**Comment by Nogone** [comment]
Tried with a resize but it "only" moves everything, leaving the bottom clipped. It works for having a bigger amount of articles but the problem seems to still be a problem with "big inventories"
pic1 and pic2 have the same crop on the last article, and changing size when at the bottom only moves everything down
![Screenshot 2021-07-13 at 15 02 08](https://user-images.githubusercontent.com/70641641/125456583-294ec4d4-17fc-44fc-966b-5da642e45fd6.png)
![Screenshot 2021-07-13 at 15 03 06](https://user-images.githubusercontent.com/70641641/125456613-6b28548a-7374-46f0-bcb2-8cf60af20b57.png)
