### ISSUE TITLE
RPG Request: The Way Home

### ISSUE THREAD

**Issue by ptp0005** [worldanvil/worldanvil-bug-tracker#427]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the request will not be considered.

**The Way Home**:
**The Way Home** (Name under which it should be listed on World Anvil):
**prestontpound**:

**https://www.drivethrurpg.com/product/290118/The-Way-Home**:

**Logo Image Link**:

**Logo Usage Terms (URL)**:

**Comment by iamromeo** [comment]
I am sorry but if your account on World Anvil is actually **ptp0005** you are not a Grandmaster and cannot request the system to ba added.
