### ISSUE TITLE
double the

### ISSUE THREAD

**Issue by tikihut** [worldanvil/worldanvil-bug-tracker#428]
**World Anvil Username**:
Tikihut
**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
the the

**To Reproduce**
1. Go to your campaigns without a world selected

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/26888945/125364632-7412e080-e338-11eb-8b0a-bce8a570fa11.png)

**Comment by iamromeo** [comment]
Thank you for reporting!
