### ISSUE TITLE
Article Expanded View messes with quick edits for other articles in category

### ISSUE THREAD

**Issue by Nogone** [worldanvil/worldanvil-bug-tracker#430]
**World Anvil Username**:
Happypill

**World / Campaign / RPG Character / Manuscript Title**:
"Hatturna"? -world?

**Feature**: 
Article Expanded view

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When using the expanded view, the new layout changes the current vinette editing window and going back makes these changes permanent, when this is done and you look at another article, the vinette does not come up, although the "shortcuts" for bold and italic and so forth DO.

**To Reproduce**
1. Go to an article
2. Click on expand view
3. Scroll down to close expanded view by clicking expanded view again
4. Click on another article
5. That is it?

**Expected behavior**
Expected it to not duplicate the vindow, and not to change it either, since you need to go to another category to fix it.

**Screenshots**
![Screenshot 2021-07-13 at 17 56 26](https://user-images.githubusercontent.com/70641641/125485594-d1f20a9e-b927-4eed-b236-104cc865a95f.png)
![Screenshot 2021-07-13 at 17 56 33](https://user-images.githubusercontent.com/70641641/125485613-ec25d610-8cc0-4122-9c6e-4ea8ae98f4ea.png)
![Screenshot 2021-07-13 at 17 56 40](https://user-images.githubusercontent.com/70641641/125485623-2acef197-2e13-4740-92eb-038c5a6e2138.png)
![Screenshot 2021-07-13 at 17 56 43](https://user-images.githubusercontent.com/70641641/125485638-04d98ad8-729d-46f1-b516-ed6fbce6d828.png)

**Comment by iamromeo** [comment]
Damn I forgot to remove this - the expand should not be there any more - Will take care of this
