### ISSUE TITLE
Vampire: The Masquerade 5e

### ISSUE THREAD

**Issue by MattClementson** [worldanvil/worldanvil-bug-tracker#431]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name (RPG SYSTEM)**: Vampire: The Masquerade 5e
**List Name** (Name under which it should be listed on World Anvil): Vampire: The Masquerade 5e
**World Anvil Username**: MClementson

**Website**:

**Logo Image Link**:

**Logo Usage Terms (URL)**:

**Comment by iamromeo** [comment]
Vampire 5e is already present under New World of Darkness
