### ISSUE TITLE
Alien rpg

### ISSUE THREAD

**Issue by cmgardone89** [worldanvil/worldanvil-bug-tracker#432]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name (RPG SYSTEM)**: Alien
**List Name** Alien 
**World Anvil Username**: gardonecory89

**Website**:

**Logo Image Link**:

**Logo Usage Terms (URL)**:

**Comment by iamromeo** [comment]
Alien RPG by Free League is already in the list of RPGs
