### ISSUE TITLE
Campaign Plots Tree does not respect Plot Position/Weights

### ISSUE THREAD

**Issue by nonplayer** [worldanvil/worldanvil-bug-tracker#433]
**World Anvil Username**: nonplayer

**World / Campaign / RPG Character / Manuscript Title**: "Palladium: The Brothers Grim"

**Feature**: Plots

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/heroes/campaign/plot/list

**Describe the Issue**
The list of Plots on the Campaign Plots Tree does not respect the assigned Position/Weight numbers of the plots.

**To Reproduce**
1. Go to Campaign Plots
2. Add multiple top-level plots.
3. Edit the plots to assign weights.
4. List does not adjust to assigned weights.

**Expected behavior**
The plot tree should respect assign weights of plots at all levels, including the top.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

![image](https://user-images.githubusercontent.com/5161177/125668223-c38667e4-036b-40e5-b511-0deff060348e.png)

![image](https://user-images.githubusercontent.com/5161177/125668302-fd724e4b-9846-4a6d-b146-4645e0394812.png)

![image](https://user-images.githubusercontent.com/5161177/125668341-74d3b9d3-14f3-4a80-9e5b-4d0470be0260.png)

**Comment by iamromeo** [comment]
Hey @nonplayer I will have a look for you on that. Is this the campaign manager plots page?

**Comment by iamromeo** [comment]
Fixed will be deploying later on today

**Comment by nonplayer** [comment]
Yes, this is in the Campaign Manager Plots page. I just logged in to check the change. I'm not sure if you rolled out the fix, because I'm not seeing the ordering changed at all. There is a new change, however: it looks like now the assigned weight is being printed on screen as part of the plot title:
![image](https://user-images.githubusercontent.com/5161177/125972578-2a5a5820-cd49-4e79-b5fa-4744c6429525.png)

That's the only change I'm seeing so far. Thanks for looking.

**Comment by iamromeo** [comment]
Thank you for letting me know - I have checked it over and there was indeed an issue with top level plots. I will deploy the fix later on today

**Comment by nonplayer** [comment]
Looks good now! Thanks!
