### ISSUE TITLE
missing links in codex menu

### ISSUE THREAD

**Issue by Kal-Verahda** [worldanvil/worldanvil-bug-tracker#434]
**Kal Verahda**:

**Arisdatha**:

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Some links don't work on the menu on my world

**To Reproduce**
1. Click on a category in the menu
2. hover over links
3.observe that some links work and some show as plain text

**Expected behavior**
Expected all links to work.

**Screenshots**
https://gyazo.com/56029b2c1f516b6223bb7f12312238e9

**Comment by Kal-Verahda** [comment]
In playing with the menu I discovered that if another menu item is also expanded, the links in the offending category work properly, but if the offending category is the only one expanded then it doesn't work properly.

**Comment by iamromeo** [comment]
I cannot be certain but it looks it might have to do with the extremely odd article title on top of them. Can you please try to normalize that title  and let me know if it works.

**Comment by Kal-Verahda** [comment]
> I cannot be certain but it looks it might have to do with the extremely odd article title on top of them. Can you please try to normalize that title and let me know if it works.

I am not sure what you mean by article title.  I haven't used any CSS to change anything.  The only thing I have changed is what is available to change in the world style editor.  I haven't used CSS to alter the template, either.

**Comment by Kal-Verahda** [comment]
> I cannot be certain but it looks it might have to do with the extremely odd article title on top of them. Can you please try to normalize that title and let me know if it works.

I think I see why you can't reproduce it.  I am not sure if I made myself clear.  I am not speaking of the links on the homepage itself but the menu that appears when you click on the menu icon "widget," for lack of a better word, at the far left of the site.

**Comment by iamromeo** [comment]
It is the same code that produces this - but with no access to your world I cannot really check, have you changed the title of the article above them?

**Comment by Kal-Verahda** [comment]
> It is the same code that produces this - but with no access to your world I cannot really check, have you changed the title of the article above them?

What title?  Are you referring to the cover image or what?  I added no title. The title only uses the name of the world as I created it.  In fact, I would prefer to get rid of the title because a cover image with the logo of the world in it followed by the name of the world in text is a bit redundant, but I am stuck with the template formatting as it is.

**Comment by iamromeo** [comment]
I am referring to the article called The Vastal  with the <.... > in it which looks like an HTML tag

**Comment by Kal-Verahda** [comment]
> I am referring to the article called The Vastal with the <.... > in it which looks like an HTML tag

Thank you for specifying what you were talking about.  That is a pronunciation guide. I had to use the "<" and ">" because brackets and parentheses are not allowed in the title of the article.  I will try removing them now that I know what you were talking about.

**Comment by Kal-Verahda** [comment]
> I am referring to the article called The Vastal with the <.... > in it which looks like an HTML tag

I removed the pronunciation.  Still did not fix it.

**Comment by Kal-Verahda** [comment]
> > I am referring to the article called The Vastal with the <.... > in it which looks like an HTML tag
> 
> I removed the pronunciation. Still did not fix it.

I am going through the menu and finding all "<" and ">" symbols and removing them.

**Comment by Kal-Verahda** [comment]
> I am referring to the article called The Vastal with the <.... > in it which looks like an HTML tag

I have gone through the menu and removed all "<" and ">" symbols but the bug still persists

I also just thought of the possibility that the browser I am using may be relevant. I am using Microsoft Edge.

**Comment by iamromeo** [comment]
oh dear god yes - please try it on a modern browser. World Anvil does not support Edge. I had no idea
Try Chrome, FIrefox Opera, or even Safari

@Kordishal we might have to add the question "Browser" and "Platform" on the template

**Comment by Kal-Verahda** [comment]
> oh dear god yes - please try it on a modern browser. World Anvil does not support Edge. I had no idea
> Try Chrome, FIrefox Opera, or even Safari
> 
> @Kordishal we might have to add the question "Browser" and "Platform" on the template

The problem is on Chrome too. Except that the third menu item of the category in question is now active while the 4th and 5th are still dead.

And as to supporting Edge. Wouldn't it be advisable to include it in your testing, given that Edge is a Microsoft product and comes included with Windows? The common normy generally has no preference and uses what is readily available (which is why I use it for my world since most people use it).

**Comment by iamromeo** [comment]
I will need to have a better look at your world, I will need you to give me more detais in regards to which categories are causing this and I will need access to your world to see if it can be replicated. 
Can you please add **Dimitris** as a co-author. 

In regards to Edge, no sadly, supporting an old browser that refuses to come into alignment with modern standards is not something I can use time towards. I am single developer and less than 4% of the internet uses it https://gs.statcounter.com/browser-market-share

**Comment by Kal-Verahda** [comment]
> I will need to have a better look at your world, I will need you to give me more detais in regards to which categories are causing this and I will need access to your world to see if it can be replicated.
> Can you please add **Dimitris** as a co-author.
> 
> In regards to Edge, no sadly, supporting an old browser that refuses to come into alignment with modern standards is not something I can use time towards. I am single developer and less than 4% of the internet uses it https://gs.statcounter.com/browser-market-share

Done.

I added you to the Author list

In Microsoft Edge:

submenu under Technology: last three items (when History AND Geography are also expanded)

submenu under Myths/Folklore/Legends: 3rd, 4th, and 5th (when Geography AND Technology are also expanded)

category Biographies (when Technology AND Myths/Folklore/Legends are expanded)

submenu under Fauna: all but Chlorophyll and Telv (when Fauna is also expanded)

submenu under The Warrior Heritage: The Importance of The Warrior Heritage and Rules Of Battle (when Flora is also expanded)

submenu under Crime and Corruption: the 3rd, 4th, and 5th (when no other category is expanded, inverted when The Warrior Heritage is expanded)

submenu under Social Customs: subcategory Clothing and menu item Disclaimer (when no other category is expanded, no problem when Crime and Corruption is also expanded)

category Military (when no other categories are expanded, no problem when Social Customs is expanded)

I tried to be thorough, but trying every possible combination would be futile and time-consuming

Chrome:

To make a long post short(er), the pattern seems to be similar to that of Edge, but the dead links vary for each instance

**Comment by Kal-Verahda** [comment]
> I will need to have a better look at your world, I will need you to give me more detais in regards to which categories are causing this and I will need access to your world to see if it can be replicated.
> Can you please add **Dimitris** as a co-author.
> 
> In regards to Edge, no sadly, supporting an old browser that refuses to come into alignment with modern standards is not something I can use time towards. I am single developer and less than 4% of the internet uses it https://gs.statcounter.com/browser-market-share

I think Edge was the culprit. I took Edge off my taskbar and am only running Chrome at the moment.  I am unable to reproduce the problem without Edge running as well.

**Comment by Kal-Verahda** [comment]
> > I will need to have a better look at your world, I will need you to give me more detais in regards to which categories are causing this and I will need access to your world to see if it can be replicated.
> > Can you please add **Dimitris** as a co-author.
> > In regards to Edge, no sadly, supporting an old browser that refuses to come into alignment with modern standards is not something I can use time towards. I am single developer and less than 4% of the internet uses it https://gs.statcounter.com/browser-market-share
> 
> I think Edge was the culprit. I took Edge off my taskbar and am only running Chrome at the moment. I am unable to reproduce the problem without Edge running as well.

Edit: Just as I was celebrating the death of the issue I just now found that in the category: Crime And Corruption submenu the 3rd-5th links are dead when only Crime and Corruption is expanded.

**Comment by iamromeo** [comment]
I am really sorry but without having a way to actually reproduce this it's really hard to help you. Unless you can give me access to this world I cannot do much more to help you. 

My username is Dimitris, add me as a co-author or subscriber and give me the exact reproduction steps so I can check

**Comment by Kal-Verahda** [comment]
> I am really sorry but without having a way to actually reproduce this it's really hard to help you. Unless you can give me access to this world I cannot do much more to help you.
> 
> My username is Dimitris, add me as a co-author or subscriber and give me the exact reproduction steps so I can check

I did the first time you requested.  https://gyazo.com/fcb3df2e2e3243863aeb9a48963b8a29

**Comment by iamromeo** [comment]
Amazing thank you - let me have a look

**Comment by Kal-Verahda** [comment]
> Amazing thank you - let me have a look

BTW, I don't know if this makes a difference, but even when I'm logged out the bug is still there, although the affected links vary from when I'm logged in.  Why no one else seems to have the same problem is a mystery to me.

**Comment by iamromeo** [comment]
https://user-images.githubusercontent.com/660175/126103571-e780e30e-a6f1-4860-a5fd-d16b5201a84e.mov

I am really sorry but I cannot reproduce this. I have in fact tried this in both CHrome and Firefox. 
This is starting to look like a local system issue. Do you have someone else, like your players of SO that can give it a try from their own computer to have a 3rd opinion? If not, can you add "Soullink" temporarily in the world so they can also check @Kordishal

**Comment by Kal-Verahda** [comment]
>  Screen.Recording.2021-07-19.at.07.37.56.mov 
> I am really sorry but I cannot reproduce this. I have in fact tried this in both CHrome and Firefox.
> This is starting to look like a local system issue. Do you have someone else, like your players of SO that can give it a try from their own computer to have a 3rd opinion? If not, can you add "Soullink" temporarily in the world so they can also check @Kordishal

I added Soullink, too.   And, btw, it doesn't happen with ALL of them expanded. Never has for me. In fact, expanding them all is the only sure remedy for the bug.  Expanding a second category sometimes remedies it, sometimes not, and sometimes only changes which items are affected.  The combinations vary.  I don't know how to describe it any clearer than I did in my previous post.  

Ok, here is one that happens every time for me when I am logged in.  When Crime and Corruption is the ONLY category expanded, the third, fourth, and fifth submenu items under it are dead.   When The Warrior Heritage above it is expanded ALSO, the submenu items switch from third, fourth, and fifth being affected to only the first and second being affected.

**Comment by Kal-Verahda** [comment]
Also, the bug does not happen on the page itself.  It is the little menu "widget" at the side of the page, not the page itself.

**Comment by Kordishal** [comment]
I could reproduce the issue. However, it only happens when zoomed in a lot and only after opening & closing certain things. And it is not consistent at all. I cannot figure out what the issue is exactly. 

My guess would be that there is some kind of an invisible element that is covering some links. Every time I try to inspect the links which do not work move up.

And it only happens in the sidebar navigation. So potentially a z-index issue.

**Comment by Kal-Verahda** [comment]
Thank you! That proves I'm not losing my mind!

**Comment by iamromeo** [comment]
Any zooming of the browser and all bets are off - simply enough the browser decides to rewrite parts of the page based on its own rules when this happens. There is no way for me to control it

**Comment by Kal-Verahda** [comment]
> Any zooming of the browser and all bets are off - simply enough the browser decides to rewrite parts of the page based on its own rules when this happens. There is no way for me to control it

Ok, I guess I will have to be satisfied with that answer.  However, I rarely use the zoom feature. In only the rarest of circumstances do I ever use anything but 100% zoom.
