### ISSUE TITLE
Missing On-the-fly CSS Editor

### ISSUE THREAD

**Issue by IbbyWondrous** [worldanvil/worldanvil-bug-tracker#436]
**World Anvil Username**: IbbyWondrous

**World / Campaign / RPG Character / Manuscript Title**: Smallscale

**Feature**: CSS

**Describe the Issue**
I've been trying to find the 'On-the-fly' editor for one of my friend's worlds, but it's missing. She's a grandmaster and on the two example worlds, I'm a co-author, and should have access to it in theory, and I'm still able to use the 'Styling' editor in the world settings to do it just fine, but the button in presentation mode is just gone. It's only like that on this world though, as it's still there on our other world.

I have the exact same permissions on both worlds. Both worlds are owned by the same person. The only difference is one is an older world, where as this was made a day after Summercamp started. The button has been missing since it's creation.

**Screenshots**
![image_2021-07-15_101835](https://user-images.githubusercontent.com/87488482/125813128-9b799c17-cd81-462f-9b45-3d219797efdc.png)
![image_2021-07-15_101845](https://user-images.githubusercontent.com/87488482/125813146-8da8e9f9-5170-4937-a2d9-29b384b9fe31.png)

**Comment by iamromeo** [comment]
IbbyWondrous you are not a guild member and you do not get access to CSS editing unless you are in any world

**Comment by IbbyWondrous** [comment]
> IbbyWondrous you are not a guild member and you do not get access to CSS editing unless you are in any world

I literally just said the world I am on was made by, and belongs to a Grandmaster user, and I'm able to access the feature in both other worlds of this same set up, AND in the stylization editor on the world in question. It's very specifically the 'On-the-fly' editor that isn't working.

Even the helpers in the discord told me that it's a glitch and I should report it as a bug. So here I am.
