### ISSUE TITLE
Writing with a pen doesn't trigger save

### ISSUE THREAD

**Issue by Nahbyr** [worldanvil/worldanvil-bug-tracker#438]
**World Anvil Username**: Nahbyr

**Feature**: 
Writing with a pen in Windows Ink does not trigger the auto-save.

**Describe the Issue**
I use a pen and tablet to write my stuff and I just noticed that it doesn't trigger the keyup event. So if it doesn't trigger then it doesn't save.

**To Reproduce**
1. Open Windows Ink
2. Write something
3. No auto-save

**Expected behavior**
You'd expect things to be saved if you see text appear in your editor.

**Comment by iamromeo** [comment]
oh my well... this is most certainly not a bug. This is simply an unsupported feature, that is certainly the first time I ever heard of this - I have no idea how to reproduce this or how microsoft decided that this would work

**Comment by Lyraine-Alei** [comment]
I have used a pen tablet on web browser, but of the browsers I've used, Microsoft only recognized my pen usages in Edge.

And WA doesn't support Edge, so I had completely forgotten about this being a thing to consider.

(not replicating the bug, just adding some details I've found in past usage)

**Comment by Nahbyr** [comment]
Hi Lyraine

I've only recently started using a pen tablet for my day to day things. But so far I've only had one issue in Chrome and that is that it doesn't always open up the box to write in. It will open it up 80% of the time. I don't think I'm supposed to close it though. Not sure, noob user atm.

Not exactly sure how Windows does it. It for sure doesn't trigger a keyUp.
Also, after a quick Google I can't find anything on the usual forums.
I'm always happy to help with anything you need if you guys want to look into implementing this. Also fine with no implementation. I just figured I'd report it and let you people decide.

PS: I wish I could convince my boss not to support Edge. I still have users using IE...
