### ISSUE TITLE
Changing world private visibility issue

### ISSUE THREAD

**Issue by Bednaz98** [worldanvil/worldanvil-bug-tracker#439]
**World Anvil Username**: Bednaz

**World / Campaign / RPG Character / Manuscript Title**: The Unorthodox system

**Feature**: Changing world from private to public

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A few days ago I tried accessing my world that was private when I had a world anvil account. My account expired and I needed to access the world for some notes. I tried clicking the button to change the world from private to public. When I did, it did not work. Instead, it took a while to load and then give me a 404 error and message saying “ Thus you have reached the end of this world.” I contacted the support email and Phoebe said she received it with her team and suggested I come here to report the issue. I just checked today and my world is no longer displayed for me to switch under the owned worlds tab. However, it is still displayed on the left sidebar under worlds.

**To Reproduce**
1. Go to 'Owned'
2. Click on 'make public'
3. 404  error

**Comment by iamromeo** [comment]
Hello there @Bednaz98 can you please give me some more information about the world you did not specify which world it is

**Comment by Bednaz98** [comment]
Hey @iamromeo, sorry it took a bit to get back to you. The world is titled "the unorthodox system." I have been using it both for a campaign setting and also for a place for my friends to see a TTRPG I have been working on to go along with it. So I gave it that as a title.

**Comment by iamromeo** [comment]
ummm this world is already public @Bednaz98
