### ISSUE TITLE
Saving changes on an extended profile of a player's character (cast) leads to 404

### ISSUE THREAD

**Issue by zarazandra** [worldanvil/worldanvil-bug-tracker#440]
**World Anvil Username**:
zarazandra

**World / Campaign / RPG Character / Manuscript Title**:
Salla (RPG-Character)

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):
![image](https://user-images.githubusercontent.com/70195103/126020586-a577a268-7a39-435e-87fc-6bf17d58c876.png)
![image](https://user-images.githubusercontent.com/70195103/126020598-fc3b2eaa-48b2-4f94-a058-99cd89c03a37.png)

**Describe the Issue**
Every time I try to save the extended profile's page of the character "Salla" on the campaign Das Jahr des Feuers (custom) in the world "Das Schwarze Auge" (both done by me) , I get a 404. This occurs if I'm doing major changes or no changes at all - the input itself therefore causes no issue.  

The character is mine, I am the player as well as the GM. So far this only occurs on this very character - not on any other character (tried it with all of mine and had no complaints about my players about it). 

There are no odd symbols etc, as far as I can see.  All inputfields inside the "extended profile" are empty, since this error occurs since I created her. 

Saving the basic profile and all other features work like a charm. 

**To Reproduce**
1. Open the character on the protagonists-page inside the campaign
2. Click on 'activate', then 'edit'
3. Go to 'extended profile'
4. Do changes or not, doesn't matter
5. Click on 'save changes'
6. See a beautiful dragon, which tells me that I have reached the end of this world. :) 

**Expected behavior**
The changed data is saved without getting a 404

**Screenshots**
see above

**Comment by iamromeo** [comment]
Can i please have a public URL and also, what are you trying to enter when this happens? 
Also can you show me the basic details of the character? In some cases this is related to the length of some fields

**Comment by zarazandra** [comment]
Sure, will do that later today.

Dimitris Romeo Havlidis ***@***.***> schrieb am Sa., 17. Juli
2021, 05:25:

**Comment by zarazandra** [comment]
https://www.worldanvil.com/hero/8b0d2d17-c589-472c-abdd-e2aeb610541c

I wanted to fill some blanks in the extended sheet, like Introduction or species. But as I said, even when I don't do anything and try to save, it's leading to 404. 

basic details: 
![image](https://user-images.githubusercontent.com/70195103/126037122-98932eb8-a997-48df-8829-35b95f474636.png)

**Comment by zarazandra** [comment]
https://youtu.be/BAPCaZBUXF8
that's the whole thing via screencapture

**Comment by iamromeo** [comment]
Your issue is that your shortbio is absolutely massive. 
this is because your browser overrides the rules set
this should not be onger that 255 characters. 
Remove that block from there save then go back to extended and check

**Comment by zarazandra** [comment]
Ahh! I removed the text and voila, it worked! Didn't seem so massive to me. Maybe showing a max-sings-warning would help?

thanks!

**Comment by iamromeo** [comment]
@zarazandra it is meant to - something really fucky is going on there - it's in my list
