### ISSUE TITLE
World Summary not Scrolling

### ISSUE THREAD

**Issue by CTKitsune** [worldanvil/worldanvil-bug-tracker#441]
**ChaosTearKitsune**:

**Isidoro/Tarin**:

**Feature**: 

**Related URLS** 
![image](https://user-images.githubusercontent.com/87584256/126048623-4929f00f-053c-4dc8-b9a5-ca7510ac334a.png)

**Describe the Issue**
When working with any window size other than full window (maximized) World Summary will not scroll. There is no scrollbar available to use and as a result depending on window size not all article templates/website features are visible.

**To Reproduce**
1. Go to your world summary/Dashboard
2. Make your window anything but full screen (click the maximize/window button beside the X and minimize, and drag/alter window sizing)
3. Attempt to scroll/view  anything besides what is on screen.

**Expected behavior**
When viewing World Anvil, a scrollbar should be visible and available to use regardless of the window size. This can cause problems with viewing or alternate screen layouts.

**Comment by iamromeo** [comment]
Not a bug, works as intended
