### ISSUE TITLE
Manuscript editor colour changes creates nested spans

### ISSUE THREAD

**Issue by Nahbyr** [worldanvil/worldanvil-bug-tracker#443]
**World Anvil Username**: Nahbyr

**Feature**:  Editor in manuscripts

**Related URLS** 
![image](https://user-images.githubusercontent.com/5855327/126067991-9a759b73-fca9-425e-92e8-4f0c7f09d364.png)
![image](https://user-images.githubusercontent.com/5855327/126067998-522f7b14-4593-4afb-a2b0-9570e093ed63.png)

**Describe the Issue**
Using the editor, typing and then using the editor again (for example, change colour of text, type text in that colour, then revert back to default black), will nest the spans instead of ending it correctly. If you do this over a long paragraph you'll end up with an unnecessary amount of spans because it also includes a span for the back to black.

**To Reproduce**
1. In a manuscript scene
2. Type test
3. Select a new font colour
4. Type test again (you should now see test twice, last one in new colour)
5. Select another as your font colour
6. Type test again (now you have test thrice, middle one in colour, last one in a different colour)
7. Go to View > Source code
8. Will look something like this: 
`<p>test<span style="color: #169179;">test<span style="color: #e67e23;">test<span style="color: #ba372a;">test<span style="color: #843fa1;">test</span></span></span></p>`

**Expected behavior**
You'd expect the spans to close correctly when a new colour was selected. This is the code I'd expect to see:
`<p>test<span style="color: #169179;">test</span><span style="color: #e67e23;">test</span><span style="color: #ba372a;">test</span><span style="color: #843fa1;">test</span></p>`

If more info is needed to reproduce then do not hesitate to ask. I can make a short video if needed too if that helps.

**Comment by iamromeo** [comment]
Please do stop submitting issues with that editor. it will not change any time soon, it is not internally developed the the source access shouldn't even be used unless something breaks to fix it.
