### ISSUE TITLE
When I remove all of the default categories from my article list and put my own in, when I come back to them all of the default stuff gets put back in

### ISSUE THREAD

**Issue by jonupchurch** [worldanvil/worldanvil-bug-tracker#444]
**World Anvil Username**:
Gravytraining
**World / Campaign / RPG Character / Manuscript Title**:
[RPGS] REALM/PLANE GENERAL SERVICES, LTD.

**Feature**: 
Categories.
![image](https://user-images.githubusercontent.com/4390014/126089120-72045607-e3d2-4728-85a3-57db5419d7f8.png)
All of the highlighted categories were removed and keep returning. I've done this like 6 times. I had to put them at one point under a "Stuff I can't delete" folder, but that was messing up my menus as well.

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

**To Reproduce**
1. Go to categories in a new world
2. Create at least 1 new category
3. Remove all the default categories
4. close the browser, or come back after a short break
5. All the default categories return no matter what I do.

**Expected behavior**
I expect them to stay deleted and not return.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by jonupchurch** [comment]
It's especially frustrating because this "world" is actually documentation for a module I am making about an organization, so most of these categories are not even relevant (which is why I am deleting them)

**Comment by iamromeo** [comment]
I am really sorry but this is not what is happening. From what I can understand you deleted the top level categories that resulted into their children categories just coming on the top level. 

Deleting a category does NOT automatically delete all the categories under it as well, this is a safetey precaution very common to data repositories. 

Also keep in mind that these categories are only added automatically to the first world you create. For subsequent worlds you can elect for them not to be added. 

I hope that this makes sense, let me know if you need furhter help

**Comment by jonupchurch** [comment]
I'm not sure that's actually accurate as I am 100% certain that I have deleted all of the categories at least 2 times. I can see that having happened later on, but not initially. It's possible I missaw what was going on but I had initially started pruning branches from the leaves up to the branches and it still happened. Regardless, it seems to have stabilized after about the 7th run through deleting them so I'm no longer concerned.
