### ISSUE TITLE
Apollo Failing to Upload New Images

### ISSUE THREAD

**Issue by HumiliatedGoblin** [worldanvil/worldanvil-bug-tracker#445]
**World Anvil Username**: BostonTheBear

**World / Campaign / RPG Character / Manuscript Title**: World

**Feature**: Image drag and drop/Apollo 

**Related URLS** [](https://www.worldanvil.com/apollo/)

**Describe the Issue**
When I upload the image, it loads, then produces an X over it. It doesn't give me any prompt after that. When I hover over the image a red bar points to the X. The image I put it is under 1mb and is a PNG.

**To Reproduce**
1. Go to Apollo
2. Click on "Click or drag and drop a single file here"
3. Select image and wait for it to load

**Expected behavior**
I expected there to be a prompt to full out meta data, or at least show me that it had been uploaded but nothing seems to be happening.

**Screenshots**
![image](https://user-images.githubusercontent.com/87675952/126233972-a69924ba-44fd-4a76-90e4-11572ec581bd.png)

**Comment by Lyraine-Alei** [comment]
This issue has been given, I believe, a correction for the moment as this occurred in the late night/early morning.

**Comment by iamromeo** [comment]
This issue shoudl now be fixed, please confirm
