### ISSUE TITLE
Create a Map 404 Error

### ISSUE THREAD

**Issue by Overhail** [worldanvil/worldanvil-bug-tracker#446]
**World Anvil Username**: Overhail
**World / Campaign / RPG Character / Manuscript Title**: Oren

**Feature**: Create a Map

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/world/map/new

**Describe the Issue**
I was trying to create a second map for my homebrew world, and after i entered all the information and clicked 'Create Map' i got a 404 error, I tried multiple times to get through this but it keeps giving me the error

**To Reproduce**
1. Go to 'World Anvil'
2. Click on 'Create a new Map (I was creating a second map so i already had one made successfully)'
3. Click on 'Create Map' after entering map information

**Expected behavior**
I expected it to create a map.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![2021-07-19 (1)](https://user-images.githubusercontent.com/87677388/126240041-c49fe6b8-3726-4982-913d-1a808b26644b.png)
![2021-07-19](https://user-images.githubusercontent.com/87677388/126240096-a6d136da-2dab-47c4-b91a-c749defea926.png)

**Comment by Lyraine-Alei** [comment]
My understanding of this issue is that it is tied to the same one as [https://github.com/worldanvil/worldanvil-bug-tracker/issues/445]This Issue(url).

I'm mostly repeating this as I believe the issue has been given a short term correction.

**Comment by iamromeo** [comment]
This should now be fixed - can you please confirm
