### ISSUE TITLE
Cover images of world can't be selected when co-authors uploaded them

### ISSUE THREAD

**Issue by happyskunk** [worldanvil/worldanvil-bug-tracker#447]
**World Anvil Username**:
Lengna

**World / Campaign / RPG Character / Manuscript Title**:
The world where I had the issues was Jaime's Wanted Hero world, 
(though any co-authored world would prolly have similar results)

**Feature**: 
cover image selection

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I was helping Jaime get pages set up to give him more time for writing. But I can't set the images he's uploaded as header images on his articles. (Same goes for character images and flags) Instead I get images for my worlds 

**To Reproduce**
1. Go to 'A friend's world'
2. Click on 'any image drop down field'
3. Scroll down to 'anything'

**Expected behavior**
What I expected to happen was that images that were attached to his world would show up in the search fields. 
I get this not happening for using '[', as that's tied to user. 
But the drop downs I had assumed would be per-world and uploader agnostic

**Screenshots**
not really an image of the issue, just to show I'm following up on something we talked about before
![Screenshot_1](https://user-images.githubusercontent.com/23743151/126346174-b927240e-817b-4ade-b4b7-82f89e86bf8b.png)

**Comment by happyskunk** [comment]
I understand this would require having two different image search locations/rules/systems, and that's a lot of work. That's why I originally thought it made a better request than a bug report.

**Comment by Kordishal** [comment]
This applies to all places where images can be searched. Co-authors can still add these images when they know the image id. Except for places where it's a drop-down for image selection.

**Comment by iamromeo** [comment]
@Kordishal can you please investigate if the opposite happens for the owner. 
also are teh images uploaded by the co-author assigned to the world?

**Comment by Kordishal** [comment]
@iamromeo 

Yes this happens to the owner (and co-owner) as well. The images are assigned to the world. The search does yield a result when using the image ID instead of a search term in the title. When searching by title or tag no images of co-authors are returned.

This applies to the Article Cover, Character Portrait, Organization Crest and Historical Event Cover

**Comment by iamromeo** [comment]
Hey guys I have made a start on this but - which cover images are we referring to? 
- Article cover
or 
- World cover
or 
- Both

**Comment by Kordishal** [comment]
This applies to the Article Cover, Character Portrait, Organization Crest and Historical Event Cover. Basically everywhere where you have the search & select visual UI element.

**Comment by iamromeo** [comment]
Thank you so much @Kordishal

**Comment by iamromeo** [comment]
Fixed to search based on active WORLD. Will be deploying later on today
