### ISSUE TITLE
Cannot Like (or heart) Posts, Updates, Journal Entries

### ISSUE THREAD

**Issue by wordigirl** [worldanvil/worldanvil-bug-tracker#450]
**World Anvil Username**:
WordiGirl

**World / Campaign / RPG Character / Manuscript Title**:
THIS ISSUE DOES NOT HAPPEN WITHIN A WORLD, IT IS HAPPENING ON THE MAINSITE, WITHIN NOTIFICATION PAGES, AND ON AUTHOR PROFILES

**Feature**: 
Liking or "hearting" posts and journal updates from members of the community

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/dashboard/
https://www.worldanvil.com/author/Wordigirl
https://www.worldanvil.com/notification/
https://www.worldanvil.com/dashboard/user/post/ba078c9f-30ae-47ac-a352-9f1c96b9fdf6#profile-posts-list
https://www.worldanvil.com/author/Escritora%20Novata
(all the author profiles, all the comment pages)

**Describe the Issue**
I suddenly noticed that I am unable to heart any updates on the mainsite. The like button has dissappeared. I've tried logging in and back out to no avail, and many others have agreed it is an issue for them as well, on both mobile and pc versions of World Anvil. This is happening on author profiles, in updates, AND on the main page, but I can still see hearts on posts I liked before.

**To Reproduce**
1. Go to any page with a post/update/journal entry on it
2. Click on the invisible heart button
3. Nothing happens. It's not there
4. See error that you cannot like any posts, updates, or journal entries.

**Expected behavior**
The comment bubble will still be there and the number amount of likes, but there will be a gap for where the heart belongs.
**Screenshots**
![image](https://user-images.githubusercontent.com/39540057/126437202-33b6d4c3-511a-46e7-b9cb-75f43cbc26ac.png)
![image](https://user-images.githubusercontent.com/39540057/126437248-0c34ea9e-48d9-4186-94e9-08139b521d62.png)

Thanks and God bless! Hopefully this will be fixed soon!

**Comment by iamromeo** [comment]
Fixed
