### ISSUE TITLE
Suffix option in Character template displays with erroneous spacing

### ISSUE THREAD

**Issue by Hanhula** [worldanvil/worldanvil-bug-tracker#451]
**World Anvil Username**: Hanhula

**World / Campaign / RPG Character / Manuscript Title**: Istralar

**Feature**: Suffix section on Character template

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/istralar-hanhula/a/helgi-fjotlisson-person-1

**Describe the Issue**
A clear and concise description of what the issue is.

There's a grammatical error in how suffixes display on a character.

When you add a suffix to a character, it displays as:
Key-Bearer Helgi Fjotlisson ,the Burning Flame

It should instead display as:
Key-Bearer Helgi Fjotlisson, the Burning Flame

**To Reproduce**
1. Create & edit a character
2. Go to the Naming tab
3. Scroll down to Suffix
4. Enter a suffix
5. View changes on presentation or on preview.

**Expected behavior**

Explained above. To summarise: the space needs to go after the comma, not before.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![](https://i.imgur.com/1HIHYEZ.png)

**Comment by iamromeo** [comment]
Fixed will deploy later
