### ISSUE TITLE
{{ variables.race }} Showing instead of race on my charcaters profile.

### ISSUE THREAD

**Issue by XyberDAWG** [worldanvil/worldanvil-bug-tracker#453]
**World Anvil Username**:
XyberDAWG
**World / Campaign / RPG Character / Manuscript Title**:
Cirith T'lorne
**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/hero/66d4d7d7-417f-4b38-9689-ded0a9051667

**Describe the Issue**
My characters profile currently displays "Level 1 {{ variables.race }} Chaotic Good Paladin"
When it should say "Level 1 Human Chaotic Good Paladin"

**Comment by iamromeo** [comment]
I am not sure where you found this shee but this is a sheet created by **GM Tryggvi** - this is not a world anvil maintained sheet. 
Are they your Storyteller?

**Comment by Tillerz** [comment]
`{<del></del>{ variables.race }}`

GM Tryggvi has to check the badge field why there is < <del></del> between the {{. That's why it is not parsing properly.
