### ISSUE TITLE
Article slug editing does not stay after renaming article

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#454]
**World Anvil Username**: SoulLink

**Feature**: Article Slug

**Describe the Issue**
When setting a custom article slug the slug does not stay custom after renaming the article.

**To Reproduce**
1. Create article with title
2. Change slug to something else
3. View article -> custom slug
4. Return to editor
5. Rename article
6. View article -> auto-generated slug

**Expected behavior**
Custom slug to stay active after renaming.

**Comment by iamromeo** [comment]
After investigation this will not be possible to fix, not unless introducing a whole new feature set. 
It will be closed for now but we will have a discussion internally of how this can be mitigated for some users.
