### ISSUE TITLE
Custom Sage domains are sometimes applied to the rest of the site

### ISSUE THREAD

**Issue by OndoAlvelle** [worldanvil/worldanvil-bug-tracker#455]
**World Anvil Username**: Ondo

**World / Campaign / RPG Character / Manuscript Title**: N/A

**Feature**: Custom Sage domains

**Related URLS** (To public & visible pages add screenshots otherwise): Examples: https://echristopherclark.com/community/challenge/summercamp-2021/duel/110 , https://echristopherclark.com/features/dnd-campaign-manager

**Describe the Issue**
Non-world pages can be accessed using Sage domains. It doesn't redirect to the worldanvil.com domain, which can be confusing for anyone who doesn't know about this feature (most people). Some pages redirect to the WA domain (example: https://echristopherclark.com/author ).

I've had a report on Twitter saying that they were able to find the first url in the previous section on Google. I've not been able to verify it, but it could add to the confusion.

**To Reproduce**
1. Go to a non-world page and replace the "worldanvil.com" with a Sage domain
2. That's it! The domain will either stay or redirect to the worldanvil.com domain

**Expected behavior**
Custom domains should either not work outside of their world or at least automatically redirect to the "worldanvil.com"

**Comment by iamromeo** [comment]
Known issue already being handled :)
