### ISSUE TITLE
Can't Change Campaign Image Headers with Heroes CSS

### ISSUE THREAD

**Issue by Oneriwien** [worldanvil/worldanvil-bug-tracker#456]
**World Anvil Username**: Oneriwien

**World / Campaign / RPG Character / Manuscript Title**: https://www.worldanvil.com/epic/the-withered-rose

**Feature**: Heroes/Campign CSS

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Heroes campaign styling automatically applies .wrapper-content in front of every single class you add, this makes it impossible to alter the cover image.

![unknown](https://user-images.githubusercontent.com/36694877/126746759-05056821-5cec-4897-bd15-e7473d98f801.png)

My reason for doing so is to make it not repeat itself and nudge it slightly over.

**To Reproduce**
1. Attempt to add CSS to a Campaign.
2. Target the wrapper-header or card-img-wrap.
3. You cannot target them because the wrapper-content is not in the hierarchy of wrapper-header or card-img-wrap

(Sorry, not sure how to do this for this issue)

**Expected behavior**
The ability to change cover image size/shape/repeat/etc.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/36694877/126746982-4af25e4a-6fb6-452c-b8cb-e614cb6bf124.png)

**Comment by iamromeo** [comment]
What is it exactly tha tyou want - because that sounds like a feature request not a bug

**Comment by iamromeo** [comment]
added .page-header-image
