### ISSUE TITLE
Organization Crest Image Credits

### ISSUE THREAD

**Issue by graylion-wa** [worldanvil/worldanvil-bug-tracker#458]
**World Anvil Username**:

Graylion

**World / Campaign / RPG Character / Manuscript Title**:

Creation

**Feature**: 

Organiztion Template - Image Crest

**Related URLS**:

[https://www.worldanvil.com/w/creation/a/the-sisters-priesthood-organization](url)

**Describe the Issue**

The Organization Crest Image does not appear to include image credits.

**To Reproduce**

Please review the linked files above. The same image is attached as the Organization Crest an imbedded in the lower sidebar. The lower sidebar image shows the image credits as expected, which the crest does not.

**Comment by Kordishal** [comment]
That should show up at the bottom of the article. As it does with character portraits.
