### ISSUE TITLE
all partymembers are listed in a session, even when I only chose specific ones

### ISSUE THREAD

**Issue by zarazandra** [worldanvil/worldanvil-bug-tracker#459]
**World Anvil Username**:
zarazandra

**World / Campaign / RPG Character / Manuscript Title**:
Jahr des Feuers (custom)

**Feature**: 
scheduling a session with specific characters (not all inside the party)

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/heroes/campaign/session/new
![image](https://user-images.githubusercontent.com/70195103/126909291-73044e3a-84b3-4717-9ba6-3fb1bf650fcc.png)
![image](https://user-images.githubusercontent.com/70195103/126909309-d9cbf3ff-719b-4d80-bd06-ebf129ef7c11.png)

**Describe the Issue**
When setting a session with specific characters, not all inside the party which wasn't chosen intentionally because of that, all of them were added regardless, which leads to editing the whole stuff every time. 

**To Reproduce**
1. create a new session
2. choose some characters of the party
3. hit save
4. See all player characters added to the session, regardless if I included them or not

**Expected behavior**
Only those characters, which I chose are part of the session

**Screenshots**
see above

**Comment by iamromeo** [comment]
This will be addressed with the new system ;) I will see if I can patch it somehow until then
