### ISSUE TITLE
Timeline fails to display properly

### ISSUE THREAD

**Issue by Lorakyth** [worldanvil/worldanvil-bug-tracker#46]
**World Anvil Username**: Loraktyh

**World / Campaign / RPG Character / Manuscript Title**: History of the World

**Feature**:  Timelines

**Describe the Issue**
For some reason the timeline refuses to display except as a black mess, and in  editing events are displayed without lines and can't be edited without finding them separately.

**To Reproduce**
1. Go to 'https://www.worldanvil.com/world/timeline/6a1a2898-285e-4179-9ad4-190bfd3589c0/edit'
2. Scroll down just a bit
3. See error

**Expected behavior**
I expect the timeline to display properly.
![Capture 1](https://user-images.githubusercontent.com/80278342/110357122-90a4b200-8000-11eb-9e96-1b491edac158.PNG)
![Capture 2](https://user-images.githubusercontent.com/80278342/110357132-93070c00-8000-11eb-986d-fefb8e8e214c.PNG)

![Capture 1](https://user-images.githubusercontent.com/80278342/110357122-90a4b200-8000-11eb-9e96-1b491edac158.PNG)
![Capture 2](https://user-images.githubusercontent.com/80278342/110357132-93070c00-8000-11eb-986d-fefb8e8e214c.PNG)

**Comment by Kordishal** [comment]
Hi Loraktyh.

This is most likely not a bug, but instead, you have an unclosed BBCode tag in an event description. Try removing the events from the timeline until it reverts back to normal.
