### ISSUE TITLE
Image Metadata not Updating

### ISSUE THREAD

**Issue by Aster-Blackwell** [worldanvil/worldanvil-bug-tracker#460]
**World Anvil Username**: PrincessESH

**World / Campaign / RPG Character / Manuscript Title**: SanZera

**Feature**: Images and Files

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

When editing the image metadata in the Images and Files tab, the Tags, Artist, Artist Website, Art Title, and Art URL fields often fail to save after clicking away from the File Manager panel. Only after reentering the information several times does it finally "stick". The fields that get wiped are seemingly random and are different every time.

**To Reproduce**
1. Go to _Images and Files_
2. Click on any image
3. Type any information into the Tags, Artist, Artist Website, Art Title, or Art URL fields in the File Manager panel.
4. Click on a different image or otherwise exit the File Manager panel.
5. Return to the same image chosen at step 2 and find that the information previously inputted is no longer present.

**Expected behavior**

Information entered into the File Manager fields doesn't disappear when exiting or clicking to a different image.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/87995336/127028929-7e0dfddf-c7ad-489d-ba45-98f2707b920d.png)
![image](https://user-images.githubusercontent.com/87995336/127029020-1f18f643-e2fa-42d4-b5bc-ab5e657ec477.png)

**Comment by iamromeo** [comment]
Are these tags PASTED in or written?

**Comment by Aster-Blackwell** [comment]
Either. I've had the problem doing both.

**Comment by iamromeo** [comment]
I am really sorry but I cannot reproduce this issue the way it is described. I am not sure if @Kordishal can have another look but from my end I cannot find the issue.

**Comment by Kordishal** [comment]
I cannot reproduce this either. Maybe there is an extension that prevents the save from performing correctly? Can you try to make this happen in a private window?

And does it happen consistently or just occasionally?
Does it happen to this image or all images?
Can you get any info saved?

**Comment by Aster-Blackwell** [comment]
It occurs when I test it in a private window. It consistently happens
across multiple images and both of my worlds. It also happens across
completely different computers.

I am able to eventually get it to save, but it takes a lot of jumping
back and forth testing to see if it'll stay. It doesn't clear all of the
information, it usually only clears about half of fields, but which fields
get wiped is completely random and has no correlation with the order I
filled them in. It also doesn't matter if I type it or paste it.

**Comment by Kordishal** [comment]
the last thing we can try is for you to add me as an editor to your world so I can check if the image issue happens to me as well. Otherwise I am out of ideas what could be causing this.

My username on World Anvil is [SoulLink](https://www.worldanvil.com/author/SoulLink).

**Comment by Aster-Blackwell** [comment]
I see... since this issue happens to me on both of my worlds, I don't know
if that would find a solution either. While it is annoying I think I can
just deal with it. Thanks for your help.
