### ISSUE TITLE
Player Character Link Not Visible

### ISSUE THREAD

**Issue by graylion-wa** [worldanvil/worldanvil-bug-tracker#461]
**World Anvil Username**:

Graylion

**Describe the Issue**

Player Character Side Menu link is no longer visible to non alchemists 

Reporting at Hanhula's request

**Related URLS** 

See Hanhula's post here

https://discord.com/channels/348060277989965844/380013392653451264/869624304290111488

**Screenshots**

![20210727_130937.jpg](https://user-images.githubusercontent.com/79761754/127198255-31cb3c78-77b5-40b0-a664-3e3b214ba566.jpg)

**Comment by iamromeo** [comment]
Fixed
