### ISSUE TITLE
Work in Progress Articles don't sort by oldest

### ISSUE THREAD

**Issue by Endrise** [worldanvil/worldanvil-bug-tracker#462]
**World Anvil Username**:
Endrise

**World / Campaign / RPG Character / Manuscript Title**:
The Fabulae Anthology

**Feature**:
Article & Categories (lists)

**Describe the Issue**
It seems that for the list WIP articles they are sorted by the newest instead of the oldest.

**To Reproduce**
1. Go to articles & categories
2. Go to lists
3. Select WIP articles
4. Error shows (check the date of the latest article)

**Expected behavior**
I expected to have the oldest WIP articles appear first.

**Screenshots**
(For context, I made that WIP only a few days ago)
![image](https://user-images.githubusercontent.com/88051031/127199410-c6170cd0-02bc-4ae1-a3c1-a1f8139ef50b.png)

**Comment by iamromeo** [comment]
Not a bug
