### ISSUE TITLE
Simple generators acting silly when put on same article

### ISSUE THREAD

**Issue by Tiirikka** [worldanvil/worldanvil-bug-tracker#464]
**World Anvil Username**: Tiirikka

**World / Campaign / RPG Character / Manuscript Title**: Melyria

**Feature**: Studio: Generators

**Related URLS**: https://www.worldanvil.com/w/melyria-tiirikka/a/drow-name-generator-article

**Describe the Issue**
Okay, this might be an odd problem! :D So I'm working on a generator that makes "drow elf" names from bits and pieces on a list, and it is coming on quite wonderfully if I say so myself. However, it popped to my mind that on occasion it would be cool if I could generate names that are a certain length. However, when I put two generators that make different lengths of names in the same article, I noticed an amusing little bug. 

When you click a generate button, the generator looks like it is doing exactly as it is supposed to; the upper one makes names about 3 to 6 characters long, and the lower one makes names 5 to 10 characters long. However, instead of the generated name only appearing under the generating button of the generator I pressed, the same result appears under both generators, even though only one is used.

**To Reproduce**
Steps to reproduce the behaviour, just in case:
1. Go to https://www.worldanvil.com/w/melyria-tiirikka/a/drow-name-generator-article
2. Click on 'Generate female Drow name (3 to 6 characters)'
3. Notice how the field under that button and 'Generate female Drow name (5 to 10 characters)' both show the same result, instead of one not showing anything

**Expected behaviour**
While this is really a minor one, I think it would be cool if the generators, even when put on the same page, would function completely seperately, so you could put several in one article like this without all of them printing the same thing. It's not a huge issue, but a little inconvenient. My best guess is that currently the result of the generator is printed to an element of a certain CSS class, instead of one with a unique HTML id, which causes duplicates when 2 items with the same class are present.

Thank you in advance, and sorry for the trouble! ^^ I hope you guys are having a fine summer!

**Comment by iamromeo** [comment]
This is not a bug, only one generator per page as per documentation
