### ISSUE TITLE
Nesting Accordion Spoilers Uses the Wrong Labels in the Wrong Places

### ISSUE THREAD

**Issue by MulciberVolcanus** [worldanvil/worldanvil-bug-tracker#465]
**World Anvil Username**:
HarleyQ

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/harleyqs-tips-and-tricks/a/nesting-accordion-test-article

**Describe the Issue**
I was recently playing around with nesting accordion spoilers and encountered an odd behavior. Apparently, when spoilers are nested, it uses the first label of the nested spoiler as the label of the main spoiler and then the label of the main spoiler for the first label of the nested spoiler. I hope that makes sense. You can see the link above for an example of this. Nesting spoilers 3 deep just breaks it outright.

**To Reproduce**
Here's my bbcode:
`[container:splr-acc-nest]
[spoiler]Content AA[container:splr-acc-nest]
[spoiler]Content A1|Label A1[/spoiler]
[spoiler]Content A2|Label A2[/spoiler]
[spoiler]Content A3|Label A3[/spoiler]
[/container]|Label AA[/spoiler]
[spoiler]Content BB [container:splr-acc-nest]
[spoiler]Content B1|Label B1[/spoiler]
[spoiler]Content B2|Label B2[/spoiler]
[spoiler]Content B3|Label B3[/spoiler]
[/container]|Label BB[/spoiler]
[spoiler]Content CC[container:splr-acc-nest]
[spoiler]Content C1|Label C1[/spoiler]
[spoiler]Content C2|Label C2[/spoiler]
[spoiler]Content C3|Label C3[/spoiler]
[/container]|Label CC[/spoiler]
[/container]`

And here's my css:
`.user-css div.splr-acc,
.user-css div.splr-acc-jus,
.user-css div.splr-acc-nest {
    line-height: 1.4em;
    width: 100%;
}

.user-css div.splr-acc a.spoiler-button,
.user-css div.splr-acc-jus a.spoiler-button,
.user-css div.splr-acc-nest a.spoiler-button {
    display: block;
    margin: 0;
    border-radius: 0px;
    border: none;
    text-shadow: 0 0 5px var(--MartianJuice);
    font-family: Aldrich;
    letter-spacing: .01em;
    font-weight: 100;
    padding-top: 5px;
    padding-bottom: 5px;
    background-color: rgba(50, 163, 139, 0.637) !important;
    white-space: normal;
}

.user-css div.splr-acc-jus a.spoiler-button {
    text-align: justify !important;
}

.user-css div.splr-acc a.spoiler-button:first-of-type,
.user-css div.splr-acc-jus a.spoiler-button:first-of-type {
    font-family: Aldrich;
    font-size: 40px;
    font-variant: small-caps;
    background-color: rgba(85, 136, 99, 0.637) !important;
}

.user-css div.splr-acc a.spoiler-button:first-of-type,
.user-css div.splr-acc-jus a.spoiler-button:first-of-type,
.user-css div.splr-acc-nest a.spoiler-button:first-of-type {
    border-top-right-radius: 10px;
    border-top-left-radius: 10px;
    text-align: center !important;
}

.user-css div.splr-acc a.spoiler-button:last-of-type,
.user-css div.splr-acc-jus a.spoiler-button:last-of-type,
.user-css div.splr-acc-nest a.spoiler-button:last-of-type {
    border-bottom-right-radius: 10px;
    border-bottom-left-radius: 10px;
}

.user-css div.splr-acc a.spoiler-button[aria-expanded=true],
.user-css div.splr-acc-jus a.spoiler-button[aria-expanded=true],
.user-css div.splr-acc-nest a.spoiler-button[aria-expanded=true] {
    border-bottom-right-radius: 0px;
    border-bottom-left-radius: 0px;
}

.user-css div.splr-acc div.spoiler-content,
.user-css div.splr-acc-jus div.spoiler-content,
.user-css div.splr-acc-nest div.spoiler-content {
    margin: 0px;
    border-radius: 0px;
    border: none;
    background: rgba(34, 68, 43, 0.637);
    box-shadow: none;
    color: var(--MartianJuice);
    text-align: justify;
}

.user-css div.splr-acc [class^=spoiler-conta]:last-child div.spoiler-content,
.user-css div.splr-acc-jus [class^=spoiler-conta]:last-child div.spoiler-content,
.user-css div.splr-acc-nest [class^=spoiler-conta]:last-child div.spoiler-content {
    border-bottom-right-radius: 10px;
    border-bottom-left-radius: 10px;
}`

**Expected behavior**
Label AA should be the label for the first spoiler and label A1 should be the label for the first nested spoiler, but as you can see, this is not the case.

Thank you!!!

**Comment by Kordishal** [comment]
This behaviour is currently working as intended. An alternative to these spoilers is planned and will likely be implemented sometime in the future. Until then nesting spoilers is not possible. 

The codex has links to [Accordion guides](https://www.worldanvil.com/w/WorldAnvilCodex/a/css-grandmasters) on how they can be achieved currently.

**Comment by MulciberVolcanus** [comment]
Oh well... I guess I'll just have to wait!

Thanks!
