### ISSUE TITLE
Unable to edit preexisting articles upon membership expiry

### ISSUE THREAD

**Issue by DragonManipulator372** [worldanvil/worldanvil-bug-tracker#466]
**World Anvil Username**: DragonManipulator372

**World / Campaign / RPG Character / Manuscript Title**: The Fantasy Nexus

**Feature**: Editing articles

**Related URLS** (To public & visible pages add screenshots otherwise): N/A

**Describe the Issue**
After membership expiry, I am unable to edit any of my preexisting articles, despite my world being public.

**To Reproduce**
Click on "Edit Article" in any of my world's articles.

**Expected behavior**
Upon trying to edit the article, I expected to still have access to it.

**Screenshots**
N/A

**Comment by iamromeo** [comment]
Can you elaborate on what you mean you are not able to edit them. What exactly does it happen. Also just so we are clear, expecting something doesn't mean it's a bug - you might be over the free account limit but I cannot say until you give me more details.

**Comment by DragonManipulator372** [comment]
> 
> 
> Can you elaborate on what you mean you are not able to edit them. What exactly does it happen. Also just so we are clear, expecting something doesn't mean it's a bug - you might be over the free account limit but I cannot say until you give me more details.

If you mean over the free article limit, then yes, I am over the public/draft article limit. However, I was informed that I should still at least be able to edit the articles that I've already created, assuming my world is public (it is). Unfortunately, when I go to edit an article, it brings up this screen:

![pass](https://user-images.githubusercontent.com/26155922/127724183-76f4ea20-6cf3-4ca6-8fb2-6749ae786bbc.png)
