### ISSUE TITLE
Content tree item title not showing

### ISSUE THREAD

**Issue by sirteabag** [worldanvil/worldanvil-bug-tracker#467]
**Sir_Teabag**:

**Content Tree New Tezz Organizations**:

**Content Tree Item**: 

**https://www.worldanvil.com/w/rexweld-sirteabag/a/new-tezz-kingdom-organization?preview=true this article contains the Content Tree** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Items in content trees that aren't articles (blank items with a manually set title) do not show their assigned titles if they do not possess a description. Only when a description is added the title is shown.

**To Reproduce**
1. Go to 'content trees'
2. Add a new item without adding an article
3. Give the item a title but no description
4. Link the content tree to an article to view it and to see that the title is not showing
5. For testing sake you can add a description and see that only then the title shows up

**Expected behavior**
I would expect that the title would appear even if a description is not added

**Comment by iamromeo** [comment]
@Xuroth can you check and confirm this

**Comment by Xuroth** [comment]
Resolved issue!
