### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by Nathaliabooks1993** [worldanvil/worldanvil-bug-tracker#468]
**Nathaliabooks1993**:

**Caminba**:

**Conflict**: 

**https://www.worldanvil.com/w/carminba-nathaliabooks1993/a/red-desert-wars-militaryConflict** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I click on the: SIDEBAR DISPLAY
 Display article sidebar (override) to take away the sidebar but it still shows in my article. I refreshed the page, but I am still out off luck. 

**Expected behavior**
I want the sidebar gone from this article
![Screenshot 1](https://user-images.githubusercontent.com/88212675/127711162-720068ff-652a-4e63-bb47-5245d857eead.PNG)
![screenshot 2](https://user-images.githubusercontent.com/88212675/127711165-8bec400c-9e93-4246-ab52-8a47df6ee9be.PNG)
. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Fixed - will be deployed a bit later on
