### ISSUE TITLE
Front Page Link Broken

### ISSUE THREAD

**Issue by AmeliaNite** [worldanvil/worldanvil-bug-tracker#469]
**World Anvil Username**: amelianite

**World / Campaign / RPG Character / Manuscript Title**: Darkness Moon Chronicles (World)

**Feature**: Front Page

**Related URLS** (To public & visible pages add screenshots otherwise): 

**Describe the Issue**
Cannot access world front page by any means; all links 404. Discovered the issue by trying to return to the main page via the Back to World button, but the issue persists when accessing via URL or through the profile.

**To Reproduce**
1. Go to any article within Darkness Moon Chronicles.
2. Click on "Go to Darkness Moon Chronicles Homepage" button.
3. See error.

**Expected behavior**
Whenever I attempt to click on the "view world" button or the "back to world" button to look at my front page, they don't work and send me straight to the 404 Dragon. I have not touched any CSS for the past week, and the "back to world" button was working until last night (12 am CNT).

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![dmc font page 404 dragon](https://user-images.githubusercontent.com/88216660/127723662-7ac7c985-5d49-4fc8-9308-92f101310cc9.png)

If more information is needed, I'm @AmeliaNite|DAIMONDORDIE(27/31)#9930 on Discord,

**Comment by Hanhula** [comment]
Main world link: [here](https://www.worldanvil.com/w/darkness-moon-chronicles-amelianite)
Random working article: [here](https://www.worldanvil.com/w/darkness-moon-chronicles-amelianite/a/adged-diamond-person?preview=true)

We discussed this in #help so I'm just popping in to make sure all relevant links are here.

**Comment by Kordishal** [comment]
This is likely not a bug, but a faulty BBCode tag that prevents the render of the fornt page and then returns a 404.

Try removing text in all fields are displayed on the front page. If that doesn't work come back to the Discord.
