### ISSUE TITLE
Export Worlds & Manuscripts does not export Statblocks

### ISSUE THREAD

**Issue by marius-djaedr** [worldanvil/worldanvil-bug-tracker#47]
**World Anvil Username**: Marius D'jaed'r

**World / Campaign / RPG Character / Manuscript Title**: Magus

**Feature**: Export Worlds & Manuscripts

**Related URLS** (To public & visible pages add screenshots otherwise): https://toolbox.soullink.docker.worldanvil.com/backup/form

**Describe the Issue**
The export did not include statblocks, even though I checked "Include Statblocks".

**To Reproduce**
1. Go to a world you own which has statblocks
2. Click on 'World Settings > Configuration'
3. Click on 'Export World > Export this World'
4. Fill out the form
5. Make sure "Include Statblocks" is checked
6. Click 'Start', wait for email with exported files
7. See that the statblocks are not included

**Expected behavior**
Statblocks are included in the files

**Comment by Kordishal** [comment]
Hi when I export a World with statblocks they are included. The blocks are inside the Folder /worlds/{name-of-world}/blocks.

**Comment by Kordishal** [comment]
You can reopen a issue for the next time :)

**Comment by marius-djaedr** [comment]
How do I reopen this issue? Normally, "Reopen Issue" appears with the comment box (this screenshot is from a different repo)
![image](https://user-images.githubusercontent.com/77884367/110474656-8dafcd00-80a5-11eb-947a-fef9519d0af0.png)

But all I see here is 
![image](https://user-images.githubusercontent.com/77884367/110474709-9d2f1600-80a5-11eb-87c8-9049d9a14f60.png)

**Comment by Kordishal** [comment]
Curious. I have no idea why that is. Thanks for bringing it up :+1: .
