### ISSUE TITLE
Map Marker Groups Cannot Be Set Private

### ISSUE THREAD

**Issue by Tom212** [worldanvil/worldanvil-bug-tracker#472]
**World Anvil Username**: Tomfool

**World / Campaign / RPG Character / Manuscript Title**: Talenmont

**Feature**: Map Marker Groups

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
After setting a map marker group to private, it immediately reverts to being public. 

**To Reproduce**
1. Create and save a private map marker group.
2. Edit the map marker group.
3. Observe that the privacy status is set to public.

This is present both when creating a new group, and when editing and existing group.

**Expected behavior**
When I set a map marker group to private, it should remain private.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Fixed also added indicators of state and list of sub groups on the list for both Marker groups and Layers

**Comment by Tom212** [comment]
Brilliant, thank you for solving this so quickly.
