### ISSUE TITLE
Funky article placement on Articles & Categories

### ISSUE THREAD

**Issue by MGatta** [worldanvil/worldanvil-bug-tracker#473]
**World Anvil Username**: MGatta

**Feature**: Articles & Categories

**Describe the Issue**
When trying to place an article into a category using the drag & drop method within Articles & Categories, I have started getting weird category selections.

So for example, when trying to place an article, I may get two categories selected, even though I am only hovering over one. Or I may hover over one, but the selected category is a different one.

**To Reproduce**
I am not sure how to reproduce this. I have been doing article placement for about 20 minutes when this started happening*. And it only started happening now. I did a refresh, and it stopped happening for a couple of articles, but it started doing it all over again.

*Specifically, I was moving recently transferred articles from "Uncategorized" list to their own (newly created) categories.

**Expected behavior**
For the category being hovered to be the category selected (and only that one) during article placement using drag & drop.

**Screenshots**
I also have a video, where the full behaviour is displayed, but it won't let me add it.
![image](https://user-images.githubusercontent.com/80196715/127779345-f72ca5fa-11d1-48b2-98c9-9c1c1d221c1e.png)

**Comment by iamromeo** [comment]
Which browser are you using make/version

**Comment by Kordishal** [comment]
This happens to me as well. On both Chrome and Firefox. I an try and make it happen consistently tonight.

**Comment by MGatta** [comment]
I am using Opera, version 77.0.4054.277.

**Comment by iamromeo** [comment]
I do not think I will be pursueing this but let's see if it can be reproduced consistently

**Comment by Kordishal** [comment]
This seems to happen with the last two categories on a sublevel highlighting the last two categories of one or two levels above it. I can however confirm that it always puts them into the hovered category regardless of what is highlighted. So this is a purely visual / UX issue.
