### ISSUE TITLE
Issues Saving with Genesys Dice Symbols

### ISSUE THREAD

**Issue by konda-immortal** [worldanvil/worldanvil-bug-tracker#474]
**World Anvil Username**: Paul Norris

**World / Campaign / RPG Character / Manuscript Title**: Linebound

**Feature**: Genesys dice symbols.

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/linebound-paulnorris/a/genesys-bug-test-article-article

**Describe the Issue**
When including the [genesysdice:type] in an article, often when using several one-after-the-other, even if the article says it has saved and you go to view it, it doesn't show past the first symbol or two. Returning to the editor reveals that everything that didn't show up has been removed from the article.

**To Reproduce**
1. Create a new article.
2. Write anything in any section including but not ending in several [genesysdice:type].
3. Save.
4. View article and see error.

Note: If you copy the entire text before viewing, empty the section you're writing in, and paste it, the issue does not occur.

**Expected behavior**
All text after some Genesys symbols doesn't display, and has been removed from the article altogether.

**Screenshots**
![Genesys Bug](https://user-images.githubusercontent.com/80478205/127783022-1ae3eeb4-7630-41a6-9268-c9f28d972840.PNG)

**Comment by Kordishal** [comment]
This issue appears to only happen in Plato. Plato is slated for a rebuild, which is why this issue won't be fixed at this time.

Please switch to the Euclid editor in the meantime. You can check how to switch [here](https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors)
