### ISSUE TITLE
Position/weight isn't working in character relationships

### ISSUE THREAD

**Issue by Dhaleen** [worldanvil/worldanvil-bug-tracker#475]
**World Anvil Username**: RazDhaleen

**World / Campaign / RPG Character / Manuscript Title**: Dawn

**Feature**:  Position/Weight

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
The position/weight stat that I type in cannot change the order that the relationships appear in when I view the article. It has a little effect in editing mode (which I'll elaborate on below), but when I click on "view (the article)" after having made any changes, the relationships always appear in the order they were created in, regardless of any value I assigned for the position/weight setting, which claims that "the higher the number, the higher it will appear."

It also doesn't really change the order for editing mode, only changes the order within the relationships that were started by the same person -> it's like they've split into type A relationships and type B relationships: the relationships created through the editing page of this character (A) take precedence over the relationships created through the page of any counterpart character (B), and if I try to set a position/weight number, it can only change the order they appear in within their own type (A or B). This is not the main issue though; the order in the viewed article is more important.

**To Reproduce**
1. Go to the full view of any character page with relationships.
2. Note which relationship is at the top.
3. Go to 'relationships' in editing mode of that character page.
4. Click on any relationship that is not the one on top.
5. Assign a large position/weight number that should surely bring them to the top.
6. Save and view the character article.
7. See that it has not changed anything.

**Expected behavior**
I was confused as this position/weight option didn't appear to do anything at all, so I asked the discord help group and was told it is indeed supposed to **be able to change the order of the relationships**, whether in the sidebar or in the detailed relationships section. On their advice I hard refreshed several times, but even though the number I typed in did save, the order of the relationships never changed.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
- Fixed the issue on the presentation 
- I can confirm the issue on the character B page ordering. This occurs because each relationship has only only one ordering value. This is highly unlikely to change at this stage but can be addressed as a feature request for "**per character ordering on relationships**"
