### ISSUE TITLE
Character Sheet does not save

### ISSUE THREAD

**Issue by Chronx6** [worldanvil/worldanvil-bug-tracker#476]
**World Anvil Username**: Duinfae

**World / Campaign / RPG Character / Manuscript Title**: Blighted World

**Feature**:  Character Sheet

**Related URLS** (To public & visible pages add screenshots otherwise):https://www.worldanvil.com/hero/589d2937-b13e-4906-9d75-40da31ff60cd

**Describe the Issue**
Character sheet was saved without a name and despite stating it was 'saved' it did not save any changes.

**To Reproduce**
Create Character sheet
Do not enter name
Make other changes
Save

**Expected behavior**
Save information sans name

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
This might be an issue with your browser. When I attempt to save a sheet without a name filled in it asks me to fill in that field and does not save at all.

What browser are you using?
