### ISSUE TITLE
Typos in Meta-Focus

### ISSUE THREAD

**Issue by Are10** [worldanvil/worldanvil-bug-tracker#477]
**World Anvil Username**:
N/A

**World / Campaign / RPG Character / Manuscript Title**:
N/A

**Feature**: 
Meta

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/world/meta

**Describe the Issue**
The word "countries" is spelled as "countires", in "First Focus Point" and "Ancillary/Expanded Focus Points"

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Comment by iamromeo** [comment]
thank you @Are10
