### ISSUE TITLE
Footnotes not being diplayed in the Military Conflict template

### ISSUE THREAD

**Issue by OndoAlvelle** [worldanvil/worldanvil-bug-tracker#479]
**World Anvil Username**: Ondo

**World / Campaign / RPG Character / Manuscript Title**: Any "Military conflict" article

**Feature**: "Footnotes" section

**Describe the Issue**
Anything added in the "footnotes" section of the Military Conflict template is not displayed in the article. This has been confirmed with another user, so it's not a CSS issue.

**To Reproduce**
1. Create/edit a Military conflict article.
2. Type anything in the Footnotes field (Sections -> Footer Sections).
3. View the article, look for the footnotes.

**Expected behavior**
Footnotes should appear in their regular location.

**Comment by iamromeo** [comment]
Thank you for reporting @OndoAlvelle
