### ISSUE TITLE
Uploads keep failing

### ISSUE THREAD

**Issue by ProgrammerSS2020** [worldanvil/worldanvil-bug-tracker#48]
Using the File Manager, I am attempting to upload files. Files over 3.3MB hang up and never complete the upload. They all get hung up just short of 3.4 MB.  I left it for over 30 minutes, and it would not complete. Tried restarting the browser. I use the latest Chrom Browser and am a Grandmaster user. My current total MB is 200.3 MB / 5.0 GB.  User name is ss2020.

**Comment by Kordishal** [comment]
This is not a general issue. Try to upload them with another browser. Log in in a private window and upload them there. If this works then some extension/plugin prevents the upload.

Make sure the image is JPG, PNG or WEBP.

Make sure your connection is stable.

If the issue persists please ask in the guild help channels on Discord.
