### ISSUE TITLE
Not all social media icons are displayed in the World Meta Introduction

### ISSUE THREAD

**Issue by Rosaa-xd** [worldanvil/worldanvil-bug-tracker#480]
**World Anvil Username**: Sh4d0wPh03n1x

**World Title**: Hesli

**Feature**: World Meta

**Related URLS** (To public & visible pages add screenshots otherwise): [World Meta](https://www.worldanvil.com/world/meta)

**Describe the Issue**
In the World Meta Introduction at the bottom just below credits, not all social media icons are displayed. Discord is the only one that's correctly displayed.

**To Reproduce**
1. Go to World Meta (https://www.worldanvil.com/world/meta)
2. Scroll nearly all the way down to credits

**Expected behavior**
I would expect all icons to be displayed correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/11375483/127859084-86e6a18a-88d2-4473-9b6f-42b93a8c486b.png)

**Comment by iamromeo** [comment]
Thank you for the heads up @Rosaa-xd
