### ISSUE TITLE
404 when trying to delete certain profile comments

### ISSUE THREAD

**Issue by ShellShaded** [worldanvil/worldanvil-bug-tracker#481]
Hello! Thank you.

**World Anvil Username**:
ShellShaded

**World / Campaign / RPG Character / Manuscript Title**:
personal Author page/profile

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/author/ShellShaded
https://www.worldanvil.com/dashboard/user/post/f61ec082-679d-46e7-b8e3-914869c8b791
https://www.worldanvil.com/dashboard/user/post/8f414285-0582-4e48-af33-4266f65cd882

**Describe the Issue**
A clear and concise description of what the issue is.

I am unable to delete the two comments on my author page (from Sep and Oct of 2020). It fails to delete them and sends me to the WA 404 error page.
The URLs of the error pages are
https://www.worldanvil.com/dashboard/user/post/f61ec082-679d-46e7-b8e3-914869c8b791/delete
https://www.worldanvil.com/dashboard/user/post/8f414285-0582-4e48-af33-4266f65cd882/delete

**To Reproduce**
1. Go to my (ShellShaded) Author page
2. Click on # to bring up the individual comment page
3. Click "delete post" red button under the comment

**Expected behavior**

I expected the posts to be deleted, but they resist my demands. :|
I deleted other comments/posts without issue.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Untitled](https://user-images.githubusercontent.com/83040855/127939419-ac35f2ac-e107-4566-bc0d-1b435c8326eb.jpg)

**Comment by iamromeo** [comment]
I am not sure which comment are you trying to delete

**Comment by Kordishal** [comment]
https://www.worldanvil.com/dashboard/user/post/f61ec082-679d-46e7-b8e3-914869c8b791
https://www.worldanvil.com/dashboard/user/post/8f414285-0582-4e48-af33-4266f65cd882

These two I think

**Comment by ShellShaded** [comment]
> https://www.worldanvil.com/dashboard/user/post/f61ec082-679d-46e7-b8e3-914869c8b791
> https://www.worldanvil.com/dashboard/user/post/8f414285-0582-4e48-af33-4266f65cd882
> 
> These two I think

Yes, those, thank you. Sorry, I should have referred to them as posts rather than comments

**Comment by iamromeo** [comment]
I am still trying to understand are you trying to delete the POST the COMMENT of CroaToan or your response?

**Comment by ShellShaded** [comment]
> I am still trying to understand are you trying to delete the POST the COMMENT of CroaToan or your response?

I am trying to entirely delete both posts linked above

**Comment by iamromeo** [comment]
Identified the issue

**Comment by iamromeo** [comment]
Thiis happens because there is a reply and the reply itself has a comment on it. Removing the reply and then the post will fix this issue. 

It will be considered at a later time but for the time being will not be actioned due to very low demand on the feature.
