### ISSUE TITLE
system needed: VtM V5

### ISSUE THREAD

**Issue by ryjol** [worldanvil/worldanvil-bug-tracker#483]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name (RPG SYSTEM)**: Vampire the Masquerade Fifth Edition
**List Name** (Name under which it should be listed on World Anvil): Vampire the Masquerade V5
**World Anvil Username**: ryjol

**Website**: https://www.worldofdarkness.com/

**Logo Image Link**: https://www.google.com/url?sa=i&url=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AVampire_The_Masquerade_logo_V5.png&psig=AOvVaw2rdiIQzWGjfQs0Sei2rk40&ust=1628112414106000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCPDahcPllfICFQAAAAAdAAAAABAD

**Logo Usage Terms (URL)**: public domain https://commons.wikimedia.org/wiki/File:Vampire_The_Masquerade_logo_V5.png
![Vampire_The_Masquerade_logo_V5](https://user-images.githubusercontent.com/88406355/128088642-84967826-1b82-4863-9d20-7674ac9615af.png)

**Comment by iamromeo** [comment]
VtM is under World Of Darkness and already present with full support.
