### ISSUE TITLE
New-style Unordered lists don't properly indent

### ISSUE THREAD

**Issue by nonplayer** [worldanvil/worldanvil-bug-tracker#485]
**World Anvil Username**: nonplayer

**World / Campaign / RPG Character / Manuscript Title**: https://www.worldanvil.com/w/rifts-earth-npc-style-nonplayer

**Feature**: Quick Bullet Lists

**Describe the Issue**
The new quick-format lists are absolutely life-saving for me and my writing process. However I notice that they display differently, and do not properly indent multi-line content. I've attached screenshot examples of correct indentation and incorrect indentation.

**Expected behavior**
Unordered lists should indent identically regardless of method used.

**Screenshots**
![image](https://user-images.githubusercontent.com/5161177/128208261-b379d6d8-7610-4285-861f-87c36d474689.png)
![image](https://user-images.githubusercontent.com/5161177/128208340-40e4842d-4929-446f-8923-f40f7398e6c3.png)
![image](https://user-images.githubusercontent.com/5161177/128208382-c98d4ac9-ad87-472e-8364-5c7358cb94b0.png)
![image](https://user-images.githubusercontent.com/5161177/128208410-85403fbb-0789-4cd3-a751-fe7e4fc23e86.png)
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
The difference is the that these lists do not have an actual list container around the list items and different classes. So some CSS has to be added to each of the themes to accommodate these changes. So you are probably better off sending a request to the person who made this theme or ask in the css help channel on Discord for a CSS solution (or if you know CSS then you can do it yourself).

**Comment by iamromeo** [comment]
@Kordishal the CSS for the lists should be on top of everything else - 

Sadly @nonplayer the article you shared is not public and/or published so I cannot really check your CSS to see what is being overriden and why

**Comment by iamromeo** [comment]
I went through most themes and none of them had an issue with this - I cannot only surmise this is a custom CSS issue.

**Comment by nonplayer** [comment]
Sadly that is not the case. I am not using any custom CSS, and the theme is the basic stock built-int-World Anvil "Galaxy Anvil" theme.

**Comment by nonplayer** [comment]
> Sadly @nonplayer the article you shared is not public and/or published so I cannot really check your CSS to see what is being overriden and why

The link I provided is public. I don't know what you're talking about. Which article in specific are you unable to see?

**Comment by nonplayer** [comment]
Upon further inspection, this appears to possibly be related to browser implementations. In Firefox, everything looks fine:

![image](https://user-images.githubusercontent.com/5161177/128380224-366a0f8e-6e1e-425b-bcaa-05e6a430dd45.png)

In Opera, Edge, and Vivaldi, it doesn't hang indent:

![image](https://user-images.githubusercontent.com/5161177/128380338-bce16fbd-70c0-4ab1-b3c2-11c29c1aa868.png)

I checked the Brave browser, which I use on my Android phone, and it too fails to indent.

**Comment by iamromeo** [comment]
In which case this is an overload, an odd one but an overload no less and a matter of the theme. Is this the Stars theme? If so you can find the creator talk to them on Discord.

**Comment by nonplayer** [comment]
Will do, thanks!
