### ISSUE TITLE
Some flat map icons not displaying

### ISSUE THREAD

**Issue by Merecraft** [worldanvil/worldanvil-bug-tracker#487]
**World Anvil Username**: Merecraft

**World / Campaign / RPG Character / Manuscript Title**: The Azure Sea

**Feature**: Some map Icons not working correctly

**Related URLS** (To public & visible pages add screenshots otherwise): https://cdn.discordapp.com/attachments/380013392653451264/872852377382846494/unknown.png

**Describe the Issue**
Some of the flat map icons are not displaying. They are not displaying when adding a new map icon, or on the final map. Not all icons are affected. So far I have determined the following are not displaying properly, there may be more:
flat_black_bridge1.png
flat_white_bridge1.png
flat_white_castle1.png
flat_black_church1.png
flat_white_church1.png
flat_black_city1.png
flat_white_city1.png
I asked in the discord help channel and another user confirmed the same issue on his world too, so it appears to be a general bug and not just related to my world.

**To Reproduce**
1. Go to 'Maps'
2. Click on 'Edit Map'
3. Scroll down to 'Create a new marker'
4. Type "flat" in the seach bar
5. See error
6. Alternatively go to any map with the affected icons on

**Expected behavior**
The correct icons to appear

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![map](https://user-images.githubusercontent.com/88499880/128372640-5a854fef-9372-4051-a5ca-d1db04d17cd2.jpg)

**Comment by iamromeo** [comment]
I am aware of what caused this - I will be taking care of it in the morning
