### ISSUE TITLE
Article Comments, Reply, Private

### ISSUE THREAD

**Issue by graylion-wa** [worldanvil/worldanvil-bug-tracker#488]
**World Anvil Username**:

Graylion

**World / Campaign / RPG Character / Manuscript Title**:

Creation

**Feature**: 

Article Comments, Reply and Private

**Related URLS** (To public & visible pages add screenshots otherwise):

[Uncouth Theater Article](https://www.worldanvil.com/w/creation/a/uncouth-theater-landmark)

**Describe the Issue**
A clear and concise description of what the issue is.

**To Reproduce**

1. Go to an article with a users comment
2. Hit replay
3. Checkmark the private box
4. Type a reply
5. Leave comment
6. Copy article url to incognito 

**Expected behavior**

I was hoping that this would leave a private reply for the users original comment. I understand this may be beyond the scope of how this currently works.

**Screenshots**
![Article Comments Reply Private](https://user-images.githubusercontent.com/79761754/128427871-dde62989-0d0d-45e8-b455-1ee710813cfd.jpg)

**Comment by iamromeo** [comment]
That won't be possible to implement at this point
