### ISSUE TITLE
Map marker creation - Unsynchronized initial marker position and coordinates

### ISSUE THREAD

**Issue by MGatta** [worldanvil/worldanvil-bug-tracker#489]
**World Anvil Username**: MGatta

**Feature**: Map

**Describe the Issue**
When creating a new marker (on the editing mode) the marker appears right in the middle. However, if you create a marker without moving it, the created marker is not in the middle, but rather on the bottom left corner. This gets particularly confusing when creating invisible markers.

**To Reproduce**
1. Go to a map's edit mode
2. Create a test marker, without moving the pin
3. See map and marker at the bottom left rather than the centre

**Expected behavior**
For the marker to be in the position the marker was at when the "Create Marker" button is pressed.

**Screenshots**
![image](https://user-images.githubusercontent.com/80196715/128500253-7bc4cf80-6829-4aa6-b579-e55c6e029c67.png)

**Comment by iamromeo** [comment]
Not a bug works as intended.
