### ISSUE TITLE
Export Worlds & Manuscripts does not generic/old-type Statblocks

### ISSUE THREAD

**Issue by marius-djaedr** [worldanvil/worldanvil-bug-tracker#49]
NOTE: this is a duplicate of https://github.com/worldanvil/worldanvil-bug-tracker/issues/47, as that issue was closed prematurely. I give further details below.

**World Anvil Username**: Marius D'jaed'r

**World / Campaign / RPG Character / Manuscript Title**: Magus

**Feature**: Export Worlds & Manuscripts

**Related URLS** (To public & visible pages add screenshots otherwise): https://toolbox.soullink.docker.worldanvil.com/backup/form

**Describe the Issue**
The export did not include statblocks, even though I checked "Include Statblocks".

**To Reproduce**
1. Be only Journeyman tier (this might affect others, but prior ticket was closed as I didn't give enough information)
2. Create a new world
- name the world "Dummy"
- don't fill out "WHAT IS YOUR WORLD ABOUT? (OPTIONAL)
- make it Private
- do not select an RPG system
3. Create a generic article
- name "Dummy Article"
- content "Dummy"
- state: Published, Private, Done
4. Create a new block
- Generic, Text
- title "Dummy Block"
- content "Dummy"
- no tags
- no folder
- leave unchecked "Allow users to view the blocks' page directly and share it with the community."
5. Click on "World Settings" > "Configuration"
6. Click on "Export World" > "Export this World"
7. Fill out the form
- include world "Dummy"
- make sure "Include Articles" is checked
- make sure "Include Statblocks" is checked
9. Click "Start", wait for email with exported files
10. See that the statblocks are not included

**Expected behavior**
Statblocks are included in the files

See attached .zip of what was emailed to me.
[2021-03-09T12_17-export.zip](https://github.com/worldanvil/worldanvil-bug-tracker/files/6108403/2021-03-09T12_17-export.zip)

**Comment by marius-djaedr** [comment]
Alright, is there an issue tracker for the API? Is there already a ticket/issue opened for this, or should I open one?

**Comment by Kordishal** [comment]
This is the issue tracker for that. But as Dimitris has switched the Status this will not be fixed. The API will be reworked at some point.
