### ISSUE TITLE
Copy & paste does not work from Word into Articles with Plato Editor

### ISSUE THREAD

**Issue by iastreb** [worldanvil/worldanvil-bug-tracker#490]
**World Anvil Username**: KoshcheiBessmertnyi

**World / Campaign / RPG Character / Manuscript Title**: Gethen, others

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is. I'm having an issue with editing World Anvil posts. I'm trying to copy-paste materials into the Play Session reports, but getting no results (nothing is copying into the window). I have never had this issue before. Please help.\

Boris Stremlin
Master-level subsciber

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected to happen. Never had this issue before - transferred a lot of material from other sources. Expect pasted material to be shown on the screen, and saved (neither is happening).

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
hello @iastreb I am really sorry but I am struggling to understand what exactly is going on. 
1. Where are you pasting from
2. Where exactly are you trying to paste into
3. What are you trying to paste
4. Which browser are you using
5. Which World Anvil editor are you using
6. Can I have a video of this happening 

Please provide URLs / content in an external file is possible.

**Comment by iastreb** [comment]
Pasting text from a word doc.
Using Chrome.
Not clear on what you mean by World Anvil editor
Don't have a video, and not sure a video would reveal. The bell in the
upper right-hand corner says changes are saved when I paste in text, but
the window remains empty.
Curiously, when I tried uploading the same word docs to Google Drive, and
then paste the text into the article, that seemed to work fine.

**Comment by Kordishal** [comment]
Yeah. Pasting from Word rarely works. Try copy-pasting without formatting or keep pasting via a note app / google docs.

And you probably use the Plato editor. Try switching to source mode from that editor or switch to the Euclid editor. There you might have more luck.

Check out this [Guide](https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors) to learn how to do that.

**Comment by iamromeo** [comment]
Not a bug, this is not a feature.

**Comment by iastreb** [comment]
Thanks!

**Comment by iastreb** [comment]
Not a bug, not a feature? ;)

**Comment by Kordishal** [comment]
There is no implementation that would allow formatted copying. Hence it is neither a bug nor a feature. Format copy-pasting doesn't just work out of the box :)
