### ISSUE TITLE
Map editor is no longer working. 

### ISSUE THREAD

**Issue by NUG-Soul** [worldanvil/worldanvil-bug-tracker#491]
**World Anvil Username**: Soulleesi

**World / Campaign / RPG Character / Manuscript Title**: NUGaming's Dark Desires

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise): 

**Describe the Issue**
A clear and concise description of what the issue is.

So far, I have been placing polygon pins for biomes/towns from the dashboard editor.
My editors were placing pins yesterday in the presentation mode, once they had finished placing them, I went through and edited each pin, adding info, linking them to things and replacing the pin icon.
When I went to bed everything was working fine, but when I went on to the world builder this morning and I can't do anything.
What I mean by this is that there is no longer the default placement pin on my map in the dashboard map editor, and nothing happens when I right click. Also, none of the placed pins were visible and neither was the group pin drop down menu.

So, because I did edit some of the pins placed by my editors to be custom pins, I thought that might have been the problem, so I deleted those first. When that didn't fix anything, I went through and deleted anything that had been edited at all, that didn't help either. So, I then deleted anything not placed by me. Still no change. 

Meanwhile, I was getting my editors to check on their ends to see if they were experiencing the same thing on their end, and they were. With each change I made, I got them to check if it fixed it on their end, but they were getting the same issues as me. They had both logged off hours before I went to bed, and had not been back on until I asked them to check if they were experiencing what I was.

It was at this point that I went on to the World Anvil discord and asked for help. It was suggested that I try creating another map and see if it was the same issue on both. So, I did and it was the same on the new map, for me and my editors.

So now I'm not sure what to do. Any help to resolve this issue would be appreciated. 
Thank you for your time.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
I will assume that you are referring to this map: 
https://www.worldanvil.com/w/nugaming-s-dark-desires-soulleesi/map/b3f5a59c-3853-41c2-8f01-d5653ec5cc2d
(please provide reproduction steps next time) 

The error on the page is probably referring to the use of the + sign on a title or description on one of your pins. 
From what I can see: 
		var **Daily+StoryQuests**SoulleesiIcon = new L.Icon({

Remove the + sign and any other special characters from the naming of pins AND custom made pins and it should be fine

**Comment by NUG-Soul** [comment]
That seems to have fixed it. Thank you so very much for your time and help.

**Comment by iamromeo** [comment]
You are most welcome :)
