### ISSUE TITLE
Map Icons and Info Gone

### ISSUE THREAD

**Issue by RayAnneFairchild** [worldanvil/worldanvil-bug-tracker#492]
**World Anvil Username**: Eterra

**World / Campaign / RPG Character / Manuscript Title**: Eterra - Aetatha

**Feature**:  Map

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/eterra---aetatha-eterra/map/8c40571a-a73e-446b-ae2a-b799e23a8510

**Describe the Issue**
Several pins placed on the map are gone as of yesterday, namely ones using the flat black church icon, a tavern icon, and a few using the settlement, large village small town icon.  There are I believe 10 missing, all would have been placed on different days and at different times. 

**To Reproduce**
Not sure it can be reproduced

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
This map is Private I cannot actually see in order to understand the issue. Can you please set the map and/or world to public or give us access so we can have a look?

**Comment by Kordishal** [comment]
This is not something we can help with here. A few questions for you to figure out what is going on:

Does this mean only a part of the icons are missing? Not all of them?
Are the markers themselves still there? You can check in the list of markers on the second tab in the map editor.
Are the icons gone both in presentation and in the editor?
And we'll need a specific list of the icons that are missing. You should be able to reference them by checking the marker list.
