### ISSUE TITLE
My Map markers are gone

### ISSUE THREAD

**Issue by Fuevo** [worldanvil/worldanvil-bug-tracker#493]
**World Anvil Username**: AtalantaDM

**World / Campaign / RPG Character / Manuscript Title**: Atalanta

**Feature**: Map

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/atalanta-atalantadm/map/b71ab4a5-cb7b-4bec-bdf3-4d5ef651443e 
https://www.worldanvil.com/world/map/b71ab4a5-cb7b-4bec-bdf3-4d5ef651443e/edit

**Describe the Issue**
All of my markers show up on the marker edit page, but when I go to look at my map, 90% of the markers aren't there. Unsure what to do

**To Reproduce**
1. Go to the maps page in my account
2. Click on Atalanta map
3. Scroll around to see that there are very little markers
4. See error on the edit markers page to notice how many markers there really are compared to what's being shown

**Expected behavior**
I would love to see all my markers back on the map. However that happens is okay by me, even if it's a fix on my end.

**Comment by iamromeo** [comment]
@Fuevo your map pins are not gone - there is a script error on your map due to the flat black church icon

**Comment by iamromeo** [comment]
(Closed by mistake) 
These icons changed name because they had an extraneous "1" at the end. Editing the pin which is using the flat black church icon and resaving should fix the issue. 

I will try to automate the correction but it cannot happen before the 17th of the month

**Comment by iamromeo** [comment]
I have managed to fix this remotely this should all be done now.
