### ISSUE TITLE
Call of Cthulhu Character Sheet issue

### ISSUE THREAD

**Issue by arturkonczalski** [worldanvil/worldanvil-bug-tracker#495]
**World Anvil Username**: CarryGuun

**World / Campaign / RPG Character / Manuscript Title**:Zew Cthulhu / Żelazny duch

**Feature**: Character Sheet Call of Cthulhu issue

**Describe the Issue**
In Call of Cthulhu character sheet, all stats and skills are set up to maximum of 99, which is incorrect, as in this system you can easily get stat or skill above 100.

**To Reproduce**
1. Go to any character sheet created based on Call of Cthulhu template
2. Click on field to fill stat or skill value, enter 100 or more
3. See error

**Expected behavior**
There should be no limit to skill or stat value, as in this system it does not have a limit.

**Screenshots**
![worldanvil error 1](https://user-images.githubusercontent.com/67600219/128888022-df8a5047-fadf-4340-af98-bdc490f6b698.png)
![worldanvil error 2](https://user-images.githubusercontent.com/67600219/128888179-db73747f-63b0-467e-939c-f2cf2ba75f1f.png)

**Comment by Kordishal** [comment]
Statblock templates are created by community members and not by the World Anvil team. You can find the author of this template at the bottom of your sheets view. 

Please contact them to get this changed.
