### ISSUE TITLE
RPG MAKER MV

### ISSUE THREAD

**Issue by adeafblindman** [worldanvil/worldanvil-bug-tracker#496]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

RPG MAKER MV:
RPG MAKER MV:
adeafblindman:

https://www.rpgmakerweb.com/products/rpg-maker-mv:

https://assets-global.website-files.com/5efc0159f9a97ba05a8b2902/5f1a938248b9f810a0a79439_rpg-maker-mv-logo-en-p-500.png:

https://www.rpgmakerweb.com/terms-and-conditions#:~:text=be%20in%20writing.-,Copyright,-All%20content%20included:

**Comment by Kordishal** [comment]
This is a video game engine, why do you want this as a TTRPG system?

**Comment by iamromeo** [comment]
Apart from the fact that this is not an RPG game the user is also not a Grandmaster+
