### ISSUE TITLE
Error 504 / cannot access site

### ISSUE THREAD

**Issue by iRoguex** [worldanvil/worldanvil-bug-tracker#497]
**World Anvil Username**: Rogue_

**World / Campaign**: Exanthia

**Feature**: Homepage

**Describe the Issue**
Cannot access the world anvil site, can sometimes get to the dashboard, then whenever I click on articles or view world it has a very long loading time resulting in an error 504 saying that the gateway has crashed. It has been like this for about 4-5 days, not sure if this is a bug or known. I can sometimes get the articles tab to open but then cannot open any of the categories or articles to edit them, would love to get back to building soon. :(

**Expected behavior**
to be able to open and use the articles and view world tabs

**Screenshots**
![20210810_182037](https://user-images.githubusercontent.com/88844780/129226396-9b0bc075-c5fe-4f37-8ed6-f4a59699964b.jpg)
![20210812_160302](https://user-images.githubusercontent.com/88844780/129226431-720f1440-2bec-4cbb-b209-fdefbb6c41e8.jpg)

**Comment by iamromeo** [comment]
That indeed looks like a localised networking issue - we did not have any other instances being reported and from our end the servers show no issues.. I will be closing this since there is nothing we can action 

Thank you for bringing this to my attention regardless
