### ISSUE TITLE
Random Generators break ampersand (&) in urls

### ISSUE THREAD

**Issue by Wcubed** [worldanvil/worldanvil-bug-tracker#498]
**World Anvil Username**: brass_phoenix

**Feature**: Urls in random generator output

**Describe the Issue**
When a url appears in the output of a random generator template, any`&` are replaced with `&amp`. This is breaking the link.

For example: `/world/location/new?type=landmark&title=testing&content=VignetteContent`
will become: `/world/location/new?type=landmark&amptitle=testing&ampcontent=VignetteContent`.

Note that putting a space behind the `&` tricks the replacer to leave it alone.
So `/world/location/new?type=landmark& title=testing& content=VignetteContent` stays as-is. This _does_ work, but is bypassing the sanitizer, and might be relying on lenient browser behaviour to actually function.

**To Reproduce**
1. Create a new random generator template.
2. Add a link: `[url:https://www.worldanvil.com/world/location/new?type=landmark&title=testing&content=VignetteContent|tab]Start writing![/url]`
3. Save and go to this generators output page.
4. Roll the dice
5. The output will be `[url:https://www.worldanvil.com/world/location/new?type=landmark&amptitle=testing&ampcontent=VignetteContent|tab]Start writing![/url]`
6. Click the link.
7. Notice that the type of new article is correct (landmark) but that the title and vignette are empty.

**Expected behavior**
As far as I can tell, it should instead replace `&` with `&amp;` (note the semicolon).

**Comment by iamromeo** [comment]
I am sorry but I cannot find any user with the username: **Wcubed**
which is your account?

**Comment by Wcubed** [comment]
Oh, I appear to have filled in my Github username instead of the Worldanvil one. Sorry about that.
My username is brass_phoenix

**Comment by iamromeo** [comment]
I will be addressing this on the next update.

**Comment by Wcubed** [comment]
Thank you :+1:. Just a question though: Is the label "will not fix" then not incorrect? Or will the next update do something that makes this issue no longer applicable :smile:?

**Comment by iamromeo** [comment]
Will not fix because it will not longer be relevant with the new implementation :) for the time being try to stay away from ampedsands :)

**Comment by Wcubed** [comment]
Good to hear :grinning:
