### ISSUE TITLE
Parent Names in family tree do not reflect updates in character sheet

### ISSUE THREAD

**Issue by JohnnyOpie** [worldanvil/worldanvil-bug-tracker#5]
**World Anvil Username**: John Parker

**World / Campaign / RPG Character / Manuscript Title**: Taling Times: 1865, Mildred May Chesterton

**Feature**: Family Tree

**Related URLS** (add URLs of the pages that do not work!):
https://www.worldanvil.com/w/tailing-times3A-1865-john-parker/a/chesterton-family-tree-article
https://www.worldanvil.com/w/tailing-times3A-1865-john-parker/a/mildred-may-chesterton-person-1

**Describe the bug**
The name displayed in the family tree is a previous version.

**To Reproduce**
1. Create a character "Mother" with a placeholder name.
2. Create a second character "Son" and designate the "Mother" character as the biological parent on relationships tab.
3. Click "Copy Family Tree Embed" button.
4. Create a generic article "Show Tree"
5. Paste family tree into Content pane.
6. Save Changes
7. Preview Show Tree page.
8. Return to "Mother" character.
9. Edit Character Title "Real Mother Name"
10. Return to "Show Tree"
11. Error: Family tree still shows "Mother" instead of "Real Mother Name"
12. Click on "Mother" to see relationships (to husband, in this case since child relationships are not displayed)
13. Error: "Mother" in title and "New Mother Name" in relationship.
![Family Tree Error - Mildred May Chesteron](https://user-images.githubusercontent.com/8194393/109392847-af59c900-78db-11eb-8a63-ff0f79b063a8.JPG)

**Expected behavior**
The mother's name in the family tree should be updated.
Note: Sibling names updated automatically.
Troubleshooting done: 
1. Clear cache. 
2. Remove all relationships to "Mother"
3. Save
4. Reassign relationships
5. Copy and paste new tree embed code (was the same code - expected, but double-checking)

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Hi, I cannot reproduce this issue and your links are private. Could you make your articles public?

**Comment by JohnnyOpie** [comment]
HI, Thanks for looking. I made them public. Please try again.

**Comment by Kordishal** [comment]
Hi I found your issue. It is not a bug, but instead you only changed the title of the article. The names for the family tree are also source from the naming tab under the prompts of the Character template. You forgot to change the name there as well.

**Comment by JohnnyOpie** [comment]
Got it. Sorry for the false report.
