### ISSUE TITLE
Artemis short cuts lead to a 404 page while no world is active instead of warning the user of the issue

### ISSUE THREAD

**Issue by 189969** [worldanvil/worldanvil-bug-tracker#500]
**World Anvil Username**:Nightshade189969

**World / Campaign / RPG Character / Manuscript Title**: Not sure here, I simply can’t create anything 

**Feature**: create new article

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/world/person/new Screenshot: https://imgur.com/a/Y72w75c

**Describe the Issue**
A clear and concise description of what the issue is.

I recently joined WorldAnvil, and was given editing access to a friend of mine’s campaign. I cannot add any new articles there or on my own page. It doesn’t matter if I’m creating a character, country, document, item, etc. I click on the create button and I’m immediately redirected to the 404 “thus you’ve reached the end of this world” page with the dragon on it. This issue was present before I was given editing access and is still here. I was able to create my first character when I joined but after that this bug hasn’t been allowing me to create anything new. I can edit my existing character just fine, I simply can’t create anything else. It’s been going on for nearly two months now. 

**To Reproduce**
1. Go to 'my page/your page?'
2. Click on 'the arrow button at the bottom right corner'
3. Scroll down to 'click on any of the “create” options that come up'

**Expected behavior**
I was expecting to be guided to the article creation page. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

some screenshots: https://imgur.com/a/B636PoU

**Comment by Kordishal** [comment]
Hi! You are attempting to create articles while a character is active. This does not work. You first need to create a world and then create articles for it. If you wish to just add articles to your friends' world, you'll have to activate their world before adding articles.

You can activate a different World or Character by clicking on the text Cassipeia in the upper left corner with the small chevron. Then select a new world or your friends world to get started.

For Dimitris (@iamromeo): Maybe it would make sense to grey out these Artemis short cuts when no world is active!

**Comment by iamromeo** [comment]
Note: Artemis should probably be disabled when a character is active or at least the sections related to a world.

**Comment by Kordishal** [comment]
Though I just realized that you can switch activation with Artemis as well. So you can just type "a" and then select the world of your friend to activate and then start creating new articles.

**Comment by iamromeo** [comment]
This will be addressed with the new feature update for this component
