### ISSUE TITLE
Textareas change colors and font size when focused which makes it hard to edit

### ISSUE THREAD

**Issue by Tillerz** [worldanvil/worldanvil-bug-tracker#501]
**World Anvil Username**: Tillerz

**World / Campaign / RPG Character / Manuscript Title**: Sheet-Creation

**Feature**: example: edit fields for stat blocks/sheets.

**Related URLS** (To public & visible pages add screenshots otherwise): Just any edit fields/text areas where you edit WA stuff.

**Describe the Issue**
When you click into an input field/text area, the textarea suddenly switches from black text/white background to white text/black background and ALSO the font size changes. The result is that if you target into the textarea with the mouse and click on a word, the cursor ends somewhere completely else, making quick editing impossible. Also the color switch is really distracting.

**To Reproduce**
1. Go to Creative Studio / Sheets & Blocks
2. Create a new Block template
3. Click into one of the sheet textareas (color change!)
4. Paste in some longer text
5. Focus some other element of the UI with the mouse.
6. Click back into the textarea and try to click a specific word. Does not work.

**Expected behavior**
No color change. no font size change. Input fields should never change when you focus them (at least their inside, no one complains about a highlight of it's outside border or something to show it's on focus)

**Comment by Kordishal** [comment]
```css
input.form-control:focus, textarea.form-control:focus {
    color: #ffffff !important;
    background-color: #000000 !important;
    font-size: 12px !important;
}
```
This CSS seems to be the problem which is applied at least the in the studio. This CSS needs to be removed / replaced with something that is theme aware and does not change the font size.

**Comment by iamromeo** [comment]
Fixed wil deploy later on

**Comment by Tillerz** [comment]
Thanks so much, that is really helping a lot! \o/ *hugs*
