### ISSUE TITLE
Mention uncreated Article in Event doesnt work

### ISSUE THREAD

**Issue by DragonSky074** [worldanvil/worldanvil-bug-tracker#502]
**World Anvil Username**:DragonSky074

**World / Campaign / RPG Character / Manuscript Title**:Equanox

**Feature**: Mention Articles in Historical Events

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.
I can mention Articles that exist already without a Problem, but i cant mention Articles that arent created yet. On other Articles it works perfectly, the new Article is created and also added to my to-do list. But when i create a Historical Event, that feature just doesnt work. Also, i am the only Author working on this World, so its not a permissions thing. 
**To Reproduce**
1. Go to 'Quick Content Creation'
2. Click on 'Create Event'
3. Mention a new Article with '@Test(character)'
4. it doesnt create a new Article and also doesnt put anything in my To Do. 

**Expected behavior**
It would be awesome to make that Feature work too, so that i can make up characters in the Event and finish the Character after.

**Comment by iamromeo** [comment]
I am really sorry but this is not a bug this is a lack of a feature. please feel free to fill a concise feature suggestion. I will be honest,I am not exactly sure what is it that you are trying to achieve. 

Placeholders is a shortcut system that can be used when you are creating articles. Most people have migrated for months now on creating articles using the + button and then the quick creation of placeholder articles that can be mentioned once created.

**Comment by DragonSky074** [comment]
Hey,
I am still pretty new to World Anvil and didnt realize how Placeholders
work, but i will now test around with them a little bit more, maybe that
already solves my problem. Otherwise i will issue a Feature Suggestion, i
have enough coins.
Max

Dimitris Romeo Havlidis ***@***.***> schrieb am So., 15. Aug.
2021, 21:10:

**Comment by iamromeo** [comment]
Awesome! Have a wonderful day -  I would strongly suggest you learn how to quicklyuse the + button on the bottom right and purple quick create - it will be really refreshing - trust me on this :)
