### ISSUE TITLE
RPG System Request - Vampire the Masquerade 5th Ed

### ISSUE THREAD

**Issue by FaeBun** [worldanvil/worldanvil-bug-tracker#503]
(As a disabled, limited income, individual, I also feel the need to state that I feel extremely excluded that this ability to request a new system, and even the ability to create full character statblocks, is limited to your most expensive tier.)

**Full Name (RPG SYSTEM)**: Vampire the Masquerade 5th Edition
**List Name** (Name under which it should be listed on World Anvil): Vampire the Masquerade 5th Edition
**World Anvil Username**: FaeBun 

**Website**: https://www.worldofdarkness.com/products/tabletop-games

**Logo Image Link**: https://s3-eu-north-1.amazonaws.com/pdx-campaign-wp-data/uploads/sites/10/2019/12/08155746/logo_vampire.png

**Logo Usage Terms (URL)**: https://www.worldofdarkness.com/dark-pack  (I believe this is what you are asking for, forgive if it's incorrect)

**Comment by iamromeo** [comment]
It already exists under World of Darkness. VtM 5e is not a system it's a flavour of one - The VtM 5e sheet already exists under that system 

I am also disabled - I am not sure what this has to do with anything though.

**Comment by FaeBun** [comment]
I was stating my disability is the reason for my limited income, explaining and apologizing in advance of I'm over stepping a bounds, while also pointing out the unfairness of putting such a simple and crucial RPG factor behind your most expensive pay wall.

I mean, arguably that's an extreme over simplification of the World of Darkness system, and VtM's stand alone system. As White Wolf created each system to not only stand alone, but to have their own unique factors that made them very different. Calling VtM and CtD and MtA the same game is a stretch, but I do see the point and reason for combining them in this context, so I concede the point.

**Comment by Kordishal** [comment]
Having a system or not is a completely irrelevant by itself. Having a specific system is only useful when there are statblocks that go with them.

Creating custom statblocks is an advanced fearture that requires some direct action from Dimitris for publication of a new sheet. So it makes sense to have this on the Grandmaster level. :)

**Comment by FaeBun** [comment]
But, I mean, VtM, CtD, MtA, WtF, Wraith, etc all do have different and varying stats that use different rules that are. Indeed, unique to each system while there are comparatives between the systems, each system is different enough that one couldn't just say a Kindreds Gifts is the same as a Mages magic, or a Changelinge's Art's & Realms. Even their morality systems are often different. We shall see how these change, or don't, with the new 5th edition, but again, these aren't factors to ignore. Though, as I've said, I understand the reason to combine it under one banner for the purpose of unified play across the systems (which 5th ed has started they are putting increased focus on). So, once again, I'll concede the point despite feeling it's important not the ignore how significantly different the systems are, and can be going forward as you implement the future ones into your system.

I would also like to apologize once more. I misunderstood what it was that was locked under grandmaster. Been under a lot of stress lately, and brain has been extra foggy (but that excuse it).
