### ISSUE TITLE
Error when Saving or Reloading page

### ISSUE THREAD

**Issue by AmeliaNite** [worldanvil/worldanvil-bug-tracker#504]
**World Anvil Username**: amelianite

**World / Campaign / RPG Character / Manuscript Title**: World Feature

**Feature**: Bug

**Related URLS** (To public & visible pages add screenshots otherwise): [https://www.worldanvil.com/uploads/images/b2d5da73c3c1f04e3fc46ecb24e1d9c2.png](url)

**Describe the Issue**
I've been trying to ignore this issue for a while, but every time I click the save button and it reloads the page as "saved," I tend to get this issue, where it claims that WA is either "down" or that WA "changed its address permanently." I can then reload the page, hit a "confirm reload," and then get back to the page I was editing for it to show that my work was indeed saved. This has been a tedious process I've been dealing with for two days now while working in WA.

This also occurs when I try to view anything on my world or even a statblock.

I use the Chrome browser.

**To Reproduce**
1. Go to any article, statblock, etc.
2. Click on "edit" and then click on "save".
3. Wait for it to attempt to save/load.
4. See error.

or

1. Go to view article, statblock, etc.
2. Attempt to reload the page.
3. See it flash the error for a split second and then load the article, statblock, etc.

**Expected behavior**
For the reload after saving to pop up the image above and claim that WA is down or changed its address.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Hello there. :) 

Obviously this is not something that anyone else is experiencing (there would have been a coup if there was :P) and there is no way to replicate it. 

These issues most of the time are related to networking problems. Either on a provider or local level. In either way this is not something that I can do anything about, this is not a WA issue. 

From what I can see here
https://kinsta.com/knowledgebase/err_quic_protocol_error/

QUIC is some sort of Chrome experimental protocol
