### ISSUE TITLE
Random generator sidebar has incorrect info

### ISSUE THREAD

**Issue by Wcubed** [worldanvil/worldanvil-bug-tracker#505]
**World Anvil Username**: brass_phoenix

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: Random generators

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/studio/generators
https://www.worldanvil.com/random-generators

**Describe the Issue**
The `generators` page says `Character is actually "person" and ethnicity is "ritual"`.
Which is not true, and might confuse people. "Tradition / Ritual" is actually "ritual" and the value for "ethnicity" is simply "ethnicity" 😃.
"character" does indeed have "person" as url value.

There is also a typo under the "Utilities & tools" in the same sidebar. It says `Alternatively you can use existsg that will print its content if the variable exists.` which has `existsg` with `exists` green, so I am guessing the `g` is from a `green` tag :P

As an additional polishing nit-pick, the https://www.worldanvil.com/random-generators page has a paragraph in it's sidebar that introduces the random generators. The last sentence says `If you are a grandmaster, you can create your own your own`, note that it has `your own` twice. the first is a link, the second isn't.

**Comment by iamromeo** [comment]
Thank you!

**Comment by Wcubed** [comment]
No problem :+1:
