### ISSUE TITLE
Campaign Plots Error

### ISSUE THREAD

**Issue by Semjax** [worldanvil/worldanvil-bug-tracker#506]
**World Anvil Username**: Semjax

**World / Campaign / RPG Character / Manuscript Title**: The "To Be Named" Campaign

**Feature**: Plots

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/heroes/campaign/3ff00eca-255a-45ce-84e5-b04afc3ddc0b/dashboard

https://www.worldanvil.com/heroes/campaign/plot/list

![image](https://user-images.githubusercontent.com/88988969/129600596-68dc31a5-70ba-4292-8bb5-049ac0af7ec1.png)

**Describe the Issue**
A clear and concise description of what the issue is.
For the past couple weeks, every time I try to go to the Plots page in my campaign I get the same error: "This Page Isn't Working." I can still find my plot articles but I have to go to my articles page or search them. I don't know if this is an error across the site or if it's just an error with my campaign.

**To Reproduce**
1. Go to 'https://www.worldanvil.com/heroes/campaign/3ff00eca-255a-45ce-84e5-b04afc3ddc0b/dashboard'
2. Click on 'Plots'
3. Scroll down to '.No scrolling necessary'
4. See error that the page can't be displayed. HTTP error 500.
![World Anvil Plots Error](https://user-images.githubusercontent.com/88988969/129601369-e8ebb308-ee4b-49cd-8a1e-11a52a12b77b.PNG)
![World Anvil Plots Error 2](https://user-images.githubusercontent.com/88988969/129601383-f54306f6-2d9c-46ee-8389-ae2eb176ce44.PNG)

**Expected behavior**
I'd love to be able to use my Plots page again.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Hi, this issue is most likely caused by a circular reference in plots. E.g. one of your plots has itself as a parent through some kind of connection you made. Once this is fixed the page will be available again.
