### ISSUE TITLE
Map toggle in Homepage not working

### ISSUE THREAD

**Issue by mantricore** [worldanvil/worldanvil-bug-tracker#507]
**World Anvil Username**: mantricore

**World / Campaign / RPG Character / Manuscript Title**: The Primordial Vale

**Feature**: Homepage/Map

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/the-primordial-vale-mantricore

**Describe the Issue**
I tried to remove the map on my homepage. When I uncheck the "Display this map on the World's homepage" option in -> Map Settings -> Display & Privacy, it does not remove said map from my Homepage.

**To Reproduce**
1. Go to Maps
2. Then select the "Edit" option under "Main Lands"
3. In the header, select "Map Settings"
4. Under that, select "Display & Privacy"
5. Uncheck the first option, which should be "Display this map on the World's homepage."
6. On the right side, click "Save Changes"
7. Click on "[View World](https://www.worldanvil.com/w/the-primordial-vale-mantricore)" on the left side.
8. The map is still at the top over the world's banner.

**Expected behavior**
The map should toggle on/off when the appropriate checkbox is ticked.

**Screenshots**
N/A

**Comment by Kordishal** [comment]
That is not the right setting for that. You set the World Master Map. 

You can find this setting under World Settings > Configuration > Display > Global Content. The first dropdown. Use the small x to remove the selection and then save.
