### ISSUE TITLE
Co-owner having issues editing Dictionary

### ISSUE THREAD

**Issue by MeisterFluffbutt** [worldanvil/worldanvil-bug-tracker#508]
**World Anvil Username**: MeisterFluffbutt

**World / Campaign / RPG Character / Manuscript Title**: Alkapayi

**Feature**: Dictionary / Language Article

**Related URLS** (To public & visible pages add screenshots otherwise): 

![WA_bugreport_dictionary_article](https://user-images.githubusercontent.com/89082519/129729084-2be12eac-89ef-42e9-8b30-57973c3738a8.jpg)

**Describe the Issue**
As a Co-owner of the World "Alkapayi" I am unable to edit the words in the Dictionary (replaced in the Screenshot with test-words). Other issues like ad-/pop-up-block, VPN, Incognito or Browser have been tested.
I am able to edit languages and dictionary words in my own world.

The Moment I try to edit words in the dictionary of Alkapayi, nothing happens (the button blinks, no changes otherwise)!

**To Reproduce**
1. Go to 'a language article of a world, where you are co-owner'
2. Click on 'Edit Language'
3. Scroll down to 'Show Template Specific Prompts & Connections'
4. Click on 'Dictionary'
5. Try to 'edit word'
6. Nothing happens

**Expected behavior**
I wish to be able to edit the words in the Dictionary, even if i am only a co-owner.

**Screenshots**

![WA_bugreport_dictionary](https://user-images.githubusercontent.com/89082519/129730180-28f0912e-2bf0-42bb-b03e-9bf9ad6e1216.jpg)

**Comment by iamromeo** [comment]
fixed
