### ISSUE TITLE
Anime 5E Request from a new user.

### ISSUE THREAD

**Issue by zero127** [worldanvil/worldanvil-bug-tracker#509]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Anime 5E - Fifth Edition Anime Role-Playing Adventures**:
**Anime 5E** (Name under which it should be listed on World Anvil):
**keeperoflenneth**:

**http://www.dyskami.ca/anime5e.html**:

**I'm not sure they have a dedicated hosted logo**:

**See above; Just thought i'd suggest it. It's fairly fresh out of kickstarter, physical goods haven't even fully shipped yet. Far as things go, I could crop one out or do a proper vector one on their behalf (i'm a web developer/designer). But overall I couldn't find anything regarding usage of the logo on its own. Everything on their materials is free for personal use, so I'd assume contact with Dyskami directly would be needed. Sorry if this is/was a waste of time. :) I appreciate world-anvil and the A5E system both. Hopefully it can get connected some day.**:

**Comment by iamromeo** [comment]
Added
