### ISSUE TITLE
Toggling NSFW

### ISSUE THREAD

**Issue by iveeeeeeeeeeee** [worldanvil/worldanvil-bug-tracker#510]
**World Anvil Username**: Ivy O'Haven

**World / Campaign / RPG Character / Manuscript Title**: Haven

**Feature**: Account Features and Account Details

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/dashboard/user/features 
https://www.worldanvil.com/dashboard/user/account

**Describe the Issue**
When going to an NSFW page there is a warning page. It gives you the option to go to your account settings to allow you to view NSFW content. However, the link takes you to Account Details rather than Account Features where you can toggle NSFW.

**To Reproduce**
1. Go to an NSFW world with NSFW content disabled in Account Features. Click an article for the 'ADULT CONTENT WARNING' page. This page is detailed in the screenshot. It is a generic block or whatever found on any NSFW article when NSFW is disabled.
2. Click on 'Account Settings' hyperlink on 'ADULT CONTENT WARNING' page.
3. Get sent to 'Account Details' rather than 'Account Features'. You cannot enable NSFW on 'Account Details'. You can only enable it on 'Account Features'. This is the error.

**Expected behavior**
I expected to be sent to the page where I can enable NSFW content.

**Screenshots**
<img width="1168" alt="Screen Shot 2021-08-17 at 4 23 23 PM" src="https://user-images.githubusercontent.com/89106395/129802556-5db671d6-e9ef-4ab2-8588-e72c5a8e7f29.png">

**Comment by iamromeo** [comment]
Thank you for the heads up - I will rectify
