### ISSUE TITLE
Too Many Buttons! (Legacy Editor)

### ISSUE THREAD

**Issue by IbbyWondrous** [worldanvil/worldanvil-bug-tracker#511]
**World Anvil Username**: IbbyWondrous

**World / Campaign / RPG Character / Manuscript Title**: Any

**Feature**: Legacy Editor

**Describe the Issue**
I still use the Legacy editor--because its easier for me to use than the new ones-- but lately I've been dealing with a weird bug that occasionally happens when I first load the editor. Basically, the bar up top that holds of the quick BBcode buttons duplicates itself a number of times; 
![image](https://user-images.githubusercontent.com/87488482/129921970-af8a3883-b675-4308-b3cc-3c22bb122539.png)

Sometimes its twice, sometimes it's 3 times. This time I caught it duplicating four times. It's not a serious bug, all the buttons still work fine, and reloading the page sometimes fixes it, but I thought I'd let you know it's happening. 

For extra info, I'm using Opera as my default browser. I haven't tested this issue with other browsers cause I don't have any other ones installed.

**Comment by Kordishal** [comment]
This has been happening for a long time and is unlikely to be fixed. Legacy will stay around but is no longer worked on actively. As this is not a critical issue and does not prevent the use of the legacy editor, it has no priority.
