### ISSUE TITLE
Explanatory Textbox in the secrets page has several typos/missing words

### ISSUE THREAD

**Issue by OndoAlvelle** [worldanvil/worldanvil-bug-tracker#512]
**World Anvil Username**: Ondo

**World / Campaign / RPG Character / Manuscript Title**: Any world

**Feature**: Secrets

**Related URLS**: https://www.worldanvil.com/world/secret/list

**Describe the Issue**
The textbox that appears at the right side of the page currently reads as:
> **Secrets are set to closed**
> This means that only the author of a and users of the assigned subscriber groups can view it. You can alter this so only the author of a secret has access to it by going to the World Configuration under "Display

The text is extremely difficult to understand due to typos and "lost words".

**Suggested rephrasing**
> **Secrets are set to closed**
> This means that only the author of the secret and users in the assigned subscriber groups can view them (instead of all world co-authors being able to view them). You can make secrets visible to all world authors by going to the "Display" tab of the World Configuration and checking the "Open Secrets" option.

I also clarified the word "author" (world author vs secret author) and rephrased the second sentence in a (hopefully) more accurate way. I don't know for sure if this accurately describes the feature, so double-check that before implementing.

(originally reported by another user on Reddit: https://www.reddit.com/r/WorldAnvil/comments/p6i6gu/roughly_two_years_ago_we_signed_up_for_a_1year/)

**Comment by iamromeo** [comment]
Corrected :)
