### ISSUE TITLE
collapse/expand button on Manuscript bin not behaving correctly

### ISSUE THREAD

**Issue by Amancham** [worldanvil/worldanvil-bug-tracker#514]
**World Anvil Username**: Amancham

**Manuscript Title**: Bughunt & Bughunt 2 

**Feature**: Manuscripts

**Related URLS** (To public & visible pages add screenshots otherwise): Seems to happen in all the manuscripts while in writing or view mode. 

**Describe the Issue**
Two issues, actually: 
1) The expand/collapse sign on the bin initially seems reversed: 
* The bin seems to be collapsed when first creating and opening a manuscript, unlike Research folder and Chapter 1 which are expanded (notice the difference in the picture: 
![1_freshmanuscriptstate](https://user-images.githubusercontent.com/25498928/130236650-6fa7979d-6ea4-4eed-ad26-5c01e44d0771.png)   
* However, you can manually drag and drop a file into the bin as if it was expanded like the other folders: 
![2_freshwithdeletedfile](https://user-images.githubusercontent.com/25498928/130236779-8d3c2706-d204-49f3-9871-06ab2f1eaa5e.png)   
* When you then collapse all folders, while research and chapter 1 display the (+) indicating that you can expand them, the bin displays the (-) suggesting, it is already expanded, despite being collapsed (the scene 1 copy file is still inside) 
![3_freshwithdeletedallcollapsed](https://user-images.githubusercontent.com/25498928/130236927-21cb1b5f-8227-4886-b146-8e29feb2a9c9.png)

2) deleting a chapter or scene with the bin open will collapse the folder but not change the collapse/expand button. This means the meaning of the +/- seems to change. See the +/- sign at the bin in the following pictures: 
![delete1](https://user-images.githubusercontent.com/25498928/130249853-8cc88c73-b303-438d-836c-d0ffb936c088.png)   ![delete2](https://user-images.githubusercontent.com/25498928/130249890-c280c72b-7b31-4822-ab7f-4722ff8b6386.png)   ![delete3](https://user-images.githubusercontent.com/25498928/130249901-0a544a7b-09c0-4d01-b923-8cbf2a73e133.png)

It does however not behave this way, if you have the bin collapsed while deleting something. It will remain collapsed and the behavior does not switch. (scene three was deleted with the bin collapsed, see how it still shows the + for expanded state, just as it did before in the previous picture)
![deletenochange](https://user-images.githubusercontent.com/25498928/130249974-67bc93fe-72f3-4c1c-8bdd-8ac759c184c3.png)

**To Reproduce**
1. create new manuscript and open it 
2. Notice that all folders are expanded and show a (-) to indicate the expanded state, while the bin indicates collapsed state with (+) sign next to it
3. Copy scene 1 and drag the copy into the bin 
4. Notice that despite the button indicating collapsed state, you can drop the scene into the bin and it is actually already expanded. You will also notice, if you click the (+) the folder will collapse and now show (-) next to it while you can no longer see the copy of scene 1 we just dropped in there.
5. expand the folder again and create scene 2 and scene 3 files in the chapter 1 folder 
6. with bin expanded and the copy of scene 1 showing, navigate to the chapter overview and hit the small bin sign on the right of one of the scenes to move it to trash 
7. see the bin now collapsed while it still shows a (+) next to it (as before) when you now click (+) it will expand and show a minus to indicate expanded state
8. leave bin expanded, click on one of the scenes in your chapter 1 and navigate to the last tab on the right 
9. hit the "move to trash button" 
10. Notice that again, the bin has collapsed with still showing a (-) next to it and when you click to expand, it changes to a (+) 
11. Collapse bin and delete the last remaining scene from your chapter. you will see, that nothing changes. there is still a (-) next to the collapsed bin, if you click it, it expands, the sign changes to a (+) and all the deleted scenes are showing up

**Expected behavior**
Like all the other folders, (+) should indicate collapsed state and (-) should indicate expanded state of the folder. 
Also, when the bin collapses during deletion of scenes or chapters, the button should change to indicate that the folder is now collapsed or the bin should remain in the same state (expanded) and not automatically collapse just because something was deleted

**Screenshots**
See above

If despite my best efforts this does not explain the issue, I am happy to make a short video or show my screen in discord voice chat to show exactly what is happening. English is not my first language but I have made every effort to explain it as much as possible.

Also sorry for reporting seemingly two bugs but they seem so closely related that it felt wrong to break it into two.

**Comment by iamromeo** [comment]
Fix will deploy today
