### ISSUE TITLE
RPG System Request: Metal Adventures

### ISSUE THREAD

**Issue by kagenotora** [worldanvil/worldanvil-bug-tracker#515]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

This is a decade old French RPG that recently successfully finished a crowdfunding for a version 1.5 of it's base books. 

**Full Name (RPG SYSTEM)**:
Metal Adventures

**List Name** (Name under which it should be listed on World Anvil):
Metal Adventures

**World Anvil Username**:
KiltTora

**Website**:
https://open-sesame.games/gamme-metal-adventures/#toggle-id-2-closed
https://fr.ulule.com/metal-adventures/
https://m.facebook.com/MetalAdventuresOfficiel/

**Logo Image Link**:
https://bucket.mlcdn.com/a/1802/1802488/images/5d662791edb1941d871ac37e5efb34460af7d3a2.png/52638efb46bac3aa7c559dcbd215769a5d695167.png

**Logo Usage Terms (URL)**:
Sorry couldn't find it anywhere.

**Comment by iamromeo** [comment]
Done
