### ISSUE TITLE
hero sidebar button hidden by burger menu

### ISSUE THREAD

**Issue by captainsharmie** [worldanvil/worldanvil-bug-tracker#516]
**World Anvil Username**: mylae-the-dm

**World / Campaign / RPG Character / Manuscript Title**: Altaris: The Tales of Ostal 

**Feature**: button placement

**Related URLS** (To public & visible pages add screenshots otherwise): the issue will only appear when a player of the campaign is logged in with a hero that is part of the campaign, but here is the world link: https://www.worldanvil.com/w/altaris3A-the-tales-of-ostal-legomysuperego

**Describe the Issue**
My character Hero sidebar on the left side of the screen covers most of the text of every article. i spent three days searching for help to discover that there's an arrow button to minimize this, but the arrow is under the burger menu and i have just a few px to click to make it minimize.

please note i am using firefox and OSX 11.5.2, my screen resolution is 2560 × 1600

**To Reproduce**
1. use firefox on a desktop  be logged in as me (or anyone with a character in this world)
2. Click on literally any article and attempt to read it
3. realize the Hero sidebar covers most of the text

**Expected behavior**
the button to minimize this should be anywhere but below another menu, and also the sidebar shouldn't be able to cover article content. should be impossible.

**Screenshots**
![Screen Shot 2021-08-18 at 5 26 31 PM](https://user-images.githubusercontent.com/89318956/130333369-977aa1d3-f06b-44e0-9ca7-7702ca3f1e41.jpg)
shows the problem
![Screen Shot 2021-08-21 at 3 52 00 PM](https://user-images.githubusercontent.com/89318956/130333380-7e8c4745-0d54-4ba6-a8df-e1663e4de662.jpg)
beside that little black box there's a sliver of red, that's the arrow to minimize the hero
![Screen Shot 2021-08-21 at 3 52 09 PM](https://user-images.githubusercontent.com/89318956/130333381-21636bb0-53de-402b-b578-9d23c1f3904e.jpg)
here's what it looks like after the hero has been minimized, the arrow is now at the bottom where it probaly should have been the whole time. please note that the accessibility button is also kind of covering it (but not enough to be an issue)

i forgot to add: it was suggested by the help team on discord to have the world owner go in and use css to fix this problem. this seems like an intense amount of work to fix an issue he's not even facing, and both of us are more likely to find a more intuitive and simple solution for our content management than spend a lot of time figuring out how to make coding adjustments.

**Comment by captainsharmie** [comment]
i forgot to add: it was suggested by the help team on discord to have the world owner go in and use css to fix this problem. this seems like an intense amount of work to fix an issue he's not even facing, and both of us are more likely to find a more intuitive and simple solution for our content management than spend a lot of time figuring out how to make coding adjustments.

**Comment by iamromeo** [comment]
@captainsharmie what is the resolution of your screen so I can test this out

**Comment by Kordishal** [comment]
It says 2560 × 1600 in the post above, but that must be a lot of scaling or zoom for that to be this squished. Can you say how much scaling of the UI or zoom in the browser you have?

And I would like to add that the CSS solution was meant as a workaround in the meantime if you know how to code and if you had asked we would have been able to provide the code and your DM could have just copied that into the right box in WA.

**Comment by Kordishal** [comment]
At around 700 to 900px height, the memories and the global side nav icon overlap. Depends also if there is a character image or not.

**Comment by captainsharmie** [comment]
i don't know how to find out about the scaling or zoom, i'm just providing the information from the system preferences on my computer. 

i'm not a coder so i wouldn't know how to deal with this. also this isn't my world and i'm new to this platform. so i'm not about to deal with code just because i couldn't read some articles. to be clear, i posted this here because they asked me to on discord, not because i expect you to fix it for me. 

i might suggest making it not possible for icons to overlap because i'm just using the default settings of my laptop.

**Comment by iamromeo** [comment]
I am really sorry but we cannot support that kid of zoom level - if this is a 2500 screen this is a zoomed browser and this cannot be controlled from our side
