### ISSUE TITLE
[Bootstrap 5] Visual Issue with on hero character article in world

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#518]
**World Anvil Username**: SoulLink
**Feature**: Article

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/breaking-anvil-soullink/a/john-slow-person

**Describe the Issue**
At the top, the Sheet & Profile tabs are on the left instead of the right.

**Screenshots**
![image](https://user-images.githubusercontent.com/14262536/130346597-b33703a4-9175-4a08-8bf7-b84ca182cd7b.png)

**Comment by iamromeo** [comment]
Can you make this article accessible to me please?

**Comment by Kordishal** [comment]
The world was private...

Should work now :)

**Comment by iamromeo** [comment]
This is reproduced - going ahead with FIX for BS5
