### ISSUE TITLE
RPG Character overlay does not have a defined placeholder image

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#519]
**World Anvil Username**: SoulLink
**Feature**: Player Overlay

**Describe the Issue**
When the character does not have a portrait, there is no image in the overlay and instead just displays the broken image link icon.

**Expected behavior**
Either remove the broken image link icon or add a placeholder image.

**Screenshots**
![image](https://user-images.githubusercontent.com/14262536/130346718-6ea91eef-2aa1-4dc8-b1f2-fb1e36f1e3ae.png)

**Comment by iamromeo** [comment]
Yup will fix
