### ISSUE TITLE
missing most major features

### ISSUE THREAD

**Issue by MillieMBanshee** [worldanvil/worldanvil-bug-tracker#52]
Millie M. Banshee:

I can't access anything but my profile editor and account related stuff. I can't write anything or build anything as the options are not there. The menu on the left side opens to blankness. I took off my ad blocker just in case, still nothing. That little plus button at the bottom that don't work either. I thought I wasn't looking in the right areas but after looking at the getting started video I saw what was wrong. I had no features or tools whatsoever.
![Screenshot (496)](https://user-images.githubusercontent.com/80363872/110547354-ce3b3500-80fd-11eb-814a-3129fc41b8c5.png)

**Comment by iamromeo** [comment]
@MillieMBanshee  It looks like you have disabled pretty much most of the features
Go to **Account Features** and activate the ones you need. 
https://www.worldanvil.com/dashboard/user/features
