### ISSUE TITLE
Shift function in Calendar

### ISSUE THREAD

**Issue by FenDawnchild** [worldanvil/worldanvil-bug-tracker#520]
**FenDawnchild**:

**Ebea**:

**Calendar**: 

**Related URLS** (To public & visible pages add screenshots otherwise):
![grafik](https://user-images.githubusercontent.com/89350614/130361441-79f4d60c-1270-403c-b100-aa594c5599f8.png)
![grafik](https://user-images.githubusercontent.com/89350614/130361473-3be6322a-213d-4782-8e16-73604d6642de.png)

**Describe the Issue**
I have put in a value to shift the New Moon a set amount of days. When clicking on an icon in the calendar the symbol for the phase does not match the actual phase. As visible in the second screenshot, for day five the calendar shows the symbol for Waxing Quarter. Upon clicking on the Symbol it shows up as a New Moon. Due to the 'Shift' the symbols do not match up/the phase seems to be shifted without shifting the symbols as well.

**To Reproduce**
1. Go to Calender
2. Click on Celestial Objects
3. Add a value to 'Shift"
4. Copy Calendar BBC Code
5. Cope the Code into an article
6. View the article with the Code
7. Click on symbol for Lunar Phase
8. See discrepancy between symbol on calendar and in pop-up 

**Expected behavior**
I expected the symbol in the calender to match the acutal Lunar Phase.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by jonaswaeber** [comment]
Hi, this is a knonw issue and you can find a potential CSS fix here: https://github.com/worldanvil/wa-calendar-issue-tracker/issues/5

The calendar is on development hiatus and this issue will not be addressed currently.
