### ISSUE TITLE
Export Error: Job failed: TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by ZephyrSpark** [worldanvil/worldanvil-bug-tracker#522]
**World Anvil Username**: Zephyr Spark

**World / Campaign / RPG Character / Manuscript Title**: MHC World

**Feature**: Export World Not Working

**Related URLS** (To public & visible pages add screenshots otherwise):
<img width="1310" alt="Screen Shot 2021-08-24 at 2 59 42 PM" src="https://user-images.githubusercontent.com/89484563/130683221-0371cc89-0ded-4e5c-a711-721c5b7942a7.png">

**Describe the Issue**
A clear and concise description of what the issue is.
I keep trying to export my world to my laptop via email. I generate the API as shown, fill out all the necessary fields, and press export. But I consistently receive the same message: Job failed: TypeError: argument of type 'NoneType' is not iterable.
<img width="1310" alt="Screen Shot 2021-08-24 at 2 59 42 PM" src="https://user-images.githubusercontent.com/89484563/130681926-4f40ae5a-0667-4bde-b7da-92579939f9ec.png">

**To Reproduce**
https://toolbox.soullink.docker.worldanvil.com/backup/form
Start
Top of the page.

**Expected behavior**
I expect the export to begin, and to receive downloadable Zip of my work via email. The last time I used this feature, it exported without problem. Back then, I only had articles. But since then, I have added four timelines and new articles. I have no idea why I keep getting this message about job failure.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
<img width="1310" alt="Screen Shot 2021-08-24 at 2 59 42 PM" src="https://user-images.githubusercontent.com/89484563/130682137-b28660fd-3755-4183-8024-9f8df5d916a0.png">

**Comment by Kordishal** [comment]
Fixed the issue. World export is available again,
