### ISSUE TITLE
Unify name of charts/content trees

### ISSUE THREAD

**Issue by OndoAlvelle** [worldanvil/worldanvil-bug-tracker#525]
**World Anvil Username**: Ondo

**Feature**: Charts/content trees

**Related URLS**: https://www.worldanvil.com/world/chart/list

**Describe the Issue**
This feature is called "Charts" in the sidebar and page title, but the list of created charts is labeled as "Content trees list", and the button says "Create a new Content Tree". The [pricing page](https://www.worldanvil.com/pricing) says "Content trees & charts" as if they were two different features. When you're [creating a chart](https://www.worldanvil.com/world/orgchart/new), the page title uses "content tree" instead of "chart" and the save button calls it "Organization chart". It's a minor detail, but giving three names to a single feature can be confusing.

**Expected behavior**
All appearances of the name of this feature should be unified to a single one.

**Comment by iamromeo** [comment]
Made changes to naming
