### ISSUE TITLE
Sword and Wizardry is a typo?

### ISSUE THREAD

**Issue by painintheasstoregister** [worldanvil/worldanvil-bug-tracker#528]
**Gray Ghost | Athea**:

**Athea/ The Curse of the Three Maidens**:

**Campaign Settings**: 

**https://www.worldanvil.com/heroes/campaign/settings** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Under the Campaign Settings tab / General Settings/TTRPG System field, I found Sword and Wizardry. Is this supposed to be the option for the Swords & Wizardry TTRPG created by Frog God Games? Or is Sword and Wizardry a completely different entity? Or is it a typo? And if so, can it be fixed? 

**To Reproduce**
1. Go to 'Campaign'
2. Click on 'Settings Tab/Campaign Settings/General Settings/TTRPG System'
3. Scroll down to 'Sword and Wizardry'
4. See error: Should be Swords & Wizardry

**Expected behavior**
Please change 'Sword and Wizardry' to 'Swords & Wizardry'

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Sword and Wizardry Screenshot](https://user-images.githubusercontent.com/89607216/131025527-6945a4f5-2117-4778-b410-5042489f2ee7.png)

**Comment by iamromeo** [comment]
Fixed
