### ISSUE TITLE
Receiving 404 error when saving an existing timeline event entry.

### ISSUE THREAD

**Issue by barryashcroft** [worldanvil/worldanvil-bug-tracker#529]
**World Anvil Username**: barryashcroft

**World / Campaign / RPG Character / Manuscript Title**: Barry's World #1 (Imaginative I know)

**Feature**: Timeline Event Entry

**Describe the Issue**
Receiving a 404 Error when saving an existing timeline event entry.

**To Reproduce**
1. Go to 'Timelines.'
2. Click on 'View Prime Timeline'
3. Select a timeline entry to edit, click on edit.
4. Save changes
5. 404 "Thus you have reached the end of this world."

**Expected behavior**
Save the timeline and return to the entry listings OR stay on entry. Show "entry saved" message. The entry does appear to save OK, despite the error.

**Comment by iamromeo** [comment]
I am sorry but I cannot reproduce that based on the above information
The chanced are that this is an issue with the content added, probably disallowed characters but I cannot be certain without any more details

**Comment by barryashcroft** [comment]
Not sure what else I can say, I log in and do the above and it happens 100% of the time when updating an existing historical entry. I don't get this on creating new items. As far as I can tell there is no use of weird characters in any of the entry text, just the regular English alphabet, numerals, and punctuation in page copy. Titles are typed using English characters and numerals only. I am getting this on every update to an existing historical entry. The only time I used something that may have been an issue was a '#' in the World title but I removed that just not are rechecked everything.

I'd be interested to know what the logs generated for the 404 points towards so I can check the relevant part for disallowed characters. Surely, if a character is disallowed it would be prevented from being saved in the first place, and if the user did enter an illegal/blocked character it should throw a form error informing the user? It is saving the updated information, just displaying the 404 error. After the page is saved what should happen? Should I see the same edit form with a message confirming the successful update? Or is there a redirect to a different page?

I'm really impressed by the system you guys have put together, so for this to happen is quite out of character. At the moment I'm just throwing ideas into the ether in the hopes something will trigger an idea. Without knowing more about how the code works, frameworks, etc. I couldn't even big to hypothesize as to what may be happening under the hood.

**Comment by barryashcroft** [comment]
I have found the culprit. I was thinking about the environment you are running and it got me thinking about what else I can see from my end i.e. what third-party sites are linked/used.

Long story short. The js agent at newrelic.com was throwing a 500 error. I run firefox and have a lot of tracking disabled by default. Allowing tracking through for newrelic.com on WA fixes the issue. Quite why I get a 404 when saving an already existing item is unclear but it looks like, for whatever reason, the new relic script is at the heart of things. It doesn't fail gracefully as you would expect and I'm assuming the 500 error causes an issue in the World Anvil web app resulting in the 404.

**Comment by Kordishal** [comment]
It's weird because I have that JS agent blocked as well and had never issues with it. I assume there are no further details what the error is?

**Comment by barryashcroft** [comment]
No, no further errors I'm afraid. I may take another look at trying to debug it further. It could be a combination of that and something else unique to my browser install that is causing an issue. One thing is for sure, in my opinion at least, this is not a WA bug. If I find out more I'll report it to the relevant third parties and post an update here.
