### ISSUE TITLE
Major features are still missing after case closed

### ISSUE THREAD

**Issue by MillieMBanshee** [worldanvil/worldanvil-bug-tracker#53]
Millie M. Banshee:

I had an issue where I have no features in the menu on the left hand side. The case was closed and I turned on all options in the account features as suggested. More than I needed and the menu is still blank.

![Screenshot (497)](https://user-images.githubusercontent.com/80363872/110580255-4291ca80-8136-11eb-957f-e196351268d9.png)
![Screenshot (499)](https://user-images.githubusercontent.com/80363872/110580305-5ccba880-8136-11eb-9908-12bceccb64c2.png)

**Comment by Kordishal** [comment]
Click on Worlds & Heroes and create a world.
