### ISSUE TITLE
Image Search & Hyphen

### ISSUE THREAD

**Issue by graylion-wa** [worldanvil/worldanvil-bug-tracker#531]
**World Anvil Username**:

Graylion

**World / Campaign / RPG Character / Manuscript Title**:

Creation

**Feature**: 

Apollo Image Search

**Related URLS** 

Image Number One Example
Ptolus-001-Federico-Musetti.jpg
[Image Number One](https://www.worldanvil.com/i/2252972)

Image Number Two Example
Ptolus-001-Federico-Musetti-1.jpg
[Image Number Two](https://www.worldanvil.com/i/2252977)

**Describe the Issue**

When I search for images in my world using the following words the above images to do show up ...

- ptolus
- Ptolus
- PTOLUS

If I search using a hypen or anything after the hyphen that matches the file name they show up, for example ...

- Ptolus-
- Ptolus-001
- Ptolus-001-Federico
- Ptolus-001-Federico-Musetti

It would appear the hyphen is causing odd search behavior. And the use of the hyphen in image names is very common. I have previously had trouble finding images but I could not really pin down what was happening.

**Expected behavior**

Searching a word without the hyphen should bring up the image

** Sidenote **

If I paste [https://www.worldanvil.com/w/creation/search?string=ptolus](https://www.worldanvil.com/w/creation/search?string=ptolus) into the url I can find the images from the presentation view 

Thank you

**Comment by iamromeo** [comment]
I am sorry but this cannot be reproduced and you have not clarified WHERE/WHICH search is causing this

**Comment by iamromeo** [comment]
Tested and not reproducable.

**Comment by graylion-wa** [comment]
The Apollo Image Search as listed in the ticket.

There are two links to the images that will not appear on Apollo image search.

Please let me know if you need any more information.

**Comment by graylion-wa** [comment]
> I am sorry but this cannot be reproduced and you have not clarified WHERE/WHICH search is causing this

The Apollo Image Search as listed in the frature section of the ticket.

There are two links to the images that will not appear on Apollo image search.

Please let me know if you need any more information.

**Comment by graylion-wa** [comment]
When I search for images in my world using the following words the above images to do show up ...

![Appolo Image Search   Hyphen 01](https://user-images.githubusercontent.com/79761754/132087319-75506dd2-4aa2-4df7-aa30-837c2daef7de.jpg)

**Comment by graylion-wa** [comment]
If I search using a hypen or anything after the hyphen that matches the file name they show up, for example ...

Ptolus-
Ptolus-001
Ptolus-001-Federico
Ptolus-001-Federico-Musetti
![Appolo Image Search   Hyphen 02](https://user-images.githubusercontent.com/79761754/132087335-cc5a11f5-4a1b-483c-8730-2eb8ed054eec.jpg)

**Comment by Kordishal** [comment]
I can't get this to happen either. So there must be something else going on as well. Not sure how we could figure this out.
