### ISSUE TITLE
Misspelling on map embed

### ISSUE THREAD

**Issue by TheTitor** [worldanvil/worldanvil-bug-tracker#532]
**World Anvil Username**: Titor

**Describe the Issue**
On the "Map embed snippet" it is says:
EMBEDDING A MAP FOCUSES ON SPECIFIX COORDINATES

Specifix is said instead of specific 

**To Reproduce**
1. Go to any map
2. Click on map settings
3. Expand map embed snippet

**Comment by iamromeo** [comment]
Thank you for the heads up :)
