### ISSUE TITLE
Sub-articles do not inherit the default category header image of the parent category

### ISSUE THREAD

**Issue by brstm** [worldanvil/worldanvil-bug-tracker#534]
**World Anvil Username**: Luxxan

**World / Campaign / RPG Character / Manuscript Title**: Age of the Imperium

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):
An example of a sub-article with World cover image:
https://www.worldanvil.com/w/age-of-the-imperium-luxxan/a/dursthaus-landmark

**Describe the Issue**
Child articles inherit the cover image of the World, unless manually changed on each child article.

**To Reproduce**
1. Create Category
2. Set "Default Article Category Cover"
3. Create an article in the category
4. Create a sub-article under the article from step 3
5. Verify cover image of sub-article is World cover image rather than category cover image

**Expected behavior**
Expected behavior is that sub-articles inherit either the cover image of the parent article's category, or of the parent article if the parent article has a cover image assigned to it.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Not a bug - sub articles are not meant to inherit anything - if anything that can be a feature request. 
Sub articles will certainly NOT inhering from the category of the parent article they MIGHT inherit from the parent article.
