### ISSUE TITLE
Vignette content of Custom Template does not appear in article quick creation

### ISSUE THREAD

**Issue by DWRoelands** [worldanvil/worldanvil-bug-tracker#535]
**DWRoelands**:

**Philadelphia By Night**:

**Custom Templates**: 

**Describe the Issue**
Tempalte content not showing up in articles created from template.

**To Reproduce**
1. Create a custom template called "NPC" using the "Person" template as a parent.  
2. Added a table to the "Vignette/Freeform" textarea.
3. Save Template.
4. Create new article using the new "NPC" template.
5. Content from template does not appear in article.

**Expected behavior**
Content from  template should appear in article.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
How could it? Quick creation being as it is a quick article creation does not load anything to begin with. 
This is not a bug. It can become possibly a feature but this is not as easy as it sounds
