### ISSUE TITLE
Tooltip BBCode

### ISSUE THREAD

**Issue by pudding437** [worldanvil/worldanvil-bug-tracker#536]
**World Anvil Username**: Pudding437

**World / Campaign / RPG Character / Manuscript Title**: The Adamant Fields

**Feature**: BBCode

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/the-adamant-fields-pudding437/a/zul-s-wild-shape-list-article

**Describe the Issue**
When trying to add a tooltip to a word in an unordered list, it adds `[tooltip:No Flying Creatures]` to the start of the line item.  It seems to only occur on the 1st tooltip added after the second h2 tag.  

**To Reproduce**
The text is entered into the article in the following order:

1. Paragraph tags around explanation of lists
2. First h2 title
3. Unordered list with 35 items using the old style of `[ul][li]item[/li][/ul]`. The first tooltip is on the 6th item, with 11 tooltips in total.  Some of the items with tooltips have strikethroughs.
4. The second h2 title
5. An unordered list of 4 items in the new style.  The first tool tip is on item 2, and it shows the `[tooltip:No Flying Creatures]` in the preview.  There are 2 items below it with tooltips, but they are working correctly.

**Expected behaviour**
The tag would not be visible, and the text contained within the tags would be displayed when mousing over the word surrounded by the tags, like with the rest of the tags on the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/89750770/131265978-29813de8-8604-4087-9295-b69bc89b7ccd.png)
![image](https://user-images.githubusercontent.com/89750770/131265983-5900ecef-2fec-405f-b8ac-f9248411546f.png)
![image](https://user-images.githubusercontent.com/89750770/131265992-3e4d9bdf-675d-4063-9a69-9ca3984bb2df.png)
![image](https://user-images.githubusercontent.com/89750770/131266000-d32f07fe-e20b-4e84-a81d-dbbc77d3d092.png)

**Comment by Kordishal** [comment]
Can you please copy the full code? I suspect that this is an issue with the editor. The plato editor has some known issues which will be addressed at a later date.

Can you try switching to the Euclid editor to see if that resolves the issues?

[See here where to switch](https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors).

**Comment by pudding437** [comment]
```
[p]This is a list of all of the beasts that @[Zul](person:4e093312-33c4-4767-94cc-de2e23a4efe5) is able to transform into using Wild Shape. These are creatures he has seen. He is currently a level 2 Circle of the Moon Druid.[/p]
[h2]Animals Seen Before the Campaign:[/h2]
[ul]
[li]Badger[/li]
[li]Brown Bear[/li]
[li]Boar[/li]
[li]Bull[/li]
[li]Cat[/li]
[li][tooltip:Uses Lion statblock minus pack tactics, and size is medium]Cougar[/tooltip][/li]
[li]Cow[/li]
[li][tooltip:No Flying Creatures][s]Crow[/s][/tooltip][/li]
[li]Deer[/li]
[li]Draft Horse[/li]
[li][tooltip:No Flying Creatures][s]Eagle[/s][/tooltip][/li]
[li][tooltip:No Flying Creatures][s]Falcon[/s][/tooltip][/li]
[li][tooltip:No Swimming Creatures][s]Fish[/s][/tooltip][/li]
[li]Fox[/li]
[li][tooltip:No Swimming Creatures][s]Frog[/s][/tooltip][/li]
[li]Goat[/li]
[li][tooltip:No Flying Creatures][s]Great Grey Owl[/s][/tooltip][/li]
[li]Hare[/li]
[li][tooltip:No Flying Creatures][s]Hawk[/s][/tooltip][/li]
[li]Lizard[/li]
[li][tooltip:Uses Lion statblock minus pack tactics, and size is small]Lynx[/tooltip][/li]
[li]Mastiff[/li]
[li]Mountain Goat[/li]
[li]Mule[/li]
[li]Pig[/li]
[li][tooltip:No Swimming Creatures][s]Poisonous Snake[/s][/tooltip][/li]
[li][tooltip:Uses Weasel statblock, and size is small, and damage dice is 1d4 for bite]Pine Martin[/li]
[li]Pony[/li]
[li]Rat[/li]
[li]Riding Horse[/li]
[li]Sheep[/li]
[li]Spider[/li]
[li]Weasel[/li]
[li]Wild Dog[/li]
[li]Wolf[/li]
[/ul]
[h2]Animals Seen Since the Start of the Campaign:[/h2]
- Mole
- [tooltip:No Flying Creatures][s]Pigeon[/s][/tooltip]
- [tooltip:No Flying Creatures][s]Pheasant[/s][/tooltip]
- [tooltip:No Swimming Creatures][s]River Crab[/s][/tooltip]
```

**Comment by Kordishal** [comment]
`[li][tooltip:Uses Weasel statblock, and size is small, and damage dice is 1d4 for bite]Pine Martin[/li]`

This line is missing the closing tooltip, which is then consuming the one below

**Comment by pudding437** [comment]
Cool.  Gonna go and hide because this was really dumb.

**Comment by Kordishal** [comment]
No worries! Sometimes a second pair of eyes is all that is needed :)

If you encounter more issues, there are many people willing to help in the [Discord](https://www.worldanvil.com/discord) server!
