### ISSUE TITLE
Sheets: form template boilerplate output wrong: textarea placeholder prefilled with random generator text

### ISSUE THREAD

**Issue by Tillerz** [worldanvil/worldanvil-bug-tracker#537]
**World Anvil Username**: Tillerz

**World / Campaign / RPG Character / Manuscript Title**: Alana

**Feature**: Sheets / Boilerplate output for FORMS

**Describe the Issue**

The **placeholder field** for **textarea** is being filled with this (see below). Looks like some code from **random tables** snuck in here.

```
 <textarea   class="form-control mention"  id="domain_features" name="domain_features" rows="3" placeholder="Random tables MUST have their first entry be a number e.g. 3 or a range e.g. 18-20. The rest of the columns can be any piece of text you please. Example of usage: 

1 | 13 copper piece and a damaged shoe
2 | 42 copper pieces and some ramen
3 | 30 silver pieces and some treachery
4 | 32 gold pieces in the form of extracted teeth 
                            ">{{ variables.domain_features is defined ? variables.domain_features }}</textarea>

```

**Comment by iamromeo** [comment]
@Tillerz Can I please have a link on where I can see that happening ?

**Comment by Tillerz** [comment]
Kingdoms and Warfare FORM boilerplate: https://www.worldanvil.com/rpgsrd/block-template/8474/display/edit

![image](https://user-images.githubusercontent.com/63370525/132203789-1b38a121-bdef-4e39-aa22-e20d6359a263.png)

**Comment by Tillerz** [comment]
Oh dear lord, I just see it. It's Kitoypoy's fault. :D

![image](https://user-images.githubusercontent.com/63370525/132204017-077a1fbf-d0ba-4387-a23b-45b49ad131ce.png)
