### ISSUE TITLE
Save issue where last action is to select a linked article

### ISSUE THREAD

**Issue by BackworldTraveller** [worldanvil/worldanvil-bug-tracker#538]
**World Anvil Username**: BackworldTraveller

**World / Campaign / RPG Character / Manuscript Title**: Maerl

**Feature**: Article Editor

**Related URLS** (To public & visible pages add screenshots otherwise): Any/Every article

**Describe the Issue**
If the last action before saving is to type @XYZ and then select an article from the list, the save only records the @XYZ not the substituted article link. If you type any character after selecting the article, the save then works as expected.

**To Reproduce**
as above

**Expected behavior**
the article link used as the replacement should be saved, not the lookup key.

**Screenshots**
N/A

**Comment by Kordishal** [comment]
This is because the auto-save is not triggered by mouse clicks. This might change in the future, but in the meantime pressing any key on the keyboard is the way to go,
