### ISSUE TITLE
Years saving incorrectly when creating new historical entry on timeline

### ISSUE THREAD

**Issue by anothermystery09** [worldanvil/worldanvil-bug-tracker#539]
**World Anvil Username**: AnotherMystery

**World / Campaign / RPG Character / Manuscript Title**: Tal

**Feature**: Timelines

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/tal-anothermystery/t/character-milestones-timeline

**Describe the Issue**
A clear and concise description of what the issue is.
When I create a new historical entry for a timeline I'm noticing that the year often doesn't save correctly. I will type in a starting and/or ending date for a new historical entry, but when I view the timeline later the year is wrong. This happens about half of the time that I'm creating or editing timelines, and I can't find any pattern to when it happens. 

**To Reproduce**
1. From the Dashboard Go to '...' Timelines--->Historical Events
2. Click on '....' "Create new Historical Entry"
3. Fill in all the relevant info -- type a title, choose a timeline, select a year for starting date (no need to be more specific, leave the rest of the starting date blank), select significance, type, and add a short description
4. Click on "Create Historical Entry" to save the new entry
5. Click on "View Event" and check if the dates displayed match the ones entered in step 3
6. May need to repeat several times to reproduce error as it seems to be random

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Hi, I cannot reproduce this at random. I believe what is happening that you are changing the number with the scroll wheel by accident before saving.

While the field is focus scrolling will change the number. Can you check if this is happening?
