### ISSUE TITLE
Major features missing on original account but new account works

### ISSUE THREAD

**Issue by MillieMBanshee** [worldanvil/worldanvil-bug-tracker#54]
Millie M. Banshee:

No matter the suggestions of previous help the account I wanted to use refuses to let me use the left side menu. It's always blank. Out of curiosity I created a second one that has everything working just fine. I don't really want this new screen name but if The Mermaid Reaper works I guess i can use it. Is there anyway to delete my original Millie M. Banshee account and let me retry making it? I'm just really, really attached to that name. I've use it for years. If that is possible that would be great, thank you.

**Comment by iamromeo** [comment]
@MillieMBanshee please contact support or come over discord - this is not a chat client.
You can login to your initial account, change the username to something else and then rename the new account to name that you want.
