### ISSUE TITLE
View Sheet in Character Articles non-functional

### ISSUE THREAD

**Issue by The-Toblin** [worldanvil/worldanvil-bug-tracker#540]
**World Anvil Username**:
Toblin

**World / Campaign / RPG Character / Manuscript Title**:
Dark Shadows/Cinders of the Cataclysm/Others

**Feature**: 
Sheet view

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/CD10-DS/a/marek-tyving

**Describe the Issue**
The "Sheet" button on character articles is supposed to switch to the character's connected statblock character sheet. Currently, that button does nothing.

**To Reproduce**
1. Go to a character that has a connected sheet
2. Click on "Sheet" at the top
3. See error. It does nothing.

**Expected behavior**
The view should switch to the sheet.

**Additional Info**
Tested on both BS3 and BS5 selected for the active world. Neither works. Sheet visibility toggle has no impact.

**Comment by iamromeo** [comment]
This is not a bug, this is an utterly f*ed sheet in terms of code. I am guessing that the sheet's badge has unclosed tags because everything is effed on this page.
