### ISSUE TITLE
Editing via quick edit allows the use of () in title text

### ISSUE THREAD

**Issue by TheTitor** [worldanvil/worldanvil-bug-tracker#541]
**World Anvil Username**: Titor

**World / Campaign / RPG Character / Manuscript Title**:  FFXIV Campaigns -> Player guide: The Sunken Temple of Qarn - Rescuing Mro'a (4 Person)

**Feature**: Article Quick Edit

**Related URLS** (To public & visible pages add screenshots otherwise): 
This article was the one I originally edited before I knew not to add ()'s. I am leaving it here until addressed or if directly asked to change it beforehand. 
https://www.worldanvil.com/w/titor-s-questwerks---open-ffxiv-rp-plots-titor/a/player-guide3A-the-sunken-temple-of-qarn---rescuing-mro-a-plot

**Describe the Issue**
When making or editing an article through most means it will not allow you to add ()'s to the title. If you use it through the quickedit however, it doesn't warn you or stop you from doing this.

**To Reproduce**
1. Go to world dashboard
2. Select an article
3. Go to quick edit
4. It allows you to add ()'s and does not warn you you shouldn't. 

**Expected behavior**
I'm not sure if you don't allow ()'s due to a security feature, if it is this should likely be addressed quickly

**Comment by iamromeo** [comment]
Now forcing removal
