### ISSUE TITLE
Impossible touch controls (on smartphone, tablet) in categories tree

### ISSUE THREAD

**Issue by Sektor527** [worldanvil/worldanvil-bug-tracker#542]
**World Anvil Username**: Sektor

**World / Campaign / RPG Character / Manuscript Title**: any

**Feature**: "Articles & Categories" -> "Browse by Categories"

**Related URLS** (To public & visible pages add screenshots otherwise): N/A

**Describe the Issue**
On touch-based devices, like smartphones and tablets, it is nearly impossible to open a category to show the subcategories or the list of articles. Any tap to attempt to open (on the name or the [+] icon) is immediately interpreted as a drag-drop event.

**To Reproduce**
1. Use a smartphone or tablet and open worldanvil to any world on any account.
2. Go to "Articles & Categories" page from the left-hand menu
3. Tap on "World Atlas" or any other category with articles and/or subcategories
4. See a brief highlight box appear and disappear where tapped, but no subcategories or articles are displayed.

**Expected behavior**
When tapping a category name, it should show the list of articles to the right, like when clicking it with a mouse on a PC.

When tapping the [+] symbol next to a category, it should show the subcategories below it, like when clicking it with a mouse on a PC.

**Screenshots**
N/A

**Comment by iamromeo** [comment]
I am really sorry, although I am perfectly aware of the issues, this is not a bug. 
There are many people who use WA on a mobile phone and I use it on an iPad Pro without an issue but I do know that there are devices that have issues. Sadly I do not have the team to adress all mobile devices at this point
