### ISSUE TITLE
Glitchy CSS on the world page(s)?

### ISSUE THREAD

**Issue by crogonint** [worldanvil/worldanvil-bug-tracker#543]
**World Anvil Username**:
crogonint

**World / Campaign / RPG Character / Manuscript Title**: 
Gotan (JUST starting it)

**Feature**: 
Configure World

**Related URLS** (To public & visible pages add screenshots otherwise): 
n/a, it's the edit page(s) *screenshots below

**Describe the Issue**
On my initial use of World Anvil (in it's current form, I did muck around with it when you guys first introduced it) The text boxes were stuck in a white-on-black style, regardless of navigating away from the page and coming back. I foolishly did not get a screen shot, because I figured it was the default color scheme. The white-on-black colors were making my eyes go buggy after a while, so I enabled my Dark Reader extension to reduce the eye strain, which made it look like this:
![Screenshot from 2021-09-03 14-35-39](https://user-images.githubusercontent.com/23371790/132067969-75594112-58a4-4e6a-ab4b-a5723a4ae0e0.png)

After I enabled / disabled the Dark Reader extension, I was left with this:
![Screenshot from 2021-09-03 15-25-17](https://user-images.githubusercontent.com/23371790/132068032-02d2533e-1b88-41b0-bf4f-5c3670bc9244.png)

I'm still not entirely sure what the default color scheme for those text boxes is SUPPOSED to be, but since layered CSS can be so glitchy in the first place, I figured it wouldn't hurt to report a bug, and have someone give it a once over, just to check it. :)

**To Reproduce**
1. (MAYBE) With clean browser settings, navigate to root web site
2. Create a new account / world
3. Default Configure World text boxes are (MAY BE) white text on black background, causing excessive eye strain.
4. There is no error. It either reproduces the glitch(??) or it doesn't

**Expected behavior**
A nice lower contrast option, if it isn't being caused by some random glitch. :).

**Screenshots**
Woops.. I think my screenshots are in line, above?

**Comment by crogonint** [comment]
I should have included above, I initially set it to use the Villain (Dark Gray) theme.

**Comment by iamromeo** [comment]
Thnk you for your feedback @crogonint  but this is not a bug. Have a wonderful day

**Comment by crogonint** [comment]
You want to explain that?? This appears to me to be a CLASSIC case of glitchy layered CSS.

It can't possibly be designed to use a white text on black background in the fields, then switch to a normal looking color scheme after I manually switch it out. 

I wasn't specifically asking for a feature change, I'm still not sure which the default IS.

So.. what's the deal? Why was I seeing (what appears to be) glitchy CSS?

**Comment by iamromeo** [comment]
Considering that
- The themes do not change the really the colour of the editors
- You have been using an external addon to change the page

I cannot consider this a bug no. I am still not sure which of the **3 editors** you are using and nobody else has reported an issue. This is the reason this is not considered a bug.

**Comment by crogonint** [comment]
...3 editors? I was on the website. Using the Chrome browser. In the World
section. Which editor is used in that section..?

The glitch happened UNTIL I used Dark Reader to fix it because it was
making my eyes buggy. When I turned Dark Reader OFF it returned to what I
assume is normal. The pictures are posted just above. You tell me, which
one is the expected result?

Really, I would think you could have run some sort of CSS checking tool
faster than this discussion has taken.

 - James T. Long

------------
There are 10 kinds of people in the world - those who understand binary,
and those who don't.
