### ISSUE TITLE
Redacted displays one less character than the number of characters specified

### ISSUE THREAD

**Issue by BackworldTraveller** [worldanvil/worldanvil-bug-tracker#545]
**World Anvil Username**:BackworldTraveller

**World / Campaign / RPG Character / Manuscript Title**:[url]https://www.worldanvil.com/w/maerl-backworldtraveller/a/examples-of-stuff-article[/url]

**Feature**: The Redacted BB Code shows one less character block than the number specified (see example on URL above)

**Related URLS** (To public & visible pages add screenshots otherwise):[url]https://www.worldanvil.com/w/maerl-backworldtraveller/a/examples-of-stuff-article[/url]

**Describe the Issue**
The Redacted BB Code shows one less character block than the number specified (see example on URL above). Thus Redacted:1 shows Zero characters redacted.

**To Reproduce**
See above

**Expected behavior**
Redacted:1 should show one redacted character

**Screenshots**
N/A

**Comment by iamromeo** [comment]
Fixed - will be deployed within the next 24 hours
