### ISSUE TITLE
Delete Manuscripts

### ISSUE THREAD

**Issue by foxteeth** [worldanvil/worldanvil-bug-tracker#546]
**World Anvil Username**: 
foxteeth

**Manuscript Title**:
Der Hohe Norden
Eine Junge Republic

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/community/manuscripts/read/0633505740-foxteeth-der-hohe-norden
https://www.worldanvil.com/community/manuscripts/read/6609302668-foxteeth-eine-junge-republic

**Describe the Issue**
I tried to delete two of my old manuscripts which resulted in an error page. They still show up on the list of my manuscripts, but I can't open or edit them any longer. I'd still like to properly delete them and hope you can help me with it.

**Comment by iamromeo** [comment]
Please read previous but reports before creating a new one - this is already reported
