### ISSUE TITLE
Notifications for Manuscripts despite them being locked or private?

### ISSUE THREAD

**Issue by Amancham** [worldanvil/worldanvil-bug-tracker#549]
**World Anvil Username**: Amancham

**World / Campaign / RPG Character / Manuscript Title**: n/a 

**Feature**: Manuscripts and/or Notifications

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/community/manuscripts/read/5903622326-elikwake-avadis3A-book-three-of-the-reaper-saga
https://www.worldanvil.com/community/manuscripts/read/6320308745-foxteeth-hafenstadtabenteuer

**Describe the Issue**
I noticed notifications for people having published a manuscript or chapter in a manuscript, but when I click on the respective link in my notification, I get an "Access Denied" message
This happens, when I have no access to the entire manuscript (I still get notifications for the chapters being published in said manuscript) and also if I can access the manuscript but the chapters have a lock on them. I still get notifications that they/chapters in them have been published. 

I am unsure if it might be a case of authors publishing public at first and changing access settings later, however I have noticed that from different authors on different manuscripts. I also had a few notifications, where I was able to read the chapter or manuscript following the link. That leads me to believe, that the links are fine, it's an issue with the site not checking if I'm even allowed to access a chapter or manuscript but I get the notification anyway. Or, almost every author I follow on world anvil published public first and sets the stuff private after that.

Sadly, I have deleted most notifications and did not think to take screenshots. I have attached the notification about the manuscript from EliKwake, which leads to an access denied page for the entire manuscript. However, after that notification, I had lots more about the individual chapters in said manuscript that I also could not access. 
Similarly, I had notifications before about the second manuscript I linked. Again, it tells me that foxteeth has published a new chapter in the Manuscript "Hafenstadtabenteuer" (second link I posted) but the individual chapter link leads to an custom access denied page, (you shall not pass, see screenshot) yet I still get notified for new, locked chapters.
There were two more with similar behaviours/issues. Sable Aradi and her manuscripts "A few good elves" (mostly locked, but still getting notified for locked content) and "Starseeds: Stories from the Toy Soldier Saga" the other author I do not recall. 

**To Reproduce**
Can't test this, since I can't trigger notifications to myself about my own manuscript and I did not want to potentially spam people who follow me, to then bother a friend to let me know if they got notifications and in which case they got them. 
Best guess is to publish a manuscript that is set to 'private' and whoever follows the publishing author will apparently get a notification about a published manuscript.

**Expected behavior**
When I get notified for it, I'd expect to be able to read it. Or else: If a manuscript or chapter is set to 'private' or specific groups that I am not a part of,  I'd expect to NOT be notified about it.

**Screenshots**
![Screenshot 2021-09-07 at 12-57-01 Worldbuilding- und RPG Kampagnen-Verwaltung World Anvil](https://user-images.githubusercontent.com/25498928/132335748-89acbdff-22bc-40a0-9752-3b6966f64545.png)

![Screenshot 2021-09-07 at 12-57-14 Avadis Book Three of the Reaper Saga](https://user-images.githubusercontent.com/25498928/132335791-0b149453-6ff7-4682-a94f-4826d82a7a74.png)

![Screenshot 2021-09-07 at 13-21-07 I](https://user-images.githubusercontent.com/25498928/132337562-54a22a99-cd5d-4c82-b7a2-25739af3660f.png)

I hope it is possible to follow my ramblings. I'm not sure how to better describe the issue, but am happy to answer questions, if needed. :)

**Comment by iamromeo** [comment]
I am sorry but this is not a bug  - it is intentional.

**Comment by Amancham** [comment]
I see. 
Would have loved to get some information what the idea/reasoning behind that is, because I can't see any use in notification-spam that is entirely useless and meaningless to me. But I'll just unfollow everyone on my list that is spamming me this way, since it is causing me some mental issues. 
Thanks anyway.
