### ISSUE TITLE
CSS-Editor refuses to edit manuscripts (Security-filter ignores the term script itself)

### ISSUE THREAD

**Issue by Hertzbube** [worldanvil/worldanvil-bug-tracker#55]
**World Anvil Hertzbube |DASK**:

**DVDS**:

**Describe the Issue**
I have tried to add a border around my manuscript that I have linked to my homepage. It worked for the moment but everytime I reloaded my world the css for the manuscript doesn't load either.

So I think it happens because of the security-filter for the term "script".

**To Reproduce**
1. Link the manuscript to a article
2. Open the CSS-Editor
3. Use .user-css .homer-manuscript-tile and edit it like 
         border-bottom: red;
4. Reloade the page and the edited manuscript should disappear except you click at something in the css-editor.

**Comment by Kordishal** [comment]
Hi, there are alternative classes on every element of the manuscript book element that you can use.

![image](https://user-images.githubusercontent.com/14262536/110638971-74934300-81af-11eb-9d2c-52f5fd2981b9.png)

Full Cover -> `homer-book-tile`
Image Cover -> `homer-book-inner-tile`
Title -> `header-title` 
Read Button -> `homer-book-tile-action` 

Please use these classes instead.
