### ISSUE TITLE
Front End Search Only Searching Titles & Tags

### ISSUE THREAD

**Issue by mknnmknn** [worldanvil/worldanvil-bug-tracker#550]
**World Anvil Username**: makonnen

**World / Campaign / RPG Character / Manuscript Title**: Alemi

**Feature**: Front end search

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
The front-end search changed perhaps a month ago to only search titles and tags. This is a very poor UX for players--they need to be able to search full-text of articles to find things. The biggest complaint I hear about WA is _it's too hard to find things._ There needs to be a way players can search in broad strokes across a world.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
To add some more context: We discussed this on the Discord a bit and I was not sure if this is a bug or would require a feature request.

It appears that the frontend search uses the same API as the mention system. As the change of removing the content search affected this search as well.

I believe Makonnens argument has merrit, that for users it is much harder to know tags & titles.

**Comment by graylion-wa** [comment]
It would be great if Mentions and Presentation search could be different

* Mention (Titles & Tags)
* Presentation Search (Titles, Tags & Content)

Just a thought

**Comment by mknnmknn** [comment]
@graylion-wa 's suggestion is exactly how I--as both a GM and a user--would expect/want it to work. As a GM, I know those things and speed of typing is more important; as a user, I want to be able to search for "blacksmith" or someone's first name, and find the content I have access to as I prepare for my next game session.

**Comment by iamromeo** [comment]
This was not a bug, it was part of a new implementation to make searching faster. After review on the presentation layer the search being able to use its advanced features is quite helpful and it is now returned to that mode. 

This will be deployed later on today
