### ISSUE TITLE
User Experience on Meta section

### ISSUE THREAD

**Issue by Golemancer42** [worldanvil/worldanvil-bug-tracker#551]
**World Anvil Username**: Golemancer

**World / Campaign / RPG Character / Manuscript Title**: Adin

**Feature**:  World Meta

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

When I Save Changes while working on any tab of my world's Meta, it saves and then flips back to the Scope tab.

**To Reproduce**

Go to Meta section
Switch to tab other than Scope
Click Save Changes
Flip table

**Expected behavior**

I would expect (and prefer) if it kept the same tab and page position after saving.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
This is not a bug, if there is an expectation - feel free to submit a feature request and let the community give its opinion

**Comment by Golemancer42** [comment]
Understood, sorry for filing it as a bug but it seemed like unintended behavior. And in Meta, so it mainly affects new users on their first steps. I'm already done with Meta, but if there are more areas of the site that behave like that, I will submit a feature request for it then. Thank you for all your hard work and this amazing site. :)
