### ISSUE TITLE
The toggle for light and dark mode are sometimes in different spots

### ISSUE THREAD

**Issue by cburgerCA** [worldanvil/worldanvil-bug-tracker#552]
**World Anvil Username**: charin

**World / Campaign / RPG Character / Manuscript Title**: N/A

**Feature**: Light/Dark mode toggle

**Related URLS** (To public & visible pages add screenshots otherwise): Editing articles

**Describe the Issue**
If a user toggles between light and dark mode while editing a page, the right side of the header (class="nav navbar-top-links navbar-right") resizes slightly, sometimes causing it to go to a newline. Happened in firefox in a full window.

**To Reproduce**
1. Go to 'Edit an existing article'
2. Click on 'Light/Dark mode toggle'
3. See error

**Expected behavior**
The light/dark modes does not change the layout of the page, and the toggle remains in place.

**Screenshots**

![image](https://user-images.githubusercontent.com/10619802/132769324-0ed2a97c-c7b0-4154-a459-e9c287ebe17e.png)
![image](https://user-images.githubusercontent.com/10619802/132769376-5a7f04c4-f92c-4da1-9edf-66d216e32f16.png)

**Comment by iamromeo** [comment]
This has to do with the size of your screen - if it's below it simply means that the current browser window does not have enough space to show it on the top right - not a bug
