### ISSUE TITLE
Spelling error (Checknox) in Design Tags Reference

### ISSUE THREAD

**Issue by Snake-Venom** [worldanvil/worldanvil-bug-tracker#553]
**World Anvil Username**: Snake__Venom

**Feature**: The Expandable Design Tags Reference that can be expanded when editing an article. Specifically under the subheading/subsection "Checkboxes", the first word in the list.

**Describe the Issue**
The word as written is "Checknox"

**Expected behavior**
Spelling to be consistent with Dictionary, specifically: Checkbox

**Screenshots**
![Screenshot from 2021-09-10 20-54-06](https://user-images.githubusercontent.com/16118725/132903529-54a65ad2-99bd-4dc6-99dc-32ca702a3d14.png)

**Comment by Snake-Venom** [comment]
Actually, I just noticed that the right chevron checkbox is listed twice, but once with the indicator for left chevron
![Screenshot from 2021-09-10 21-01-15](https://user-images.githubusercontent.com/16118725/132904205-e0d9d59e-e077-4d92-9187-daef799f17e3.png)

**Comment by Kordishal** [comment]
Full List:
```
[] Checkbox, empty
[c] Checkbox, checked
[r] Checkbox, right chevron
[l] Checkbox, left chevron
[x] Checkbox, failed
[+] Checkbox, plus
[-] Checkbox, minus
```

Thanks for reporting!

**Comment by iamromeo** [comment]
Thank you guys
