### ISSUE TITLE
RPG NPCS section details not showing above articles like they should.

### ISSUE THREAD

**Issue by Radicon** [worldanvil/worldanvil-bug-tracker#557]
**World Anvil Username**: Onikaze77

**World / Campaign / RPG Character / Manuscript Title**: Lurking Strands/Darius Marefellow

**Feature**: RPG NPCS section

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
For some reason, the RPG NCPS information (eg. Plotter, details, goals, secrets, appearance) and such are not showing when I view an article I wrote using them.  Last week I was accustomed to seeing this data show up above the article in question, but now they simply don't show at all and to see them I have to go into the editor.  Did something change or is there a setting I'm overlooking?

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Please check the announcements. This is a new feature. These can be revealed by clicking on the header above all content to those with access to them

**Comment by Radicon** [comment]
Apologies, I looked for announcement information and couldn't locate it.  However, there is still the issue that I don't see a header above the content to click.  I'm the owner/creator of these articles, and yet I see nothing to click (and tried clicking everything I did find) and still can't find the RPG NPC details.

Can you tell me where I should click in this image?  Or show me on a screenshot of your own what I should click?
![darius](https://user-images.githubusercontent.com/25268411/133029944-bcf318fd-4856-4329-a361-f46ecab9564f.png)

**Comment by iamromeo** [comment]
Hey @Radicon I found the issue and fixing it - it was only working if you ALSO had something on the seeded section. 
It should up within the hour
