### ISSUE TITLE
Cannot Delete Charakter

### ISSUE THREAD

**Issue by charley2020** [worldanvil/worldanvil-bug-tracker#558]
**World Anvil Username**:
charley2020
**World / Campaign / RPG Character / Manuscript Title**:
RPG Charakter
**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):
[hero:e58f1093-f013-4d41-9f73-801e18e7670d]
@e58f1093-f013-4d41-9f73-801e18e7670d 

**Describe the Issue**
I am not able to delete a character i made for testing ozr the RPG Character feature.

**To Reproduce**

From Portal:
1. Go to Your RPG Charakters. The is only one with the Name : Cannot Delete
2. Click on Activate
3. Click on Edit
4. Scroll down to Delete Charakter
5. Click on Delete Charakter
6. Confirm the Delete Progress
7. See Page 404

**Expected behavior**
I expect the charakter to be deleted permanently. But i isn´t. I try to delete ever piece of information of this charakter but i still cannot delete it. I wasted  about 2h on this. This is clearly a bug.

**Comment by iamromeo** [comment]
This does look like a bug indeed. I will investigate

**Comment by iamromeo** [comment]
Guten tag Charlie

I tried to replicate this on my end and I cannot. I am not sure if this is something specific to the account. 
Would it be possible to send me an email on hello@worldanvil.com with a 
new temporary secure password for your account so I can access it and try to use my test tools to see what is going on there?

**Comment by charley2020** [comment]
ok. All set up. Email send a few hours ago. Do I have to log out?

**Comment by iamromeo** [comment]
This issue is resolved but the underlined cause is not. 

The issue is related to the fact that Quests are not deleted when a character is deleted. It will be addressed imminently
