### ISSUE TITLE
New welcome e-mail when creating second world

### ISSUE THREAD

**Issue by BackworldTraveller** [worldanvil/worldanvil-bug-tracker#560]
**World Anvil Username**:BackworldTraveller

**World / Campaign / RPG Character / Manuscript Title**:Herrir County

**Feature**: Welcome E-Mail

**Related URLS** (To public & visible pages add screenshots otherwise):N/A

**Describe the Issue**
On creating a second world, I received another copy of the "One-time-only" welcome e-mail!

**To Reproduce**
Create a new world

**Expected behavior**
Either no e-mail should be created, or a "New-World" mail should. If the latter, the Welcome e-mail should be amended to state that one mail will be sent per world created.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Creating a new world does not send an email. Creating an account does. I am really sorry, thank you so much for taking the time to report this, but i cannot replicate this.

1500 new worlds are created every day and this is the first time this was ever reported.

**Comment by BackworldTraveller** [comment]
The e-mail was received at 18:39 UK time, if that helps.

Best Regards
David
