### ISSUE TITLE
Plots Issue

### ISSUE THREAD

**Issue by adv666** [worldanvil/worldanvil-bug-tracker#563]
**World Anvil Username**: adv666

**World / Campaign / RPG Character / Manuscript Title**: Iluvatár

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/iluvatar-adv666/a/dr-alhazred2C-presumo3F--plot?preview=true

**Describe the Issue**The View doesn't show the contents of the plots, only the relations

**To Reproduce**
1. Go to https://www.worldanvil.com/w/iluvatar-adv666
2. Click on any plot line, v.g. "Dr. Alhazred, presumo?" link

**Expected behavior**
The view should show all the plot sections - as it did until now -, and not only the Relations. When I edit, the content is still there, but doesn't show on the view.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
All the content is visible?
![image](https://user-images.githubusercontent.com/14262536/133496821-98fc4127-ec13-4cc6-b2e7-adae752cfb98.png)

Either way, this is definitely not a bug. The most common cause for this is an unclosed BBCode tag.

**Comment by adv666** [comment]
No, only Relations is visible in **all** my plots, You can check it by going to the master-plot:

https://www.worldanvil.com/w/iluvatar-adv666/a/prologo-plot

As an example, when i export the plot given as an example, i get the full content:

https://www.worldanvil.com/w/iluvatar-adv666/a/dr-alhazred2C-presumo3F--plot?renderer=print

About the given explanation, an unclosed BBCode tag would have the this effect in **all** plots?

Thanks for the atention given

**Comment by adv666** [comment]
No, only Relations is visible in *all* my plots, You can check it by going
to the master-plot:

https://www.worldanvil.com/w/iluvatar-adv666/a/prologo-plot

As an example, when i export the plot given as an example, i get the full
content:

https://www.worldanvil.com/w/iluvatar-adv666/a/dr-alhazred2C-presumo3F--plot?renderer=print

About the given explanation, an unclosed BBCode tag would have the this
effect in *all* plots?

Thanks for the atention given

**Comment by Kordishal** [comment]
An unclosed tag would only be one field, but it seems unlikely. It would mess up the structure.

The main plot has content that is not in the relations section, so not sure how the subplot would not display it.

Can you screenshot the content of the other sections? Otherwise just try removing content from the fields that do not display until they do.

**Comment by adv666** [comment]
It wasn't any problem with an unclosed BBCode tag.

There was an alteration on your web interface, with the inclusion of a
"Show Storyteller Content" button at the top. The user now needs to click
it to see the content of the plot.

Thanks for the help
