### ISSUE TITLE
I cannot delete my account

### ISSUE THREAD

**Issue by CLDickson** [worldanvil/worldanvil-bug-tracker#564]
C.L Dickson

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
This report has no details - I cannot action this
