### ISSUE TITLE
WA adds linebreaks/spacers into CSS code (sheets)

### ISSUE THREAD

**Issue by Tillerz** [worldanvil/worldanvil-bug-tracker#565]
**World Anvil Username**: Tillerz

**World / Campaign / RPG Character / Manuscript Title**: Alana

**Feature**: Sheets & Statblocks

**Describe the Issue**

I try to use 

```
.table-striped tbody tr:nth-of-type(odd) {
    background-color: #00000020!important;
}
```

This is not working because the security filter is breaking it, it doesnt like the ) {
So I try to use

```
.table-striped tbody tr:nth-of-type(odd)
{
    background-color: #00000020!important;
}
```

This works, but every accidental manual edit or source formatter will break this into the first version again, so this is not staying, and each edit of the css will most probably break this code agaian.

So I try to use

```
.table-striped tbody tr:nth-of-type(odd) /* bla */ {
    background-color: #00000020!important;
}
```

That works... UNTIL any code formatter breaks it by formatting it into

.table-striped tbody tr:nth-of-type(odd) /* bla */

```
{
    background-color: #00000020!important;
}
```

That is still valid code and should work, BUT: this is not working, because WA adds html:

```
.template-class_features_2020-tillerz-1 .table-striped tbody tr:nth-of-type(odd) 
<br /><span class="line-spacer d-block">&nbsp;</span>
{
  background-color: #00000020!important;}
```

WA should NOT at any time ever add any html code into CSS blocks, it will most likely break the CSS.

**Comment by iamromeo** [comment]
This is related/tied to a security feature - not a bug - will not be fixed.

**Comment by Tillerz** [comment]
The adding of <br /><span class="line-spacer d-block">&nbsp;</span> into CSS is a security feature? I am not expecting your to change the ) { behaviour, I know that and it's good.
