### ISSUE TITLE
Table Bug in Editing Article

### ISSUE THREAD

**Issue by ajweaver13** [worldanvil/worldanvil-bug-tracker#566]
**World Anvil Username**: Morae

**World / Campaign / RPG Character / Manuscript Title**: Ti'dil, Gods

**Feature**: Table

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/vi-dil-morae/a/gods-article-1

**Describe the Issue**
When I was clicking edit artcile to update it, I've noticed the formatting of my table for the first rows disappeared. I redid the format, previewed the article, and exited the editing page for the article. I went back again and I noticed the problem again.

**To Reproduce**
1. Go to article with a table.
2. Click on "Edit Article"
3. See error

**Expected behavior**
The format of the table for the first three rows would disappear, creating rows of text without the "[tr]","[td]", and "[th]" format.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/90331906/133655545-e0b47365-a61e-4b12-a2ac-63b7b9d067c0.png)

**Comment by Kordishal** [comment]
This is probably an issue with the plato editor. Can you try switching to the Euclid editor?

Check out [this](https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors) if you don't know how to switch.

**Comment by iamromeo** [comment]
This is an issue with Euclid and complex BBcode - please switch to the advanced editor
