### ISSUE TITLE
In a timeline, "Additional Timelines" links go to the wrong page

### ISSUE THREAD

**Issue by Len42** [worldanvil/worldanvil-bug-tracker#567]
**World Anvil Username**: LenP

**World / Campaign / RPG Character / Manuscript Title**: Earthship Ark

**Feature**: Timelines

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/earthship-ark-lenp/t/earthship-ark-s-voyage-timeline
https://www.worldanvil.com/w/earthship-ark-lenp/t/the-starlost-campaign-timeline

**Describe the Issue**
When a timeline event has links to "Additional Timelines", those links don't go to another timeline; instead, they go to an article page with a similar (but not always identical) name.

**To Reproduce**
1. Go to one of the timelines linked above.
2. Scroll down and find an event that has an "Additional Timelines" link.
3. Click on that link.
4. Instead of going to the other timeline page, it goes to an article page with a similar name.

**Expected behavior**
Expect the "Additional Timelines" link to link to a timeline, not some other article.

**Comment by iamromeo** [comment]
This is not a bug, this is a feature :) When your target timeline is set to be under a specific article loading that timeline will load the article ;) 

![Screenshot 2021-09-24 at 06 54 15](https://user-images.githubusercontent.com/660175/134615658-7e757c8e-f7a3-46b3-b944-b977fd7c2660.png)
