### ISSUE TITLE
Epic Hero custom URL slug consistently reverts after one visit.

### ISSUE THREAD

**Issue by ElectricKeet** [worldanvil/worldanvil-bug-tracker#568]
**World Anvil Username**: ElectricKeet

**World / Campaign / RPG Character / Manuscript Title**: Millimax

**Feature**: Custom URL

**Related URLS** (To public & visible pages add screenshots otherwise):

- https://www.worldanvil.com/hero/8e2cbf03-07e1-42cc-95ee-7a4168e3fdbe (character profile)
- https://www.worldanvil.com/hero/millimax-by-millimax (what I want it to be)

**Describe the Issue**
After setting a custom URL for the character profile, it can be visited precisely once at that URL; afterward, the custom URL returns only "This character has gone into hiding, and by hiding I mean, not to be seen again!" which is a frankly _terrifying_ error message to get. The profile is still available at the original hexadecimal soup URL.

**To Reproduce**
1. Go to https://www.worldanvil.com/heroes/character/edit/epic/subscription and into the Epic Features tab. See the "You are a/an Epic Hero!" text to confirm that the features should work.
2. In the Custom URL field, enter `millimax-by-millimax` then click the "Update URL Slug" button. The expected green "All done!" banner appears to indicate success.
3. Visit https://www.worldanvil.com/hero/millimax-by-millimax and see the character profile.
4. Reload that page and get the "This character has gone into hiding" error.
5. Go to https://www.worldanvil.com/heroes/character/edit/epic/subscription and into the Epic Features tab; the Custom URL field now shows `8e2cbf03-07e1-42cc-95ee-7a4168e3fdbe`.

**Expected behavior**
The custom URL really should persist past a single visit – ideally, until changed again.

**Comment by Kordishal** [comment]
@Dimitris: Can confirm that we've looked at this issue and can confirm that it is happening. Unfortunately, we could not figure out why and it is not reproducible on other accounts.

**Comment by iamromeo** [comment]
I will have a look at this it might be releated with the reverting of the security status as well

**Comment by iamromeo** [comment]
The bug is now reproducable - I will proceed with the fix

**Comment by iamromeo** [comment]
This was an issue affecting only users with Epic-hero minor memberships - now fixed
