### ISSUE TITLE
Relationship face shows as smiley even for negative relationships

### ISSUE THREAD

**Issue by NecroAura** [worldanvil/worldanvil-bug-tracker#570]
NecroAura

Runeterra

Relationships

![image](https://user-images.githubusercontent.com/90993347/133912369-6aa8baee-658b-4659-b252-3e64e7aedd20.png)

When making relationships where the counterpart's opinion is negative, the face still smiles on the preview of the relationship

**To Reproduce**
1. Go to any character article while a second character article exists
2. Click on Relationships
3. Create a relationship where the counterpart's shown opinion or actual opinion of the character is negative

**Expected behavior**
The face should be the same as the character to the counterpart

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Hi, I can't reproduce this. Can you try to edit the relationship to something else and then back? Saving in between of course.

**Comment by NecroAura** [comment]
I just tried changing it and when I made it something different the problem was solved and the face showed normally, but then when I changed it back it was the same again.  After some further testing it seems to be _only_ when the counterpart's **REAL** opinion is 4 or 5 and the shown opinion is negative that it shows as a smiley:
![image](https://user-images.githubusercontent.com/90993347/133931528-989cac6f-fd48-43e1-9e62-7a2d1748aa52.png)
![image](https://user-images.githubusercontent.com/90993347/133932767-bc4ef9dc-c170-46ac-b6d8-47b51a11c70c.png)
![image](https://user-images.githubusercontent.com/90993347/133931549-32e69d81-2615-483f-9914-119a67bf24cb.png)

**Comment by iamromeo** [comment]
it might be a typo on the code. I will have a look.
