### ISSUE TITLE
Filtering Statblocks By Tag

### ISSUE THREAD

**Issue by bpohja** [worldanvil/worldanvil-bug-tracker#571]
**World Anvil Username**: bpohja

**World / Campaign / RPG Character / Manuscript Title**: The Northern Lands and Beyond

**Feature**: StatBlocks

**Related URLS** (To public & visible pages add screenshots otherwise): See Screenshots

**Describe the Issue**
I have tags on the statblock sheets that I have. When I click on a tag to filter, the results say "No blocks matching this term found." even though I know I have blocks with the same term (e.g., session1). 

It appears that filter works on the template type "Item (2020)" that I've used for a couple of sheets, but not the "Generic" sheet types (e.g., Image, Text, Table), which is what I am primarily using.

**To Reproduce**
1. Goto Statblocks screen
2. Click on tag "session1"

**Expected behavior**
I expect to see two items listed ("Caves" Document from Body, Campaign Start Group Missions).

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Capture1](https://user-images.githubusercontent.com/3054537/133913075-b2c77b8c-7b1c-4e53-b85b-799b68e26d0f.PNG)
![Capture2](https://user-images.githubusercontent.com/3054537/133913077-5056e062-23c3-429a-bc0a-fbe25e0698b8.PNG)

**Comment by Kordishal** [comment]
@Dimitris Can confirm that this is an issue with generic statblocks.

**Comment by iamromeo** [comment]
Only generic statblocks?

**Comment by Kordishal** [comment]
I didn't test it with a lot of statblocks, but it works for the D&D 2020 statblocks. Do you want me to look into it some more?

**Comment by iamromeo** [comment]
@Kordishal if that is possible it would be very helpful

**Comment by Kordishal** [comment]
Ok I will have a look tonight

**Comment by iamromeo** [comment]
No need found and resolved
