### ISSUE TITLE
Custom map html pin with custom class doesn't have a corresponding custom css class on its popup

### ISSUE THREAD

**Issue by kaiohon** [worldanvil/worldanvil-bug-tracker#573]
**World Anvil Username**: kaiohon

**Feature**:  Maps / Special HTML marker

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Special HTML Marker is currently the only way to generate pure CSS/HTML pin (i.e. scalable quality + great versatility without a lot of effort) but the there is no possibility to set an appropriate Leaflet JS anchor points and popup points for it. By default it is anchored by the center point, which doesn't work for custom pins in the form of actual pins. With a bit of global CSS magic you can position it sort of correctly (meaning so it is anchored by the bottom center point), but there is no special class applied to the popup of that custom pin (htmlIcon). Which means even if I position the custom pin correctly I have no way of targeting the popup of that custom pin specifically and it overlaps the icon. I can either move all popups or none, which is an issue. 

**To Reproduce**
1. Go to any map and click "Add a special HTML Marker" 
2. Here is the code for the custom pin:
`<div style="width: 40px; height: 40px; border-radius: 60px; background: red; display: inline-block; border-bottom-right-radius: 0; transform: rotate(45deg); border: 5px solid blue; box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.5), 0 2px 4px 0 rgba(0, 0, 0, 0.5); "></div><i class="ra  ra-match" style="color:white; font-size:19px; display:block; position:relative; top:-40px; "></i>`

3. Go to global CSS and enter the following rules:
`.user-css.htmlIcon {
margin-top: -51px !important;
border-radius: 0px !important;
padding:0px !important;
position: relative;
background: none;
}
.leaflet-popup {
bottom: 40px !important;
}`

4. See the result where popup displays correctly for the custom pin but wrong for all others:

![image](https://user-images.githubusercontent.com/34840988/133932804-e67d0c91-28c9-4859-be27-d640d5eb2d77.png)

**Expected behavior**
There should be either a way to specify individual anchor points and popup points for special HTML Markers in order for Leaflet JS to pick them up correctly, or perhaps easier, a custom class applied to popups of special HTML Markers so that they can be targeted and styled separately from other popups.

**Comment by iamromeo** [comment]
Hey there! I am really sorry but this is not a bug, it might be considered as a lack of functionality but this is not something to be addressed here. If you feel it should be a feature please use the feature suggestion board and we can take it from there.

**Comment by aestry** [comment]
After a short discussion and some encouragement from SoulLink :), I've decided to explain perhaps a bit further how the situation can be rectified with minimal effort by adding 2 words to the code in 2 places when special HTML markers are created and the .bindPopoup method is called for them.

1) In case of Editing mode, it's a matter of adding {className:'htmlIcon'} to all icons created via HTML special marker field;
2) In case of Presentation mode, it's a matter of changing {className:'popup-section'} to {className:'popup-section htmlIcon'}. 

Thus when the popup is related to the special HTML icon these changes will add "htmlIcon" class to the popoup div in case (1) in addition to  existing "leaflet-popup  leaflet-zoom-animated" classes and in case (2) in addition to existing "leaflet-popup popup-section leaflet-zoom-animated" classes. 

This extra class will in turn allow to control the popups of special HTML icons separately from popups related to polygons, circles and other markers, and especially with regard to control of their position if you want to dynamically change the HTML icon's anchoring point (which is the case if you want it to look like a pin and anchor like a pin).

Hope this  extensive research into the problem helps! :)

I would also gladly create a tutorial for creating quick dynamic and fancy icons with gradients, etc., in case this part gets fixed, which can perhaps be shared with the community and encourage more creativity while the Atlas project is in progress.  :)

**Comment by kaiohon** [comment]
After a short discussion and some encouragement from SoulLink :), I've decided to explain perhaps a bit further how the situation can be rectified with minimal effort by adding 2 words to the code in 2 places when special HTML markers are created and the .bindPopoup method is called for them.

1) In case of Editing mode, it's a matter of adding {className:'htmlIcon'} to all icons created via HTML special marker field;
2) In case of Presentation mode, it's a matter of changing {className:'popup-section'} to {className:'popup-section htmlIcon'}. 

Thus when the popup is related to the special HTML icon these changes will add "htmlIcon" class to the popoup div in case (1) in addition to  existing "leaflet-popup  leaflet-zoom-animated" classes and in case (2) in addition to existing "leaflet-popup popup-section leaflet-zoom-animated" classes. 

This extra class will in turn allow to control the popups of special HTML icons separately from popups related to polygons, circles and other markers, and especially with regard to control of their position if you want to dynamically change the HTML icon's anchoring point (which is the case if you want it to look like a pin and anchor like a pin).

Hope this  extensive research into the problem helps! :)

I would also gladly create a tutorial for creating quick dynamic and fancy icons with gradients, etc., in case this part gets fixed, which can perhaps be shared with the community and encourage more creativity while the Atlas project is in progress.  :)

/Edit, as accidently posted from my wife's account open in different browser. :(/

**Comment by iamromeo** [comment]
If I am not mistaken this was moved to the Features request board  (very corectly) let's see what the community says about this there. Regardless having read your feature request I can think of some ideas of how this can be implemented but it looks more like an Atlas (new maps version) than a fix :)

**Comment by kaiohon** [comment]
Sure! On another note, since there is no date yet on Atlas, would you consider adding a public pack of predefined divIcons if I prepare all the options and JS Leaflet definitions? :) Let me know as I would be glad to share my own explorations!

**Comment by kaiohon** [comment]
To elaborate I went ahead and created a JSFiddle with comments for you to look at with a pack of themes for a new type of default icon.
https://jsfiddle.net/6njoL978/13/

![image](https://user-images.githubusercontent.com/34840988/134719831-73778d4c-dd32-46a0-acbe-43128e9bc5a5.png)

Basically, you only need to include the icon below in your library of icons, and all the above styles become applicable. By default it creates an SVG red pin without shadow, which I think is a type of icon not represented yet in WA's library so it will be useful for users who don't even want to additionally style it with CSS.

`var stylablePinIcon = L.divIcon({`
`html: '<div class="stylableIcon-form-wrapper"></div><div class="stylableIcon-icon-wrapper"><svg style="width: 60px; height: 60px; margin-left: auto; margin-right: auto;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 30 60"><path d="M 15,30.000134 C 6.7291397,30.000134 0,23.270855 0,15.000134 0,6.72941 6.7291397,0 15,0 23.270848,0 30,6.7292775 30,15 30,23.270722 23.270848,30.000134 15,30.000134 Z" id="pin-background" style="fill:#d50000;"/><path d="M 14.00005,29.948952 V 59.980066 H 16.00006 V 29.948952 Z" id="pin-shape" style="fill:#707070;"/><path d="M 9.9939957,7.0000266 C 7.7879557,7.0000266 5.9939857,8.7939953 5.9939857,11.000042 5.9939857,13.206089 7.7879557,15.000058 9.9939957,15.000058 12.200046,15.000058 13.994016,13.206089 13.994016,11.000042 13.994016,8.7939953 12.200046,7.0000266 9.9939957,7.0000266 Z" id="pin-reflection" style="fill:#f66666;"/></svg></div>',`
`iconSize: [60, 60],`
`className: 'user-css stylableIcon ',`
`iconAnchor: [30,60],`
`popupAnchor: [0, -60],`
`});`

As mentioned I can write a detailed CSS guide for various themes.  So let me know what you think of adding one more thing while we wait for Atlas. Perhaps this can be useful for Atlas as well!
