### ISSUE TITLE
Regression on World Anvil API since last week update

### ISSUE THREAD

**Issue by adrien-schiehle** [worldanvil/worldanvil-bug-tracker#575]
**World Anvil Username**: Didialchichi

**World / Campaign / RPG Character / Manuscript Title**: Acaria Empire

**Feature**: World Anvil Module for Foundry

**Related URLS** (To public & visible pages add screenshots otherwise):
- Issue description on WA Module : https://gitlab.com/foundrynet/world-anvil/-/issues/31

**Describe the Issue**
Since last API update a week ago, we're not able to synchronize article contents.  
(Same problem with category contents by the way).

We get a 404 error. And it seems you have an internal CORS exception.

The problem comes from the way we are communicating with World Anvil API.
To avoid CORS problem, we pass authentication key and application-key as parameters

It works fine for some requests :
- /user?application-key=...
- /world/{id}
- /world/{id}/articles
- /world/{id}/categories

But for some others, we get an error :
- /article/{id}
- /category/{id}

**To Reproduce**
With Foundry : Try to synchronize an article content

With Postman :  
1. /user?application-key=...    ( <= You will get the authentication-key)
2. /world/{id}
3. /world/{id}/articles  ( <= You can pick an article id )
4. /article/{id}   

- It will fail if you pass x-application-key and x-auth-token as parameters
- It will work if you pass them as headers.

**Expected behavior**
- API works with keys passed as parameters
- Or, a solution so that I can pass keys as headers in the foundry module and avoid CORS exceptions

**Screenshots**
See the ones in the Foundry module issue.

**Comment by iamromeo** [comment]
Hello guys, I have been banging my head against the wall and I cannot find an issue with this. 

On my local everything works as intended with either the x-... as params on the URL or on the heads

For example: 
http://localhost:8080/app_dev.php/api/aragorn/article/00be5154-055b-4743-b107-90aaca370d43?x-application-key=Tt8RbuX7KD65F6QSHmhWvZLT7VAfCbZqbyBT6vY6BhbwfH4R2Y3YSYgUmJSAqJ3NaPUyNQPFExfQswTeHHSP9ve6jdn8DZuWYkCRrfUZ6dqXKVyyq4vjammk4qggNrh3jMvssu9X7dYBwQysUF9GjLS6vLqSDQMF5vBVCmHTuVuFfJMh6LCCy9DZ2UHVDZZj7ZRtX6GqJnqApWXdXGxQfLsmz4VehtxL3WFmc3XqaDrK6U3hdA2u84gt5eRs5&x-auth-token=9QxWuGXFsLX85Mb29kCcfQqMm0h5IPWL6k2F1xQlDhP5KrvspPafapCX0ayMM9gBaqP1O0gY6KPLLrSkNaWpr6WQWvyPFHTEgHEPugzYJENz2LYZu3iyKxLS29PrLFif52MLMHgpaWICMddtx7DBiRFuWwPOzDjGxd9XDJWYIqWoim2X6f12wSdwhQvulJFoIMJPaOf9bSd1c7qcGyAcNayS7GRgJbU6vwQQQFwvODQdYMcFoPAP8vCuX

I also went to my Git repo and checked the latest changes and I cannot see any issue there either.

**Comment by iamromeo** [comment]
@adrien-schiehle I have pushed a small fix - can you please check and let me know if this is woring now for you ?
