### ISSUE TITLE
Relationships are public (when one person is public and the other one is private)

### ISSUE THREAD

**Issue by kerkmann** [worldanvil/worldanvil-bug-tracker#58]
**World Anvil Username**: kerkmann

**World / Campaign / RPG Character / Manuscript Title**: The Echo World

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/the-echo-world-kerkmann/a/emily-knaack-person
https://www.worldanvil.com/w/the-echo-world-kerkmann/a/fynn-knaack-person

**Describe the Issue**
If one person is public (Emily Knaack) and the other person is private (Fynn Knaack), the relationship is public on Emily Knaack's profile.

**To Reproduce**
1. Create a public article (character)
2. Create a private article (character)
3. Create a relationship between them.
4. See the public article page (the relationship will be public)

**Expected behavior**
If both characters are not known, there should be no public relationship on the public article page.
Best feature would be, a privacy setting on the relationship setting. So GM can set the relationship be private or public.

**Comment by Kordishal** [comment]
This is working as intended but it might make sense to change it (or add an option for it). 

In the meantime, as a Grandmaster, what you can do is use visibility toggles to hide the relationships from your players. Or simply hide them completely with the visibility toggle.

**Comment by kerkmann** [comment]
@Kordishal 

Thanks for your reply. :)
I'm a Grandmaster, but the problem is, I can only hide them for all.
I wish I could hide them for some specific subscriber group.

The same problem is with everything else, like religion.
Person A (is public, because the player knows them), the religion (is also public).
On the website the user can see: "Yeah Person A is part of this religion" (which maybe isn't known).
It would be great to hide/show some relations for specific subscriber group, instead of hide/show them for all. :)

**Comment by Kordishal** [comment]
Agreed. I believe Dimitris is looking into it if there is a way to improve this easily but it is not very high priority. So it might take a while. 

Otherwise, if Dimitris closes the issue, you'll have to go the feature request route.
