### ISSUE TITLE
I have a problem with Articles not being shown

### ISSUE THREAD

**Issue by Otakurious** [worldanvil/worldanvil-bug-tracker#580]
**World Anvil Username**: Otakurious

**World / Campaign / RPG Character / Manuscript Title**: Abalur

**Feature**: Pretty much any Article

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/abalur-otakurious/a/brian-david-gilbert-article?preview=true
https://www.worldanvil.com/w/abalur-otakurious/a/humans-species
https://www.worldanvil.com/w/abalur-otakurious/a/leeha-ragnvald-person?preview=true

**Describe the Issue**
As you can see in the Links provided, the articles seem completly empty, when i however look at the preview (as seen in the screenshots section) they appear normal and I do not know what happened that caused this, and I would like to find a solution since it stopped me in the tracks of making more Articles.

**To Reproduce**
I don't 100% know what I did, i added a footer section to Brians Article including his magical items, and once I finished the Item all articles broke, deleting it didn't solve the issue.

**Expected behavior**
To show me the Article

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/91184040/134305650-ee8766d6-869b-4df2-96dd-b5599a1e3995.png)
![image](https://user-images.githubusercontent.com/91184040/134305761-44349199-6a62-4e61-a9d4-158fb68df5e3.png)
![image](https://user-images.githubusercontent.com/91184040/134305907-2e21749c-3600-42df-95af-121001e2c894.png)

**Comment by iamromeo** [comment]
This is already fixed and it being deployed

**Comment by BackworldTraveller** [comment]
The issue is still visible to me - not fixed

**Comment by BackworldTraveller** [comment]
And it is now fixed

**Comment by iamromeo** [comment]
@BackworldTraveller my message mentioned "it is being deployed" :)
