### ISSUE TITLE
Heroes "short bio" cannot be edited

### ISSUE THREAD

**Issue by Timespool** [worldanvil/worldanvil-bug-tracker#584]
**World Anvil Username**: Timepool

**World / Campaign / RPG Character / Manuscript Title**: Dr. Em

**Feature**: Hero profile

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/hero/apra-dr-em

**Describe the Issue**
The "short bio" for character pages (found in the basic profile tab) cannot be edited. More accurately— I can only remove text, not add any. No numbers, letters, etc. Not even copy/paste will work.

**To Reproduce**
1. Go to 'Edit' on a character profile
2. Click into the 'Short bio' text box
3. Attempt to type new characters

**Expected behavior**
I should be able to edit the text as I would anywhere else, adding and removing characters normally.

**Comment by iamromeo** [comment]
please provide the EXACT content and the location/url you are trying to use for this

**Comment by Timespool** [comment]
The exact content is in the short bio, and reads;

"A nervous research assistant of Dr. Zie, Dr. Em has worked for the ACF for [redacted: 3] years. During their tenure, they have accomplished many things, all of which are classified and very commendable I swear, don't look into it."

The URL is as I shared above: https://www.worldanvil.com/hero/apra-dr-em
I don't know if the editor-side URL helps here at all but that would be: https://www.worldanvil.com/heroes/character/edit/basic
(It's just the character editor)

![image](https://user-images.githubusercontent.com/51835701/134549689-1faf9a8b-fed7-4df2-8b13-5ca82ab21f4b.png)

**Comment by iamromeo** [comment]
Thank you  :) I will have a look

**Comment by iamromeo** [comment]
@Timespool can you please give me the exact copy of this field for you - I do not seem to be able to reproduce this.

**Comment by Timespool** [comment]
This is what it currently has;

A nervous research assistant of Dr. Zie, Dr. Em has worked for the ACF for [redacted: 3] years. During their tenure, they have accomplished many things, all of which are classified and very commendable I swear, don't look into it.

**Comment by Kordishal** [comment]
Can't reproduce this issue either. What exactly is the error? Or does the field just not react to input? Or is can you not focus it? My guess would be that is an issue on your side.


I noticed that the short bio is rendered below the character portrait on the profile, but not rendered in the About section:
![image](https://user-images.githubusercontent.com/14262536/147361027-dcbea59f-17e2-48a2-b672-28f82cecf954.png)

**Comment by Timespool** [comment]
The field won't react to any inputs, I can focus it but it doesn't react to any button presses.

**Comment by Kordishal** [comment]
And its only on that character? Not any other characters?

**Comment by iamromeo** [comment]
Unable to reproduce in any way - has not be reported again.
