### ISSUE TITLE
Aftermath!

### ISSUE THREAD

**Issue by kkavika** [worldanvil/worldanvil-bug-tracker#586]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name (RPG SYSTEM)**:
**List Name** (Name under which it should be listed on World Anvil):
**World Anvil Username**:

**Website**:

**Logo Image Link**:

**Logo Usage Terms (URL)**:

**Comment by iamromeo** [comment]
I am really sorry, but if you are not reading the instructions I cannot action the issue.
