### ISSUE TITLE
Manuscript typing overlay

### ISSUE THREAD

**Issue by trixquinzel** [worldanvil/worldanvil-bug-tracker#59]
TrixQuinzel

Vagharia/ Watchers Rising:

Manuscript

I have been trying to type out several sections of my manuscript however, everytime I come to the end of the line, the next line is over lapping with the first meaning I come out with a solid block of writing that I can't read. 

**Expected behavior**
I expected that when coming to the end of a line, the next line would sit underneath and you could read It clearly. 

**Screenshots**
![manuscript issue](https://user-images.githubusercontent.com/80497862/110881534-6a209880-82d8-11eb-9eef-a2fda5c23488.jpg)

**Comment by iamromeo** [comment]
hey @trixquinzel I cannot be sure but this looks like a misconfiguration on your Manuscript's display settings. 
Can you please send me a screenshot of your settings?

**Comment by trixquinzel** [comment]
Hi @iamromeo you are probably right, I have never been very good with this kind of thing. Here is what my settings are at, at the moment. Hope it helps, and thank you any help you can give is very much appreciated.  

![world anvil](https://user-images.githubusercontent.com/80497862/110966527-3f245c00-834d-11eb-9c9d-e71519162dc2.jpg)

**Comment by Kordishal** [comment]
Hi, this image is too low resolution. It is not possible to read. Can you please come by the [Discord](https://www.worldanvil.com/discord) and ask for help there? It will be easier to help you in real-time :)
