### ISSUE TITLE
Refresh List icon not working on certain lists

### ISSUE THREAD

**Issue by b57123m** [worldanvil/worldanvil-bug-tracker#591]
Bambam57:

Articles and Categories page:

Refresh button incorrectly working on certain lists: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When viewing the Lists; Unpublished articles, WIP articles and maybe the Stub Articles (my list is too long and won't load the Stub list) and you click the little refresh button on the right side next to the Slim Down, Expand and Super Expand icons, the list reloads with the Storyteller Seeds list instead of the list that you were viewing.

**To Reproduce**
1. Go to Articles 
2. Click Unpublished Articles
3. Click the Refresh icon
4. See error, the Storyteller Seeds list will load

**Expected behavior**
The unpublished article list should refresh, not the Storyteller Seeds

**Comment by Kordishal** [comment]
Can confirm for Unpublished & WIP. Stubs reloads the correct list.

Thanks for reporting!

**Comment by iamromeo** [comment]
Fixed - will be deploying today - thank you for reporting!
