### ISSUE TITLE
entering year on event (start date) manually doesn't work

### ISSUE THREAD

**Issue by mfcarbo-author** [worldanvil/worldanvil-bug-tracker#592]
**World Anvil Username**: mfcarbo

**Chronicle Title**: https://www.worldanvil.com/w/practice-of-power/chronicle/saylossan-chronicle-chronicle

**Chronos System**
 event

**Describe the Issue**
I am not able to easily set a year manually (without a hack workaround). I'm working with millennia time spans and need to set large numbers for the year. But this problem affects any manually entered number.

**To Reproduce**
1. Click + to create a new event (or edit one... same problem either way)
2. Click on the "start" down arrow. 
3. Click on the "0" in the year field and enter a different number. The field in the "start" text does not update.
4. Click the back or forward buttons and the year is updated as desired. You can then click back or forward again to the year you want. 

**Expected behavior**
I expect to remove the 0 from the field, enter the year I want, and click save. 

**Screenshots**

https://user-images.githubusercontent.com/74458780/134788332-8a7a04b3-6db6-4bee-b65d-88b1e3a094e5.mov

**Comment by iamromeo** [comment]
Please do not post bug reports for ALCHEMIST features here - they have their own boards 
Also please do not assign developers
