### ISSUE TITLE
WorldAnvil bug with These Are the Voyages Theme

### ISSUE THREAD

**Issue by kinghumble1** [worldanvil/worldanvil-bug-tracker#594]
**World Anvil Username**: kinghumble

**World / Campaign / RPG Character / Manuscript Title**: Star Trek Timeline T

**Feature**: Timelines - Images

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/star-trek---timeline-t-kinghumble/h/e39701c3-94af-4da7-9b25-e540663dd25b

**Describe the Issue**
A clear and concise description of what the issue is.

I am trying to embed images to be Centred in my posts, but they are always coming up aligned to the Left on the "These Are the Voyages" theme. I am able to align them to the Centre if I switch to a different theme, but not the theme that directly matches my campaign.

**To Reproduce**

**Expected behavior**

I try to designate my images to align in the Centre of a post, but they always come out aligned to the Left no matter what I try. I can align them properly in different themes, but not the These Are the Voyages theme.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Can you please show me the BBcode you are using to align this image?

**Comment by kinghumble1** [comment]
![World Anvil image](https://user-images.githubusercontent.com/91435401/134923119-f09818c5-9756-4133-bdea-6ee4227b1f58.png)

**Comment by kinghumble1** [comment]
Hello, please see the attached screenshot for verification that I essentially used the Ctrl+E function to attempt to centre the image. I will post another screenshot below of the resulting post and how the image remains on the left-margin

**Comment by kinghumble1** [comment]
![World Anvil image2](https://user-images.githubusercontent.com/91435401/134923526-54688d81-6e16-4631-b2dc-b3ab7805105e.png)

**Comment by iamromeo** [comment]
This is not a centered image, this is a centered paragraph bud :) Have a look at the codex - you are looking for something long the links of [img:12345|center]
