### ISSUE TITLE
CSS @media rules are added to WorldAnvil TODO list

### ISSUE THREAD

**Issue by skairunner** [worldanvil/worldanvil-bug-tracker#595]
**World Anvil Username**: skairunner

**World / Campaign / RPG Character / Manuscript Title**: The Story

**Feature**: CSS

**Related URLS** (To public & visible pages add screenshots otherwise):
![image](https://user-images.githubusercontent.com/3517115/134919035-007e4497-b051-4c9f-af77-f340665ecf96.png)
![image](https://user-images.githubusercontent.com/3517115/134919132-d4940016-d667-42f4-a0d9-a7153498078d.png)

**Describe the Issue**
Using `@media` rules in page CSS is picked up in the TODO list, once for each `@media` rule.

**To Reproduce**
1. Create an article
2. Go to Design/CSS
3. Use an `@media` rule such as:
```css
@media screen and(max-width: 1200px) {
}
```
4. TODO list should have a new entry "MEDIA SCREEN AND", with the category set to "Max-width: 1200px". 

**Expected behavior**
I would not expect anything in CSS to be detected as a worldanvil mention and added to the TODO list.

**Screenshots**
See above for screenshots.

**Comment by iamromeo** [comment]
hahhahaah that is very very funny - ok I will see what I can do about that :)

**Comment by iamromeo** [comment]
Patched - will deploy within the next 48 hours
