### ISSUE TITLE
Categories Moved Across Worlds

### ISSUE THREAD

**Issue by david-clark** [worldanvil/worldanvil-bug-tracker#596]
**Categories**: 

**Describe the Issue**
This was found and confirmed with Firefox.  I have not tested this with other browsers.  With multiple tabs open, it's possible when shifting worlds to create categories that are a part of one world and the add them as children of categories in another world.

**To Reproduce**
1. Navigate to World 1's Articles & Categories.
2. Open 2nd Tab to World Anvil and change world from World 1 to World 2.
3. Go back to 1st Tab, create a new category and drag a category from World 1 into the new category.
4. Refresh Tab 2 and you should see the new category with the other world's category inside.
5. Navigate back to World 1 and the category dragged into World 2's category is no longer there.
6. It appears to act as a normal category otherwise with the exception of seeing articles when viewing the category.

**Expected behavior**
Should not be able to move categories between worlds.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Actually this is a community requested feature :) 
- Category should be possible to be moved across worlds
- On the other hand, working on multiple tabs is really discouraged.
