### ISSUE TITLE
I cannot make a world! :[

### ISSUE THREAD

**Issue by gahdamncam** [worldanvil/worldanvil-bug-tracker#598]
**World Anvil Username**: gahdamncam

**World / Campaign / RPG Character / Manuscript Title**: Tyrra

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

Everytime I go to make my first world I get an error. I tried typing nothing and I tried filling out the paragraph in full. The error continued even AFTER I paid for full subscription. Hoping to get this resolved so I can use this wonderful site I've heard so much about. :D

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Hello @gahdamncam can you please let me know if: 
- Did you have an account with the same username before?
- Did this account had a world with the same name before?

**Comment by iamromeo** [comment]
After investigation both of the above were true which triggers teh system's copyright protection. 
I am removing the lock for you 
YOu should be able to create your world in 2 minutes

**Comment by gahdamncam** [comment]
Haha. Yeah I totally did use the same name before. I changed the name and
it worked. My bad!

**Comment by Kordishal** [comment]
You should be able to create a world with the original name as well, as Dimitris removed the copyright lock.
