### ISSUE TITLE
I can't post any more journal entries, and I only have 26 so far

### ISSUE THREAD

**Issue by suchaCoffeeCat** [worldanvil/worldanvil-bug-tracker#599]
**World Anvil Username**: suchaCoffeeCat

**World / Campaign / RPG Character / Manuscript Title**: Cali Zendyr (character)

**Feature**: Journals 

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/hero/dfdd7f63-ef1a-456c-ba73-7407cadee0e1 this is her profile. 

**Describe the Issue**
A clear and concise description of what the issue is.
So I just created my account about a week or so ago, with the intention of transferring all my old campaign notes onto this page so my whole group can read my session notes. I typed many of them up manually and posted them, and then i copied and pasted several more from the notes I had on my computer. However, when I got to Session 27, I did everything the same as I had been, but when I click "sign and post", it takes me to a 404 screen, with a picture of a dragon and a quote that says "and thus, you have reached the end of the world." I can't find a post limit anywhere on the site, and at first I thought it might be because I posted so many in one day, but it's an entirely different day now and I just tried again and it's still giving me the error. I have a ton more entries to add--we're on like session 75 or something now and i want to use this in the future for each new session, but if it's stopping me this early on, i won't be able to use it and will have to switch to a different website. It's also weird because the site has saved my session title and the date, only in the sense that when I click on the title it's a suggested option that I can click on now, but it doesn't show up at all in my journals folder. 

**To Reproduce**
1. Go to '...' - Journals
2. Click on '....' - Write New Journal
3. Scroll down to '....' - "Sign&Post" after typing an entry

**Expected behavior**
I of course expected the journal entry to post to my profile without issue, the same way the others posted. And not just this journal entry, but many more to come! 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
When the journal entry fails like this, it likely means that it cannot save. So whatever you are copying & pasting contains something that World Anvil cannot process.

Try to copy from a note-editor or somewhere without formatting.

This definitely needs some polish in the future to show such an error instead of just going to the 404 page.

**Comment by Kordishal** [comment]
And on a side note: Journal entries aren't really intended for how you are using them, I believe. There is an article template for session reports with some useful fields.

**Comment by iamromeo** [comment]
Note: There is no limit on the number of journals

**Comment by iamromeo** [comment]
@suchaCoffeeCat can you please create a new one with just one word in it - the chances are that something on your text is out of bounds, probably a special character or something similary. 

Let me know how it goes

**Comment by suchaCoffeeCat** [comment]
> When the journal entry fails like this, it likely means that it cannot save. So whatever you are copying & pasting contains something that World Anvil cannot process.
> 
> Try to copy from a note-editor or somewhere without formatting.
> 
> This definitely needs some polish in the future to show such an error instead of just going to the 404 page.

That wouldn't make sense though, because I was copying it from the same notes app note as the others. There weren't any special characters or anything like that, I triple checked it because I saw that on the FAQ page. 

> @suchaCoffeeCat can you please create a new one with just one word in it - the chances are that something on your text is out of bounds, probably a special character or something similary.
> 
> Let me know how it goes

I was successfully able to post that one, so I'm not sure what the issue was? I can try just typing the entry manually but again, I was able to copy and paste without issue beforehand

**Comment by suchaCoffeeCat** [comment]
okay, i'm still super confused about what the issue was--I still copied and pasted it but randomly selected lines to manually type, and i copied some of it in sections instead, but it worked? very confused, but also hoping this never pops up again. thanks for your responses!!
