### ISSUE TITLE
Interactive tables do not display their full height when placed within spoilers

### ISSUE THREAD

**Issue by Rozarik** [worldanvil/worldanvil-bug-tracker#6]
**World Anvil Username**: 
Rozarik

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 
Interactive Tables & Spoilers

**Related URLS** (add URLs of the pages that do not work!):

**Describe the bug**
Interactive tables are prevented from displaying their full height when placed within a spoiler.

**To Reproduce**
1. Create an interactive table with several rows.
2. Copy the interactive table's embed code.
2. Create an article and insert a spoiler.
3. Paste the interactive table's embed code within the spoiler.
4. Save the article and view it.
5. Locate the the spoiler on the article and click it to expand.
6. The interactive table will not be fully displayed.

**Expected behavior**
When a spoiler is expanded, any interactive tables that are contained within it should display their full-height.
![WorldAnvil_Bug_InteractiveTables_And_Spoilers](https://user-images.githubusercontent.com/79772384/109403638-4726d980-7913-11eb-8667-d72006190817.jpg)

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Interactive tables are not meant to be used inside of spoilers. 
There is an option to load only the header of the table with the ability to expand it.
