### ISSUE TITLE
Presentation Mode Marker Placement Closing

### ISSUE THREAD

**Issue by Shadowclaimer** [worldanvil/worldanvil-bug-tracker#60]
**World Anvil Username**: Shadowclaimer

**Describe the Issue**
When creating new markers in Presentation Mode simply mousing over another marker closes your in-progress marker creation. This is problematic for maps with plenty of markers and a simple mouse movement to swap text boxes can close your progress.

**To Reproduce**
1. Go to Presentation Mode on any map (one that already has markers)
2. Right Click to create a new marker
3. Put in some basic information, do not hit create yet
4. Mouse over any other marker you've already created
5. Watch as your in progress creation closes

**Expected behavior**
My in-progress marker to stay up until either I click elsewhere, close them, or finalize them. When you're working with a map with a ton of markers this can get incredibly annoying and eats a lot of time. Its also problematic because the window for creation expands upwards when you select a pin type, sometimes causing you to have to cross other markers to reach it.

**Comment by iamromeo** [comment]
Although frustrating, this is not a bug. This will be addressed with Atlas.
