### ISSUE TITLE
Issue with accessing World Anvil pages

### ISSUE THREAD

**Issue by MrSinnerael** [worldanvil/worldanvil-bug-tracker#600]
**World Anvil Username**:

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
worldanvil keeps crashing with 404 error, won't load images or refresh, I need direct assistance and repair to my account.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Then come to the [Discord](https://worldanvil.com/discord) server. This is not a bug most likely.

Try to access the page with a private / incognito window. This would mean the issue is caused by an extension / plugin on your browser.

Otherwise, we will need a lot more information than just the title.

**Comment by MrSinnerael** [comment]
I've tried two different computers. I've cleared the cache and history, scanned for errors, bugs etc on my end. I've installed no new extensions. I log in it looks fine until I open a page, try to edit or attempt to upload an image. 
Sent from Yahoo Mail on Android 
 
  On Fri, Oct 1, 2021 at 1:27 AM, Jonas ***@***.***> wrote:   


Then come to the Discord server. This is not a bug most likely.

Try to access the page with a private / incognito window. This would mean the issue is caused by an extension / plugin on your browser.

Otherwise, we will need a lot more information than just the title.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kordishal** [comment]
I will need more information.

What pages are you trying to access? At what point does it fail? What still works? Since when has this been happening? Do you have a subscription? Did your subscription recently end? What is the name of your world? What is your username on World Anvil?

It would be a lot easier to help you on the Discord: [https://worldanvil.com/discord](https://worldanvil.com/discord)

**Comment by MrSinnerael** [comment]
I am able to open the global dashboardI click on articles and categories it times out to a 404 page The issue has been getting progressively worse. At first, it was an occasional error. but it's degraded now to being unable to perform anything at all. I first noticed maybe 5 days ago.I do have a subscriptionMy subscription has not endedReturn to Ravenloft is the world, Mr. Sinn is the username 
I will try discord tomorrow. At this point, I can't go anywhere, not even my profile. Everything fails, times out to a 404
    On Friday, October 1, 2021, 02:01:22 AM PDT, Jonas Waeber ***@***.***> wrote:  
 
 


I will need more information.

What pages are you trying to access? At what point does it fail? What still works? Since when has this been happening? Do you have a subscription? Did your subscription recently end? What is the name of your world? What is your username on World Anvil?

It would be a lot easier to help you on the Discord: https://worldanvil.com/discord

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kordishal** [comment]
Can you link the World? I can't find it with that title.

**Comment by iamromeo** [comment]
@Kordishal the world is private the user is 
Journeyman MrSinn f308f576-3f83-4332-820d-b97a509f3b55
 
@MrSinnerael this is not a global issue so I will check which of the content you entered caused a problem. 

1. Can you please give me some more infrormation of any change on the way you have been using WA lately or something that you believe it might have triggered this 
2. Can you send me an email at hello@worldanvil.com with a newly created password for your account AND a list of pages/actions that have caused this 404 in the past

**Comment by MrSinnerael** [comment]
Okay, again it's every page. I've done nothing new.The problem started as a hiccup and Id have to refresh or close and reopen but it got way worse this week. Now I can't edit or add anything.
Today I opened a page I had created, copied text into the body saved. Clicked to view.all that was fine. 
tried to go back to edit view, timed out. So whenever I attempt to edit, change, load a picture, view any page it does this.     On Friday, October 1, 2021, 03:35:38 AM PDT, Dimitris Romeo Havlidis ***@***.***> wrote:  
 
 


@Kordishal the world is private the user is
Journeyman MrSinn f308f576-3f83-4332-820d-b97a509f3b55

@MrSinnerael this is not a global issue so I will check which of the content you entered caused a problem.
   
   - Can you please give me some more infrormation of any change on the way you have been using WA lately or something that you believe it might have triggered this
   - Can you send me an email at ***@***.*** with a newly created password for your account AND a list of pages/actions that have caused this 404 in the past

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MrSinnerael** [comment]
Okay, so I shut down everything else I can think of. I was able to do edits but as soon as I view the page and try to back an error to reedit it drops to 404 again.
    On Friday, October 1, 2021, 12:00:24 PM PDT, Cam Turner ***@***.***> wrote:  
 
  Okay, again it's every page. I've done nothing new.The problem started as a hiccup and Id have to refresh or close and reopen but it got way worse this week. Now I can't edit or add anything.
Today I opened a page I had created, copied text into the body saved. Clicked to view.all that was fine. 
tried to go back to edit view, timed out. So whenever I attempt to edit, change, load a picture, view any page it does this.     On Friday, October 1, 2021, 03:35:38 AM PDT, Dimitris Romeo Havlidis ***@***.***> wrote:  
 
 


@Kordishal the world is private the user is
Journeyman MrSinn f308f576-3f83-4332-820d-b97a509f3b55

@MrSinnerael this is not a global issue so I will check which of the content you entered caused a problem.
   
   - Can you please give me some more infrormation of any change on the way you have been using WA lately or something that you believe it might have triggered this
   - Can you send me an email at ***@***.*** with a newly created password for your account AND a list of pages/actions that have caused this 404 in the past

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iamromeo** [comment]
The username/passoword provided are incorrect. I have emailed the used no response the last 24 hours

**Comment by MrSinnerael** [comment]
I was advised by your tech support to change my password by sending it to this address, that is what I did. I don't need it changed personally. I need Worldanvil to stop crashing when I use it. 
    On Sunday, October 3, 2021, 06:04:37 AM PDT, Dimitris Romeo Havlidis ***@***.***> wrote:  
 
 


The username/passoword provided are incorrect. I have emailed the used no response the last 24 hours

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iamromeo** [comment]
I am sorry but I am not sure you understood my answer. The username/password combination you have provided does not work. I need you check that it is correct and send me again the username/password combination on the email we provided you with.

**Comment by MrSinnerael** [comment]
***@***.***
***@***.***
    On Sunday, October 3, 2021, 10:20:19 PM PDT, Dimitris Romeo Havlidis ***@***.***> wrote:  
 
 


I am sorry but I am not sure you understood my answer. The username/password combination you have provided does not work. I need you check that it is correct and send me again the username/password combination on the email we provided you with.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kordishal** [comment]
Luckily for you cannot send passwords to GitHub. This is a public board.

Dimtiris requires the access in order to be able to understand what is going on with your account. What is happening to you is not happening in general.

Send the username and password of you account to hello@worldanvil.com . This way Dimitris will be able to access your account and hopefully figure out what is going on.

**Comment by MrSinnerael** [comment]
Awesome so I did that. And now it's been a week of the service barely working and another week of asking for help. Your system for handling issues is very frustrating. Also, yall keep saying it isn't a problem for anyone else, and whether or not that is true doesn't help the issue from my end. 

    On Sunday, October 3, 2021, 10:48:44 PM PDT, Jonas Waeber ***@***.***> wrote:  
 
 


Luckily for you cannot send passwords to GitHub. This is a public board.

Dimtiris requires the access in order to be able to understand what is going on with your account. What is happening to you is not happening in general.

Send the username and password of you account to ***@***.*** . This way Dimitris will be able to access your account and hopefully figure out what is going on.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iamromeo** [comment]
I am sorry @MrSinnerael but have you changed the credentials again after sending me the second email ? 
These creds ALSO do not work. I am trying to help you but I cannot replicate this and I do need access to your account.

**Comment by iamromeo** [comment]
This is confirmed as an account level issue. 

@MrSinnerael can you please give me some more information in regards to what you have been doing when this issue started appearing so I can get a better understanding on where to start searching for the issue ?

Please try to be as specific as possible so I can understand the situation better

Just to put your mind at east
1.This is not an issue with your data. all is safe
2. when this is resolved I will be adding the time you lost in your account, plus some

**Comment by MrSinnerael** [comment]
I first noticed when I would try to upload an image or when I would go to preview a page id created. It got progressively worse. So now if I preview the page it won't go back to editing, won't load a new page won't do anything unless I close down explorer and log in again. 
    On Monday, October 4, 2021, 08:39:06 PM PDT, Dimitris Romeo Havlidis ***@***.***> wrote:  
 
 


This is confirmed as an account level issue.

@MrSinnerael can you please give me some more information in regards to what you have been doing when this issue started appearing so I can get a better understanding on where to start searching for the issue ?

Please try to be as specific as possible so I can understand the situation better

Just to put your mind at east
1.This is not an issue with your data. all is safe
2. when this is resolved I will be adding the time you lost in your account, plus some

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iamromeo** [comment]
Still in the process of investigating. Spotted an issue with an article under the places category which has no slug somehow. I am not sure if this is the cause of your problem - still investigating

**Comment by iamromeo** [comment]
I have actually found another 7 but these are not the cause of the issue - it's certainly localized on your Places category which I am currently going though to investigate. 

Some notes
- A category should not have in it more than 20 articles
- An article should not have over 3 - 5 sub articles you have articles with over 20 nested. 

I cannot confirm just yet if that is the issue - still going though. What I can say for sure is that there is a memory leak somewhere because the page 500s

**Comment by iamromeo** [comment]
Ok the only issue I can find is this category and honestly I cannot understand for the life of me why this is the case. I will be deleting this category - all the articles of the Places category is under the Quarantine one which actually works just fine. 

You can remain that to Places, but it might be cursed so I would be careful, it looks that Strahd did not like you writing about him. 

I would strongly suggest that you make actual categories out of your super articles with sub articles because I am still not 100% convienced that this is not a residual issue due to that.

**Comment by iamromeo** [comment]
Also it goes without saying but you have done some truly beautiful work with your world.

**Comment by iamromeo** [comment]
You also seem to have a problem with your map village of Barovia which somehow has not image?! 
These are quite odd issues. 
- Which browser are you using when editing your world
- Would you say you are in a stable connection
-

**Comment by MrSinnerael** [comment]
Alright thats fine. I guess if I hadn't set it up properly anyway it won't hurt anything.

Sent from Yahoo Mail on Android 
 
  On Thu, Oct 7, 2021 at 9:46 PM, Dimitris Romeo ***@***.***> wrote:   


I am deleting the Village of Barovia map for you so you have no issues.

there was a single marker on the 0,0 (which means that somehow was also never assigned.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MrSinnerael** [comment]
Yes stable, home network. No other issues.Im using Google chrome.

Sent from Yahoo Mail on Android 
 
  On Thu, Oct 7, 2021 at 9:44 PM, Dimitris Romeo ***@***.***> wrote:   


You also seem to have a problem with your map village of Barovia which somehow has not image?!
These are quite odd issues.
   
   - Which browser are you using when editing your world
   - Would you say you are in a stable connection
   - 

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iamromeo** [comment]
OK I went through yout account with the finest comb I could find - all should be OK now  
I will add 1 month to your subscription for time lost and keep an eye

**Comment by MrSinnerael** [comment]
It would be very helpful
    On Thursday, October 7, 2021, 10:17:39 PM PDT, Cam Turner ***@***.***> wrote:  
 
 Awesome thank you. Can you give me a check list of what I should do on my end? I was confused about some of your terms.

Sent from Yahoo Mail on Android 
 
  On Thu, Oct 7, 2021 at 10:05 PM, Dimitris Romeo ***@***.***> wrote:   


OK I went through yout account with the finest comb I could find - all should be OK now
I will add 1 month to your subscription for time lost and keep an eye

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
