### ISSUE TITLE
Minor Typo

### ISSUE THREAD

**Issue by BackworldTraveller** [worldanvil/worldanvil-bug-tracker#601]
**World Anvil Username**: BackworldTraveller

**World / Campaign / RPG Character / Manuscript Title**:
https://www.worldanvil.com/studio/article/list
**Feature**: 
https://www.worldanvil.com/studio/article/list
**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/studio/article/list
**Describe the Issue**
The text in the "CRAFT YOUR OWN TEMPLATES" block has "ot" instead of "to"

**To Reproduce**
Go to the template

**Expected behavior**
Should be spelt correctly

**Screenshots**
N/A Text currently reads...
CRAFT YOUR OWN TEMPLATES
Custom article templates will allow you completely modify the way the standard templates of World Anvil look. You will be able ot use HTML/CSS and Twig to completely redesign the way your articles are presented.

**Comment by iamromeo** [comment]
Thank you very much for the heads up - this is now fixed
It will be deployed later on today.
