### ISSUE TITLE
Adding Onslaught to the list of RPG Systems

### ISSUE THREAD

**Issue by UberAffe** [worldanvil/worldanvil-bug-tracker#602]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name (RPG SYSTEM)**: Onslaught
**List Name** (Name under which it should be listed on World Anvil): Onslaught
**World Anvil Username**: UberAffe

**Website**: https://docs.google.com/document/d/1umH9jwAhcZnanjvxHk1_m0PPC_KPOKg7Za6yZt0l5XE/edit?usp=sharing

**Logo Image Link**: https://i.imgur.com/DcYrOWQ.png

**Logo Usage Terms (URL)**:

I am the developer of Onslaught and it has reached the point where character sheets and creature statblocks can be created.

**Comment by iamromeo** [comment]
All done :)
