### ISSUE TITLE
wrong channel name for "do you need help?"

### ISSUE THREAD

**Issue by grimreaper** [worldanvil/worldanvil-bug-tracker#603]
**Feature**: the "do you need help?" explanation has the wrong channel

It should say "#help" instead of "#guild-help"

**To Reproduce**
1. Go to https://www.worldanvil.com/world/chronicle/list (or any other page with the same dropdown)
2. Click on 'do you need help?'
4. see help text

**Expected behavior**
correct channel is shown

**Screenshots**
<img width="363" alt="image" src="https://user-images.githubusercontent.com/433817/135731502-436077be-3d0b-4281-9f28-8d659b9a7dda.png">

<img width="318" alt="image" src="https://user-images.githubusercontent.com/433817/135731554-ef906092-39ba-4ede-b31d-e171223cb0cc.png">

**Comment by iamromeo** [comment]
Done - will deploy later on
