### ISSUE TITLE
Error when trying to export

### ISSUE THREAD

**Issue by Alithert** [worldanvil/worldanvil-bug-tracker#604]
**World Anvil Username**:
jandis
**World / Campaign / RPG Character / Manuscript Title**:
Tir-nirvaal
**Feature**: 
Export Worlds & Manuscripts 
**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

Attempting to export my world documents brings us the error
 Job failed: AttributeError: module 'foundry.utilities' has no attribute 'tasks'

**To Reproduce**
1. Go to 'https://toolbox.soullink.docker.worldanvil.com/backup/form'
2. Click on 'start' after adding key and email adress
3. wait

**Expected behavior**

A cornfirmation that my world's documents were sent to my email address.

**Comment by Guinean** [comment]
I have had this same issue. I have tried multiple emails, logging in/out. I get the exact same error as described above.
![WA error](https://user-images.githubusercontent.com/73323189/135772976-fc5b12df-8552-4b44-8537-b44fb1a9c5b4.png)

**Comment by GorkamWorka** [comment]
To answer, we are aware of that bug, and i think i know where it does come from so we will look into fixing it

**Comment by Alithert** [comment]
thank you for the response.
