### ISSUE TITLE
Building Template: error when creating 'Including vehicle' article from the edit page directly

### ISSUE THREAD

**Issue by Amancham** [worldanvil/worldanvil-bug-tracker#605]
**World Anvil Username**: Amancham

**World / Campaign / RPG Character / Manuscript Title**: Playground (Private, but not neccesary, anyway)

**Feature**: Building Template - Creating and Linking article for "Including Vehicle"

**Related URLS** (To public & visible pages add screenshots otherwise): n/a

**Describe the Issue**
In the Room section under "Including Vehicle": 
When using the "Create new article and link it" feature on this specific item, Worldanvil will create an organziation article instead of a vehicle article. (It's only this one, all the others work as expected)
The Name of the new article is shown and it looks like everything is working. 
However, saving does not work. Any and all changes, additions and edits done after creating the supposed vehicle article and linking it to the current one, will be lost, without warning. With autosave running, the page does regularly say that changes have been saved, but when exiting the edit view, all changes are lost and instead of a vehicle article, an organization article has been created with the title used in that field.
The Search bar in the "Including Vehicle Section" will search for vehicles, though. If you have created the vehicle before, you are golden, can just pick it from the list and won't encounter any errors unless you want to UNLINK the article. That, again, has issues related to the here described bug.

**To Reproduce**
1. Go to Dashboard and create a new building Article.
2. Add some Lorem Ipsum to the vignette and make sure it saves.
3. Click on the "Room" tab 
4. At the first item "Including Vehicle" click on "Create new article and link it" 
5. Enter "New Vehicle Article" and click "Create & Link" 
6. The Title will be displayed as expected
7. Go to "Design" and enter some Lorem Ipsum here, too. 
8. Put some more in Entries or any other box 
9. Make sure you trigger a save and see the green notification saying that the page has saved (go ahead and click the save button, too, makes no difference)
10. Leave the article and go back to Articles & Categories 
11. Find a new Article created as expected with "New Vehicle Article" as title but it is an organization Template 
12. Click back into your Building article either via viewing and editing or directly going to edit, doesn't matter. 
13. See that the Room - Including Vehicle section is empty again and the text filled in AFTER you created the new article, is lost. The "Design" Text field and others will be empty.

Addition: Upton further testing, I noticed that on the top where it normally tells you the word count and time of the last save, it says "Last Saved undefined WA Time " after hitting the wrong template created and linked issue. However, you still get a green little popup saying that it has successfully saved. But I guess that is another issue entirely?
![wa_error](https://user-images.githubusercontent.com/25498928/135749774-beccfe26-8e21-4c40-9d80-f1a1d44228cd.jpg)

**Expected behavior**
I'd expect a vehicle article to be created, not an organization. 
Also, I would expect a red popup stating that there was an issue/error while trying to save, so that I don't lose all my edits, just because I thought the green "saved" popup is correct and left the edit mode to work on another article or view the newly created article. 
Especially if you are further down on the page and don't actually see the hint with the unidentified WA Time up top. All you see is a green little popup stating that changes have been saved.

**Screenshots**
![wa_error2](https://user-images.githubusercontent.com/25498928/135749835-d548bb85-ea0b-4cff-8f7c-e4e9dd51c45c.jpg)
![wa_error3](https://user-images.githubusercontent.com/25498928/135749845-24e31ef5-f0bd-491b-9348-8bb7cba33454.jpg)

**Comment by iamromeo** [comment]
Thank you for the heads up - I will be deploying the fix soon
