### ISSUE TITLE
Information Box suddenly placed below the article

### ISSUE THREAD

**Issue by Kohrune** [worldanvil/worldanvil-bug-tracker#606]
**World Anvil Username**: Amelia Barcroft

**World / Campaign / RPG Character / Manuscript Title**: Falldenai

**Feature**: Article (Location)

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/aldrune-ambarcroft/a/falldenai-location 

**Describe the Issue**
I've been working on this article and it is currently live as what I'm calling "A live Article" that updates as my Pathfinder Players continue in the campaign. Suddenly after saving and taking a break as I got stumped when it comes to a certain area I checked the article to see if everything was aligned correctly and notice the Information box on the right of the article was suddenly beneath the actual Article and I'm unsure if this is a bug or if I accidentally messed up somewhere and caused an issue. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the linked URL
2. Scroll down to the bottom to see the text box which is normally next to the article.

**Expected behaviour**
To have the article in line with the information bar on the right-hand side at the top of the article. 

**Screenshots**
![Bottom of the article](https://user-images.githubusercontent.com/91840416/135762199-813839af-f715-437f-95f1-2ef7928b6f14.JPG)

**Comment by Kordishal** [comment]
This is likely not a bug, but instead an unclosed BBCode tag in the main body of your article. Like [in], [row], [col] and a few others can cause this when unlosed.
