### ISSUE TITLE
Broken account after deleting and reregistering

### ISSUE THREAD

**Issue by JCorcelli** [worldanvil/worldanvil-bug-tracker#607]
**World Anvil Username**: Xander Pfotegeist

**Describe the Issue**
I get a 404 if I try to make a new world.

**To Reproduce**
1 Register
2 Delete account
3 Register again
4 Attempt to delete account, get a 404
5 Delete world
6 Try to make a new world, get a 404 every time

**Expected behavior**
I expect to be able to delete my account and remake it once without a fuss
I expect to be able to delete and remake worlds at will

**Comment by iamromeo** [comment]
This is not a bug this is part of the Copyright/ Intellectual Property lock feature.

**Comment by Kordishal** [comment]
To add a bit of context:

The copyright lock exists to protect the work of creates. With this they can proof that and when they created a work on World Anvil. This can help to defend / fight a copyright claim.

Accounts with a subscription, can request to have their copyright lock lifted. As this comes with some administrative overhead.

You can change your username or your world name to recreate them (any change will not trigger the copyright lock).
