### ISSUE TITLE
Cannot Center Image

### ISSUE THREAD

**Issue by kinghumble1** [worldanvil/worldanvil-bug-tracker#608]
This is not a centered image, this is a centered paragraph bud :) Have a look at the codex - you are looking for something long the links of [img:12345|center]

_Originally posted by @iamromeo in https://github.com/worldanvil/worldanvil-bug-tracker/issues/594#issuecomment-927995844_

Hello, I had a busy week at work and was unable to follow up until tonight. I have looked in the Codex but been unable to solve my issue. I have looked at the following page in the Codex and it has no advice on how to center an image:

https://www.worldanvil.com/w/WorldAnvilCodex/a/images

I have tried experimenting with using the [img:12345|center] commands you outline above but with no success. 

Please advise?

**Comment by kinghumble1** [comment]
This is what I see when I try to center the image using the [img:12345|center] example:

![Fuck](https://user-images.githubusercontent.com/91435401/135774583-9e28eadd-b50d-4cf1-97d6-d188ba215641.png)

**Comment by kinghumble1** [comment]
Ok, i think i figured it out...... Copy-and-pasting the Img code [img:2674948] doesn't work for centering the image. It seems I need to manually type out the [img:2674948] code before i have the ability to add the [|center] addendum. If I copy-and-paste the image using WorldAnvil's generated code, the image just pops up in the post and I have no access to influence the formatting. 

It's very inefficient and requires me to keep on flipping back and forth between tabs to input hte img code manually, but it at least gets the result I want. I hope you guys create an easier way in the future to adjust the formatting of images in posts!

**Comment by iamromeo** [comment]
Ummmm you do not need to do that just use the [ automation and the name of your image For example is the image is called "Warthog" just type [War and you will get a dropdown

After that, just add the |center part if you want it centered
