### ISSUE TITLE
Exporter Job Failing

### ISSUE THREAD

**Issue by eccbooks** [worldanvil/worldanvil-bug-tracker#609]
**World Anvil Username**: eccbooks

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: World Exporter

**Related URLS** (To public & visible pages add screenshots otherwise): https://worldanvil.com/w/eccbooks

**Describe the Issue**
I'm receiving an error message when I try to export my world (which I do once a month as an extra backup, because I'm paranoid).

<img width="1148" alt="Screen Shot 2021-10-04 at 7 55 12 PM" src="https://user-images.githubusercontent.com/83819488/135940321-31bcd231-69a9-489a-bc59-826df8ac400c.png">

**Comment by iamromeo** [comment]
Please check the board before submitting a new bug :) this is already here #604
