### ISSUE TITLE
Account Deletion Error

### ISSUE THREAD

**Issue by HotSauce-12** [worldanvil/worldanvil-bug-tracker#616]
**World Anvil Username**:

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I no longer plan to use World Anvil, and would like to delete my account. Every time I try I get a 404 error.

**To Reproduce**
1. Go to Account Settings
2. Scroll down to "Account Deletion" 
3. Type in username and click "Delete Account"

**Expected behavior**
My Account to be deleted

**Screenshots**
![Screenshot 2021-10-05 9 58 48 PM](https://user-images.githubusercontent.com/92064885/136299963-1af2717c-49ed-49c2-a128-0cd7e3c0e747.png)

**Comment by iamromeo** [comment]
There is no account under the username HotSauce-12 and no other information has been submitted. This is not a global issue.

**Comment by iamromeo** [comment]
The reason you cannot delete your account is that you already had an account that you deleted before, with the exact same username and email which is in direct violation of Terms of Service. I will be releasing the lock but this is not a bug.
