### ISSUE TITLE
Theme "The Great Gamemaster" causes issues with the Calendar

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#62]
**World Anvil Username**: SoulLink
**Feature**: Calendar / Theme The Great Gamemaster

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/breaking-anvil-soullink/a/test-calendar-article

**Describe the Issue**
The Great GM Theme does not play nice with the calendar numbers. They are way too big due to being targeted for h3.

**Expected behavior**
Smaller numbers

**Comment by jonaswaeber** [comment]
Sent the link to the issue to TJ via Discord.
