### ISSUE TITLE
404 Issue For Editors

### ISSUE THREAD

**Issue by mknnmknn** [worldanvil/worldanvil-bug-tracker#621]
**World Anvil Username**: makonnen

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Multiple reports in the #help channel regarding editors getting 404's when trying to view articles, whether through direct links or from the VIEW button.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by CBairdAsh** [comment]
My information can be found here: https://github.com/worldanvil/worldanvil-bug-tracker/issues/620
