### ISSUE TITLE
Phantom notifications

### ISSUE THREAD

**Issue by artyrambles** [worldanvil/worldanvil-bug-tracker#625]
**World Anvil Username**: arty

**World / Campaign / RPG Character / Manuscript Title**:  https://www.worldanvil.com/w/writers--home-pierrot05

**Feature**: Private Comments

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/writers--home-pierrot05/a/compelling-conflict-between-characters-article

**Describe the Issue**
I received a notification for a comment on an article that I wrote for a world I'm a contributor for. The comment seems to be private, so I cannot see it at all.

**To Reproduce**
1. Write article for a world you're an Editor for
2. Someone leaves a private comment on the article
3. I receive a notification about the comment
4. But I cannot actually see the comment

**Expected behavior**
I would think that either
a) I'd be able to see the comment or 
b) not get a notification for it.

**Screenshots**
![7680_keepincool](https://user-images.githubusercontent.com/29456646/136856766-261ad44e-c658-4dd9-84df-611dab0df2b2.png)

**Comment by iamromeo** [comment]
Well it was certainly a hilarious image. My question is - replied to comments cannot be private unless the initial message was - can you please explain the series of events abit
