### ISSUE TITLE
Auto-save doesn't trigger in Manuscripts when blanking out interface settings

### ISSUE THREAD

**Issue by OndoAlvelle** [worldanvil/worldanvil-bug-tracker#631]
**World Anvil Username**: Ondo

**World / Campaign / RPG Character / Manuscript Title**: Any

**Feature**: Manuscripts

**Related URLS** (To public & visible pages add screenshots otherwise): any Manuscripts editing page

**Describe the Issue**
When you edit interface settings (like paragraph ident or CSS extra rules) the auto-save triggers as normal. However, if the result of the edit is blanking out the field, it won't trigger. Triggering the auto-save by editing another field does not save the blanked out field.

**To Reproduce**
1. Go to any Manuscripts and edit it
2. In the "Default Interface Settings", delete any custom values. Notice that the "Saved" notification won't appear.
3. Reload page
4. See that the field returns to the previous value

**Expected behavior**
Auto-save should trigger when blanking out fields.

**Comment by iamromeo** [comment]
This is a known issue and not easy to solve. It is already noted for Manuscripts II but it will not be addressed at an earlier time
