### ISSUE TITLE
Text layout in Basic NPC Profile is wrong

### ISSUE THREAD

**Issue by seanhagen** [worldanvil/worldanvil-bug-tracker#632]
**World Anvil Username**: seanhagen

**World / Campaign / RPG Character / Manuscript Title**: Numenera North West

**Feature**: NPCs

**Related URLS**:
![text-layout-wrong](https://user-images.githubusercontent.com/444767/137394795-15ce8551-a6a5-41cf-a0e0-f8cc6c84f5c7.png)

Link: https://www.worldanvil.com/heroes/campaign/npc/ad5cdbc0-d03f-4d20-993b-4151ba333caa/edit

**Describe the Issue**
The text boxes for `Short bio` and `Secret notes` aren't displaying text properly. The layout is happening right-to-left instead of left-to-write, making it hard to write and edit text.

**To Reproduce**
1. Go to 'Campaign -> NPCs'
2. Click on 'Edit' for an existing NPC
3. Scroll down to 'Short bio'
4. Start typing in the text box
5. Text displays right-to-left

**Expected behavior**
Text displays properly.

**Comment by seanhagen** [comment]
Just saw the comment on the other bug I submitted ( #617 ), so I guess this will get handled at the same time?

Any previews or hints as to what the new NPC design will look like? Or ( more importantly ) should I wait to fill out my NPCs until this new design is done?

**Comment by iamromeo** [comment]
This layout will also be redesigned from the ground up.

**Comment by Kordishal** [comment]
There should be no problem with you starting to fill in your NPCs. The update might still be a bit off as it is quite a big one. The migration to the new system will happen automatically.
