### ISSUE TITLE
Presentation Search reloads after first result is loaded with different list since update

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#634]
**World Anvil Username**: SoulLink

**World / Campaign / RPG Character / Manuscript Title**: Codex

**Feature**: Presentation Search

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/WorldAnvilCodex

**Describe the Issue**
The presentation search loads two sets of results after each other. First it displays results based on title / tag search and then adds the content ones. Which often pushes the title matches out of the result set.

**To Reproduce**
1. Type "Guild" into search
2. See first it will load two results with Guild in title
3. After a short amount of time it will replace that result with 10 other results of which none have guild in the title.
4. Then it usually switches back to the short list.

**Expected behavior**
Should still sort title / tag results before content.

**Comment by iamromeo** [comment]
Requested feature not bug

**Comment by Kordishal** [comment]
Your implementation does not work though? This is terrible UX.

I can't select a thing based on content search. So either revert the change and have it work as before or fix it.
