### ISSUE TITLE
Problem with creating a new world

### ISSUE THREAD

**Issue by gn00me** [worldanvil/worldanvil-bug-tracker#635]
**World Anvil Username**: gn0me

**World / Campaign / RPG Character / Manuscript Title**: -

**Feature**: New World

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/world/new

**Describe the Issue**
A clear and concise description of what the issue is.
When I try to create a new world, I have an error message "You have no more world slots available :(". I've created a 2 worlds, but deleted one to create a new one, so I only have 1 world on a free account.
**To Reproduce**
1. Go to 'Worlds & Heroes'
2. Click on '+ New World'
3. See error 'You have no more world slots available :('

**Expected behavior**
Creation of the New World
**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Error 1](https://user-images.githubusercontent.com/3670722/137626813-38959458-ae00-4207-98dd-23abadd6e38f.JPG)
![Error 2](https://user-images.githubusercontent.com/3670722/137626818-7e267557-4eb5-4d29-aeb3-9027282bd571.JPG)

**Comment by iamromeo** [comment]
https://www.worldanvil.com/w/kodeks-artifex-gn0me 
and
https://www.worldanvil.com/w/lunae-lumen-gn0me

both public - you have 2 worlds 

This is not a bug

**Comment by Kordishal** [comment]
Though something is strange:

![image](https://user-images.githubusercontent.com/14262536/137719837-b5c7146f-10ce-4d60-a0e1-c048256b9fd7.png)

The second world does not show up in the profile or the selection menu above.

There must have gone something wrong during the deletion.

**Comment by gn00me** [comment]
Yup, cause I've tried to delete Lunae Lumen world...
