### ISSUE TITLE
Manuscript tags - dark mode

### ISSUE THREAD

**Issue by KajetanWrites** [worldanvil/worldanvil-bug-tracker#64]
**World Anvil Username**: KajetanWrites

**Feature**: Manuscripts

**Describe the Issue**
Manuscript tags seen in the community section dedicated to manuscripts are unreadable in dark mode.

**To Reproduce**

**Expected behavior**
Tags readable

**Comment by Kordishal** [comment]
Can you be a bit more specific which page you mean? And make a screenshot?

**Comment by KajetanWrites** [comment]
![bug wa](https://user-images.githubusercontent.com/80585282/111063450-cd642380-84ae-11eb-929f-a6d580de2348.png)
This is the problem

**Comment by Kordishal** [comment]
Same problem with the labels used inside of the manuscripts.

![image](https://user-images.githubusercontent.com/14262536/111064289-714fce00-84b3-11eb-848e-cc2fad1e0cbd.png)

![image](https://user-images.githubusercontent.com/14262536/111064313-947a7d80-84b3-11eb-9e29-372363a3fd9d.png)
