### ISSUE TITLE
Delete confirmation cancel does not prevent delete of note on storyteller screen

### ISSUE THREAD

**Issue by ianneiriksson** [worldanvil/worldanvil-bug-tracker#647]
**World Anvil Username**:Ian Eiriksson

**World / Campaign / RPG Character / Manuscript Title**:Heroes Storyteller Screen Notebook

**Feature**: Delete Page

**Related URLS** (To public & visible pages add screenshots otherwise): N/A?

**Describe the Issue**
I accidentally hit the delete page option on my notebook, and hit cancel to prevent deleting the page in my notebook, but it deleted it anyway.

**To Reproduce**
1. Go to a storyteller screen and have open a page with any amount of information on it.
2. Click on delete page
2. Click on cancel on the confirmation

**Expected behavior**
I expect when cancelling to delete a page, that I can keep my page.

**Screenshots**
![image](https://user-images.githubusercontent.com/82564126/138926313-38ec348f-ef03-4a08-9abb-da94cdcc559b.png)

**Comment by iamromeo** [comment]
This will be addressed with the new DSTS interface.
