### ISSUE TITLE
Manuscripts Daily Word Count has Stopped

### ISSUE THREAD

**Issue by Gillymaya** [worldanvil/worldanvil-bug-tracker#651]
**World Anvil Username**:
@gillymaya

**World / Campaign / RPG Character / Manuscript Title**:

World: Astaeria
Manuscript: The Wardens of Ethera

**Feature**: 

Manuscripts: Day to day status of your manuscript

**Related URLS** (To public & visible pages add screenshots otherwise):
N/A

**Describe the Issue**

The daily word count report stopped updating for me on October 3rd

**To Reproduce**

**Expected behavior**
Word count for the manuscript as a whole should update daily. As I have been writing a fair bit I should be able to see this reflected.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Screenshot_20211028-192651_Chrome](https://user-images.githubusercontent.com/93345632/139314468-b8ca0f7c-c58c-4acc-a4fa-7354f25bb923.jpg)

Thanks :)

**Comment by iamromeo** [comment]
I am really sorry but I cannot replicate this - is there any changes you have done to your manuscript we should be aware of?

**Comment by Gillymaya** [comment]
No problem, thanks for looking into it, Dimitris. Unless I've done something strange accidentally, the only changes I've made are renaming my labels. Other than that, my settings have remained default.

**Comment by Gillymaya** [comment]
I've just gone back into my manuscript, and it appears the situation is now resolved as I have an updated word count for today. Hooray! Not sure what you did, but thank you so much! 

Fixed just in time for NaNoWriMo :D

![Stats](https://user-images.githubusercontent.com/93345632/139538797-8ff111fa-8de9-4485-8d3a-78e22fceec37.PNG)

**Comment by Kordishal** [comment]
I'll close the issue for now. If the issue re-appears please comment here so we can investigate further. As far as I am aware Dimitris did not change anything in the manuscripts.
