### ISSUE TITLE
Export Failure: "Job failed: pywaclient.exceptions.InternalServerException"

### ISSUE THREAD

**Issue by CyberXZT** [worldanvil/worldanvil-bug-tracker#653]
**World Anvil Username**:
CyberXZT

**World / Campaign / RPG Character / Manuscript Title**:
Firebird

**Feature**: 
Export Worlds & Manuscripts

**Related URLS** (To public & visible pages add screenshots otherwise):
https://toolbox.soullink.docker.worldanvil.com/backup/form

**Describe the Issue**
Export fails with:
`Job failed: pywaclient.exceptions.InternalServerException: article/01e30d8c-1a1e-443e-9448-1fa1ba92600e`
The article in question is a blank 'stub' article with seemingly nothing that it should be hitching on.

**To Reproduce**
1. Go to 'https://toolbox.soullink.docker.worldanvil.com/backup/form'
2. Fill in address and token.
3. Hit start, Wait.

**Expected behavior**
Export completes and is sent to my email.

**Screenshots**
![image](https://user-images.githubusercontent.com/2793530/139430993-4fc7c2b7-2fe3-49d0-a76b-727d2c982478.png)

**Comment by Kordishal** [comment]
Hi, this issue has been fixed. Can you confirm if you can export your world now?
