### ISSUE TITLE
Article formatting stripped on save

### ISSUE THREAD

**Issue by CMAlbrecht** [worldanvil/worldanvil-bug-tracker#657]
**Article formatting stripped on save**

Reported by: Draigsffau, a.k.a. CMAlbrecht re. Gaiaverse

More than half the time I save my work and then view it, I find that *all* of the formatting has been stripped from the text block.  Even a vignette as simple as:

[p]Keth is a spacer who plies the spacelanes between Bragarzin Station and Bo Fom Tri Spaceport.[/p]

[h2]Story[/h2]

[p]On the way back from Bo Fom Tri, the adventurers get a lot of gossip from Keth including several plot hooks.[/p]

Save, then view, and everything appears as simple paragraphs.  Go back to edit and all of the formatting has been stripped from the text.  This seems to be the case with all text entry areas, not just the vignette, i.e. sidebar, text areas provided by templates.

Add the formatting again, save, view; all is again simple paragraphs and on edit it is clear that the formatting has been stripped *again*.

As a new user, I found this behavior extremely frustrating.  I very nearly quit on my second day as a guild member, on the grounds that if something as simple as text formatting just didn't work the entire site was likely to be full of pitfalls and outright bugs.

**Operational Context:**

Creating a new article, usually using a template rather than a generic article, and using the basic (?) / legacy (?) text editor; the one that lets the user apply explicit BBCode tags within the text.  I've been a programmer for over 40 years, what can I say; I prefer to **see** my  code.

Although I didn't realize it at the time (because new user), my article editing had auto-save enabled so I was explicitly selecting the Save link, but it's likely auto-save was also occurring (sometimes, for some classes of changes, but we'll get to that).

**Steps to Reproduce:**

Order of operations is likely important to being able to reproduce this issue.  Some other orders to get to the same ultimate text have different results, and there's a terribly clunky workaround. (I'll get to that too, as it's likely a clue as to what is going wrong.)

My order of operations is, starting with an empty text entry area,
1. Type in all of the text to be displayed (no formatting tags, but with @mentions as appropriate (the @mentions don't seem to affect this particular issue, though), separating paragraphs with an empty line.
2. Highlight the first text paragraph, then select a formatting tag from the row of buttons immediately above.  The formatting tags are pre-pended and appended at the start and end of the paragraph.
3. Repeat step 2 for each remaining paragraph in succession.
4. Save.
5. View.

At this point, it can be observed that the formatting (particularly the H2 of the example text above) was not applied.

6. Select "Edit Character" (or "Edit Location", etc.).

At this point, it can be observed in the text entry area that all of the formatting tags have been stripped from the text.

**Expected Behavior:**  When viewed, all text is displayed with the assigned formatting.  When subsequently edited, the text display shows all of the assigned formatting tags.

**Actual Behavior:**  When viewed, all text is displayed as ordinary paragraphs.  When subsequently edited, the text display shows none of the assigned formatting tags.

**_Clunky workaround:_**  **AFTER** setting all formatting tags, go to the end of the last line of text and enter a carriage return, placing an empty line at the end of that section of text.  This triggers the auto-save (which was **not** triggered by format changes), and when the text is subsequently viewed, it has the assigned formatting.

**Guesses and Suppositions**

My guess is that what actually gets saved depends on change detection; that to make save operations more efficient, only text that is deemed to have been changed is actually saved.  My supposition, based on the behavior I've described, is that formatting changes are not detected as changes, so they neither trigger the auto-save feature nor allow the text block to be saved with the formatting when the article is explicitly saved.

**Impact of Deficiency:**

This is bad because changes made by users to present their work to advantage are obliterated without explanation.  It may also (as it nearly did me) dissuade new users from continuing to use World Anvil.

**Comment by iamromeo** [comment]
Hello @CMAlbrecht and welcome to the Guild. 

It is true that editors will require a key press to autosave or even for the save button to be able to capture its content. 
This is a known limitation for most editors. The simple change in workflow is to, as you did make a simple edit like a carriage return or space at the end when you are done. 

As a clarification, the above issue only presents on EUCLID now LEGACY. In Legacy, pressing the save button will save the changes. 

We are aware of this and considering our options. Thank you for reporting!
