### ISSUE TITLE
Map won't be deleted

### ISSUE THREAD

**Issue by JamiMcG** [worldanvil/worldanvil-bug-tracker#659]
**World Anvil Username**: Wrathetic

**World / Campaign / RPG Character / Manuscript Title**: Cuminia

**Feature**:  Attempting to delete faulty map

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/cuminia-wrathetic/map/0fd31045-94b7-406c-8de9-a8af6c9f6b81

**Describe the Issue**
My map was acting weird so I attempted to fix it by replacing the image. I got the error that I was over file size (can't remember the exact wording). I currently only have 4.1mb while I have the original map in the gallery. After attempting that my entire map dissapeared showing just the markers and my layered map on top of it (which was the exact same apart from territories drawn out) became grey.
I attempted to delete the map file and just reupload it but now I get a 404 error everytime I try and I have a floating blank box on my home screen. The map file is still in the dashboard.
A clear and concise description of what the issue is.

**To Reproduce**
1. Go to Maps
2. Click on The Map of Cuminia
3. Click on Map Settings
4. Click on Map Deletion
5. Confirm Map Deletion
4. See error (404)

**Expected behavior**
I expect my map file "The map of Cuminia" to be deleted and for the box to no longer be displayed on the world front page.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/80470346/139514329-f536c33b-b5f9-4429-8067-7aa25730ac50.png)
![image](https://user-images.githubusercontent.com/80470346/139514419-6484a092-5516-415a-8501-08a6656dd6c0.png)
![image](https://user-images.githubusercontent.com/80470346/139514495-c85948cf-ffd2-40e1-84bd-dcb5551b27f8.png)
![image](https://user-images.githubusercontent.com/80470346/139514442-551b4601-b223-4753-b6d7-fbe16a238e09.png)

Thanks very much for the help!
-Jamie

**Comment by iamromeo** [comment]
The I would very much like to test this on your account because it cannot be replicated using the process above. 

Please please change your password to a temporary one and send to hello@worldanvil.com
- Your username
- The new password

So I can have a look and see what is wrong.
