### ISSUE TITLE
Myth template: placeholder texts cut off

### ISSUE THREAD

**Issue by Tillerz** [worldanvil/worldanvil-bug-tracker#66]
On the Myth article template, many of the placeholder texts are cut off, "Make y" instead of "Make your choice".

![d25b40deb54ea3381edeca88e8cd9b40](https://user-images.githubusercontent.com/63370525/111065688-38b3f280-84bb-11eb-8815-b05902e35039.png)

**Comment by iamromeo** [comment]
This is a known issue with this library and cannot for the life of me find why it does it
