### ISSUE TITLE
Renaming Threads

### ISSUE THREAD

**Issue by graylion-wa** [worldanvil/worldanvil-bug-tracker#660]
**World Anvil Username**:

Graylion 

**World / Campaign / RPG Character / Manuscript Title**:

Creation 

**Feature**: 

Discussion Boards

**Describe the Issue**
A clear and concise description of what the issue is.

When a user of Discussion boards (not the World Owner) renames an existing thread (first post) the thread vanishes from the Thread Board for the user and the world owner. 

**To Reproduce**

- As a user (not the world owner) go [here](https://www.worldanvil.com/w/creation/board/test-public-forum) to create a thread.
- Copy the url so it can be reached later.
- Check that it appears on the Thread Board
- Edit the title of the thread and rename it
- Save
- Check the thread board it will no longer be visible.
- It may be reached with the url.
- And if the world owner edits the thread and saves it re-appears.
- The world doesn't have to change anything, just save.

Thank you

**Comment by iamromeo** [comment]
Who creates the thread?

**Comment by graylion-wa** [comment]
> Who creates the thread? 
> Who edits the thread? 

The user (not the world owner) creates the thread. 

The user (not the world owner) edits the thread title which makes it disappear.

**Comment by iamromeo** [comment]
Confirmed and fixed. This will be deployed later on today
