### ISSUE TITLE
World of Darkness 20th Anniversary – Subsystems

### ISSUE THREAD

**Issue by Rieliesza** [worldanvil/worldanvil-bug-tracker#661]
**Full Name (RPG SYSTEM)**:
    Vampire: The Masquerade 20th Anniversary Edition
    Werewolf: The Apocalypse 20th Anniversary Edition
    Mage: The Ascension 20th Anniversary Edition
    Wraith: The Oblivion 20th Anniversary Edition
    Changeling: The Dreaming 20th Anniversary Edition

**List Name** (Name under which it should be listed on World Anvil):
    Vampire: The Masquerade 20th Anniversary Edition
    Werewolf: The Apocalypse 20th Anniversary Edition
    Mage: The Ascension 20th Anniversary Edition
    Wraith: The Oblivion 20th Anniversary Edition
    Changeling: The Dreaming 20th Anniversary Edition

**World Anvil Username**:
Rieliesza

**Website**:
http://theonyxpath.com/world-of-darkness-20th-anniversary-sale/

**Logo Image Link**:

**Logo Usage Terms (URL)**:

**Comment by iamromeo** [comment]
Hey @Rieliesza I will not be adding the systems separately that is done on purpose so all sheets for the same system are together,.
