### ISSUE TITLE
Article rearrangement

### ISSUE THREAD

**Issue by MGatta** [worldanvil/worldanvil-bug-tracker#662]
**World Anvil Username**: MGatta

**Feature**: Articles & Categories

**Describe the Issue**
When arranging articles within a category, the view often jumps to the top of the window. It makes rearranging articles very difficult. According to SoulLink, this happens in particular when scrolling down.

**To Reproduce**
1. Go to Articles & Categories and a category that has a good amount of articles
2. Click on 'Arrange'
3. Scroll down to drag down the article

**Expected behavior**
For the window not to jump around and for users to be able to scroll if necessary.

**Comment by iamromeo** [comment]
Sadly not much we can do about this - this is a browser / too long list issue not a WA issue
