### ISSUE TITLE
Discussion boards: post gets lost after pinning.

### ISSUE THREAD

**Issue by Tillerz** [worldanvil/worldanvil-bug-tracker#664]
**World Anvil Username**
Tillerz

**World / Campaign / RPG Character / Manuscript Title**
https://www.worldanvil.com/w/sheet-creation

**Feature**
Discussion Boards

**Related URLS**
https://www.worldanvil.com/w/sheet-creation/thread/45f7659d-9570-4a60-8491-68a959112589/view

**Describe the Issue**
When editing an existing post to pin it, the post vanishes from the board after saving.

**To Reproduce**
1. Go to a board
2. Add a new thread and save it
3. Edit it again: set "pin" and save.
4. Reload the board view: thread is gone.

**Expected behavior**
Thread is not gone.

**NOTE 1**
When editing the threat again in the still open window after save, the PIN toggle is gone. When I save again now without pinning, the threat is visible again.

**NOTE 2**
I tried to also LOCK this post, doesn't work. If I go back and check, it doesn't show as LOCKED in the dropdown.

**Comment by graylion-wa** [comment]
I have also reproduced this. And to add a point.

The thread is created by the world owner. 

The thread is edited by the World Owner.
