### ISSUE TITLE
& gets replaced with &amp instead of &amp; and thus is breaking links in [url]

### ISSUE THREAD

**Issue by Tillerz** [worldanvil/worldanvil-bug-tracker#666]
**World Anvil Username**: Tillerz

**Feature**: BBCode and html-ification on save

**URL:** https://www.worldanvil.com/w/alana/map/8873e572-3211-4117-bdd4-72560402b992

**Describe the Issue**

I am trying to make prompt links in the pin description of a map.

`
An [url:https://www.worldanvil.com/world/article/new?type=item&content=test] object [/url] that has been passed through the generations in a family.
`

But the URL gets killed by WA replacing the & with &amp instead of the proper &amp;

**Comment by iamromeo** [comment]
I am **really** sorry but that replacement is there for a reason, namely so JS doesn't crush. I cannot fix this without breaking the map. 
This will be most probably fixed with Atlas but the current implementation makes it quire hard. 

Suggestion: use a URL shortener like so https://bit.ly/3bGdKey
