### ISSUE TITLE
Replying to posts in a followed thread provides notifications with no links nor identifying info

### ISSUE THREAD

**Issue by Stormbril** [worldanvil/worldanvil-bug-tracker#668]
**World Anvil Username**: Stormbril

**World / Campaign / RPG Character / Manuscript Title**: Cathedris

**Feature**: Discussion Boards

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/cathedris-stormbril/thread/b040aad3-1de6-4259-8b99-af3c1f6f4645/view?latest=latest_id1

**Describe the Issue**
When **replying** to a post within a thread that is followed, the resulting notification contains no identifying information as to which thread it came from. It merely shows as "Thread has a new reply by Stormbril."

**To Reproduce**
1. Follow a thread
2. Have an existing post within the thread
3. Press the "reply" button on that post, and then reply to the post
4. The resulting notification will contain no links to initial thread, nor identification for the thread

**Expected behavior**
It should show "Thread 'Prayers to the God-husks' (link) has a new reply by Stormbril' in the notifications

**Screenshots**
![image](https://user-images.githubusercontent.com/45296671/140468000-e5b70356-eeb8-4ffa-ba39-305235089762.png)

**Comment by graylion-wa** [comment]
I have had a couple of these where I can't figure out what thread they have replied to (I have a lot of threads), where I have to go back and ask the player.

**Comment by graylion-wa** [comment]
As the amount of threads and posts grows, I have had to remove this reply button with css as it causes confusion without a notification link to go back to

/* HIDE REPLY BUTTON */

.discussion-board-post-actions a:first-of-type {
    display: none;
}

.discussion-board-main-thread-post .discussion-board-post-actions a:first-of-type {
    display: inline-block;
}

**Comment by iamromeo** [comment]
I think that I will have to disable the reply button for now - this is quite a complicated issue to fix -- Will be actioning this now
