### ISSUE TITLE
Auto-save copies HTML into page when the state-change buttons are pressed at the wrong moment

### ISSUE THREAD

**Issue by MGatta** [worldanvil/worldanvil-bug-tracker#669]
**World Anvil Username**: MGatta

**Feature**: Article editing

**Describe the Issue**
While cutting a section from an article (CTRL-X) and then saving or clicking the WIP->Done toggle, the autosave triggered and I got code instead of the vignette. This removes the window where you write text altogether.

Replacing a text box in the editor for bootstrap has happened before, see HBFR-5609

According to SoulLink: " if you press one of the three state buttons right as the auto-save fires it adds the code to the window."

**To Reproduce**
1. Go to legacy editor (or the legacy-like editor in Euclid by using the spellchecker for example)
2. Write text
3. Press a state button as the autosave goes

**Expected behavior**
For code not to replace the text window.

**Screenshots**
![image](https://user-images.githubusercontent.com/80196715/140603334-482fd5c8-48c7-417a-8237-651dcd14e19a.png)

**Comment by Kordishal** [comment]
This affects the legacy editor, source mode of the Plato editor and spellcheck mode of the Euclid editor. 

To reproduce, just write a bit of text and then spam the state buttons.

**Comment by iamromeo** [comment]
Cannot be reliably reproduced in order to be identified or fixed

**Comment by MGatta** [comment]
Kordishal can replicate it though.
