### ISSUE TITLE
Map Pin Position Inconsistent between viewed by reader & author of the map

### ISSUE THREAD

**Issue by JamesWoodwright** [worldanvil/worldanvil-bug-tracker#67]
**World Anvil Username**:
JamesWoodwright
**World / Campaign / RPG Character / Manuscript Title**:
Future's Seen (Birdencaster Article)
**Feature**: 
Maps
**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.
The Map its self works on its own inserting it in the sidebar makes the pin move to somewhere else
![in article](https://user-images.githubusercontent.com/80630797/111070484-e1694e80-84c9-11eb-8f34-76f77d13d941.png)
![Map on its own](https://user-images.githubusercontent.com/80630797/111070485-e201e500-84c9-11eb-8af1-03e8647d9309.png)

 makes the pin rest somewhere else. 
**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Hi, thank you for your report.

Unfortunately with the information given I cannot reproduce this issue. It does not generally happen on all maps. It would be helpful if you could send links to involved pages or isolate the conditions this happens under.

**Comment by JamesWoodwright** [comment]
i have some screenshots to show you. It's a shame you can't get it to do it
again. the top image is how it looks for me as the author and the bottom is
how it looks for the viewer is there anything else I could do to help.

[image: How it looks for the editor or author.png]
[image: What it should look like..png]

James Richard Anthony Woodwright
Unemployed
