### ISSUE TITLE
Related Session Reports Title Issue

### ISSUE THREAD

**Issue by oncomingshower** [worldanvil/worldanvil-bug-tracker#671]
**World Anvil Username**: 
OncomingShower

**World / Campaign / RPG Character / Manuscript Title**: 
Arrasgoth, A History

**Feature**: 
Linking session reports to characters

**Related URLS** (To public & visible pages add screenshots otherwise): 
https://www.worldanvil.com/w/arrasgoth-oncomingshower/a/emrys-ddraig-sy-n-ddu-person

**Describe the Issue**
I linked a session report to a character on my World Anvil. When looking at the character, the title seems to be a string of words rather than like the other titles. 

**To Reproduce**
1. Create a session report.
2. Choose a character to link the session report to in the drop down menu.
3. Look at the character's page and their information section.

**Expected behavior**
I expected when looking at the character page that it should say something like Linked Session Reports or Related Session Reports instead of a string of words.

**Comment by GorkamWorka** [comment]
It's indeed a bug on my part.

relatedPersons not relatePersons 

(the string is the translation string index key)

**Comment by GorkamWorka** [comment]
Fixed, Will be deploy on next cycle
