### ISSUE TITLE
World Credits Override showing world.worldCreditsOverride.placeholder

### ISSUE THREAD

**Issue by MJHeijster** [worldanvil/worldanvil-bug-tracker#672]
**World Anvil Username**:
MoonRaven
**World / Campaign / RPG Character / Manuscript Title**:
Irrelevant
**Feature**: 
World configuration
**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.
When going to world settings, configuration, World Credits Override has a placeholder of world.worldCreditsOverride.placeholder instead of a descriptive text.
**To Reproduce**
Login to world anvil
Open dashboard
Open world settings > configuration
If WORLD CREDITS OVERRIDE isn't filled in yet, the value is world.worldCreditsOverride.placeholder instead of something like "Your patreon username".

**Expected behavior**
A nice little text <3
**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![2021-11-08_21h41_28](https://user-images.githubusercontent.com/246678/140815773-f8fcf2c6-b959-4600-aa62-68c87f4551d8.png)

**Comment by GorkamWorka** [comment]
thx for the catch
Fixed will deploy soon
