### ISSUE TITLE
Character Name vs Title Posts

### ISSUE THREAD

**Issue by graylion-wa** [worldanvil/worldanvil-bug-tracker#673]
**World Anvil Username**:

Graylion

**World**:

Creation 

**Feature**: 

Discussion Boards Posts

**Related URLS**

[Post Link](https://www.worldanvil.com/w/creation/thread/74aea1ac-99f3-4997-929d-95fb1ccb7410/view)

**Describe the Issue**

When posting in a thread as a character with a title, the title overwrites the character name with the title.

**Expected behavior**
If the character title is to be displayed it should apend or be in addition to the character name.

**Screenshots**

![20211108_192740.jpg](https://user-images.githubusercontent.com/79761754/140839531-34fd4082-8049-401e-988b-a7aa82763995.jpg)

**Comment by iamromeo** [comment]
This cannot preproduced. the issue is not what it was reported. 

![image](https://user-images.githubusercontent.com/660175/140862277-187ac216-4f24-4f8c-9488-98c6cd163baa.png)
![image](https://user-images.githubusercontent.com/660175/140862533-b8dee97f-5588-4599-9e87-b86c4ea0d1df.png)

**Comment by graylion-wa** [comment]
OK renaming to Character Article Title vs Article Article Title

In this example you posted you added additional fields of given name and family name.

I did not use either of these fields

In the example above 

Character Article Title = Mr_Name_Two

Title = His_Title

If I post in the thread His_Title overwrites or replaces Mr_Name_Two

Thank you

**Comment by graylion-wa** [comment]
Thank you for the fix on this.
