### ISSUE TITLE
Error 404 When Doing Almost Anything

### ISSUE THREAD

**Issue by PresidentMystry** [worldanvil/worldanvil-bug-tracker#674]
**World Anvil Username**: PresidentMystry

**World / Campaign / RPG Character / Manuscript Title**: All of the above

**Feature**: Any

**Related URLS** (To public & visible pages add screenshots otherwise): Unsure

**Describe the Issue**
A clear and concise description of what the issue is.
The problem that I am having is that in the feature Homepage bar to the left, none of the features are available to click except for Worlds & Heroes. When I click on that one, nothing happens. Furthermore, when I try to edit my world, or create a new world, or do anything that has to do with my personal creations, I get an error 404 message on my screen and nothing changes. 

**To Reproduce**
1. Go to My Worlds
2. Click on whatever world I have (which is just one at the moment)
3. Click on the pencil button for editing Maps
4. See error 404

**Expected behavior**
I expected to be able to use the site. Especially considering I just paid for extra features with a subscription.

**Screenshots**
![image](https://user-images.githubusercontent.com/93960551/140853821-82dcd944-b851-4bd2-90c2-aafb06f68a0d.png)
![image](https://user-images.githubusercontent.com/93960551/140853928-6dfad433-d60d-4886-9b41-87388ff78800.png)
![image](https://user-images.githubusercontent.com/93960551/140854530-98307cd1-699d-413d-86ba-3365fddd0285.png)

**Comment by iamromeo** [comment]
Can you please
1. Go to Account Features (From the top right menu) https://www.worldanvil.com/dashboard/user/features and take a screenshot of which Features you have activated. 
2. Click on the homepage **Worlds**  and then Activate your world if it's not activated (let me know if it is)

**Comment by PresidentMystry** [comment]
![image](https://user-images.githubusercontent.com/93960551/140860842-de0d52d6-69c7-4640-bffa-0cf0fc3ab8e6.png)
![image](https://user-images.githubusercontent.com/93960551/140860917-f0ebe627-07a3-47b3-82a9-6cda50005bbf.png)
![image](https://user-images.githubusercontent.com/93960551/140860981-93e812b3-5c27-4e44-a1e5-dd95fbff5f2f.png)

**Comment by iamromeo** [comment]
Thank you for this, have you activated your world?

**Comment by PresidentMystry** [comment]
I just activated the world, and it seems to have fixed the problem for this world and the rest of the site. Thank you.

**Comment by iamromeo** [comment]
Glad we managed to resolve it!
