### ISSUE TITLE
Problem Using Mac with Worldanvil

### ISSUE THREAD

**Issue by scottstory** [worldanvil/worldanvil-bug-tracker#675]
**scottstory**:

**World / Campaign / RPG Character / Manuscript Title**:

**Navigation**: 

**https://www.worldanvil.com/w/aorlis-scott-story

**Beginning last week, when I use the navigation icon on my Worldanvil site on a Mac, the navigation bar does not open up but acts as a direct link. Navigation works fine on Android, Kindle, and Windows.**

**Access my world on a Mac**

**Screen shot of what it should look like**

**Screenshots**
![codex](https://user-images.githubusercontent.com/40002259/140933910-9cc1cf9d-b1d9-49d7-a00c-62f1f63d297f.jpg)

**Comment by iamromeo** [comment]
Hey Scott, I am sorry to say that this is not a Mac of Safari issue. World Anvil is being developed on a mac and these issues do not present. 

The chances are that this is a local issue - Have you tried opening it in Chrome or Firefox on your mac?

**Comment by scottstory** [comment]
You're a genius! It wasn't a Mac issue, it's a safari issue. I downloaded Chrome and the site works just great. Thanks--Scott

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 9, 2021 at 3:13 PM, Dimitris Romeo ***@***.***> wrote:   


Hey Scott, I am sorry to say that this is not a Mac of Safari issue. World Anvil is being developed on a mac and these issues do not present.

The chances are that this is a local issue - Have you tried opening it in Chrome or Firefox on your mac?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
