### ISSUE TITLE
Icons Not Centered.

### ISSUE THREAD

**Issue by Thandersen** [worldanvil/worldanvil-bug-tracker#676]
**Trolnir**:

**Danmark**:

**Timeline**: 

**https://www.worldanvil.com/w/dungeons-and-danish/t/eventyrernes-forening-timeline** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Displaced graphics in event icons.
Appears to be related to Base Font Size. 
In Screenshot base font size is set to 20.
Second example screenshot uses Base Font Size 16
Issue appears at Basic Font Sizes over 12.

**To Reproduce**
1. Set Base Font Size in Styling to >12.
2. Create Timeline
3. Create Events on Timeline
4. View timeline

**Expected behavior**
Icon graphics not centered in circle.

**Screenshots**
![Bug](https://user-images.githubusercontent.com/87699425/140953436-85a80c5a-37ce-4103-b83d-bd4686280a9e.png)
![Bug2](https://user-images.githubusercontent.com/87699425/140954050-4876538b-3741-4740-be6d-3b0a63a393d6.png)

**Comment by iamromeo** [comment]
it looks like that was a matter of a theme of CSS applied to that theme. I can see you have now changed your theme - but can you please let me know which theme was it that had the issue so I can fix it?

**Comment by Thandersen** [comment]
I was using the Dungeons & Dragons Theme.

I have since changed to the Elven Forest theme. Apparently, this theme will default to base font size regardless of what I set the base font size to in settings, so I couldn't see if the bug could be reproduced with this theme.
