### ISSUE TITLE
Ironsworn: Starforged System Request

### ISSUE THREAD

**Issue by frws25** [worldanvil/worldanvil-bug-tracker#677]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the request will not be considered.

**Full Name (RPG SYSTEM)**: Ironsworn: Starforged
**List Name** (Name under which it should be listed on World Anvil): Starforged
**World Anvil Username**: frws25

**Website**: https://starforged.absolutetabletop.com/

**Logo Image Link**:

**Logo Usage Terms (URL)**:

**Comment by iamromeo** [comment]
All done :)
