### ISSUE TITLE
Missing Article

### ISSUE THREAD

**Issue by Dakadak** [worldanvil/worldanvil-bug-tracker#678]
Brokes

Amatera- The Desert Wards

Cant find it

Had an article called The Desert Wars that was pretty lengthy by my standards. I haven't been able to work on my world in quite a while, I came back recently and noticed that the article is missing except for the title nothing else remains of all that work. I am not sure if I am in the right place to report this but i would like some help getting this article back. 

Go to world page
click on the desert wars tab
it empty

- want the article back. 

no screens shots available cus its no longer there.

**Comment by Kordishal** [comment]
Hi!

Do you mean this article: https://www.worldanvil.com/w/amatera-brokes/a/the-desert-war-militaryConflict ?

You have two articles with the same name. This one is empty: https://www.worldanvil.com/w/amatera-brokes/a/the-desert-wars-article
