### ISSUE TITLE
Shared account Upgrade issue

### ISSUE THREAD

**Issue by Sebastianos-Ionnides** [worldanvil/worldanvil-bug-tracker#679]
**World Anvil Username**:
Aelstyn
**World / Campaign / RPG Character / Manuscript Title**:
EvenTide in Albion
**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Hello Dimi, I hope you are well. 
This is my first shared world, im helping a vampire LARP build their world. They had journeyman account. I want them to have a GM account so I was going to go buy them a GM upgrade. and when I did it redirected me to my account status which said "IS" and I couldnt upgrade the shared account

**To Reproduce**
I went to the "Upgrade account" button and I was redirected to MY account status not the shared world account status. Not sure this is the behavior you want. We needed up going through Phoebe to fix it. 

**Expected behavior**
I expected it to give me the upgrade status options or at minimum redirect me to the owners account level and tell me I dont have the ability to pay for the upgrade based on my role in their world. or something like that

**Screenshots**
The attempt
![image](https://user-images.githubusercontent.com/94059525/141127015-c75a1c0f-2779-4622-889b-628cf784934b.png)

The redirect
![image](https://user-images.githubusercontent.com/94059525/141127486-be7fd1d6-ebd4-4b0a-abf5-230138fe7ccf.png)

**Comment by iamromeo** [comment]
Hey Sebastianos

Accounts on World Anvil are not shared, Worlds are. A world follows the features of their owner. The account of the co-owner is irrelevant regardless if they are a Freeman or a member of the inner sanctum. 

Not a bug :)

**Comment by Sebastianos-Ionnides** [comment]
ok. it wasnt a great user experience. I pointed it out. I understand
accounts are separate. Im working with a company (a LARP) that wants to use
WA, the world is associated to the owners account I got notification to
"upgrade a the account to get a feature" in that world and when I went to
it (I wanted to pay for the LARPs account to be a GM from Journeyman) I was
redirected to my IS account page and implied I had the ability and I didnt.
So I had to contact Phoebe and have her help. which causes support
overhead. It wasnt a good user experience.

anyway. pointed out a frustrating user experience. yours to do with how you
will

cheers and hope you are well
Sebas

**Comment by Kordishal** [comment]
So basically it would make sense for co-authors to not be prompted to upgrade on that world as that action would not actually result in unlocking the feature (and in case they are upgraded more they just can't).

I agree that this should be improved.

**Comment by Sebastianos-Ionnides** [comment]
its my first Co-Authoring,a nd I just asked the owner to make me a
co-owner.

Ive been in IS a long time so I forget at times what is what level for
features.

yeah either take it off the board or have it prompt to the owners world
subscription level or something. I mean. I was trying (and have just paid)
to have the journeyman world im working in be a grandmaster and what I was
trying to do was upgrade the world to a higher subscription. I would wager
you want that to be as easy as possible no matter who is paying for it.

What happened was I had to go through Phoebe and then buy a subscription
and have her apply it to that work, so I cant really "Gift" a subscription
easily through the interfarface

If I was writing a story for this it would be something like. the catch 22
is that im an IS member and have an expensive account, the LARP i'm helping
doesnt, even though worlds and accounts are independent objects they are
independent from a subscription level. there is always one top user that
the world default's its feature subscriptions to.

"as a Co-Author or Co-Owner of a world I would like to be able to upgrade a
subscription level and be prompted with payment details and have the
subscription applied to the actual world owner so that the world im working
on gets the subscription upgrade without me having to contact account
support"

anyway. just my feedback I hope all of you guys are doing well. nothing but
love to the WA team.


Cheers
Aelstyn/Sebas
