### ISSUE TITLE
Show ToolTip when hover on article link shows hidden items

### ISSUE THREAD

**Issue by A-R-Lyons** [worldanvil/worldanvil-bug-tracker#68]
**World Anvil Username**: AngusLyons

**World / Campaign / RPG Character / Manuscript Title**: Acoris

**Feature**: Tooltips

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/acoris-anguslyons/c/npc-s-category-1

Hover over Vetak Mirebolt - the will points section should be hidden

**Describe the Issue**
The tooltip on hover displays containers that should be hidden

**To Reproduce**
1. create a container within the general content section of the article
2. Hide that container with the visibility button in the world view of the article
3. Hover over a link to that article, the "hidden" content is still displayed

**Expected behavior**
The hidden containers should not display in the article preview/tooltip

**Comment by iamromeo** [comment]
This issue cannot be fixed that is why it suggested that the two features are not used in tandem.
