### ISSUE TITLE
Streaming page buttons not working (and typo)

### ISSUE THREAD

**Issue by MJHeijster** [worldanvil/worldanvil-bug-tracker#680]
**World Anvil Username**:
MoonRaven

**Feature**: 
Streaming page
**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/streaming
**Describe the Issue**
Both the packs are linked to dropbox folders instead of sharable links. Since I don't have those folders in my dropbox, I cannot access them. Please share them through the Copy link or share dialog.

Also, the WorldEmber 2021 pack says Downlaod instead of Download.

**To Reproduce**
Open https://www.worldanvil.com/streaming and try to download any of the packs while not being logged into the WorldAnvil dropbox account (if you are logged in, it'll probably work, but I can't test that)

**Expected behavior**
Click, download, joy.

**Comment by iamromeo** [comment]
Fixed and deployed - thank you for the heads up
