### ISSUE TITLE
Additional Rulers (Settlement, Building, Geographic Location) creates organization template

### ISSUE THREAD

**Issue by Amancham** [worldanvil/worldanvil-bug-tracker#681]
**World Anvil Username**: Amancham

**World / Campaign / RPG Character / Manuscript Title**: n/a 

**Feature**: Articles (Settlement/Geographic Location/Building Template)

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When creating a new article for "Additional Ruler" on the template, is creates an organization template instead of a character. This will result in an error and loss of changes since the save does not actually trigger despite saying it does.

**To Reproduce**
1. Go to any settlement/location or building article)
2. scroll down to "Additional Rulers/Owners" 
3. Click the "Create new article and link it" link
4. enter a name and hit "create & link" button 
5. find the last save time on the article at the top say "Last Saved undefined WA Time" 
6. hit save and go back to uncategorized articles 
7. find the newly created template to be organization instead of character 

**Expected behavior**
charakter being created AND if it doesn't, I would still expect the page to tell me that there was an error and not flash the green "article saved" flag, when it does not save.

**Comment by iamromeo** [comment]
Resolved deploying in the next 3 hours
