### ISSUE TITLE
Session Report "Related Characters" creates generic article instead of character

### ISSUE THREAD

**Issue by Amancham** [worldanvil/worldanvil-bug-tracker#682]
**World Anvil Username**: Amancham

**World / Campaign / RPG Character / Manuscript Title**: n/a

**Feature**: Aricle: RPG Session Report

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Using the "create article and link it" on the session report for related characters will create a generic article instead of a character article; Saving the article will fail after this has been used

**To Reproduce**
1. Go to any session report 
2. Scroll to "Related Characters" and click the "Create new article and link it" link
3. Enter any name and hit the button to create and link the article
4. Edit anything else, hit the save button for good measure, then leave the article 
5. Pull up uncategorized articles and find the newly created character to be a generic article
6. Check Session report to find any other changes, done after creating the character to link, to be gone.

**Expected behavior**
Character article created instead of generic Article. 
Error message to tell me that there is an issue and my changes are not being saved.

**Comment by iamromeo** [comment]
Resolved deploying in the next 3 hours
