### ISSUE TITLE
My world won't open

### ISSUE THREAD

**Issue by b57123m** [worldanvil/worldanvil-bug-tracker#683]
Bambam57:

**World / Campaign / RPG Character / Manuscript Title**:

World won't load: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
The title says it all, I accidentally clicked to load all character articles, which I don't usually do since there are a lot. But after that nothing will load, not even the home page from an incognito tab. Others have tried as well and can't open and my internet is working for other sites

**To Reproduce**
1. Go to http://www.worldanvil.com/w/galfin-bambam57

**Expected behavior**
It would open as normal

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Hi! I can confirm that accessing your world causes a timeout. My guess would be that you simply have too many articles in one article. There are technical limitations to how they are loaded.

I'd recommend to not have more than 10 articles in one article and at most 20. Any categories with more articles than that will start slowing down. Above 50 articles it will be start slowing down heavily and at some point it will simply fail. 

This means you need to start putting articles into categories. I had to restart my computer to be able to reload your world once.

**Comment by b57123m** [comment]
Thank you for the advice. That is the plan once I am able to work again. Dimi messaged me on discord last night and is running some tests while signed into my world

**Comment by b57123m** [comment]
So when this happened, I hadn't changed anything major with my maps but yesterday as I was removing different aspects of my homepage to try and get things working. Removing one of my maps from displaying on the homepage made it start loading again. It was probably an overall size issue but one specific map was enough to put it back into a working state.

**Comment by iamromeo** [comment]
This is being handled privately. The issue is somewhat resolved and currently working on making sure its mitigated.
