### ISSUE TITLE
Can't Join, Can't Leave, Can't Kick a player from a party, and it's causing a 404 I think.

### ISSUE THREAD

**Issue by TensonD** [worldanvil/worldanvil-bug-tracker#684]
**World Anvil Username**: 
Tenson Doragon

**World / Campaign / RPG Character / Manuscript Title**:
Empyrean Fields
Empyrean Field Dungeons & Dragons 5e Campaign
Avaline Astaseul

**Feature**: 
Party/Campaign Joined

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

**To Reproduce**

**Expected behavior**
They keep getting 404 errors in joining the campaign and I have no way to kick them out of the party and I think there's something messing up their ability to join the campaign because of when they made their character they tried to join the character but have it separate. Now I can't remove from the party and they just get 404 errors even though they've left the campaign.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window[!]

https://cdn.discordapp.com/attachments/793279998781161482/908605738727927828/unknown.png
https://cdn.discordapp.com/attachments/793279998781161482/908605834177699850/unknown.png

**Comment by Kordishal** [comment]
Hi this is likely the same issue as here: #175 

You can resolve it by deleting the party and then re-inviting the player.
