### ISSUE TITLE
Image files accessible despite setting to Private

### ISSUE THREAD

**Issue by hdewendt** [worldanvil/worldanvil-bug-tracker#686]
**World Anvil Username**: hdewendt

**World / Campaign / RPG Character / Manuscript Title**: Braythe: Shattered Realities

**Feature**: Image Upload: Setting image to Private

**Related URLS** (To public & visible pages add screenshots otherwise):

https://www.worldanvil.com/i/2803934
https://www.worldanvil.com/uploads/images/c49e04ef8dcc1e2be2f0450a3b4c3b0e.png

**Describe the Issue**
I've set an image to private, accessible only for a specific user group. The image page ("/i/...") is actually protected. But the file URL (".png") is still publicly accessible.

**To Reproduce**
1. Go to an image's settings in the backend. Set it to private, accessible only for a specific user group.
2. Click on "view" to open the image page.
3. Right click on the image and copy the URL
4. Log off from WA (or use a different browser where you're not logged in), open the image URL. It's fully accessible.

**Expected behavior**
When opening the image URL, it should be as protected as the image page, not accessible for anyone who isn't in the user groups that were granted access.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
I am sorry but that won't be possible - if someone has the url they will have access to the image.

**Comment by hdewendt** [comment]
> I am sorry but that won't be possible - if someone has the url they will have access to the image.
> 
> Just to clarify. In practice it is possible to protect those images but it is not a but that they are not. In order for someone to have access to the already obfuscated URL of an image they would need to have had access to the image prior to the image being set to private (which assumes that it was public in the first place)
> 
> Due to the above and that this is a quite a fringe case, and some more technical matters this will not be actioned at this point

Uh... I'm honestly pretty surprised about this reply. It is technically possible to protect images via server setting, shouldn't even be too hard, and many other image-hosting sites already have a variety of solutions for this.

URLs could always be leaked. This is, from my point of view, a pretty critical issue, setting products available to the public that are meant to be available only after purchase.

So, in my humble opinion, not a  "fringe" case, but a really serious problem that makes me consider to host my commercial images outside of World Anvil!

**Comment by hdewendt** [comment]
> I am sorry but that won't be possible - if someone has the url they will have access to the image.
> 
> Just to clarify. In practice it is possible to protect those images but it is not a but that they are not. In order for someone to have access to the already obfuscated URL of an image they would need to have had access to the image prior to the image being set to private (which assumes that it was public in the first place)
> 
> Due to the above and that this is a quite a fringe case, and some more technical matters this will not be actioned at this point

It is also a pretty common marketing technique to set maps and other images public for a short time, so yes, it is absolutely realistic that an image was public for some time, but isn't anymore after a marketing event.
