### ISSUE TITLE
Cant change default Sheet used for character creation

### ISSUE THREAD

**Issue by tkell234** [worldanvil/worldanvil-bug-tracker#687]
**World Anvil Username**: Tkel234

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
There is no way to change the default character sheet used for new characters in dashboard
EX: Go to dashboard and over the statblock and create a new character. Its always the regular d&d5e. I would like to create them with the d&d5e2020 sheet because I like the layout better. I can do this in the statblock area with the dropdown but there is no way to change what my campaign thinks is the default so that the dashboard options recognize it.

This has to be a bug or overlooked? worldanvil has a bazillion settings

**Comment by iamromeo** [comment]
oh hmm ok that is a forgotten hardcoded link, I will update to the 2020 sheet. :)
