### ISSUE TITLE
Table isn't loading properly

### ISSUE THREAD

**Issue by hecl3** [worldanvil/worldanvil-bug-tracker#688]
**penguintiefling3**:

**Barovia**:

**Add NPC**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When I click on "Add NPC" the table is shifted towards the right and offscreen. 

**To Reproduce**
1. Go to '[...](https://www.worldanvil.com/heroes/campaign/character/list/non?type=npc)'
2. Click on 'Create a New Supporting Cast Member (NPC)'
3. See error

**Expected behavior**
The form should display as a table in descending order.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/94264746/141663660-6029988b-e4b2-4af8-b287-2e9aaa761b89.png)

**Comment by Kordishal** [comment]
This is not something that happens in general.

Below is how it looks like when clicking `Create a New Supporting Cast Member (NPC)`
![image](https://user-images.githubusercontent.com/14262536/141675773-c7341e3f-76ca-4c4e-a44a-30b3237f317c.png)

Have you tried reloading this page with CTRL+F5? What browser are you using? Do you have an active campaign? Any other thing you did before that happened? Does it always look like that?

**Comment by hecl3** [comment]
Hello,

I tried CTRL + F5 but all it did was zoom out on my screen. I primarily use Google Chrome, but I just tried it in Firefox and I had no issues with that. I don't have an active campaign currently, and I can't think of what could have caused the issue. Even closing and restarting my computer doesn't seem to have an effect.

**Comment by Kordishal** [comment]
Can you try accessing the page with a private window in Chrome? Log in and then navigate there and see if that works.

**Comment by iamromeo** [comment]
No update from the OP for the last 4 days
