### ISSUE TITLE
Typo in writers landing page

### ISSUE THREAD

**Issue by OndoAlvelle** [worldanvil/worldanvil-bug-tracker#689]
**World Anvil Username**: Ondo

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/author

**Describe the Issue**
The "Write your novel" and "Publish & Monetize your way" taglines have two dots instead of one.

**Expected behavior**
It should be either one or three. I'd say one, from looking at the other landing pages.

**Comment by iamromeo** [comment]
fixed - will deploy later on
