### ISSUE TITLE
religion article

### ISSUE THREAD

**Issue by Ham-Dragon** [worldanvil/worldanvil-bug-tracker#690]
**Ham Dragon**:

**EARTH-65 (NAGATOSUKE & KUROMARU) (TRI-WORLDS) **:

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
i go to the dashboard, click on religion to make a religion and it send me to the page to create an organization, i copied the link, and tried to open it in new tab, but nothing worked.

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Religion'
3. See error

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Hello @Ham-Dragon if you read the description you will read that Religions are organizations - this is not a bug
