### ISSUE TITLE
BBCode search performance problems

### ISSUE THREAD

**Issue by Alarich** [worldanvil/worldanvil-bug-tracker#691]
**World Anvil Username**: Alarich

**Feature**: Increase the performance of BBCode @ search by introducing a debounce mechanism

**Describe the Issue**
When using autocomplete, it's very common to use a debounce method to trigger a timeout that will stop the execution of a request for some milliseconds. This is beneficial in cases where user input is expected, like any search with autocomplete. 

What usually happens is that a user writes a long word that describes what they seek and the system will attempt to search each variation of what the user wrote. Now, if there was a 100 millisecond delay between triggering the request, we could wait for the user to add another character, thereby saving multiple requests and making the user experience better, quite often.

A simple guide on debounce: https://www.freecodecamp.org/news/javascript-debounce-example/

Now, perhaps this is meant to be working in such a manner, but I'm going to hazard a guess that the feature is becoming less usable over time due to the amount of articles that has to be searched through. 

**To Reproduce**
1. Have a lot of articles
2. Use bbcode @ search and start typing
3. See every character you type make a separate query to the server and then wait for them all to finish to finally get what you want.

**Expected behavior**
Only search the final-ish version of what the user intends to type. 

**Screenshots**
The current behaviour when I search for `@morning`:
![image](https://user-images.githubusercontent.com/5496089/142079556-f7c945e3-ce77-454c-ade0-038a210858ca.png)

I will say, this is _incredibly_ noticeable during times of lag, as you can see from the loading times. It is not a matter of my internet, there was supposedly some sort of [stability test](https://discord.com/channels/348060277989965844/378865780768374784/910252505416478780) running around that time, so that might've been it. 

But even so, were it to use a normal debounce as is industry standard, perhaps the load on the server wouldn't be so bad and everyone benefits.

**Comment by iamromeo** [comment]
Last week there were serious networking issues which was the time that this issue was present. In reality there is no issue with the search, It was a conscious choice not to use debounce at this point. There are other locations that do.
