### ISSUE TITLE
Second world does not appear in Switch To... Menu

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#692]
**World Anvil Username**: SoulLink

**Feature**: Switch To... Menu

**Describe the Issue**
The second world in my menu list is missing since today. The world is not stored and still appears on the Global Dashboard My World tab. Hard refresh and private window did not resolve the issue, so it is not just a caching issue.

**Comment by iamromeo** [comment]
When did you create that world? The sidebar menu is now cached for 3600 seconds

**Comment by iamromeo** [comment]
Found the issue and fixed
