### ISSUE TITLE
Campaign / World / Account deletion issues

### ISSUE THREAD

**Issue by LaurasDilys** [worldanvil/worldanvil-bug-tracker#693]
**World Anvil Username**: lauras

**Feature**: Campaign / World / Account deletion

**Describe the Issue**
After having deleted my campaign and my world, I could still see them in the sidebar (see first picture). Then I had issues creating a new world (it did not appear in the sidebar and could not be accessed). I decided to delete the account and then create an account using the same information. Currently I've got one world and one campaign created, but none of them are visible in the sidebar (see second picture).

**To Reproduce**
1. Login using **World Anvil Username**: lauras and **User Password**: lauras
2. See the issue by navigating to the SWITCH TO... section

**Expected behavior**
Could you perhaps simply delete absolutely everything that's associated with my account, so that I could start from scratch?

**Screenshots**
![1 - deleted but visible](https://user-images.githubusercontent.com/77634444/142296809-a4718710-1293-4737-8b09-46cb3a163bae.png)
![2 - no world, no campaign](https://user-images.githubusercontent.com/77634444/142296822-b80dab7b-1d5f-48c9-b664-aaa8f7cbc47c.png)

**Comment by iamromeo** [comment]
Hello there :) The switcher is refreshed more or less every hour. This was implemented yesterday, I will lower the time but this is not a bug, it was made to speed up loading of pages. 

You can always access your worlds from the dashboard which is always refreshed. 


FYI: Creating a second account is against Tos
