### ISSUE TITLE
Comment Out function doesn't work

### ISSUE THREAD

**Issue by reymasx** [worldanvil/worldanvil-bug-tracker#694]
**World Anvil Username**: reymas

**World / Campaign / RPG Character / Manuscript Title**:  Article

**Feature**:  Comment Out

**Related URLS** (To public & visible pages add screenshots otherwise): 
https://www.worldanvil.com/w/nexia-reymas/a/pc-organization-organization

**Describe the Issue**
From what I understand when editing text if I use the Comment Out option /*hidden text*/, noone apart from the editor may see the text, howevr when I go to incognito window and follow the link to the article I can still see it.

**To Reproduce**
1. Create an article
2. Add some text part of which should be commented out
3. Go to the public link for the article
4. The commented out text is visible to all users and non users

**Expected behavior**
The commented text should be visible only to the editor

**Screenshots**
![image](https://user-images.githubusercontent.com/94543578/142374993-85ae4076-9cdb-4cb9-948e-9ef05ca1e28d.png)

**Comment by iamromeo** [comment]
This function is not available to free members :) this is not a bug

**Comment by reymasx** [comment]
I see, I read about the secrets but didn't realise this was the same, thanks!
