### ISSUE TITLE
Featured Articles Not Showing

### ISSUE THREAD

**Issue by Heathertuesday** [worldanvil/worldanvil-bug-tracker#695]
**World Anvil Username**: Heathertuesday

**World / Campaign / RPG Character / Manuscript Title**: Avistrea

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/avistrea-heathertuesday (Home Page).
**Describe the Issue**
A clear and concise description of what the issue is: I have ticked the feature requirements for the article I want to feature in my homepage but suddenly from about 3 days ago it stops showing up 

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Send to troubleshoot](https://user-images.githubusercontent.com/94653156/142510551-73902cf7-03c2-457e-bf2e-2eb095ef0a8f.png)

**Comment by iamromeo** [comment]
Hello Heather, Featured and Recent articles are currently disabled (for the last 48 hours) and will be returning soon :) 
Keep an eye on the development-changelog channel on our discord if you want to be updated :)
