### ISSUE TITLE
Save changes button not saving on articles

### ISSUE THREAD

**Issue by SyntaxChick** [worldanvil/worldanvil-bug-tracker#696]
**World Anvil Username**: SyntaxChick

**World / Campaign / RPG Character / Manuscript Title**: Estia

**Feature**: Article Editor

**Describe the Issue**
Manually clicking the save changes button does not seem to work despite giving the confirmation. Auto-save does still work though so a bit weird to reproduce.

**To Reproduce**
1. Open an article editor
2. Hit the [br] tag BUTTON (adding something without triggering the auto-save)
3. Click save changes
4. Refresh the page, added content is missing. 

Work around is to just manually type in text as it triggers the auto-save, and that seems to work fine.

**Expected behavior**
It should save the changes :)

**Comment by iamromeo** [comment]
Hello there :) The Save button only saves if there are typed changes since the last autosave :) 
It is honestly not needed at all. it's there as a safety reinforcement

**Comment by SyntaxChick** [comment]
Hm. Okay, although using the buttons on the editor do not seem to count as typed changes, so if I'm going back through and adding/adjusting bbcode it doesn't always save unless I remember type in some random text and remove it.

**Comment by Kordishal** [comment]
you can press any kind of key on the keyboard to trigger a save. It does not have to be something that actually writes something

**Comment by SyntaxChick** [comment]
@Kordishal Gotcha. Should it be a suggestion/request then that the buttons of the editor also trigger the auto-save?

**Comment by Kordishal** [comment]
I guess you can try. Don't see any attempts to have that added before.
