### ISSUE TITLE
Incorrect Celestial Phase

### ISSUE THREAD

**Issue by PhoenixInanis** [worldanvil/worldanvil-bug-tracker#697]
**World Anvil Username**:
Phoenix Inanis

**World / Campaign / RPG Character / Manuscript Title**:
Transformers Deception

**Feature**: 
Calendars

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/transformers-deception-phoenix-inanis/a/calendars-26-time-article

**Describe the Issue**
Celestial phase is not registering correct phase

**To Reproduce**
1. Scroll down to Cybertronian Calendar
2. Click on celestial icons
3. See error

**Expected behavior**
Celestial phase registers correct phase

**Screenshots**
![celestial error](https://user-images.githubusercontent.com/89389931/142665228-aa48d118-9d34-4fea-a2ec-0949ee194610.png)

**Comment by jonaswaeber** [comment]
This is a known issue with the calendar. As that is currently not worked on it will unfortunately not be addressed currently. 

The issue with it are tracked here: https://github.com/worldanvil/wa-calendar-issue-tracker/issues

I believe there is a potential temporary solution with CSS in one of those tickets.
