### ISSUE TITLE
Bug - Featured Articles not appearing

### ISSUE THREAD

**Issue by QuintusAgrippa** [worldanvil/worldanvil-bug-tracker#698]
**World Anvil Username**:
Agrippa
**World / Campaign / RPG Character / Manuscript Title**:
Mestynya Hundred
**Feature**: 
Feature articles missing
**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/mestynya-hundred-agrippa
**Describe the Issue**
A clear and concise description of what the issue is.
I moved the site from private to public and the featured articles disappeared from the front page.
**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
The Features and Recent articles interface are currently disabled and undergoing an upgrade :) 
Please refer to #dev-changelog on our discord to stay up to date! :)
