### ISSUE TITLE
Setting cell width in an article table is removed if article is saved

### ISSUE THREAD

**Issue by JohanFalt** [worldanvil/worldanvil-bug-tracker#699]
**World Anvil Username**: johanfk

**World / Campaign / RPG Character / Manuscript Title**: Should be any but I discovered it in my world Sektor X.

**Feature**: Set cell widths in article tables.

**Describe the Issue**
A clear and concise description of what the issue is.

Today I found a irritating bug.

The bug is that if you have created a table in an article and then you set a width on the cells. Then as you save the article and views it, the widths you have set works. But if you then go to edit it and then saves it again all widths is removed immediately.

The feature is described at: https://www.worldanvil.com/w/WorldAnvilCodex/a/bbcode#tables

**To Reproduce**

1. Create an Article, add a table example:

[table]
[tr]
[th:20]Weapon[/th]
[th:15]Skill[/th]
[th:15]Range[/th]
[th:5]Damage[/th]
[th:5]Crit[/th]
[th:5]Enc.[/th]
[th:5]Tech Level[/th]
[th:30]Notes[/th]
[/tr]
[tr]
[td]Handgun[/td]
[td]Ranged[/td]
[td]Short[/td]
[td]1[/td]
[td]1[/td]
[td]1[/td]
[td]1[/td]
[td][/td]
[/tr]
[/table]

2. Save Article

3. View Article

4. Edit Article

5. Save Article

6. View Article

7. Width settings has been removed.

Adding the same settings in all rows has no additional effect.

**Expected behavior**

That the cell widths should remain.

**Comment by Kordishal** [comment]
This is not a bug, but a lack of feature. That editor cleanses unknown BBCode and removes it. To use this newer features it is necessary to switch to the Euclid editor. Check this guide to see the differences.

https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors

The Plato editor will be updated at some point in the future to fix the existing issues and expand the supported BBCodes.
