### ISSUE TITLE
rgba in statblock css is filtered incorrectly

### ISSUE THREAD

**Issue by Imper1um** [worldanvil/worldanvil-bug-tracker#7]
**World Anvil Username**: imper1um

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: statblocks

**Describe the bug**
When you try to insert an rgba value, the system replaces the second, third and fourth value with a .template-<name> <value> which disrupts the color and makes it not display.

**To Reproduce**
1. Go to Statblocks
2. Create a new statblock
3. Enter in whatever.
4. Go to display mode and go to CSS Edit.
5. Try to enter in a css for background with rgba.
6. Save.
7. Create a statblock with the specific statblock created and click View Statblock.
8. Notice the background is having an issue. Open up DevTools for the browser and locate the CSS. Notice the replacements.

**Expected behavior**
Don't replace things in rgba in CSS.

**Screenshots**
![TemplateCSS](https://user-images.githubusercontent.com/49252077/109404595-a39af080-7935-11eb-8356-946c08b5ff15.png)

**Comment by Kordishal** [comment]
This is not considered a bug. You are not allowed to use commas in statblock CSS. 

Use hex values instead.

**Comment by Imper1um** [comment]
@Kordishal I believe you are incorrect on assuming a comma cannot be used in CSS. I believe this is caused by an overzealous use of making that a comma is *always* replaced by a , .template structure, which causes RGBA to be completely be unable to be used, meaning that opacity values in colors cannot be used (opacity in css applies to the entire element, whereas if you use an rgba() value, you can just adjust the color of a background color).

More info on RGBA is here: https://www.w3schools.com/cssref/func_rgba.asp

**Comment by Kordishal** [comment]
This is a limitation imposed by World Anvil. Obviously, CSS in general allows for the use of commas. 

You can use opacity just as well with hex values. Simply add an additional two digits to the value. So this restriction does not prevent the use of opacity at all.

https://www.digitalocean.com/community/tutorials/css-hex-code-colors-alpha-values
