### ISSUE TITLE
Long world names and discussion boards button

### ISSUE THREAD

**Issue by KajetanWrites** [worldanvil/worldanvil-bug-tracker#704]
**World Anvil Username**: KajetanWrites

**World**: Institute of Extradimenisonal Anthropology

**Feature**: Discussion Boards

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
With long world names the text on the discussion boards button on the world homepage goes beyond the button making the page not as nice as it could look

**Screenshots**
![1](https://user-images.githubusercontent.com/80585282/142763511-ddf128b9-1b7a-419c-8dcb-cce98bbdaf93.png)
!

**Comment by iamromeo** [comment]
This is not a bug and there is no fix for it apart from modifying your CSS
