### ISSUE TITLE
Ethnicity "Major Organisations" section currently displaying keys

### ISSUE THREAD

**Issue by Hanhula** [worldanvil/worldanvil-bug-tracker#706]
**World Anvil Username**: Hanhula

**World / Campaign / RPG Character / Manuscript Title**: Istralar

**Feature**: Article display

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/istralar-hanhula/a/snow-elf-article
https://www.worldanvil.com/w/istralar-hanhula/a/drastic-reformers-article

**Describe the Issue**
A clear and concise description of what the issue is.

**To Reproduce**
1. Create an Ethnicity article
2. Navigate to the Connections & Relations tab
3. Scroll down to Major Organisations
4. Enter some information in the box, ensure it's saved
5. Go to view the published article
6. Witness error on Major Organisations header displaying ethnicity.major.organizations instead of Major Organisations

**Expected behavior**
Expected "Major Organisations" to display as a header instead

**Comment by iamromeo** [comment]
Fixed - deploying as we speak - thank you for the heads up :)
