### ISSUE TITLE
Updating challenge page after the challenge is over

### ISSUE THREAD

**Issue by MGatta** [worldanvil/worldanvil-bug-tracker#707]
**World Anvil Username**: MGatta

**Feature**: Challenge's page

**Related URLS**: https://www.worldanvil.com/community/challenge/worldember-2020/homepage/MGatta

**Describe the Issue**
The World Ember page has continued to count wordcount and article number (?) even though the competition is over. As a result, my WE 2020 page (for example) thinks I never made it to 10 k. In reality, I got around 15 to 18k last year (roughly; well above 10 k but not enough to get to 25 k badge).

For others, it may show a much greater word count than they initially had if they continued working on the articles.

**To Reproduce**
1. Go to a world ember page
2. See differences between the "original" wordcount and the new wordcount

**Expected behavior**
For challenge pages to be static after the competition finishes.

World ember page, for example, shows the article block plus word count and the number of likes. Word count and number of likes should be frozen (on the challenge page) after the competition is over, to appropriately reflect what we did during the competition.

**Screenshots**
![image](https://user-images.githubusercontent.com/80196715/142827185-3ccb39b7-4da7-4db9-ae72-e6de232df166.png)

**Comment by MGatta** [comment]
I should clarify I understand this may be too late to do retrospectively for WE 2020, but ideally, a static page would be used for WE 2021 so that this does not happen in the future.

**Comment by iamromeo** [comment]
That will not be addressed at this stage. due to lack of manpower vs importance.
