### ISSUE TITLE
Ethnicity "Culture & Cultural Heritage" section currently displaying keys

### ISSUE THREAD

**Issue by theDinkus** [worldanvil/worldanvil-bug-tracker#709]
**World Anvil Username**: Dinkus

**World / Campaign / RPG Character / Manuscript Title**: Draeva

**Feature**: Article Display

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/raghido-dinkus/a/draeva-ethnicity
**Describe the Issue**
"Culture & Cultural Heritage" text field's header shows as keys "ethnicity.culture.cultural.heritage"

**To Reproduce**

1. Create an Ethnicity article
2. Navigate to the "Customs" tab
3. Scroll down to "Culture & Cultural Heritage"
4. Enter some information in the box, ensure it's saved
5. Go to view the published article
6. Witness error on "Culture & Cultural Heritage" header displaying "ethnicity.culture.cultural.heritage" instead of Major Organisations

**Expected behavior**
Header should display "Culture & Cultural Heritage"

**Related Issue**
See [706 (Closed) ](https://github.com/worldanvil/worldanvil-bug-tracker/issues/706)

**Comment by iamromeo** [comment]
Fixed and being deployed within the next 30 minutes
