### ISSUE TITLE
Campaign Homepage: Foundry Link only shows up when roll20 link is set as well

### ISSUE THREAD

**Issue by Satrium** [worldanvil/worldanvil-bug-tracker#710]
**World Anvil Username**: Satrium

**World / Campaign / RPG Character / Manuscript Title**: Call of the Deep

**Feature**: Campaign Page

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Filling the Foundry VTT field in the campaign settings does not show up on the view side for players. It only shows up when the Roll20 fields is filled as well.

**To Reproduce**
1. Go to Edit a campaign 'https://www.worldanvil.com/heroes/campaign/settings'
2. Add a URL into the field  'VTT Board URL (Foundry VTT)'
3. Head over to the public view page of the same campaign
4. See that the link to foundry is not showing up
5. Head back to the Campaign Edit page
6. Add a URL into the field  'VTT Board URL (Roll 20)'
7. Head back to the public view page and see that both links are now showing up

**Expected behavior**
The link to Foundry VTT should show up, even when the Roll20 link is not set.

**Screenshots**
_Only foundry link set_
![image](https://user-images.githubusercontent.com/4740623/143065541-0d8df0d2-361b-45b6-b4ad-ea2b9b41e53d.png)
_Only roll20 link set_
![image](https://user-images.githubusercontent.com/4740623/143065903-5c2603e7-a2de-446c-8883-645d6c66a2fa.png)
_Both links set_
![image](https://user-images.githubusercontent.com/4740623/143066257-ec08c11e-d16e-4907-938e-6ba558ac4228.png)

**Comment by iamromeo** [comment]
Fixed will be deployed within the next 6 hours
