### ISSUE TITLE
Featured Articles will not be displayed on main page

### ISSUE THREAD

**Issue by Hasamura** [worldanvil/worldanvil-bug-tracker#711]
**World Anvil Username**: Jhekarn Hasamura

**World / Campaign / RPG Character / Manuscript Title**: coriolis---der-3te-horizont-jhekarn-hasamura

**Feature**: Articles set to "featured" should be displayed on main page but will not anymore.

**Related URLS** (To public & visible pages add screenshots otherwise):
Article set to "featured" but is not displayed
https://www.worldanvil.com/w/coriolis---der-3te-horizont-jhekarn-hasamura/a/eintrag-333A-die-geister-die-wir-riefen--report

**Describe the Issue**
Featured articles will no longer be displayed on main page. This stopped from one day to another but the main page design was not changed by me. 

**To Reproduce**
1. Set an article featured
2. Check if article is on main page under "featured" articles
3. Foud the bug
4. PS: If the featured block seems to be not avaiable - it was never disabled by me. 

**Expected behavior**
Featured articles will be displayed on main page (rotating with displaying 3 in total if there are more than 3)

![grafik](https://user-images.githubusercontent.com/94937392/143141139-08dd62db-79b7-49c2-b456-33561760c3c6.png)

**Comment by iamromeo** [comment]
The Features and Recent articles feature are currently disabled and will be returning within this week. :) 
This was announced on the development changelog. You can always find all minor and major changes happening by going on our discord under the **#dev-changelog** channel
