### ISSUE TITLE
Map sidebar tab does not switch when clicked when multiple articles are attached to a marker

### ISSUE THREAD

**Issue by Phaler** [worldanvil/worldanvil-bug-tracker#712]
**World Anvil Username**:
Phaler
**World / Campaign / RPG Character / Manuscript Title**:
Barovia
**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/barovia-phaler/map/66cf2807-c21e-45fe-b3ef-db88d419aa46
**Describe the Issue**
A clear and concise description of what the issue is.
When I link more articles to one pin marker on the map, and than click on it, I have all the articles displayed on the sidebar but I can't open them.
**To Reproduce**
Go to the link of the map and click on the grey village marker, on top of the left sidebar, where there are displayed all the linked articles, there is the "settlment" article, which is open, and the "species" article. I can't open the "species" article, when I click on it nothing happens.

**Expected behavior**
When I click "series" on the top of the left sidebar it should open the linked article.
**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window
<img width="809" alt="Cattura" src="https://user-images.githubusercontent.com/94977091/143265069-dc0b1e3f-e15d-4d13-aa32-4c23a824ef1d.PNG">

**Comment by iamromeo** [comment]
I am sorry but I cannot access this map, can you please make it public or give me access

**Comment by Phaler** [comment]
> I am sorry but I cannot access this map, can you please make it public or give me access

I'm so sorry, it should be public now.

**Comment by Phaler** [comment]
I'm so sorry it should be public now.

Il ven 26 nov 2021, 11:15 Dimitris Romeo Havlidis ***@***.***>
ha scritto:

**Comment by Kordishal** [comment]
The map pins are still private.

Here is a test map with the blue pin has all of the links: 

https://www.worldanvil.com/w/breaking-anvil-soullink/map/568e9560-7a2c-4c48-b990-5343306a151c

There is no link to the Historical Event or to the Category either I've noticed. And it is not possible to navigate to the organization or person.

**Comment by Phaler** [comment]
Ok now the map pins are no more private, but I don't understand why the
sidebar doesn't switch the articles even if I linked them to the pin marker.

Il giorno ven 26 nov 2021 alle ore 14:30 Jonas Waeber <
***@***.***> ha scritto:

**Comment by iamromeo** [comment]
Issue has been identified and I am exploring possible solutions and time to action

**Comment by Roneuron** [comment]
Please fix this.

**Comment by Kordishal** [comment]
Closing this as it is now reported on the new platform.

https://www.worldanvil.com/udan-tracker/6dfae24a-b804-4eef-97b6-dcdda88ea9b8/view
