### ISSUE TITLE
Secrets in metadata section do not display bbcode

### ISSUE THREAD

**Issue by MGatta** [worldanvil/worldanvil-bug-tracker#713]
**World Anvil Username**: MGatta

**Feature**: Secrets & metadata/secrets section at the bottom of an article

**Describe the Issue**
While secrets display bbcode within an article, they do not at their section at the bottom of an article.

**To Reproduce**
1. Create a secret with bbcode such as [u]XXXX[/u]
2. Embed it in an article
3. Scroll down to the bottom and click on secrets

**Expected behavior**
For the bbcode to also render on that bottom-of-page tab. For GMs, secrets can be a major way of introducing information to players, and it is important for them to look nice. It'd be nice if they look like that across the article.

**Screenshots**
![image](https://user-images.githubusercontent.com/80196715/143266496-095db401-2f9d-4ac3-9305-6dcf6664be4e.png)
![image](https://user-images.githubusercontent.com/80196715/143266518-0dbb0f45-7ecc-43ef-9bce-e4077872e807.png)

**Comment by iamromeo** [comment]
Hey Maria, I am really sorry but I cannot replicate this. I can see the issue in your screenshot but my tests do not replicate it. 
You will need to give me some more detail 

Is this BBcode on the TITLE of the secret? If this is the case, this is misuse of the feature not a bug.

**Comment by MGatta** [comment]
Hi! Yes, they are on the title. I did not realize that bbcode was not allowed there.

**Comment by iamromeo** [comment]
If the entry on the authoring side does not have a sidebar. it should not have BBcode on it :)
