### ISSUE TITLE
Subcontainer in Heroes are always displayed

### ISSUE THREAD

**Issue by Satrium** [worldanvil/worldanvil-bug-tracker#714]
**World Anvil Username**: Satrium (GM) and DropFire (Player)

**World / RPG Character**: Lothrea / Davis Reed

**Feature**: Hero Linked to World

**Related URLS** (To public & visible pages add screenshots otherwise):
- https://www.worldanvil.com/w/lothrea/a/davis-reed
- https://www.worldanvil.com/hero/19710b80-4f9c-49b6-b4fd-57c57990a8fe

**Describe the Issue**
Subcontainers do not work on the display side of Heroes. When using subcontainers in an article linked to a hero, the bbcode gets parsed but the text inside the subcontainers is visible to everyone, including logged out users.

**To Reproduce**
1. Invite a character to the world
2. Add a subcontainer to the article of that character in the world
3. Head over to the character's hero profile in an incognito window
4. See that the content within the subcontainer is shown

**Expected behavior**
The subcontainer should check the permissions of the user, the same way normal secrets do. Of course, the player owning the character will see the text inside the subcontainer in their editing view.

**Screenshots**
_**Worldowner Editor View**_
![image](https://user-images.githubusercontent.com/4740623/143291503-6d586124-22aa-4d91-8930-e7040ddb8f9b.png)

**_Player Editor View_**
![image](https://user-images.githubusercontent.com/4740623/143291593-34498954-8ee7-4792-abb1-9a15d3099cda.png)

**_Public hero profile_**
![image](https://user-images.githubusercontent.com/4740623/143291619-f25466b0-a07b-445e-aa9c-4cc76ad3a5fe.png)

**Comment by iamromeo** [comment]
Hmm, so, first this is not a bug. 
As it stands, the character does not BELONG to you so it does not have access to the feature or your world 
It is something that I will probably address in this update

Out of curiosity how do SECRETS work ? (yes I am asking you to check my system :P )

**Comment by iamromeo** [comment]
Confirmation, secrets do work as they should - I am not going to consider this a bug. but I will see if it's possible to make some magic ot make it work in the coming update

**Comment by iamromeo** [comment]
Ok .... well... I "fixed" it :P 
I will deploy today - but now subcontainers also work on heroes
