### ISSUE TITLE
Automatic save on articles and manuscipts does not operate when only formatting changes are applied. 

### ISSUE THREAD

**Issue by DMFW** [worldanvil/worldanvil-bug-tracker#715]
**World Anvil Username**: DMFW

**World / Campaign / RPG Character / Manuscript Title**: Not specific

**Feature**: Text editing on articles and manuscripts

**Related URLS** (To public & visible pages add screenshots otherwise): N/A

**Describe the Issue**
I've noticed that whenever I make a formatting change of any kind to an article **_and no other changes_**, the formatting change does not trigger the save operation. There is an easy work around which I normally remember to do. Changing any text character does trigger the save which picks up pending formatting previously applied, so I find myself deleting and re-adding the last full-stop, for example, after I've made some text bold, otherwise the bold directive is in danger of being lost. It's quite easy to forget to do this in the final stages of editing, and hence quite easy to lose formatting changes accidentally. It would be good if any change to an article or manuscript, whether it is in the text or in the formatting alone, would trigger the autosave.

**To Reproduce**
1. Open any existing article or manuscript section.
2. Apply some formatting instruction, e.g. making some text bold, or adding a horizontal line. Do not change anything else.
3. Note that the autosave does not happen when you move off the page. Reopen the article and the formatting has disappeared.
4. Repeat the above, but this time change any character in the text body after applying formatting. This time the document does save and the formatting is not lost.

**Expected behavior**
Before I got used to this behaviour I expected formatting changes to work the same way as changes to the body of the text and to trigger an automatic save.

**Screenshots**
N/A

**Comment by iamromeo** [comment]
I am really sorry but this won't be possible to be actioned. I understand the issue and we are already aware of it - it is not considered a bug, but a lack of functionality that we do intent to address on the upcoming update of the editors. 

May I suggest that simply adding a space/carriage return character after your changes will in fact save all them.
