### ISSUE TITLE
Co-Owner Lacks Way to Access World

### ISSUE THREAD

**Issue by gabartomeo** [worldanvil/worldanvil-bug-tracker#717]
**World Anvil Username**: estrellitadelmar

**World / Campaign / RPG Character / Manuscript Title**: Raqualis

**Feature**: Authors Management -> Adding a Co-Owner

**Describe the Issue**
I added another user, worldsonmobile, to be a co-owner of my world, Raqualis. While it correctly shows on my end that they have been added, it does not show on theirs that they have been added. Directly linking them to the world allows them access to it, but otherwise, they have no way to access this through their account's dashboard.

**To Reproduce**
1. Create a new world
2. Add a user to be co-owner of this world (before any articles are created or added)
3. Have the user check their list of worlds, see nothing there

**Expected behavior**
I expected this other user to receive a notification by e-mail and/or through WorldAnvil that they have been added as a co-owner to my world, and for them to be able to access this world through their dashboard.

**Comment by Kordishal** [comment]
There is no email or notification, but co-owned worlds can be accessed either via the sidebar activaten dropdown or via the global dashboard under the My Worlds tab.

![image](https://user-images.githubusercontent.com/14262536/143503805-a841c32f-864d-4cf2-bc3f-fb9d2fc29d0c.png)
![image](https://user-images.githubusercontent.com/14262536/143503827-209f6294-690e-49e3-9562-5f113c105f5a.png)

I cannot reproduce this, so can you confirm that they indeed do not see the world listed in these two locations?

**Comment by Hanhula** [comment]
Anecdotally from my own peering into their issue - [the coauthor doesn't seem to have the world they were added to listed on their profile, either](https://www.worldanvil.com/author/worldsonmobile). This is the second such case of this I've seen, with [this Reddit user](https://www.reddit.com/r/WorldAnvil/comments/r1c9bo/do_all_world_authors_need_paid_account/) being the other.

**Comment by iamromeo** [comment]
The menu on the left can take up ton 1 hour to update BUT the dashboard Worlds link updates instantaneously.

**Comment by gabartomeo** [comment]
worldsonmobile now has the world listed for them as of about 15 minutes ago, but it wasn't there prior.
