### ISSUE TITLE
Insufficient contrast of knowledge base text while using Villains theme.

### ISSUE THREAD

**Issue by stevelle** [worldanvil/worldanvil-bug-tracker#718]
**World Anvil Username**:
N/A

**World / Campaign / RPG Character / Manuscript Title**:
N/A

**Feature**: 
knowledge base

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/knowledge-base

**Describe the Issue**
When using a non-hero theme, the text appears in an unreadable color because there is not enough contrast between the text and the background.

**To Reproduce**
1. set your interface theme to Villains (Dark Grey)
2. visit the related url
3. try to read the knowledge base pages

**Expected behavior**
I'd expect an accessible text contrast level from the background.

**Screenshots**
<img width="1002" alt="Screen Shot 2021-11-25 at 10 17 05 PM" src="https://user-images.githubusercontent.com/539741/143535691-8caaca21-5c50-4702-b0b4-d8c1dea86ce9.png">

**Comment by MGatta** [comment]
This was reported [just five days ago](https://github.com/worldanvil/worldanvil-bug-tracker/issues/702#issue-1059312646) and closed because the system is not in use.

**Comment by iamromeo** [comment]
@MGatta @stevelle we actually decided to do a quick fix on this after your initial report - it will be live today
