### ISSUE TITLE
Some public eras are not showing in a timeline when viewed as a non-logged on user

### ISSUE THREAD

**Issue by DMFW** [worldanvil/worldanvil-bug-tracker#719]
**World Anvil Username**: DMFW

**World **: Bubble

**Feature**: Timeline Display

**Related URLS** : https://www.worldanvil.com/w/the-bubble-dmfw/t/galactic-history-timeline

**Describe the Issue**
I've noticed that some eras are not appearing on the main timeline (see link above) of my world if I visit the page without logging on. They DO appear correctly when I log on under my own account. In the above timeline, the very first era is missing and there are some others (including the second era). The world is public and these eras are also public (I have double checked that), so it's unclear to me why they aren't visible to everyone.

**To Reproduce**
1. Visit the above timeline whilst not logged on. The first entry shown is:-

THE LOST TIME
Between 100 million years BCE and 35 million years BCE

but it should be:-

THE EMPTY EPOCH
Earlier than 120 million years BCE

(and there is another era immediately after this, which is also missing)

Both these have negative date ranges with overridden descriptions but I am not sure if that is signficant as other eras with the same features are showing correctly.

2. The era state for the missing two eras is set to public.
3. I have at least two more examples, further down in the timeline.

**Expected behavior**
I expected to see the first two eras in the timeline when visiting the page as an anonymous user. I can't see any difference between the parts of the timeline that are going missing and the parts that appear to work correctly when visiting without logging in. When logged in, all looks correct. My first thought was that it was because the entries hadn't been made public, but they have and I can't see what else is wrong.

**_Possible explanation : I have just noticed that all the four eras that are not shown, happen to have no events within them. My hypothesis is that public eras with no events within them may not be showing up correctly unless the world user is logged on. But I am guessing...._** 

**Screenshots**
N/A

**Comment by iamromeo** [comment]
I cannot be certain about this but, if your era has no events IN it will not show. Do these eras have public events in them ?

**Comment by DMFW** [comment]
> I cannot be certain about this but, if your era has no events IN it will not show. Do these eras have public events in them ?

Thanks for your response. The missing eras **don't** have any events in them, something I didn't spot as a common factor to begin with.  This probably means I have a work around which is to simply add at least one public event in an era to force the era to be shown. I'm going to try that now. I still think this is kind of a bug, though (although one I am now much happier living with, now I understand the behaviour and can potentially control it). The timeline when logged on, doesn't seem to need an event to show it and looked great even without any events. Would be less confusing if the non-logged on view looked exactly like the logged on view when all permissions are public.

**Comment by iamromeo** [comment]
It is not about logged in or not, it's about an owner/editor of a world which need to see the eras vs any reader who can only see what is there. 

This is not a bug since it was voted by the community to act as such.
