### ISSUE TITLE
Variable not present in hover pop up for article

### ISSUE THREAD

**Issue by jerry2478** [worldanvil/worldanvil-bug-tracker#72]
**World Anvil Username**:jerry247

**World / Campaign / RPG Character / Manuscript Title**:multiverse!

**Feature**: variable

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/multiverse21-jerry247/a/3-entrance-to-the-tomb-of-horrors-landmark
https://www.worldanvil.com/w/multiverse21-jerry247/a/4-fresco-of-the-wizardly-work-room-landmark
**Describe the Issue**
A clear and concise description of what the issue is.
the sidebar contains a link to a page with a variable in the text. when the hover preview pops up the variable is absent completely.
**To Reproduce**
1. Go to first link above
2. hover over "4. Fresco of the Wizardly Work Room" in sidebar
3. See error on 15th(?) line sentance should read: "This lever moves easily, and if it is pulled with any force it will open a trapdoor in this square that covers a 30-foot-deep covered pits." covered pits is absent.

**Expected behavior**
covered pits should be readable, if not hoverable.

contact me on discord if you need more information. jerry247

**Comment by iamromeo** [comment]
The content will not appear as a bubbling up modal but the actual title will be in place
