### ISSUE TITLE
Creating articles in Article & Categories defies forced privacy state

### ISSUE THREAD

**Issue by MGatta** [worldanvil/worldanvil-bug-tracker#721]
**World Anvil Username**: MGatta

**Feature**: Article & Categories

**Describe the Issue**
Even though my world has the setting for "forced privacy" so that all new articles are private, when creating an article in a category within the Articles & Categories section, the created articles are public, not private.

**To Reproduce**
1. Go to world settings and force all articles created to be private
2. Go to Articles & Categories, create a new category, and select on create a new article
3. Fill in title & article template
4. Scroll down to see "Public" as the default article privacy state

**Expected behavior**
For the new articles created (regardless of where) to follow the desired privacy setting of the world.

**Screenshots**
![image](https://user-images.githubusercontent.com/80196715/143719902-93e34d4c-34b8-4a5e-b8e1-422c7e9d5ffd.png)
![image](https://user-images.githubusercontent.com/80196715/143719908-9b22d650-6d98-46b4-a93d-fc8f42981ce6.png)

**Comment by iamromeo** [comment]
Fixed, will be deployed within the next 36 hours
