### ISSUE TITLE
world title copyright lock

### ISSUE THREAD

**Issue by Chasm-98** [worldanvil/worldanvil-bug-tracker#722]
**World Anvil Username**: Chasm

**World / Campaign / RPG Character / Manuscript Title**: My world is called "Placeholder Name" for now, for reasons that will become clear soon.

**Feature**: The "Create World" feature where you put in a title name

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
The issue is that I've previously made a world with the name "The Everlasting Reaches", of which I must've deleted, and subsequently tried to create again. Creating a new world with this same name did not work as someone on the WorldAnvil discord server taught me it may have to do with a copyright lock on the name, and that I'd have to report it here to get it released, so I can reuse it. Hopefully I can get some help with that.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Hello Chasm, I see no other world with this name or another deleted account with that username, There is a world with the same name but this is not under your username so this is not a copyright lock issue. 
Can you please show me the error you get when you try to rename your world?

**Comment by Chasm-98** [comment]
Hello!

After naming my world something else to be able to create it, and then renaming it to The Everlasting Reaches after the initial creation process, the issue resolved itself, not sure why or how, but it's working, I appreciate your email though! Have a good day!

Best regards, Casper

________________________________
Fra: Dimitris Romeo Havlidis ***@***.***>
Sendt: 28. november 2021 09:30
Til: worldanvil/worldanvil-bug-tracker ***@***.***>
Cc: Chasm-98 ***@***.***>; Author ***@***.***>
Emne: Re: [worldanvil/worldanvil-bug-tracker] world title copyright lock (Issue #722)


Hello Chasm, I see no other world with this name or another deleted account with that username, There is a world with the same name but this is not under your username so this is not a copyright lock issue.
Can you please show me the error you get when you try to rename your world?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fworldanvil%2Fworldanvil-bug-tracker%2Fissues%2F722%23issuecomment-981004133&data=04%7C01%7C%7C9bc06ba9e6544474cb6308d9b2495f15%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637736850465645486%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=M6pO7v%2BKXOYYNOcJFF3Kcjp2eOcqDos%2FU4pEs3%2FWC9Y%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWV56V2CBYNGISINJLUWVWLUOHSDHANCNFSM5I4SYHAA&data=04%7C01%7C%7C9bc06ba9e6544474cb6308d9b2495f15%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637736850465645486%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HkdpuYoSkhTio5Js1Mz2Wfa31ehvlRb0slWgseumooY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C9bc06ba9e6544474cb6308d9b2495f15%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637736850465655479%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=n0UoHlzUL6BE8%2Fs9KtH05asLdkRVy0D4p7s2TAL2NUQ%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C9bc06ba9e6544474cb6308d9b2495f15%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637736850465655479%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sBbgEXVhB1om%2BY3dT%2F2dh91sBiD0Qc%2F9BIZA1rydJ%2FM%3D&reserved=0>.
