### ISSUE TITLE
Mouse-Over not working for Article Links

### ISSUE THREAD

**Issue by sullome** [worldanvil/worldanvil-bug-tracker#724]
**World Anvil Username**: Sullome

**World / Campaign / RPG Character / Manuscript Title**: https://www.worldanvil.com/w/D0A1D0BAD0B0D0B7-D0BE-D0BFD0B8D180D0B0D182D0B0D185-sullome

**Feature**: Article Preview

**Describe the Issue**
For an unclear reason, article preview is not shown for article links, nor for article blocks.

Observations:

- Option ""Display Article Tooltips" is enabled in World Settings.
- Links to history event articles, made by `[history]` BBCode produce correct article preview on mouse over.
- Links to history event articles have class `tooltipstered` assigned to them, links to regular articles, for which previews are not working does not have class `tooltipstered` assigned to them.
- Article Preview is working on World Anvil Codex pages, for example, on [Guide to BBCode Commands](https://www.worldanvil.com/w/WorldAnvilCodex/a/bbcode)
- Browser — Firefox 94.0

**To Reproduce**
1. Go to https://www.worldanvil.com/w/D0A1D0BAD0B0D0B7-D0BE-D0BFD0B8D180D0B0D182D0B0D185-sullome/a/main-test-article-article
2. Mouse over "Some Historical Event" link — preview of the article is shown
3. Mouse over "Linked Test Article" link — preview of the article is not shown

**Expected behavior**
Preview of the article shown for both links.

**Screenshots**
![Working Article Preview](https://user-images.githubusercontent.com/5189428/143781989-446bddab-80ec-490d-9143-f66a9cf8d0d3.png)
![Not Working Article Preview](https://user-images.githubusercontent.com/5189428/143781990-69925393-fe72-41ed-9750-0c433193c2f0.png)

**Comment by sullome** [comment]
What I found with Firefox Tools is that history link in the articles have next functions for mouseover event:
```js
function(b) {
  !a._touchIsTouchEvent(b) && a._touchIsEmulatedEvent(b) || (a.__pointerIsOverOrigin = !0, a._openShortly(b))
}
function(b) {
  return "undefined" != typeof r && r.event.triggered !== b.type ? r.event.dispatch.apply(a, arguments) : void 0
}
```
However, article link, for which preview is not working, has next functions assigned for mouseover event:
```js
function() {
  return a.apply(b || this, d.concat(f.call(arguments)))
}
function(b) {
  return "undefined" != typeof r && r.event.triggered !== b.type ? r.event.dispatch.apply(a, arguments) : void 0
}
```

**Comment by iamromeo** [comment]
I cannot reproduce this for two reasons
- the above article is private 
- It's working everywhere else

I am not sure if this an issue with the article being unpublished (Draft) or something else but this does work as intended everywhere I can find it. 

@Kordishal can you have a look as well?

**Comment by sullome** [comment]
@iamromeo sorry, opened world, category and article, forgot to do that.

**Comment by Kordishal** [comment]
Article Preview is a Master+ feature: https://www.worldanvil.com/w/WorldAnvilCodex/a/previews

That is why it is not working for you. Fill in the excerpt field for a tooltip.

**Comment by sullome** [comment]
@Kordishal thank you for clarification!

Although, it would be great if there was a clarification under "Display Article Tooltips" or "Mouseover Snippet" that this is a Master+ feature.

Anyway, I'll probably upgrade then.

**Comment by Kordishal** [comment]
If you see those sections, then that is either a bug or the feature was supposed to be for Journey and wasn't correctly unlocked.

**Comment by iamromeo** [comment]
Fix deploying now-ish
