### ISSUE TITLE
Article changes by only using Euclid Formatting Buttons are not saved

### ISSUE THREAD

**Issue by Jan-Ka** [worldanvil/worldanvil-bug-tracker#725]
**World Anvil Username**: ka_jan

**World / Campaign / RPG Character / Manuscript Title**:  Urlurra / Euclid Error

**Feature**:  Euclid Editor

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/urlurra/a/euclid-error-article

**Describe the Issue**
Using the formatting buttons (such as paragraph, quote, alignment) on a text selection does not seem to cause a change that would trigger a save
Pressing the save button does not save what is shown in the editor, but the unchanged text.

This issue seems to be not unique to the main article field but on every field using Euclid (such as Sidebar: Top as example)

_Usually happens when coming into the article editor from the Article preview via the "Edit Article" Button to fix small formatting errors which looks like: selecting a text, then pressing a format button, pressing the Save Button and finally clicking the View Button._

**To Reproduce**
1. Create new article
2. add Title to article
3. save and reload
4. insert some text such as `Lorem ipsum dolor sit amet, consectetur adipiscing elit.`
5. save and reload
6. select the text
7. press the quote button (it's easier to see that nothing happens, but most other buttons seem to have the same issue)
8. see that no save notification is triggered if no additional modifications are made (e.g. typing or using the spellchecker button)
9. press save button (save notification shows but did not save expected content)
<img width="396" alt="image" src="https://user-images.githubusercontent.com/11042838/143959195-eabedaff-568e-4e13-8428-741eba08c460.png">

10. reload page to see changes gone, or press view to see that previous changes are missing

As long as only the formatting buttons are used, no changes are saved.
Using the spellchecker button before saving (once for engage, second time for disengage) and then pressing save, seems to work.

**Expected behavior**
Formatting, without typing / using keyboard shortcuts, should save what is visible in the editor.

**Comment by iamromeo** [comment]
This has been addressed multiple times in the past. It is a known issue it will not be addressed until the next version of the editor. :) Please check previous reports <3
