### ISSUE TITLE
Campaign character made by another user will not appear in list of PCs aka Cast

### ISSUE THREAD

**Issue by Leezard113** [worldanvil/worldanvil-bug-tracker#726]
**World Anvil Username**: paladinlee

**World / Campaign / RPG Character / Manuscript Title**: Waterdeep / Dragon Heist / Klogani Swiftgift / 

**Feature**:  "Cast" aka "PCs"

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
User (named JoelleyFoley) who is a member of my campaign is unable to have their character display in the campaign's list of PCs.

**To Reproduce**

**Expected behavior**
Character made by one of my players to appear in the campaign list of PC's or Cast.

**Screenshots**
![image](https://user-images.githubusercontent.com/95265704/143981989-2fcc7574-ffa7-45db-9599-866be00ceee3.png)
![image](https://user-images.githubusercontent.com/95265704/143982035-755176d3-43fe-439e-a8a6-3eb33302fdf2.png)

**Comment by iamromeo** [comment]
I am sorry but I will need to have some links to check this out. Can you please provide with links to your campaign and the hero profile of your friend?

**Comment by Kordishal** [comment]
Is the player visible in the Party screen? 

Then it is probably the same issue as in #175.

**Comment by Leezard113** [comment]
Campaign:
https://www.worldanvil.com/heroes/campaign/6987fec0-5b1d-4a48-a603-b62fa72e3c78/dashboard
or
https://www.worldanvil.com/epic/52ZkNciQgEjISsKoFDPtW4ESciRKTF


hero profile:
https://www.worldanvil.com/hero/e93b6e15-bd6b-4544-80e2-d4b4ca511db6

-Lee

**Comment by Kordishal** [comment]
That character is in the world but not in the campaign as far as I can tell. Try expelling them from the world and then invite them to the campaign

**Comment by Leezard113** [comment]
when she joins the campaign, she reports this...
"
This comes up and when I choose her it gives me 404
[image: Image]
<https://cdn.discordapp.com/attachments/915014110167588885/915396294976098344/unknown.jpeg>
"

-Lee

**Comment by iamromeo** [comment]
@Leezard113  In order to replicate and debug this, I will need the owner of the account to give me access to it (please change password and send username/password to hello@worldanvil.com)

From you I will need the link you have given them to join the campaign

**Comment by Kordishal** [comment]
Have you kicked her from the world first, though? She can't join the world if she is already in the world.

**Comment by iamromeo** [comment]
> Have you kicked her from the world first, though? She can't join the campaign if she is already in the world.
> 
> You can expel them from the world via this menu: ![image](https://user-images.githubusercontent.com/14262536/144262627-94f83084-e7df-4a51-afff-111c2fccdae0.png)

Hmmm this needs to be fixed. Since people are not kicked out of the world when they are kicked out of a campaign, being kicked out of the world to join a cmapaign should not be a requirement. 

I am checking this right now.

**Comment by iamromeo** [comment]
Ok after extensive testing the above are all covered and tested. 

@Leezard113 I will really need the information that I asked for above to fix this for you and find the issue. 
Please ask your player to send me their credentials (After changing their password) to hello@worldanvil.com and please send me your campaign invitation link here.

**Comment by iamromeo** [comment]
Any news on this? @Leezard113

**Comment by Leezard113** [comment]
Greetings!  I am meeting with the player tomorrow (Sunday) to gather
further information and can report back to you then.  Talk to you soon,
thanks,

-Lee

**Comment by Leezard113** [comment]
this case may be closed.

unfortunately, I am unable to describe what I did to fix.  I gained access
to the user's login and disassociated the character from the world and then
re-added.  it took a couple of tries.

-Lee

**Comment by iamromeo** [comment]
@Leezard113 the times that it failed can you tell me what happened?
