### ISSUE TITLE
Custom Article Templates do not render symbol on Dashboard

### ISSUE THREAD

**Issue by mDehning** [worldanvil/worldanvil-bug-tracker#727]
**World Anvil Username**:
Vertixico

**World / Campaign / RPG Character / Manuscript Title**:
Ekozia

**Feature**: 
Custom Articles

**Describe the Issue**
When creating a custom template and selecting an rpg-awesome symbol for it, this symbol does not show up on the dashboard. The HTML Element of the icon is missing the appropriate classes "ra" and "fa".

**To Reproduce**
1. Create any Custom Article Template
2. Select an Icon for said template, for example "ra-speech-bubbles"
3. Attach template to a world
4. Open Dashboard of the world
5. Custom Template appears with no symbol / a square as placeholder

**Screenshots**
![image](https://user-images.githubusercontent.com/31063219/144020647-b45afee3-43cb-42c0-8815-f67c7f6e6486.png)
The icon to the right had the class "ra" manually added to the element.

Unedited (not working, left side button):
![image](https://user-images.githubusercontent.com/31063219/144020929-4b198253-cc64-4093-a494-317b96a98815.png)
Works as soon as the class "fa" is added

Edited (right side):
![image](https://user-images.githubusercontent.com/31063219/144020831-485e93d9-8f48-494d-abf0-525edefeee3f.png)
Started working as soon as the class "ra" was added

**Comment by iamromeo** [comment]
Are you sure it's ra-speech-bubbles and not fa ?
