### ISSUE TITLE
Notebook note counter works incorrectly in free version

### ISSUE THREAD

**Issue by a-shroom** [worldanvil/worldanvil-bug-tracker#73]
**World Anvil Username**: frgovara

**World / Campaign / RPG Character / Manuscript Title**: Gardens

**Feature**: Notebook

**Related URLS** (To public & visible pages add screenshots otherwise): N/A (not sure if notebooks are linkable)

**Describe the Issue**
I made a notebook in the notebook app, added a few pages and some notes (totalling 5 notes). I get a message saying I have reached the maximum number of notes for a free account (reportedly 10 notes). Clearly, I do not have 10 notes made, and cannot get beyond 5. Deleting a note frees up a slot after a few minutes of waiting, but creating another note after displays the message once again.

**To Reproduce**
1. Go to notebook (free account)
2. Create a notebook
3. Create 5 notes
4. See error/note

**Expected behavior**
I expect the notebook app, now that this feature is available to free users, to either correctly count my nubmer of notes, or correctly display the maximum allowed number of notes a free user can create.

**Screenshots**
Notebook management tab:
![image](https://user-images.githubusercontent.com/62396124/111296727-17830b80-864d-11eb-8626-185b8e5092ca.png)

Message displayed in the notebook:
![image](https://user-images.githubusercontent.com/62396124/111296798-2e296280-864d-11eb-8399-da44e9dd0efa.png)

**Comment by iamromeo** [comment]
The notebook no longer has 10 sheets for free. This feature will be completely removed from the the free version because of regulat abuse.
