### ISSUE TITLE
Alegreya Regular Font in D&D 3.5 Monster Template does not support bold

### ISSUE THREAD

**Issue by Dougman96455** [worldanvil/worldanvil-bug-tracker#730]
**World Anvil Username**:
GameOverMan96
**World / Campaign / RPG Character / Manuscript Title**:
Munnad'il
**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.
[BB] code for bold type does not work in statblock description panel. Underline and Italic works fine. Found using D&D 3.5 Monster statblock template.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Can you provide a link to an example statblock with that issue?

**Comment by Dougman96455** [comment]
Still familiarising myself with navigation etc. Not sure if this will let you access the block. 
[block:883938]
Thanks

Sent from Mail for Windows

**Comment by Kordishal** [comment]
I can't access that statblock directly. Can you toggle the `Allow users to view...` in the statblock editor: 

![image](https://user-images.githubusercontent.com/14262536/144292176-3d57df1e-9de5-4770-a55a-2bf9b652b984.png)

Then I can have a look.

**Comment by Dougman96455** [comment]
Sorry,
once again I’m new at this. Should be available now.

Sent from Mail for Windows

**Comment by Kordishal** [comment]
The [b] does work, the used font just doesn't support bold for some reason. 

For Dimitris: This might be an issue how the font is installed for the template.

@Tillerz

**Comment by Dougman96455** [comment]
Sound


Sent from Mail for Windows

**Comment by Kordishal** [comment]
The issue has been resolved by Tillerz

**Comment by Tillerz** [comment]
Fixed it for character, monster, feat and spell.
