### ISSUE TITLE
In character template the Honorary Titles is generated as dt/dd pair which does not allow KEY-VALUE Pair Code

### ISSUE THREAD

**Issue by PatheticBarrel** [worldanvil/worldanvil-bug-tracker#731]
**World Anvil Username**:
PatheticBarrel
**World / Campaign / RPG Character / Manuscript Title**:
The Hylian Fantasy
**Feature**: 
Key Value Pairs
**Related URLS** (To public & visible pages add screenshots otherwise): see screenshots.

Reader reported not being able to click on any bottom of page buttons (Like, Follow, Reading List etc) and subsequent troubleshooting revealed this to extend to links throughout article. Global footer and breadcrumbs (mine appear below footer) were also out of whack.

Additionally, sidebar fields appeared as incorrectly indented.

Troubleshooting with Legna and Soulink led to me removing the KVP from the Titles field under Naming, which fixed the issue 
Sidebar appearance
![unknown-6](https://user-images.githubusercontent.com/65030632/144277580-9a65baf2-cb5f-47bc-82c6-af98760027c0.png)
Lower article appearance
![Screenshot_20211201-111513](https://user-images.githubusercontent.com/65030632/144277609-b262dcf3-58ec-4c57-b91e-9843081b88a9.jpg)

**Comment by Kordishal** [comment]
Replacing the HTML generated by that field with the section-title + section-payload divs would likely resolve this issue.

**Comment by iamromeo** [comment]
Fixed - deploying today
