### ISSUE TITLE
Discord embeds for image links show raw BBCode

### ISSUE THREAD

**Issue by SierraKomodo** [worldanvil/worldanvil-bug-tracker#733]
**World Anvil Username**:
SierraKomodo

**World / Campaign / RPG Character / Manuscript Title**:
Galaxies End

**Feature**: 
Discord embedding of links to image pages

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/i/2834266

**Describe the Issue**
When posting links to image pages on discord, the metadata presented that discord displays includes bbcode tags from the description box instead of the final rendered text. See below screenshot.

**To Reproduce**
1. Post a link to a public/published image page on WorldAnvil onto a discord channel or DM that includes bbcode in the description box.
2. Wait for the discord preview/embed to appear.

**Expected behavior**
Discord embed description should present the final rendered text instead of the raw bbcode - I.e., from the example screenshot below, the description should show:
> A portrait of Dominika Kirilisav wearing her service dress uniform.

**Screenshots**
![Discord_2021-11-29_17-00-59](https://user-images.githubusercontent.com/11140088/144540542-d43db8fb-efd6-4f0a-b797-c2ddc6f276ef.png)

**Comment by iamromeo** [comment]
That is not possible since DIscord descriptions do not support anything except plain text.
