### ISSUE TITLE
Article removed from WorldEmber with Remove Entry keeps being readded to WorldEmber

### ISSUE THREAD

**Issue by Hurttaj** [worldanvil/worldanvil-bug-tracker#734]
**World Anvil Username**:
frogdrake

**World / Campaign / RPG Character / Manuscript Title**:
Spirit of the Age

**Feature**: 
Remove Entry (from WorldEmber)

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/spirit-of-the-age-frogdrake/a/spiritd6-skills-article

**Describe the Issue**
On the above linked article, I have now three times removed the article from my worldember progress (because it's not really worldbuilding but TTRPG rules). Every time I remove the article using the remove entry button, it comes back after a few hours/the next day (I am not totally sure how long it takes to return)

**To Reproduce**
1. Click the "Remove Entry" button on an article that is part of your WorldEmber progress.
2. Wait

**Expected behavior**
The article should stay permanently removed from WorldEmber.

**Comment by iamromeo** [comment]
Sadly not a bug but an issue with the interface. Articles cannot be removed from World Ember if they are 
- Public 
- In a public world
- Published
breaking any of the above during Worldember will disqualify the article for the month

**Comment by Kordishal** [comment]
Then why is the button there if it doesn't stick? Wouldn't it be removed automatically if you draft / private an article during WorldEmber?

**Comment by Amancham** [comment]
I know this has been closed already, but I have to agree with @Kordishal here. If the button doesn't stick, and it is not actually possible to remove articles from world ember, then please for the love of god, delete the useless button. This keeps bugging me and 'promising' something that is obviously not possible to be delivered (e.g. not counting an article towards world ember when removing it) is only throwing up questions.

**Comment by Kordishal** [comment]
Dimitris has stated in another place that the button can be used to removed entries from the special categories submissions. So it has to stay. But it might make sense to rename this clearer.

And I do think you need to use the button if you want to turn an article private / draft so it gets removed and then stays removed as it is no longer discorverable.

**Comment by Amancham** [comment]
Thank you for the information. 

Makes sense, of course, though I do agree that renaming the button might be an idea for next year. 

And maybe add a quick info about removing and making it private or setting as a draft to get rid of the article if needed. As it stands right now it is, unfortunately, not very clear how it works. Maybe a line or two like the info about adding an article for a special category, would be helpful.
