### ISSUE TITLE
Military Conflict template won't expand to 100% if no sidebar

### ISSUE THREAD

**Issue by samsarag** [worldanvil/worldanvil-bug-tracker#735]
**World Anvil Username**: George Sanders george.a.sanders@gmail.com samsarat samsaratg

**World / Campaign / RPG Character / Manuscript Title**: Anhult

**Feature**: Military Conflict template won't expand to 100%

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/anhult/a/siege-of-mirasoon-militaryconflict
https://www.worldanvil.com/w/anhult/a/flowers-of-war

**Describe the Issue**
I unchecked the box so the sidebar would hide. The sidebar content is hidden but the bootstrap css stays at 66% width. The article won't expand to 100% of the space. 

**To Reproduce**
1. Create a Conflict Article
2. Add some content
3. Go to Sections 
4. Scroll down and uncheck the box to hide the sidebar
5. Preview the Article and it is not 100% width. 

**Expected behavior**
It doesn't stay at 66% on any other article template that I have seen when the sidebar is hidden so seems like an adjustment is needed on the military conflict article template

**Screenshots**

**Comment by iamromeo** [comment]
This is not a bug, these are both military conflicts without belligerents, like saying humans without heads :P

**Comment by Kordishal** [comment]
Then you should not use that template if you don't want the Wikipedia style belligerent summary section in your military conflict?

**Comment by Kordishal** [comment]
My question was targeted at DImitris. I agree with your sentiment that the template should act the same way that other templates do. As in have the sidebar toggle actually hide the sidebar.

**Comment by iamromeo** [comment]
@samsarag @Kordishal fixed this - currently deploying

**Comment by samsarag** [comment]
The fix looks good!
