### ISSUE TITLE
404 errors for syncing discord and updating email

### ISSUE THREAD

**Issue by StrangeNovelty** [worldanvil/worldanvil-bug-tracker#736]
**World Anvil Username**: Toole

**World / Campaign / RPG Character / Manuscript Title**: 

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I am having 2 issues. I upgraded to Sage and attempted to sync with Discord and am getting a 404 error
also When i try to update my email to a new one, that also brings up a 404 error message.

**To Reproduce**
1. Go to Accounts
2. Click on 'Update' after entering in my preferred email, current ID and password  (other issue: click on the discord link on the accounts page, log into discord.)
3. See error

**Expected behavior**
I was hoping that in the first issue, Discord would sync and in the second issue, i would be able to update my email

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/62902266/144700690-1c946f5b-ee8e-4803-9df1-2535b5d4b211.png)
![image](https://user-images.githubusercontent.com/62902266/144700694-77d9b09e-1f6b-4724-b956-dc5cae907656.png)

**Comment by Kordishal** [comment]
Did you update to Eternal Sage? Then message a moderator on Discord to get that sorted. Otherwise @Xuroth will have to have a look.

**Comment by iamromeo** [comment]
Both of those issues have one thing in common. A previous account 
that 
1. Has the lock on the Discord ID
2. Is using the email you are trying to change TO 

Is that the case?

**Comment by iamromeo** [comment]
No reply for over 1 month
