### ISSUE TITLE
Quotation marks break generic rolling table

### ISSUE THREAD

**Issue by MGatta** [worldanvil/worldanvil-bug-tracker#737]
**World Anvil Username**:

**Feature**: Rolling tables

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/13-mgatta/a/test-tables-article

**Describe the Issue**
Adding quotation marks (") makes rolling tables not function. When you click on them they stop jump to the top of the page and still do not roll for a result.

**To Reproduce**
1. Make a rolling table
2. Test it
3. Add a quotation mark

**Expected behavior**
To be able to add quotation marks

**Comment by iamromeo** [comment]
This will not be actioned. We do have modern tables that can do the same things the old ones can - as mentioned before these tables are going out of the way soon.
