### ISSUE TITLE
Counting words 

### ISSUE THREAD

**Issue by Edward-Morein** [worldanvil/worldanvil-bug-tracker#739]
**World Anvil Username**: Liar Moraine 

**World / Campaign / RPG Character / Manuscript Title**: After The End 

**Feature**: Counting words 

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/after-the-end-liar-moraine/a/D098D181D0BAD183D181D0BDD0BED181D182D18C-person-1

**Describe the Issue**
Hello, help solve the problem, please!

The article written in my native language, consisting of about 2000 words, according to the site algorithms, contains no more than 364 words. I noticed this sin and for other written articles, but did not give it importance because of their insignificance, but somehow I do not understand why try to write something if the system still does not count the total number of words. I would have enough to write a couple more articles about the deities and I would have achieved the goal, but now I don't even know what kind of memoirs you need to write to achieve a threshold at least in 10,000 words. Help me figure it out! 

**To Reproduce**
1.Posted by Article.
2.Published
3.Instead of the actual number of words, a different number shows.

**Expected behavior**
The actual number of words in the article.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

https://www.worldanvil.com/i/2872527
https://www.worldanvil.com/i/2872528
https://www.worldanvil.com/i/2872529

**Comment by Kordishal** [comment]
Unfortunately, the word count currently does not work properly with Cyrillic or Greek alphabets. This is the reason that it does not count the total number.

**Comment by iamromeo** [comment]
Sadly this is a known issue and it is a matter of encoding which cannot be easily fixed. I am honeslty really sorry (I am Greek and I had the same issue), at this point I will not be actioning this.

**Comment by iamromeo** [comment]
IF this is a Worldember issue - I will be willing to see articles myself and award the badge regardless on the count on the page. 
Just create a category of articles that are public and published in a public world and submit it to me at the end of the competition
