### ISSUE TITLE
Back-end Side Bar overlap

### ISSUE THREAD

**Issue by GamezGm** [worldanvil/worldanvil-bug-tracker#740]
**World Anvil Username**: Gamez

**World / Campaign / RPG Character / Manuscript Title**: World

When you click into the world to vie wan article and revert to the back-end the sidebar overlaps even when hidden.

see image.
![Bug](https://user-images.githubusercontent.com/81829633/144937279-1a78442f-2853-4249-b759-d809197ce70c.PNG)

**Comment by GamezGm** [comment]
Browser used Google Chrome

**Comment by iamromeo** [comment]
I am sorry but this report makes little sense, also I cannot reproduce it. We know there is an issue with this DURING loading but not after.
