### ISSUE TITLE
Link code not parsing

### ISSUE THREAD

**Issue by FantasyXah** [worldanvil/worldanvil-bug-tracker#741]
**World Anvil Username**: xah

**World / Campaign / RPG Character / Manuscript Title**: All worlds and articles

**Feature**: Generating @ links within articles

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/atray-xah/a/test-article-article

**Describe the Issue**
When adding @ links to an article, the last link on the page fails to parse as a link within in the article, despite appearing legitimate in the editing screen. Reloading the article to edit reverts the link to whatever was used to pull up the link from the list

**To Reproduce**
1. Create article
2. Create a link to an existing article using @
3. Save the article
4. View article

**Expected behavior**
Links to be shown as expected

**Screenshots**

![The Code](https://user-images.githubusercontent.com/95686579/145014782-48f83705-d922-4bdd-ba23-4f9add2f6ea7.png)
![The Page](https://user-images.githubusercontent.com/95686579/145014789-af070802-7c46-4d18-ad38-cb70cd8ceb2a.png)

**Comment by Kordishal** [comment]
This is a save issue. You likely select the articles with your mouse. This does not trigger the auto-save. So before viewing the result, add a space or use the keyboard keys to select the article from the dropdown.
