### ISSUE TITLE
Commented out BBCode section visible in the Preview

### ISSUE THREAD

**Issue by Arghantyr** [worldanvil/worldanvil-bug-tracker#743]
**World Anvil Username**: Angantyr

**World / Campaign / RPG Character / Manuscript Title**: Ædeos

**Feature**: Preview of the article embedded using the article block.

**Related URLS** (To public & visible pages add screenshots otherwise):

URL1. [Worldember hub, through which the Preview was noticed](https://www.worldanvil.com/w/Adeos-angantyr/a/worldember-2021-article?preview=true)
URL2. [The article with some commented out BBCode at the end](https://www.worldanvil.com/w/Adeos-angantyr/a/velvet-shanks-species)

**Describe the Issue**
When Previewing the article content through the article block, the viewer can see the commented out section of the BBCode.

**To Reproduce**
1. Go to URL1
2. Mouseover article block 1: Velvet shanks
3. Scroll down to the bottom of the article visible through the article block
4. See the empty quote block wrapped in /* */ tags

**Expected behavior**
When Previewing the article by mouseovering the article block, one should see the commented out empty quote. When entering the article itself (URL2), the quote is not visible.

**Screenshots**
![Screenshot 2021-12-09 at 15 09 14](https://user-images.githubusercontent.com/59778570/145411439-0e5f762a-30f0-47de-b54e-1ee59fe71cdd.png)

**Comment by Arghantyr** [comment]
And it turns out this is the case for signatures as well:

![Screenshot 2021-12-09 at 16 04 19](https://user-images.githubusercontent.com/59778570/145421681-113e1777-a36b-4132-8f11-8e61b5c454be.png)

**Comment by iamromeo** [comment]
That will not be addressed. in comments. 
Comments of this sort are a quick way to note take - I will have a look if it's something that can be easily fixed on the preview but it will not be a priority.

**Comment by Arghantyr** [comment]
Got it. I will leave the commented out quote in the article until the ticket closes, so it is accessible at any time.
