### ISSUE TITLE
Dragging & Dropping images into gallery does not work due to changed path

### ISSUE THREAD

**Issue by CyricTheDark** [worldanvil/worldanvil-bug-tracker#744]
**Cyric**:

**Valenor**:

**Images**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Dragging & dropping images in Gallery does not work anymore.

**To Reproduce**
1. Go to 'Images'
2. Load a new image
3. Drag & Drop in a Gallery
4. The Image is still in the "unsorted files" and not in the selected folder.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Fixed deploying ASAP

**Comment by iamromeo** [comment]
Thank you so much for the heads up and thorough review
