### ISSUE TITLE
RPG and Font Awesome fonts are not appearing on any pages

### ISSUE THREAD

**Issue by Gritchu** [worldanvil/worldanvil-bug-tracker#745]
**World Anvil Username**:
Gritchu

**World / Campaign / RPG Character / Manuscript Title**:
N/A

**Feature**: 
RPG and Font-Awesome icons

**Related URLS** (To public & visible pages add screenshots otherwise):
Everywhere these icons are used. For Articles mostly.

**Describe the Issue**
I've added links to RPG and Font Awesome icons, however, they don't show up. In place of the icon, both in the CMS and on the page view, I only see an empty box.

**To Reproduce**
1. Go to an article in the WorldAnvil CMS
2. Click where it lets you add a RPG or Font Awesome icon, and add it.
3. View the Table of Contents on the page, or the article itself.
4. See error, No icon and instead an empty box.

**Expected behavior**
I would expect to see the icon I selected rather than an empty box.

**Screenshots**
![image](https://user-images.githubusercontent.com/79152593/145470447-31eb85f7-118f-4802-9724-d16512aca57c.png)
![image](https://user-images.githubusercontent.com/79152593/145471530-b7102bb1-c6ac-476e-b7ad-0e823c1f9153.png)

Also found a typo:
![image](https://user-images.githubusercontent.com/79152593/145471800-dbd071e0-bf9d-46af-ba95-9392b45841ec.png)

**Comment by Kordishal** [comment]
You are missing the prefix class.

In case of RPGAwesome it is always `ra ra-heartburn`.

For Fontawesome it is one of `fas`, `fal`, `far`, `fab` or `fad` (different versions of the same icon, not all options are available for all icons)

**Comment by iamromeo** [comment]
Fixed the typo - will be deploying today
