### ISSUE TITLE
Protagonist List bug in Campaign Home

### ISSUE THREAD

**Issue by dcf0** [worldanvil/worldanvil-bug-tracker#746]
**World Anvil Username**: dcf

**World / Campaign / RPG Character / Manuscript Title**: Curse of Strahd

**Feature**: Campaign Home

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/epic/the-curse-of-strahd

**Describe the Issue**
A clear and concise description of what the issue is.
When players created their PCs in world anvil, an empty container was somehow created between two of the players. This field contains a '-' symbol and a eye symbol.

eye symbol links: https://www.worldanvil.com/sheet/857105/view
As the world creator I do not have access to this sheet.

the 'minus' symbol links to the player character's page above the dummy cell. https://www.worldanvil.com/hero/b4b08341-1b90-41b4-b6a1-20de30d785b4

There are no controls that allow me to remove this cell from the page.

**To Reproduce**
1. Go to '[...](https://www.worldanvil.com/epic/the-curse-of-strahd)'
2. Scroll down protagonists list to see the empty container

**Expected behavior**
Empty container should not exist in the list.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/95884471/145473226-164d8b44-2824-41ea-a29b-c5621f75ec06.png)

**Comment by iamromeo** [comment]
This is now resolved

**Comment by dcf0** [comment]
Wow! Thank you for the fast turn around!

**Comment by iamromeo** [comment]
I try  - Have an awesome one @dcf0
