### ISSUE TITLE
Pathfinder 1a icon causes formatting error in rendered fragment

### ISSUE THREAD

**Issue by Frumpski** [worldanvil/worldanvil-bug-tracker#747]
**World Anvil Username**:
efrec

**World / Campaign / RPG Character / Manuscript Title**:
Cimbri

**Feature**: 
Pathfinder icons, rendered fragments

**Related URLS** (To public & visible pages add screenshots otherwise):
Set to private, as this is an early draft. Screenshots below.
![image](https://user-images.githubusercontent.com/21204953/145474252-e92992e2-58c9-4942-805a-8a82f5337c3e.png)

![image](https://user-images.githubusercontent.com/21204953/145474345-a3ce9a1c-d5de-4a05-8f2f-25ed3f791dd6.png)

**Describe the Issue**
The two-action pathfinder icon renders differently than the others when placed within a rendered fragment. I am repurposing these icons for fun and profit, but others may want to customize these tooltips themselves as well for consistent tooltips across their articles.

**To Reproduce**
Create the following world variables:
Collection
	Notation
Prefix
	note
Rendered Fragment
	Key: action
	Value: [tooltip: Action][pf:2a][/tooltip]
Rendered Fragment
	Key: bonus_action
	Value: [tooltip: Bonus action][pf:1a][/tooltip]

Add them to an article as this BBCode:
[table]
[tr] [th:20]Symbol[/th] [th:80]Meaning[/th] [/tr]
[tr] [td:20][var:note-action][/td] [td:80]Action[/td] [/tr]
[tr] [td:20][var:note-bonusaction][/td] [td:80]Bonus action[/td] [/tr]
[/table]

View source HTML of article:
```<table class="table table-striped">
<tr> <th style="width:20%;">Symbol</th> <th style="width:80%;">Meaning</th> </tr>
<tr> <td style="width:20%;"><span class="world-variable world-variable-string note-action"><span class="text-abbreviation tooltipster cursor-pointer" title=" Action"><img src="/images/rpgsrd/system-imagery/pathfinder2/a2.png" class="iconPf2 twoaction tooltipster" title="Two Actions"/></span></span></td> <td style="width:80%;">Action</td> </tr>
<tr> <td style="width:20%;"><a class="world-variable world-variable-link" href="<span class="text-abbreviation tooltipster cursor-pointer" title=" Bonus action."><img src="/images/rpgsrd/system-imagery/pathfinder2/a1.png" class="iconPf2 oneaction tooltipster" title="One Action"/></span>"></a></td> <td style="width:80%;">Bonus action</td> </tr>
</table>
```

The tooltip for the pf:2a fragment works fine and exactly as expected, as do all other pathfinder icons except the pf:2a icon. Both the tooltip and the displayed icon/text are broken in this example.

**Expected behavior**
![image](https://user-images.githubusercontent.com/21204953/145474722-95481960-135a-4430-ab05-f7b425ed7883.png)

Any "outer" tooltips I set around a predefined object would override any "inner" tooltips, rather than become a race condition for which is displayed. And these variables, as implemented, would render identical spans, so I can apply the same CSS to all.

And while probably possible to correct through CSS (not sure, I am new here), I would expect this to be doable through the rendered fragment feature.

**Screenshots**
![image](https://user-images.githubusercontent.com/21204953/145474179-a0494539-efe2-4887-b4a5-5693436c1396.png)

**Comment by iamromeo** [comment]
This has more chances of being related to the tooltip than the actual symbol. It couldn't be replicated by just adding the symbol. 

Can I please have the full and exact text of that fragment please.

**Comment by Kordishal** [comment]
I cannot make this happen either. I think I rebuilt the example. It does create double tooltips which are sometimes showing both and sometimes just one depending on where I hover.

**Comment by iamromeo** [comment]
@Kordishal are you sure it's a **rendered fragment** type can you show me what you see or give me the code to replicate it ?

**Comment by Frumpski** [comment]
This variable:
![image](https://user-images.githubusercontent.com/21204953/147184411-f98b6028-a92a-4e85-93b2-fc56551c0707.png)

In a new article containing only this:
[var:note-bonusaction]

Shows this in Edge/Chrome:
![image](https://user-images.githubusercontent.com/21204953/147184802-3f00d137-5549-4cd1-8972-1c65f094281f.png)

**Comment by Frumpski** [comment]
Sorry, I see I'd copied the variable text to here already. Just hoped a shorter example would be less confusing overall.

**Comment by Kordishal** [comment]
That is a link variable. You should not be using that. It does indeed break. Switch to a rendered fragment variable (all the other variables you have made are rendered fragments).
