### ISSUE TITLE
Current date not readable on Terror of the Deep theme.

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#748]
**World Anvil Username**: SoulLink

**Feature**: Terror of The Deep Theme

**Describe the Issue**
The current date below the icon is not readable on the Terror of the Deep theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/14262536/145575573-2b6db35e-3c08-4f47-8f12-499449871ada.png)

**Comment by iamromeo** [comment]
Thank you - I will address promptly
