### ISSUE TITLE
Multiple notifications for the same comment

### ISSUE THREAD

**Issue by Naeliner** [worldanvil/worldanvil-bug-tracker#749]
**World Anvil Username**: Naelin

**World / Campaign / RPG Character / Manuscript Title**: Symbols of Power

**Feature**: Notifications / Commenting

**Related URLS**: https://www.worldanvil.com/w/tierras-magicas-naelin/a/sebastian-person (link to one of the articles that triggered the issue)

**Describe the Issue**
Earlier today I received 4 notifications about a singular comment on an article. I took it as some mistake from the author of the comment and ignored it. But now I have received 3 and 2 notifications for other two comments. In all three cases, there is only one comment per person on the article

**To Reproduce**
1. Leave a comment on an article
2. Check the notifications of the owner of the article
3. (This issue is NOT happening consistently, I don't know the trigger)

**Screenshots**
![image](https://user-images.githubusercontent.com/86533873/145623133-68676802-9549-4fb1-b011-3d0bfc976e56.png)
![image](https://user-images.githubusercontent.com/86533873/145623233-66539ea1-f359-43be-b4f1-e507bb23c5b7.png)

**Comment by Kordishal** [comment]
Have you asked them if they deleted comments because of rewriting them? You'd get a new notification for each creation, but no notification.

Otherwise I don't see how this could happen.

**Comment by Naeliner** [comment]
I have asked the people that triggered these notifications, here are the responses.
Only Krostatina had trouble posting, their comment disappeared after triggering the first notification (I can't see it either), the rest posted normally:

![image](https://user-images.githubusercontent.com/86533873/145728362-28183d45-d9ca-46f4-9922-1c707bb95ea5.png)
![image](https://user-images.githubusercontent.com/86533873/145728458-dfd0f7e9-0055-4f11-b78d-7a3ea0df3bbd.png)
![image](https://user-images.githubusercontent.com/86533873/145728590-cedcae6a-f253-4ae8-a5d6-f17487f45bed.png)
![image](https://user-images.githubusercontent.com/86533873/145728602-6090b9f1-4435-4822-bce7-39925d885aa4.png)

**Comment by iamromeo** [comment]
Hello there, I had no other reports of this or a way to replicate it. At this point I can consider it an odd fluke. 
If that happens again, please reply on this message. 
Out of curiosity was it all for the same article?

**Comment by Naeliner** [comment]
Hi Dimitris,

It was for two different articles.
It has not happened again since so I guess it was indeed an odd fluke.
