### ISSUE TITLE
Previewer Interactions Open Artemis On Ctrl Push

### ISSUE THREAD

**Issue by RiverFang13** [worldanvil/worldanvil-bug-tracker#75]
**World Anvil Username**: RiverFang

**World / Campaign / RPG Character / Manuscript Title**: Isekai

**Feature**: Previewer & Artemis

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Once the Previewer has been opened and an article selected, moving the Previewer or any other interaction with the Previewer will then cause Artemis to open upon pressing Control after moving to work outside of the Previewer.

**To Reproduce**
1. Open Previewer
2. Interact with Previewer (move window, search article, open article)
3. Push Control
4. Artemis opens

**Expected behavior**
Artemis opens on ctrl+enter as listed in the tips and does not open on a single ctrl press while Previewer is open.

**Comment by Xuroth** [comment]
Marked as complete as no longer able to reproduce. Please do a "hard refresh" (`ctrl`+`F5`) to ensure issue is resolved. Closing issue unless additional support is needed. Thanks for your patience!
