### ISSUE TITLE
Request for 24XX RPG system to be added

### ISSUE THREAD

**Issue by POCGamer** [worldanvil/worldanvil-bug-tracker#750]
Hello, 
I'm requesting Jason Tocci's excellent 24XX system be added to the World Anvil roster of the games. 

**Full Name (RPG SYSTEM)**: 24XX
**List Name** (Name under which it should be listed on World Anvil): 24XX
**World Anvil Username**: POCGamer

**Website**: https://jasontocci.itch.io/24xx 

**Logo Image Link**: nil

**Logo Usage Terms (URL)**: nil

Thank you, 

POCGamer

**Comment by iamromeo** [comment]
Hey @POCGamer! I hope you are doing well!
I have added 24XX in the list of games for you
