### ISSUE TITLE
Inconsistent arrows in the Advanced Tools & Options menu

### ISSUE THREAD

**Issue by Rosaa-xd** [worldanvil/worldanvil-bug-tracker#751]
**World Anvil Username**: Sh4d0wPh03n1x

**World / Campaign / RPG Character / Manuscript Title**: Hesli

**Feature**: Write Article

**Related URLS** (To public & visible pages add screenshots otherwise):
N/A

**Describe the Issue**
When I open the Advanced Tools & Options menu when writing an article, the menu arrows are inconsistent. Some point upwards when the menu is closed, others do it the other way around.

**To Reproduce**
1. Create an article or open an existing one in the editor
2. Select Advanced Tools & Options

**Expected behavior**
Consistency with the menu arrows. :)

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
<img width="363" alt="Screenshot 2021-12-13 at 09 00 18" src="https://user-images.githubusercontent.com/11375483/145775156-8a60d387-8fd8-453c-8ee5-a854c579ef72.png">
<img width="368" alt="Screenshot 2021-12-13 at 09 00 40" src="https://user-images.githubusercontent.com/11375483/145775161-7b17bb1b-f07b-44ca-9fb6-eccff55241db.png">

**Comment by GorkamWorka** [comment]
fixed, will deploy soon
