### ISSUE TITLE
P.O.V. character field in Manuscripts only gives one name and it isn't one of mine.

### ISSUE THREAD

**Issue by Gritchu** [worldanvil/worldanvil-bug-tracker#753]
**World Anvil Username**:
Gritchu

**World / Campaign / RPG Character / Manuscript Title**:
Wells of Power

**Feature**: 
P.O.V. Character field

**Related URLS** (To public & visible pages add screenshots otherwise):
See screenshot

**Describe the Issue**
While writing my story I thought I'd add my P.O.V. characters. In this section of my story, the character is named Evan Gadaway. When I type Evan into the text field the name Evan Hesher appears. I've never made a character with that name, nor is it listed anywhere on Evan Gadaway's character article or any other. I've tried searching for that name and it doesn't give results. I then tried my other characters' names in the P.O.V. field and none of them appear. The only name that has ever appeared for me is for a character I didn't create. Evan Hesher.

I've also cleared my cookies/cache/history etc... and this issue still exists. I even tried a completely new web browser on my computer (one I had never logged into WA before on). Still has this problem.

**To Reproduce**
1. Go to the Manuscript Page
2. Click on a section
3. Scroll down to P.O.V Character on the right-hand column
4. See error: Type in names of characters I've created, nothing appears. Type Evan and this other name appear.

**Expected behavior**
I would expect that when I attempt to add a character to this P.O.V. Character field, it would list all of my characters and not a character I didn't create.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by dragging & drop into this window!
![image](https://user-images.githubusercontent.com/79152593/145841049-fd33be3d-2e75-4830-9605-a724d8d02cee.png)

**Comment by Kordishal** [comment]
Hi, I cannot reproduce this. The names popping up when I search are all of the world that the manuscript is attached to. And as far as I can tell they are complete.

This sounds like your manuscript is somehow wired to the wrong world. As all of your stuff is private I can't check if this is the case.

The linked world is displayed on the main config page of the manuscript below the main title. Check if this is correct.
![image](https://user-images.githubusercontent.com/14262536/145846834-a9c146e4-61d4-443a-83e4-302909165136.png)

**Comment by Gritchu** [comment]
Thanks Jonas, you’re absolutely correct. The manuscript was linked to the wrong world. Is there a way I can change which world it is linked to, or will I need to create a new manuscript and copy everything over? I’ve only just begun, so it wouldn’t be difficult to do that if I needed.

Greg

**Comment by Kordishal** [comment]
You will have to create a new manuscript, there is currently no way to change the world of a manuscript.
