### ISSUE TITLE
Manuscript Label text doesn't show up correctly against label colors

### ISSUE THREAD

**Issue by Gritchu** [worldanvil/worldanvil-bug-tracker#754]
**World Anvil Username**:
Gritchu

**World / Campaign / RPG Character / Manuscript Title**:
Wells of Power

**Feature**: 
The Label's feature in the Manuscript area.

**Related URLS** (To public & visible pages add screenshots otherwise):
See Screenshots

**Describe the Issue**
A clear and concise description of what the issue is.
I like the idea of using labels to help me track storylines. However, when I select a label, the font is nearly impossible to read against light colors. I saw that the background colors can be changed, which is great, however, I feel the text also needs to be changeable. If I enter a dark background color, I should be able to make the text over top light, and with a light background color, as in the screen caps below, it should have dark text.

**To Reproduce**
1. Go to a manuscript
2. Click on a section
3. Assign a label color
4. See how impossibly difficult it is to read.

**Expected behavior**
The text overtop of the labels should change, or be editable, so that it can be easily read.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/79152593/145842731-63c34d33-d8e4-485d-9006-d318e330db7c.png)
![image](https://user-images.githubusercontent.com/79152593/145842825-98b94453-4ab4-4ace-90af-0d4cc4b991e8.png)
![image](https://user-images.githubusercontent.com/79152593/145843080-27f3aa4b-a278-4e38-9cac-02425296c4a1.png)

**Comment by Kordishal** [comment]
You can change these colours in the settings as well. Though likely you'll have to change the text colour via the World CSS to make it work.

A collection of colours that work better.
![image](https://user-images.githubusercontent.com/14262536/145851466-4b3f4b48-abcd-4355-977d-c60f635810fc.png)
![image](https://user-images.githubusercontent.com/14262536/145851517-e1f91d62-9423-454b-98f3-c9743dc0a3f6.png)

@ Dimitris: A setting for the text colour would be helpful to make it really work for any theme and use case.
![image](https://user-images.githubusercontent.com/14262536/145850309-989be0c9-45d8-42c1-aa73-7fc654d9207f.png)


And I cannot read the "no label" placeholder on the chapter overview.
![image](https://user-images.githubusercontent.com/14262536/145851617-1ea60bad-76dd-4db5-b318-5b9abbcb6dbf.png)

**Comment by iamromeo** [comment]
This will be addressed on Manuscripts v.2.
