### ISSUE TITLE
"Secret information" field in historical entries doesn't support BBCode

### ISSUE THREAD

**Issue by OndoAlvelle** [worldanvil/worldanvil-bug-tracker#756]
**World Anvil Username**: Ondo

**Feature**: Historical entries

**Related URLS** https://www.worldanvil.com/world/timeline/history/new

**Describe the Issue**
The "secret information" field (under advanced options) doesn't support BBCode. Any BBCode tags added there are displayed in presentation as if they were inside [noparse] [/noparse] tags.

**To Reproduce**
1. Create historical entries
2. Additional options -> secret information -> type anything with BBCode tags
3. See result in presentation

**Expected behavior**
The field should support BBCode as any other long-form field. If the field is supposed to work like an article's scrapbook, it should be removed from presentation (and make it clear that BBCode is not supported).

**Comment by iamromeo** [comment]
All fixed by @GorkamWorka
