### ISSUE TITLE
Save does not store formatting / text added via mouse clicks

### ISSUE THREAD

**Issue by CyricTheDark** [worldanvil/worldanvil-bug-tracker#757]
**World Anvil Username**: Cyric

**World / Campaign / RPG Character / Manuscript Title**: Valenor

**Feature**: Text Editor

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/valenor-cyric

**Describe the Issue**
Sometimes the text editor don't save the latest changes. i verified thet it happen in 2 situation; when i click something on the toolbar as my last action, and if i use some autocomplete to select a link (@).
In all situation if i save directly the article the save is not complete (the change is not saved), if i write something later (even a space) the save is done correctly.

**To Reproduce**
1. Go to 'text editor'
2. 'write something, select the writing and apply a "P" formatting'
3. Click on  'save',
4. Click on "view",
5. See error, the P formatting is missing
6. Click on "Edit"
7. See error, the "[P] [/P]" is missing.

**Expected behavior**
to edit the code normally

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![2021-12-16](https://user-images.githubusercontent.com/95873838/146372424-cf95c72f-832a-4a5f-bae5-c5ad2f111ccd.png)
![2021-12-16 (1)](https://user-images.githubusercontent.com/95873838/146372427-c21182ee-5f45-4aa8-b04b-d8704fa873e6.png)

**Comment by Kordishal** [comment]
The auto-save is only triggered by keyboard key presses. The save button triggers that same mechanism and does not register any changes added via mouse.

This might change in the future but is not considered a bug.
