### ISSUE TITLE
All Icons missing from World Anvil when using latest Microsoft Edge Browser based on Chromium

### ISSUE THREAD

**Issue by zeepee021** [worldanvil/worldanvil-bug-tracker#758]
**World Anvil Username**: Zeepee

**World / Campaign / RPG Character / Manuscript Title**: Tales of the Forgotten Realms

**Feature**:  All

**Related URLS** (To public & visible pages add screenshots otherwise):
Nothing is Public

**Describe the Issue**
A clear and concise description of what the issue is.

Allmost all GUI icons are not loaded, when using World Anvil, making it really difficult to use.

This can be due to a bad Edge update from Microsoft, but in case it is not, I wanted to let you know, in hope to get it fixed asap.
I have been using both the old Edge browser and later the new cromium based Edge browser since I started my Grandmaster subscription on World Anvil years ago. I have never encountered any browser specific issues before. 

I can't reproduce the problem on Firefox (same machine)

**To Reproduce**
Log on to World Anvil using Microsoft Edge browser and start browsing the site.

**Expected behavior**
See the GUI as normal

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

Running latest Microsoft Edge version on a Windows 11 machine - Have always worked perfectly until last night.

![WorldAnvil - Missing Icons](https://user-images.githubusercontent.com/96253588/146408896-84de4c94-9305-4c5b-ab33-8bd5712ab1bc.png)

Same Screen opened with Firefox on the same machine:

![WorldAnvil - Missing Icons - Firefox](https://user-images.githubusercontent.com/96253588/146409394-5c1e192c-3dfe-424b-a271-473e6de28128.png)

**Comment by Kordishal** [comment]
There was an issue with Fontawesome yesterday. This issue may still be cached in your Edge browser. Please try to reload the cache (should be CTRL+F5). 

if this doesn't resolve the issue comment here.
