### ISSUE TITLE
Toggle buttons and script not appearing

### ISSUE THREAD

**Issue by Daerith** [worldanvil/worldanvil-bug-tracker#759]
**World Anvil Username**: Daerith

**World / Campaign / RPG Character / Manuscript Title**: Skyre

**Feature**: Toggle buttons and scripts

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is. 
For the last two days, toggle buttons will appear but with no graphics and there is absolutely no script for options of to edit, view, etc. Across all worlds, in every format. 

**To Reproduce**

**Expected behavior**
Fix it? This seems like a website-wide problem , but I'm not sure. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
<img width="2048" alt="World Anvil Bug" src="https://user-images.githubusercontent.com/96257532/146421714-dec3a4e7-8827-4bcb-89a1-0dab9ed1d31b.png">

**Comment by Kordishal** [comment]
There is / was an issue with Fontawesome which provides these icons. Nothing on World Anvil's side. Try CTRL +F5 to refresh the cache as the issue has been resolved in general.
