### ISSUE TITLE
Adding BattleTech RPG Character Sheet to Character, Makes Character Unaccessable (404)

### ISSUE THREAD

**Issue by CodeMonkeyWantsBanana** [worldanvil/worldanvil-bug-tracker#76]
**World Anvil Username**:
Troy Holt

**World / Campaign / RPG Character / Manuscript Title**:
Troy and Temp are the borked characters, Temp3 works fine

**Feature**: 
BattleTech RPG Character Sheet

**Related URLS** (To public & visible pages add screenshots otherwise):
These URLs should be characters, but display 404 errors:
https://www.worldanvil.com/hero/44eaad52-ff56-4f0d-abff-4ce04fe9757e
https://www.worldanvil.com/hero/7d18f7d6-84aa-4c33-9347-ab718e33a065

**Describe the Issue**
Creating a BattleTech RPG character sheet makes the character unopenable/unviewable.

**To Reproduce**
1. Create a new character. Select Battletech RPG as the RPG system. Save. At this point, the character functions as intended. No problems.
2. Edit character. 
3. Press "Create/Choose character sheet"
4. On the next page, select "BattleTech RPG 3e (Battletech RPG). Press "Choose and edit this sheet".
5. At this point, whether you enter a name on the sheet and save (which appears to be the minimum), or you navigate away without saving, you will be sent to a 404 error when you try to display the character again.

**Expected behavior**
I expected to fill in some of the sheet, enough to get started, and save the sheet. Then I should be able to return to the character via one of the character selection widgets.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/80868624/111567985-4d6fdf00-8776-11eb-9392-dea3c0876410.png)
According to the green block, I was successful in saving the character sheet. However, if I press the view "View Sheet" button, I'm off to a 404 screen.

**Comment by iamromeo** [comment]
@CodeMonkeyWantsBanana sheets are a community project therefore not supported here. BUT having said that the Creator is here. As I mention below this is probably an issue with a string value being put where a number was expected. 

===
@Tillerz the error I get is: 
Warning: A non-numeric value encountered
I am guessing @CodeMonkeyWantsBanana  probably put a string where a numeric value should be in. place.

**Comment by Tillerz** [comment]
Having a look.

**Comment by Tillerz** [comment]
Fixed. :)

**Comment by CodeMonkeyWantsBanana** [comment]
Outstanding! Thanks Tillerz and Dimitris!
