### ISSUE TITLE
Removal of an article from WE contest is not permanent - I've removed this article at least 4 times. :(

### ISSUE THREAD

**Issue by shyredfox** [worldanvil/worldanvil-bug-tracker#760]
**World Anvil Username**: shyredfox

**World / Campaign / RPG Character / Manuscript Title**: vssCollab

**Feature**: Removal of an article from WE contest 

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/vsscollab/a/vsscollab-challenge-article

**Describe the Issue**
I keep removing the above article and it keeps coming back into my list of articles. It's not a worldbuilding article, its a group challenge page. so I keep removing it. But my patience for this is gone. I'm reporting it and I'm not removing it from my WE list anymore. I have tried, valiantly. Pretty please, fix this. It will drive people crazy.

**To Reproduce**
1. Go to https://www.worldanvil.com/w/vsscollab/a/vsscollab-challenge-article and edit it.
2. Go down to the WE stuff and click delete
3. Click on the verification that yes I really want to delete it.
4. I edited the vssCollab article again and ...
5. POOF, its back listed in my WE articles. (*internal screaming*)

**Expected behavior**
https://www.worldanvil.com/community/challenge/worldember-2021/homepage/shyredfox should not show the article again. But I've seen it 4 times. 

I hope the descriptions help. Please let me know if you need more details.

**Screenshots**
![Screenshot_18](https://user-images.githubusercontent.com/59369948/146603844-d8b9e2e3-4189-4836-a1a1-3a58e210a34b.png)
![Screenshot_21](https://user-images.githubusercontent.com/59369948/146603846-21b8d06d-3be3-42bc-8be7-42a1d6c74483.png)
![Screenshot_20](https://user-images.githubusercontent.com/59369948/146603848-19702994-7f6d-4f2a-8651-ed75e07fd372.png)
![Screenshot_19](https://user-images.githubusercontent.com/59369948/146603850-58bfd5d2-bc72-433f-b32e-1a89841b65fd.png)

**Comment by shyredfox** [comment]
I chatted with friends on a stream: LordGalakrond and KahunatheElder have also had this problem.

**Comment by iamromeo** [comment]
Articles were never able to be removed. This is not a bug. the functionality only exists to remove articles from Special categories. 
You can keep an article a draft or private for the duration if you do not wish it to be counted. :)

**Comment by shyredfox** [comment]
Alas I need the article public for a story challenge. Thanks for the clarification though. Would it be possible to clarify it on the interface since I wasn't the only one confused?
