### ISSUE TITLE
Combined Notebooks, missing pages

### ISSUE THREAD

**Issue by xm-ml** [worldanvil/worldanvil-bug-tracker#761]
**World Anvil Username**: xmml

**World / Campaign / RPG Character / Manuscript Title**: "My First Notebook"

**Feature**: Notebook

**Related URLS** (To public & visible pages add screenshots otherwise): (screenshot)

**Describe the Issue**
A while ago, I had created two different notebooks. One was called "My First Notebook", and I don't remember the name of the second one. The second one had multiple sections, each with a few pages. The first one had multiple sections with one page each. I hadn't used World Anvil for a little while, so when I logged back in and tried opening the notebook, all the sections were combined under "My First Notebook." This would have been fine, but all of the pages were deleted. There is only one page still there, and I can't remember if I added it after the fact.

**To Reproduce**
Steps to reproduce the behavior: I have no idea

**Expected behavior**
I expected that each section would have saved my pages, or that reloading might restore them. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![tempwa1](https://user-images.githubusercontent.com/96350398/146651461-7895edcb-e243-416b-9d61-a24f0620b344.PNG)
![tempwa2](https://user-images.githubusercontent.com/96350398/146651469-4e4e702a-80ff-43e2-b448-ea6f2d5d93e3.PNG)

**Comment by iamromeo** [comment]
That is rather odd, we never got a report for something like that and there is literally no functionality that could have done that on World Anvil. When you search for those notes on the SEARCH of your world's Dashboard can you see them?

**Comment by iamromeo** [comment]
Hey Xavier was that resolved? I haven't heard back from you in over a week

**Comment by xm-ml** [comment]
Sorry, I forgot to respond. I tried the search feature and it didn't come
up.
The notes are probably gone for good. Thanks for trying to help though.
