### ISSUE TITLE
Can't Change World's Name

### ISSUE THREAD

**Issue by buckwell0** [worldanvil/worldanvil-bug-tracker#762]
**World Anvil Username**:
buckwelles

**World / Campaign / RPG Character / Manuscript Title**:
End Of Everything (World)

**Feature**: 
World Configuration

**Related URLS** (To public & visible pages add screenshots otherwise):

![worldname](https://user-images.githubusercontent.com/84354328/146680536-c0793073-7a77-4880-bf34-9e0d346bf7bc.png)

**Describe the Issue**
I can't change name of the my world, it's giving 404

**To Reproduce**
change the name & click the save button

**Comment by Kordishal** [comment]
What is the new name you want to have? Did you have a world with that name before?

**Comment by iamromeo** [comment]
A World Called end of everything already exists into your account. You cannot have two worlds with the exact same name :)

**Comment by buckwell0** [comment]
Actually, I was trying to name it as 'Her Şeyin Sonu'

I have a different world that has the name 'Her Seyin Sonu' But the character S & Ş are different. So, it is weird to can't name it as 'Her Şeyin Sonu'
