### ISSUE TITLE
Sidebar of ethnicity template display at the bottom.

### ISSUE THREAD

**Issue by RoguesNtheHouse** [worldanvil/worldanvil-bug-tracker#763]
RoguesNTheHouse

RUNE

**Problem:**  All articles I paste in the Sidebar of my ethnicity articles ends up in the body of the article.

**What I expected:**  I expected what I posted into the sidebar to show up in the sidebar.

![image](https://user-images.githubusercontent.com/96397659/146696018-0c1af686-c018-4926-8e88-bd94d7a19744.png)

![image](https://user-images.githubusercontent.com/96397659/146696099-0559210e-e14a-402c-ac41-95a8c9cebd3b.png)

**Comment by iamromeo** [comment]
I am really sorry but I cannot replicate this. It looks VERY much like an unclosed BBcode tag on your main content though :) 
I cannot confirm without an actual link to the article but I cannot reproduce it.
