### ISSUE TITLE
Military conflict footnotes are displayed in a different place than in other article templates.

### ISSUE THREAD

**Issue by RoguesNtheHouse** [worldanvil/worldanvil-bug-tracker#764]
RoguesNTheHouse

RUNE

**Problem:**  All footnotes in my military conflict articles end up wonky.  If I add Belligerents it automatically adds the footnote to the sidebar.  Also, the gold bar that goes across the bottom of the foot note (in both places) is indented to the right.  The third picture is a proper one and what I expect.

**What I expected:**  I expected the footnote to be in the proper place as it is in other articles

![image](https://user-images.githubusercontent.com/96397659/146707558-a85d7dce-fba5-45d3-b8a9-b95d142cccd8.png)
![image](https://user-images.githubusercontent.com/96397659/146707601-0571f9eb-53e7-4793-8a87-b649fad0a6e2.png)

![image](https://user-images.githubusercontent.com/96397659/146696403-5faf58c4-c147-4463-a728-e3ced4336f80.png)

**Comment by GorkamWorka** [comment]
Fixed, will be deployed soon

**Comment by Kordishal** [comment]
The footnotes are now being duplicated:
https://www.worldanvil.com/w/breaking-anvil-soullink/a/footnote-test-militaryConflict

**Comment by GorkamWorka** [comment]
https://www.worldanvil.com/w/meta-gorkamworka/a/a-military-conflict-test-militaryConflict
