### ISSUE TITLE
Character template TWIG download is not up to date and misses some variables.

### ISSUE THREAD

**Issue by DragonKnightAdam** [worldanvil/worldanvil-bug-tracker#765]
**World Anvil Username**:
DragonKnightAdam
**World / Campaign / RPG Character / Manuscript Title**:
Shattered Realms
**Feature**: 
TWIG coding for persons/deities
**Related URLS** (To public & visible pages add screenshots otherwise):
https://worldanvil-static.sfo2.cdn.digitaloceanspaces.com/templates/base-article-templates-aug-21.zip
**Describe the Issue**
A clear and concise description of what the issue is.

**To Reproduce**
1. Go to: (https://worldanvil-static.sfo2.cdn.digitaloceanspaces.com/templates/base-article-templates-aug-21.zip)
2. Click on: take persons TWIG code
3. Scroll down to Deities
4. See missing code

**Expected behavior**
missing code so does not appear in final article

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Considering the massive upcoming updates on the templates (that will probably will cover this issue to the point you won't be needing it anymore) I will close this FOR NOW - the current spec, will blow your mind. If there is something specific you need please let me know of Discord and I can give you the twig part
