### ISSUE TITLE
Family Tree Issue

### ISSUE THREAD

**Issue by rjclar2933** [worldanvil/worldanvil-bug-tracker#767]
**World Anvil Username**: Whyse

**World / Campaign / RPG Character / Manuscript Title**: Tythol

**Feature**: Family Tree

**Related URLS** (To public & visible pages add screenshots otherwise): 
https://www.worldanvil.com/w/tythol-whyse/a/purphoros2C-god-of-the-forge-person
https://www.worldanvil.com/w/tythol-whyse/a/dimiour2C-god-of-technology-person
https://www.worldanvil.com/w/tythol-whyse/a/fysi2C-goddess-of-nature-person
https://www.worldanvil.com/w/tythol-whyse/a/agios2C-the-godmother-person-1

**Describe the Issue**
Was creating a family tree of the gods in my world. Some of the related gods have children with one another. The god Purphoros is the child of the gods Dimiour and Fysi, who are related. When I select the grandparent (Agios), it shows two of Purphoros and does not show the connection of Dimiour and Fysi. When I select siblings of Dimiour and Fysi, it does not show Purphoros at all. When I select Dimiour or Fysi, it shows the connection of the two, but it also shows a copy of them on the family tree. When I select Purphoros, it shows the connection of Dimiour and Fysi, but it also shows two sets of the same grandparents for them.

**To Reproduce**
1. Create at least three character articles.
2. Create a 4th character article and set it to the parent of the other three.
3. Have two of of the three children be parents of a 5th character article.
4. Create a family tree link for each character.
2. See error

**Expected behavior**
The family tree should only show one version of Purphoros and should be visible when selecting other members of the family tree. The connection between the parents should also always be visible. When selecting Purphoros, it should not show two sets of the same grandparents. It should not show copies of the parents on the family tree.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![family_tree_6](https://user-images.githubusercontent.com/61369446/146935344-bfaf00a1-8c54-43d4-a58e-327c18504322.PNG)
![family_tree_5](https://user-images.githubusercontent.com/61369446/146935348-4b06543c-37c0-49f9-b38a-163bcc728160.PNG)
![family_tree_4](https://user-images.githubusercontent.com/61369446/146935350-1381fc3b-a62c-48bd-bc8a-c257f0e3c0f5.PNG)
![family_tree_3](https://user-images.githubusercontent.com/61369446/146935352-c0502732-a31a-4e50-b55d-5095d4ed86ae.PNG)
![family_tree_2](https://user-images.githubusercontent.com/61369446/146935353-1f907a6d-f76a-4a81-80c2-56955d89cc62.PNG)
![family_tree](https://user-images.githubusercontent.com/61369446/146935356-4d9fa0ce-9761-4d5c-be34-f896c5b73f24.PNG)

**Comment by Xuroth** [comment]
Hello! The automatic family trees are very, very simplistic in how they handle relations. In this case, the script is seeing one relation (sibling) in certain situations, and "spouses" in others, which the script doesn't know how to handle. This is likely the source of the trouble. Sadly, the auto-tree isn't able to determine this, and a massive rewrite would be needed.

We do have requests for a "manual" mode, similar to Content Trees for Grandmasters+, that let you specify what each "node" displays. We're working through a large backlog, so in the mean time, Content Trees may be the best solution/work-around until then, though these custom Content Trees are available to GM+ tiers.

I'm going to close this for now, but rest assured that we'll take this into consideration when the next version of Family Trees is up for development!
