### ISSUE TITLE
Cannot invite characters to campaign

### ISSUE THREAD

**Issue by Demothrin** [worldanvil/worldanvil-bug-tracker#768]
**Demothrin**:

**Golarion/ Age of Ashes**:

**Invite Character to Campaign**: 

**https://www.worldanvil.com/heroes/campaign/f3e3e3c2-a378-4c61-b24c-abc9ec49022a/character/46c71fea-a30e-4f2c-9dab-e278b9d744d1/grant-access/RYPA-oUDu-6Hd0wL/)** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I have tried to invite my wife and also tried one of my own characters to my age of ashes campaign when we click the invite link it take us to character selection, once we choose our character it takes us to a 404 error page. (I read that if you already have an article with a character of the same name it could cause this issue but i have checked all my articles and I have no characters with these names)

**To Reproduce**
1. Click on campaign invite link
2. Choose Character or make new character to join campaign
3. see error

**Expected behavior**
A new character would be added to the campaign.

**Comment by iamromeo** [comment]
Hey @Demothrin I can solve this very quickly if I can have access to the account that is trying to get into the campaign. 
Can you please ask your (I bet) amazing wife to send an email to hello@worldanvil.com with their username and a new temporary password so I can try to simulate the error they are getting and see what the issue is?

**Comment by iamromeo** [comment]
Also it seems that this code does not match this campaign. Did you by any chance reset the code?

**Comment by Demothrin** [comment]
> Also it seems that this code does not match this campaign. Did you by any chance reset the code?

Yes, sorry, I was trying some more troubleshooting.
Do you want the invite url, the 404 error message url or both?

there is the new code I randomly got a new character to join by creating them through the link where it asks if you want to join with an existing character or new character but when i tried to do this again it didnt work

Ill get my (definitely amazing) wife to send the account details through right away.

**Comment by iamromeo** [comment]
Thank you! Can you send me the current inviation link so I can try to follow it?

**Comment by Demothrin** [comment]
http://www.worldanvil.com/epic/KFrfNH8cUiE5uPUsxSxQNfIeqX8Y9D/join/6fQR-1JkP-7AGOVL

**Comment by iamromeo** [comment]
@Demothrin I have talked to your wife (or you) the username/password you've sent me did not work. I haven't heard back. Did you manage to resolve this issue?

**Comment by Demothrin** [comment]
sorry about that, she gets issues seeing replies in her inbox sometimes, she messaged you back we double checked the password and sent you hopefully the correct one this time XD hope you had a good holiday!

**Comment by Demothrin** [comment]
@iamromeo Hope you have a great holiday! I'm just checking up on things and thought i would give joining the campaign another go. Not sure what magic you managed to work but I got everyone in! Fingers crossed the issue doesn't creep up again in the future as I'm about to start up a 2nd running campaign but thank you for everything you looked into.
