### ISSUE TITLE
Private character articles info displayed on public timeline

### ISSUE THREAD

**Issue by juldum54** [worldanvil/worldanvil-bug-tracker#769]
**World Anvil Username**: juldum54

**World / Campaign / RPG Character / Manuscript Title**: Orcaïl

**Feature**: Timeline / timeline event

**Describe the Issue**
Privates related characters articles info (name, token) of a timeline event can be read from the timeline, even as an external/unauthenticated user.

**To Reproduce**
1. Create a new article of type 'Character' (in private).
2. Add a portrait/token to the character article.
2. Create a new timeline (in public).
3. Create a new historical event associated with the timeline (in public).
4. Link the historical event with the character article.
5. Go to the timeline history in private navigation or as any user who should not have access to the character article.
6. The name and the token of the character are displayed.

**Expected behavior**
Because the character article is private and that the user isn't part of the group who can access it, the article shouldn't be displayed on the timeline history on this event.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Complements**
To be more specific, the user can't access the character's articles, but they can see the names and token from the timeline. And this is not happening with the other related articles, only with the characters.

Private character article :
![Capture d’écran 2021-12-21 à 19 43 00](https://user-images.githubusercontent.com/40001456/147000841-2b0ace29-c59d-4798-ac96-9c33cf33cbd5.png)

Name and token displayed on the timeline as an unauthenticated user :
![Capture d’écran 2021-12-21 à 19 43 26](https://user-images.githubusercontent.com/40001456/147000873-e35b6255-0e93-4005-be05-acde21c05bc3.png)

**Comment by iamromeo** [comment]
All done - fixed this for organization as well - will be deploying today
