### ISSUE TITLE
Hey, Everytime I try to enter my dashboard, it kicks me out to the 404 error screen with the dragon.

### ISSUE THREAD

**Issue by Goddamd** [worldanvil/worldanvil-bug-tracker#772]
**World Anvil Username**: O.S.H.

**World / Campaign / RPG Character / Manuscript Title**: Universe CBDA-032-6

**Feature**: Dashboard not working

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/universe-cbda-032-6-osh

**Describe the Issue**
So far, every time I attempt to enter my dashboard to write a new article, the site takes me to the 404 error page with the dragon on it. From there, I can only go back to my home page. 

**To Reproduce**
1. Go to My world anvil home page.
2. Click on 'Dashboard'
4. See error 404

**Expected behavior**
I expected the site to take me to my dashboard where I can make new articles and get a general overview of my world.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by dragging & drop into this window!

**Comment by Xuroth** [comment]
Hello!

Thanks for reporting this! We had a slight hiccup and the Udans broke out... but we've wrangled them back up.

The issue should now be fixed, and the Dashboard should now be accessible again!
