### ISSUE TITLE
Im unable to use dashboard

### ISSUE THREAD

**Issue by Sayith-Dune** [worldanvil/worldanvil-bug-tracker#773]
**World Anvil Username**:    Sayith

**World / Campaign / RPG Character / Manuscript Title**:   Tath

**Feature**:    dashboard

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

I clicked on dashboard and it sent me to a 404 screen, I tried logging out and logging back in, even using a different browser, restarting my browser, it still takes me to the 404 screen

**Expected behavior**

I expected it to take me to the dashboard,

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image_2021_12_23T06_20_09_048Z](https://user-images.githubusercontent.com/96564098/147197541-d2f47c3a-920c-4a83-bf80-3e59162c472f.png)

**Comment by Xuroth** [comment]
Hello!

Thanks for reporting this! We had a slight hiccup and the Udans broke out... but we've wrangled them back up.

The issue should now be fixed, and the Dashboard should now be accessible again!
