### ISSUE TITLE
404 Error "thus you have reached the end of this world.

### ISSUE THREAD

**Issue by Birdiejett** [worldanvil/worldanvil-bug-tracker#774]
Birdiejett:

Worldbuilder: 

Dashboard: 

https://www.worldanvil.com/world/4b085903-417c-4499-ba46-4a9e37940bee/summary (To public & visible pages add screenshots otherwise):

Every time I try to go to the Dashboard for my world it comes up with a 404 page not found. 
![Web capture_23-12-2021_3402_www worldanvil com](https://user-images.githubusercontent.com/96569425/147212913-ea5b7d3e-c4dc-4253-b268-c2d684411042.jpeg)

**To Reproduce**
1. Go to a world page
2. Click on 'Dashboard'

Can the page be fixed so it doesn't have this error anymore? I don't know if this is an issue for others or just me.

**Comment by Xuroth** [comment]
Hello!

Thanks for reporting this! We had a slight hiccup and the Udans broke out... but we've wrangled them back up.

The issue should now be fixed, and the Dashboard should now be accessible again!
