### ISSUE TITLE
Dashboard glitch

### ISSUE THREAD

**Issue by MothHart** [worldanvil/worldanvil-bug-tracker#775]
**World Anvil Username**: J_Hart

**World / Campaign / RPG Character / Manuscript Title**: Orydis

**Feature**: Dashboard

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/world/4103576b-5df0-4c1e-a4ed-6d5fc89f016d/summary

**Describe the Issue**
A clear and concise description of what the issue is.  Dashboard link is leading to 404 page

**To Reproduce**
1. Go to any page
2. Click on Dashboard button
4. See error - goes to 404 page not found error

**Comment by Xuroth** [comment]
Hello!

Thanks for reporting this! We had a slight hiccup and the Udans broke out... but we've wrangled them back up.

The issue should now be fixed, and the Dashboard should now be accessible again!
