### ISSUE TITLE
Dashboard to World is unavailable

### ISSUE THREAD

**Issue by skyelight** [worldanvil/worldanvil-bug-tracker#776]
**Skyelyght**:

**World Dashboard**:

**Sashboard**: 

**[Related URLS](https://www.worldanvil.com/world/c353b0ae-9d23-4052-b3ed-0bbac4adec75/summary)** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Trying to access the dashboard to the world creation. Takes to a 404 Error about it not being there.

**To Reproduce**
1. Go to Homepage
2. Click on Dashboard
3. See error

**Expected behavior**
The dashboard to display with the world and the relevant articles to it.

**Screenshots**
![image](https://user-images.githubusercontent.com/53496970/147216449-e8d087b0-e8bf-4a93-b7f8-3fcd72a439f8.png)

**Comment by Xuroth** [comment]
Hello!

Thanks for reporting this! We had a slight hiccup and the Udans broke out... but we've wrangled them back up.

The issue should now be fixed, and the Dashboard should now be accessible again!
