### ISSUE TITLE
Word Goal cannot be Disabled

### ISSUE THREAD

**Issue by dumbassdruid** [worldanvil/worldanvil-bug-tracker#778]
**World Anvil Username**: dumbxssdruid

**World / Campaign / RPG Character / Manuscript Title**: World: Eithur

**Feature**: Word Goal

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.
The Word Goal cannot be disabled. Whenever I try to change it to 0 and save, it doesn't change the goal on the dashboard.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Advanced'
3. Set "Word Goal" to '0'

**Expected behavior**
I expected the word goal to disappear. It is distracting as a campaign manager.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Hello @dumbassdruid disabling a this will be a feature. It is most certainly not a bug :) 
If you wish for this to become a feature you can use the Features Suggestion board and ask the community what they think about it :) 

Happy holidays!

**Comment by dumbassdruid** [comment]
Is it not? It clearly states here "set to 0 to disable this".
[image: image.png]

---
Päikest!

Annabel Heindla
+372 503 3816
***@***.***


Kontakt Dimitris Romeo Havlidis ***@***.***>) kirjutas
kuupäeval N, 23. detsember 2021 kell 20:09:

**Comment by Kordishal** [comment]
Uploading an image via email doesn't work. I'll add it for you:

![image](https://user-images.githubusercontent.com/14262536/147361600-c9727985-4dd7-4385-a0eb-a4471e3a818c.png)
Your documentation on the field says that you can disable it, Dimitris :P

**Comment by dumbassdruid** [comment]
@iamromeo is the disabling feature incomplete, then?
