### ISSUE TITLE
404 Error on attempted deletion of Campaign/World

### ISSUE THREAD

**Issue by realkaleidio** [worldanvil/worldanvil-bug-tracker#779]
**World Anvil Username**: kaleidio

**World / Campaign / RPG Character / Manuscript Title**: The Isles of Gold / The Isles of Gold Campaign

**Feature**: Deleting World / Campaign

**Related URLS** : https://www.worldanvil.com/w/the-isles-of-gold-kaleidio

**Describe the Issue**
If I try to delete the world or campaign it simply gives me a 404 error and it remains. 

**To Reproduce**
I have not the slightest clue

**Expected behavior**
The world / campaign gets deleted.

**Comment by Kordishal** [comment]
The world can't be deleted when you still have a campaign. Which currently leads to a 404 page. But I can't see a campaign on your account? Can you link it? Or might it have been deleted anyway?

**Comment by realkaleidio** [comment]
I can't delete the campaign either. Not to mention that two worlds are connected to one campaign so I guess that also sucks? Since I need to delete the campaign one world I use is linked to to delete the world I don't actually want.

The whole campaign thing is really weird. I had a world without it and it was the same as my worlds that are linked to a campaign are, just less problematic. So I don't understand the necessities of campaigns just yet.
Either way, I do not know how to link to a campaign.

I don't think it's deleted, still showing up in my world anvil and I still can't delete the world.

**Comment by Kordishal** [comment]
A campaign can't be connected to two worlds. 

The campaign can be seen with the link from the following menu item:
![image](https://user-images.githubusercontent.com/14262536/147368087-2a6578e3-403d-46fc-bc72-857927b5abb0.png)

It can be private though

**Comment by realkaleidio** [comment]
Ah nope, true it just has nearly the same name so I confused it.

That's why I want to delete the old one I don't want, which I can't do, since I keep confusing them.
https://www.worldanvil.com/epic/Aw4SFS4ZCpCXZ6FkcXY7fe080Lf26J

**Comment by Kordishal** [comment]
Just to confirm:

When you now go to settings from that menu and do the DELETE action it goes to 404 and the campaign continues to exist? Even after you navigate back to the world?

![image](https://user-images.githubusercontent.com/14262536/147389690-149fc9cd-cf2d-452a-8fa3-8d0199429ce6.png)

**Comment by realkaleidio** [comment]
Yes, that's exactly what happens.
I click delete, it gives an error and it remains.

I have tried on 3+ different days, both campaign and world, it simply doesn't go away, just gives error and no matter where I navigate after the world's just still there.
The world exists, it doesn't go away.

I have tried on plenty different days and it's the only world/campaign this happens on far as I know.

**Comment by iamromeo** [comment]
Hey @realkaleidio that sounds like an account specific issue - can you please 
1. Change your password
2. Send an email to me at hello@worldanvil.com with your **username** and **password** and the **campaign you are trying to delete**?

**Comment by realkaleidio** [comment]
Well yeah I did that

**Comment by iamromeo** [comment]
I am really sorry I missed this reply - which email have you sent the information from? I cannot find the email

**Comment by iamromeo** [comment]
Today I have also fixed a similar bug that **might** have fixed this - can you try deleting it again?

**Comment by realkaleidio** [comment]
If you fixed something, you did not fix my problem.
Also I am not exactly keen on sharing my email on public bug tracking forms.

**Comment by iamromeo** [comment]
Thank you for the update. Can you resend the email you've sent me then please?
