### ISSUE TITLE
Statblock Eyeball Button Visible to All

### ISSUE THREAD

**Issue by daniadventures** [worldanvil/worldanvil-bug-tracker#78]
**World Anvil Username**: DaniAdventures

**World / Campaign / RPG Character / Manuscript Title**: To Do List Adventures

**Feature**: Statblocks

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/todolistadventures/a/intro-and-character-builder-article
and I've also seen it on others' sites.

**Describe the Issue**
When viewing the page, it displays the Eyeball in the top righthand corner of the statblock.  This can be clicked on, and also brings the user to a 404 page.

**To Reproduce**
1. Go to either of those links ( https://www.worldanvil.com/w/todolistadventures/a/intro-and-character-builder-article )
2. Look in upper right corner of the panel displayed; eyeball is visible.
3. Click Eyeball.
4. 404.

**Expected behavior**
No eyeball button?

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

![EyeballButton bug](https://user-images.githubusercontent.com/81049897/111886191-c9e70580-89a2-11eb-9e25-1f305800c44b.png)

**Comment by daniadventures** [comment]
I had ShyRedFox's site as a link, but she figured out a temporary CSS suppression so you won't see it on her page now :D

**Comment by shyredfox** [comment]
Out of curiosity. I see this was marked as “working as Intended”. I am confused. Why should ALL site viewers see the eyeball icon? I don’t think everyone should be able to try click to see my statblocks. It even shows in an Incognitio window (so it shows for non WA users too). :(
