### ISSUE TITLE
System request: Noctum

### ISSUE THREAD

**Issue by NilsCordes** [worldanvil/worldanvil-bug-tracker#780]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name (RPG SYSTEM)**: Noctum (it is a pretty fringe and old 2d10-system)
**List Name** (Name under which it should be listed on World Anvil): Noctum
**World Anvil Username**: NilsCordes

**Website**: https://index.rpg.net/display-entry.phtml?mainid=11825&editionid=13231 (Noctum no longer has its own webpage, the creator, Wicked World Games, can be reached here: https://www.facebook.com/Wicked-World-Games-11-204350396301638/)

**Logo Image Link**: https://www.rpg.net/pictures/show-pic.phtml?picid=14425

**Logo Usage Terms (URL)**: https://forum.rpg.net/index.php?help/terms/ (The game no longer has its own homepage)

**Comment by iamromeo** [comment]
Hey @NilsCordes the game is added to the list :)
