### ISSUE TITLE
Timelines-feature doesnt work right

### ISSUE THREAD

**Issue by FireDivision** [worldanvil/worldanvil-bug-tracker#781]
**World Anvil Username**: FireDivision

**World / Campaign / RPG Character / Manuscript Title**: Elentael

**Feature**: Timelines

**Related URLS**:

**Describe the Issue**
The timeline that im building doesnt adjust to what i try to enter into the separate sections of content. 
For one entry it has the right dates saved in the edit-frame but outside its completely random. 
When i try to place an entry between Era's, it either ends up under the wrong one or under 'orphan histories'.

**To Reproduce**
1. Go to 'Timelines'
2. Click on 'Add Era', create one
3. Enter and save a historical entry, enter the time between two era's.

**Expected behavior**
I hope to use the feature itself (as far as i can anyway) to properly and easily create a history.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/96658536/147388492-a24edc0c-17bf-4235-9e85-203bd2806032.png)
![image](https://user-images.githubusercontent.com/96658536/147388507-6c84d815-8177-4288-beeb-614e0ce03932.png)
(the Great War entry is supposed to be between the two upper era's and the Skism entry should have the dates 2047-2052

**Comment by Kordishal** [comment]
As far as I am aware, the feature works correctly. Usually, this means you have your Eras not setup correctly.

According to your images, the Peaceful times go from year negative infinite to 0. The Era AGW goes from year 9 - 2052. Which means that there is no Era for the years 1 - 8 shown.

The first event is correctly placed and translated to AGW. 2047 - 9 + 1 = 2039 and 2052 - 9 + 1 = 2044. I am guessing AGW has a starting date of 1.

The orphaned event does not display its actual date. But it means that its duration lands outside of any ERA.

Come by the Discord server for quicker help with the use of World Anvil in the channel #help.

https://www.worldanvil.com/discord
