### ISSUE TITLE
Sidebar content panel is visible in Plot Template even without content

### ISSUE THREAD

**Issue by timursobolev** [worldanvil/worldanvil-bug-tracker#782]
**World Anvil Username**: pinkflumph

**World / Campaign / RPG Character / Manuscript Title**: Test

**Feature**: sidebar 

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/test-pinkflumph/a/test--plot

**Describe the Issue**
The sidebar main content section (white rounded background, i.e. "bubble") is visible in some templates (specifically, the plot template) even when there is no content. 

**To Reproduce**
1. Create a new article with a plot template and the default theme
2. See white bubble in the sidebar

**Expected behavior**
The bubble should disappear when there is no content in the sidebar (this happens in the generic template)

**Screenshots**
Example without any content:
![2021-12-25_20-23-46](https://user-images.githubusercontent.com/60177501/147400102-747a7939-d8f6-4218-aea0-a9efe87a42f2.png)
Example with content in a different section (the top section)
![2021-12-25_21-47-24](https://user-images.githubusercontent.com/60177501/147400142-3beb4abb-8edc-4505-810b-d450a7ddf6b3.png)

**Comment by iamromeo** [comment]
Fixed
