### ISSUE TITLE
Built-in maps and containers

### ISSUE THREAD

**Issue by timursobolev** [worldanvil/worldanvil-bug-tracker#783]
**World Anvil Username**: pinkflumph

**World / Campaign / RPG Character / Manuscript Title**: Test

**Feature**: Containers, built-in maps

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/test-pinkflumph/a/test-2-article

**Describe the Issue**
The built-in maps interact... strangely with other containers. See next section

**To Reproduce**
1. Create custom container
2. Put built-in map within the custom container in an article
3. Try to switch between the visual editor and the source editor several times
4. See many new span's appear in the text and the container become red
5. Be confused

**Expected behavior**
Everything up to step 3.

**Screenshots**
Adding map to container:
![2021-12-25_23-22-01](https://user-images.githubusercontent.com/60177501/147401655-f4428afb-87f6-47f0-97eb-65517ce51ffd.png)
Switching to visual editor (notice how container is now red):
![2021-12-25_23-22-14](https://user-images.githubusercontent.com/60177501/147401656-da4b290e-106d-4f1b-95db-7e7b4b352c64.png)
Switching back to source (extra span's have shown up):
![2021-12-25_23-22-29](https://user-images.githubusercontent.com/60177501/147401659-72250b44-911d-4de4-88bd-9e5f5fe32ef6.png)
Switching back to visual and then back to source again (more span's):
![2021-12-25_23-22-43](https://user-images.githubusercontent.com/60177501/147401661-6fb8742f-6023-4a49-a3af-f00da9bf1813.png)
etc...

**Comment by Kordishal** [comment]
You are using the Plato / WYSIWYG editor. This editor does not support advanced BBCode like containers. You need to switch to the Euclid / Code editor.

There are instructions on how to change your article editor below:

https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors
