### ISSUE TITLE
GIF image does not render as cover image.

### ISSUE THREAD

**Issue by SyntaxChick** [worldanvil/worldanvil-bug-tracker#785]
**World Anvil Username**: SyntaxChick

**World / Campaign / RPG Character / Manuscript Title**: Estia

**Feature**: Covers/Headers

**Related URLS** (To public & visible pages add screenshots otherwise):
Article url:
https://www.worldanvil.com/w/estia-syntaxchick/a/helC989arva-settlement-1
404 url: 
https://www.worldanvil.com/media/cache/cover/uploads/images/8252fa85f2321f5beeca12e66fdac607.gif
Screenshot of it working in editing:
![Screenshot 2021-12-26 222242](https://user-images.githubusercontent.com/18120592/147431175-56628e71-8d7f-4a7c-8aaa-ab2891ef6a79.jpg)
Actual problem image:
![heljarva](https://user-images.githubusercontent.com/18120592/147431225-632de459-59f2-40a8-b292-25d2aa08c9b2.gif)

**Describe the Issue**
I uploaded a cover for one of my articles and while it works when editing the article or in the image gallery area, it's not working on the article itself and in the sidebar when editing the details. On the article it returns a 404 when trying to grab the image. It is a larger image but still under the 10MB max, and one of the supported filetypes. The second image is the image itself. I tried deleting the image and re-uploading it and no dice. Tried a jpeg version of the image, worked fine. Also tried viewing the article in an incognito browser and on a different network with my phone, still didn't work. Not sure if it's just a compatibility issues with GIF's or maybe a caching issue? 

**To Reproduce**
1. Upload given image
2. Add to article as header
3. View article
4. Image returns 404 in console

**Expected behavior**
Image should appear as the cover

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Screenshot 2021-12-26 222242](https://user-images.githubusercontent.com/18120592/147431175-56628e71-8d7f-4a7c-8aaa-ab2891ef6a79.jpg)
![heljarva](https://user-images.githubusercontent.com/18120592/147431225-632de459-59f2-40a8-b292-25d2aa08c9b2.gif)

[edited to add more details]

**Comment by iamromeo** [comment]
Cover images as being rescaled on purpose. This is not a bug it is not a feature :) You cannot have gifs as headers
