### ISSUE TITLE
Artemis list of templates in mismatched language

### ISSUE THREAD

**Issue by RafaelaBarros** [worldanvil/worldanvil-bug-tracker#786]
**World Anvil Username**: RivaliChaos

**World ~~/ Campaign / RPG Character / Manuscript~~ Title**: Gods in Space

**Feature**: Artemis

**Related URLS** (To public & visible pages add screenshots otherwise): None

**Describe the Issue**
My Account and World Settings have language set to **English**, however today, when I used Artemis on the World, the template names (and only that) are in Portuguese. On the Dashboard the templates are named in English and I can't find Portuguese nowhere near my configurations or the rest of the World.

**To Reproduce**
1. Open Artemis
2. Write 'Create'
3. See error

**Expected behavior**
The list of templates should match the language of the rest of configurations (English).

**Screenshots**
Weird one, the World language is set to English, so is the account's (as noticeable by sidebar)
![ARTEMIS Error](https://user-images.githubusercontent.com/82919168/147489950-5c9be7b6-b1d8-4516-bad6-b46b8eae782f.png)

Normal one, same World Setting Language, and same account with the same Account Setting Language.
![ARTEMIS Normal](https://user-images.githubusercontent.com/82919168/147489966-39f649fd-005f-4bef-983f-79534f24632a.png)

**Edit:** Both screenshots are in the same browser. The browser's language is set to Portuguese.

**Comment by Kordishal** [comment]
The important detail here might be that the browser language is set to Portugese right?

**Comment by RafaelaBarros** [comment]
> The important detail here might be that the browser language is set to Portugese right?

Yes, it is. That shouldn't be a factor, however, since it is the same browser on both screenshots. (As in, it is a constant on both screenshots).

Either way, I will add.

**Comment by iamromeo** [comment]
This will not be addressed at this point since this interface is ... well - getting some extra love soon
