### ISSUE TITLE
 Worldember 2021 right hand sidebar claiming an article is x/10000 words to be eligible for WE

### ISSUE THREAD

**Issue by Lyraine-Alei** [worldanvil/worldanvil-bug-tracker#787]
**Feature**: 
Worldember 2021 right hand sidebar

**Describe the Issue** 
The word counter for a single article proclaiming the article is x/10000 words to be eligible for World Ember.

**To Reproduce**
Write an article to at least 50 words, refresh the page.
Under the Scrapbook, where the World Ember Eligibility is seen, there is the word counter for the single article proclaiming the article is x/10000 words to be eligible for World Ember.

**Expected behavior**
I expected the counter to "disappear" once 50 words was met or something, maybe include other articles? I'm not sure, but I know this bar has confused other people despite my amusement that an article is ineligible for World Ember until it has 10K words in it (despite my knowing it doesn't require that)

**Screenshots**

https://image.prntscr.com/image/120PLeHoTHWrxVcTOIy0Ig.jpeg

**Comment by iamromeo** [comment]
This will not be addressed at this time.
