### ISSUE TITLE
Autolinker seems to be linking to a empty article

### ISSUE THREAD

**Issue by MetaverseRPN** [worldanvil/worldanvil-bug-tracker#788]
**World Anvil Username**:DoctorEnigmaROC

**World / Campaign / RPG Character / Manuscript Title**:The Metaverse

**Feature**: Autolinker

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When trying to use the autolinker it seems to be trying to link multiple things to an unnamed empty species article. I already deleted all unnamed stubs earlier in the night after experiencing this issue originally and the issue is persisting.

**To Reproduce**
1. edit an article
2. Attempt to use the autolink feature
3. select selective linking

**Expected behavior**
The autolinker not to be trying to link nothing to a species article I don't think even still exists.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/7560033/147586402-2c7ace62-20ca-41e5-9296-e71f2f0b6948.png)
![image](https://user-images.githubusercontent.com/7560033/147586408-2b3c6da3-a899-4cc2-91c3-410e06d9d290.png)
![image](https://user-images.githubusercontent.com/7560033/147586425-77ce42b6-dc06-4842-8006-51aa2038b5e2.png)

**Comment by GorkamWorka** [comment]
fixed deploying soon
