### ISSUE TITLE
When utilizing spoilers in World anvil when you have a link using "|tab" in a statblock you break the contents of the spoiler.

### ISSUE THREAD

**Issue by sondrex76** [worldanvil/worldanvil-bug-tracker#789]
**World Anvil Username**:Sondrex76

**World / Campaign / RPG Character / Manuscript Title**: Fang's alchemcial emporium
The world is private, images and descriptions has been provided below.

**Related URLS** (To public & visible pages add screenshots otherwise):
Without adding "|tab" to statblock:
![bilde](https://user-images.githubusercontent.com/3610508/147599332-4fed5c04-0223-4734-a6d2-4094b8e88d12.png)
With "|tab" within statblock:
![bilde](https://user-images.githubusercontent.com/3610508/147599476-a50a0146-9915-4ff5-961a-d89012e8b9c2.png)
![bilde](https://user-images.githubusercontent.com/3610508/147599519-6db3c4fc-8c22-4e00-ac28-46f894cea8ce.png)

**Describe the Issue**
A clear and concise description of what the issue is.

**To Reproduce**
1. Make a new article
2. Make a statblock
3. In the statblock make a new link and use "|tab" within it
4. In the article add the statblock within a spoiler

**Expected behavior**
The statblock should not be able to break the spoiler just before "|" was utilized

**Comment by iamromeo** [comment]
This is quite an extreme/unique case. I am really sorry but I will not be addressing this at this point. 
I have made a note of it, thank you for bringing it to my attention :)
