### ISSUE TITLE
Can't grant character profile access to GM

### ISSUE THREAD

**Issue by adajd** [worldanvil/worldanvil-bug-tracker#79]
I'm using WorldAnvil to run an RPG campaign, and I asked my players to grant me editing access to their character profiles, like it says you can do in the Guide to Character Creation. 

None of them could figure out how to do it, even after I sent them a link to the Guide, so ultimately one of them let me log into their account, and sure enough, the "Grant access to GM" button that the guide said should be there simply isn't there. Is there another way to do it or something?

Screenshot attached of the "Character Access Rights" section of my player's profile page. 

![WorldAnvil Access Rights](https://user-images.githubusercontent.com/68634926/111893865-222dff80-89c3-11eb-936b-cf853319e5b0.JPG)

**Comment by iamromeo** [comment]
This character is an inhabitant of a world but has no access to a campaign. 
Was that character invited to the world as part of a campaign or were they invited via the world community? 

There is no way for the system to know which campaign / gamemaster to grant access to if the character is not a member of a campaign to begin with. 

If the character was in fact invited to a campaign and not the world can I please have a link to that character's profile to investigate

**Comment by adajd** [comment]
All five of the characters in question are members of my campaign, not just the world. I invited each of them by typing their players’ email addresses into the “INVITE YOUR PLAYER CHARACTERS IN THE CAMPAIGN!” box on my campaign’s page. 

This is the character whose profile I took the screenshot from (Thorrfakhz Onghozo): 
https://www.worldanvil.com/hero/2ba379d4-1265-4cd2-8fad-f7327cb805d8 

I also personally looked at this profile (Bao Pey Zhang), on the player’s own computer (we live together), and saw with my own eyes that the “Grant access to GM” button is nowhere to be found, just like with the first one: 
https://www.worldanvil.com/hero/63e6ef9e-c553-4209-a1d5-10dda326d69d 

I haven’t personally looked at the other characters’s profiles while logged into their user accounts, but all of them have reported that they can’t find the button: 
https://www.worldanvil.com/hero/18b738b1-20b5-4c86-a589-6109f080fdee 
https://www.worldanvil.com/hero/9ebc3307-9c09-464a-8c8e-c6f34f84d75a 
https://www.worldanvil.com/hero/c46c82c8-c151-4cb9-88d8-a8806e7016ad

**Comment by Kordishal** [comment]
Yeah, I cannot find this button either on an article with my test character, which is definitely invited to the campaign. Was it moved? 

And to be honest I am not sure why it exists? Most of the profile can be edited via the article anyway?

**Comment by iamromeo** [comment]
@Kordishal @adajd I am not sure I understand 
What is it that you are trying to achieve? The character is already part of the world and the GM should be able to see / edit the character in their world. 

The step of needing to grant access has been defunct.

**Comment by Kordishal** [comment]
@adajd As Dimitris has mention it is no longer possible to give access this way. I updated the Codex article accordingly. If you wish to edit your players character use the article in your world.
