### ISSUE TITLE
Double layered spoilers have the names of the spoilers swapped

### ISSUE THREAD

**Issue by sondrex76** [worldanvil/worldanvil-bug-tracker#790]
**World Anvil Username**:Sondrex76

**World / Campaign / RPG Character / Manuscript Title**:Fang's alchemcial emporium

**Feature**: Spoilers within articles

**Related URLS** (To public & visible pages add screenshots otherwise):
The following code:
![bilde](https://user-images.githubusercontent.com/3610508/147599931-aaaa1bc7-c954-4dbf-9581-72b2af92d01b.png)
![bilde](https://user-images.githubusercontent.com/3610508/147600000-40fdb0ee-a0e2-43e9-8608-78b34d86a577.png)

**Describe the Issue**
When using double layered spoilers the name of the inner spoiler and the name of the outer one will be switched.
The issue gets weird when you have a double layered one with multiple spoilers in the inner layer, it is the first of the inner spoilers that gets the name switched
![bilde](https://user-images.githubusercontent.com/3610508/147601116-c3d04e0a-90fb-4549-9079-01e46a5af2c7.png)

**To Reproduce**
1. Make a new article and make a double layered spoiler
2. Give them names through "|name"
3. Observe how the names are switched from what you would expect

**Expected behavior**
You make a double layered spoiler and the names of the spoilers are not switched up

**Screenshots**
![bilde](https://user-images.githubusercontent.com/3610508/147599931-aaaa1bc7-c954-4dbf-9581-72b2af92d01b.png)
![bilde](https://user-images.githubusercontent.com/3610508/147600000-40fdb0ee-a0e2-43e9-8608-78b34d86a577.png)

**Comment by iamromeo** [comment]
This is quite an extreme case, not the intended use of the feature. I am really sorry but I will not address this at this time.
