### ISSUE TITLE
A bug that says I follow more worlds than I actually do. 

### ISSUE THREAD

**Issue by Lenosallose** [worldanvil/worldanvil-bug-tracker#791]
**World Anvil Username**: Lenosallose

**World Title**: Miand'Mésvéstell. 

**Describe the Issue**
It says that I follow 31 worlds when I actually follow merely 3 worlds. 
If I follow an additional world now, it will say 32 worlds. 
If I unfollow it, it will go back to 31 worlds again. 

**To Reproduce**
It appears to have happened sometime when I unfollowed 156 worlds in quick succession.

**Expected behavior**
I expected the number to showcase the correct amount of worlds that I follow. 

**Screenshots**
![Skärmavbild 2021-12-28 kl  23 26 17](https://user-images.githubusercontent.com/80036231/147641083-5c4dfb56-fbb2-44dc-9de5-3f60cb0df04b.png)

**Comment by iamromeo** [comment]
Removed the statement on its entirety
