### ISSUE TITLE
Thread Select Actor Removal X does not remove

### ISSUE THREAD

**Issue by graylion-wa** [worldanvil/worldanvil-bug-tracker#792]
**World Anvil Username**:

Graylion

**World / Campaign / RPG Character / Manuscript Title**:

Creation

**Feature**: 

Discussion Boards & Threads

**Describe the Issue**

in the process of posting to a thread, I have an actor selected by mistake. I click the the "X" to the right of the name and it does not remove the name. I can select a new character, but the post actually needed to be from the GM not an NPC. And once you post the user/character posted as can not be changed.

**To Reproduce**

01. Go to the post box in a thread
02. Select an character from the drop down list.
03. Click the X to remove the character

**Expected behavior**

There should be a way to return to posting as the user without refreshing the page, which would require copy the info that is already typed into notepad, refreshing the page and pasting it back.

Thank you

**Screenshots**

![image](https://user-images.githubusercontent.com/79761754/147713027-588d63ed-cc36-41c1-b78e-a8f9b729aa0b.png)

**Comment by iamromeo** [comment]
added empty option - because of its triviality I will not be going any further with this at this point.
