### ISSUE TITLE
Delete world leads to 404 page

### ISSUE THREAD

**Issue by CromixX** [worldanvil/worldanvil-bug-tracker#793]
**World Anvil Username**:

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I try to delet worlds or campanigs and it does work.

**To Reproduce**
1. Go to ' World'
2. Click on 'settings /delet World'
4. See error 404 “ Thus you have reached the end of this world.”

**Expected behavior**
![Error](https://user-images.githubusercontent.com/96698853/147855388-b2700334-43bf-4548-9d63-92e266645b05.PNG)

Did i do something wrong or why cant i delet the world

**Screenshots**

**Comment by iamromeo** [comment]
I cannot check without the users username but this is probably due to multi account and same name of world
