### ISSUE TITLE
Global sidebar content shows even if sidebar is hidden in article

### ISSUE THREAD

**Issue by Bladeswillfall** [worldanvil/worldanvil-bug-tracker#794]
**World Anvil Username**: Bladeswillfall (_Fall_ on Discord)

**World / Campaign / RPG Character / Manuscript Title**:VISCERIUM

**Feature**: Global sidebar content

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/viscerium-bladeswillfall/a/citadel-article

**Describe the Issue**
I have content set in the Global sidebar section which I use to populate the sidebar of all of my articles. However, when I select the "Display article sidebar (override)" option in the article, the global sidebar content still appears in the article, though it is in a weird spot and no longer to the right-hand side. I had expected the do not display option to overule the global sidebar content and hide it, not move it.

**To Reproduce**
1. Go to (https://www.worldanvil.com/w/viscerium-bladeswillfall/a/citadel-article)
2. Scroll down to Just below the faction icons, above the WorldTOC
3. See error

**Expected behavior**
I'd like the "Display article sidebar (override)" to **overule** the global sidebar content and hide it.

**Screenshots**
![Screenshot_8](https://user-images.githubusercontent.com/81432164/147891649-bf4d795c-e450-4640-8c3b-1a6496f72e99.png)

If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
This article has the Display Sidebar set to **on**. I just set it to off and it dissappeared. 
This is not a bug :)
