### ISSUE TITLE
World Editor Bar Covers Article Content

### ISSUE THREAD

**Issue by tlees** [worldanvil/worldanvil-bug-tracker#796]
**World Anvil Username**: stormtroll

**World / Campaign / RPG Character / Manuscript Title**: Article

**Feature**:  [articletoc] and the World Editor Bar

**Related URLS** See Screenshot.

**Describe the Issue**
When editing the page with the World Editor bar enabled, clicking on a deep link from the [articletoc] sidebar will cause the content to be hidden, forcing the user to scroll up to see the actual content that's hidden underneath the World Editor bar.

**To Reproduce**
1. Go to any page that has an [articletoc] in the sidebar that you can view the world edit bar on.
2. Click on the link in the sidebar.
3. Clicking the sidebar scrolls you down the page to the appropriate section, but the top of the section is hidden by the World Editor Bar.
4. The heading and the first few lines of text are hidden by the World Editor Bar and you need to scroll up to read it.

**Expected behavior**
This should be adjusted globally with css while the World Editor Bar is visible so that the content is not hidden. 

**Example fix**
While this may not be the exact solution that solves every case, I was able to use this custom css to fix the issue for me.
```
#world-editor-bar~#full-layout .article-content h1[data-article_toc-id],
#world-editor-bar~#full-layout .article-content h2[data-article_toc-id],
#world-editor-bar~#full-layout .article-content h3[data-article_toc-id],
#world-editor-bar~#full-layout .article-content h4[data-article_toc-id],
#world-editor-bar~#full-layout .article-content h5[data-article_toc-id] {
    /* 48px is the size of the world editor bar */
    padding-top: 48px;
    margin-top: -48px;
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
Clicking this link
![C80BSZ5 - Imgur](https://user-images.githubusercontent.com/338971/147953817-141c24e6-45a2-4176-8a82-934977cfb02b.png)
Looks like this
![wKZKfX9 - Imgur](https://user-images.githubusercontent.com/338971/147953779-5ebdfdc2-56c4-48a8-9cd0-22b1396bd9a8.png)
It should look like this
![Screenshot_1](https://user-images.githubusercontent.com/338971/147953941-00ab1316-4faf-4fb4-8432-8aacbc66a9f0.png)

**Comment by Kordishal** [comment]
This only affects the editors of a world. Readers do not have this bar. So if you adapt the CSS to consider this bar in your World CSS then any user will think it does not scroll down enough.

**Comment by tlees** [comment]
The code that I provided will only be valid if the world-editor-bar exists on the page.  If the bar does not exist, the css will not be valid.
