### ISSUE TITLE
WorldEmber Style last-child causes incorrect colors on Table of Contents

### ISSUE THREAD

**Issue by Mr4Goosey** [worldanvil/worldanvil-bug-tracker#797]
**Mr4Goosey**

**The Known World**

**CSS Styling - WorldEmber**:

**[Example Page](https://www.worldanvil.com/w/the-known-world-mr4goosey)**

![image](https://user-images.githubusercontent.com/27518053/147979108-e3acb57e-9838-413e-8d0c-0622b22e7366.png)
In-editor ('correct') result left, real-world ('incorrect') result right.

When using the WorldEmber style, the table of contents links seem to go white, with all other color styles being overwritten by a section of a:last-child theming in the style.

This bit of code seems to be intended for the "edit" buttons next to each entry in the editor, however when viewing the page outside of the editor it causes them to be white.

**To Reproduce**
1. Switch a world to use the WorldEmber style.
2. Give it an article to show in the table of contents
3. In-editor view has correct (and interactive) text colors
4. Real-world view has permanent white text color

**Expected behavior**
Real-world view should match in-editor view.

**Comment by iamromeo** [comment]
Hello there :) 

If by in editor you mean while you use the palette on the right hand side, the chances are that your CSS is incorrect or it is not following the rules :)

**Comment by Mr4Goosey** [comment]
While I understand the straight-forward conclusion would be that I've messed up my custom CSS, this issue persists even when I remove all custom CSS. As stated in the reproduction steps, the WorldEmber style does this by itself, without any changes made to it.
In-editor was indeed poor phrasing, but I'm not sure how else to refer to it. If I visit the page on my account, the "edit page" icons show up next to each timeline link, and everything looks as it should. If I visit the page in incognito (therefore without edit rights), the "edit page" icons disappear (as expected), but the table of contents text turns white, as shown in the image above.

**Comment by Kordishal** [comment]
I assume you mean the rule below? Seems to me that is there on purpose, no? So I feel it is up to you to change it if you do not like it.
```css
.user-css ul.category-list li a:last-child {
    color: var(--ember-light-d);
    line-height: 2;
    vertical-align: -6%;
}
```

**Comment by Mr4Goosey** [comment]
Thanks for the swift reply! That is indeed the rule in question. How would I go about removing said rule from the theme I'm using? 
I've looked around the settings a bunch, but I've been unable to find any place that'd allow me to disable part of the theme. Unfortunately, just overwriting the styling set in that rule with something else has proven problematic, as the a:last-child overrides hover colors. Doing so I could make my links appear as the correct color again, however they wouldn't change upon mouse-hover.

**Comment by Kordishal** [comment]
You do not have the ability to change the CSS of the theme itself. We'll have to see if there is something TJ / Melior can do without changing the base theme too much.

**Comment by Mr4Goosey** [comment]
I've gone ahead and had a chat on Discord about this as well, and I've got a sensible workaround now by adding this to my custom CSS:
`.user-css ul.category-list li a:first-child {
  color: var(--ember-danger-l);
}
.user-css ul.category-list li a:first-child:hover {
  color: var(--ember-warning);
}`

Here's a link to the Discord conversation in case the extra details might be of use: https://discord.com/channels/348060277989965844/406145626200604675/927922729284435999
