### ISSUE TITLE
Breadcrumb icons of child articles are used for parent article.

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#798]
**World Anvil Username**: SoulLink
**Feature**: Breadcrumb BBCode

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
The breadcrumb displayed within an article that is under a parent article shows the icon of the article for both itself and its parent article. This overwrites the icon of the parent article.

**Reproduce**
1. Create article with icon.
2. Create second article without icon.
3. Set first article as parent article of second article.
4. Add breadcrumb to second article.
5. See that both articles have no icon displayed.

**Comment by iamromeo** [comment]
confirmed - fixing

**Comment by iamromeo** [comment]
fixed deploying
