### ISSUE TITLE
Cant delete test world

### ISSUE THREAD

**Issue by vigge88** [worldanvil/worldanvil-bug-tracker#799]
**World Anvil Username**: vigge88

**World **: test

**Feature**: Delete world

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Im not able to delete the world. when i ptess in the settings delete world it takes me to the 404 page the world is no more. but when i go back to my anvile home page it still there and everything.

**To Reproduce**
1. Go to 'world settings >2. delete world > 3. press okay >4.  rederected to 404 page > 5. go back to the home page '

**Expected behavior**
the world is not deleted

**Screenshots**

**Comment by iamromeo** [comment]
Hello @vigge88 that is quite odd, I have checked everything that I knew it can cause it and I cannot find a solution. 
Can you please 
1. Update teh password to your account to a temporary one
2. Send me that password and a link to this issue at hello@worldanvil.com 
So I can have a look first hand

**Comment by iamromeo** [comment]
Potentially related to https://github.com/worldanvil/worldanvil-bug-tracker/issues/802

**Comment by iamromeo** [comment]
Hello @vigge88 thank you for the email. 
This had something to do with your campaign. Deleting the campaign first fixed the issue - I will investigate but you are all set.
