### ISSUE TITLE
Den oändliga världen map in header and cant delete it

### ISSUE THREAD

**Issue by vigge88** [worldanvil/worldanvil-bug-tracker#800]
**World Anvil Username**: vigge88

**World **: Den oändliga världen

**Feature**: map in header on all pages

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/den-oandliga-varlden-vigge88

**Describe the Issue**
1. somehow i ve enable the map "1" to show in the header off all pages as you can see in the link above . and i seem not to be able to disable it anywhere.
2. i tried to delete the map but i get the 404 code and the map is still there as an container for the map but the image is deleted

**To Reproduce**
1. delete map
2. 404 page
3. go back to world page  maps

**Expected behavior**
i expect the map to be removed from the header somehow 
i expect to be able to delete maps and its container.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![nedladdning (1)](https://user-images.githubusercontent.com/97147898/148170305-b650f0a4-9bab-449e-98cd-9df83fd8c0a0.png)
![nedladdning (2)](https://user-images.githubusercontent.com/97147898/148170311-6b592993-93b1-480e-84c3-e3545369d275.png)
![nedladdning (3)](https://user-images.githubusercontent.com/97147898/148170395-9d695f00-1d0b-4e08-bb1b-2dc0a2176def.png)
![nedladdning (4)](https://user-images.githubusercontent.com/97147898/148170438-0857742c-4dcd-47ea-8257-42e64ac59eb6.png)

**Comment by vigge88** [comment]
![nedladdning (6)](https://user-images.githubusercontent.com/97147898/148170673-c6fb4cbc-8601-43b7-92ae-e41d16f59a8f.png)
![nedladdning (5)](https://user-images.githubusercontent.com/97147898/148170667-9ddfe460-6a3f-4b1b-a8ca-bac52264e7cf.png)

**Comment by Kordishal** [comment]
This is a setting in the main world configuration. 

Press the small gear icon to get to that menu:
![image](https://user-images.githubusercontent.com/14262536/148183250-3f22bd43-c6c1-4d63-8b47-9de3779916fa.png)

Then remove the map as the world master map:
![image](https://user-images.githubusercontent.com/14262536/148183315-08942beb-9f10-4ebc-b027-31fccf628434.png)

For the future, please come to the Discord server for technical difficulties first.
