### ISSUE TITLE
Leave world & switch to world button visible on world blocks I am no longer a part of.

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#801]
**World Anvil Username**: SoulLink
**Feature**: User Profile World Blocks

**Describe the Issue**
While on Lenosallose's author profile I can see the Leave World and Switch to World buttons on the world of Creation. Both the buttons of course tell me that I can't do that as I do not actually have the permissions. I am no longer a coauthor on Creation.

Leno has reported the same behaviour for a world he used to be a part of. Though there is little consistency so I am not sure what the cause could be and can't realiably reproduce it.

**Screenshots**

On Lenosallose's profile:
![image](https://user-images.githubusercontent.com/14262536/148207352-7df42487-d404-417c-afe4-2d0e42c450c7.png)

On Graylion's profile:
![image](https://user-images.githubusercontent.com/14262536/148207431-2f50d248-926c-49bf-b071-d909534c73d2.png)

**Comment by iamromeo** [comment]
This is just cache taking a bit of time to refresh
