### ISSUE TITLE
I deleted my world but it still exists

### ISSUE THREAD

**Issue by Lynnettecat** [worldanvil/worldanvil-bug-tracker#802]
I deleted my cyberpunk red world five times and it's still there screen pops up 404 this world has come to and end then I reloaded the page it tells me to and the world is still there. I can't even make a new world either

**Comment by iamromeo** [comment]
If you are referring to this world https://www.worldanvil.com/w/night-city-lynnettecat
this world is not deleted.

**Comment by iamromeo** [comment]
Hmmm, thank you @Kordishal 
Lynnettecat I will need more details. on this. 
Did you have a world with the same name before or another account?

**Comment by iamromeo** [comment]
@Lynnettecat can you do me a favour and try to delete your campaign before you delete your world?
