### ISSUE TITLE
Profession template has a wrong link for Related Technologies

### ISSUE THREAD

**Issue by Ratharee** [worldanvil/worldanvil-bug-tracker#803]
**World Anvil Username**: Ratha

**World / Campaign / RPG Character / Manuscript Title**: All worlds

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise): Profession Template

**Describe the Issue**
When using the profession template, in the Related Technologies field, if you click on "Create a New Article and Link It", it creates a new vehicle article, instead of a new technology article.

**To Reproduce**
1. Go to Profession Template
2. Click on Relations
3. Scroll down to Related Technologies
4. Click on "Create a New Article and Link It" to create a new article

**Expected behavior**
To create a new technology article, as the Related Technologies field says.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Fixed - will be deploying today 
Thank you for reporting!
