### ISSUE TITLE
Featured articles not appearing on the homepage

### ISSUE THREAD

**Issue by DanforthLaertes** [worldanvil/worldanvil-bug-tracker#804]
**World Anvil Username**:Danforth Laertes

**World / Campaign / RPG Character / Manuscript Title**:Outremer (Homepage)

**Feature**: Featured articles not appearing on the homepage

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/outremer-danforth-laertes
This article edit page https://www.worldanvil.com/world/article/b86e9248-437e-4439-97ef-25699e2cd890/edit shows the article is selected as "featured"

**Describe the Issue**
Previously the featured articles (I have two for this world; both short articles displaying a gallery at the bottom) appeared on the homepage. Recently, they have stopped doing so - but no change has been made to the articles (they have not been unfeatured). This also happens on my other world - similar articles which are featured but do not appear on the homepage.

**To Reproduce**
1. Go to the homepage - featured articles do not appear, but they used to and should.

**Expected behavior**
Featured articles should appear on the world homepage.

**Comment by iamromeo** [comment]
Featured articles is a feature that is currently disabled that was announced some time ago. It will be coming back once I can guarantee that it will not cause stability issues to the website. :)
