### ISSUE TITLE
Creating New World Redirects to 404 Error Page

### ISSUE THREAD

**Issue by artiemauve** [worldanvil/worldanvil-bug-tracker#805]
**World Anvil Username**: artie_mauve

**World / Campaign / RPG Character / Manuscript Title**: Etherios (or trying to make world called such)

**Feature**: Creating World

**Related URLS** (To public & visible pages add screenshots otherwise):

https://www.worldanvil.com/world/new

**Describe the Issue**

I had tried creating a new world after deleting one and the website directs me to a 404 error message page. I've tried it on multiple occasions in the past 24 hours but it hasn't worked as I had figured maybe the site what having maintenance on it. I see others had similar issues but with deleting worlds instead of creating new ones.

**To Reproduce**
1. Go to "Create a new World"
2. Entire information in the three boxes (do not uncheck automatic basic categories)
3. Select "Save and Proceed"
4. Site redirects user to 404 error
5. World has not been saved

I'm not sure if this is a unique experience or if others are finding this same bug, but steps have been included anyway.

**Expected behavior**
I was expecting to be able to continue editing a new world and move on to the next steps. The world I try creating does not save. Makes the site virtually unusable for me.

**Screenshots**
![bugreport1](https://user-images.githubusercontent.com/97326841/148631471-518458fc-8281-4531-848f-2ef7494b65d3.PNG)
![bugreport2](https://user-images.githubusercontent.com/97326841/148631473-7aff8294-d0c4-43a6-9267-c141b78963d4.PNG)
![bugreport3](https://user-images.githubusercontent.com/97326841/148631475-461bd551-21b8-40cb-ae9e-113290673e60.PNG)

**Comment by Kordishal** [comment]
Have you tried creating it with a different name? The world you deleted before had the same name? If this is the case then the copyright lock prevents you from recreating your world. Dimitris will have to remove it if you want to reuse the name,

**Comment by artiemauve** [comment]
> Have you tried creating it with a different name? The world you deleted before had the same name? If this is the case then the copyright lock prevents you from recreating your world. Dimitris will have to remove it if you want to reuse the name,

Welp, turns out that was the problem. I think what happened was I had 2 accounts and tried to have the same world name between them both. I can probably fix this issue myself, and upon searching the world under that name, turns out there's about three dozen other worlds by different users of the same name, so I'll have to get creative. Thank you for responding and apologies for submitting a bug report that wasn't actually a bug, just a copyright feature.

**Comment by Kordishal** [comment]
Just so you know, Dimitris can remove the copyright lock for you if you have a subscription. And other accounts having the same world name doesn't matter for this. Only the same username + world name combination triggers the copyright lock.

**Comment by iamromeo** [comment]
Multi account is actually a cause for account termination and ban (Please read the ToS) . Please remove all secondary accounts within the next 48 hours
