### ISSUE TITLE
Unexpected crashes while editing an article

### ISSUE THREAD

**Issue by jetsetdrift** [worldanvil/worldanvil-bug-tracker#806]
**World Anvil Username**: JetSetDrift

**World / Campaign / RPG Character / Manuscript Title**: Outrider

**Feature**: Editing article

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
The bug in question is causing the website to freeze & no longer respond, and it occurs whenever an article featuring a spoiler tab is edited or deleted. I have switched web browsers assuming that would solve the issue. Unfortunately, it persists to which this has halted progress on posting to the Outrider world page. Hopefully, it can be resolved without much issue.

**To Reproduce**
1. Create any type of article
2. In the content tab, create a spoiler tab and save changes, followed by clicking view.
3. Return back to the article with the spoiler tab in the content tab and attempt to edit or delete it.
4. This results in the website freezing and crashes

**Expected behavior**
I am hoping that this bug can be easily fixed with a simple solution.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Screenshot 2022-01-09 03 42 20](https://user-images.githubusercontent.com/97380577/148675511-bffcaa50-f8ff-4d2e-85a7-e0dc11658d1f.png)
![Screenshot 2022-01-09 03 42 32](https://user-images.githubusercontent.com/97380577/148675512-bb362495-555c-45a2-95ff-26e98b3847ec.png)
![Screenshot 2022-01-09 03 42 40](https://user-images.githubusercontent.com/97380577/148675513-016bdd17-96e0-485f-9325-f831c66152af.png)
![Screenshot 2022-01-09 03 43 36](https://user-images.githubusercontent.com/97380577/148675514-6ec04a86-308a-469f-9347-465946950ae5.png)

**Comment by Kordishal** [comment]
Hi, thank you for your report!

I can't reproduce it crashing the tab, but it slows down and there is some lag as soon as there is a rendered spoiler present and you type in it.

This is an issue with the Plato Editor which will be completely reworked at some point in the future. In the meantime you should switch to the Euclid editor. No such issues exist there.

Check out [this guide](https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors) on the Codex to learn how to switch!

**Comment by iamromeo** [comment]
This might be an issue with the browser or plugins running on the browser. Regardless I would suggest you move to Euclid for now
