### ISSUE TITLE
World Export Fails with: Error Type: pywaclient.exceptions.InternalServerException: article/9ba3f1dc-4a34-4630-80a7-19b4ad0fb0a6

### ISSUE THREAD

**Issue by ZephyrSpark** [worldanvil/worldanvil-bug-tracker#807]
**World Anvil Username**: ZephyrSpark

**World / Campaign / RPG Character / Manuscript Title**: MHC World

**Feature**: Export the World

**Related URLS** (To public & visible pages add screenshots otherwise):
This might be a personal problem with my account.

**Describe the Issue**
A clear and concise description of what the issue is.
I can't download my work on World Anvil. I generated a Token, press the Start Button, and get a message saying "Successfully scheduled backup. This can take several minutes. You will receive an email to confirm." But then it changes to a message that says, "Job failed: pywaclient.exceptions.InternalServerException: article/9ba3f1dc-4a34-4630-80a7-19b4ad0fb0a6."

Previously, when I tried doing this four months ago, I received a message stating "Job failed: TypeError: argument of type 'NoneType' is not iterable." Now, there seems to be a new kind of error?

**To Reproduce**

1. Go to Export World
2. Click on "Start"
3. See error

**Expected behavior**

I get an email confirming the download process has begun or is underway. Later, I should have all my documents.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
<img width="1152" alt="Screen Shot 2022-01-09 at 11 56 54 AM" src="https://user-images.githubusercontent.com/89484563/148694353-daf1552e-9431-4fb1-af7c-300a6c023a05.png">

**Comment by Kordishal** [comment]
Hi,
Thanks for the report. I will need an authentication token from you to easily figure out what the problem is. Can you message me on Discord? 

SoulLink#3294 (honorary Forge Gremlin)

**Comment by ZephyrSpark** [comment]
Hold on, I'm trying to access the app right now.

**Comment by ZephyrSpark** [comment]
I don't know how to use the app. How do I contact you through it?

**Comment by Kordishal** [comment]
Hi sorry I forgot to include the link!

https://www.worldanvil.com/discord

This link will get you on the server (you can just use Discord in the browser or if the app is open it should redirect you automatically).

Once you are in the server there should be a channel in the sidebar named #help. Go into this channel and type @SoulLink (check you are selecting the correct one as there are two with different numbers).

Then write that you are looking for help with the API. Then I will contact you directly and you can send me the token. (Or you can find my name via CTRL+T and then send me a direct message)

**Comment by ZephyrSpark** [comment]
I just sent the message via Discord. It took me a while to figure out. Also, I might have to leave my computer a while to do a chore.

**Comment by Kordishal** [comment]
@Dimitris:

We figured out that this was caused by a broken BBCode in the article. This prevented the HTML from being rendered and as a result the API could not return the article. Would be useful to have some checks there.

The BBCode in question was a [url:[timeline BBCode]]Text[/url] combination which breaks the renderer.

**Comment by iamromeo** [comment]
I am not even sure how to catch that and what sort of a catch it would be and for which cases. Thoughts?
