### ISSUE TITLE
Cannot Submit or Save new content

### ISSUE THREAD

**Issue by Slumblebum** [worldanvil/worldanvil-bug-tracker#808]
**World Anvil Username**: Slumblebum

**Feature**: Create New World and Journal

**Describe the Issue**
Attempting to save a New World results in a 404 error.
Attempting to Submit content into blank journal fails

**To Reproduce**

Creating New World fails and results in 404 error 
1. From Home, go to Your Campaigns
2. Go to Create New World
2. Enter content into fields (doesn't seem to matter if anything is left blank or all fields are entered)
3. Press Save & Proceed

Updating Journal Pages fails
1. From Home, press Journal
2. Navigate to any Journal Page or create a new page NOTE: Titles correctly save
3. Enter information into journal page
4. Press Submit
5. Navigate to different page
6. Navigate back to journal page

**Expected behavior**
Information entered should save and persist

**Comment by Slumblebum** [comment]
Attempted solutions

1. Noticed Worldbuilding feature was disabled. Worldbuilding has since been enabled. **No Change**
2. Logged out and back in. **No Change**
3. Changed from Plato editor to Euclid. **No Change**
4. Changed from Euclid editor to Legacy. **No Change**

**Comment by Slumblebum** [comment]
Note: Noticed Ticket# 805 had similar issues. However, my account has no old/previous content.

**Comment by Slumblebum** [comment]
Attempted solution

Based on Ticket# 805

1. Created New World with different title than previous attempts. **Successful**

Failed attempts to create new world are being logged somewhere in the background, however those worlds do not appear in existing worlds.

**Comment by Slumblebum** [comment]
Edited "Test" world title to same as failed world title **Successful**

**Comment by Slumblebum** [comment]
Progression

1. Pasting content from original attempts into World Introduction/Description results in 404 Error
2. Typing new content (the word "Test") into World Introduction/Description **Successful**

**Comment by Slumblebum** [comment]
**World Introduction/Description and Updating Journal Pages Issues Update**

Information being entered were excerpts from texts and included an Emoji. Removed Emoji **Successful**

**No further issues remain**

**Comment by Slumblebum** [comment]
All issues seem to be tied to the inclusion of an Emoji in text bodies.

**Comment by Kordishal** [comment]
Yes, Emojis are currently not supported in most of World Anvil (the exception are Discussion Boards). Thanks for taking the time to test it out and documenting your process :)
