### ISSUE TITLE
User Stream "like" status not reflecting the REAL like status

### ISSUE THREAD

**Issue by Tillerz** [worldanvil/worldanvil-bug-tracker#809]
**World Anvil Username**: Tillerz

**World / Campaign / RPG Character / Manuscript Title**: any

**Feature**:  User Stream

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/dashboard/

**Describe the Issue**
Likes on the userstream are not shown properly when you liked an entry because it popped up in your notifications.

**To Reproduce**
1. Wait for an entry to appear in your notifications that is also visible in the user stream.
2. Like it while your are in the notificatons.
3. Switch to the User Stream (visible right side of https://www.worldanvil.com/dashboard/ )
4. Your like is not shown as active (hollow heart)
5. Now if you like the entry here, the heart gets active (red), but the like counter goes down by 1.

**Expected behavior**
Like should be shown as active.

**Comment by iamromeo** [comment]
After some investigation the reason for this is caching, I have removed the caching for now to test - this might make this page slower to load but I will see if that is the case and act accordingly

**Comment by iamromeo** [comment]
If that fails I might have to remove the ability to HEART something from there.
