### ISSUE TITLE
Edit map: compass rose overlays the "create marker" window

### ISSUE THREAD

**Issue by Tillerz** [worldanvil/worldanvil-bug-tracker#81]
See image. If a compass rose is enabled, it covers the window for creating new markers:

* solution 1: change z-sorting (bad, as this stuff will always just create new issues elsewhere)
* solution 2: hide compass rose in edit mode (good)

![image](https://user-images.githubusercontent.com/63370525/111896616-46b5c600-8a1b-11eb-95f3-eb22505a3a51.png)

**Comment by Kordishal** [comment]
Wouldn't it be better to only change the z-index on this page? Hiding it would just confuse people.

**Comment by iamromeo** [comment]
Compass removed from Map editing interface since it would always be covered anyway.
