### ISSUE TITLE
Plots fail to load

### ISSUE THREAD

**Issue by Schmericson** [worldanvil/worldanvil-bug-tracker#810]
**World Anvil Username**: Schmericson

**World / Campaign / RPG Character / Manuscript Title**:  Elendil / Stories of Elendil: Candlekeep / Plots

**Feature**: Plots

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/heroes/campaign/plot/list

**Describe the Issue**
Anytime I click on the plots a the top of my campaigns page it goes to a "This Page isn't working right now" HTTP Error 500

**To Reproduce**
1. Go to Campaign Dropdown or in the campaign screen
2. Click on Plots
3. See error

**Expected behavior**
When clicking on plots should be able to reach plots. 

**Screenshots**
![image](https://user-images.githubusercontent.com/93686965/149013568-9d76cc9a-f1f7-4980-93a6-61806f2a831e.png)

**Comment by iamromeo** [comment]
Well that is something it was not reported for a long time :) 
If you go to edit any of your plots, under the PARENT PLOT entry you will see 

![image](https://user-images.githubusercontent.com/660175/149059600-5cf52edb-ad94-401b-a2a8-2193e0a0f5e9.png)

I hope that makes sense :) 

Make sure you do not create an infinite loop of an article having as a child its parent and so forth
