### ISSUE TITLE
404 when trying to delete a campaign

### ISSUE THREAD

**Issue by DMZimo** [worldanvil/worldanvil-bug-tracker#811]
**World Anvil Username**: Zimo

**Campaign Title**: oldcampaign

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/epic/oldcampaign

**Describe the Issue**
Attempting to delete an empty campaign.
Entering 'DELETE' in the confirmation box sends me to a 404 page.
Campaign remains even after said action is taken.

**To Reproduce**
1. Go to Campaign >> Settings
2. Click on the small arrow next to 'Delete Campaign'
3. Enter 'DELETE' (without quotes) in the field.
4. Press the red 'DELETE CAMPAIGN' button
5. See error.

**Expected behavior**
The campaign should be removed as normal.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/32243512/149180739-d7912215-399a-4cb9-a014-4c336efc81df.png)
![image](https://user-images.githubusercontent.com/32243512/149180793-07d14e06-0119-4d64-9d9b-606ea5f875bf.png)
![image](https://user-images.githubusercontent.com/32243512/149180837-b365d47c-77f9-497a-b658-cc1f15b943d6.png)

**Comment by iamromeo** [comment]
Hey Zimo, can you please check if you have any sessions currently running and does it fix the issue if you stop those sessions?

**Comment by DMZimo** [comment]
Hey,
No sessions are running.
I went further and removed all plots, npcs, primers and anything else that was attached to the campaign.
still no success.

**Comment by iamromeo** [comment]
hmmm I might need access to your account to run a test - can you talk to me on DIscord please so we can resolve this ?

**Comment by iamromeo** [comment]
Fixed.
