### ISSUE TITLE
Missing Player Character Articles

### ISSUE THREAD

**Issue by DJRankine** [worldanvil/worldanvil-bug-tracker#814]
**World Anvil Username**: DJRankine

**World / Campaign / RPG Character / Manuscript Title**: Ekina

**Feature**: Player Character Articles

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/ekina-djrankine

**Describe the Issue**
A clear and concise description of what the issue is.

2 of my player characters do not have articles for their characters. The characters in question are 'Godric' and 'Veda'. Both have been part of my world for a while now, but I've recently tried to create a family tree for Veda, and realised that I can't do it because there is no article to link to.

**To Reproduce**
n/a

**Expected behavior**
Articles for Godric and Veda to be present.

**Screenshots**
n/a

**Comment by iamromeo** [comment]
@DJRankine did you find a way around this is this still an issue sir?

**Comment by DJRankine** [comment]
> 

Hi there. I just ended up making 'Character' articles for them, like I would for an NPC. It served my purpose for the family trees, but still technically an issue with them not automatically having articles linked to their characters.

**Comment by iamromeo** [comment]
That is indeed quite odd - the only think I can think of is that someone deleted the articles before the fix that does not allow the deletion of character articles that have a Hero (player character) attached to them. 

I will keep an eye out for this.
