### ISSUE TITLE
Error Uploading .WEBP to Character templates

### ISSUE THREAD

**Issue by chturner94** [worldanvil/worldanvil-bug-tracker#815]
**World Anvil Username**:
chimis
**World / Campaign / RPG Character / Manuscript Title**:
Golarion / Abomination Vaults / Tristan Harris (not set to my account though; no PC character for me) / NA
**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/heroes/campaign/npc/new
https://www.worldanvil.com/heroes/campaign/npc/*

**Describe the Issue**
When working inside of the uploader associated with NPC/PC (I haven't tested with other templates that have template elements that request image uploads; I would image the issue would be across the board) articles, I cannot successfully upload images in the WEBP format. I have found a work around by uploaded another file format first, navigating to the images tab (https://www.worldanvil.com/world/apollo/), selecting `advanced edit` and replacing the image with the WEBP file. 

**To Reproduce**
1. Go to https://www.worldanvil.com/heroes/campaign/character/list/non?type=npc
2. Click on '[Create a new supporting Cast Member (NPC)](https://www.worldanvil.com/heroes/campaign/npc/new)'
3. Add a name so you can later save.
4. Click on NPC portrait | drag webp file onto the container (Dropzone class element)
5. Select a webp format image (if you didn't use the drag and drop method)
6. The image uploads as a preview successfully.
7. Select save.

**Expected behavior**
To upload a an image in the WEBP format, and for it to be assigned to the NPC successfully. 

**Screenshots**
### Page that produces the issue
![image](https://user-images.githubusercontent.com/49048780/149418985-375a25a0-a6eb-4011-9c45-584db5b833a4.png)

### Success Display of uploaded objects preview | JSON ERROR `Successfully uploaded :Invalid JSON response from server.`
![image](https://user-images.githubusercontent.com/49048780/149419343-916063f6-13ab-4250-a66a-abebec644cb6.png)

### Default icon showing for NPC
![image](https://user-images.githubusercontent.com/49048780/149419544-b2efc51b-b431-4aa1-9a47-dff4ceedba58.png)

**Error Logs**
[POST-https-www-worldanvil.com-her-log-upload.txt](https://github.com/worldanvil/worldanvil-bug-tracker/files/7866439/POST-https-www-worldanvil.com-her-log-upload.txt)
[GET-https-api.userway.org-api-a11y-data-v0-page-data-v0-page-https-worldanvil.TXT](https://github.com/worldanvil/worldanvil-bug-tracker/files/7866440/GET-https-api.userway.org-api-a11y-data-v0-page-data-v0-page-https-worldanvil.TXT)
[POST-https-www.worldanvil.com-cdn-cgi-rum.txt](https://github.com/worldanvil/worldanvil-bug-tracker/files/7866441/POST-https-www.worldanvil.com-cdn-cgi-rum.txt)

**Comment by Kordishal** [comment]
The same applies to RPG Character protraits.

**Comment by iamromeo** [comment]
Fixed will deploy today
