### ISSUE TITLE
Profession template is missing the 'article-content-right' CSS class on the sidebar

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#816]
**World Anvil Username**: SoulLink
**Feature**: Profession Template

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/WBtV/a/hunter?preview=true

**Describe the Issue**
The sidebar does not have the `article-content-right` CSS class on the right sidebar <div>. This leads to the sidebar toggle not working properly and CSS only intended for the sidebar does not work the same as in all other templates.

**Screenshots**
![image](https://user-images.githubusercontent.com/14262536/149613772-395293b3-1837-4276-bc29-4a45387f8b3c.png)

**Comment by NaincyKumariKnoldus** [comment]
Hey @Kordishal I would love to do this. Can I please?

**Comment by iamromeo** [comment]
Thank you bud! Fixed will deploy today
