### ISSUE TITLE
World Transfer Service not working as expected

### ISSUE THREAD

**Issue by Terran34** [worldanvil/worldanvil-bug-tracker#817]
**World Anvil Username**: MacVega
**World Anvil Username**: TeraTremolo

**World / Campaign / RPG Character / Manuscript Title**: Essaron

**Feature**: World Transfer Service

**Related URLS** (To public & visible pages add screenshots otherwise): 
![image](https://user-images.githubusercontent.com/17458247/149630780-b0c95f69-52ad-49f5-bf1c-c840256ab11f.png)

**Describe the Issue**
I am attempting to transfer a world from one account to another. Yet I get the error in the above screenshot. 
The sending account is MacVega. Its membership is journeyman.
The receiving account is TeraTremolo. Its membership is grandmaster.
Therefore, I should not be getting the above error message.

**To Reproduce**
1. Click World Transfer
2. Type in TeraTremolo while signed in as MacVega
3. Hit OK

**Expected behavior**
MacVega should be able to transfer ownership of the world to TeraTremolo.

**Screenshots**
![image](https://user-images.githubusercontent.com/17458247/149630898-8889e7b7-127f-4316-9042-ab17bd45f260.png)
![image](https://user-images.githubusercontent.com/17458247/149630920-8e7bc05e-8573-42cb-b884-3126e6cffceb.png)

**Comment by iamromeo** [comment]
Thank you I will investigate asap

**Comment by iamromeo** [comment]
This is now fixed - it will be deploying today in about 3 hours
