### ISSUE TITLE
Autolink feature reverted article to previous save from hours prior

### ISSUE THREAD

**Issue by philoten** [worldanvil/worldanvil-bug-tracker#818]
**World Anvil Username**: philoten

**World / Campaign / RPG Character / Manuscript Title**: Krreyel

**Feature**: Autolinker

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/world/settlement/23b9e35b-275c-4ba2-9597-14f0059d7b8c/edit

**Describe the Issue**
A clear and concise description of what the issue is.

Spent few hours on filling out a page and decided to try the auto linker feature instead of manually adding the links. The auto linker reverted the article page to some 15 saves earlier when i only had a few sentences typed.

**To Reproduce**

**Expected behavior**
I expected the auto linker to auto link my articles not delete and ignore previous saves of an article. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![c1ce99d1a588b626fcf3416745c5d8b8](https://user-images.githubusercontent.com/97806760/149635871-94dd298f-6660-4666-9e5e-d5592c4b1043.png)

**Comment by iamromeo** [comment]
I am sorry but this is actually impossible. Simply enough even if the autosave wanted to, there is no record of previous saves to revet to. Still @GorkamWorka  can have a look just in case but reading the code I cannot see how this could even be possible.

**Comment by Kordishal** [comment]
Have you potentially written in one tab and then used the autolinker in a different tab? That stale tab without the content would then have overwritten the new content you added in a different tab.

**Comment by philoten** [comment]
> Have you potentially written in one tab and then used the autolinker in a different tab? That stale tab without the content would then have overwritten the new content you added in a different tab.

I did have multiple tabs open but one was of the article in view mode and the other was it in the editor mode. 



> I am sorry but this is actually impossible. Simply enough even if the autosave wanted to, there is no record of previous saves to revet to. Still @GorkamWorka can have a look just in case but reading the code I cannot see how this could even be possible.

So that would mean the save feature is what broke? So when the autolinker updated none of the saves I had manually or the automatic ones actually saved? Wouldn't there be like a save error or something that would of alerted me to an issue so i wouldn't do something that would potentially lose my work?

**Comment by Kordishal** [comment]
There are save errors and they are usually caught. When there is a save error it displays a red badge in the upper right corner instead of the green save badge.

Did you ever refresh the view to make sure that everything was saved correctly?
