### ISSUE TITLE
Table loses formatting when toggling view source mode

### ISSUE THREAD

**Issue by adrestia716** [worldanvil/worldanvil-bug-tracker#819]
**World Anvil Username**: Makoto Ichijoji

**World / Campaign / RPG Character / Manuscript Title**: Asarere

**Feature**:  Edit Article

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/world/article/3ba94b9d-ee8d-4ee7-81a9-5eb6ee74c868/edit

**Describe the Issue**
Tables will sometimes lose formatting and appear as plain text when going from basic interface to view source and back.

**To Reproduce**
1. Create a table with a header
2. Enter data in columns and rows
3. Click "View Source" in the toolbar
4. View or edit table data
5. Click "View Source" in the toolbar to return to the basic edit

**Expected behavior**
Table appears correctly formatted with data in the correct columns and rows

**Screenshots**
![image](https://user-images.githubusercontent.com/18536434/149643730-53c60844-8a1e-4980-b1d0-cc2a1f38644d.png)

**Comment by adrestia716** [comment]
I was able to fix my first table somehow by messing with the formatting but that table existed for a very long time so it seems like the new tables aren't getting fixed no matter what I try.

**Comment by adrestia716** [comment]
OH! It's all of my formatting that this is happening to, not just tables. Old content is fine but new edits to the table aren't saving formatting.

**Comment by adrestia716** [comment]
Oh snap...my whole page just 404'd on view mode.

**Comment by adrestia716** [comment]
Edit page is still accessible

**Comment by adrestia716** [comment]
I found the offending bit of code

[b]Abahambi [/b]tribes are roaming tribes that travel the lands, never staying in one place too long. Because they need to travel light, they tend to stay small and have very little in the way of technology. Some travel out of necessity, keeping several steps ahead - or so they hope - of their local [url:[category:19685c8a-ece7-4681-912e-dfacb70f9eb0]|tab]Primal Lord[/url] or other tribes that may be aggressive or rivals. [br]
If the party chooses to start with this Civ level, it will make for a great exploration and combat style game with little in downtime activities. If the party would like to begin advancement, they'll need to find a [b]Safe Haven[/b].

**Comment by adrestia716** [comment]
it's this. I don't know why but I removed it and it's okay. l [url:[category:19685c8a-ece7-4681-912e-dfacb70f9eb0]|tab]Primal Lord[/url]

**Comment by Kordishal** [comment]
[category:19685c8a-ece7-4681-912e-dfacb70f9eb0] by itself creates a full link anyway. There is no need to add the [url] BBCode around it and as you noticed it currently even breaks the page.
