### ISSUE TITLE
bbcode tags missing in Design Tags Reference and Codex BBCode page

### ISSUE THREAD

**Issue by Tillerz** [worldanvil/worldanvil-bug-tracker#82]
**Related URLS** (To public & visible pages add screenshots otherwise):

1. Article edit / Right sidebar / Design Tags Reference 
2. https://www.worldanvil.com/w/WorldAnvilCodex/a/bbcode

**Describe the Issue**
1. Documentation missing for: [map], [subgroup], [userstate], [pagetoc] and [bloodline] tags. Hint: just copy the info from #dev-changelog or https://blog.worldanvil.com/2020/04/04/development-update-rollup-for-end-of-march/ and https://blog.worldanvil.com/2021/03/05/end-of-february-2021-development-update-rollup/
2. **Variables** have their own page https://www.worldanvil.com/w/WorldAnvilCodex/a/variables but should have a mentioned with link in the https://www.worldanvil.com/w/WorldAnvilCodex/a/bbcode page

**Comment by iamromeo** [comment]
[map], [subgroup] and [bloodline] will not be added since without having the actual ID it's not possible to do anything about it and the blocks are very visible on their locations of creation. 

[pagetoc] and [userstate] are two that are indeed missing and will be added
