### ISSUE TITLE
Print: right sidebar CSS Editor icon is getting printed

### ISSUE THREAD

**Issue by Tillerz** [worldanvil/worldanvil-bug-tracker#820]
**World Anvil Username**: Tillerz

**Feature**: Print Article

**Problem**: Print Article: right sidebar CSS Editor icon is getting printed. Also there is a lot of whitespace left and right, would nice to get rid of that, too.

**Screenshots**
![image](https://user-images.githubusercontent.com/63370525/149821938-740271b0-2858-48a0-854e-01da85d3772e.png)

**Comment by iamromeo** [comment]
Fixed will deploy today - Thank you for reporting!

**Comment by Tillerz** [comment]
This is still printing. 

But! I just checked Bootstap 5 docs... and tried with my BREADCRUMB that also printed .... **d-print-none** works to hide it! So either replace do-not-print with d-print-none, or check what the different is between those two. :)
