### ISSUE TITLE
FFG End of the World system request

### ISSUE THREAD

**Issue by OceanMan603** [worldanvil/worldanvil-bug-tracker#821]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name (RPG SYSTEM)**: End of the World - Fantasy Flight Games
**List Name** (Name under which it should be listed on World Anvil): End of the World RPG (FFG)
**World Anvil Username**: Oceanman603

**Website**: https://www.fantasyflightgames.com/en/news/2016/8/19/its-the-end-of-the-world/

**Logo Image Link**: https://www.fantasyflightgames.com/en/news/2016/8/19/its-the-end-of-the-world/

**Logo Usage Terms (URL)**:

**Comment by iamromeo** [comment]
All done :)
