### ISSUE TITLE
Updated Manuscripts Lost

### ISSUE THREAD

**Issue by MoogaBooga** [worldanvil/worldanvil-bug-tracker#825]
**World Anvil Username**: MoogaBooga

**World / Campaign / RPG Character / Manuscript Title**: Evolve

**Feature**: Manuscripts

**Describe the Issue**

Some days I'll work for hours on my manuscript, close out of it, and then log in on a different laptop to continue working. When I open up the manuscript on the second browser, all of my work has been lost and it looks as though nothing has been done.

I often log into World Anvil on my work laptop when it's slow in the office. (Don't tell them that.) I'm wondering if the strict VPN is somehow blocking World Anvil from saving my progress? I don't know if that's even possible but it seems to work just fine the other way around. If I go from my personal laptop to my work laptop, the manuscript is accurate. But, if I go from my work laptop to my personal laptop, all my progress has been lost. Maybe there's an issue with me leaving myself logged into World Anvil on my personal laptop all the time?

I can't figure out what I'm doing to create this issue so any tips or theories would be appreciated. It's always a bummer when I have to rewrite a scene or I realize all my notes/ideas from the day have disappeared.

**Expected behavior**
The most up-to-date manuscript should always be present.

**Comment by Kordishal** [comment]
Do you leave the tab with the manuscript open on both systems? Then if one of them becomes stale and you save it would still contain the old version. Resulting in your newer version that was saved from the other device to be overwritten.

However, if you always properly close the tab with the manuscript editor and open it new when you switch device this should not happen.

The VPN preventing you from saving seems unlikely, but I have seen stranger things. You should be able to confirm if you can save in the VPN by writing a paragraph and then reloading the page. If the paragraph is gone it did not save properly. Keep an eye out for the green save badge in the upper right corner to see if it saves.

Hope this helps!

**Comment by MoogaBooga** [comment]
Yeah, I think I normally do leave the tab open on my personal laptop, but not on my work laptop. So maybe that explains why I lose all my progress as soon as I open up my personal laptop again. I'll play around with it this week to see if that solves the issue. I'll have to teach myself to close out of the page every time so I don't consistently save over my new stuff.

Nothing saves if I try to use Google Docs with the VPN, which is the only reason I was considering that as an option. But I do see the "Saved" icon pop up in the corner as I'm working in World Anvil. I have noticed that if I add something while on my work laptop, close the page, and then open the page back up, the addition is there. It only disappears when I move to the other laptop.

Thank you for taking the time to respond! Definitely wishing there was a "version history" option so I could go back in time and recover all of my work.

**Comment by iamromeo** [comment]
I am really sorry for this, but indeed it does sound like it can be prevented by properly closing the tab when you are not working on it. 

In other news, there are discussions about soem sort of version history system for the next version of Homer (Manuscripts system).
