### ISSUE TITLE
RPG System Request: LevelUp: Advanced 5th Edition

### ISSUE THREAD

**Issue by rewdmister4** [worldanvil/worldanvil-bug-tracker#826]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name (RPG SYSTEM)**: "LevelUp: Advanced 5th Edition"
**List Name** (Name under which it should be listed on World Anvil): "LevelUp! A5E"
**World Anvil Username**: "Informal_Informant"

**Website**: "https://www.levelup5e.com"

**Logo Image Link**: "https://images.squarespace-cdn.com/content/v1/5f30140933f50e61c794e1a3/1631474188819-4WN2UF6NWH2JPZCI5EN3/poweted_by.jpg"

**Logo Usage Terms (URL)**: "https://www.levelup5e.com/publish"

**Comment by iamromeo** [comment]
hey @rewdmister4 is this far flung from 5e? Does it need another sheet and if so - is it only the character sheet or also monsters/iterms etc that change?

**Comment by rewdmister4** [comment]
@iamromeo Thanks for getting back so fast!

A lot of the base is similar between 5E and A5E, however the character sheet in A5E has enough changes to make it distinct enough to warrant a specific sheet for it, at least in my opinion. 
Items and Monsters have only minor changes that fit within existing sheets on WA though

thanks again! ^-^

**Comment by graylion-wa** [comment]
Oh yes I didn't even think of that and I backed the Kickstarter

**Comment by graylion-wa** [comment]
The existing 5e sheet should be used as the base, I believe

**Comment by rewdmister4** [comment]
@graylion-wa I was originally trying to just modify the 5E template for a custom one, but gave up after about 3 hours of fumbling in the dark and decided to try this route. Using the existing 5E sheet as a base in not a bad way to go about it if its easier on Dimitris' end

**Comment by graylion-wa** [comment]
It will most likely be Tillerz who looks at it as he designed the current 5e sheet. He has a sheet request board. 

I have started a request thread here.

https://www.worldanvil.com/w/sheet-creation/thread/44269068-6162-419e-9809-71a21a306aac/view

**Comment by iamromeo** [comment]
In which case I think that this should probably not be a a separate system but a new sheet for 5e, I am open to thoughts and suggestions. I will keep this open for the next 48 hours to talk it over.

**Comment by rewdmister4** [comment]
@iamromeo That would work perfectly IMO. A5E is supposed to be fully compatible to original 5e anyways

**Comment by iamromeo** [comment]
In which case I will be closing this down :)
