### ISSUE TITLE
Articles permanently "linked" to NPCs in a campaign that no longer exists

### ISSUE THREAD

**Issue by vinceblake** [worldanvil/worldanvil-bug-tracker#827]
**World Anvil Username**: halfblake

**World / Campaign / RPG Character / Manuscript Title**: 
Lilli Longshadow
Palasar Tolthik
Taslyn Cordaer

**Feature**: RPG Campaigns, I guess?

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/acaelica/a/lilli-longshadow-article

**Describe the Issue**
I have a handful of characters who were linked to NPCs in a campaign I have since deleted. It appears that their articles are still linked and I have no ability to unlink them. This results in permanent components of their articles that I am unable to modify or delete under the DM ONLY NOTES section. The only "unlink" option I have includes deleting the article as well (which I do not want to do).

**To Reproduce**
[Hypothetical] Steps to reproduce the behavior:
1. Link an article to an NPC in a campaign
2. Delete the campaign
3. View the article from step 1
4. See Character Profile information from the deleted campaign

**Expected behavior**
These articles should automatically have been "unlinked" following the deletion of the campaign. I am further unable to link the currently perma-linked articles to new campaigns (though this may be by design?) 

**Screenshots**
<img width="384" src="https://user-images.githubusercontent.com/5651306/150398347-1a1e8ed1-4207-4f2b-89dd-eced31950007.png">

<img width="420" src="https://user-images.githubusercontent.com/5651306/150398644-a99290f7-7d7e-4160-8c2f-90365691c594.png">

**Comment by iamromeo** [comment]
Hmmmm, ok I have to have a look on this. This is a much bigger issue the way it sounds. I will have to investigate

**Comment by vinceblake** [comment]
Note that I hid the offending sections with CSS since making that post, but
of course you can see somewhere in the back end that they are linked I am
sure.

Just thought it was worth calling out.

**Comment by iamromeo** [comment]
New specificiation is taking this under consideration and will be fixed with the upcoming update
