### ISSUE TITLE
Manuscripts in the phone browser

### ISSUE THREAD

**Issue by Miluriel** [worldanvil/worldanvil-bug-tracker#828]
**World Anvil Username**:
Miluriel

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 
Manuscripts

**Related URLS** (To public & visible pages add screenshots otherwise):
![Screenshot_20220120-195823_Chrome](https://user-images.githubusercontent.com/98120364/150404355-7b2701a1-7615-48a9-9187-e511b87a41c1.jpg)

**Describe the Issue**
A clear and concise description of what the issue is.
When trying to edit a manuscript on my phone browser (I'm using Chrome on a Samsung S10e) I can't select a text/folder. It will automatically load the last text opened on the browser or a text when it’s added, but I can’t select any other/older scene. The only thing I can do when clicking on them is move them around folders. This makes it pretty much impossible to write on my phone, because I can never check any ressources or scenes I've previously written, which is a bit of a shame.

**To Reproduce**

Not sure if this is normal, but:
1.Go to the manuscripts tab on a phone browser
2. Select a manuscript
3. Try to select a scene to edit

**Expected behavior**

I would like to click on a scene (on the touchscreen) and edit it/ work on it on my phone.  

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Miluriel** [comment]
Additional note: Trying to scroll through the list of folders will also start moving things around because they're accidentally grabbed - that's why everything is a bit jumbled in the screenshot.

**Comment by iamromeo** [comment]
Although we'd love to one day for Manuscripts to be fully usable on mobile devices, it was never built to be mobile friendly
There are many ideas about how we will go ahead and do this ranging from a new version of the current system to a mobile LITE version of WA that will also include basic Manuscripts editing on a mobile-frist interface.
