### ISSUE TITLE
Duplicates in Character list and they lead to 404 pages so I can't fix or delete.

### ISSUE THREAD

**Issue by carterartist** [worldanvil/worldanvil-bug-tracker#829]
**World Anvil Username**: id8tionist

**World / Campaign / RPG Character / Manuscript Title**: happening with a few, such as "Reginald Ivoryclaw"

**Feature**: Player Character or character templates are bugged out

**Related URLS** (To public & visible pages add screenshots otherwise):

https://www.worldanvil.com/w/dierde-id8tionist/a/reginald-ivoryclaw-person
https://www.worldanvil.com/w/dierde-id8tionist/a/reginald-ivoryclaw-person

**Describe the Issue**
A clear and concise description of what the issue is.

When linking characters I discovered I had duplicates. Such as Reggie, and when I tried to delete or fix them I find I cannot.

**To Reproduce**

Look up the reginalds in my world. Try to go to their page. There are others, but this is one of them.

**Expected behavior**

I expected to see a page for Reginald, or if he was deleted before then for it to not show up in a search.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
<img width="345" alt="Screen Shot 2022-01-20 at 7 12 11 PM" src="https://user-images.githubusercontent.com/7810268/150459328-36b4e45c-99fb-4be1-98bd-4a80b57d7698.png">

**Comment by iamromeo** [comment]
This is actually not a bug. That means that the character you are trying to delete belongs to one of your players. 
You can expel the character from your world or campaign depending on how it was linked to the world, but you cannot delete their character. 

Is this the case? Does the character belong to one of your players?

**Comment by iamromeo** [comment]
No response for over 20 days
