### ISSUE TITLE
Journal entries: map embeds do not work properly

### ISSUE THREAD

**Issue by Tillerz** [worldanvil/worldanvil-bug-tracker#831]
**World Anvil Username**: Tillerz

**World / Campaign / RPG Character / Manuscript Title**: Alana

**Feature**: Journal + Map snippets

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/author/Tillerz

**Describe the Issue**
When you embed a map into a journal entry, the map is empty except you have a compass rose. Then you only see that rose.

**Screenshots**
![image](https://user-images.githubusercontent.com/63370525/150629258-5094e461-37c1-4400-9a44-9dbc9a8ccb7f.png)

**Comment by iamromeo** [comment]
Journal entries were never meant to have map injections :P that is the reason they do not work. They will with the new version but this is not a bug :D it's a lack of a feature.
