### ISSUE TITLE
"Delete my account" function does not delete my account

### ISSUE THREAD

**Issue by aquantumofgravitas** [worldanvil/worldanvil-bug-tracker#835]
**World Anvil Username**:
aquantumofgravitas
**World / Campaign / RPG Character / Manuscript Title**:
A Rose By Any Other Wave
**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
"Delete my account" function does not delete my account. I've tried twice, both about a week ago, and I can still log in, all my articles are still there.

**To Reproduce**
1. Go to Account
2. Type username into relevant box.
3. Click on Delete Account
4. World Anvil logs out. Login is still possible immediately and a week later.

**Expected behavior**
World Anvil logs out, attempts to login result in failure to find account, email sent confirming deletion.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
The reason that is happening is because there is already a deleted account with that username. THis means that this account is in violation of Terms of Service already for a single used, that is not a guild member using the same username or password consecutively or having more than one account.
