### ISSUE TITLE
Arcane Ugly

### ISSUE THREAD

**Issue by MysticStarsTTV** [worldanvil/worldanvil-bug-tracker#836]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name (RPG SYSTEM)**: Arcane Ugly
**List Name** (Name under which it should be listed on World Anvil): RPG SYSTEM
**World Anvil Username**: MysticStarsTTV

**Website**: https://miscastterrain.itch.io/arcaneugly

**Logo Image Link**: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.reddit.com%2Fr%2FArcaneUgly%2F&psig=AOvVaw1l0NaAOn31Lvat-k_o6f3i&ust=1643078311218000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCNiP6uqtyfUCFQAAAAAdAAAAABAD

**Logo Usage Terms (URL)**:

**Comment by iamromeo** [comment]
I am sorry but, the user is not a grandmaster
