### ISSUE TITLE
Map tags invisible on articles

### ISSUE THREAD

**Issue by 737oli** [worldanvil/worldanvil-bug-tracker#84]
---
name: Map tags invisible on articles
about: Map tags are missing when players look at articles while they have access to the tags.
title: 'Map tags invisible on articles'
labels: 'map tags embedded snippets'
assignees: ''

---

**World Anvil Username**: 737oli

**World / Campaign / RPG Character / Manuscript Title**: All articles with embedded map snippets.

**Feature**: embedded map snippets

**Related URLS** (To public & visible pages add screenshots otherwise): Mr Dimitris Havlidis has full access to my world via co-authorship.

**Describe the Issue**
As a DM I have made a map called "Waterdeep" which includes a lot of tags. Some of these tags are visible to the players via subscription groups "the party". I have linked an embedded map snippet to every article which is linked to that map tag (building map tag vs building article). They are able to see the map tags while using the main map mode but when they check out the articles they see the embedded map snippet without the tag. This is not the case when I look at the articles from my DM account. I do see the tags aswell.

**To Reproduce**
1. Log into a player account (might not be feasible)
2. Go to "Neverember villa article"
3. Look at the embedded map article

**Expected behavior**
I expected that the players, aswell as the DM, can see the map tags on the embedded map snippets.

**Screenshots**
![image](https://user-images.githubusercontent.com/66430857/111918997-fe80bd00-8a87-11eb-899f-a9f359096072.png) -> player article view
![image](https://user-images.githubusercontent.com/66430857/111919005-03de0780-8a88-11eb-9df3-93d25386ad7a.png) -> player map view
![image](https://user-images.githubusercontent.com/66430857/111919048-3e47a480-8a88-11eb-88e9-98624e3009d0.png) -> DM article view

**Comment by iamromeo** [comment]
hello @737oli I see your world is private, which leads me to ask. 
Does your player(s) have access to a subscriber group that has access to those tags?

**Comment by 737oli** [comment]
Well, It is the same group that is used for the article and the tag on the main map which they can see, so I would say yes.

**Comment by iamromeo** [comment]
So, first of all sadly I still cannot reproduce this, secondly am I right to assume that by "tags" you mean "markers" ? 
can you give me more details as in 
- what is the name of the subscriber group and it possible the ID of it (you can find it on the edit page's URL for the group)
- Which map (give me the map edit page URL) 
- and which marker (give me the marker edit page URL)

**Comment by 737oli** [comment]
Yes, my apologies, I meant markers indeed.

[Subscriber group link](https://www.worldanvil.com/world/access/groups/a062b0a8-126b-449a-b47e-1f0efc795bfd/edit)
The Party -> subscriber group name
[Map link ](https://www.worldanvil.com/w/waterdeep-737oli/map/1ba02070-aca5-4f88-9c62-f694c4e069b1)
[Marker edit url](https://www.worldanvil.com/world/map/marker/dc87b9e0-8da9-4368-87a9-64076c542011/edit)

Here you go!

I fear that the only way you could try reproducing this, would be to log in as a player and get access to the same subscriber group...

**Comment by iamromeo** [comment]
So, first of all thank you for the access @737oli 
I have added GamemasterTest as a member of the party and this is what the account sees when they go to this url
https://www.worldanvil.com/w/waterdeep-737oli/map/1ba02070-aca5-4f88-9c62-f694c4e069b1 

![mapCapture](https://user-images.githubusercontent.com/660175/112330811-0c6d5280-8cc1-11eb-83f2-aa79e8dc300e.PNG)

Which is in accordance with what I see here: 

![Screenshot 2021-03-24 165159](https://user-images.githubusercontent.com/660175/112331052-42123b80-8cc1-11eb-8938-1fceb3743966.png)

Can you please explain to me what is not appearing as should to your players?

**Comment by 737oli** [comment]
No problem!

As DM I can see the marker of the building while I am in the linked article. As a player, I cannot see that marker. I would like it to be that the player can see the marker too.

![image](https://user-images.githubusercontent.com/66430857/112335924-ee055800-8cbc-11eb-9bde-69a6d6f94b1f.png)
![image](https://user-images.githubusercontent.com/66430857/112335963-f52c6600-8cbc-11eb-8f69-74dd31e1857c.png)

**Comment by iamromeo** [comment]
OMG IT TOOK **HOURS** but 
IT'S FIXED!!!

BEER FOR EVERYONE!

**Comment by 737oli** [comment]
Hey, thank you for the time you are spending on my issue but it seems, at least on my player's end, that the issue still isn't fixed.
She still can't see the marker on the article page, and even worse, now she lost all the markers on the main map page as well...

On the main map page, it seems that I have lost the marker group selector on the top right.

Everything still works fine on the DM's side.

![image](https://user-images.githubusercontent.com/66430857/112452935-70425a80-8d57-11eb-91de-1d9ef287b957.png)
![image](https://user-images.githubusercontent.com/66430857/112452997-83552a80-8d57-11eb-9417-075cdd41cc9a.png)

**Comment by iamromeo** [comment]
I am sorry bud, but this is not possible I have an account with exactly the same permissions as your players and they can see exactly what they should be seeing. 

I will need the username / password of your friend to check 
please send an email with her username and temporary password at hello@worldanvil.com quoting this bug reports url.

**Comment by Kordishal** [comment]
The player should also attempt to look at the map in a private window and with a different browser to make sure it is not something on their end.

**Comment by 737oli** [comment]
Hey, I'm sorry. I let 2 players check their accounts, with icognito mode and different browsers, and both got the same result. No makers on the map and the article.  I'll send an email! 

![image](https://user-images.githubusercontent.com/66430857/112503900-98e44780-8d8b-11eb-880d-45fa8924bd16.png)
![image](https://user-images.githubusercontent.com/66430857/112503940-a00b5580-8d8b-11eb-85c2-616aec90c409.png)

**Comment by iamromeo** [comment]
This bug is related to the recent update for world markers and requires immediate attention. 
@737oli fixed for you for now - but there is work to be done on my side.
