### ISSUE TITLE
Character profile issue

### ISSUE THREAD

**Issue by TheArthurianKing6** [worldanvil/worldanvil-bug-tracker#840]
King@rthur

Daearen/Arthur Pendragon

Character profile

**Describe the Issue**
I just copied a character sheet for my character. After I had filled in the sheet, I tried to edit the character profile which I had made the sheet for. It gave me the 'You've reached the end of the world' screen. Even after I logged out, closed my browser and restarted my computer it still gave me the error page.

**To Reproduce**
1. go to https://www.worldanvil.com/dashboard/
2. Go to characters
3. Scroll down to 'Arthur pendragon'
4. Press view or activate
5. see error

**Expected behavior**
I would like to be able to view, activate and edit this character

**Comment by Kordishal** [comment]
My guess would be that there is a bug in the sheet that you are using. Which sheet is it? Try changing the sheet back as it was before.

**Comment by TheArthurianKing6** [comment]
Thankyou for your swiftness to reply, I have already solved the issue and
yes it was because of a bugged character sheet. Thank you anyway.

Yours sincerely
R.G.K Hall
