### ISSUE TITLE
Menus missing

### ISSUE THREAD

**Issue by rightofwei** [worldanvil/worldanvil-bug-tracker#841]
**rightofwei**:

**Terra**:

**Menus**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I seem to be missing any menu items in the side bar (my menu is basically empty) compared to any of the videos I've watched.

Also, I think I'm missing menus in other areas. For example, I cannot see a dashboard link, my world content, etc., without going through my profile and then into my World.

Also, when I click "Home" it takes me to a page that asks me to create "my character." Is that where Home is supposed to go?

I do not think you can reproduce this bug because my friends said this is strange behaviour. T
he only thing I can think of is that I said I wanted to create a character when I first joined instead of world and then didn't finish the character and now it won't let me not make a character as my home page? I don't know the site well enough to know.

I have included screenshots of my menus.
<img width="1425" alt="Screen Shot 2022-01-25 at 7 41 33 PM" src="https://user-images.githubusercontent.com/98435381/151083592-21d137ce-4650-4fa1-9ebf-6d26e85dd1a0.png">

**Comment by Kordishal** [comment]
Hi!
As you have a campaign active but not world visible my guess is that you have disable some features:

https://www.worldanvil.com/dashboard/user/features

Check here that RPG Features and Worldbuilding are enabled.

**Comment by rightofwei** [comment]
YES! That was it! Thank you.
