### ISSUE TITLE
http 500 on TODO list

### ISSUE THREAD

**Issue by scotthibbard** [worldanvil/worldanvil-bug-tracker#842]
**World Anvil Username**: Scylaxu

**World / Campaign / RPG Character / Manuscript Title**: Faerûn / Neverwinter 

**Feature**: TODO List

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/world/todo/view

**Describe the Issue**
The list of TODOs on the TODO list page gets stuck on "Loading". Looking at the browser dev tools I see a POST call to https://www.worldanvil.com/world/todo/list/limit/1000 that resulted in a 500 error. I also noticed that when I go to any other article page, I am able to see a partial list of TODOs. The POST call for this is https://www.worldanvil.com/world/todo/list/limit/10. On the article page, it says "Only 44 items remaining!" which I take to mean that I have a total of 44 TODO items. On a hunch I tried different values of limit. 20 works. 30 works. 40 works. 43 works but 44 does not. 

https://www.worldanvil.com/world/todo/list/limit/43 <<-- works
https://www.worldanvil.com/world/todo/list/limit/44 <<-- gives a 500 error.

**To Reproduce**
1. Go to https://www.worldanvil.com/world/todo/view with dev tools open.
2. See list shows "Loading..." 
3. In dev tools on the Network tab, find POST request with a 500 status to https://www.worldanvil.com/world/todo/list/limit/1000

**Expected behavior**
Call to https://www.worldanvil.com/world/todo/list/limit/1000 does not produce a 500 error and the https://www.worldanvil.com/world/todo/view page shows the list of 43 TODO items.

**Screenshots**
![image](https://user-images.githubusercontent.com/2342607/151374360-63b3cbfd-f3ae-475f-ad28-77c85f33af7d.png)
![image](https://user-images.githubusercontent.com/2342607/151374530-ec020e93-6509-4fe8-a1a8-f5e9fffed2db.png)
![image](https://user-images.githubusercontent.com/2342607/151374728-2e2739c9-fffb-4b61-a90e-2c3aaa2e95b5.png)
![image](https://user-images.githubusercontent.com/2342607/151374833-8a4d6083-16d5-4106-951a-d68dde24ac98.png)
![image](https://user-images.githubusercontent.com/2342607/151375002-3175a993-99ef-43ab-9023-f76ddff08d6d.png)
![image](https://user-images.githubusercontent.com/2342607/151375086-12ac5e99-e267-4e9c-ad93-b1cc6868c494.png)

**Comment by iamromeo** [comment]
Hmmm yeah that really looks like one of the TODO items is bork somehow. And from the looks of it, it's the first one you ever added? I will have to take a ganter, I haven't see this before as an issue.

**Comment by scotthibbard** [comment]
Yes, I still don't quite understand all the ways TODO items can be added. I wasn't aware of the TODO list feature and had just been adding "TODO..." in my articles so I could manually search for them later. I only later found the TODO list and saw that I already had a bunch in there but I'm still not sure how they got in there or what the first "bad" record is.

**Comment by iamromeo** [comment]
hey @scotthibbard sadly I cannot find a way to replicate this. Can you please send me your username and a newly created password with a link to this but at hello@worldanvil.com so I can run some tests to your account please?
