### ISSUE TITLE
Pathfinder 1e Feat statblock is misaligned when embedded

### ISSUE THREAD

**Issue by Zorothegallade** [worldanvil/worldanvil-bug-tracker#843]
**World Anvil Username**: Zoro the Gallade

**World / Campaign / RPG Character / Manuscript Title**: Spira

**Feature**: Statblock and Embed

**Related URLS** https://www.worldanvil.com/w/spira-zorothegallade/a/talenti-article

**Describe the Issue**
When embedding a statblock from the aforementioned template into an article, the text is misaligned, overlapping the embed window on the left.

**To Reproduce**
1. Create a new statblock using the Feat template
2. Embed the statblock in a Worldanvil article

**Expected behavior**
 Embed should be properly aligned.

**Comment by iamromeo** [comment]
I am really sorry but this is a draft article I have no access to it. Also the chances are that this has nothing to do with the sheet but with the article's typography
