### ISSUE TITLE
Style Tags Inserted with Buttons Don't Save Unless Additional Changes Are Made to Article Text

### ISSUE THREAD

**Issue by zpatterson614** [worldanvil/worldanvil-bug-tracker#844]
**World Anvil Username**: Freedomlc

**World / Campaign / RPG Character / Manuscript Title**: Eterna

**Feature**: Article editor

**Describe the Issue**
When you use the H1, H2, bold, etc. buttons to add tags in article text it does not save unless you type something else afterword.

**To Reproduce**
1. Go to any article edit screen with text.
2. Select any text.
3. Click the Bold style button, [B].
4. Click the "Save Changes" button.
5. Click the preview or view button.
6. See that the selected text is not bold.
7. Repeat steps 1 - 3. Then, type anything into the article body. Repeat steps 4 and 5. See that the text is bold.

**Expected behavior**
The text should be bolded after clicking "Save Changes".

**Comment by iamromeo** [comment]
Hey there :) this is a known issue. It will not be addressed for the time being though. The implementation to fix it will cost a lot of resources from the user's environment for the time being. New versions of the editors will be addressing this.
