### ISSUE TITLE
Unable to Edit Player Character Sheets as GM

### ISSUE THREAD

**Issue by nerdmeat** [worldanvil/worldanvil-bug-tracker#845]
**World Anvil Username**: nerdmeat

**World / Campaign / RPG Character / Manuscript Title**: Stenneron / Adventures in Audrath / All

**Feature**: Edit Character Sheet

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When I click on "Edit Sheet" on the profiles of the players in my campaign, it takes me to a 404.

**To Reproduce**
1. Go to campaign > character
2. Click on "Edit Sheet."

**Expected behavior**
Should take me to a page where I can edit sheet information

**Comment by iamromeo** [comment]
Hey @nerdmeat I will be happy to help but I will need more information to help out! 
- Can you let me know WHERE is this edit button that you are trying ot click and fails
- Can you give me the ID of the statblock you are trying to edit?
- Who is the player character and under which campaign?

**Comment by Kordishal** [comment]
Graylion created a detailed step-by-step guide on how to make sheets editable:
https://www.worldanvil.com/w/creation/a/invite-characters-article

@Dimitris: The button appears regardless if these steps are followed or not. It has been reported before, but with Hercules that is going to be irrelevant anyway.
