### ISSUE TITLE
Missing Notebook entries

### ISSUE THREAD

**Issue by Jimmbacca** [worldanvil/worldanvil-bug-tracker#846]
**Jimmbacca**:

**Notebook entry "For The Children**:

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
After Deleting an unused Campaign titled "Progress Campaign" Journal entries were missing from my Notebook, most of which were empty but one had a great bit of detail for an upcoming session.
The entire "Notebook" that these were found under has apparently been deleted along with all of it's entries. I believe i titled it "The City Of Progress", which i have now replaced with a "City of Progress (2)"

**To Reproduce**
I attempted to to make a new World and Campaign, then added some entries to the Notebook while signed into that World.
Upon deletion all notes were still present.
I am not sure how to Reproduce what happened.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Hello @Jimmbacca I am trying to locate your notes but I cannot even find the "City of Progress (2)" you are referring to or the first under your entries. 
- Are you sure you are using the correct account? 
- Which is the name of the Notebook section these were/are under?

**Comment by iamromeo** [comment]
No response for over 10 days
