### ISSUE TITLE
Bug when joining an existing campaign with an existing character.

### ISSUE THREAD

**Issue by dalton-baker** [worldanvil/worldanvil-bug-tracker#847]
**World Anvil Username**: Dalton_baker

**World / Campaign / RPG Character / Manuscript Title**: Agrathia / Quest of the orbs / Greckum Emberbreeze

**Feature**: Joining the campaign. 

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/epic/yl55aqsEc0rRoeieV1fP9ZbC4ZHP8y/join/yGay-aTH1-35kpQB

**Describe the Issue**
When I join the campaign, if I click on my existing character, I am lead to a 404 page. If I create a new character, things work as they should.

**To Reproduce**
1. Go to https://www.worldanvil.com/epic/yl55aqsEc0rRoeieV1fP9ZbC4ZHP8y/join/yGay-aTH1-35kpQB
2. Click on "Choose Greckum"
3. Presented with a 404 page.

**Expected behavior**
I would expect to have my character added to the campaign or have an error message pop up telling me what I did wrong.

**Screenshots**
I go to this page
![image](https://user-images.githubusercontent.com/77222479/151651572-14cbffd5-0a68-4662-9f5b-7ba70bcb565f.png)

I click on this button
![image](https://user-images.githubusercontent.com/77222479/151651596-d8388a02-5bb8-4af2-92ac-50d5843d997e.png)

Then I end up on this page
![image](https://user-images.githubusercontent.com/77222479/151651576-e0b57e97-7f81-4b0d-85a5-e83015db53f9.png)

**Comment by iamromeo** [comment]
Hmmm after snooping I can see you have a single character and that this character is part of a campaing so - I will imagine tha tthis was resolved
