### ISSUE TITLE
Character delete button doesn't show up.

### ISSUE THREAD

**Issue by dalton-baker** [worldanvil/worldanvil-bug-tracker#848]
**World Anvil Username**: dalton_baker

**World / Campaign / RPG Character / Manuscript Title**: No world or campaign / Greckum Emberbreeze

**Feature**: Deleting a character

**Related URLS** (To public & visible pages add screenshots otherwise):  https://www.worldanvil.com/heroes/character/edit/basic

**Describe the Issue**
I ended up adding two characters with the exact same name. I went to delete one of them, but when I open the delete collapse, there is nothing inside it.

One more note is that I had another character that I was able to delete. However the two characters I have now do not have the delete buttons.

**To Reproduce**
1. Go to Character edit page
2. Click on the "Delete Character" collapse.
3. There is nothing inside.

**Expected behavior**
I expect there to be a button inside the collapse.

**Screenshots**
On the edit screen before I dropdown the delete character collapse.
![image](https://user-images.githubusercontent.com/77222479/151651711-d1754853-a7e9-4816-b624-506a94677e6c.png)\

The page after I drop down the collapse.
![image](https://user-images.githubusercontent.com/77222479/151651726-4fcde3a8-871a-41aa-b342-5d36cfaccbab.png)

Here is the console output.
![image](https://user-images.githubusercontent.com/77222479/151651780-eba04f77-3292-43bb-97a6-c355e9130dc7.png)
The very last line shows up specifically when you open the collapse.

**Comment by iamromeo** [comment]
Hey there! If the button doesn't appear it generally means that you do not have permission to delete the character. That is most cases is because you ceded the ownership of a character to a Storyteller or owner of a world. Is this the case?

**Comment by dalton-baker** [comment]
I'm not sure about that, I will check with the owner of the world the character is part of.

**Comment by dalton-baker** [comment]
I was not able to determine the ownership of the character. I ended up renaming t and transferring it to the DM of my group.

**Comment by iamromeo** [comment]
Thank you Dalton, i will investigate
