### ISSUE TITLE
Requesting a new RPG system to be added

### ISSUE THREAD

**Issue by One-LeggedGM** [worldanvil/worldanvil-bug-tracker#849]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name (RPG SYSTEM)**: ODG System
**List Name** (Name under which it should be listed on World Anvil): Hidden Worlds
**World Anvil Username**: One-Legged GM

**Website**:https://www.incursionlegends.com

**Logo Image Link**:

**Logo Usage Terms (URL)**:

**Comment by iamromeo** [comment]
Hey Bryan! ODG System is now in the list :)
