### ISSUE TITLE
World Recreation 404 Error

### ISSUE THREAD

**Issue by HarbingerOfSand** [worldanvil/worldanvil-bug-tracker#85]
**World Anvil Username**: HarbingerOfSand

**World / Campaign / RPG Character / Manuscript Title**: Any world belonging to a deleted account.

**Describe the Issue**
When I try to recreate my world that I previously had on my old deleted account, it gives me a 404 error when I enter the same name.

**To Reproduce**
1. Create World
2. Enter the same name as the world of a deleted account.
**Expected behavior**
It should produce a 404 Error.

**Comment by iamromeo** [comment]
This works as intended world/username pairs are retained as proof of copyright creation date.
