### ISSUE TITLE
Problems with the Euclid Editor

### ISSUE THREAD

**Issue by JohanFalt** [worldanvil/worldanvil-bug-tracker#851]
**World Anvil Username**:
johanfk
**World / Campaign / RPG Character / Manuscript Title**:
Rage Across Colorado

**Feature**: 
The Euclid Editor

**Describe the Issue**
I tested the editor out after the release of the autolinking was announced and found at least two problem during the 30 minutes using the Euclid. Normally I use the Plato Editor.

1. The following text breaks as you save it and the [b] section is removed:

```
[br]
[b]Pack Traits:[/b][br]
The Get of Fenris respect any pack
```

If you put a [space] between [/b][br] it works.

2. If you try to link an article with the @-search you can't use letters in the words like åäö. Writing @snö breaks it right away. Would think the problem that the search doesn't take utf8 in account. Plato Editor this works for.

**Comment by iamromeo** [comment]
![image](https://user-images.githubusercontent.com/660175/151916270-e288174a-6cf3-440b-bc36-ccd4019d8429.png)

![image](https://user-images.githubusercontent.com/660175/151916284-843b2041-bcb7-48e4-b35b-648158b1ad20.png)


Hello there, what is exactly that you see being broken? I cannot see any issue with this

**Comment by JohanFalt** [comment]
Of course I can't recreate the issue any longer either. Next time I'll see if I can get some error code.

**Comment by JohanFalt** [comment]
2. is still an issue though (tried it again). Do think only a-z letters are allowed.

**Comment by iamromeo** [comment]
There is really no solution for 2, this is due to unicode limitations. You can still use any other part of the linked article/object. We will be re-investigating the issue with unicode in the future but not at this stage :)
