### ISSUE TITLE
Editing a number column in an Interactive Table does not always stick to the value entered

### ISSUE THREAD

**Issue by Dinadon** [worldanvil/worldanvil-bug-tracker#852]
**World Anvil Username**: Dinadonosaur

**Feature**: Interactive Tables

**Describe the Issue**
When editing a number the value in the cell will change if you scroll the table

**To Reproduce**
1. Create a new table called Table of Numbers
2. Add a number column called Numbers
3. Create enough rows so that the table needs to be scrolled
4. Enter a value in the Numbers column
5. While the focus is on the value entered, scroll the page (using trackpad or mouse wheel)
6. The value should (eventually) change 

**Expected behavior**
The value should remain as it was typed

**Comment by iamromeo** [comment]
I am really sorry but this is how number fields work on browsers, this is not an issue we can do something about.
