### ISSUE TITLE
Reordering categories by dragging in the Articles view does not respect the order set

### ISSUE THREAD

**Issue by dbj** [worldanvil/worldanvil-bug-tracker#854]
**World Anvil Username**:

Dirkster

**World / Campaign / RPG Character / Manuscript Title**:

Explorers of StarSea

**Feature**: 

Reordering categories by dragging when viewing Articles.

**Related URLS** (To public & visible pages add screenshots otherwise):

N/A

**Describe the Issue**

After reordering of the sub-categories of a top level category via dragging, the ordering does not remain as set - I can't find pattern to how it messes it up because it is different each time.

**To Reproduce**

1. Click on Articles in the left menu
2. Expose a top-level category with sub-categories
3. Reorder one of the sub-categories and notice the green message "Category Moved!"
4. Reload the page

Result: the sub-categories are in a different order than was set

**Expected behavior**
I expect the sub-categories to remain in the same order as was set

**Screenshots**

Starting Order: 

![image](https://user-images.githubusercontent.com/63229/152046079-a3c4a861-e1f0-4daf-8851-9a344206dec5.png)

After dragging:

![image](https://user-images.githubusercontent.com/63229/152046142-5f9bc7d7-03fd-450b-bf52-a00a5bae77a8.png)

After reloading the page:

![image](https://user-images.githubusercontent.com/63229/152046210-4983da0d-7520-40ed-b269-2c0d9ce4e6ba.png)

**Workaround**

You can work around this issue by setting the Position value manually. :)

**Comment by iamromeo** [comment]
Hey @dbj 

This probably means that at some point, one of your categories ended up without a POSITION number OR that 2 categories have the same. If you go though your categories you will see that the position of one of them is empty, filling that number to it puts it in the desired order will fix the isuse. 

We are aware and the next version will correct this issue even if it happens by human error :)
