### ISSUE TITLE
Interactive table not loading

### ISSUE THREAD

**Issue by Siijaye** [worldanvil/worldanvil-bug-tracker#855]
**World Anvil Username**: Siijaye

**World / Campaign / RPG Character / Manuscript Title**: The Barony of Stachys

**Feature**: Tables

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/the-barony-of-stachys-siijaye/a/kingdom-building---buildings-article

**Describe the Issue**
Tables are not loading.

**To Reproduce**

**Expected behavior**
To see the table I have created appear. I upgraded to Master tier to use the feature.

**Screenshots**
![thumbnail_image](https://user-images.githubusercontent.com/98851074/152053598-67236d92-244d-4306-b97f-5cb5d14ec7c6.png)

**Comment by iamromeo** [comment]
Hello there @Siijaye, 

I am really sorry but this article is either a draft or private - I cannot access it to see what is going on and help you. 
Does the table load when you are editing it?

**Comment by Siijaye** [comment]
Hi Dimitirs,

Try the article now? I can see the table when I'm editing it yes, its only when I added it to an article and my players and I tried to view it that we seem to encounter trouble.

**Comment by iamromeo** [comment]
Hey @Siijaye I can see the article now and reproduce the issue. @Xuroth will be having a look as soon as it is possible. :)

**Comment by Xuroth** [comment]
Hello! I see the table is stuck in that "infinite loading" loop in that article. Can you go into the editor for that table and copy the embed tag? it should look something like:

`[inttable:lots-of-numbers-and-letters]`

**Comment by Siijaye** [comment]
Hi @Xuroth,

Went to grab that for you and found the table gone entirely. It was there this morning when I was working on it. The article I was using it in had [itable:420320aa-90ae-4bae-b03e-7c937aa90a4b] as the embed tag.

**Comment by Xuroth** [comment]
Thanks for that! I just tested, and the table's data is indeed not showing in the system, which is odd. Do you happen to have multiple tables? Do you notice any similar issues with those (or just this one)?

**Comment by Siijaye** [comment]
Hi @Xuroth sorry for the delay, miserable kids keep me away from the computer :') I didn't have multiple tables but I spent this morning while bub was still in bed recreating the old one and its working just fine. No idea what that was about but I really appreciate the speedy support you guys have.

**Comment by Xuroth** [comment]
No worries! Glad it's working now for you! I'll go ahead and close this for now. If you experience any further issues with the Interactive Tables not loading properly, let me know!
