### ISSUE TITLE
Country takes me to organisation

### ISSUE THREAD

**Issue by Alundra828** [worldanvil/worldanvil-bug-tracker#856]
**World Anvil Username:** Alundra828

**World:** Hyper Sun

**Feature:** Articles: 

![image](https://user-images.githubusercontent.com/43576482/152071246-f394bd41-a086-453e-b811-fddb07149039.png)

It appears that when I click on countries to create a country article, it takes me to organisations.

![image](https://user-images.githubusercontent.com/43576482/152071358-20af1a07-273e-484e-a425-6703831010ab.png)

Above is a screenshot of the url it takes me to. I'm unable to get to the country article page because it requires a guid as part of the route.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to World
2. Under the 'Create New' section Click on 'Country'
3. You will be taken to the organisation page, not the country page

It should take you to the country page.

**Comment by iamromeo** [comment]
hello  @Alundra828 , 

 This is not a bug, this is what a country is, a geopolitical organization. The link is a reminder for those that need the extra nudge :)
