### ISSUE TITLE
404 Error on Custom Block Templates

### ISSUE THREAD

**Issue by sorinkat** [worldanvil/worldanvil-bug-tracker#858]
**World Anvil Username**: Sorinkat

**World / Campaign / RPG Character / Manuscript Title**: Lost in Seattle

**Feature**: Studio > Sheets & Blocks

**Related URLS** (To public & visible pages add screenshots otherwise): 
https://www.worldanvil.com/rpgsrd/block-template/#####/part/delete/all
etc.

**Describe the Issue**
Clicking on any of the save buttons or clear buttons results in a 404 page.

**To Reproduce**
1. Go to https://www.worldanvil.com/rpgsrd/block-template/#####/parts/edit
2. Click on Delete All Parts on Sheet, Or Import Data
4. 404 page

**Expected behavior**
The buttons work properly unsure what the actual behavior is, this is my first time using the feature.

**Screenshots**
https://gyazo.com/8c1c0c7b992e3b0a23e6995d4faac338

**Comment by sorinkat** [comment]
I attempted on two different browsers, same issue.  Here is a screen cap video of the steps to reproduce:

https://gyazo.com/c18fb0deabea2e6bd6054defec2893f4

**Comment by iamromeo** [comment]
All fixed
