### ISSUE TITLE
Cannot undo a "Create and link Article" in sidebar prompts of article without screen refresh.

### ISSUE THREAD

**Issue by DinosaurBob** [worldanvil/worldanvil-bug-tracker#859]
**World Anvil Username**:
RPGDinosaurBob

**World / Campaign / RPG Character / Manuscript Title**:
Cartyrion

**Feature**: 
Creating an Article (e.g. a LANDMARK article)

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When filling out the template for a LANDMARK article, I used the "Create and Link an Article" feature for the Owner. This feature worked just fine, but after doing so, I wished to delete the link from that particular prompt as I am arranging my own sidebar. There was no visible way to delete the newly created article link -- until I happened to refresh the whole editor screen. Once I did that, I could remove the link.   The Issue isn't that the Create and Link isn't working properly; it works fine. But the impression is that once you do it, you're stuck with it. There's no indication that a screen refresh (or other similar action) is needed in order to regain control over the contents of the field.   I encountered this in the LANDMARKS template, but I presume it is everywhere the Create and Link is used.

**To Reproduce**
1. Go to an article template (e.g. LANDMARKS)
2. Click on the "Create and Link Article" button available on many prompt fields
3. Create the new article
4. Prompt now shows the newly created and linked article, but there are no edit controls on the field anymore.

**Expected behavior**
Either a way to edit (e.g. delete the newly created link and either select another existing link or create another new one)... or at least a line of text warning you that a screen refresh is required before you can edit the field. (Just that one line of informational text would prevent user from feeling the field was no longer editable.

**Screenshots**
Note that there are no edit controls now that I've used the new create and link article feature.
![Create and link](https://user-images.githubusercontent.com/67075344/152361622-d8ce796a-cbce-4970-a775-7b023415a5a4.PNG)

**Comment by iamromeo** [comment]
Hey Bob, all of the above is true, but this is not a bug, it is a lack of a feature, but I cannot keep it in this board active.
