### ISSUE TITLE
Player character always 404s when adding to campaign

### ISSUE THREAD

**Issue by Fabio11234** [worldanvil/worldanvil-bug-tracker#86]
**World Anvil Username**: Kstau24

**World / Campaign / RPG Character / Manuscript Title**: world - The Sol System. Campaign - Leviathan Wakes. Character name - Prit Solokov (given to username ksaathoff)

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Character Prit Solokov was created by Kstau24 and transferred to ksaathoff. When ksaathoff activates Prit and then clicks the link to join the campaign sent by Kstau24, as soon as the button “select Prit” is chosen the page 404s. This happens regardless of link - several new join campaign links were generated and still he cannot join. Character was transferred back to Kstau24 and then back again to ksaathoff with same result. Every other PC was able to join with no issue.

**To Reproduce**
1. Ksaathoff clicks on any “join campaign” link sent to join the campaign “Leviathan awakes” by Kstau24
2. As soon as the character selection option opens up, ksaathoff selects Prit Solokov
3. Site 404s

**Expected behavior**
The character would join the campaign like every other PC.

**Screenshots**

**Comment by iamromeo** [comment]
hey @Fabio11234 this character was already invited to the world directly and not through your campagin.

The player needs to remove the character from the world and then click on the invitation link for the campaign. 
In other news, you are playing THE EXPANSE and I am SO JEALOUS ... but yeah.

**Comment by Fabio11234** [comment]
I removed the character from the world, but the Player said he tried again and still had it 404

**Comment by Fabio11234** [comment]
Is there a way for you guys to add him in on your end?

**Comment by iamromeo** [comment]
Hey @Fabio11234 following our conversation on Reddit I am reopening this issue. 
At this point I will need from you to send me an email with 
- the username and password of the user owning the character (please change the password to a temporary one) 
- the link to the campaign you are try to add them (the one you generated) 

the email is hello@worldanvil.com 

I will try to login with the user and join with the character in order to run some tests and see what is the issue.

**Comment by iamromeo** [comment]
The character somehow ended up being member of the party but not of any campaing. 
Removing (via admin action) the character from the party mended the issue.
