### ISSUE TITLE
Embedding map with private marker groups will cause a 404 on the article if the user does not have access to all marker groups

### ISSUE THREAD

**Issue by Satrium** [worldanvil/worldanvil-bug-tracker#860]
**World Anvil Username**: Satrium

**World / Campaign / RPG Character / Manuscript Title**: Lothrea

**Feature**: Map embeds

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/lothrea/a/kathaldir
https://www.worldanvil.com/w/lothrea/map/fc31bd54-f609-46a9-8e4f-e4073d8490c4

**Describe the Issue**
Embedding a map with private marker groups into an article, will cause that article to return a 404 when viewed by someone who does not have access to every single marker group on that map.

In my case, the map of the Golden Coast is embedded into the Kathaldir article, which is now 404ing for everyone who does not have access to the two private marker groups on it. Removing the map from the article or making the marker groups public fixes the issue. People having access to all marker groups also do not experience the issue (including myself)

**To Reproduce**
1. Create a map with a private marker group
2. Embed the map into an article using the map embed
3. View the article as a user that does not have access to all marker groups (either by logging out or having an account without the correct subscriber groups)
4. The article will display a 404 error

**Expected behavior**
The page should still display and include the map without the private marker groups.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/4740623/152406511-1ad74e82-45da-454e-87a7-7925628934b8.png)
![grafik](https://user-images.githubusercontent.com/4740623/152406580-1df21606-2467-409a-acf3-bb2cca65811e.png)

**Comment by iamromeo** [comment]
Hmmmm that is indeed very interesting. Thank you @Satrium - I will be on it right away. I think it is related to a recent major codebase change

**Comment by iamromeo** [comment]
FIxed - it will be live within the hour! Thank you for reporting @Satrium
