### ISSUE TITLE
Articles Showing Up in Dashboards of Writers Without Article Access

### ISSUE THREAD

**Issue by L0rdArthas** [worldanvil/worldanvil-bug-tracker#861]
**World Anvil Username**: LordArthas

**World / Campaign / RPG Character / Manuscript Title**: Drifting Worlds (private world)

**Feature**: Dashboard / Co-Authors

**Related URLS** (To public & visible pages add screenshots otherwise): N/A

**Describe the Issue**
Recently created/edited articles show up in the "Continue Working" boxes of Co-Authors set to the "Writer" rank, even if they are not the author of the article. This way "Writers" are able to see titles of articles they should not be able to see.

**To Reproduce**
1. Have at least one Co-Author with rank "Writer"
2. As owner of the world: Create a private article and leave it as WIP and unpublished, save the article
3. As "Writer": Access the worlds dashboard, the article will show up in the "Continue Working" box

**Expected behavior**
Writers should not be able to see articles in their dashboard boxes, that they do not have access to 

**Screenshots**
World owners view:
![Owners view](https://user-images.githubusercontent.com/11505257/152584093-73ab2257-d4c0-4eed-80a3-ddcf42a98c03.jpg)

Contributors view:
![Contributors View](https://user-images.githubusercontent.com/11505257/152584194-986ec0f5-5dba-4993-8a2a-b33839b06c42.jpg)

**Comment by iamromeo** [comment]
Fixed will be deployed today - now only the world owner has access to the **continue working** functionality
