### ISSUE TITLE
Master Timeline returns 404

### ISSUE THREAD

**Issue by DMZimo** [worldanvil/worldanvil-bug-tracker#862]
**World Anvil Username**: Zimo

**World Title**: Numidius

**Feature**: Timelines

**Related URLS**: https://www.worldanvil.com/w/numidius/t/log-of-the-time-keeper-timeline (is currently set to private)

**Describe the Issue**
Trying to access a Timeline called "Log of the Time Keeper" (id: 960f19b3-b582-4c13-aead-4df7e349b815)

**To Reproduce**
1. Go to 'Timelines'
2. Click on one of the 'view/edit' buttons next to Log of the Time Keeper

**Expected behavior**
Simply entering the view and edit versions of the timeline.

**Screenshots**
![image](https://user-images.githubusercontent.com/32243512/152595784-bbe1df83-85b1-4d0a-b8bf-961f25740d6c.png)
![image](https://user-images.githubusercontent.com/32243512/152595842-c8108821-1f97-41d6-b1e2-91b20ae70790.png)

**Comment by iamromeo** [comment]
All fixed - please change your password

**Comment by DMZimo** [comment]
Confirmed working.
Password changed.
Thanks!
