### ISSUE TITLE
Player Sheet view: Tracker viewable by everyone?

### ISSUE THREAD

**Issue by Tillerz** [worldanvil/worldanvil-bug-tracker#864]
**World Anvil Username**: Tillerz

**World / Campaign / RPG Character / Manuscript Title**: 

**Feature**: Tracker sheet

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/hero/6aba164c-aeea-4bbb-b4c5-9ccaf77a0886

**Describe the Issue**
It seems like the tracker on someone's player page is visible to everyone.

**Comment by iamromeo** [comment]
Apparently that was always a thing .... no idea why - fixed now will deploy later today
