### ISSUE TITLE
Request for System Addition: Ars Magica 5th Edition

### ISSUE THREAD

**Issue by ForeverRonin** [worldanvil/worldanvil-bug-tracker#865]
**World Anvil Username**:flyer777

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: Add the Ars Magica 5th Edition System to World Anvil with Awesome Character and Campaign Support

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.atlas-games.com/product_tables/AG0205

I don't know what else to add here, but thanks for making such a cool program. I think it will make Ars sooo much fun to play.

**Comment by iamromeo** [comment]
Hey flyer777! 

Ars Magica is already in the list, what am I missing here ? :)
