### ISSUE TITLE
Youtube video for family trees covering the content to use it 

### ISSUE THREAD

**Issue by Mouse116** [worldanvil/worldanvil-bug-tracker#866]
**World Anvil Username**:
Mouse116

**World / Campaign / RPG Character / Manuscript Title**:
Gaia

**Feature**: 
Family tree

**Describe the Issue**
The Youtube video that show you how to use the family tree is covering the first part to make a family tree. So it impossible to put in the mother or father, just the extened family and i can not get the link to make the family tree from there. i have been unable to remove the video.

![world anvil](https://user-images.githubusercontent.com/99355313/153260656-21fad9d9-67e8-4bb7-95ea-6c7d4cada8b4.jpg)

**Comment by Kordishal** [comment]
That is on purpose. Free users do not get access to Family trees. They are a feature for Master+ subscribers.
