### ISSUE TITLE
The basic character history is not readable because of the white background and nearly white font

### ISSUE THREAD

**Issue by Hertzbube** [worldanvil/worldanvil-bug-tracker#87]
**Hertzbube**:

**Character Elena Lichtherz- Rosematt from the World of Iriel**:

**https://www.worldanvil.com/hero/4b562472-e682-40c6-abf9-b95cb5ad1b11** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Because of the white background and nearly white or light gray font it's not possible to read the history entry without effort.

**To Reproduce**
1. Look out or a World with additional characters (under the index tab "characters")
2. Look at the history entries

I think it is possible to change the appearance if you are a master or higher, but not if you are under the journeyman.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/80397163/112003261-08a2ca00-8b21-11eb-9c16-a209dfe04622.png)

**Comment by iamromeo** [comment]
Hey @Hertzbube just a note here to let you know that we are working on this
