### ISSUE TITLE
NPC Secret Notes

### ISSUE THREAD

**Issue by POHarmony** [worldanvil/worldanvil-bug-tracker#872]
**World Anvil Username**: Page of Harmony

**World / Campaign / RPG Character / Manuscript Title**: Suveon / Suveon Campaign / Kymma Zenakis / Basic NPC Profile

**Feature**: Secret Notes

**Related URLS** (To public & visible pages add screenshots otherwise): 
![image](https://user-images.githubusercontent.com/99561214/153727872-93a73a1d-7eef-4042-906b-4f43c5674d45.png)
![image](https://user-images.githubusercontent.com/99561214/153727881-0a1376b9-b397-4827-a93b-a55205d4a052.png)

**Describe the Issue**
The text box formatting tools do not seem to be working in this box. All that happens when I use them is that they are put on the viewing screen as text instead of doing things like underlining or line breaks, etc. I understand from a question that I posted on Discord that this is the BBCode.

**To Reproduce**
Steps to reproduce the behavior: Inputting formatting for text/paragraph does not work in this box. 

**Expected behavior**
I expect to see line breaks when [br] is input. I expect that a word with [u] word [/u] to be underlined rather than show the formatting commands.

**Screenshots**
See screen shots above.

**Comment by iamromeo** [comment]
Fixed will be deployed today

**Comment by POHarmony** [comment]
Thank you so much!
