### ISSUE TITLE
Button text and background both dark. Cannot read

### ISSUE THREAD

**Issue by QuantumBob** [worldanvil/worldanvil-bug-tracker#874]
**World Anvil Username**-QBob

**World / Campaign / RPG Character / Manuscript Title**:Sheet = MOLVOT MALSEN Non Player Character NPC (2020)

**Feature**: BB Code buttons

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Both the buttons and the text of the buttons are dark so difficult to see text on button.

**To Reproduce**
1. In dark mode
2. Create Non Player Character NPC (2020) Dungeons and Dragons 5e sheet
3. Scroll down to "Description" text edit section (all others are the same)
4. The buttons to add BB code are impossible to read as the colours of the text and button are both dark

**Expected behavior**
In dark mode text should be light and in light mode text should be dark.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

![WA error](https://user-images.githubusercontent.com/12417271/154148396-54208a41-069c-4845-91d8-68d85357a6ca.png)

**Comment by Kordishal** [comment]
That is a community made sheet. Probably not much that can be done about this. The sheet is probably optimized for light mode.

@Tillerz Created this sheet. Maybe he'll have a look.

**Comment by Tillerz** [comment]
Fixed.
