### ISSUE TITLE
"Go to..." feature missing

### ISSUE THREAD

**Issue by Catoblepon** [worldanvil/worldanvil-bug-tracker#876]
**World Anvil Username**: Catoblepon

**World / Campaign / RPG Character / Manuscript Title**: Worldanvil interface

**Feature**: "Go to" (down "Continue working...")
**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/dashboard/

**Describe the Issue**
Down the "Continue working..." there is usually a box saying "Go to..." and is linked to the latest article from your world that you saw. Since the lasts days (at least three), the box is empty, laking the link and the title "Go to...". It happens to other people, not only to me.

**To Reproduce**
1. Open sidebar from the worldanvil's interface
2. Look down "Continue working..."

**Expected behavior**
Should appear a text saying "Go to..." and the title of your article. When clicking it, it should open the article.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Captura](https://user-images.githubusercontent.com/55326820/154457033-675da09a-0f49-41ab-bb76-5eb9f55f4d24.PNG)

**Comment by Kordishal** [comment]
It will appear once you visit a page within that world. The field is cleared when switching the world. The space is reserved to ensure that the sidebar does not jump when loading this in as it is loaded after the rest of the sidebar is loaded.

Or do you never get something in there?

**Comment by OndoAlvelle** [comment]
Hi, Ondo here. @Catoblepon reported the bug after she came to me and I realized I could reproduce it, as shown in the following gif (ignore the weird visual glitches, that's the screen recording software):

![go to bug](https://user-images.githubusercontent.com/79748701/154675176-0e4881f5-c96e-4b86-acb9-6b1b9e8fa65f.gif)

As you can see, the "go to" box is empty at the beginning of the gif. After viewing an article and going back to the dashboard, it shows up correctly. However, **after reloading the page**, it disappears. For me, this started happening on the 11th or 12th, after what seems an update or bug fix to that feature (according to the #dev-changelong). Let me know if you need more details (or feel free to DM on Discord too).
