### ISSUE TITLE
New article cannot be viewed, previewed or mentioned properly.

### ISSUE THREAD

**Issue by Dallasv** [worldanvil/worldanvil-bug-tracker#877]
**World Anvil Username**: Aramec
**World / Campaign / RPG Character / Manuscript Title**: Geron

**Feature**: Article creation

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Since accidentally upgrading to Sage last weekend, I now experience the following problems:
1.  When creating articles from a mention on a page, attempting to preview or view the article gives me an Error 404.  The article does get created, but I only know that from going and trying to look at the article.  The slug generated by this will be the article name without any appended article type.  So if I create 'smoke mirror way' then the preview URL I get is 'smoke-mirror-way' and not 'smoke-mirror-way-articletype'.
2.  The @mention will not inherit the article URL.  clicking on the @mention will bring me to a new article creation page where I begin again at Step 1.

This happens regardless of the article type, whether I'm in incognito mode or not, whether I log out and log back in, whether I'm using chrome or edge, and regardless of what article type I use for the original and mentioned article.  I can always reproduce it.

I was downgraded back to Grandmaster which I was hoping would fix this problem, but it still persists.

**To Reproduce**
I think this is specific to my world/account.

**Expected behavior**
A created article should be previewable or viewable from the article editor without a 404 error and the @mention should then lead to that article instead of to the editor to make a new article.

**Screenshots**

**Comment by Kordishal** [comment]
This happens when the article does not have a proper slug available. To fix this you have to change the title and have the article save. Then you can change the title back and wait until it saves as well. 

Not sure under which circumstances this happens as I've only very rarely experienced this.

**Comment by Dallasv** [comment]
I'm pretty sure it's because the automatic slug generation got borked when I was temporarily Sage.   The URLs that are created when I create an article no longer have the article type appended to the article name and it's creating errors.   I agree that the problem is that the proper slug is not available.  However, the proper slug is also not being generated anymore.

**Comment by Dallasv** [comment]
This happens any time I make any article with any name, but ok.

> This happens when the article does not have a proper slug available. To fix this you have to change the title and have the article save. Then you can change the title back and wait until it saves as well.
> 
> Not sure under which circumstances this happens as I've only very rarely experienced this.

I'm pretty sure it's because the automatic slug generation got borked when I was temporarily Sage. The URLs that are created when I create an article no longer have the article type appended to the article name and it's creating errors. I agree that the problem is that the proper slug is not available. However, the proper slug is also not being generated anymore.

Do you want me to create a new issue since this one is closed?  It's quite a serious issue for my ongoing ability to use WA.

**Comment by Kordishal** [comment]
No, but that does sound like a lot more serious, but just something with your account. You'll probably have to give access to Dimitris to your account for him to able to track this issue down.

**Comment by Kordishal** [comment]
@ Dimtris: When you are reading this. Please message me so I can talk to you. The issue is very weird and hard to describe. You've got access to the World as editor (Geron).

**Comment by GorkamWorka** [comment]
@Dallasv i cannot reproduce outside of your world so i gonna need access to that world for tests. can you add me as Co-author ?
-> https://www.worldanvil.com/author/GorkamWorka

**Comment by iamromeo** [comment]
@Dallasv is this still an issue ? Can you please update us within the next 24 hours please?

**Comment by Dallasv** [comment]
It's definitely more than 24 hours later, but yes, unfortunately it's still
an issue.

**Comment by Kordishal** [comment]
Does Dimitris still have access to your world?

**Comment by Dallasv** [comment]
Hi Jonas,

Happy Tuesday.

Yes he does!
