### ISSUE TITLE
Dimday Red RPG System

### ISSUE THREAD

**Issue by spirton** [worldanvil/worldanvil-bug-tracker#878]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name (RPG SYSTEM)**: Dimday Red RPG System
**List Name** (Name under which it should be listed on World Anvil): Dimday Red
**World Anvil Username**: 1sickpuppy

**Website**: www.dimday.red

**Logo Image Link**: https://static.wixstatic.com/media/3cafad_a565b67b139b43f0a638ad5e79d76a3f~mv2.png/v1/fill/w_1852,h_356,al_c,q_90,usm_0.66_1.00_0.01/logo_long.webp

**Logo Usage Terms (URL)**: Not sure abut this. You can use the logo as you need.

**Comment by iamromeo** [comment]
All done and the system will also have its logo by tomorrow. 
@spirton I have messaged you on Facebook but I would very much like to talk to you guys.

**Comment by spirton** [comment]
Hey Dimitri, I wish you are well! I have been trying to reach you through Facebook but had no luck. Please let me know if you will be available for a chat sometime this week. Cheers!

**Comment by spirton** [comment]
@iamromeo sorry don't know if I should have tagged you in the previous message :)
