### ISSUE TITLE
My plot articles are not available from the plot link under campaign in the link tree on the left of the dashboard

### ISSUE THREAD

**Issue by thwingster** [worldanvil/worldanvil-bug-tracker#879]
**World Anvil Username**: FultonsNewestKicks

**World / Campaign / RPG Character / Manuscript Title**: Myral

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/heroes/campaign/plot/list
![Campaign Shortcut](https://user-images.githubusercontent.com/100059378/154828830-c88a5a44-8a0d-4820-86c6-d26268804b4a.jpg)

**Describe the Issue**
When I click the plots link under the campaign shortcut on the left side of the page I get a page that says: 
"This page isn’t working
www.worldanvil.com is currently unable to handle this request.
HTTP ERROR 500"

The articles are available when I follow the links in the article list however
![Article List](https://user-images.githubusercontent.com/100059378/154828817-6216c067-23e8-4001-bf35-6643a41d9470.jpg)

**To Reproduce**

**Expected behavior**
The link used to take me to a page that showed my plots in a tree structure

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
This means that there is some kind of loop in the plot tree that prevents the tree from being generate. Attempt to remove connections until the page renders again. After that you can carefully rebuild the tree.
