### ISSUE TITLE
Variable Bugs

### ISSUE THREAD

**Issue by Shaudawn** [worldanvil/worldanvil-bug-tracker#88]
I think I broke some variables.  I have created one collection that seems to work as intended.  But a second collection renders the entire Value on the page, not just as a title and a tooltip.  It is a collection of Advanced Terms.  

The difference (I suspect) is that I added a prefix to the collection (since I might use the same kind of terms in other worlds).  I've since removed this prefix in an attempt to fix the problem, but I still get the same result--much of the Advanced Term's Value is being displayed like a tooltip and not just the Title.  When I do a mouseover of that text, a tooltip popup appears with the first amount of text that was entered into the Value field.  

I can see displayed an HTML close-out tag ('>) before it then outputs the Title text.  

I thought that maybe this was an issue with using a single quote that messed up the conversion to HTML, but I have since created a couple of test variables without that punctuation, and I get the same result.  I have been using the Euclid editor.  Both using the [ to get the variables and by directly copy-pasting it into the article.  The same result occurs.  

The Rendered Fragment test seems to work fine.  The Simple and Advanced Terms do not.  I've not tried Link or Number variables yet.

Article where it occurs: @[Akaun](person:f1641077-cfd3-4279-bba9-0f11082f8c83)
https://www.worldanvil.com/w/e-er-all-shaudawn/a/akaun--person

**Comment by iamromeo** [comment]
This is a duplicate of #77

**Comment by Shaudawn** [comment]
@iamromeo 
I'd like to suggest a reopening of this bug.  The Advanced Term is now fixed, which is the subject of #77 (thanks, didn't realize it was a duplicate).  However, the **Simple Term** is still having this problem.  

Furthermore, _I was able to add an HTML tag_ into a variable Value.  I don't think it's a security issue--I couldn't inject a JavaScript alert--but it may not be desirable.  

To reproduce:

1. Create a Simple Term
2. In Title field, add name such as "Test Simple String 2"
3. In the Value field, add the following:

```
Testing Simple Term

Yes/No/Maybe

The apostrophe goes here ' and there it is.

Testing HTML injection:  <b>BOLD</b> 

Testing js injection: <script>alert("security flaw")</script> 
```

**Comment by iamromeo** [comment]
Thank you @Shaudawn I will be looking at this asap.

**Comment by iamromeo** [comment]
@Shaudawn I am deploying a new version -  this should now be fixed.

**Comment by Shaudawn** [comment]
A third test of the Simple Term shows that it will still break if the user inputs multiple lines with one line consisting of just a break.  But the HTML now gets sanitized.

This user entry into the Value field will _not_ break the variable:
```
Testing Simple Term 3 
Yes/No/Maybe
The apostrophe goes here ' and there it is.
Testing HTML injection:  <b>BOLD</b> 
Testing js injection: <script>alert("security flaw");</script> 

```
However, this will break it:
```
Testing Simple Term 3 

Yes/No/Maybe
The apostrophe goes here ' and there it is.
Testing HTML injection:  <b>BOLD</b> 
Testing js injection: <script>alert("security flaw");</script> 
```

This second input only differs with a blank line.  It outputs as this:
`  Yes/No/Maybe The apostrophe goes here ' and there it is. Testing HTML injection: <b>BOLD</b> Testing js injection: <script>alert("security flaw"</script> ">Test Simple String 3`

So, a little insignificant bug, but at least it won't cause any potential security issues.

Thanks!

**Comment by iamromeo** [comment]
![Screenshot 2021-03-25 at 05 57 25](https://user-images.githubusercontent.com/660175/112416754-fb5b2a80-8d2e-11eb-9468-d40cd11aef8c.png)

Hey @Shaudawn  I do not seem to be able to replicate the last usecase (see above) 
What am I missing?

**Comment by Shaudawn** [comment]
For me, if I leave a blank line, I get the bug output.  This is the simple term input:

![simple_term_bug88](https://user-images.githubusercontent.com/81183703/112418919-a6e08c80-8ce7-11eb-97ff-4866933b1430.png)

This is how it is rendered in Firefox (not yet cross-browser tested):

![simple_term_bug88_output](https://user-images.githubusercontent.com/81183703/112419191-338b4a80-8ce8-11eb-81b0-1e9166be5472.png)

Although my input here is two empty lines, it also breaks with at least one.  There is no issue when all of the lines have some character in them.

I've moved to a test article: https://www.worldanvil.com/w/e-er-all-shaudawn/a/test-platform-article?preview=true

**Comment by iamromeo** [comment]
Good morning @Shaudawn I have re-written this system and brought it in par with the article tooltip system. I am. closing this because there want be any direct correlation. 
If you find another issue , please let me know by opening another issue.
