### ISSUE TITLE
Health and resources tracker D&D 5e

### ISSUE THREAD

**Issue by FemkevKeulen** [worldanvil/worldanvil-bug-tracker#882]
**World Anvil Username**:
FictionFan1995

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 
Health and resources tracker

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When I play D&D, the campaign usually lasts longer than a one-evening session, so in-between, I need to save which resources I've used and how many HPs I have. I recently started using the new 2020 5e character sheet, and I've since found that while my HPs and remaining spell slots are saved correctly, when I reload the page, or close it down and open it later, the class resources are reset to the max, no matter how often I press "save changes".

**To Reproduce**

**Expected behavior**
Not much to add here, except that the resources and notes should be saved when pressing "save changes".

**Screenshots**
My health and resources when I finish the session and save them for the next time:
![Screenshot before reloading](https://user-images.githubusercontent.com/100145557/154983099-1eed451f-25a4-4d7b-8115-32e93f5709ff.png)

My health and resources after reloading or re-opening the page:
![Screenshot after reloading](https://user-images.githubusercontent.com/100145557/154983154-78f63496-f5e4-4bc1-afd3-d39489c47a5c.png)

**Comment by Tillerz** [comment]
Fixed. NOT working for the 2 additional resources I have just added, which is weird because this is a look and using the same code for all 6 fields. But I'll get those to work, too.

**Comment by Tillerz** [comment]
Fixed the saving of resource 5 and 6, too.
