### ISSUE TITLE
Global Options>WA Community Social Features turn off after upgrade to Eternal GM account

### ISSUE THREAD

**Issue by Arghantyr** [worldanvil/worldanvil-bug-tracker#885]
**World Anvil Username**: Angantyr

**World / Campaign / RPG Character / Manuscript Title**: Ædeos

**Feature**: Global World Settings

**Related URLS** (To public & visible pages add screenshots otherwise): N/A

**Describe the Issue**
Comments, Likes, Read Later, Follow gets ticked off (disabled) after upgrade to Eternal Grandmaster account.

**To Reproduce**
0. Make sure you are running on a non-eternal account (this was tested on Master Yearly and Grandmaster Yearly)
1. Make sure Comments are enabled Globally (Global Options>WA Community Social Features) and Locally (Edit Article>Preferences>Allow Comments) on a selected article
2. Go to the selected article and scroll down to the Comments section to verify Likes, Follow, Comments, Read Later are visible
3. Upgrade to Eternal Account (tested on Eternal Grandmaster)
4. Go to the selected article and confirm the Comments, Likes, etc. are not visible

**Expected behavior**
The Settings are not affected by the upgrade to the Eternal account.

**Screenshots**
N/A

**Comment by iamromeo** [comment]
That is a bit more complicated than that - it was not the upgrade that caused the problem but due to the payment issues there was some forced resetting of settings - :P
