### ISSUE TITLE
Secret tab name displays variable

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#886]
**World Anvil Username**: SoulLink

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/the-multiverse-hedgehawk/a/grand-portwai-aux-renags-settlement

**Describe the Issue**
When embedding a secret the tab name of the secret has called SECRET.NAME instead of the actual name.

**Screenshots**
![image](https://user-images.githubusercontent.com/14262536/155372008-66623074-69b4-4f81-9de7-556fdce037f7.png)

**Comment by iamromeo** [comment]
Fixed will deploy
