### ISSUE TITLE
PDF Viewer not displaying PDFs

### ISSUE THREAD

**Issue by BTLOTM** [worldanvil/worldanvil-bug-tracker#887]
BTLOTM

The World of Algaress, Character page:  Alana Fastbender (https://www.worldanvil.com/w/algaress-btlotm/a/alana-fastbender-person)

PDF Viewer 

Related URLs:  https://www.worldanvil.com/w/algaress-btlotm/a/alana-fastbender-person, https://drive.google.com/file/d/1-BquWQosdYZ56kCrSiiPyLxTN-NmbWuE/preview?usp=drivesdk

I am unable to use the PDF viewer on any page to show a PDF.  I've tried my own PDFs from google drive with the suggestion I got from discord to ""Use preview instead of edit in the URL. It will work." ... so /preview?usp=drivesdk instead of /view...", both ways it doesn't show.  I also tried the following URLs:  https://media.wizards.com/2019/dnd/downloads/UA-ClassFeatures.pdf and https://www.orimi.com/pdf-test.pdf and neither will show either.  I also had another user (Graylion) test the same links on their W.A. pages and it worked properly for them.  The only difference we could find is that Graylion is a Worldsmith of the Inner Sanctum and I am a Master Worldsmith, so we were wondering if it just might not be permissioned correctly across the board.

**Comment by graylion-wa** [comment]
This is a article in my world with the same pdf link provided from above which does display.

[Test PDF Character](https://www.worldanvil.com/w/creation/a/test-pdf-character-person)

**Comment by Kordishal** [comment]
All three example licks work for me. The announcements says that it is available to all subscribers so they should definitely work for you.

But I just had another master subscriber test it and they don't work for them either. So it does seem to be the case that the permissions on this feature are not setup correctly (assuming the announcement was correct). 

I did not check if journeyman can use them.

**Comment by iamromeo** [comment]
There was an issue with the permissions. this will be available ot masters in teh coming hours
