### ISSUE TITLE
Timelines bug and ideas

### ISSUE THREAD

**Issue by neoblanks** [worldanvil/worldanvil-bug-tracker#888]
**World Anvil Username**:

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by neoblanks** [comment]
there is no way to delete an event in the timeline. also i cant seem to make the event not public. it would be easier if i was able to "attach" an event to a time line like drag and droping it in.

**Comment by Kordishal** [comment]
There is a delete button on the event when looking at the timeline though

![image](https://user-images.githubusercontent.com/14262536/156002232-fe8f8502-047e-4bd1-abd8-d222d9114339.png)

The same applies to the events on the view side on the timeline. You just have to hover over the event for the button to show up.

Events can be made private with a subscription. When editing the event press the Show Additional Options at the bottom of the editor form and there is the option way at the bottom.

Drag & drop for the timeline editor would really work the way it is built right now and it would be a feature suggestion and not a bug report.
