### ISSUE TITLE
Broken Image in Item Stat Block

### ISSUE THREAD

**Issue by randalldr** [worldanvil/worldanvil-bug-tracker#89]
**Chessdan**:

**World / Campaign / RPG Character / Manuscript Title**:

**Item Stat block**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When creating an item stat block the image shows as a broken link.

**To Reproduce**
1. Go to the item stat block tool and complete the basic information section.
2. Go to the images and files feature and upload a PNG of the appropriate size.
3. Copy the image ID by clicking on the image preview.
4. Return to the item stat block tool and paste the image ID from the clipboard in to the image field.
5. Sample image ID is [img:2114223].
6. Save and attempt to view the stat block.
7. The image appears as a broken link.
8. Several variations of deleting the image, stat block, removing file name spaces and trying again were not successful.
9. Thank you :)

**Expected behavior**
After adding an image to the stat block with the image ID (see above) that image should image should be viewable as part of the item stat block.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/61250292/112073242-eadd6100-8b30-11eb-9731-cefbfc16c5dc.PNG)

**Comment by Tillerz** [comment]
Hello Chessdan, only enter the number, not the [img: ] portion. But I'll change it so it will work better. :)

**Comment by randalldr** [comment]
Hi Tillerz, thank you that worked.
