### ISSUE TITLE
Case_D20

### ISSUE THREAD

**Issue by CaseD20** [worldanvil/worldanvil-bug-tracker#890]
**World Anvil Username**:

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Were you trying to make a bug report? If so you will need to actually fill it out. You can edit the message and the title. IN the meantime I will close this,
