### ISSUE TITLE
Manuscripts Error: Text parts have no content under them (but really they do)

### ISSUE THREAD

**Issue by FibroJedi** [worldanvil/worldanvil-bug-tracker#891]
**World Anvil Username**:
FibroJedi

**World / Campaign / RPG Character / Manuscript Title**:
Qal'ath - (Manuscript: Finding His Place)

**Feature**: 
Manuscripts > Review

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When I go to the "Review" tab in Manuscripts I see the error: "Nothing to review! Text parts have no content under them."

I am also enclosing a screenshot of JavaScript errors from Developer Tools (Firefox).

**To Reproduce**
1. Go to Manuscripts
2. Click on a text entry under a chapter that has content in it.
3. Hit "Review" in the top right.
4. See error "Nothing to review! Text parts have no content under them."

**Expected behavior**
Something to review?

**Additional Notes**
I reached out on Twitter initially (I'm having problems signing up to Discord) in case it was "user error" and I was putting the content in the wrong place. But when I use the "read" tab in Manuscripts, the text is there. Madeline suggested I sent a bug report, so I'm following their advice.

**What I Have Tried**
In the event I was blocking some function or other, I have disabled adblock and tracker blocking and neither improved or changed the situation, so I cannot see that it is something my end.

**Screenshots**

![World Anvil Manuscripts Report](https://user-images.githubusercontent.com/69349920/156452382-2899b688-610b-42ec-81e3-7c341d160a3b.jpg)
![WorldAnvil Manuscripts Report JS Errors](https://user-images.githubusercontent.com/69349920/156452386-a804e6b7-cf68-4481-a5cb-1d49866f7551.jpg)

**Comment by iamromeo** [comment]
Review is used with FOLDERS not PAGES :) you have a page selected.

**Comment by FibroJedi** [comment]
Thank you. Maybe that error message could be updated when a folder is
selected then? :)

**Comment by Kordishal** [comment]
You mean that the message should say that you need to select a folder?

**Comment by Kordishal** [comment]
That makes sense yeah:

For Dimitris:

`Please select a folder to review! Text & image elements can have no content under them.`

Something like this
