### ISSUE TITLE
Pricing page, page shows it's a recurring subscription for lifetime

### ISSUE THREAD

**Issue by MJHeijster** [worldanvil/worldanvil-bug-tracker#893]
**World Anvil Username**:
MoonRaven

**Feature**: 
Pricing
**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/pricing

**Describe the Issue**
When you click lifetime, it shows the label " Hey there! What you're purchasing is a recurring subscription, which means you will be charged you today and continue to be charged for your chosen period until you cancel your subscription. You can cancel anytime from your Account Details page. As this is a digital product which is delivered immediately, we are unable to offer refunds. " This may cause some confusion.

**To Reproduce**
1. Go to https://www.worldanvil.com/pricing
2. Click on lifetime
3. Scroll down to the bottom
4. See label

**Expected behavior**
Click lifetime, label poofs out of existance.

**Comment by iamromeo** [comment]
Considering that the recurrence is set to lifetime - yes it is true - in case of reincarnation you will have to be charged again.
