### ISSUE TITLE
Typo in "Welcome to World Anvil - READ ME FIRST"

### ISSUE THREAD

**Issue by jackie1776** [worldanvil/worldanvil-bug-tracker#894]
**World Anvil Username**: jackie1776

**World / Campaign / RPG Character / Manuscript Title**: Freeland

**Feature**: Article

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/world/3af317ed-a9d0-402e-b0ee-2431e53dfd50/summary

**Describe the Issue**
Text says "If you don't have your own map but you want to create one and do **knot** know how"
"knot" should be "not"

**To Reproduce**
From Dashboard click "Welcome to World Anvil - READ ME FIRST" article

**Expected behavior**
For there not to be typos or spelling errors

**Screenshots**
[Screenshot 2022-03-04 220753](https://user-images.githubusercontent.com/100982234/156865482-ed1b5638-14a6-43d9-812e-70dbd0c7ce31.jpg)

**Comment by iamromeo** [comment]
Thank you Jackie! - Will be deploying later on today
