### ISSUE TITLE
deleted a tutorial I no longer needed, lost 5,100+ words of detailed worldbuilding

### ISSUE THREAD

**Issue by imitationcamel** [worldanvil/worldanvil-bug-tracker#896]
**World Anvil Username**: Imitationcamel

**World / Campaign / RPG Character / Manuscript Title**: Paan Atta

**Feature**: Everything

**Related URLs** (To public & visible pages add screenshots otherwise): I am so sorry, I can't I couldn't screenshot anything before I lost it all. I hate myself for letting this happen.

**Describe the Issue**
A clear and concise description of what the issue is.

I was going through the world that I was writing and organizing with your beautifully user-friendly and detailed website, looking over the worldbuilding articles I had shared with friends and family to their delight. For some reason, I found among these articles something like "welcome to world anvil here's how to get started". As if it were an article I had written. Since its contents were things I was already aware of and it kept coming up in the section of the fictional world I was writing, including in the list of articles on the world intro, yet it was unrelated, I decided to delete the tutorial I no longer needed that was listed under the articles I had written for this world. 

Here's where the error started. As soon as I did this, I went back to work on my other articles and their pages no longer existed, coming up as an error 404. Even the world itself was somehow listed as archived by me. I did no such thing! I kept trying different devices, refreshing and refreshing the page, closing and re-opening the site, absolutely nothing worked. 

**Apparently, because I tried to remove a tutorial I no longer had need for, I lost countless hours spent worldbuilding. I lost over 5,100 words and information that I had not stored anywhere else. I have no idea why or how I could have thought to screenshot these articles I had access to on several devices and double-saved several times, with no looming threat of loss or deletion.**

**To Reproduce**

**Expected behavior**

I expected the tutorial I no longer needed to be deleted in a normal way, and the entire world I had spent hours on to not be archived.

**I suggest that like google docs and email you create a sort of trash bin in the case of unintentional or errored deletions like this so I don't lose 5,100+ words in one easy to make mishap. I am so sorry for bothering you and for messing everything up like I did. I ruined hours of work with a single click, and I have no idea how I could have predicted, stopped, or prevented this. I put so much time and effort, so much planning into this, and my loved ones enjoyed it and found it so useful. And now it's all gone. Everything I did, everything I worked for is gone forever. Is there something you can do, anything to somehow bring my work back, even transcripts of it or something, anything, so I can even begin to rebuild what I had. I am so so very sorry. Please, is there anything you can do? Again, I am so sorry. I'm 16 and autistic, I share my writing with my parents and grandparents, and I'm so anxious about having to explain to them why the wonderfully organized articles I sent them suddenly turn up 404s.**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Hi!

It is always very frustrating when losing content. However, deleting one article will not just another. The tutorial articles are created on world creation automatically.

That being said when I look up your account name you do not seem to have any world. A world with the name Paan Atta does not exist either.

Could you have deleted the world instead of the article by accident? Because your account found here does not have any content?

https://www.worldanvil.com/author/Imitationcamel <- this is your account right?

That would explain why all your articles disappeared when you only wanted to delete one article. 

Whether this is possible to restore depends on Dimitris. So I cannot tell you about that and you will have to have some patience until he responds.

**Comment by imitationcamel** [comment]
Thank you so much, it means so much to me, you are the kindest, and it
shall never happen again. My, what a fool I am, and what a generous patron
you are of my creations. I apologize strongly for the inconvenience and my
lack of technological education. I am bewildered by this second chance. 🙏

**Comment by iamromeo** [comment]
I am really sorry - I just saw your reply - I am so very glad to hear that everything is there. Also I just noticed you joined the guild. Thank you so very much for your support <3

**Comment by imitationcamel** [comment]
Thank you for your response, I hope you enjoy Purim today and the weather
