### ISSUE TITLE
Image Link Breaks

### ISSUE THREAD

**Issue by michaeltenner** [worldanvil/worldanvil-bug-tracker#897]
**World Anvil Username**: MikeTenner

**World / Campaign / RPG Character / Manuscript Title**: Stargazers

**Feature**: Homepage -> Custom Content

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A BBCode image link breaks after saving. Save and return to the page yields a broken mess that has to be fixed from scratch every single time. This bug being present on the **homepage** is detrimental to comfort and ease of use.

**To Reproduce**
1. Go to Homepage -> Custom Content2. 
2. Into any of the boxes add a BBCode image link: [url=https://www.worldanvil.com/world/image/list][img:82765|nolink][/url] 3. 
3. Click 'Save Changes'4. 
4. Return

**Expected behavior**
It working normally, not breaking.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

<img width="265" alt="Screen Shot 2022-03-06 at 8 05 06 PM" src="https://user-images.githubusercontent.com/101064418/156938194-b5eb67b8-d087-4f08-852d-b680724906b7.png">
<img width="262" alt="Screen Shot 2022-03-06 at 8 05 32 PM" src="https://user-images.githubusercontent.com/101064418/156938207-44b59d10-b0be-4426-aaab-185f6a5384b8.png">

**Comment by Kordishal** [comment]
Hi, the mess is created by the editor you have enabled. You should switch to the Euclid editor. Check [this guide](https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors) on how to do that.

Furthermore this is the old way of doing this (including the old syntax of the url BBCode with the `=` sign). It is possible to just add the link to the image in the Advanced Edit section of the image. With the field LINK URL. Go to the Images interface and then select the image you want to add the link to. Then press the Advanced Edit button to the right.

**Comment by michaeltenner** [comment]
I do not feel comfortable using the EUCLID editor. It's complicated and I do not know how to use it properly.
Further, this is the way listed on World Anvil Codex, I would suggest updating the guide if there is a better way to do this.

Seeing a bug be solved as "yeah, it happens" is concerning.

**Comment by Kordishal** [comment]
The Plato editor doesn't support any kind of fancy / advanced BBCode (including nested stuff like this). The Plato Editor will be reworked (there are other issues with it that need to be resolved), but this is unlikely to be added to its feature set. Plato editor is only intended for very basic formatting.

Thank you for the heads up on the guide. I have added a note that this is the old way of doing this and how to do it the new way.
