### ISSUE TITLE
World Anvil: Images I have embedded below text in my articles pop out of speech bubbles.

### ISSUE THREAD

**Issue by Grimmibo** [worldanvil/worldanvil-bug-tracker#898]
**World Anvil Username**: GRIMMBO

**World / Campaign / RPG Character / Manuscript Title**: VALADAR

**Feature**: Image embedding/ speech bubbles when hovering over linked articles.

**Describe the Issue**: I keep having this problem where if I hover over an article name in view mode, if it has an image embedded below the text, the first time I hover over it the image sticks out of the speech bubble thing that pops up, making it so that if I try to click on said link, it just directs me to a page of the image by itself. Is there a way to fix that? Right now I have to hover over the link twice to get the image to stay in the speech bubble and allow me to click on the article I was hovering over, which is annoying.

**To Reproduce**
1. Go to any article with a linked article alongside the sidebar.
2. Hover over a linked/related article within the article clicked on.
3. See error

**Expected behavior**
I just want the image to not overlap with the speech bubble the first time I hover over it.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Image_overlap_problem](https://user-images.githubusercontent.com/101070225/156944866-101e46c2-c0d8-4a04-b483-e4dd9de05c54.png)

**Comment by iamromeo** [comment]
hmmmm I cannot replicate this - can we have an example?

**Comment by iamromeo** [comment]
Closed due to lack of feedback

**Comment by Grimmibo** [comment]
Hey there,

So I would be able to make public/link my world that has the issue. Would that work for the purposes of an example you can look through? And how would I go about linking it; will just a straight link from the article itself will work?

As for a screenshot of what the current main heading of the article in edit mode looks like, here's what I've got. Sorry, I'm not knowledgeable of what BBCode is, I just noticed this odd bug and they recommended I report it here from the WorldAnvil discord.
![Edin Arturus Error - Copy](https://user-images.githubusercontent.com/101070225/160080407-4bca254a-010a-4ea6-a649-1aecfce90d00.PNG)

**Comment by Kordishal** [comment]
That icon there means that the image is not properly embedded in the plato editor. Its strange that it even shows in the article. Basically it should be showing in the editor.

The likely issue is that you have not just the id, but the full BBCode in the ID.

`[img:1234]`   <- this is what it should look like


You likely have some extra `%` and letters where only numbers should be.

When you press `>_` on the toolbar you can see the code. Remove any non-numbers between the colon `:` and the closing bracket `]`. Then it should display in the editor as well.

Then check again if the issue persists.

If it is still an issue then please just post a link to the article with the link inside.

**Comment by Grimmibo** [comment]
Oddly enough, after re-inserting the image without choosing an alignment, the bug seems to have stopped. I checked the other images that had the same bug, and it looks like this might be what made this happen:

'[img:3093223|center]'

Maybe this bug is occurring because when inserting these images, something is wrong with the 'align' section?

**Comment by Kordishal** [comment]
Nope works fine for me: 
![image](https://user-images.githubusercontent.com/14262536/160162848-b4b8de8a-b0e0-4ce0-82af-8ad033b819a9.png)

Does the image now properly display in the editor?

And I really think a direct link to the article would be the best to help us figure out what the problem is.

**Comment by Grimmibo** [comment]
Weird. Also it properly displays now that I removed the center bit. Here you go, I'll link an article that is still bugged. Hover over 'Antonio De Leon'.

https://www.worldanvil.com/w/valadar-grimmbo/a/the-shylo-castilca-kingship-isles-organization
