### ISSUE TITLE
Inconsitent behavior for Table Custom CSS

### ISSUE THREAD

**Issue by StefanDamberg** [worldanvil/worldanvil-bug-tracker#899]
**World Anvil Username**: Stiefel

**Feature**: Custom CSS / Table

**Related URLS** (To public & visible pages add screenshots otherwise):
Tables after loading the page
![TableCssPageLoad](https://user-images.githubusercontent.com/8058210/156946449-39bae28a-1103-4069-af16-fc357b8bf74b.jpg)
Table after updating CSS
![TableCssAfterUpdatingCSS](https://user-images.githubusercontent.com/8058210/156946452-dce64427-fcc0-4124-9376-6aad9f1ebceb.jpg)

**Describe the Issue**
The CSS used by the table in the article changes after CSS is modified with the widget.
This means that everything looks as I want it when I modify the CSS - but looks wrong when I reload the page as some other kind of CSS is used for the table.

**To Reproduce**
1. Create an Article with Tables inside.
2. Modify Custom CSS for tables.
3. Observe how the style of tables changes.
4. Reload page.
5. Observe how different style is applied.

**Expected behavior**
Consistent styling of tables using the CSS definitions set up by me.

**Comment by Kordishal** [comment]
This is the security filter removing some keywords. In this case I believe its the word `body` (in `tbody`). Avoid keywords and special characters removed by the security filter. Check the [Codex entry on CSS](https://www.worldanvil.com/w/WorldAnvilCodex/a/css) for more details.
