### ISSUE TITLE
Map Image quality on Chrome Mobile (Android)

### ISSUE THREAD

**Issue by Maltodaxtrin** [worldanvil/worldanvil-bug-tracker#9]
**World Anvil Username**: Daxtreme

**World / Campaign / RPG Character / Manuscript Title**: Tertia (2.8 MB)

**Feature**: Interactive Map

**Related URLS** (add URLs of the pages that do not work!):

**Describe the bug**
On Google Chrome Mobile (Android), the map image quality is low resolution/blocky, even if you zoom in maximum. I tested both on my tablet and phone, same result. This bug strangely does not appear on Edge (Android) which is weird because they're both based on Chromium.

**To Reproduce**
1. Open a Highres map on Chrome (Android) - my map is 2.8 MB
2. Zoom in at maximum
3. Zoomed-in map image will be lowres and blocky, compared to the exact same map zoomed in at maximum on desktop. 

**Expected behavior**
Zoomed-in map should look the same in Chrome Android as it does in desktop browser or Edge for Android or any other browser.

**Screenshots**

**Priority**
Low

**Comment by iamromeo** [comment]
This is not an issue with World Anvil but with the mobile provider lowering the quality of images and compressing them
This is fairly standard practice, especially on large images

**Comment by Kordishal** [comment]
You could attempt to transform the image into WEBP which is an image format optimized for the web. This *might* lead to some improvements.

**Comment by Maltodaxtrin** [comment]
thank you both for the answers!
