### ISSUE TITLE
Double Daily Guild rewards

### ISSUE THREAD

**Issue by AgaritaBerry** [worldanvil/worldanvil-bug-tracker#900]
**World Anvil Username**: Michael Chandra

**Feature**: Anvil Coins

**Describe the Issue**
I realised I was gaining coins too fast and discovered that I occasionally receive my daily guild reward twice. Looking back several months, I can see that I got rewards twice on 25 November, 17 & 19 December, 1 & 9 January, 22 February, 1 & 6 & 7 March.

**To Reproduce**
Unknown, but I suspect having multiple tabs open on WA plays a role?

**Expected behavior**
Only gaining daily rewards once.

**Screenshots**
![image](https://user-images.githubusercontent.com/80285999/157016935-3b90a796-c6c8-4dd0-9a2d-015aee6f4c02.png)

**Comment by iamromeo** [comment]
Hmmmm isn't that very interesting. Thank you Michael - I will have a looksie!

**Comment by iamromeo** [comment]
In theory fixed :) Currently conducting tests in dev and will be deploying later on.
