### ISSUE TITLE
Can access public category in private world via direct link

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#901]
**World Anvil Username**: SoulLink
**Feature**: Access
**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/breaking-anvil-soullink/c/world-ember-prep-category

**Describe the Issue**
The public category above can be accessed via direct link, even though the world is private.

**Comment by iamromeo** [comment]
Fixed will be deploying later today
