### ISSUE TITLE
Unable to delete world

### ISSUE THREAD

**Issue by TaoPirate** [worldanvil/worldanvil-bug-tracker#902]
**World Anvil Username**: TaoPirate

**World / Campaign / RPG Character / Manuscript Title**: Lost in the Strange

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/world/ddd90bd7-13b9-414d-ba06-c66790aaee35/delete

**Describe the Issue**
Trying to delete a World.  I get a 404 after I confirm the delete but the world is still in my list.

**To Reproduce**
1. Go to (https://www.worldanvil.com/world/ddd90bd7-13b9-414d-ba06-c66790aaee35/edit)
2. Click on Delete World, then Delete this World, Then OK on the popup.
3. See error (https://www.worldanvil.com/world/ddd90bd7-13b9-414d-ba06-c66790aaee35/delete)
4. World still shows in World list.

**Expected behavior**
Delete the World

**Comment by iamromeo** [comment]
Hey Tao! This might be an issue with your default subscriber groups 
1. Go to Security
2. Remove all subscribers
3. Remove all subscriber groups
4. Try to delete
If this still persists, let me know.

**Comment by TaoPirate** [comment]
When I go to subscriber groups I was able to delete one of the groups but I get a 404 error when I try to delete the last one.  When i click okay to confirm I get directed to this URL : https://www.worldanvil.com/world/access/groups/df62e90c-55fb-43dc-80f6-31db0f39b48e/delete
