### ISSUE TITLE
Error Exporting World: 'NoneType' object has no attribute 'has_category'

### ISSUE THREAD

**Issue by Drekey** [worldanvil/worldanvil-bug-tracker#903]
**World Anvil Username**: Drekey

**World / Campaign / RPG Character / Manuscript Title**: Ener

**Feature**: World Export

**Related URLS** (To public & visible pages add screenshots otherwise): https://toolbox.soullink.docker.worldanvil.com/backup/form

**Describe the Issue**
When I try to export my world 'Ener' I get the following error: "Job failed: AttributeError: 'NoneType' object has no attribute 'has_category'"

**To Reproduce**
1. Go to 'Export world'
2. Click on 'Export'
3. Include Worlds "Ener"
4. Include Articles, Statblocks, Manuscripts
5. Click Start

**Expected behavior**
I don't really know because it never completed, but I would assume I would get a file or a link for a file with my whole world in some format.

**Comment by iamromeo** [comment]
@Kordishal is that something you can have a look at?

**Comment by Kordishal** [comment]
Yes. I believe this error can only appear when there is an article that can't be accessed. Which should not be possible. So I would need access to the data to investigate further.

In the meantime I will just fix it by skipping these articles.

@Drekey  Can you possibly come to the Discord of World Anvil so we can discuss this in more detail? (I am SoulLink#3294 on there)

**Comment by iamromeo** [comment]
@Kordishal do we have an update on this?

**Comment by Kordishal** [comment]
@Drekey Can you re-export your world? A fix has been deployed.

**Comment by Kordishal** [comment]
Not response for 15 days so I assume this has been fixed.
