### ISSUE TITLE
Articles reverting to old username

### ISSUE THREAD

**Issue by thewabisabian** [worldanvil/worldanvil-bug-tracker#904]
**World Anvil Username**: thewabisabian

**World / Campaign / RPG Character / Manuscript Title**: Nethdria

**Feature**: Articles

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/nethdria-macabara/a/dark-elves-article

**Describe the Issue**
We discussed it in the help channel in the discord, I changed my username last year or so and some of the links to articles in my world have the old username, when I change them to the new username they don't work and 404 me.

**To Reproduce**
1. Go to the Dark Elves page. https://www.worldanvil.com/w/nethdria-macabara/a/dark-elves-article
2. Click one of the hyperlinks in the bodies of text like 'infernal gods' for instance.
3. See error

**Expected behavior**
The Dark Elves page will have my old username 'Macabara' in the address bar, the hyperlinked pages have my new username 'thewabisabian' and will 404 you. The site doesn't seem to acknowledge my username has changed.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Please read the documentation before submitting a bug. the articles do not revert to a previous state. You probably changed your username and never re-saved your world configuration so the slug for your world is still the same.

**Comment by Kordishal** [comment]
Where is this supposed to be documented? I can't a mention on the username change form that this is necessary? And the Codex does not mention it either.

I was not aware of this, which is why I suggested this ticket should be made.

**Comment by thewabisabian** [comment]
It seems to have worked though I'm sure I've saved my configuration some time in the near-year period. And as stated, I only made the ticket on the advice of a moderator.
