### ISSUE TITLE
Typo on the Welcome Page

### ISSUE THREAD

**Issue by JustVibin51** [worldanvil/worldanvil-bug-tracker#905]
**World Anvil Username**: Just_Vibin51

**World / Campaign / RPG Character / Manuscript Title**: Tal'Dorei / Rise of the Kobold King

**Feature**: on the Welcome to World Anvil - READ ME FIRST

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
On the Welcome Page generated by creating a new world >Where to Start>Setup Your Map. In the Second sentence, the wrong form of "not" is used. "you want to create one and do knot know how"

**To Reproduce**
1. Go to 'Welcome to World Anvil - READ ME FIRST'
2. Under the 'Setup Your Map' section.
3. Scroll down to 'If you don't have your own map but you want to create one and do knot know how, we have created a list of software you can use'

**Expected behavior**
The word "not" to be used in place of "knot"
**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
This is fixed but the old articles cannot be replaced.
