### ISSUE TITLE
Cancel delete confirmation on note does not cancel delete

### ISSUE THREAD

**Issue by scoobydoo192** [worldanvil/worldanvil-bug-tracker#906]
**World Anvil Username**: Scoobychu192

**World / Campaign / RPG Character / Manuscript Title**: Note section jasper in feywilds

**Feature**: note taking?

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I just finished taking some notes and clicked submit i thought a copy of it went to another notebook. And so i went to delete it on that one seeing it was still in the other. But then when i clicked delete i thought oh i should copy the notes just in case something goes wrong and clicked cancel to stop the deletion. It ended up deleting anyway and i'm seeing the note still there but i cant click onto it if that makes sense. When i click it nothing happens but the page is supposedly still there. Either way im not impressed it deleted all my notes when i clicked cancel.

**To Reproduce**
5. Not sure if its reproducable

**Expected behavior**
A clear and concise description of what you expected to happen. Explained above i clicked cancel but it deleted anyway

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
#647

**Comment by iamromeo** [comment]
This is a duplicate of a previous bug - also the notebook will soon have a completely new version fixing this.
