### ISSUE TITLE
404 Error when adding tags to a Statblock 

### ISSUE THREAD

**Issue by galahad423** [worldanvil/worldanvil-bug-tracker#907]
**World Anvil Username**:galahad423

**World / Campaign / RPG Character / Manuscript Title**: Kethenicaea - Staff of the Magi 

**Feature**: Statblock Tag Management 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.
When using the statblock item feature on WorldAnvil, when trying to save new tags to the Item "Staff of the Magi," I am repeatedly redirected to a 404 "you have reached the end of this world" error page. When attempting to replicate the issue, the error is inconsistent, as sometimes adding identical tag (or Tags) which previously produced this issue fails to produce the 404 page again, and instead are saved as they normally should be. I have also experienced this issue when dealing with the "Belt of Giant Strength" article and it seems to be related to the number of tags being uploaded or length of the total list of tags (but I have also experienced the issue when attempting to only save a single tag, and have had success saving identical long lists of tags which previously resulted in a redirect to a 404 page, so it seems inconsistent in its cause). I've also checked internet connection thoroughly, and it doesn't seem to be resulting from a loss of network connection either. 

**To Reproduce**
1. Go to 'Statblocks page'
2. Click on 'add tags, add long or extensive list of multiple tags or even a single tag'
3. Scroll down to 'save changes and click'
4. See error (redirect to 404 page sometimes) 

**Expected behavior**
I expected the page to save the tags normally instead of being directed to a 404 page and have the tags remain unsaved and disappear from the article. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Can you give examples of tags that were not saved successfully and links to the relevant statblocks?

**Comment by galahad423** [comment]
Here's a link to the statblock! 
https://www.worldanvil.com/sheet/988095/view

 I've had the issue with the tags "Quarterstaff," "Conjure Elemental," "Dispel Magic," "Fireball," "Flaming Sphere," "Ice Storm," "Invisibility," "Knock," "Lightning Bolt," "Passwall," "Plane Shift," "Telekinesis," "Wall of Fire," and "Web," _(quotation marks mine to represent each individual tag)_. These are all presently saved to the statblock after working on later attempts (or adding them in groups of one or two rather than all at once), but are examples of attempts to save Tags which result in a 404 error the first time I attempted to save, but which mysteriously functioned and eventually saved when entered again during subsequent attempts (again, with no apparent distinction between the initial tag which failed and the working second or third try). 

Examples of Tags which continue to generate 404 errors and which are not presently saved to the Statblock include "Arcane Lock,"  "Detect Magic," "Enlarge," "Reduce," "Light," "Mage Hand," or "Protection from Evil and Good" _(again, quotation marks mine)_

**Comment by iamromeo** [comment]
I am sorry but I cannot reproduce this. @Tillerz (As the creator of the sheet) do you have any idea what might be causing thing?

**Comment by Tillerz** [comment]
@iamromeo I just copied the sheet to my world, added ",bla" to the tags, it saved, add another ",blubb" to the end, it 404ed. Looks like there is an issue with the length of the tag field in the right side bar of the sheet form: after adding ",bla" it's below 255, after adding also ",blubb" the field is > 255 characters. Nothing I can fix in my sheet, it seems to be a WA issue.

works:

Staff of the Magi, Staff, Attunement, Legendary, Magic Item, Wondrous Item, Quarterstaff, Conjure Elemental, Dispel Magic, Fireball, Flaming Sphere, Ice Storm, Invisibility, Knock, Lightning Bolt, Passwall, Plane Shift, Telekinesis, Wall of Fire, Web,bla

breaks:

Staff of the Magi, Staff, Attunement, Legendary, Magic Item, Wondrous Item, Quarterstaff, Conjure Elemental, Dispel Magic, Fireball, Flaming Sphere, Ice Storm, Invisibility, Knock, Lightning Bolt, Passwall, Plane Shift, Telekinesis, Wall of Fire, Web,bla,blubb

**Comment by iamromeo** [comment]
.... why do you need so many tags? :O 

In light of this, this is not an issue with the sheet. 256 characters for tags is a global parameter as it stands. 
This will not be fixed since it requires a massive overhaul.
