### ISSUE TITLE
World Anvil does not allow use of Windows Voice Recognition

### ISSUE THREAD

**Issue by dcrdougher** [worldanvil/worldanvil-bug-tracker#908]
**World Anvil Username**: ddougher

**World / Campaign / RPG Character / Manuscript Title**: all

**Feature**: Not sure.  Is this considered a bug or a new feature request?

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Although both Chrome and Edge browsers allow me to enter text via voice commands when i enter manuscript mode in World Anvil the feature stops working correctly.  In some cases, it will take words I am dictating and try to turn them into commands - popping up menu items and skipping to different parts of the system.  Note that this is only for Windows 10.  I don't have Windows 11 to try.

**To Reproduce**
1. Activate Windows Voice recognition on the computer.
2. Go to World Anvil on either Chrome or Edge by using voice commands or by typing.
3. Go into Manuscripts and select a novel.
4. Place the cursor in a scene and attempt to dictate text.
5. No text will be generated in the scene.  Occasionally some words may be interpreted as a command and control will shift to another area of World Anvil. 

**Expected behavior**
I can currently dictate in Word and Scrivener and I would expect that I should be able to do so in World Anvil, especially since I know both browsers support it. 

**Screenshots**
N/A

Note: Not to push, but voice dictation is becoming increasingly popular as a way to get a first draft done more quickly.  I dictated large portions of my last two novels and the current one I dictated more than 50%.  I can understand if this is a serious issue to get from the browser to the World Anvil system, but I think it might be on the list of items to consider in a future release?

**Comment by iamromeo** [comment]
Thank you for your feedback @dcrdougher. 
I am sorry to say it but this is not really a bug. It might be a lack of feature or an issue with the current WYSIWYG used. 
We can investigate but I am closing this.
