### ISSUE TITLE
I'm getting CSS in rich textarea inputs. When I remove them and save they pop back.

### ISSUE THREAD

**Issue by yaronveg** [worldanvil/worldanvil-bug-tracker#909]
**World Anvil Username**:

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
I am sorry but I cannot understand this issue as it is shown here and there is no details for me to action it.

**Comment by Kordishal** [comment]
This sounds like the Plato editor bug. It sometimes loads parts of itself into the text field.

To resolve the issue switch to the Euclid issue and remove all the rogue text.

Check the guide below for how to switch. You can switch back afterwards, but Euclid is currently the recommended editor as the Plato editor is awaiting a rework.

https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors
