### ISSUE TITLE
Pins not visible on maps

### ISSUE THREAD

**Issue by TrolKabu** [worldanvil/worldanvil-bug-tracker#91]
**World Anvil Username**: TrolKabu

**World / Campaign / RPG Character / Manuscript Title**: World Map

**Feature**: Map pins

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/troupe-de-l-horizon-drayker/map/aaf51ab9-e25c-44c2-b9ec-2d41907d95df
https://www.worldanvil.com/w/runavaan-akirauwu/map/29236dd6-7c3c-4691-a206-f4915a9259a3

**Describe the Issue**
A clear and concise description of what the issue is.

Pins can't be seen on the map.

**To Reproduce**
1. Go to any public map (not tested on private one)
2. See error

Browser has no impact. Tested on several computers with different setups. Pins worked back as usual after a few minutes for me. Other users still having troubles. No intervention on my side to make it works in between the opening of the map.

**Expected behavior**

Pins should be visible and hovering over them should open the tooltip associated to them.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/81257642/112196972-dae67f80-8c0b-11eb-8a55-b1d3d9b59593.png)

**Comment by iamromeo** [comment]
Hmmm, so I can see the pins on a logged in account and not when logged out. 
Even more interestingly this pin is a guild exclusive pin. @TrolKabu was this user ever a guild member?
