### ISSUE TITLE
System Request - Level Up: Advanced 5e

### ISSUE THREAD

**Issue by AceAckbar** [worldanvil/worldanvil-bug-tracker#910]
Would love to see this system be an available choice. 

**Full Name (RPG SYSTEM)**: Level Up: Advanced 5th Edition
**List Name** (Name under which it should be listed on World Anvil): Level Up, A5e
**World Anvil Username**: Ace_Ackbar

**Website**:  https://www.levelup5e.com/

**Comment by Tillerz** [comment]
Hello, I have this on my list of sheets to make and it's already in the works. Will take a bit of time.

**Comment by Tillerz** [comment]
As this is a bug tool for WA, I'll close this post. If you want to follow what's happening about A5e, clease come over here to the forum: https://www.worldanvil.com/w/sheet-creation/board/advanced-5e-28level-up2C-a5e29

**Comment by Kordishal** [comment]
System has been added as a choice for worlds & campaigns

**Comment by Tillerz** [comment]
Can't find it yet in https://www.worldanvil.com/community/rpg ?
