### ISSUE TITLE
Undesirable "Film" Overlay placed over Character Template "Portrait" feature

### ISSUE THREAD

**Issue by dlandi** [worldanvil/worldanvil-bug-tracker#911]
**World Anvil Username**: HieronymusBlaze

**World / Campaign / RPG Character / Manuscript Title**: Rogue Universe - Infinite Planes

**Feature**: The "Portrait" feature in the Character Article Template

**Related URLs** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Article's "Portrait" Feature applies a "film" overlay over my image, but as you can see it displays correctly in the main article via the [img] tag.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by dragging & dropping them into this window!
![image](https://user-images.githubusercontent.com/3196088/158018243-8959c3d7-c91a-40a4-8b20-2b58672787a9.png)

**Comment by dlandi** [comment]
I thought maybe the grayscale gradient was throwing the "Portrait" rendering off, so I tried and a clear frame around the image. 
![image](https://user-images.githubusercontent.com/3196088/158020149-ec4fe9d7-9b75-4654-b402-946e3f35bba4.png)

No luck.

**Comment by iamromeo** [comment]
I am sorry but there is no transformation coded in world anvil apart from cropping. I am not sure why but I cannot fix something that doesn't exist.
