### ISSUE TITLE
Timeline creation fails.

### ISSUE THREAD

**Issue by Zerman85** [worldanvil/worldanvil-bug-tracker#912]
![rreeeee](https://user-images.githubusercontent.com/101468432/158024938-6a995dd9-aa65-4bee-aca2-6a03be9bbe00.png)

I can't create timeline even by pressing the button, and it does the same to me for other options

**Comment by Zerman85** [comment]
my name autor was : Zerman
I have the worries on all my worlds

In firefox havn't problem but in chrome and private chrome i have problem

**Comment by iamromeo** [comment]
Timelines do not have any autosave system. 
The chances are the issue occurs because of special characters on the title or description but without a good way to replicate it I cannot really reproduce it.

**Comment by Zerman85** [comment]
Je fais des titres et des descriptions avec simplement des lettres, aucun accent, aucun chiffre ou caractère spéciaux (même pas de é).

Le problème se produit lorsque je clique sur le "créer une nouvelle chronologie"
![rreeeee](https://user-images.githubusercontent.com/101468432/158053344-060b7baf-8300-4c03-98e4-5f1244e74a7c.png)

**Comment by Zerman85** [comment]
En cliquant dessus, il ne se passe simplement rien, comme si le bouton n'était reliée à aucune commande

**Comment by Zerman85** [comment]
J'ai le même problème pour sauvegarder les dates/heures ect...

**Comment by iamromeo** [comment]
Have you tried using your browser in incognito mode or a different browser? That sounds like a plugin taking over the click. 
Also would it be possible to write in English, please? I lived in France for a year, but I am not in any way fluent.
