### ISSUE TITLE
Spellbook is not appearing

### ISSUE THREAD

**Issue by jamixu** [worldanvil/worldanvil-bug-tracker#913]
**World Anvil Username**: Conversinator

**World / Campaign / RPG Character / Manuscript Title**: Character Sheet (2020) Dungeons & Dragons 5e

**Feature**: Spellbook

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
The Spellbook section of a newly created Character Sheet (2020) Dungeons & Dragons 5e does not give the space or oportunity to even type anything

**To Reproduce**
1. Go to Statblocks
2. Click on Create Character Sheet (2020) Dungeons & Dragons 5e 
3. Scroll down to Spellbook, at the bottom of the page

**Expected behavior**
It used to be a space to place spells and make rolls based on the spellcasting ability of the character or for the spells damage. Both factors should be introduced at the space that is missing
**Screenshots**
![Spellbook WA error](https://user-images.githubusercontent.com/100138372/158033421-276357e8-e6d5-4eb7-8ae7-9d278aa2814f.png)

**Comment by Kordishal** [comment]
@Tillerz Something for you to look at.

**Comment by Tillerz** [comment]
Fixed. :) That was something that came in when making the sheet ready for the DNDBeyond-Imports.
