### ISSUE TITLE
tables issue and editing display

### ISSUE THREAD

**Issue by david-brenner** [worldanvil/worldanvil-bug-tracker#916]
**World Anvil Username**: agback

**World / Campaign / RPG Character / Manuscript Title**:  Faerun BFA/ article "Players"

**Feature**: table

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I created a page with a table. Upon creation everything was great.  When I enter the page again to edit the table is broken.  Any updates to fix do not stick.  The first couple of rows loose all the [tr] and [td] tags.

**To Reproduce**

**Expected behavior**
the WYSIWYG display should work and data should not be removed

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Can you please show us the code that you are using to create the table please?

**Comment by iamromeo** [comment]
Closed due to no response
