### ISSUE TITLE
Moon phase for celestial objects in calendar is incorrect in modal popup

### ISSUE THREAD

**Issue by TimothyHarrelson** [worldanvil/worldanvil-bug-tracker#917]
**World Anvil Username**: DeceitfulEcho

**World / Campaign / RPG Character / Manuscript Title**: Emala

**Feature**:  Calendars

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/emala-deceitfulecho/a/campaign-calendar-article

**Describe the Issue**
The icons for the phase of celestial objects differs between what is shown on the calendar and what is shown in the modal that pops up when you click the icon. The first day of the calendar seems correct, but it seems that the period (how long between new moons) is different between what the calendar icon displays and what the modal says for that celestial body. If you take a day later in the year you can see the phase is incorrect to a high degree. 

**To Reproduce**
1. Go to the calendar linked in the related URL's
2. Click on a celestial body for some day later in the year.
3. Compare the phase on the calendar and the phase displayed in the modal
4. See the phases are not the same

**Expected behavior**
The phase displayed in the modal should match the phase displayed on the calendar

**Screenshots**
![image](https://user-images.githubusercontent.com/9173623/158081508-21b1f33e-6900-412a-a117-fbb73f42289a.png)

**Comment by iamromeo** [comment]
Hey there @TimothyHarrelson 

That has been reported again in the past. It is quite rare for it to happen, but it does happen. The calendar system is due for a complete redesign ( do not worry the same JSON will be either transformed or kept the same) 

Due to the rewrite - this will not be addressed RIGHT now, but we are aware of it :)
