### ISSUE TITLE
Adding new map silently fails

### ISSUE THREAD

**Issue by adigitalnative** [worldanvil/worldanvil-bug-tracker#919]
**World Anvil Username**: dcheneau

**World / Campaign / RPG Character / Manuscript Title**: Lithuin

**Feature**: Add a map

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/world/map/new

**Describe the Issue**
A clear and concise description of what the issue is.

When I try to create a new map with an (admittedly large) png image, nothing seems to happen.

**To Reproduce**
**How I got there:**
I go to the 'Create a Map' page.
I add a (large) map - PNG, 16.4 MB
I click the 'Create Map' button

**Expected Behavior:**
Either a map will be created and I'll be taken to another screen
_OR_
An error message will appear telling me that there's been an issue.

**Actual Behavior:**
Nothing happens.

(My guess: Either the request timed out or had another issue, or the file is slow to upload due to size. Would be great to have some kind of progress or loader after clicking the button if that's the case)

**Comment by iamromeo** [comment]
Hey @adigitalnative 

That is indeed a rare occurence and it mostly has been observed to be present in unstable connections. We do have a plan to implement a loader system in the future, but the root cause will most possibly have more or less the same effect to the loader as well.
