### ISSUE TITLE
Editor buttons don't have visible symbols

### ISSUE THREAD

**Issue by joshuadotbio** [worldanvil/worldanvil-bug-tracker#920]
**World Anvil Username**: joshua.bio

**World / Campaign / RPG Character / Manuscript Title**: Eberron

**Feature**: Editor

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Editor buttons are black and don't have visible symbols.

**To Reproduce**
1. Go to edit any page

**Expected behavior**

**Screenshots**
<img width="823" alt="Screen Shot 2022-03-14 at 03 10 05" src="https://user-images.githubusercontent.com/1232305/158151422-7ab30e37-7687-40b5-b3db-d9a1cfb5ec31.png">

**Comment by joshuadotbio** [comment]
Update: The same problem happens on Chrome on macOS, so it's not an isolated Safari issue.

**Comment by Kordishal** [comment]
this isn't an editor issue, but an issue with the interface theme and the community statblock template you are using. You'll need to talk to whoever created this sheet to see if they can update the CSS for it or just try another editor theme.
