### ISSUE TITLE
Spellcasting Ability on the Spellbook

### ISSUE THREAD

**Issue by jamixu** [worldanvil/worldanvil-bug-tracker#921]
**World Anvil Username**: Coversinator

**World / Campaign / RPG Character / Manuscript Title**: Character Sheet (2020) Dungeons & Dragons 5e

**Feature**: Spellbook spellcasting ability

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When creating a new Character Sheet, the selected spellcasting ablity on the Spellbook section is overruled and goes back to "NONE" everytime the "Save changes" button is clicked.

**To Reproduce**
1. Go to Statblocks
2. Click on Create Character Sheet (2020) Dungeons & Dragons 5e
3. Scroll down to Spellbook, at the bottom of the page
4. Select a spellcasting ability (INT, WIS, CHA)
5. Scroll up to the top of the page
6. Type anything on the "Character Name" section
7. Click on "Save changes"
8. Scroll back to Spellbook section
9. Click on spellcasting ability on Spellbook

**Expected behavior**
The selected spellcasting ability on the Spellbook should stay the same despite saving the changes

**Comment by iamromeo** [comment]
@Tillerz can you please check this sir?

**Comment by Tillerz** [comment]
Checked, it only didn't save for INT (missing a bit in a comparison). Fixed it.

**Comment by jamixu** [comment]
Thank you so much!!

Sorry for not being thorough enough in my testing.
