### ISSUE TITLE
delete world not working

### ISSUE THREAD

**Issue by sneakynos** [worldanvil/worldanvil-bug-tracker#922]
**Sneakynos**:

**Evarria**:

**Delete World**: 

**[Related URLS](https://www.worldanvil.com/world/4d2d9e6c-f090-46c0-9a04-bb876f9136be/edit)** (To public & visible pages add screenshots otherwise):

**I am trying to delete the world as I would like to start over, but it even after confirming and getting the end of the world page, it is still available as an option in my worlds lis**
A clear and concise description of what the issue is.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Hey @sneakynos 

This happens in some cases if you have a bit of an odd struture with your security. 
Make sure you delete all or your subscriber groups, authors and subscribers 
After that try again, if the problem persists, please message me here again referencing this issue.
