### ISSUE TITLE
Unable to reuse NPCs

### ISSUE THREAD

**Issue by WernerKnoesen** [worldanvil/worldanvil-bug-tracker#923]
**World Anvil Username**: Wernerknoesen

**World / Campaign / RPG Character / Manuscript Title**: [New Ullios](https://www.worldanvil.com/w/new-ullios-wernerknoesen)

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I have been setting up a new campaign but needed to start over. I want to re-use the NPCs I created that exist as separate articles in the world. Within the Campaign Section I am not able to create new NPCs linking them to the existing article. I also am not able to select previous NPC profiles from the deleted campaign. When I select a character article and navigate to preferences it states the characters is linked to a profile and the link provides a 404 error page.

**To Reproduce**
1. Go to new campaign created "The Treasures of a Lost City, A D&D Story" 
2. Click on "Create New Supporting Cast Member (NPCs)" and create a previously created NPC "Erru"
3. Open Advanced Details and search for "Erru" under Linked Character Article.
4. Character doesn't appear.
5. Open Character Article for "Erru" https://www.worldanvil.com/world/person/0713447a-59e6-479d-b673-982c5a4bec56/edit
6. Navigate to "Preferences"
7. Above Delete the page states "This Character article is attached to [Erru](https://www.worldanvil.com/hero/d3be5d46-7105-4e49-995a-1cb95176bebe) profile."
8. Link is dead and I am unable to manage any of these pages
 
**Expected behavior**
I should be able to either select the old profile or create a new one attached to the new Campaign.

**Comment by iamromeo** [comment]
This is not a bug - this i show the system is currently work - but as announced that will be changing.
