### ISSUE TITLE
Unisystem (All Flesh Must Be Eaten, ConspiracyX, Witchcraft) 

### ISSUE THREAD

**Issue by NiffinMagician** [worldanvil/worldanvil-bug-tracker#925]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Unisystem**:
**List Name** (Name under which it should be listed on World Anvil): Unisystem
**World Anvil Username**: btvsfan

**Website**: CJ carella's Witchcraft RPG book on drivethrurpg is free and has all basic rules. 

**Logo Image Link**:

**Logo Usage Terms (URL)**:

**Comment by iamromeo** [comment]
Hey @NiffinMagician  - Officially you need to be a grandmaster to request a system (See on the text you pasted above)  but .... you have been with us since time immemorial, and that counts around here :) 

I have added the system for you. <3

**Comment by NiffinMagician** [comment]
Hello Dimitris!

Thank you so much. I appreciate your willingness to help me. I admire what
you have been doing with World Anvil, and I hope one day I will be able to
fully be part of the creative community. I am still learning how to world
build and making small baby steps.
Once I am accomplished, I will definitely upgrade ;)

Thanks again!

Best,
Hechmi (NiffinMagician)
