### ISSUE TITLE
Broken HTML when a Term, Advanced variable refers to another and when an Article mention is used.

### ISSUE THREAD

**Issue by HeffeHeffling** [worldanvil/worldanvil-bug-tracker#93]
**World Anvil Username**: Heffe

**World / Campaign / RPG Character / Manuscript Title**: The Hefflings

**Feature**: Variables

**Related URLS** (To public & visible pages add screenshots otherwise): [https://www.worldanvil.com/w/hefflings/a/bloombell](https://www.worldanvil.com/w/hefflings/a/bloombell)

**Describe the Issue**
I'm sorry for the inconvenience; I understand if wrapping many actual issues into one Github issue isn't perhaps good practice, but I suppose the main issue is the rendering of the Term, Advanced variable. I can always edit this to focus on one issue and create another if needs be.

I have Term, Advanced variables which reference other variables. These other variables are Render Fragment variables. The HTML appears to break upon when the first variable is used.

It is the same with the article @ mentions. The article linked in this thread has Term, Advanced variables, with article mentions as part of the value.

**To Reproduce**
Steps to reproduce the behaviour:

**A. Variable referencing variable:**
1. Create a Render Fragment variable; this is to be the variable to be referenced later. Any suitable key and value.
2. Create a Term, Advanced variable; any key, but the value must contain the BBCode which refers to the variable made in step 1. *(Side note: Many variables I've created do have the Title as a referred variable; though I'm unsure if this is an issue, as this worked before.)*
3. Add the variable from step 1 into an article
4. View the article.

**B. Article mention in variable**
1. Create a Term, Advanced variable. Any key, with the value containing an article mention.
2. View variable in an article.

**Expected behaviour**
Mentioning an article and referencing another Variable, with no broken HTML, as I could before.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Hey Heffe, do you have a public article I can see this happening. This might have to do with the security issue that it was reported and fixed but I would need the actual content of your variables to make sure I am reproducing this correctly

**Comment by iamromeo** [comment]
@HeffeHeffling I have changed completely the way that advanced variables are working. They are now use the same system that article tooltips use. This should resolve the problem, well most of it. Do let me know here if you see something

**Comment by iamromeo** [comment]
Resolved bt https://github.com/iamromeo/Worldbuilder/pull/3088

**Comment by iamromeo** [comment]
Resolved by https://github.com/iamromeo/Worldbuilder/pull/3088

**Comment by HeffeHeffling** [comment]
The article mentions are working now and the Article looks as it should; so thank you!

However, I did just notice the Advanced, Term tooltips do not read/show variables.

So to reproduce:
- add a `[var]` into the value of an Advanced, Term variable.
- View in an article and hover over the text
- Tooltip pops up, but any value which was in the reference variable isn't even being parsed.



Also, for future reference, if I'm to find where variables aren't being parsed correctly, would you like me to post a comment here and perhaps if possible, rename this issue to something like missing/unparsed variables, or would it be better to make a new issue for that?

**Comment by Kordishal** [comment]
I think it's generally better to create new issues with different problems even if they are somewhat related. Makes it easier to organize and offers a better archive overview.
