### ISSUE TITLE
Creating new world

### ISSUE THREAD

**Issue by Archaeoman** [worldanvil/worldanvil-bug-tracker#931]
**World Anvil Username**:
Archaeoman

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 
World Creation

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I was trying to create a new world, but I am unable to do so because every time I put in the title, description, and the game system (DnD5e) it sends me to a 404 page. 

**To Reproduce**

**Expected behavior**
My understanding is that if I put all the information that it will create a new world. Thanks.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Hello Archaeoman
Would you like to give us some more information? 

You haven't supplied any reproduction steps so we can duplicate this. Obviously several thousands of worlds are created every day so - this is not a generic problem

1. Are you pasting in any details
2. Are you using special characters
3. Have you ever had another account with the same username
4. Do you already have a world with the same name

**Comment by Archaeoman** [comment]
Hello,

  Thanks for the quick response, but it seems to have worked itself out or I was not doing something correctly the first time.
