### ISSUE TITLE
Ranger Coding Issue

### ISSUE THREAD

**Issue by FoxyBugFixer** [worldanvil/worldanvil-bug-tracker#932]
FoxyDM:

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 

[**Related URLS** (To public & visible pages add screenshots otherwise)](https://www.worldanvil.com/world/article/337ec45e-86a5-4172-a8ed-dae81f984a75/edit):

**Describe the Issue**
Script for the table on the page changes when loading and removes some of the cells in the first few rows. At first the coding seems to be fine but then transfers to removing cells. I also can not edit the page without being in the code version of the page. The first screenshot

**To Reproduce**
1. Go to ['...'](https://www.worldanvil.com/world/article/337ec45e-86a5-4172-a8ed-dae81f984a75/edit)

**Expected behavior**
I expected the header cells in the table to not be removed along with a few other cells on the first table. It should look like the second screenshot. 

**Screenshots**
![image](https://user-images.githubusercontent.com/101908605/159098062-dd2a9ff4-e3b3-429e-9c0c-cf2bc319ae26.png)
![image](https://user-images.githubusercontent.com/101908605/159098308-158d7294-26d2-4849-8b26-fdf4a3b63b07.png)

**Comment by iamromeo** [comment]
Hello FoxyDM

I am not sure which of the two is considered the correct code but both have mistakes 
Many of the tags here are not opening when they should or not closing at all. that can certainly create issues. 

1. Have you tried using a BB table creation tool? 
2. Is there a reason you are not using the Tables system for this ? :)

**Comment by Kordishal** [comment]
Example for a BBCode table generator:

https://tableconvert.com/bbcode-generator

**Comment by FoxyBugFixer** [comment]
I had initially used the table system, but the coding got messed up and
keep resetting to the wrong coding. The coding seems correct when loading
but after loading the whole system and button like bold and italics, the
coding changes to not have things in boxes or remove them entirely.

**Comment by Kordishal** [comment]
when using some nested BBCode the Plato editor can mess up even if everything is in order. You might have more luck using the recommended Euclid editor.

Check the editors guide to see how to switch: 

https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors
