### ISSUE TITLE
Orange flickering bug

### ISSUE THREAD

**Issue by starburner1122** [worldanvil/worldanvil-bug-tracker#933]
**World Anvil Username**: Starburner

**World / Campaign / RPG Character / Manuscript Title**: Akiviras

**Feature**: Article editing

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Sometimes while editing an article parts of the screen will begin flickering a bright orange. This is not the fault of my laptop as it has only ever occured in Worldanvil in the three years I have used this laptop, and does not occur even in other tabs at the same time. This makes concentrating on working essentially impossible, and there is no way to fix it. Closing and reopening Worldanvil and even restarting my computer does not fix the issue, and the only thing that does is going away until it is fixed, which takes hours.

**To Reproduce**
1. Begin editing any article
2. Eventually, the orange flickering will begin
3. See error

**Expected behavior**
No orange flickering during the article editing, or indeed any part of Worldanvil.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Hi, that does seem very annoying, but that isn't something that happens for anyone else. I honestly don't know what could be causing this. Things you could try (though they are just generic suggestions):

1. Have you updated your graphics drivers?
2. Does this occur when you are editing in a private / incognito window?
3. Does it occur in any other browsers?

**Comment by starburner1122** [comment]
> Hi, that does seem very annoying, but that isn't something that happens for anyone else. I honestly don't know what could be causing this. Things you could try (though they are just generic suggestions):
> 
> 1. Have you updated your graphics drivers?
> 2. Does this occur when you are editing in a private / incognito window?
> 3. Does it occur in any other browsers?

My graphics drivers are up to date. I just tested it in an incognito window and another browser and can confirm that the bug is also present in both occasions.

If nobody else is experiencing it then it may be on my end. I find that curious considering it is only present in Worldanvil and nowhere else, but I am at a loss as to what could be causing this. I would provide screenshots, but the orange flickering does not show on them for some reason.

**Comment by Kordishal** [comment]
Is the userway widget active?

![image](https://user-images.githubusercontent.com/14262536/159115711-4faa843d-9fa4-4956-8113-12726993e587.png)

If yes, then you can try disabling it below:

https://www.worldanvil.com/dashboard/user/features

**Comment by starburner1122** [comment]
> Is the userway widget active?
> 
> ![image](https://user-images.githubusercontent.com/14262536/159115711-4faa843d-9fa4-4956-8113-12726993e587.png)
> 
> If yes, then you can try disabling it below:
> 
> https://www.worldanvil.com/dashboard/user/features

I disabled the userway, but unfortunately the problem persists.

**Comment by iamromeo** [comment]
Can you check if this occurs if  you are using WA in incognito mode?

**Comment by starburner1122** [comment]
> Can you check if this occurs if you are using WA in incognito mode?

This does occur when I am using incognito mode, and it also occurs in a different browser.

**Comment by Kordishal** [comment]
Can you try another device? Like your phone or someones elses device?

**Comment by starburner1122** [comment]
> Can you try another device? Like your phone or someones elses device?

I will try that next time the flickering begins. Thank you
