### ISSUE TITLE
Avatar Legends

### ISSUE THREAD

**Issue by kelpyIRL** [worldanvil/worldanvil-bug-tracker#935]
**Avatar Legends RPG (RPG SYSTEM)**:
**Avatar Legends** (Name under which it should be listed on World Anvil):
**kelpyIRL**:

**https://magpiegames.com/pages/avatarrpg**:

**Comment by iamromeo** [comment]
Isn't Avatar part of FATE ?

**Comment by iamromeo** [comment]
Cool - all fair points :)

**Comment by iamromeo** [comment]
Done - Avatar Legends is now in the list of sheets  

@Tillerz is this character sheet in your list?

**Comment by Tillerz** [comment]
Adding it. :)
