### ISSUE TITLE
Cannot join campaign - getting a 405 / 404 page

### ISSUE THREAD

**Issue by DrDoomDEU** [worldanvil/worldanvil-bug-tracker#936]
**World Anvil Username**:
DD_Tester

**World / Campaign / RPG Character / Manuscript Title**:
The Old World Campaign

**Feature**: 
Join Campaign as invited player

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/heroes/campaign//character/2786d4cc-7543-4586-b9ef-c0fedad53153/grant-access/yELT-7wL5-6syzTm/

**Describe the Issue**
Got an invitation to join a game.
When clicking on the character to join the campaign with it leads to a 404-page.
The same happens when I choose to add a new character.

**To Reproduce**
1. Click on the join-link.
2. A page opens up to choose the character
3. click on the button on the character
4. The click leads to a 404-page

**Expected behavior**
The character should join the campaign.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
I am really sorry but ... where did you find this URL? This url does not exist. 
URLs to join a campaign look like that: 
http://www.worldanvil.com/epic/f6LS9MiESri4BaRVIN1H0COOBzoNCn/join/UqSD-IAdm-C6W8yH

**Comment by iamromeo** [comment]
Or like that if you are joining a WORLD (not a campaign) 
http://www.worldanvil.com/heroes/world/c7f48146-508d-4346-9480-3b5a19fc2310/grant-access/OoI6-JhUf-gHADwD

**Comment by iamromeo** [comment]
Closed due to no response from the submitter
