### ISSUE TITLE
Life, Birth Icon Not Showing Fully

### ISSUE THREAD

**Issue by Chal-at-Ludicrous-Speed** [worldanvil/worldanvil-bug-tracker#938]
**World Anvil Username**: Chaltastic 

**World / Campaign / RPG Character / Manuscript Title**: Zunderade

**Feature**: Timelines

**Related URLS** (To public & visible pages add screenshots otherwise):
[timeline:3ab8137e-cf88-41dc-8e87-e768c67b2280]

**Describe the Issue**
A clear and concise description of what the issue is.

The icon for the Event Life, Birth is not showing completely. The top part of the image, a heart, seems to be cut off. This bug only appears to be on my Mac iOS, however. I tried both Mozilla Firefox and Google Chrome and on both browsers the icon image is incomplete. On mobile (Google Pixel 4a, using Firefox), on the other hand, the icon image appears to be complete, with a heart fully shown.

**To Reproduce**

If the link works:
1. Go to the link 
2. Scroll down to the events on the timeline (all are Life, Birth)
3. See error

If the link does not work: 
1. Go to World Anvil -> Discover -> Worlds
2. Type in 'Zunderade'
3. Click on 'View world'
4. Scroll down to see the Timelines category
5. Click on 'Special timeline just for the bug'
6. Scroll down to see the entire timeline
7. See error

**Expected behavior**

I expect the icon image to appear in full when not using World Anvil on my phone, which is a heart that has not been cut off.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

<img width="354" alt="Screenshot 2022-03-23 at 19 14 54" src="https://user-images.githubusercontent.com/102251909/159770976-bd0c9799-3b65-4c6a-bc08-f592ce9f6779.png">
<img width="1167" alt="Screenshot 2022-03-23 at 19 30 43" src="https://user-images.githubusercontent.com/102251909/159770984-b190f9c7-5a72-45dc-9e8f-10d80993c285.png">
<img width="463" alt="Screenshot 2022-03-23 at 19 51 22" src="https://user-images.githubusercontent.com/102251909/159774359-bfb8303e-148a-48ab-ae85-9ced49681450.png">

**Comment by iamromeo** [comment]
I am sorry this cannot be reproduced - it probably has to do with the settings of your Mac. 
Also, please provide a direct link if possible next time. <3 
https://www.worldanvil.com/w/zunderade-chaltastic/t/special-timeline-just-for-the-bug-timeline
