### ISSUE TITLE
Autolink rolling back edits.

### ISSUE THREAD

**Issue by NorEtoc** [worldanvil/worldanvil-bug-tracker#939]
**World Anvil Username**: NorEtoc

**World / Campaign / RPG Character / Manuscript Title**: Nor

**Feature**: Autolink

**Describe the Issue**
When you edit an article, and enter spellcheck mode and make edits, then use the autolink function, all of your saved changes for that previous edit get rolled back.

**To Reproduce**
Edit an existing article. 
Edit the article.
select spell check.
Make edits to the article. 
make sure the article is saved (You see the save box pop up)
Hit the autolink option.
Save after using the autolink widget.
The article does not contain any of the edits you made during the spell check phase.

**Expected behavior**
One you save the article in the spell check phase the article should update and the autolink should not roll back those changes.

**Comment by iamromeo** [comment]
Hey @NorEtoc 

Autolink will not work in conjunction with spellcheck. This is not a bug, it's a lack of a feature.
