### ISSUE TITLE
BB codes in [container] are converted to HTML tags on edit

### ISSUE THREAD

**Issue by MathijsR94** [worldanvil/worldanvil-bug-tracker#94]
**World Anvil Username**:
Bonus Action
**World / Campaign / RPG Character / Manuscript Title**:
The Sea of Starlight
**Feature**: 
BB codes in `[container]` tags are converted to HTML tags on edit
**Related URLS** (To public & visible pages add screenshots otherwise):
Unfortunately a private URLs, but screenshots are provided.
**Describe the Issue**
When creating an article with BB code, creating a simple block like
```
[container:test-container][h2]Test[/h2][/container]‌
```
Will result in the article saving correctly, but then, when editing, the BB code appears converted to be converted to HTML when looking at 'View source' or viewing the output on the article page.

**To Reproduce**
1. Create a new article (I created this via the Quick Actions menu)
2. Paste `[container:test-container][h2]Test[/h2][/container]‌` as content in Vignette / Freeform Prose.
3. Save the article
3. Optionally look at the article if everything looks right
4. Click edit article
5. Change the headline to `Test!`
6. Save again and view the article

**Expected behavior**
The BB code should not be converted to HTML, but should stay intact and be rendered on the client

**Screenshots**
Setting up article structure
![image](https://user-images.githubusercontent.com/9801298/112385577-122e5c80-8cf0-11eb-949d-7222392be859.png)

Looking at the article, all is fine! Now, we need to edit the article again
![image](https://user-images.githubusercontent.com/9801298/112383933-0fcb0300-8cee-11eb-8dd8-ab3672a2f4cd.png)

On first glance this looks ok, but when going to 'View source' this reveals the following:
![image](https://user-images.githubusercontent.com/9801298/112384100-49037300-8cee-11eb-9a07-cc1b01cc4aae.png)

Resulting in:
![image](https://user-images.githubusercontent.com/9801298/112385359-d1cede80-8cef-11eb-990e-6175c1685ff1.png)

This also happens when not clicking on 'View source'

Also clicking multiple times on View source will result in incorrectly escaping it seems
![image](https://user-images.githubusercontent.com/9801298/112384187-646e7e00-8cee-11eb-9166-b9e3d0cdb476.png)

**Comment by iamromeo** [comment]
Hey Tim (?) @MathijsR94 

the [container] tag is an advanced tag and it is not covered by the simpleWYSIWYG editor that is why you are getting this issue. 

The solution for this , if you wish to use the plethora or advanced tags, is simply to switch from Plato (WYSIWYG) to Euclid. 
You can do this here: 
https://www.worldanvil.com/dashboard/user/interface 

I hope this makes sense
if you need any more help message me here!
