### ISSUE TITLE
Creating article from @test(article) creates test article but never backlinds to @test(article) which just continually makes new 'test' articles.

### ISSUE THREAD

**Issue by Dallasv** [worldanvil/worldanvil-bug-tracker#941]
**World Anvil Username**: Aramec

**World / Campaign / RPG Character / Manuscript Title**: Geron

**Feature**: Article Editing

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Since accidentally upgrading to sage and then downgrading back to grandmaster, any article created via a 'mention' does not resolve the mention to the created article.   Clicking on the @mentioned article just makes a new article.

**To Reproduce**
1. Go to Geron, edit any article, @ an unmade article such as @test(article
2. save changes, view page
3. click on test mention to make a new article 
4. save new 'test' article
5. go back to look at article page you @mentioned test on

**Expected behavior**
Creating an article from an @mention should backlink that created article to the mention instead of generating a new article with the mentioned name when clicked.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Potentially related to #877
