### ISSUE TITLE
Max integer value not validating

### ISSUE THREAD

**Issue by TheLarchTree** [worldanvil/worldanvil-bug-tracker#943]
**World Anvil Username**:ClareD

**World / Campaign / RPG Character / Manuscript Title**:Sandpit - new sheet set up to demonstrate, link below

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/heroes/sheet/997560/edit

**Describe the Issue**
When using a template part of type Integer, the system is not correctly validating the maximum value if one is specified.

**To Reproduce**
If you can access this URL: https://www.worldanvil.com/heroes/sheet/997560/edit this is set up with the issue.
Otherwise create a new sheet with a single template part of type integer, and a maximum value specified.
Set a value in the field which is above the allowed maximum
Save the sheet
No error or validation message shown.

**Expected behavior**
When inputting a value into the box, entering a value higher than the maximum should prompt a validation message

**Screenshots**
![image](https://user-images.githubusercontent.com/102385522/160188287-e9e22b89-42ff-402f-8f38-cd0848111369.png)

As a note when inspecting the content, there is a rogue space in the 'max' field. When this is removed using the inspector, the validation works again. Unfortunately as this template part was created using the UI, it's not possible to directly edit.
![image](https://user-images.githubusercontent.com/102385522/160188502-d9126b22-3186-41a4-92aa-08a23abe8ed5.png)

**Comment by iamromeo** [comment]
Removed the extra space will be deploying later today
