### ISSUE TITLE
articles not appearing on world homepage

### ISSUE THREAD

**Issue by Enverous** [worldanvil/worldanvil-bug-tracker#944]
World Anvil Username: Cae.e

World / Campaign / RPG Character / Manuscript Title: Of Blood and Hearth

Feature: articles??

Many of my articles, that are clearly marked as to be featured on the homepage, are simply not there. I can look them up fine, but they aren't featured. I saw on Reddit that other people were having the same problem but it's been months now and it's still happening. As you can see below, all the articles below the one labelled "magical cores" that are supposed to be featured, arent: 

<img width="488" alt="Screen Shot 2022-03-26 at 5 39 23 pm" src="https://user-images.githubusercontent.com/102404854/160228275-4fc6fcc8-968c-4c4f-8431-f7a786e4515f.png">
<img width="575" alt="Screen Shot 2022-03-26 at 5 40 23 pm" src="https://user-images.githubusercontent.com/102404854/160228289-c230c64f-de4f-496b-be49-64b607a25186.png">

Steps to reproduce the behavior: I'm not sure? there doesn't seem to be any sort of pattern, but I can't seem to replace them with new articles.

**Comment by Kordishal** [comment]
The Featured Articles feature was disabled for performance reason and it still is. There is currently no news when (or even if) it will come back. You can use the [ŧagged] BBCode to simulate the same thing with tags.

However, what you are showing are not featured articles. These are just the uncategorized articles. All the article below Magical Cores are not uncategorized so they do not appear there, but instead appear in their categories. You can disable the display of uncategorized articles in the settings.

The featured articles widget used to be in the center column below the recent articles widget and looks exactly like it.
