### ISSUE TITLE
Adding emotes/emoji to any field makes articles fail to save

### ISSUE THREAD

**Issue by butterdroid** [worldanvil/worldanvil-bug-tracker#945]
**World Anvil Username**: Ydeon

**World**: Yecia

**Feature**: Articles (Tried with plots and NPCs)

**Describe the Issue**
If an emoji is added to any of the fields, it will display (in Windows WinKey+. to bring up the system emojis and selecting one), the page can no longer save. User gets a "Unable to autosave" message, image attached.
Because the error only appears at the top of the page, I didn't know why the changes had not been saved properly.

**To Reproduce**
1. Open any article for editing
2. Insert an emoji
3. Try to save

**Expected behaviour**
Emojis that are part of the Unicode standard should be displayed. If they can't be for some reason, the error message should appear in context so as to not lose data.

**Screenshots**
![image](https://user-images.githubusercontent.com/10198723/160243063-3636c981-4d79-4240-8bd9-41152a2ad71f.png)

**Comment by Kordishal** [comment]
This is not a bug, unicode emojies of a certain size are not supported currently. They can be added in the discussion boards.
