### ISSUE TITLE
BBcode error [discord:]

### ISSUE THREAD

**Issue by MrGadwel** [worldanvil/worldanvil-bug-tracker#946]
**World Anvil Username**: Gadwel

**World / Campaign / RPG Character / Manuscript Title**: Continente

**Feature**: BBCode [discord] don't work

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/continente-gadwel/a/olhos-species (for exemple and and on all others pages)

![image](https://user-images.githubusercontent.com/102283026/160260197-1073f817-43e7-4478-9d7a-6aeb9854981a.png)

Every time I insert a BBCode [Discord] it keeps loading infinitely in the view. I looked for help on the official World Anvil discord server and tried everything they suggested. The last thing I was told to do was to report this as a bug. 

**To Reproduce**
1. Go to World Anvil editor and type [discord:"discord ID"]
2. Load the page
3. See error

**Expected behavior**
Show server online members as described in the World Anvil BBcode guide (https://www.worldanvil.com/w/WorldAnvilCodex/a/bbcode)

**Screenshots**
![image](https://user-images.githubusercontent.com/102283026/160260400-f3e12949-1f17-4ef2-9e56-4729d6746def.png)

**Comment by iamromeo** [comment]
This is not an error with World Anvil
You need to enable your widget for it to work
![image](https://user-images.githubusercontent.com/660175/160529715-f9e43940-4509-404a-bfd6-d332a01bf2c0.png)
