### ISSUE TITLE
Amazing Tales

### ISSUE THREAD

**Issue by Ysardo** [worldanvil/worldanvil-bug-tracker#947]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Amazing Heroes**:
**Amazing Heroes** (Name under which it should be listed on World Anvil):
**Ysardo**:

**[Website](https://amazing-tales.net/amazing-heroes/)**:

**[Logo Image Link](https://amazing-tales.net/amazing-heroes/)**:

**[Logo Usage Terms (URL)](https://amazing-tales.net/amazing-heroes/)**:

**Comment by iamromeo** [comment]
All done
