### ISSUE TITLE
Locked Out of Worlds with Too Many Co-Authors

### ISSUE THREAD

**Issue by BaronessZen** [worldanvil/worldanvil-bug-tracker#948]
**World Anvil Username**: BaronessZen

**World / Campaign / RPG Character / Manuscript Title**: Nino Hogoku (Second Sanctuary)
_Note: Effects whole account._

**Feature**: Co-Authors

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I used to be a grandmaster and used all nine of my co-author slots. At some point, I deactivated my membership since I was no longer using my account/worlds. (I left my worlds untouched—in particular, all my co-authors were still assigned.)

Recently, I wanted to use WorldAnvil for a new project, so I rejoined the guild as a master. However, I can't assign co-authors to my new project because I exceeded the number of co-authors my current subscription allows. 

When I try to switch to my old world to remove the co-authors (either by using the "SWITCH TO..." menu on the side-bar or from the "YOUR WORLDS" menu on my home screen), I get the "Naughty naughty little hobbitses... ...poking their nose where they shouldn't they had." error message saying I don't have access to it.

**To Reproduce**
1. Sign up for a higher tier of guild membership
2. Use all your co-author slots
3. (May not be necessary?) Deactivate guild membership
4. Reactivate at a lower tier
5. Attempt to access a world with co-authors

**Expected behavior**
I expected to be able to access my world to remove all my co-authors so I can reassign the appropriate number for my current tier of membership. Or otherwise be able to revoke my co-authors so I can reassign them.

**Screenshots**

Error page when attempting to access world:
<img width="1299" alt="Screen Shot 2022-03-27 at 6 43 08 PM" src="https://user-images.githubusercontent.com/87511030/160306530-e842b543-50b5-4017-bec6-9cd5492bbf8b.png">

Subscription details:
<img width="565" alt="Screen Shot 2022-03-27 at 6 44 42 PM" src="https://user-images.githubusercontent.com/87511030/160306531-c01e3ac6-b50a-4f5b-babd-4e5002c14cbe.png">

**Comment by iamromeo** [comment]
I will be happy to remove your co-authors but I will need more information in order to do that. Which world do you want them removed from?

**Comment by iamromeo** [comment]
@BaronessZen please reply so I can action this.

**Comment by BaronessZen** [comment]
I would

**Comment by iamromeo** [comment]
@BaronessZen you should be all set now - please let me know if there is still an issue
