### ISSUE TITLE
World was deleted when trying to delete the timeline

### ISSUE THREAD

**Issue by TheBronzeManticore** [worldanvil/worldanvil-bug-tracker#952]
**The Bronze Manticore**:

**Land of the Purple Dragon**:

**Deletion of Timelines**: 

[**Related URLS** (To public & visible pages add screenshots otherwise):](https://www.worldanvil.com/w/land-of-the-purple-dragon-the-bronze-manticore/t/D097D0B5D0BCD0BBD0B8-D09FD183D180D0BFD183D180D0BDD0BED0B3D0BE-D094D180D0B0D0BAD0BED0BDD0B0-development-changelog?preview=1)

I went to the "Development Changelog Timeline" and tried to delete it. It ended was deleted, but the whole World was as well.

**To Reproduce**
1. Go to Development Changelog Timeline
2. Try to delete it

**Expected behavior**
Timeline would be deleted but the world it's a part of will stay on

**Screenshots**
Unfortunately, I dont got any

**Comment by iamromeo** [comment]
Hello @TheBronzeManticore I am really sorry but this cannot be replicated and it is more certainly not the case. 
Deleting a timeline DOES NOT delete the world, this is practically impossible to do.

**Comment by iamromeo** [comment]
Was that a world you need to get back?

**Comment by Kordishal** [comment]
Yes they have said that they need it back on the Discord.

**Comment by TheBronzeManticore** [comment]
> Was that a world you need to get back?

Yes, and asap :-D

**Comment by TheBronzeManticore** [comment]
The world is still missing

**Comment by iamromeo** [comment]
The world is recovered.
