### ISSUE TITLE
D&D Beyond Character sheet importer Error '0:Undefined'

### ISSUE THREAD

**Issue by DanielMcWhorter** [worldanvil/worldanvil-bug-tracker#954]
**World Anvil Username**: SOLVERBRICK

**World / Campaign / RPG Character / Manuscript Title**: https://www.worldanvil.com/epic/the-star-fall

**Feature**: DnD beyond character sheet importer

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.dndbeyond.com/characters/64874150

**Describe the Issue**
The importer works, except for this one character. To describe, I had successfully imported the character my first time using the ID 64874150 as prompted, but then I decided to change my background from sailor to fisher, so I updated that on D&D beyond, but when I went to reimport the character I got a error code of 0:Undefined. I could import other characters of mine just fine, but even making a new copy of this character yielded the same error code, I even attempted to remake the same character new on D&D beyond and got the same error code. However when doing all the same steps on characters that weren't this one, it worked just fine for exciting, edited, and newly created DnD beyond sheets. I attempted to look up what the code '0:Undefined' meant, but I couldn't find or locate any support articles for this issue. 

**To Reproduce**
1. Within editing a DnD 5e 2020 sheet go to the top right on the red bar button labeled "IMPORT D&D BEYOND CHARARTER SHEET"  
2. Click on the button to pull up D&D Beyond Character ID box. In another tab also have your D&D beyond character sheet at the ready. 
3. Copy the character ID from the D&D beyond sheet on another page and paste it into the box (64874150)
4. For a split second on the top right you'll receive the error code 0:Undefined before it fades out a second later. 

**Expected behavior**
The data should be imported onto World Anvil, but nothing occurs.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![ErrorMessage](https://user-images.githubusercontent.com/52330405/160959963-1c7ff3ef-7dce-426c-a7dd-b36eb48ed470.png)

**Comment by iamromeo** [comment]
Is the character public?

**Comment by DanielMcWhorter** [comment]
Yes the chararter is public.

In my trial and error it seems the Fisher background from DnD beyond is causing the issue in the importing process. I ended up working around it by selecting a different background and importing that then manually updating to the fisher background on World Anvil's end.

To note the fisher background is unique in that it only gives one language proficiency and no tool proficiency, in total it only gives the one option and not two options like every other background. My best guess is that the difference is confusing the code or template for that part of the process.

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by xSpazztic** [comment]
In my case, the character in question failed after I added more gear. I tried deleting some of the gear and importing again. I felt like deleting gear little by little and re-trying it repeatedly was more work than I wanted. It was easier for me to delete the character, re-create it, and just not add all (just some) of the gear back. In the end, my Chronomancer made it over safely and with only minor disruptions to the timestream.

**Comment by FroBoyX** [comment]
This is a data formatting issue with the _item_ **Net** which is classified as a `weapon` on D&D:Beyond but doesn't come with an attack value. So the importer chokes on it. Putting in a fix this morning.

Thank you for the thorough bug report @DanielMcWhorter.

**Comment by FroBoyX** [comment]
@xSpazztic it is likely a **gear** related edge case, which is easy for me to diagnose and catch, can you please send me a link to your character sheet so I can handle the *error* and get you back on track!

**Comment by FroBoyX** [comment]
Understood @xSpazztic, due to the nature of the D&D: Beyond character sheets and how many variables they can have (including homebrew content) there are going to be a ton of edge cases. If an import ever fails again assume that it is on my side.

But just getting a link to the character sheet allows me to find the bug, diagnose the missing piece of information, and put in a rule to handle the conversion. D&D: Beyond and World Anvil see characters in fundamentally different ways so it does take some trail and error even in the live release.

Please keep submitting those bug reports, it will help all future importers!

**Comment by FroBoyX** [comment]
@DanielMcWhorter **Surging Thundercloud (Thunder)** now makes it through the _import_ process to get a valid stat block.

Please test it on your end, and it works we will consider this issue closed.

**Comment by DanielMcWhorter** [comment]
> @DanielMcWhorter _Surging Thundercloud (Thunder)_ now makes it through the _import_ process to get a valid stat block.
> 
> Please test it on your end, and if it works we will consider this issue closed.

Yes that did seem to do the trick, and I'm having no issues importing the DnD beyond sheet into WorldAnvil now. Thank you all for the help and my apologies for the delay on my end!
