### ISSUE TITLE
Children and/or Parent Technology creating new Side Panel

### ISSUE THREAD

**Issue by Oneriwien** [worldanvil/worldanvil-bug-tracker#955]
**World Anvil Username**: Oneriwien

**World / Campaign / RPG Character / Manuscript Title**: Ravare

**Feature**: Side-Panel, Technology Template

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/ravare/a/warforging-article
**Describe the Issue**
Currently, the Technology Template places the "Children and Parent" Technology in a different sidebar than I believe it should. 

**To Reproduce**
1. Create two Technology articles.
2. Set one as the parent of the other.
3. Insert basically any text into the SIDEBAR: CONTENT PANEL TOP.
4. Check the page, the parent/child technology will be in a different panel.

**Expected behavior**
The parent/child technology link to be placed UNDER the SIDEBAR: CONTENT PANEL TOP rather than its own side panel.

**Screenshots**
![TechSide](https://user-images.githubusercontent.com/36694877/161164725-4b38c93a-445f-42ae-8888-1469d2993a7b.png)

**Comment by Kordishal** [comment]
This has always been the case. I believe it is on purpose so its more of a design choice to specifically separate out the navigation element for the technology tree.,
