### ISSUE TITLE
Timeline issue

### ISSUE THREAD

**Issue by sdnicol** [worldanvil/worldanvil-bug-tracker#957]
**World Anvil Username**: cyberfed

**World / Campaign / RPG Character / Manuscript Title**: Ethion

**Feature**:  Timeline

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
The symbol in a Historical Event of a timeline, when displayed on the left side of the timeline, covers the Year so it is not fully displayed.

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="938" alt="Screen Shot 2022-04-02 at 2 01 11 PM 1" src="https://user-images.githubusercontent.com/102874686/161395620-23c296a8-62f8-449c-8396-c41321253c31.png">

If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
That is an issue with the theme not world anvil sadly. It has to do with the line-height assigned. 

This system is being refurbished so that should fix the issue but it's not going to be addressed right now.
