### ISSUE TITLE
Read a report button redirects to the wrong page

### ISSUE THREAD

**Issue by spaceconquistador** [worldanvil/worldanvil-bug-tracker#958]
**World Anvil Username**: tolochatlas

**World / Campaign / RPG Character / Manuscript Title**: Terra/Farnai

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise): 

Instead of taking the players to this url 
https://www.worldanvil.com/w/terra-tolochatlas/a/session-1---tails-from-the-sinkhole-report-report, it takes them to this instead:
https://www.worldanvil.com/epic/aZOz44FjuxsYiIDPw61KQ4mNjYsLYi/report/ba865569-0a34-4238-869e-6d42b343fcd4

**Describe the Issue**
I have setup players with the right username and permission. My world is private. I have run a session, written up the report. If my players click on the read the report button, it takes them to this link https://www.worldanvil.com/epic/aZOz44FjuxsYiIDPw61KQ4mNjYsLYi/report/ba865569-0a34-4238-869e-6d42b343fcd4 and they get a 404 error. If instead i manually give them this link https://www.worldanvil.com/w/terra-tolochatlas/a/session-1---tails-from-the-sinkhole-report-report then they can access it. Does the button redirect to the wrong place? 

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window! 
![Sessionsarchive](https://user-images.githubusercontent.com/24643380/161401896-ce67dd0c-449a-4061-a5eb-9c2c7c7395fa.PNG)

**Comment by iamromeo** [comment]
On which page is this button - there were no stept to reproduce this. Can you please link to the page this appears ?

**Comment by iamromeo** [comment]
@spaceconquistador can you please reply so I can proceed with this?

**Comment by iamromeo** [comment]
Closed due to no response from the user
