### ISSUE TITLE
Battle for Diratia

### ISSUE THREAD

**Issue by dylanldionne** [worldanvil/worldanvil-bug-tracker#959]
Remember, to request a RPG System you need to have a Grandmaster subscription. The reason for this is to make sure that it is at least theoretically possible for you to create statblocks for that system. Make sure to fill in the first for points at least, otherwise the reqeust will not be considered.

**Full Name (RPG SYSTEM)**: Battle for Diratia
**List Name** (Name under which it should be listed on World Anvil): Battle for Diratia
**World Anvil Username**: ProductionsDiratia

**Website**: https://www.wargamevault.com/product/338540/Battle-for-Diratia--Wargame--RPG-hybrid

**Logo Image Link**: https://1drv.ms/u/s!AitJD3IMRsS0jIYlbHZVUnhdRTzMEA?e=vXoAXA

**Logo Usage Terms (URL)**: https://www.productionsdiratia.com/brandassets

Do not hesitate to contact for additional details : productionsdiratia@hotmail.com

**Comment by iamromeo** [comment]
Thank you for submitting @dylanldionne  - the game is added - when you have a full collection of sheets we can add logo etc as well :)
