### ISSUE TITLE
Visibility Toggle Nonfunctional in Map Article Summaries

### ISSUE THREAD

**Issue by TrivialGalaxy** [worldanvil/worldanvil-bug-tracker#96]
**World Anvil Username**:
TrivialGalaxy

**World / Campaign / RPG Character / Manuscript Title**:
Alevar

**Feature**: 
Visibility Toggle

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/alevar-trivialgalaxy/map/3609f021-e136-4bf8-93f0-9cc644e577c8

**Describe the Issue**
Just as said in the title. The visibility toggle feature that was recently added for Grandmasters does not work when viewing an article from a marker in a map.

**To Reproduce**
1. Go to my link in **Related URLS**.
2. Click on the upper left white marker in the black area.
3. If the last word in the article preview is "entering", the bug is still active.

**Expected behavior**
Everything from the paragraph that starts with "Glindrel existed before the Ooze..." is marked secret with visibility toggle on the main article, but is visible to everyone who views the article from the map.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![screenshot1](https://user-images.githubusercontent.com/44380948/112410176-c926da00-8ce8-11eb-9886-a8b44b3429e5.PNG)
![screenshot2](https://user-images.githubusercontent.com/44380948/112410185-cb893400-8ce8-11eb-9c87-f0a1d562317b.PNG)

**Comment by iamromeo** [comment]
Visibility was never meant to work on map sidebar it's a quick shortcut not a work-all-over solution. 
Subcontainers / secrest are the standard way and work across all entities. 
We will see if the new Map system can take care of this
