### ISSUE TITLE
Whiteboard preferences are not stored.

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#960]
**World Anvil Username**: SoulLink

**Describe the Issue**
The preferences of the whiteboard are not stored beyond the current session.

**To Reproduce**
1. Change the preferences from default.
2. Reload the page.
3. See that the preferences reverted to the original state.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/14262536/161413723-d22115bb-1b34-475c-9faa-fda687236eda.png)

**Comment by iamromeo** [comment]
They are not meant to - this was never part of the brief. Please file a feature suggestion.
