### ISSUE TITLE
Whiteboard can't be panned while cursor is on an element

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#961]
**World Anvil Username**: SoulLink

**Describe the Issue**
Panning can be done with the middle mouse button. When pressing it while the cursor is hovering over any element that covers up the background it will not enable panning. This is a problem when most of the background is covered by something.

**To Reproduce**
1. Add an element to a whiteboard
2. Hover the cursor over the element.
3. Press middle mouse button to enable panning
4. Move mouse
5. No movement of the whiteboard occurs.

**Comment by iamromeo** [comment]
Indeed this cannot be done - the alternative which is using the spacebar works.

**Comment by Kordishal** [comment]
The space bar method doesn't work when the whiteboard is embedded though.
