### ISSUE TITLE
Embedded whiteboard CSS affects article layout

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#962]
**World Anvil Username**: SoulLink
**Related URLS**: https://www.worldanvil.com/w/WBtV/a/hunters-guild

**Describe the Issue**
When the whiteboard is embedded it affects headings, article title and spacings in various places.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

With Whiteboard:
![image](https://user-images.githubusercontent.com/14262536/161415237-c0b8207a-d05c-450d-af34-9defeaa8fa5c.png)

No Whiteboard:
![image](https://user-images.githubusercontent.com/14262536/161415247-9f4d8fab-abd0-4fc2-af58-16d8c02426be.png)

With Whiteboard:
![image](https://user-images.githubusercontent.com/14262536/161415273-24388ca1-0d35-4cb7-923f-4f3c9c03f330.png)

No Whiteboard:
![image](https://user-images.githubusercontent.com/14262536/161415287-f3556898-85b4-4cdb-8afa-0cecd3b860df.png)

**Comment by iamromeo** [comment]
That needs fixing indeed :)

**Comment by Duranzno** [comment]
Gotcha! Adding it to Todo Tasks

**Comment by RiverFang13** [comment]
Also to add on to what SoulLink posted, only my h2, h3, and h4 headings are affected (shrunk considerably). Article title and h1 remained the same when a Whiteboard was embedded.

Example: https://www.worldanvil.com/w/isekai/a/professions-article

**Comment by Duranzno** [comment]
Working on this

**Comment by Kordishal** [comment]
@Duranzno Did you fix this? It no longer affects my article.

**Comment by Kordishal** [comment]
It is back again after it was fixed? Or at least it didn't 8 days ago, but now it is back to how it was.

**Comment by iamromeo** [comment]
Hello @Kordishal after estimating this we figured out that since the impact is not so and it will take a very long time and effort to implement this on this version we will be tackling this to the new presentation version but not this one.
