### ISSUE TITLE
Text tool deselects on first use instead of creating a text element.

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#966]
**World Anvil Username**: SoulLink
**Feature**: Whiteboards

**Describe the Issue**
When loading up a whiteboard for the first time and using the text tool it just switches to the select tool when clicking on the background. This does not happen when clicking on an existing element instead.

Once the text tool works it works for the entire session. When the page is reloaded the issue exists again.

**Comment by Duranzno** [comment]
First Reported Bug on Github! Gonna be checking it out

**Comment by iamromeo** [comment]
Is this still relevant @Duranzno @Kordishal  ?

**Comment by Kordishal** [comment]
Yes, this has not been fixed yet.

**Comment by iamromeo** [comment]
We have tried this across Mac, PC and Linux and Chrome / Firefox and we cannot replicate it - we are closing this for the time being but the possible issue is recorded
