### ISSUE TITLE
Can't scroll sideways on a Mac using White Board?

### ISSUE THREAD

**Issue by BonnieJuju** [worldanvil/worldanvil-bug-tracker#969]
**Bonnie Juju**:

**White Boards**:

Hi World Anvil:
While checking out the white board feature I've discovered I can't scroll sideways using shift-mouse wheel (it works on my work PC however.) Checking into this it appears to be a problem with Macs in general. :(  
Is there any way a horizontal scroll bar can be added to the bottom of the white boards for us eccentrics who are still using Macs? Thank you!

-Bonnie Juju

**Comment by Duranzno** [comment]
Noted and added to the ToDo

**Comment by iamromeo** [comment]
Is this still relevant?

**Comment by BonnieJuju** [comment]
Hi Dimitris:

Yes, unfortunately I still can't scroll horizontally with on my Mac. I can do it with programs like Excel by holding down the shift key & using the mouse wheel, but for some reason it doesn't work with the White Boards. Any help you can provide would be greatly appreciated!

-Julia
________________________________

**Comment by Duranzno** [comment]
This is now fixed

**Comment by BonnieJuju** [comment]
Thank you, Alejandro and World Anvil team! I really appreciate the work you all do behind the scenes. 💚

-Julia
________________________________
