### ISSUE TITLE
Articles with whiteboards loading unusually

### ISSUE THREAD

**Issue by Animals82** [worldanvil/worldanvil-bug-tracker#972]
**World Anvil Username**:
Mochimanoban
**World / Campaign / RPG Character / Manuscript Title**:
Yonderverse
**Feature**: 
Whiteboards
**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/jerna-s-diary-mochimanoban/a/nature-article
**Describe the Issue**.
When I view my articles containing whiteboards, it will not load at the top of the page. Instead, it loads part way through the whiteboard. 
**To Reproduce**
1. Go to an article containing a whiteboard, such as the one linked.
2. Notice that the article does not load at the top of the page.

**Expected behavior**
I would expect the article to load at the top of the page, instead it loads where the whiteboard is.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
<img width="949" alt="2022-04-07 (1)" src="https://user-images.githubusercontent.com/41923883/162252545-ff600180-460c-414d-bf4f-97b88281994c.png">
This is what occurs as soon as I click on the article ^

**Comment by Kordishal** [comment]
This doesn't happen for me on your article. Does it happen if you log out and look at the article?

**Comment by Animals82** [comment]
Yes, I logged out and tried it, and I logged back in and tried it again. Both times it happened

**Comment by Kordishal** [comment]
What is your device browser combination? And your resolution?

**Comment by iamromeo** [comment]
Closed due to no response from the user
