### ISSUE TITLE
Plot Dashboard HTTP ERROR 500

### ISSUE THREAD

**Issue by edmonan** [worldanvil/worldanvil-bug-tracker#979]
**World Anvil Username**: edmonan

**World / Campaign / RPG Character / Manuscript Title**: World - Toril; Campaign - Waterdeep: Above and Below

**Feature**: Plot interface

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/heroes/campaign/plot/list

**Describe the Issue**
When I try to open the Plot interface in my campaign Waterdeep: Above and Below I get HTTP ERROR 500. This is a recent development, and I have other campaigns inside the Toril world (Tyranny of Dragons) and in another world: Ravenloft (Mist Hunters) that do not have this issue. In the case of ToD and R:MH there are no plots currently assigned, but I did create test plots and successfully assigned them.

**To Reproduce**
1. Go to 'https://www.worldanvil.com/heroes/campaign/9a80dde4-d797-4d61-acab-61160f525a98/dashboard'
2. Click on 'PLOTS' link
3. See error

**Expected behavior**
I expect the plot dashboard to open.

**Screenshots**
![Screen Shot 2022-04-13 at 7 45 52 AM](https://user-images.githubusercontent.com/4227916/163185769-b3da63c0-7fe5-40ed-aa2b-b82170bad25a.png)

**Comment by Kordishal** [comment]
This means that there is a loop in your plots. Remove parent plots until the page loads again.

**Comment by edmonan** [comment]
Hi!

Thanks Jonas for the quick response.

Your advice helped me resolve the issue, but the issue wasn’t a loop in my plots.

I added a plot (https://www.worldanvil.com/w/toril-edmonan/a/6-hell-of-a-summer-plot) to my campaign(https://www.worldanvil.com/heroes/campaign/9a80dde4-d797-4d61-acab-61160f525a98/dashboard), then gave that plot a parent (https://www.worldanvil.com/w/toril-edmonan/a/waterdeep3A-dragon-heist-plot). The parent plot had no parent. It was not the child of any of its children. There was no loop.

Removing the parent plot from the plot that was attached to the campaign fixed the issue.

I tested it a couple more times. It looks like any attempt to add a plot that has a parent plot to a campaign crashes the system. I don’t think that was outlined in any of the documentation I read.

I may have done something to create this that I am unaware of, but I wouldn’t consider this bug closed.

Thought you might want to know.

Thank again,
Andy

andy_edmonds = {
expertise: ['web design','web development','digital marketing'],
email: ***@***.***',
phone: '773-575-0780'
}

**Comment by Kordishal** [comment]
When I add one plot with a parent to the campaign it continues to work. It just does display that plot and not its parent since it does not check for it.

Did you assign multiple plots to the campaign? Because I did play around it and the screen did crash once I had two plots added to the campaign with each one parent and no loops.

So yeah there appears to be at least one more condition under which this fails.

I will leave the issue closed, because this will not be addressed until the next iteration of the Campaign interface.

**Comment by edmonan** [comment]
Thanks!

I only had one plot assigned to the campaign at a time. I may have done something else weird that I don’t remember though.

I appreciate your time!

andy_edmonds = {
expertise: ['web design','web development','digital marketing'],
email: ***@***.***',
phone: '[773-575-0780](tel:7735750780)'
}

------- Original Message -------
