### ISSUE TITLE
D&D Beyond Import does not add class features and levels of fifth character class on multi-class character.

### ISSUE THREAD

**Issue by DSewell83** [worldanvil/worldanvil-bug-tracker#980]
**World Anvil Username**:DinahUnscripted

**World / Campaign / RPG Character / Manuscript Title**:Amarisia
**Feature**:  Statblocks

**Related URLS** (To public & visible pages add screenshots otherwise):https://www.worldanvil.com/w/the-island-matriarchy-of-amarisia-dinahunscripted

**Describe the Issue**
I imported a character sheet with multiclass cleric 12, sorceror 1, fighter 1, rogue 3, bard 3. The import process is chopping off the bard class features and levels from the WA character sheet interface. 

**To Reproduce**

**Expected behavior**
Character importer should not be cutting off portions of my class levels and class features.)

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by FroBoyX** [comment]
Hey, @DSewell83 I need the character ID/URL to see if I can solve the issue.

**Comment by iamromeo** [comment]
Closed due to no response from the user
