### ISSUE TITLE
Pages in Notebook Disappeared

### ISSUE THREAD

**Issue by wolfofwinter** [worldanvil/worldanvil-bug-tracker#982]
World Anvil Username: WolfofWinter

Feature: Notebook

Related URLS (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/notebook/

Describe the Issue
I had a lot of information on my notebook, I went into the notebook and found that all my pages had gone except one which is the first one I made. All my sections are still there but not the pages. I'm unsure when and how this happened.

Expected behavior
I expected all the pages I had made to be in there sections.

Screenshots
 ![blank](https://user-images.githubusercontent.com/103697598/163488388-f0191853-4505-4ad0-baf0-09eaed2b52d7.png) #982

**Comment by iamromeo** [comment]
Hello there! Hmm that is practically inpossible - there is no function that mass deletes notes on World Anvil (literally not coded) 
Can you give me an example name of a note you've written and cannot find?

**Comment by iamromeo** [comment]
![image](https://user-images.githubusercontent.com/660175/163661184-6b5fa326-ad61-4103-9f07-0b8619781826.png)

This is the only note I have in record under this account.

**Comment by wolfofwinter** [comment]
I had all my dnd notes on my account like lists of questions to ask and plot points before i turned them into pages. The page u found is the first page I made on my account when I first joined but the rest are gone. I also don't have a second account because all my world building stuff from the past year are on the worlds.

**Comment by wolfofwinter** [comment]
> ![image](https://user-images.githubusercontent.com/660175/163661184-6b5fa326-ad61-4103-9f07-0b8619781826.png)
> 
> This is the only note I have in record under this account. Created on: 2021-01-17 16:35:52 Last updated: 2021-01-17 16:57:25
> 
> Is there a chance that you have a secondary account ?

I had all my dnd notes on my account like lists of questions to ask and plot points before i turned them into pages. The page u found is the first page I made on my account when I first joined but the rest are gone. I also don't have a second account because all my world building stuff from the past year are on the worlds.

**Comment by iamromeo** [comment]
Hey @wolfofwinter this is indeed very odd, because World Anvil most certainly does not delete content out of nowhere (even if you had to drop your membership) and I have no record of any notes. Normally there would be indicators of even deleted content which I cannot find anywhere. 

Can you remember the Title of any of your notes JUST in case I can find it somewhere else? Or any piece of content in them?

**Comment by wolfofwinter** [comment]
@iamromeo The only bit I remember was a list of court places like court wizard with information on the placements. I also have a page called Things to Keep Track of. This is all I remember unfortunately because I had a few of them.

**Comment by ike9899** [comment]
I have also been having this issue. Specifically, I cannot access about half of my pages on the default notebook (which displays the incorrect name), and only have access to one notebook that is _not_ the default. When I switch to the single notebook available, it has all of the sections and pages it should - however, I cannot access the default notebook and the three pages I had access to when pulling up the notebook. I _can_ create new notebooks, sections, and pages and those remain visible and accessible.

![image](https://user-images.githubusercontent.com/104152370/164484171-e1fa752b-b224-4ea6-aac0-8239788e075a.png)
![image](https://user-images.githubusercontent.com/104152370/164484481-64978631-fb23-40cd-bc2a-fc8eb63598cd.png)
![image](https://user-images.githubusercontent.com/104152370/164484638-8e28321f-a135-484a-aa26-1a0706287fd9.png)

Additionally, when I try to navigate to the manage notebook page in the default notebook, it takes me to the error 404 page. I do not have this problem when I try to navigate to any other notebook edit pages.

![image](https://user-images.githubusercontent.com/104152370/164485651-5710aa9f-805c-4c49-98f9-b49a748abd8a.png)

I believe the notebook I lost is named "Grim Hollow," one of the sections should be named "Meta," and some of the pages I'm missing I believe were things like "Rule Systems," "Rule tweaks," or "Campaign Ideas." 

I have attempted to clear cookies and delete history to no avail. I usually use Firefox, but have attempted to use Chrome and Edge, as well as the android versions of Firefox and Chrome and none of them have worked.

**Comment by iamromeo** [comment]
@wolfofwinter are you aware of a user called **ike9899** ?

**Comment by iamromeo** [comment]
![image](https://user-images.githubusercontent.com/660175/165262701-f932357e-ab98-4a19-b3a8-2b5ef2f9367b.png)

**Comment by Kordishal** [comment]
I think you mixed this up Dimitris. ike9899 is who reported that they do not see the notebooks that you found. wolfofwinter is a different user looking for different pages,

**Comment by iamromeo** [comment]
ok so @ike9899 I have found YOUR note sections and indeed they have no notebook - I am not sure how this has happened but they are recoverable. Do you want me to put them on the notebook you currently have? 

and yes @Kordishal  I was confused thank you for letting me know.

**Comment by ike9899** [comment]
@iamromeo Yes, that would work for me - I can just sort them back out into new notebooks. Sorry for the confusion on users

**Comment by wolfofwinter** [comment]
@iamromeo i've given the information that I remember as i had a lot of pages, so I can't remember what i've lost because I lost it.  
This is all I can remember losing, a list of court places like court wizard with information on the placements. I also have a page called Things to Keep Track of. There was also a page with my dnd notes on. I'm sorry that I can't give more info, I don't know what else to give.

**Comment by iamromeo** [comment]
Sadly after multiple efforts I cannot find the notes or any trace of them under the account. The only way that this could have happened is if someone actually deleted the notes. I have also tried to search through the code for any rogue way to delete a note and there is none apart from deleting it or the notebook it was in.
