### ISSUE TITLE
Conworld vanished after upgrading membership

### ISSUE THREAD

**Issue by halian** [worldanvil/worldanvil-bug-tracker#983]
**World Anvil Username**: Hālian

**World / Campaign / RPG Character / Manuscript Title**: Safir Alliance

**Feature**: Worldbuilding

**Related URLS** (To public & visible pages add screenshots otherwise): I don't remember :(

**Describe the Issue**
Now that I've upgraded my membership to Guildmaster, my conworld, and all characters/articles thereto attached, have vanished. If possible, I should like to have them restored, please.

**To Reproduce**
1. Make a conworld.
2. Write some articles.
3. Vanish from the site for some years.
4. Return and upgrade your membership.

**Expected behavior**
The continued existence of the conworld and associated articles.

**Screenshots**
N/A

**Comment by iamromeo** [comment]
Hello there, I am not sure what a conworld is - but I can tell you that there has ever only been 1 world on this account called 
**Safir Alliance** that world was de;eted by you. Of course, upgrading does not delete worlds :)

**Comment by halian** [comment]
> Hello there, I am not sure what a conworld is

It's short for “constructed world”, in the same vein as “conlang”, and is a synonym for “worldbuilding project”.

> but I can tell you that there has ever only been 1 world on this account called **Safir Alliance** that world was de;eted by you. Of course, upgrading does not delete worlds :)

I'm a doofus. Consider my face duly egged. Is there any way to undelete it or no?

**Comment by iamromeo** [comment]
hey @halian I will see what I can do :) We caught it early

**Comment by iamromeo** [comment]
@halian I think I managed to save most if not all of it - it should be back available to your account
