### ISSUE TITLE
Not published manuscripts visible for the community

### ISSUE THREAD

**Issue by KajetanWrites** [worldanvil/worldanvil-bug-tracker#984]
**World Anvil Username**: KajetanWrites

**Manuscript Title**: Blue Blood

**Feature**:  Manuscripts (the community page)

**Related URLS**: https://www.worldanvil.com/community/manuscripts?genreId=76fc4a3f-037e-4966-8005-779242347101

**Describe the Issue**
Like the title of the issue says. My manuscript titled "Blue Blood" isn't published, but is still visible on the community page for manuscripts. I asked someone else to check if they see it on their account and it is still there. Luckily, no one can read it, but it still seems strange that a manuscript that isn't published is visible.

**Comment by KajetanWrites** [comment]
One more thing. The search doesn't find the manuscript. It is visible when browsing by genre

**Comment by PrincessHoneytea** [comment]
This also happened to my unpublished, private manuscript. People could see the cover and the synopsis and it said that my MS had 128 views. I removed all the genres and the language tag from it as a stop gap measure. :C

**Comment by iamromeo** [comment]
Fixed will deploy today
