### ISSUE TITLE
Ampersand & is HTML escaped in URL BBcode added to article

### ISSUE THREAD

**Issue by kazeookami** [worldanvil/worldanvil-bug-tracker#986]
One of my writers is trying to add a link to the credit section of an article they are writing. It is entered as follows;

[url:https://www.amazon.com/s?i=digital-text&rh=p_27%3AT.+Castellan&s=relevancerank&text=T.+Castellan&ref=dp_byline_sr_ebooks_1]Amazon[/url]‌)

The link entered is not the same link that results.

https://www.amazon.com/s?i=digital-text&rh=p_27%3AT.+Castellan&s=relevancerank&text=T.+Castellan&ref=dp_byline_sr_ebooks_1
https://www.amazon.com/s?i=digital-text&amprh=p_27%3AT.+Castellan&s=relevancerank&text=T.+Castellan&ref=dp_byline_sr_ebooks_1

The top link is the one entered, the bottom one is the one that results when clicking the link. Notice it's adding AMP in resulting in the link breaking.

**Comment by Kordishal** [comment]
According to #666 this might be working as intended. Though not sure if this is only supposed to work like that on the map or in an article as well.

In the meantime the URL shortener should be a workaround for this as well.

**Comment by iamromeo** [comment]
This works as intended. In your case, you can use a url minifier as bit.ly to make this work :)
