### ISSUE TITLE
Massive issue

### ISSUE THREAD

**Issue by IhsanEffulgence** [worldanvil/worldanvil-bug-tracker#989]
**World Anvil Username**:
palerider391
**World / Campaign / RPG Character / Manuscript Title**:
I'm not sure this is applicable since it happens even before signing in. A friend of mine can't even get into the site cause it happens the moment he opens it
**Feature**: 
Peace for Ukraine i guess? It's the only thing i can think of since it's the only thing we can interact with
**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.
The peace for Ukraine thing you are promoting is causing massive issues when i or my friends try to use your site. It makes it so we can't click on anything but it and then when we do and go back it still won't work.
**To Reproduce**
I'm not really sure but it just happens. 

**Expected behavior**
I would like it to either be removed, fixed, or added as a banner/button on the site itself and not an addition.
**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Screenshot_20220419-202247](https://user-images.githubusercontent.com/104041519/164122330-b4aa1df2-c4b1-466a-a92a-86ccf19e41b6.png)

**Comment by iamromeo** [comment]
This is not related to the ICRC (Red Cross) link
The chances are you are using an outdated version of IE or EDGE that doesn't support pop ups

Use a decent modern browser like 
- CHrome
- Safari
- Firefox
- Brave 
- Opera
- Enter name of any browser not by Microsoft
and it will work.

**Comment by IhsanEffulgence** [comment]
See that would be a decent answer if it didn't also do the same thing on
the phone which uses Google chrome....

**Comment by Kordishal** [comment]
This happens from time to time on mobile. It is a pop-up either for an ad or some other promotion that is in the way but not on the screen. The usual workaround is to open the website on a desktop environment and click it away. After that it works again.

**Comment by IhsanEffulgence** [comment]
Ok I'll try that. I think i see the issue. It's that last chance sale y'all
are running that pops up every chance it gets. It's weird though cause i
can't interact with the screen but CAN click on the Ukraine thing
