### ISSUE TITLE
Please allow Ctrl+Z on pasted data.

### ISSUE THREAD

**Issue by silent107** [worldanvil/worldanvil-bug-tracker#990]
**World Anvil Username**:

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Ctrl+Z doesn't work when copying data from an external document.

**To Reproduce**
Type some data in a notepad app. Paste it. Try Ctrl+Z.

**Expected behavior**
The pasted text should disappear.

**Comment by Kordishal** [comment]
This issue only appears with the Plato editor. The Euclid editor has full undo support. The Plato editor will be reworked in the future and will then most likely support undo as well. 

If this is something you absolutely need then you should switch editors until then:

https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors
