### ISSUE TITLE
Authors added to world don't obey article/category privacy settings  

### ISSUE THREAD

**Issue by N7Huntsman** [worldanvil/worldanvil-bug-tracker#991]
**World Anvil Username**: N7Huntsman

**World / Campaign / RPG Character / Manuscript Title**: Age of the Wolf

**Feature**: Access Rights Management

**Related URLS** (To public & visible pages add screenshots otherwise): **See screenshots.**

**Describe the Issue**
Writers added to the private world can see and browse private categories from the world home page and see the titles of private articles they did not create within those categories, despite not being part of a subscriber group that grants access to those categories/articles. If the article within this private category is private, they cannot view it. If it is public, the writer can view it.

**To Reproduce**
1. Create a private category and article in a world with no subscriber group access to that article/category.
2. Add another account to the world as a writer via access rights management.
3. Using the writer account, view the world home page.
4. Browse the codex and see the private category and article title.

**Expected behavior**
Expected that writers added to the world will not be able to see private categories or articles that they do not otherwise have access to via subscriber groups and did not create.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**1. Add an account to the world as a writer.**
![1](https://user-images.githubusercontent.com/38633594/164181345-68ec8d4c-73bf-473b-b1f8-7cb6ac8b900d.PNG)

2. Create a private article, within a private category.
![2](https://user-images.githubusercontent.com/38633594/164181442-7c1f4281-9407-4830-a707-4c58f90c1d4a.PNG)
![3](https://user-images.githubusercontent.com/38633594/164181521-c2905235-b6ee-43b2-a603-ef63d1ef9e91.PNG)

3. Switch to the writer account.
![4](https://user-images.githubusercontent.com/38633594/164181582-e0d80f01-dcf2-4227-a209-19db388211f0.PNG)

4. Browse private categories and view article titles.
![5](https://user-images.githubusercontent.com/38633594/164181676-ca462e33-c92c-4a33-b204-b4e351738fde.PNG)

**Comment by iamromeo** [comment]
I am sorry, I might be misunderstanding but ... authors have access to everything. This is not a bug, this is literally a feature. 
Feel free to reply to elaborate.

**Comment by Kordishal** [comment]
They are talking about writers & advanced writers. Not authors in general. 

In the writer interface they can only see the list of articles that they have created. Nothing else.

On the presentation however, writers can see every private article and category ignoring privacy in the **tables of contents**. This can reveal quite a bit of information. This is the only place where Writers get additional permissions that they do not need or should get really.

**Comment by N7Huntsman** [comment]
Sorry for the confusion. From my conversation with the helpers on the WA discord, it's as Kord describes.

Writers and Advanced Writers shouldn't be granted additional permissions to see private content they didn't make, but are and can see stuff in presentation mode that they shouldn't be able to.

**Comment by N7Huntsman** [comment]
@iamromeo Kord explained the issue better than I could. Any further details I can provide that might help clarify what I mean?
