### ISSUE TITLE
RPG System Selection lists Unisystem twice

### ISSUE THREAD

**Issue by Catspur** [worldanvil/worldanvil-bug-tracker#992]
**World Anvil Username**: Catspur

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: selecting rpg system

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is. when selecting an rpg system for your world the list has Unisystem twice, with no differentiation between them. There is more than one type of Unisystem, Classic and Cinematic, and some variations within those based on what rules book it comes from. So I don;t know if its the same thing just listed twice, or if one if class and the other cinematic but they haven't been correctly labelled, or some other variation. Most of my games are Unisystem based so I would appreciate it being looked at, thank you.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Thank you for the heads up :_)
