### ISSUE TITLE
Issue with URL on google search

### ISSUE THREAD

**Issue by Ishural** [worldanvil/worldanvil-bug-tracker#994]
**Username : ISHURAL**:

**Name of the world : ISHURAL SG - La Saga Galactique**:

**Feature : Grandmaster**: 

**[Related URLS](https://www.worldanvil.com/w/ishural-sg---la-saga-galactique-ishural)** (To public & visible pages add screenshots otherwise):

**I have an issue with my second world, "Ishural SG" i renamed this world a few days ago and as expected the url is not the same. old title : ISHURAL - La Saga Galactique, New Title : ISHURAL SG - La Saga Galactique. 
My problem is that now every page that i can find on google under my world name goes error 404 because the results kept the same old url that doesnt exists anymore, i had a couple of friends who visited the world during work in rpogress thats why some results appear on google. I tried to do a reconnection but it did not fix it. I would like the result to feature the new url and stop showing the old one that doesnt work anymore. All of this is just because of two letter in the world name.
Do you know if the results will be updated automatically? Will google make appear the new URL when new people will come on the site? **
A clear and concise description of what the issue is.

**To Reproduce**
1. Go to 'google'
2. Tap 'ISHURAL SG WORLD ANVIL'
3. The results only show ISHURAL - La Saga Galactique (the old title)
4. Click on 'ISHURAL - La Saga Galactique'
5. See error 404

**Expected behavior**
1. Go to 'google'
2. Tap 'ISHURAL SG WORLD ANVIL'
3. The result with the new name should appear "ISHURAL SG - La Saga Galactique"
4. Click on 'ISHURAL SG - La Saga Galactique'
5. See main page of the world

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

Google search : 
![Capturehggh](https://user-images.githubusercontent.com/104134469/164424430-3c6f68eb-be12-4e6b-b953-a0297670e1fb.JPG)

Expected result : 
![Capture](https://user-images.githubusercontent.com/104134469/164424026-a60e40c2-2e24-4276-83c9-d05e5d3a70ae.JPG)

Actual result : 
![Capturefdgdfgdf](https://user-images.githubusercontent.com/104134469/164424648-4bdc5e5c-5d3e-4174-a1aa-c4e103f7686d.JPG)

**Comment by iamromeo** [comment]
Hey there @Ishural 
That actually has nothing to do with World Anvil. This is an issue with the fact that Google has not crawled your new URL just yet.  :) 

In theory Google will crawl your world and find out the other no longer exists and update its internal database
