### ISSUE TITLE
Unable to Edit Any Maps

### ISSUE THREAD

**Issue by b57123m** [worldanvil/worldanvil-bug-tracker#995]
Bambam57:

Maps:

Edit Maps: 

Anytime I try to edit a map in my world, the site crashes. I haven't updated my maps in a while but back when my world would not load, removing the maps from my homepage allowed me to keep working. I don't think I have edited a map since then but yesterday I tried to edit one and I got this error

![image](https://user-images.githubusercontent.com/91383290/164571241-1aefd732-0a69-42ff-8f43-5eeb3b5a38b9.png)

As of now I cannot edit any maps, even the small ones with just an image and no markers yet.

This is all I see when I view the console on the crash

![image](https://user-images.githubusercontent.com/91383290/164571358-23f8cede-2d5b-4186-aff7-ca7ca41420e3.png)

**Comment by iamromeo** [comment]
Hey @b57123m oh no! Ok, I will have to once again have a look at this specifically. 
Can you please send an email to me at: dimitris@worldanvil.com
Include your
- Username
- Password (crreate a new, safe password before sending it to me) 
- The world that is happening to  (if you have more than one)

**Comment by b57123m** [comment]
I have sent the email and changed my password to something safe. Let me know if you require anything further.
Thanks!

**Comment by b57123m** [comment]
Since I am unable to delete maps without entering the edit interface, I was wondering if having a delete icon on the map list would be beneficial.
![image](https://user-images.githubusercontent.com/91383290/170701369-119c41c4-cd9d-4817-95b7-660c3cb7a6f5.png)
Then I could try getting rid of some of my larger maps and see if that fixes my issues.

**Comment by Kordishal** [comment]
Hi!

This is starting to sound like issue #988. Do you have a lot of articles?

**Comment by b57123m** [comment]
Yes, Dimi and I have spoken before how issues I have ran into before are due to  the size of the world I have built.

**Comment by iamromeo** [comment]
@b57123m I will be messaging you in private about this.

**Comment by b57123m** [comment]
@iamromeo  Just touching base on this, I see the merged issue is still open but I was wondering if the expected fix for the large load times has an estimated completion timeframe? I am able to work on my articles in the Articles page, limiting me to only be able to add to my vignette. This works for now but any information I need to update that is template specific I am unable to adjust. Lately I have been completely unable to launch the Dashboard as well which was a quick way for me to see and create new articles. I appreciate any information you are able to provide as I know development is busy with other things.

**Comment by b57123m** [comment]
Checking in again on this issue. I am still unable to utilize many of World Anvil's features without issue. I have tried many of the templates but it seems none of them can load.
