### ISSUE TITLE
Deleting parent categories hides but does not delete child categories

### ISSUE THREAD

**Issue by nic-hartley** [worldanvil/worldanvil-bug-tracker#996]
**World Anvil Username**: nic-hartley

**World / Campaign / RPG Character / Manuscript Title**: Y Ddaer

**Feature**: Article categories

**Related URLS**: https://www.worldanvil.com/world/athena/

![image](https://user-images.githubusercontent.com/4331760/164599733-77aebcb1-79a1-4b80-8cc1-14a7e0b8b656.png)

**Describe the Issue**

Deleting parent categories doesn't delete child categories, but it does remove them from the list until the list is refreshed.

**To Reproduce**
1. Create a category. Create another. Set one as the parent of the other.
2. Delete the *parent* category
3. Note that the child also appears to be gone
4. Refresh to see the child still there, moved up to the level in the hierarchy where the parent was

**Expected behavior**

One of two:

- The children should be deleted as well
- The children should be visible, moved up one level in the hierarchy

**Screenshots**

Two categories:

![image](https://user-images.githubusercontent.com/4331760/164599994-d0467142-400a-4a55-88db-d5a504c67445.png)

Deleting the top one:

![image](https://user-images.githubusercontent.com/4331760/164600095-64d96324-b4b9-4a1a-81cb-9fac21c99888.png)

Neither Test nor Test2 are visible:

![image](https://user-images.githubusercontent.com/4331760/164600155-e0039064-4255-47ab-90d1-f7464ec7d7ed.png)

After refresh, Test2 is back:

![image](https://user-images.githubusercontent.com/4331760/164600210-e6a19f71-e8e6-40b4-a1da-6ae2daa11a05.png)

**Comment by iamromeo** [comment]
That is very correct and works as intended.
