### ISSUE TITLE
Can't set map to public

### ISSUE THREAD

**Issue by draconefox** [worldanvil/worldanvil-bug-tracker#997]
**World Anvil Username**: draconefox

**World / Campaign / RPG Character / Manuscript Title**: The Hallowed lands

**Feature**: Map

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

I recently had to downgrade/cancel my subscription and subsequently made my world public so that my friends could still see it. However, the continent map of my world is not visible on the World Page and is still set to be private. When going into the settings, it says the map is public, but when i save the settings it stays hidden and i can't change anything to make it actually be public

**To Reproduce**
1. Go to 'Maps'
2. Click on 'Continent Map Settings'
3. Scroll down to 'Privacy Settings'

**Expected behavior**

I expected being able to set the map on public.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

![Map List](https://user-images.githubusercontent.com/104215468/164743701-810fc08f-0f8a-431e-bba1-1f216a80da82.PNG)

![Map settings](https://user-images.githubusercontent.com/104215468/164743716-dbb2181c-9018-4d56-b941-9e7fa2ee45ba.PNG)

**Comment by iamromeo** [comment]
Is your world public or private?

**Comment by draconefox** [comment]
it's currently set on public, and everything but this map is visible for everyone.

**Comment by iamromeo** [comment]
@draconefox I am sorry - I am confused now - don't you want your map to be public ?

**Comment by Kordishal** [comment]
The map is private. The rest is public. And they can't set it to public as it doesn't save the change for some reason.

**Comment by draconefox** [comment]
Exactly!
To be specific, when i try to set it to public, in the settings it says the map is already set to public. But when I save that, it stays private and inaccessible to anyone but me.

**Comment by iamromeo** [comment]
The interface will not be updated at this point but your maps is now set to public
