### ISSUE TITLE
Autolink broken on Safari

### ISSUE THREAD

**Issue by phd20** [worldanvil/worldanvil-bug-tracker#998]
**World Anvil Username**: phd20

**World Title**: Prime

**Feature**: Autolink

**Describe the Issue**
Autolink appears to be broken in Safari. Clicking the Autolink button causes no UI change. It's working fine in Chrome.

**To Reproduce**
1. Open the full editor for any article in Safari.
2. Click on Autolink for the content section.
3. Open the browser's console.
4. See error: `Unhandled Promise Rejection: SyntaxError: Invalid regular expression: invalid group specifier name`

**Expected behavior**
The auto link modal would open to continue the workflow.

**Comment by iamromeo** [comment]
Hey Kirk, that is sadly true, this is an issue we were not able to fix so far and it has to do with how our current UI Framework (Bootstrap) handles it - We are aware of this and it will be corrected on the next iteration with a completely new modal system.
