### ISSUE TITLE
Unchecking "Display this map on the World's homepage" is not stored in map settings

### ISSUE THREAD

**Issue by mate-code** [worldanvil/worldanvil-bug-tracker#999]
**World Anvil Username**: StoryTellerGM

**World / Campaign / RPG Character / Manuscript Title**: Örnland

**Feature**: Maps

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/world/map/9721fcad-fb82-47e0-84f9-b8e0d4f123b2/edit

**Describe the Issue**
If I uncheck "Display this map on the World's homepage." and save, the changes don't seem to be saved

**To Reproduce**
1. Go to Maps -> Edit Map -> Map Settings -> Display and Privacy
2. Uncheck "Display this map on the World's homepage."
3. Click "save map"
4. Checkbox remains checked, the map is still visible on my worlds homepage

**Expected behavior**
Unchecking "Display this map on the World's homepage." should save and the map is no longer visible on my homepage

**Comment by Kordishal** [comment]
Hi, the functionality works fine on my end. Does this happen in all your maps or just one in particular? Does it happen if you create a new map? Can you save other changes to the settings and the map in general?

**Comment by mate-code** [comment]
I currently have two maps, this happens in both of them. 
When I create a new map, it happens, too. 
I can save other changes as usual.
My browser is Google Chrome Version 100.0.4896.127

**Comment by iamromeo** [comment]
Freemen do not have access to visiblity configuration sadly. This is the issue here.

**Comment by mate-code** [comment]
> Freemen do not have access to visiblity configuration sadly. This is the issue here.

Then the option should either not be displayed or marked as a feature that is not included in the current payment plan. Imo no reason to close the issue, the user should get some feedback.
